### ISSUE TITLE
segmentation fault on sites based on osnova

### ISSUE THREAD

**Issue by IWannaBeTheKappa** [qutebrowser/qutebrowser#5508] opened 2020-06-09 07:49 UTC
**Version info**:
qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Does the bug happen if you start with `--temp-basedir`?**:
No
**Description**
Opening dtf.ru or vs.ru or tjournal.ru cause segmentation fault
**How to reproduce**
Open https://dtf.ru or https://vs.ru or https://tjournal.ru with :open or directly as argument from terminal.

Disabling adblock doesn't affect.

**Comment by The-Compiler** [comment] 2020-06-09 08:44
Do the crashes go away if you remove `~/.local/share/qutebrowser/webengine/Service Worker` (or whatever the data directory is in `:version`)?

**Comment by IWannaBeTheKappa** [comment] 2020-06-09 13:32
When `~/.local/share/qutebrowser/webengine/Service Worker` is removed everything is working fine but after restarting the browser it crashes again.

**Comment by The-Compiler** [comment] 2020-06-09 13:34
I suspect this is a duplicate of #5279 then. What OS/distribution are you on?

Also, if you run `qutebrowser --basedir /tmp/serviceworker https://dtf.ru https://vs.ru https://tjournal.ru`, wait a bit, quit qutebrowser, and run that again - do you get a crash too?

**Comment by IWannaBeTheKappa** [comment] 2020-06-10 01:12
Yes, looks like a duplicate, sorry.

Yes, it is crashing with basedir in /tmp even if you just reload page.

I am on Manjaro 20.0.3, Linux 5.4.43-1
```
Platform plugin: xcb
OpenGL: X.Org, 3.1 Mesa 20.0.7
Platform: Linux-5.4.43-1-MANJARO-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Manjaro Linux (manjaro)
```
And also I cheched it on Windows 10 and it is works fine.

**Comment by The-Compiler** [comment] 2020-06-15 14:30
Hmm, so you're saying even if you just reload one of those pages without restarting qutebrowser (and without having visited it previously, e.g. via `--temp-basedir`), you get a crash as well?

**Comment by The-Compiler** [comment] 2020-06-24 07:55
I'm assuming this is indeed a duplicate of #5279.

**Closed by The-Compiler** 2020-06-24 07:55 UTC
Labels: bug: segfault/crash/hang, component: QtWebEngine, qt: 5.14, status: can't reproduce, status: needs triage
