### ISSUE TITLE
Typing in Google Maps input keeps going back to normal mode

### ISSUE THREAD

**Issue by rr-** [qutebrowser/qutebrowser#4044] opened 2018-07-06 17:28 UTC
Problem:

1. Go to https://maps.google.com
2. Start typing whatever in "Search Google Maps" box here:

![20180706_192325_jff](https://user-images.githubusercontent.com/1045476/42392136-1599d478-8152-11e8-9e4b-1f7dea6098f6.png)

3. Keep typing
4. Notice how the browser suddenly goes back to normal mode mid-typing
5. …continuing their momentum your fingers keep typing (but now in normal mode) and that causes random stuff to happen

Workaround:

I can type each letter slowly and go back to insert mode if the mode resets to normal.

Version:

```
qutebrowser v1.3.2
Git commit: 3399f2df9 (2018-06-17 21:03:44 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.4
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.17.2-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/rr-/.cache/qutebrowser
config: /home/rr-/.config/qutebrowser
data: /home/rr-/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```

**Comment by The-Compiler** [comment] 2018-07-06 17:29
Duplicate of #3596

**Closed by The-Compiler** 2018-07-06 17:29 UTC

**Comment by rr-** [comment] 2018-07-06 17:31
Oh, sorry.
