### ISSUE TITLE
Keychain password manager integration

### ISSUE THREAD

**Issue by sandersantema** [qutebrowser/qutebrowser#3035] opened 2017-09-27 13:12 UTC
Hey there, 

First off thank you to all the contributors for making such an awesome browser.  

I was planning to use Qutebrowser as my main browser on Mac OS however there is no keychain integration (The default password manager on Mac OS) this is quite a big deal breaker for me. I use keychain to sync passwords between my devices, it's fast and as far as I know quite secure as long as you protect your iCloud well. 

Would it be possible to integrate [this](https://github.com/jaraco/keyring) python library in Qutebrowser to provide integration with Mac OS keychain and others like: Freedesktop Secret Service, KWallet and Windows Credential Locker? 

I would like to do this myself but I don't know how to program, I'm planning on learning Python and maybe Swift, Go or Rust in the future but I'm currently very buzzy with school. The time I spend on this kind of stuff currently goes to improving my workflow for school stuff like learning vim to make notes faster and LaTeX to make beautiful papers among others. However if this is easy to integrate or if a newbie like me could help (great!) I would really like to hear about it. 

Anyways, thanks a lot if you're looking in to this. 

Greetings, Sander.

**Comment by The-Compiler** [comment] 2017-09-27 13:19
Duplicate of #180 
Also see #30 - this is probably going to be a plugin rather than a built-in functionality at some point.

**Closed by The-Compiler** 2017-09-27 13:19 UTC

**Comment by sandersantema** [comment] 2017-09-27 13:33
Thanks for your answer. Is there a roadmap for this plugin or a vague idea when this will be implemented? The password fill-plugin isn't compatible with the Mac OS keychain right?
