### ISSUE TITLE
Sometimes some tab just failed to scroll with `j` `k` etc keys after loading some pages unless use `gC` to clone into new tab

### ISSUE THREAD

**Issue by amalgame21** [qutebrowser/qutebrowser#8391] opened 2024-11-22 17:44 UTC
**Description**
Sometime when I am browsing in a tab, for example youtube, after browsing into several webpage, the j, k ctrl+f, ctrl+b, ctrl+u, ctrl+d just stop working. In this case I can still scroll with the mouse though.
When I press `gC` to clone the current page in new tab, I can then use the j,k,etc keys to scroll on the page in the new tab, but still cannot scroll with j,k,etc on old tab. 

This symptom exists for more than one year. I just use `gC` as a workaround.
It just happen randomly and I do not know how to debug it.

**Comment by The-Compiler** [comment] 2024-11-22 17:53
There's a reason the issue template asks for your version information...

When this happens, does `f` also show that an "unknown error occurred"? Can you look at the `:devtools` console and see if there are any errors there?

**Comment by amalgame21** [comment] 2024-11-24 09:09
Yes `f` shows `unknown error while getting elements`
versions:
```
qutebrowser v3.2.1
Git commit: 
Backend: QtWebEngine 6.7.2
  based on Chromium 118.0.5993.220
  with security patches up to 125.0.6422.142 (plus any distribution patches)
  (source: api)
Qt: 6.7.2

CPython: 3.11.10
PyQt: 6.7.0.dev2404081550

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.4
pygments: 2.17.2
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.7.12
pdf.js: 4.2.67 
sqlite: 3.45.3
QtNetwork SSL: OpenSSL 3.0.14 4 Jun 2024

```

**Comment by The-Compiler** [comment] 2024-11-24 11:18
Assuming this is a duplicate of #8197 - not much qutebrowser can do about it unfortunately.

**Closed by The-Compiler** 2024-11-24 11:18 UTC
Labels: status: can't reproduce, status: needs triage
