### ISSUE TITLE
Autofill/qute-pass support for Authentication Prompts

### ISSUE THREAD

**Issue by Holzhaus** [qutebrowser/qutebrowser#5879] opened 2020-11-09 17:30 UTC
qute-pass works great for HTML login forms, but it doesn't work for authentication prompts (e.g. when the website uses HTTP Auth). It would be great if these prompts could also be autofilled by qute-pass.

**Comment by The-Compiler** [comment] 2020-11-10 15:25
This is mostly a duplicate of #3871 - note that at the moment support for that wouldn't be possible, for reasons mentioned there.

**Closed by The-Compiler** 2020-11-10 15:25 UTC
