### ISSUE TITLE
Qutebrowser fails to redirect to another page.

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#6133] opened 2021-02-04 23:54 UTC
**Version info**:

qutebrowser v1.14.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2
More version info: https://paste.the-compiler.org/view/63db99a6

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**

Some webpages aren't redirecting to another page, they just go to the page you are currently on.

**How to reproduce**
Go to [http://therange.co.uk/](http://therange.co.uk) and submit the CAPTCHA. It just refreshes the page.
Also same issue with [https://gitlab.com/users/sign_in](https://gitlab.com/users/sign_in), it says it will automatically redirect in 5 seconds (no need to fill out a CAPTCHA), but the page just refreshes.

**Comment by The-Compiler** [comment] 2021-02-05 09:33
No issues here. Can you try with another browser based on QtWebEngine, such as KDE Falkon?

**Comment by pkillnine** [comment] 2021-02-05 11:52
I don't have another browser using QtWebengine packaged, however I tested with the qtwebkit backend and it didn't have this issue, it successfully went to the next page, so I guess it's some issue with QtWebengine. Maybe it will be fixed on the next QtWebengine release when it is built on a newer version of Chromium.

**Comment by The-Compiler** [comment] 2021-02-05 13:35
Closing this then, as I can't reproduce and I doubt there is anything qutebrowser can do about it.

**Closed by The-Compiler** 2021-02-05 13:35 UTC
Labels: status: can't reproduce, status: needs triage
