### ISSUE TITLE
using minus as hint character makes hint pass as option

### ISSUE THREAD

**Issue by ivomac** [qutebrowser/qutebrowser#4841] opened 2019-06-10 17:20 UTC
**[Version info](https://paste.the-compiler.org/view/0bb94ef1)**

**Description**
hints of the form -(letter) get passed as option arguments and generate the error:

`
follow-hint: unrecognized argument: -(letter)
`

**How to reproduce**
add - to hints.chars
use any -(letter) hint

**Comment by user202729** [comment] 2019-06-11 08:56
Similar to #4368 .

**Comment by The-Compiler** [comment] 2020-04-14 18:33
Closing this as a duplicate of #4368 - also see #2017.

**Closed by The-Compiler** 2020-04-14 18:33 UTC
