### ISSUE TITLE
Screen goes white while focusing to a different monitor

### ISSUE THREAD

**Issue by JonathanReeve** [qutebrowser/qutebrowser#5288] opened 2020-03-15 03:12 UTC
**Version info**:

https://paste.the-compiler.org/view/77e709d4

**Does the bug happen if you start with `--temp-basedir`?**:

Yes. 

**Description**

When I run Qutebrowser in GNOME with the PaperWM extension, switching to a window on a different monitor causes the Qutebrowser window to go white. Switching back to any window on Qutebrowser's monitor restores the page. Qutebrowser is the only program I've seen that behaves like this. Although this could also be [a problem with PaperWM](https://github.com/paperwm/PaperWM/issues/270). 

**How to reproduce**

Use Qutebrowser on PaperWM with two monitors. Focus a window on a different monitor from Qutebrowser. Notice that Qutebrowser no longer displays the webpage, but just a white screen.

**Comment by The-Compiler** [comment] 2020-03-15 07:37
Could you please check whether you can reproduce the same issue with KDE falkon?

**Comment by olejorgenb** [comment] 2020-03-15 10:09
I can reproduce the behavior on gnome-shell 3.35.92 **without** paperwm: Minimize a qutebrowser window and open the overview or alt-tab. The window preview is white. (ref: https://github.com/paperwm/PaperWM/issues/270#issuecomment-5991898

**Comment by olejorgenb** [comment] 2020-03-15 13:52
Happens with falkon also (gnome-shell 3.35.92 (X11), falkon 3.1.0)

![image](https://user-images.githubusercontent.com/72201/76702714-5e51c480-66cc-11ea-85c9-2817372ea9a8.png)

Same as with qutebrowser - the web content is blank, while the chrome "survives".

**Comment by AckslD** [comment] 2020-03-23 09:01
I'm having the same issue (using paperwm)

**Comment by The-Compiler** [comment] 2020-06-24 09:06
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself (if this is still reproducible with Qt 5.15)? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2020-06-24 09:06 UTC
Labels: status: needs triage

**Comment by aaronrancsik** [comment] 2021-04-24 08:45
Hi,
I still have this. 
I commented upstream:  ￼﻿​ ￼﻿​https://bugreports.qt.io/browse/QTBUG-51815?jql=project%20%3D%20QTBUG%20AND%20component%20%3D%20WebEngine%20AND%20text%20~%20%22workspace%22

**Comment by The-Compiler** [comment] 2021-04-24 08:53
@aaronrancsik Do you use Intel graphics with `xf86-video-intel` installed by any chance? If so, [consider uninstalling it](https://wiki.archlinux.org/index.php/intel_graphics#Installation) (see the "note" box there) to use the modesetting driver instead.

**Comment by aaronrancsik** [comment] 2021-04-24 09:43
Thanks for the idea! 
I have an optimus laptop and I use [optimus-switch-gdm](https://github.com/dglt1/optimus-switch-gdm) so I made some experimenting. 

# The results:
 :x: = bug is presents
## Xorg
### Installed: xf86-video-intel 
| _ |     optimus-switch Intel config   | optimus-switch  Nvidia config     |
| ------------- |:-------------:| -----:|
| BIOS Hybrid ON Nvidia and Intel     |  :x: |  :x: |
| BIOS Hybrid OFF  Nvidia only     |  can't start GDM | :x:  |

### Not installed: xf86-video-intel 
| _ |     optimus-switch Intel config   | optimus-switch  Nvidia config     |
| ------------- |:-------------:| -----:|
| BIOS Hybrid ON Nvidia and Intel    |  can't start GDM |  :x: |
| BIOS Hybrid OFF  Nvidia only     |  can't start GDM  | :x:  |

## Wayland
### Installed: xf86-video-intel 
| _ |     optimus-switch Intel config   |
| ------------- |:-------------:| 
| BIOS Hybrid ON Nvidia and Intel     |  :x: |

**Comment by The-Compiler** [comment] 2021-04-24 12:40
Thanks for the detailed reply! No idea then I'm afraid. You might want to play around with the `qt.force_software_rendering` setting (requires a restart) to see if that helps in any way.

**Comment by aaronrancsik** [comment] 2021-04-24 14:27
Unfortunately it did't solved it. Anyway, thanks for the stunning support :) I'm impressed. I guess, I can live with that bug and hope that some day it's just magically gone  :) Thanks again!
