### ISSUE TITLE
QtWebEngine renderer process crashes on certain sites (status 6)

### ISSUE THREAD

**Issue by pfirestone** [qutebrowser/qutebrowser#7429] opened 2022-10-10 16:00 UTC
Reproduce:
Open one of the following sites:
http://thecodelesscode.com/names/
http://www.thecodelesscode.com/names/Hwídah
http://thecodelesscode.com/names/Banzen
etc.
http://code.qt.io/
https://code.qt.io/cgit/
https://code.qt.io/cgit/qt/qtwebengine.git/
etc.
https://cgit.freedesktop.org/systemd/systemd/tree/NEWS?id=2d1ca11270e66777c90a449096203afebc37ec9c#n262
(but https://cgit.freedesktop.org/systemd/systemd/tree/NEWS?id=2d1ca11270e66777c90a449096203afebc37ec9c#n263 works!)
[more examples to be gathered].

Result: 
![error](https://user-images.githubusercontent.com/52336150/194901651-b45ea038-13fc-47b9-a47b-6f190a41a503.png)

Does anybody else have this problem? Looking at the stack trace, I think that this is a MacOS-specific issue; it may be that this is a bug for QtWebEngine and not qutebrowser, but I'd like to gather some more information. Can people on other OSes reproduce this? 

Weirdly, http://thecodelesscode.com/ is fine, as are the pages beginning http://thecodelesscode.com/case/; but it seems that none of the pages beginning http://thecodelesscode.com/names/[...] work — I only tested a few at random, not all of them.

Here is the relevant section of the error log produced by running `qutebrowser -T http://thecodelesscode.com/names`:

> 2022-10-09 22:15:54.262 QtWebEngineProcess[39837:119781430] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
> *** First throw call stack:
> (
> 	0   CoreFoundation                      0x00007ff80e2f5e9b __exceptionPreprocess + 242
> 	1   libobjc.A.dylib                     0x00007ff80e057e48 objc_exception_throw + 48
> 	2   CoreFoundation                      0x00007ff80e3b169b _CFThrowFormattedException + 194
> 	3   CoreFoundation                      0x00007ff80e3bbfe1 -[__NSPlaceholderDictionary initWithCapacity:].cold.1 + 0
> 	4   CoreFoundation                      0x00007ff80e206452 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 251
> 	5   CoreFoundation                      0x00007ff80e20633d +[NSDictionary dictionaryWithObjects:forKeys:count:] + 49
> 	6   AppKit                              0x00007ff8112e4474 __NSSearchFieldCellGetSymbolImageDict_block_invoke + 6109
> 	7   libdispatch.dylib                   0x00007ff80dffe317 _dispatch_client_callout + 8
> 	8   libdispatch.dylib                   0x00007ff80dfff4fa _dispatch_once_callout + 20
> 	9   AppKit                              0x00007ff8112e2829 NSSearchFieldCellGetSearchImage + 652
> 	10  AppKit                              0x00007ff810cdcaee -[NSSearchFieldCell(NSSearchFieldCell_Local) _adjustSearchButtonCellImages::] + 244
> 	11  AppKit                              0x00007ff810cdc8a6 -[NSSearchFieldCell resetSearchButtonCell] + 192
> 	12  AppKit                              0x00007ff810cdc2ce -[NSSearchFieldCell initTextCell:] + 130
> 	13  QtWebEngineCore                     0x00000001214c33a6 _ZNK5blink14LayoutThemeMac6SearchEv + 70
> 	14  QtWebEngineCore                     0x0000000121669a70 _ZN5blink15ThemePainterMac16PaintSearchFieldEPKNS_4NodeERKNS_13ComputedStyleERKNS_9PaintInfoERKNS_7IntRectE + 240
> 	15  QtWebEngineCore                     0x00000001215bcb50 _ZN5blink10BoxPainter36PaintBoxDecorationBackgroundWithRectERKNS_9PaintInfoERKNS_12PhysicalRectERKNS_17DisplayItemClientE + 1024
> 	16  QtWebEngineCore                     0x00000001215bc581 _ZN5blink10BoxPainter28PaintBoxDecorationBackgroundERKNS_9PaintInfoERKNS_14PhysicalOffsetE + 529
> 	17  QtWebEngineCore                     0x000000012134d745 _ZNK5blink9LayoutBox28PaintBoxDecorationBackgroundERKNS_9PaintInfoERKNS_14PhysicalOffsetE + 21
> 	18  QtWebEngineCore                     0x00000001215b5ddc _ZN5blink12BlockPainter11PaintObjectERKNS_9PaintInfoERKNS_14PhysicalOffsetE + 188
> 	19  QtWebEngineCore                     0x000000012131e455 _ZNK5blink11LayoutBlock11PaintObjectERKNS_9PaintInfoERKNS_14PhysicalOffsetE + 21
> 	20  QtWebEngineCore                     0x00000001215b57d1 _ZN5blink12BlockPainter5PaintERKNS_9PaintInfoE + 1169
> 	21  QtWebEngineCore                     0x000000012165d5f0 _ZN5blink28TextControlSingleLinePainter5PaintERKNS_9PaintInfoE + 48
> 	22  QtWebEngineCore                     0x00000001213e3bd5 _ZNK5blink27LayoutTextControlSingleLine5PaintERKNS_9PaintInfoE + 21
> 	23  QtWebEngineCore                     0x000000012160cc8a _ZN5blink13ObjectPainter24PaintAllPhasesAtomicallyERKNS_9PaintInfoE + 138
> 	24  QtWebEngineCore                     0x00000001215f8be0 _ZN5blink20NGBoxFragmentPainter22PaintAtomicInlineChildERKNS_15NGPaintFragmentERKNS_9PaintInfoE + 496
> 	25  QtWebEngineCore                     0x00000001215f6678 _ZN5blink20NGBoxFragmentPainter19PaintInlineChildrenENS_15NGPaintFragment4ListINS1_19TraverseNextSiblingEEERKNS_9PaintInfoERKNS_14PhysicalOffsetE + 408
> 	26  QtWebEngineCore                     0x00000001215f50d3 _ZN5blink20NGBoxFragmentPainter11PaintObjectERKNS_9PaintInfoERKNS_14PhysicalOffsetEb + 1315
> 	27  QtWebEngineCore                     0x00000001215ff2c9 _ZN5blink26NGInlineBoxFragmentPainter5PaintERKNS_9PaintInfoERKNS_14PhysicalOffsetE + 729
> 	28  QtWebEngineCore                     0x00000001215f669b _ZN5blink20NGBoxFragmentPainter19PaintInlineChildrenENS_15NGPaintFragment4ListINS1_19TraverseNextSiblingEEERKNS_9PaintInfoERKNS_14PhysicalOffsetE + 443
> 	29  QtWebEngineCore                     0x00000001215f70b4 _ZN5blink20NGBoxFragmentPainter20PaintLineBoxChildrenEPNS_14NGInlineCursorERKNS_9PaintInfoERKNS_14PhysicalOffsetE + 628
> 	30  QtWebEngineCore                     0x00000001215f6499 _ZN5blink20NGBoxFragmentPainter22PaintBlockFlowContentsERKNS_9PaintInfoERKNS_14PhysicalOffsetE + 505
> 	31  QtWebEngineCore                     0x00000001215f4ea9 _ZN5blink20NGBoxFragmentPainter11PaintObjectERKNS_9PaintInfoERKNS_14PhysicalOffsetEb + 761
> 	32  QtWebEngineCore                     0x00000001215f4885 _ZN5blink20NGBoxFragmentPainter13PaintInternalERKNS_9PaintInfoE + 773
> 	33  QtWebEngineCore                     0x000000012146192d _ZNK5blink22LayoutNGBlockFlowMixinINS_15LayoutBlockFlowEE5PaintERKNS_9PaintInfoE + 813
> 	34  QtWebEngineCore                     0x0000000121622aea _ZN5blink17PaintLayerPainter22PaintFragmentWithPhaseENS_10PaintPhaseERKNS_18PaintLayerFragmentERNS_15GraphicsContextERKNS_8ClipRectERKNS_22PaintLayerPaintingInfoEj + 986
> 	35  QtWebEngineCore                     0x0000000121622241 _ZN5blink17PaintLayerPainter27PaintForegroundForFragmentsERKN3WTF6VectorINS_18PaintLayerFragmentELj1ENS1_18PartitionAllocatorEEERNS_15GraphicsContextERKNS_22PaintLayerPaintingInfoEj + 753
> 	36  QtWebEngineCore                     0x0000000121620c0c _ZN5blink17PaintLayerPainter18PaintLayerContentsERNS_15GraphicsContextERKNS_22PaintLayerPaintingInfoEj + 2956
> 	37  QtWebEngineCore                     0x000000012162003c _ZN5blink17PaintLayerPainter5PaintERNS_15GraphicsContextERKNS_22PaintLayerPaintingInfoEj + 652
> 	38  QtWebEngineCore                     0x0000000121621d94 _ZN5blink17PaintLayerPainter13PaintChildrenENS_19PaintLayerIterationERNS_15GraphicsContextERKNS_22PaintLayerPaintingInfoEj + 292
> 	39  QtWebEngineCore                     0x0000000121620d7d _ZN5blink17PaintLayerPainter18PaintLayerContentsERNS_15GraphicsContextERKNS_22PaintLayerPaintingInfoEj + 3325
> 	40  QtWebEngineCore                     0x000000012162003c _ZN5blink17PaintLayerPainter5PaintERNS_15GraphicsContextERKNS_22PaintLayerPaintingInfoEj + 652
> 	41  QtWebEngineCore                     0x0000000121621d94 _ZN5blink17PaintLayerPainter13PaintChildrenENS_19PaintLayerIterationERNS_15GraphicsContextERKNS_22PaintLayerPaintingInfoEj + 292
> 	42  QtWebEngineCore                     0x0000000121620d7d _ZN5blink17PaintLayerPainter18PaintLayerContentsERNS_15GraphicsContextERKNS_22PaintLayerPaintingInfoEj + 3325
> 	43  QtWebEngineCore                     0x00000001215cc892 _ZNK5blink22CompositedLayerMapping11DoPaintTaskERKNS_22GraphicsLayerPaintInfoERKNS_13GraphicsLayerEjRNS_15GraphicsContextERKNS_7IntRectE + 930
> 	44  QtWebEngineCore                     0x00000001215cd6b5 _ZNK5blink22CompositedLayerMapping13PaintContentsEPKNS_13GraphicsLayerERNS_15GraphicsContextEjRKNS_7IntRectE + 757
> 	45  QtWebEngineCore                     0x0000000120904226 _ZN5blink13GraphicsLayer18PaintWithoutCommitEPKNS_7IntRectE + 598
> 	46  QtWebEngineCore                     0x0000000120903add _ZN5blink13GraphicsLayer5PaintEv + 45
> 	47  QtWebEngineCore                     0x00000001209039a0 _ZN5blink13GraphicsLayer24PaintRecursivelyInternalERN3WTF6VectorIPS0_Lj0ENS1_18PartitionAllocatorEEE + 64
> 	48  QtWebEngineCore                     0x00000001209039fb _ZN5blink13GraphicsLayer24PaintRecursivelyInternalERN3WTF6VectorIPS0_Lj0ENS1_18PartitionAllocatorEEE + 155
> 	49  QtWebEngineCore                     0x00000001209039fb _ZN5blink13GraphicsLayer24PaintRecursivelyInternalERN3WTF6VectorIPS0_Lj0ENS1_18PartitionAllocatorEEE + 155
> 	50  QtWebEngineCore                     0x0000000120903881 _ZN5blink13GraphicsLayer16PaintRecursivelyEv + 33
> 	51  QtWebEngineCore                     0x0000000120fce039 _ZN5blink14LocalFrameView9PaintTreeEv + 297
> 	52  QtWebEngineCore                     0x0000000120fcd053 _ZN5blink14LocalFrameView22RunPaintLifecyclePhaseEv + 99
> 	53  QtWebEngineCore                     0x0000000120fcc75d _ZN5blink14LocalFrameView29UpdateLifecyclePhasesInternalENS_17DocumentLifecycle14LifecycleStateE + 765
> 	54  QtWebEngineCore                     0x0000000120fcb99c _ZN5blink14LocalFrameView21UpdateLifecyclePhasesENS_17DocumentLifecycle14LifecycleStateENS_20DocumentUpdateReasonE + 316
> 	55  QtWebEngineCore                     0x00000001215804e0 _ZN5blink12PageAnimator24UpdateAllLifecyclePhasesERNS_10LocalFrameENS_20DocumentUpdateReasonE + 32
> 	56  QtWebEngineCore                     0x0000000120f31857 _ZN5blink11WebViewImpl15UpdateLifecycleENS_18WebLifecycleUpdateENS_20DocumentUpdateReasonE + 231
> 	57  QtWebEngineCore                     0x00000001209cf021 _ZN5blink10WidgetBase17UpdateVisualStateEv + 49
> 	58  QtWebEngineCore                     0x000000011fa0d9fb _ZN2cc13LayerTreeHost22RequestMainFrameUpdateEb + 27
> 	59  QtWebEngineCore                     0x000000011fa51900 _ZN2cc9ProxyMain14BeginMainFrameENSt3__110unique_ptrINS_28BeginMainFrameAndCommitStateENS1_14default_deleteIS3_EEEE + 912
> 	60  QtWebEngineCore                     0x000000011fa5d825 _ZN4base8internal13FunctorTraitsIMN2cc9ProxyMainEFvNSt3__110unique_ptrINS2_28BeginMainFrameAndCommitStateENS4_14default_deleteIS6_EEEEEvE6InvokeISB_NS_7WeakPtrIS3_EEJS9_EEEvT_OT0_DpOT1_ + 85
> 	61  QtWebEngineCore                     0x000000011e678d6f _ZN4base13TaskAnnotator7RunTaskEPKcPNS_11PendingTaskE + 255
> 	62  QtWebEngineCore                     0x000000011e68d096 _ZN4base16sequence_manager8internal35ThreadControllerWithMessagePumpImpl10DoWorkImplEPNS0_7LazyNowEPb + 374
> 	63  QtWebEngineCore                     0x000000011e68ce04 _ZN4base16sequence_manager8internal35ThreadControllerWithMessagePumpImpl6DoWorkEv + 132
> 	64  QtWebEngineCore                     0x000000011e710881 ___ZN4base24MessagePumpCFRunLoopBase13RunWorkSourceEPv_block_invoke + 49
> 	65  QtWebEngineCore                     0x000000011e5f621a _ZN4base3mac15CallWithEHFrameEU13block_pointerFvvE + 10
> 	66  QtWebEngineCore                     0x000000011e70fedf _ZN4base24MessagePumpCFRunLoopBase13RunWorkSourceEPv + 63
> 	67  CoreFoundation                      0x00007ff80e27b35a __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
> 	68  CoreFoundation                      0x00007ff80e27b2c2 __CFRunLoopDoSource0 + 180
> 	69  CoreFoundation                      0x00007ff80e27b040 __CFRunLoopDoSources0 + 242
> 	70  CoreFoundation                      0x00007ff80e279a50 __CFRunLoopRun + 892
> 	71  CoreFoundation                      0x00007ff80e279014 CFRunLoopRunSpecific + 562
> 	72  Foundation                          0x00007ff80f00dd4a -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 216
> 	73  QtWebEngineCore                     0x000000011e7110de _ZN4base20MessagePumpNSRunLoop5DoRunEPNS_11MessagePump8DelegateE + 126
> 	74  QtWebEngineCore                     0x000000011e70f822 _ZN4base24MessagePumpCFRunLoopBase3RunEPNS_11MessagePump8DelegateE + 130
> 	75  QtWebEngineCore                     0x000000011e68d62b _ZN4base16sequence_manager8internal35ThreadControllerWithMessagePumpImpl3RunEbNS_9TimeDeltaE + 139
> 	76  QtWebEngineCore                     0x000000011e6517cb _ZN4base7RunLoop3RunEv + 395
> 	77  QtWebEngineCore                     0x00000001221d3e47 _ZN7content12RendererMainERKNS_18MainFunctionParamsE + 839
> 	78  QtWebEngineCore                     0x000000011e08fbc3 _ZN7content21ContentMainRunnerImpl3RunEb + 259
> 	79  QtWebEngineCore                     0x0000000122368bfc _ZN15service_manager4MainERKNS_10MainParamsE + 2796
> 	80  QtWebEngineCore                     0x000000011e08f054 _ZN7content11ContentMainERKNS_17ContentMainParamsE + 68
> 	81  QtWebEngineCore                     0x000000011bc38c4a _ZN15QtWebEngineCore11processMainEiPPKc + 186
> 	82  QtWebEngineProcess                  0x0000000104996ee7 main + 167
> 	83  dyld                                0x00000002049d852e start + 462
> 	84  dyld                                0x00000002049d3000 dyld + 0
> )
> libc++abi: terminating with uncaught exception of type NSException
> 22:15:54 ERROR: Renderer process crashed (status 6)

There are also several warnings of the form 

> objc[96775]: Class QMacAutoReleasePoolTracker is implemented in both /Applications/qutebrowser.app/Contents/MacOS/QtCore (0x115863198) and /Applications/qutebrowser.app/Contents/Resources/PyQt5/Qt5/lib/QtCore.framework/Versions/5/QtCore (0x10f8a8198). One of the two will be used. Which one is undefined.

in the error log, but they appear in any event, even when the crash isn't produced. They may, nevertheless, be relevant.

Here are details about my version of qutebrowser:

> qutebrowser v2.5.2
> Git commit: 951a14a66 on HEAD (2022-06-22 15:30:51 +0200)
> Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
> Qt: 5.15.2
> 
> CPython: 3.10.4
> PyQt: 5.15.6
> 
> sip: 6.5.1
> colorama: 0.4.4
> jinja2: 3.1.1
> pygments: 2.11.2
> yaml: 6.0
> adblock: 0.5.2
> PyQt5.QtWebEngineWidgets: yes
> PyQt5.QtWebEngine: 5.15.5
> PyQt5.QtWebKitWidgets: no
> pdf.js: 2.14.305 (bundled)
> sqlite: 3.33.0
> QtNetwork SSL: Secure Transport, macOS 10.16
> 
> Style: QMacStyle
> Platform plugin: cocoa
> OpenGL: None
> Platform: macOS-10.16-x86_64-i386-64bit, 64bit
> Frozen: True
> Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
> Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
> Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt5/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt5
> OS Version: 10.16, x86_64

The full log produced by :report is attached.

[[debug.log](https://github.com/qutebrowser/qutebrowser/files/9747063/debug.log)](url)

**Comment by toofar** [comment] 2022-10-10 20:06
A few questions:
1. Did you try reproducing with a temp basedir? It mentions something about styles in the stack trace so it might be specific to your config?
2. I would suggest trying with falkon too but I'm not sure that has builds for mac
3. Did this just start happening recently? If so did anything else change?
4. If you feel like trying a Qt6 build from the [nightly jobs](https://github.com/qutebrowser/qutebrowser/actions/workflows/nightly.yml) that would be interesting. Although please note that you should probably run that with a temp/separate basedir because otherwise rolling back to Qt5 will lose your webengine browser state (cookies, visited links)

**Comment by The-Compiler** [comment] 2022-11-22 10:35
Another report of this, when opening https://cppreference.com:

https://crashes.qutebrowser.org/view/db02fb7d

Doubt there is much we can do, but it'd be good if someone could test with Qt 6 too. @pfirestone did you get around to doing that in the meantime?

**Comment by krobelus** [comment] 2022-11-23 20:29
> Another report of this, when opening https://cppreference.com/:

Yeah, I hit this consistently on macos but it's fixed by the Qt6 build :)

**Comment by The-Compiler** [comment] 2022-11-23 20:35
Assuming this is fixed upstream in Qt 6 then.

**Closed by The-Compiler** 2022-11-23 20:35 UTC
Labels: priority: 2 - low, component: QtWebEngine, os: macOS, bug: segfault/crash/hang
