### ISSUE TITLE
feat: vim like normal / visual mode in text forms

### ISSUE THREAD

**Issue by midirhee12** [qutebrowser/qutebrowser#8362] opened 2024-10-30 18:21 UTC
It would be nice if you could use vim like movement from even within text forms.

**Comment by The-Compiler** [comment] 2024-10-30 19:01
Duplicate of #827

**Comment by The-Compiler** [comment] 2024-10-30 19:02
Also note that you can already spawn vim (or another editor of your choice) with ctrl-e too.

**Closed by The-Compiler** 2024-10-30 19:01 UTC

**Comment by midirhee12** [comment] 2024-10-30 20:08
WOOPs. Sorry! My bad. I should have searched the issues more thoroughly
