### ISSUE TITLE
Broken tab history title test on WebKit

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4811] opened 2019-05-27 14:14 UTC
```
____________________________________ test_titles[1-item1] _____________________________________

objects = Objects(history=<PyQt5.QtWebKit.QWebHistory object at 0x7f059bf9f978>, user_data=[None, None, {'foo': 23, 'bar': 42}, {'zoom': 149, 'scroll-pos': PyQt5.QtCore.QPoint()}, {'zoom': 120, 'scroll-pos': PyQt5.QtCore.QPoint()}])
i = 1
item = qutebrowser.misc.sessions.TabHistoryItem(active=True, original_url=PyQt5.QtCore.QUrl('http://example.com/…'), title='percent', url=PyQt5.QtCore.QUrl('http://example.com/…'), user_data=None)

    @pytest.mark.parametrize('i, item', enumerate(ITEMS))
    def test_titles(objects, i, item):
        """Check if the titles were loaded correctly."""
>       assert objects.history.itemAt(i).title() == item.title
E       AssertionError: assert 'Network access is disabled' == 'percent'
E         - Network access is disabled
E         + percent

tests/unit/browser/webkit/test_tabhistory.py:118: AssertionError

tests/unit/browser/webkit/test_tabhistory.py ......                                     [100%]

=================================== short test summary info ===================================
FAILED tests/unit/browser/webkit/test_tabhistory.py::test_titles[1-item1] - AssertionError: ...
```

Not sure why that started failing. Also it looks like QtWebKit actually does some network requests here? That shouldn't happen in the tests... Maybe they should use the HTTP server on localhost if that's really the case.

**Comment by toofar** [comment] 2019-05-29 07:56
Hmm, I tried running in an empty net namespace (sudo netns add foo; sudo netns exec foo bash; su user) and all five of the `test_title` tests passed. Debian sid Qt5.11.

**Comment by toofar** [comment] 2019-06-01 02:04
This was working on [May 23rd](https://travis-ci.org/qutebrowser/qutebrowser/builds/535930270) and not working on [the 24th](https://travis-ci.org/qutebrowser/qutebrowser/builds/536654143). It is working in an arch chroot for with qt5-webkit version `5.212.0alpha2-29`, but failing in docker with version `5.212.0alpha2+156+g95401fe3908-1` running on the same qutebrowser commit. That package was [updated](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/qt5-webkit&id=bf0f5ee7177524a801b4641e0bf9242a6953c4a8) on the 21st to "latest git as per upstream recommendation". So that's why it started failing then.

> it looks like QtWebKit actually does some network requests here? 

The [lazier loading](https://github.com/qutebrowser/qutebrowser/pull/4037/) PR depends on the behaviour that a tab will start loading if you deserialize a history item marked as active into its history. Why it wasn't failing before though I don't know because that PR works as intended on the older package.

**Closed** 2019-06-03 07:29 UTC
Labels: bug: behavior, component: QtWebKit, component: tests, priority: 1 - middle
