### ISSUE TITLE
Rapid Hinting for Yank Target

### ISSUE THREAD

**Issue by NoSuck** [qutebrowser/qutebrowser#3174] opened 2017-10-20 19:59 UTC
The error message says it "makes no sense", but any program that has a clipboard monitoring feature begs to differ!  Rapid yanking would be useful for loading links in a download manager (JDownloader 2, for example) without having to resort to `userscript` or `spawn`.  Users could also make quick URL lists using clipboard managers (parcellite, etc).

Please reconsider.

**Comment by The-Compiler** [comment] 2017-10-20 20:00
Duplicate of #521

See https://github.com/qutebrowser/qutebrowser/issues/521#issuecomment-120906916

**Closed by The-Compiler** 2017-10-20 20:00 UTC

**Comment by NoSuck** [comment] 2017-10-20 21:27
Thank you.  I saw that issue while searching but overlooked it on account of the title only mentioning modes.
