### ISSUE TITLE
Feature request: allow native file picker for saving files

### ISSUE THREAD

**Issue by tidux** [qutebrowser/qutebrowser#5342] opened 2020-04-08 19:49 UTC
Qutebrowser's prompt menu for choosing a location for a saved file chokes and hangs on directories with thousands of files in them, locking up the entire browser for seconds at a time.  It would be nice to be able to use the OS native file chooser for downloads as well as uploads to avoid this problem, or keep current behavior, depending on configuration values.

**Comment by The-Compiler** [comment] 2020-04-08 19:55
Duplicate of #1365

**Closed by The-Compiler** 2020-04-08 19:55 UTC
