### ISSUE TITLE
shuffle through hints by tabs

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#5710] opened 2020-09-10 16:15 UTC
when i press `f`, i get links hinted. when i type some words, i get hints reduced to those with words in it (nice).

this feature is about: for the list of available hinted links, it would be nice if i can just shuffle through them by pressing tab.

e.g. say that i pressed `f`, and got 100 hints.  then i typed a few letters, and reduced the hints down to 5 hints. in order to choose the hint that i want, it would be nice if i can chose it by simply shuffling through them by hitting tabs.  so every time i press tab, a hint gets highlighted in succession, until i reach the last hint (5th in this case), then if i press tab again, it goes to the 1st, and so on.  finally, if i can click the hint by pressing enter.

advantage: in many cases hints overlap, or consequences of mis-choosing a hint is major (e.g. delete vs. save an item.  order vs. cancel order.  activate doomsday machine vs. disarm nukes.  etc).  therefore it's nice to choose these hints by tabs, with visual hint (e.g. hint highlighted) before we finally press "enter" to actually click it.

because, currently, imagine that putin is using qutebrowser to navigate throughout his doomsday machine, and wants to choose "disarm nukes" which has hint (say) `09` but he accidentally hits `08` which is the link for `yup, start doomsday at full blast`?  not nice.  but if qutebrowser has this hint selection by tabs,  mr. putin can at least press just `0` to limit the hints list, then shuffle through them by tab, and only press enter when the right one is selected.

**Comment by The-Compiler** [comment] 2020-09-10 16:25
Duplicate of #1305

**Closed by The-Compiler** 2020-09-10 16:25 UTC
