### ISSUE TITLE
Cannot type correctly when using certain input method in certain sites

### ISSUE THREAD

**Issue by OmeletWithoutEgg** [qutebrowser/qutebrowser#7176] opened 2022-05-12 04:56 UTC
**Version info**:
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.6.1
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.12.0
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: 2.13.216 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.38.5
QtNetwork SSL: OpenSSL 1.1.1o  3 May 2022

Style: Breeze::Style
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.0.3
Platform: Linux-5.17.5-arch1-2-x86_64-with-glibc2.35, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/qqbx/.cache/qutebrowser
config: /home/qqbx/.config/qutebrowser
data: /home/qqbx/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/qqbx/.config/qutebrowser/config.py has been loaded
Uptime: 0:16:03

**Does the bug happen if you start with `--temp-basedir`?**:
No.
edit: YES. (I misunderstood this question.)

**Description**
When typing non-latin language using the input method, the first several characters cannot be type correctly.
I guess it is something about composition events.
https://stackoverflow.com/questions/51226598/what-is-javascripts-compositionevent-please-give-examples

I've tried fcitx chewing, fcitx mozc, ibus chewing, ibus anthy. All of them will fail like this:
https://imgur.com/a/NoG2cxT
When I want to type "da re", it splits into "d a re".

When I use the google-chrome browser it's all good.

**How to reproduce**
Use qutebrowser to view these sites:
- https://www.facebook.com/
- https://www.messenger.com/

And then use an input method (e.g. IBus, fcitx) to type something in any text field (e.g. comments).

**Comment by The-Compiler** [comment] 2022-05-12 08:00
Huh, so it works correctly when you start with `--temp-basedir`? If that's really the case, can you show your `:config-diff`?

**Comment by OmeletWithoutEgg** [comment] 2022-05-12 17:07
Oh sorry I misunderstand it.
The bug does happen when I start with `--temp-basedir`.

**Comment by The-Compiler** [comment] 2022-05-12 17:20
Can you please try with another browser using Qt 5 and QtWebEngine, such as KDE Falkon?

**Comment by OmeletWithoutEgg** [comment] 2022-05-13 02:30
It works incorrectly in KDE Falkon. So it's a Qt problem?

**Comment by The-Compiler** [comment] 2022-05-13 09:21
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can easily reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

Note that there's work undergoing at the moment to switch to Qt 6 with a newer QtWebEngine version, where this problem might already be fixed too. You can test the `qt6-v2` branch to confirm, see the [instructions](https://github.com/qutebrowser/qutebrowser/issues/5395#issuecomment-1120213898) for details.

**Closed by The-Compiler** 2022-05-13 09:21 UTC
Labels: status: needs triage
