### ISSUE TITLE
HTML characters in phrase break search

### ISSUE THREAD

**Issue by yogo1212** [qutebrowser/qutebrowser#2532] opened 2017-04-16 09:24 UTC
E.g. a search for `this envir` won't find `this&nbsp;environment&nbsp;question`

```
qutebrowser v0.10.1
Git commit: 
Backend: QtWebKit

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
```

**Comment by The-Compiler** [comment] 2017-04-16 09:27
You mean with that rendered as HTML, right? Works fine for me.

**Comment by yogo1212** [comment] 2017-04-16 14:22
hmm. you're right. my conclusion was bad.

this is where a noticed a problem:
`/` for `I will elaborate on this envi` on http://all-things-andy-gavin.com/2011/09/11/video-game-programmer-method/.
`I will elaborate on this ` works. But when another character is added, no results are found.
` will elaborate on this e` also works. But prefixing it with an `I`, it won't match.

**Comment by The-Compiler** [comment] 2017-04-16 14:43
Looks like it's because non-breaking spaces do not match when searching case-sensitively. When doing `:set general ignore-case false` it's reproducible with your example as well.

This seems like a WebKit/Chromium or QtWebKit/QtWebEngine bug to me though - I'll find out who's to blame and open an upstream bug when I find the time.

**Comment by yogo1212** [comment] 2017-04-19 21:43
thank you :-)

**Comment by The-Compiler** [comment] 2017-05-01 06:12
From what it looks, Chromium just [uses ICU](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/core/editing/iterators/TextSearcherICU.cpp?l=156&rcl=3c689934871ad2f934d37938b67e7a3fb2b65987) for the search. I wonder if it reproduces when doing the same thing Chromium does by hand...

**Comment by The-Compiler** [comment] 2017-05-01 06:42
So I found ICU's `strsrch` example in `icu/icu4c/source/samples/strsrch` and it reproduces there:

```
$ ./strsrch -level 1 -source 'foo\u00a0bar' -pattern 'o b'
Warning, U_USING_DEFAULT_WARNING for en_US
Finding pattern o b in source foo\u00a0bar
Pattern found at offset 2 size 3
End of search
```

```
$ ./strsrch -level 3 -source 'foo\u00a0bar' -pattern 'o b'
Warning, U_USING_DEFAULT_WARNING for en_US
Finding pattern o b in source foo\u00a0bar
Pattern not found in source
End of search
```

See [this explanation](http://userguide.icu-project.org/collation/concepts#TOC-Comparison-Levels) for the different levels - Chromium uses primary for case-insensitive search, and tertiary for case-insensitive.

Looks like there's no way to tell ICU "normalize whitespace, but not case differences", so I don't think there's an easy way to fix this in QtWebEngine or Chromium - so I'm closing this.

**Closed by The-Compiler** 2017-05-01 06:42 UTC
Labels: priority: 2 - low, qt
