### ISSUE TITLE
Certain things appear in multiple windows

### ISSUE THREAD

**Issue by willruggiano** [qutebrowser/qutebrowser#8156] opened 2024-04-04 20:14 UTC
**Version info**:
```
qutebrowser v3.1.0
Git commit: 
Backend: QtWebEngine 6.6.3, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.3
```

also

```
nixos: 24.05.20240329.807c549 (Uakari)
nvidia: 550.67
hyprland: 0.38.0
```

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
Certain things (e.g. commands) trigger e.g. popups that appear in all qutebrowser windows.

**How to reproduce**
- `:set-cmd-text foo` will show a deprecation warning and error in all windows (screenshots 1)
- `:macro-record a` will show the "Recording macro..." popup in all windows (screenshot 2)

![screenshot-2024-04-04T13:55:23-06:00](https://github.com/qutebrowser/qutebrowser/assets/11872440/99d10525-e62a-4127-aea2-9b8bdd9967fe)

![screenshot-2024-04-04T14:13:19-06:00](https://github.com/qutebrowser/qutebrowser/assets/11872440/3558670b-f9a5-42b6-9f60-b8686c4d14ea)

**Comment by The-Compiler** [comment] 2024-04-04 20:27
Duplicate of #4018

**Closed** 2024-04-04 20:27 UTC

**Comment by willruggiano** [comment] 2024-04-04 20:51
Thanks, not sure how that didn't show up in my search :/
