### ISSUE TITLE
Question about embedded videos

### ISSUE THREAD

**Issue by ManuGraiph** [qutebrowser/qutebrowser#7443] opened 2022-10-20 15:00 UTC
For some reason, the videos on twitter can't be played in qutebrowser. All of them say 'The media could not be played'.

I'm on windows.

**Comment by The-Compiler** [comment] 2022-10-20 15:01
Duplicate of #7019 (and others) - also, please use discussions for support, not issues.

**Closed by The-Compiler** 2022-10-20 15:01 UTC
