### ISSUE TITLE
Typing a command in the statusbar sometimes results in the typed characters appearing out of order

### ISSUE THREAD

**Issue by jansheikkinen** [qutebrowser/qutebrowser#7943] opened 2023-09-26 19:34 UTC
**Version info**:

```
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.11.5
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.2
pygments: no
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: no
sqlite: 3.43.1
QtNetwork SSL: OpenSSL 3.1.3 19 Sep 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.1.8-arch1.1
Platform: Linux-6.5.2-zen1-1-zen-x86_64-with-glibc2.38, 64bit
Linux distribution: Artix Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6
```

**Description**
When typing commands in the status bar (i.e. `:open <search query>`), the typed characters may appear out of order. I'm *pretty* sure this happens specifically when there're a lot of suggestions for the autocomplete, such as bookmarks or history in the case of `:open`, since these queries tend to lag pretty bad. I think this issue is in part due to the fact that I have a very low-end computer.
I initially thought this was just user error, but I'm generally a pretty accurate typist, and this issue neither occurs anywhere else on the system, nor even anywhere else within the browser itself, so I figured it was worth a report.

**Does the bug happen if you start with `--temp-basedir`?**:
Yes, though it is harder to reproduce due to the lack of a massive number of autocomplete results.

**How to reproduce**

Just type a command into the statusbar that has a lot of autocomplete suggestions. I notice it most with `:open`, since I never clear my history.
It also helps if you use a low-end computer and have something intensive running like a game or compilation.

Though please do note that this is just my best guess as to the cause based on the circumstances in which I notice it occur naturally. I'm not actually 100% sure if this truly is how to reproduce it, since it occurs very sporadically.

**Comment by The-Compiler** [comment] 2023-09-26 20:00
Duplicate of #1874

**Closed by The-Compiler** 2023-09-26 20:00 UTC
