### ISSUE TITLE
Sending commands to a running Qutebrowser instance causes the window to take focus

### ISSUE THREAD

**Issue by lrustand** [qutebrowser/qutebrowser#8300] opened 2024-09-09 18:04 UTC
**Version info**:

         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v3.1.0
Git commit: 
Backend: QtWebEngine 6.6.3, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.3

**Does the bug happen if you start with `--temp-basedir`?**:
I would assume so

**Description**
When running `qutebrowser :some-commmand` to run a command in an already running Qutebrowser instance, the browser window steals the focus, even when the command has no reason to focus the window. For example setting a variable.

**How to reproduce**

Have one or more qb windows open, send whatever command to it from a shell somewhere. The qb window is now focused.

**Comment by The-Compiler** [comment] 2024-09-09 18:18
Duplicate of #5094

**Closed by The-Compiler** 2024-09-09 18:18 UTC
