### ISSUE TITLE
Tab freezes when scrolling a store page

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#8018] opened 2023-12-05 04:04 UTC
**Version info**:

```
qutebrowser v3.0.2
Git commit: 
Backend: QtWebEngine 6.6, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.0
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

On some sites scrolling the site suddenly results in the tab being freezed. Refreshing the page doesn't help, it just won't do anything.

**How to reproduce**

1. Go to https://market.yandex.ru/search?cvredirect=0&text=glasses&rs=eJwzamEOYCxgPMrIcCDXFkgqSO8FkgnrbYDkgxoQeeDiHiDJ0AYWSQGxD6wGi5iARRStgaSDEYjdcGI3iPQEyT4IApl24CSInXAELNu1HcSOALEVFoJUKiSCTRMGqWzYDzKHoQIk4hADUuNwHWyaOIidsABEMnwDkwfB9lbtB-lVB-l1mA5SyXAXJL5gPtgES5D4g3lgu15A_AISSagEySqYgmXBtjT8sQKpdwabLAL2bwtY3A3s_jdgvRG7QHpPg9V8AMvygN3PC1YjA3atDDjcboB88eAU2JxikF0LasFu6IG4HBxuP8Em3AG7NgMcPvttAHbgidk%2C&allowCollapsing=1&local-offers-first=0
2. Pick the scrollbar with mouse and scroll down to where the link to the next page is located
3. Click the next page
4. Do 1…3 3 or 4 times *(it's usually reproduced pretty fast)*, till the tab just freezes and you're not able to do anything

**Additional information**

Screencast demonstrating the issue: https://youtu.be/1-tWi1PBt54

**Comment by The-Compiler** [comment] 2023-12-05 10:24
Thanks for the detailed report! Unfortunately I can't reproduce because the page just gives me a 403 and doesn't load as soon as I click the next button.

Could you try to reproduce with the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py)?

**Comment by Hi-Angel** [comment] 2023-12-05 11:06
> Could you try to reproduce with the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py)?

Reproduced. During the navigation I see appearing from time to time messages:

```
js: ResizeObserver loop limit exceeded
js: ResizeObserver loop limit exceeded
js: ResizeObserver loop limit exceeded
js: ResizeObserver loop limit exceeded
js: ResizeObserver loop limit exceeded
js: ResizeObserver loop limit exceeded
js: ResizeObserver loop limit exceeded
js: ResizeObserver loop limit exceeded
js: ResizeObserver loop limit exceeded
js: ResizeObserver loop limit exceeded
[…]
````

When the freeze happens, nothing new appears in the logs.

**Comment by The-Compiler** [comment] 2023-12-05 11:56
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can easily reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2023-12-05 11:56 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by Hi-Angel** [comment] 2023-12-05 13:54
[Done](https://bugreports.qt.io/browse/QTBUG-119733) C:
