### ISSUE TITLE
Scrolling position lost on window switch with Qt 5.13

### ISSUE THREAD

**Issue by jpalus** [qutebrowser/qutebrowser#4869] opened 2019-06-25 20:16 UTC
qutebrowser: 1.6.3
Qt: 5.13
OS: Linux (X11)

Steps to reproduce:
1. Open some page and scroll to the bottom
2. Focus different window
3. Go back to to qutebrowser

Expected: scroll position is maintained
Actual: page is usually scrolled to the top

It looks like on each refocus of qutebrowser next URL on page is highlighted (starting from the top) and page is scrolled so that link is visible. Each time it is different link so position page is scrolled to changes as well. Reproducible ie on https://github.com/qutebrowser/qutebrowser/issues/ notice how links are highlighted one after the other.

**Comment by jgkamat** [comment] 2019-06-25 21:17
I'm unable to test 5.13 at the minute, but are you able to reproduce the same 
issue in kde falkon or other qtwebengine browsers?

**Comment by jpalus** [comment] 2019-06-25 21:59
Indeed same behavior is observed in otter-browser with QtWebEngine backend.

**Comment by toofar** [comment] 2019-06-26 07:08
Does it lose position the same way that pressing Tab does? If so it could be this issue: https://github.com/qutebrowser/qutebrowser/issues/4579

**Comment by jpalus** [comment] 2019-06-26 12:20
Yes that's the same issue, I can also see Tab presses on https://w3c.github.io/uievents/tools/key-event-viewer.html.

Feel free to resolve as duplicate.

**Comment by The-Compiler** [comment] 2019-06-26 18:53
Duplicate of #4579

**Closed by The-Compiler** 2019-06-26 18:53 UTC
Labels: qt: 5.13
