### ISSUE TITLE
There was an error while getting hint elements

### ISSUE THREAD

**Issue by edi9999** [qutebrowser/qutebrowser#2735] opened 2017-06-17 19:14 UTC
This seems to happen on all sites since today : 

my commit id is : a5db21abe92eedab13dfefb44a3ccd5ebc3699ee

**Comment by The-Compiler** [comment] 2017-06-17 19:49
Did you update without restarting?

**Comment by The-Compiler** [comment] 2017-06-19 07:22
Closing this for now, as I'm pretty sure that was the issue - let me know if that didn't fix it!

**Closed by The-Compiler** 2017-06-19 07:22 UTC

**Comment by edi9999** [comment] 2017-06-19 17:18
Yes, it is working now indeed

**Comment by MasterSergius** [comment] 2018-02-06 09:21
Facing this issue with few sites, for example - yaplakal.ru

**Comment by The-Compiler** [comment] 2018-02-06 12:15
@MasterSergius Works fine here. Can you please open a new issue with more details and version information?

**Comment by MasterSergius** [comment] 2018-02-07 08:54
After 2 min loading it began to work, next time couldn't reproduce this bug. So, it's hard to describe in details
