### ISSUE TITLE
qute://log adds a new level of html escaped characters every time

### ISSUE THREAD

**Issue by lufte** [qutebrowser/qutebrowser#4137] opened 2018-08-17 03:56 UTC
Every time you visit qute://log, the log messages are HTML-escaped but the result is saved on the log entry. Next time you visit the page, the previous escaped message will be re-escaped, eventually resulting in something like `&amp;amp;amp;amp;...`.

How to reproduce:

1. Run the following command: `spawn --userscript somenotexistentuserscript`
2. Visit qute://log?level=info.
3. Refresh the page a couple of times.

I'm sending a pull request along with this issue.

```
qutebrowser v1.4.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.6
Qt: 5.10.1
PyQt: 5.11.2

sip: 4.19.12
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.17.0-1-amd64-x86_64-with-debian-buster-sid, 64bit
Linux distribution: Debian GNU/Linux buster/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/xavi/.cache/qutebrowser
config: /home/xavi/.config/qutebrowser
data: /home/xavi/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 8 days, 9:20:12
```

**Comment by The-Compiler** [comment] 2018-08-17 06:25
Duplicate of #2537

**Comment by The-Compiler** [comment] 2018-08-17 06:26
To be fair, #2537 is almost impossible to find - took me a while, but I knew it was somewhere :laughing:

**Closed by The-Compiler** 2018-08-17 06:25 UTC
