### ISSUE TITLE
confirm_quit prompts pops up on all windows

### ISSUE THREAD

**Issue by LamprosPitsillos** [qutebrowser/qutebrowser#6875] opened 2021-12-09 23:23 UTC
**Version info**:
```
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.9
PyQt: 5.15.6

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.10.0
yaml: 6.0
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.11.338 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.37.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021
```
**Does the bug happen if you start with `--temp-basedir`?**:
No, since `c.confirm_quit = ["always"]` is not set.
**Description**

https://user-images.githubusercontent.com/61395246/145490952-1e65093e-694e-4214-91d2-006c6cb1a556.mp4

Trying to kill a window prompts me for confirmation on all the windows,instead of the one i chose to kill.

**How to reproduce**
Open qutebrowser
Set  `c.confirm_quit = ["always"]`
Open a couple of windows
Try killing one from your environments key-binds.

**Comment by The-Compiler** [comment] 2021-12-10 09:11
Duplicate of #5535

**Closed by The-Compiler** 2021-12-10 09:11 UTC
