### ISSUE TITLE
Show tabs when opening new tab

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#5882] opened 2020-11-10 16:30 UTC
Hey, i feel like tabs should be shown (if you use "show tabs on switching") whenever you open a new tab, even if it is in the background. It often feels unsatisfying to use "F" to open tabs in the background because you dont get feedback on wether it went through or not. 

btw love your porject! I hope to be able to contribute soon!

**Comment by The-Compiler** [comment] 2020-11-10 16:35
Closing this as a duplicate of #3084, since this is mentioned in there already as well.

**Closed by The-Compiler** 2020-11-10 16:35 UTC
