### ISSUE TITLE
Downloading the same filename simoutaneously ends up overwritten

### ISSUE THREAD

**Issue by freed00m** [qutebrowser/qutebrowser#5300] opened 2020-03-20 13:37 UTC
**Version info**: qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

CPython: 3.8.2
PyQt: 5.14.1

sip: 5.1.1
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.1
pygments: 2.6.1
yaml: 5.3
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1e  17 Mar 2020

Style: Qt5CTProxyStyle
Platform: Linux-5.6.0-1-MANJARO-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/frdm/.cache/qutebrowser
config: /home/frdm/.config/qutebrowser
data: /home/frdm/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/frdm/.config/qutebrowser/config.py has been loaded
Uptime: 4:53:00

https://paste.the-compiler.org/view/cd66c516

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

Downloading file with the same name won't propmt filecheck if the conflicting file is being downloaded.

Can result in files being overridden.

Would it be possible to extend file check for the file and its *.download counterpart when handling conflicts.

**How to reproduce**

1.) Start downloading file A called "videoplayback", in a prompt use /tmp.
The temporary file is `/tmp/videoplayback.download"

2.) Start downloading file B called "videoplayback" while the first download is still progress and chose /tmp in a file prompt.
The temporary file is `/tmp/videoplayback (1).download`

Note that no file conflict prompt raised as `videoplayback` file does not yet exists

3.) The file A finishes and is at `/tmp/videoplayback`

4.) The file B finishes and overrites file A at `/tmp/videoplayback` when user would expect `/tmp/videoplayback (1)` 

Could the file B retain the numbering, or the prompt check if the *.download file is there as well?

**Comment by The-Compiler** [comment] 2020-03-20 13:39
Duplicate of #3966

**Closed by The-Compiler** 2020-03-20 13:39 UTC
