### ISSUE TITLE
[webengine] mouse 'stays' on screen hidden after a hint click

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#2265] opened 2017-01-31 04:31 UTC
This is a little easier to explain in video form, so here's one: https://www.youtube.com/watch?v=syr7hgPx7kI&feature=youtu.be

Essentially, when a link is clicked with `f`, the mouse seems to move there, and interacts with the page, regardless of where the mouse actually is. Ideally, there would be no interaction at all in this case. Refreshing the page returns the expected behavior.

Steps to reproduce

1. Click a link
2. Go back in history to previous page (the page where you clicked the tab)
3. Move up or down

Or

1. Click a link (open in a new tab)
2. Go back to previous tab
3. Move up or down.

This is only a problem with the webengine backend (I think).
```
qutebrowser v0.9.1
Git commit: 

CPython: 3.4.5
Qt: 5.7.1
PyQt: 5.7.1

sip: 4.19
colorama: 0.3.3
pypeg2: 2.15
jinja2: 2.9.4
pygments: 2.1.3
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: no
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.4.39-gentoo-x86_64-Intel-R-_Core-TM-_i7-6700HQ_CPU_@_2.60GHz-with-gentoo-2.3, 64bit
Frozen: False
Imported from /usr/lib64/python3.4/site-packages/qutebrowser
OS Version: 

--- /etc/lsb-release ---
DISTRIB_ID="Gentoo"

--- /etc/os-release ---
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"

--- /etc/gentoo-release ---
Gentoo Base System release 2.3

Paths:
system_data: /home/jay/.local/share/qutebrowser
download: /home/jay/Downloads
cache: /home/jay/.cache/qutebrowser
runtime: /run/user/1000/qutebrowser
config: /home/jay/.config/qutebrowser
data: /home/jay/.local/share/qutebrowser
```

**Comment by pkill-nine** [comment] 2017-01-31 05:11
another way of testing it is on a youtube video, do `:hint all hover` and select a name in the comments, the profile card should popup, then scroll down with `j` and other profile cards will popup in the same spot if their name/pic resides in the same area.

**Comment by The-Compiler** [comment] 2017-01-31 08:02
I think it's an issue with QtWebKit as well, and I don't know if there's anything we can do about this.

**Comment by lahwaacz** [comment] 2017-01-31 08:23
It is worth mentioning that the _real_ cursor is not moved, only the backend acts as if it moved. That is the result of the simulated clicks, which consist of a sequence of `QEvent.MouseMove`, `QEvent.MouseButtonPress` and `QEvent.MouseButtonRelease` events at given position. One solution might be to add another `MouseMove` event to move the virtual cursor out of the way, e.g. like this:
```diff
--- a/qutebrowser/browser/webelem.py
+++ b/qutebrowser/browser/webelem.py
@@ -331,6 +331,7 @@ class AbstractWebElement(collections.abc.MutableMapping):
         self._tab.data.override_target = click_target
 
         pos = self._mouse_pos()
+        origin = type(pos)(0, 0)
 
         log.webelem.debug("Sending fake click to {!r} at position {} with "
                           "target {}".format(self, pos, click_target))
@@ -353,6 +354,8 @@ class AbstractWebElement(collections.abc.MutableMapping):
                         Qt.LeftButton, modifiers[click_target]),
             QMouseEvent(QEvent.MouseButtonRelease, pos, Qt.LeftButton,
                         Qt.NoButton, modifiers[click_target]),
+            QMouseEvent(QEvent.MouseMove, origin, Qt.NoButton, Qt.NoButton,
+                        Qt.NoModifier),
         ]
 
         for evt in events:
```

**Comment by jgkamat** [comment] 2017-01-31 17:04
If it would be possible to make a mouse event that says 'the mouse has left the window' that might be better (but I'm not sure if that's possible). 

Maybe there's a way to store the state of the mouse and restore it after the click has been made?

**Comment by jgkamat** [comment] 2017-02-10 22:06
I'm not able to reproduce this on master now (probaby 545539f28d86c162f0e7f803480ad7fe24b6870f)! :smile: 

There could be more specific cases that weren't fixed, but this works for me. Can I go ahead and close this @The-Compiler?

**Comment by The-Compiler** [comment] 2017-02-11 19:53
Things like `;h` (hovering) or clicking on unknown elements are still affected, so I'd like to keep it open for now (though with the wishlist priority :wink:)

**Comment by The-Compiler** [comment] 2017-03-27 08:29
This is actually a duplicate of #1197.

**Closed by The-Compiler** 2017-03-27 08:29 UTC
Labels: component: hints, priority: 3 - wishlist
