### ISSUE TITLE
Hangs when opening a dropdown (i.e. `<select>`) while qutebrowser is on a secondary monitor

### ISSUE THREAD

**Issue by motevets** [qutebrowser/qutebrowser#6074] opened 2021-01-27 19:42 UTC
**Version info**:
qutebrowser v1.14.1
Git commit: b38420862-dirty on v1.14.x (2020-12-04 21:15:50 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
More Windows (10) shenanigans. :wink:

When opening a dropdown (i.e. `<select>`) while qutebrowser is on a secondary monitor, qutebrowser hangs. Trying to interact further with the windows leads to the typical Windows non-responsive app behaviour. I.e. graying out the window, putting "(Not responding)" in the title bar, and eventually prompting to forcefully end the process.

It seems that any `<select>` tag can trigger the bug, and I've attached a very simple page which reproduces the problem. I have attached logs from the debug build that you recently supplied for another issue where I also ran `debug-pyeval -q __import__("faulthandler").dump_traceback_later(20)` before clicking on the dropdown.

**How to reproduce**
1. open qutebrowser
1. move window to secondardy display
1. go to site with a `<select>` input element
1. click on select element.

[qute_dropdown_crash2.log](https://github.com/qutebrowser/qutebrowser/files/5882614/qute_dropdown_crash2.log)

[short_dropdown.html](https://github.com/qutebrowser/qutebrowser/files/5882621/short_dropdown.html.txt)

![dropdown_crash](https://user-images.githubusercontent.com/777773/106044449-beb3df80-60ad-11eb-9554-4aa16fd645ff.png)

**Comment by The-Compiler** [comment] 2021-01-27 19:49
Can you check whether this is reproducible with [KDE Falkon](https://www.falkon.org/) as well?

**Comment by motevets** [comment] 2021-01-27 21:33
Indeed, it reporduces on KDE Falkon on Windows.

**Comment by The-Compiler** [comment] 2021-02-24 09:36
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here - I've tried getting a VM with multiple screens up and running, but VirtualBox seems to crash once I try to display the second screen.

Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Maybe also first try if you can still reproduce it with qutebrowser v2.0.x.

If you report a bug upstream about this, please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2021-02-24 09:36 UTC
Labels: bug: segfault/crash/hang, os: Windows, status: needs triage
