### ISSUE TITLE
Ability to ignore prompts for X minutes

### ISSUE THREAD

**Issue by mcastorina** [qutebrowser/qutebrowser#6433] opened 2021-04-28 04:18 UTC
Misbehaving sites can prevent using qutebrowser by spamming notifications, keeping the browser in "prompt mode". The only way out is to kill qutebrowser and lose all tabs / windows.

Here's a simple example of a misbehaving page that could cause this.
```html
<script>
    while (true) { alert('hi') }
</script>
```

I think it would be a good idea to add an option that would ignore the same notification for X minutes, or allow colon commands in "prompt mode".

**Comment by The-Compiler** [comment] 2021-04-28 05:41
Duplicate of #3821

**Closed by The-Compiler** 2021-04-28 05:41 UTC

**Comment by The-Compiler** [comment] 2021-04-28 05:43
As for

> or allow colon commands in "prompt mode".

I thought `:bind --mode=prompt : set-cmd-text -s :` would work, but the next prompt will immediately switch to prompt mode again. You could bind a key to `tab-close` in prompt mode, however.

**Comment by mcastorina** [comment] 2021-04-28 14:05
Thanks for the tip! Binding `tab-close` in prompt mode is a good workaround for me.
