### ISSUE TITLE
readline support in insert mode

### ISSUE THREAD

**Issue by parisni** [qutebrowser/qutebrowser#5854] opened 2020-10-31 21:23 UTC
There is only few shortkeys available in insert mode. (delete word = ctrl+backspace) it would be great to either:
- support readline shortkeys
- allow to define them in the config.py

**Comment by The-Compiler** [comment] 2020-10-31 21:24
Duplicate of #68

**Closed by The-Compiler** 2020-10-31 21:24 UTC

**Comment by parisni** [comment] 2020-10-31 21:38
thanks indeed:
this did the trick:
```
c.bindings.commands = {
    'insert': {
        '<Ctrl-f>'        : 'fake-key <Right>',
        '<Ctrl-b>'        : 'fake-key <Left>',
        '<Ctrl-a>'        : 'fake-key <Home>',
        '<Ctrl-e>'        : 'fake-key <End>',
        '<Ctrl-n>'        : 'fake-key <Down>',
        '<Ctrl-p>'        : 'fake-key <Up>',
        '<Alt-v>'         : 'fake-key <PgUp>',
        '<Ctrl-v>'        : 'fake-key <PgDown>',
        '<Alt-f>'         : 'fake-key <Ctrl-Right>',
        '<Alt-b>'         : 'fake-key <Ctrl-Left>',
        '<Ctrl-d>'        : 'fake-key <Delete>',
        '<Alt-d>'         : 'fake-key <Ctrl-Delete>',
        '<Alt-Backspace>' : 'fake-key <Ctrl-Backspace>',
        '<Ctrl-y>'        : 'insert-text {primary}',
    }
}
```
