### ISSUE TITLE
Faild to write history : datebase is locked 

### ISSUE THREAD

**Issue by xxzozaxx** [qutebrowser/qutebrowser#3278] opened 2017-11-12 21:01 UTC
hi great programmers , really I love this browser alot and I turn it into my defult browser . 

my Issue happen when i open a url of click on anything  , it buffering and compelet then it freaze for 2-3 sec and type : 
> ## Faild to write history : datebas is locked .

**my version and another information** 
qutebrowser v1.0.3
Git commit: 
Backend: new QtWebKit (WebKit 602.1)

CPython: 3.6.2
Qt: 5.7.1
PyQt: 5.8.1

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.2.0
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2j-fips  26 Sep 2016

Style: QFusionStyle
Platform: Linux-4.13.11-200.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six, 64bit
Linux distribution: Fedora 26 (Twenty Six) (fedora)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/Boos/.cache/qutebrowser
config: /home/Boos/.config/qutebrowser
data: /home/Boos/.local/share/qutebrowser
runtime: /run/user/1001/qutebrowser

**Comment by The-Compiler** [comment] 2017-11-12 21:03
Duplicate of #2930

**Closed by The-Compiler** 2017-11-12 21:03 UTC

**Comment by The-Compiler** [comment] 2017-11-12 21:09
If this is happening always (and restarting qutebrowser doesn't help), your history database got into a weird state - we don't really know yet how that happens. If that's the case, one of those might help (make sure to close qutebrowser first):

- If you don't care about your history, remove `~/.local/share/qutebrowser/history.sqlite`
- Try moving the `history.sqlite` file away and moving it back (which apparently helps to clear stale locks according to [this page](http://www.sqlite.org/cvstrac/wiki?p=DatabaseIsLocked))
- If that doesn't help either, do something like `cd ~/.local/share/qutebrowser && mv history.sqlite history.sqlite.bak && echo ".dump" | sqlite3 history.sqlite.bak | sqlite3 history.sqlite`

**Comment by xxzozaxx** [comment] 2017-11-12 21:39
@The-Compiler  
thnx now its work :tada:
