### ISSUE TITLE
Crash on startup after pressing and holding Shift-j

### ISSUE THREAD

**Issue by mondique** [qutebrowser/qutebrowser#5623] opened 2020-07-26 16:03 UTC
**Version info**:

```
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.8
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Qutebrowser crashes on startup. Reinstalling twice helps (but not once).
Message when called from the command line:
```
18:33:50 INFO: Run :adblock-update to get adblock lists.
python3: ../nouveau/pushbuf.c:723: nouveau_pushbuf_data: Assertion `kref' failed.
Aborted (core dumped)
```
or
```
18:44:00 INFO: Run :adblock-update to get adblock lists.
Segmentation fault (core dumped)
```
or
```
18:27:51 INFO: Run :adblock-update to get adblock lists.
nouveau: kernel rejected pushbuf: No such file or directory
nouveau: ch4: krec 0 pushes 0 bufs 1 relocs 0
nouveau: ch4: buf 00000000 00000002 00000004 00000004 00000000
Segmentation fault (core dumped)
```

**How to reproduce**

1. Launch Qutebrowser (`$ qutebrowser`).
2. Press and hold `J` (`Shift-j`).
3. Restart Qutebrowser (close the window in herbstluftwm if Qutebrowser does not crash, then `$ qutebrowser`).

**Comment by The-Compiler** [comment] 2020-07-27 07:34
The nouveau drivers are quite buggy, so I doubt this is an issue in qutebrowser.

I assume this only happens if you have a couple of tabs open, right? Can you try to reproduce the same issue in KDE Falkon by holding Ctrl+Tab there? Also, can you play with the `qt.force_software_rendering` setting and see if any of the values there changes anything? (note they'll need a restart)

**Comment by mondique** [comment] 2020-07-28 09:58
> I assume this only happens if you have a couple of tabs open, right?

Yes

> Can you try to reproduce the same issue in KDE Falkon by holding Ctrl+Tab there?

Turns out this happens in Falkon, too.

> Also, can you play with the `qt.force_software_rendering` setting and see if any of the values there changes anything?

The problem vanishes with any value except for `none`.

**Comment by The-Compiler** [comment] 2020-07-28 11:01
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this isn't the case here as I don't use the Nouveau driver. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2020-07-28 11:01 UTC
Labels: status: can't reproduce, status: needs triage
