### ISSUE TITLE
Segmentation fault when opening https://www.nauticed.org/sailing-simulator

### ISSUE THREAD

**Issue by gmagno** [qutebrowser/qutebrowser#6185] opened 2021-02-19 19:56 UTC
**Version info**:

qutebrowser v2.0.2
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: no
jinja2: 2.11.3
pygments: no
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: 2.7.570 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1j  16 Feb 2021

**Does the bug happen if you start with `--temp-basedir`?**:
No.

**Description**
Opening https://www.nauticed.org/sailing-simulator#instructions crashes the browser.

**How to reproduce**

Run:
```
$ qutebrowser https://www.nauticed.org/sailing-simulator#instructions
fish: “qutebrowser https://www.nautice…” terminated by signal SIGSEGV (Address boundary error)
```

**Comment by gmagno** [comment] 2021-02-19 19:57
There's a chance of being related to: #6183

**Comment by The-Compiler** [comment] 2021-02-21 09:36
Duplicate of #6183

**Closed by The-Compiler** 2021-02-21 09:36 UTC
