### ISSUE TITLE
Text editor makes a phantom content

### ISSUE THREAD

**Issue by Hi-Angel** [qutebrowser/qutebrowser#4047] opened 2018-07-08 19:23 UTC
This problem appears on different sites in different shapes. E.g. on bugzilla.mozilla.org the content in comment, once saved, just plain disappears. Though "phantom content" one is probably the most noticeable and annoying.

## Steps to reproduce

1. Open any page with comments box on gitlab *(e.g. [this one](https://gitlab.freedesktop.org/Hi-Angel/libinput/issues/1))*.
2. Type in comment "foo"
3. Invoke editor, and append "bar"
4. Save content, close editor *(you'll see "foobar" appears, so everything seems to be fine)*, and post the comment.

## Expected

"foobar" content

## Actual

Only "foo", the "bar" part just plain disappears, as if it even wasn't there.
	
	$ qutebrowser --version
	ATTENTION: default value of option vblank_mode overridden by environment.
	qutebrowser v1.3.3
	Git commit: 
	Backend: QtWebEngine (Chromium 65.0.3325.230)

	CPython: 3.6.5
	Qt: 5.11.1
	PyQt: 5.10.1

	sip: 4.19.8
	colorama: 0.3.9
	pypeg2: 2.15
	jinja2: 2.10
	pygments: 2.2.0
	yaml: 3.12
	cssutils: no
	attr: 18.1.0
	PyQt5.QtWebEngineWidgets: yes
	PyQt5.QtWebKitWidgets: yes
	pdf.js: no
	sqlite: 3.24.0
	QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

	Style: Breeze::Style
	Platform: Linux-4.17.2-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
	Linux distribution: Arch Linux (arch)
	Frozen: False
	Imported from /usr/lib/python3.6/site-packages/qutebrowser
	Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

	Paths:
	cache: /home/constantine/.cache/qutebrowser
	config: /home/constantine/.config/qutebrowser
	data: /home/constantine/.local/share/qutebrowser
	runtime: /run/user/1000/qutebrowser
	system data: /usr/share/qutebrowser

	Uptime: 0:00:00

**Comment by The-Compiler** [comment] 2018-07-08 19:45
Duplicate of #3786

**Comment by The-Compiler** [comment] 2018-07-08 19:45
As a workaround, you can type and delete a character via the browser after closing the external editor.

**Closed by The-Compiler** 2018-07-08 19:45 UTC
