### ISSUE TITLE
Hints with two leading semicolons cannot be selected

### ISSUE THREAD

**Issue by UnicodeAlt255** [qutebrowser/qutebrowser#4895] opened 2019-07-05 23:54 UTC
**Version info (see `:version`)**:
```
qutebrowser v1.6.3
Git commit: 4b402de3d (2019-07-05 12:10:00 +0200)
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.12.3

sip: 4.19.17
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/user/.local/share/qutebrowser/user/cache
config: /home/user/.local/share/qutebrowser/user/config
data: /home/user/.local/share/qutebrowser/user/data
runtime: /home/user/.local/share/qutebrowser/user/runtime
system data: /usr/share/qutebrowser

Uptime: 0:02:34
```
**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When `hints.chars = "asdfjkl;"`, hints such as `;;s` cannot be followed.

**How to reproduce**

Go to a website with many links (I was on wikipedia).

Press `f` or equivalent to activate hints.

Try to follow a hint that starts with two semicolons.

Get an error message about there being no such command.

**Comment by toofar** [comment] 2019-07-06 03:33
Hmm, when you match a hint the hint text is passed to the target command (like in the case of `f` it is `follow-hint -s `). That goes through the normal command dispatcher which lets you chain commands with `;;`. We should probably keep using the normal command dispatcher so that we can have hint targets that run chained commands but we should escape the hint text. Except that isn't a thing at the moment. I think that this bug would be covered by https://github.com/qutebrowser/qutebrowser/issues/2017

**Comment by user202729** [comment] 2019-07-06 06:10
Duplicate of #4368.

**Closed** 2019-07-06 08:10 UTC
