### ISSUE TITLE
Closing multiple tabs through tab switch menu closes unexpected tabs

### ISSUE THREAD

**Issue by tausen** [qutebrowser/qutebrowser#4826] opened 2019-06-03 19:32 UTC
**Version info (see `:version`)**: 1.6.2 (06a9c5c4c)

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

When closing multiple tabs using the menu opened with gt (which would be super handy when cleaning up unused open tabs), unexpected tabs are closed.

**How to reproduce**

Open several tabs, e.g.

    o 1 O 2 O 3 O 4

Then close more than one of those tabs via the gt menu, e.g.

    g t <mark tab with title "2 at DuckDuckGo"> ctrl-d <mark tab with title "3 at DuckDuckGo"> ctrl-d ESC

The tabs that are now open are the ones with title "1 at DuckDuckGo" and "3 at DuckDuckGo" instead of the desired "1 at DuckDuckGo" and "4 at DuckDuckGo".

**Comment by The-Compiler** [comment] 2019-06-03 21:30
Duplicate of #2986

**Closed by The-Compiler** 2019-06-03 21:30 UTC
Labels: bug: behavior, component: completion, priority: 1 - middle
