### ISSUE TITLE
After opening a background tab, scrolling happens in the wrong tab.

### ISSUE THREAD

**Issue by parchd-1** [qutebrowser/qutebrowser#2320] opened 2017-02-18 08:27 UTC
When I open a tab in the background using the F binding, and then try to navigate the page with arrows or PgUp/PgDown the current page does not move. By hitting : and then escape it regains focus.

On moving to the newly opened tab, it appears that it has received the arrow keys instead.

### version info
qutebrowser v0.9.1
Git commit: v0.9.0-277-g79d22f250 (2017-02-17 07:02:57 +0100)
Backend: QtWebEngine

**Comment by The-Compiler** [comment] 2017-02-18 10:39
I can't reproduce this. What Qt version are you on? Can you reproduce it with `--temp-basedir`? Does it also happen when middle-/ctrl-clicking links? Can you try on the latest git master (something changed about how hints are opened there)?

**Comment by parchd-1** [comment] 2017-02-18 10:51
I forgot to mention that I have set tabs background-tabs true (I forgot that it wasn't the default).
The problem also exists with the latest git master, and with --temp-basedir.
It does not happen when ctrl-clicking links.

### Updated and more complete version info

qutebrowser v0.9.1
Git commit: v0.9.0-292-g0b94f2ed8 (2017-02-18 00:46:55 +0100)
Backend: QtWebEngine

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.7.1

sip: 4.19
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.9.8-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
OS Version: 

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

**Comment by The-Compiler** [comment] 2017-02-18 11:18
Reproduced now, though scrolling just doesn't happen at all here, not in the other tab either.

**Comment by parchd-1** [comment] 2017-02-18 11:32
Ok. Strange that you don't get scrolling in any tab, I've tested on several websites and concistently do.

**Comment by The-Compiler** [comment] 2017-02-18 11:37
I now do too, no idea why I got different behavior before. Haven't figured out why it happens yet.

**Comment by The-Compiler** [comment] 2017-02-19 21:19
Like with #2321, https://codereview.qt-project.org/#/c/184111/ or https://codereview.qt-project.org/#/c/176113/ might be related.

**Comment by The-Compiler** [comment] 2017-04-08 17:34
Still reproduces with Qt 5.9

**Comment by NoctuaNivalis** [comment] 2017-04-10 08:34
As it isn't mentioned on this issue, yet: when I open a page with `F` and `set tabs background-tabs true`, I can reproduce the problem, but only with the arrow keys. j/k and the scrollwheel all work on the current tab.

**Comment by arza-zara** [comment] 2017-04-10 14:27
So as a workaround you can bind up/down/pgup/pgdown to scroll/scroll-page:
```
bind <up> scroll up
bind <down> scroll down
bind <pgup> scroll-page 0 -1
bind <pgdown> scroll-page 0 +1
```

**Comment by Ape** [comment] 2017-10-18 04:57
Is there a way to focus the currently active tab with a command? I can do that for example by clicking the active tab with mouse, but if there would be a command then I could just bind to always execute that after `:open -b`.

**Comment by The-Compiler** [comment] 2017-10-18 04:59
@Ape From the original post here:

> By hitting : and then escape it regains focus.

FWIW it's already focused as far as qutebrowser is concerned, but there's something with QtWebEngine going wrong there most likely.

**Comment by Ape** [comment] 2017-10-18 05:08
`:` + escape fixes the focus. If that works then there is probably something qutebrowser could do after opening background tabs to workaround this (even if this is really caused by QtWebEngine). This issue is quite annoying and it seems to affect many people (at least the bug has been reported many times).

**Comment by The-Compiler** [comment] 2017-10-18 05:34
I agree there's probably some workaround, but those things are usually quite tricky to fix. This also doesn't affect me personally and has multiple workarounds available. As usual, the best way to get something fixed quickly is to contribute, there is only so much I can take care of every given day ;)

**Comment by abrasive** [comment] 2017-12-29 12:23
This horrible workaround is effective:
```diff
--- qutebrowser/mainwindow/tabbedbrowser.py	2017-12-29 23:21:23.289723961 +1100
+++ qutebrowser/mainwindow/tabbedbrowser.py	2017-12-29 23:21:32.968723672 +1100
@@ -465,6 +465,8 @@
         else:
             self.setCurrentWidget(tab)
 
+        self.currentWidget().setFocus()
+
         tab.show()
         self.new_tab.emit(tab, idx)
         return tab
```

**Comment by Ape** [comment] 2018-01-02 09:08
@abrasive Thanks, it seems to work.

@The-Compiler Is this something you would be willing to merge?

**Comment by The-Compiler** [comment] 2018-01-02 13:46
Doesn't seem too bad to me - I want to look into it some more, but I'm not opposed to that workaround. However, I'm currently busy with exams, so it might be early February until I get to it. @abrasive, mind to open a pull request with the fix so it doesn't get lost?

**Comment by Ape** [comment] 2018-01-25 10:19
Was this fixed? This doesn't seem to occur for me since I upgraded qutebrowser from 1.0 to 1.1.1.

**Comment by The-Compiler** [comment] 2018-01-25 10:46
Doesn't seem to be fixed in qutebrowser, but in Qt 5.10. I can still reproduce it on Qt <= 5.9.

**Comment by Ape** [comment] 2018-05-23 06:10
I am experiencing this again with qutebrowser 1.3.0 and Qt 5.10.1.

**Comment by jgkamat** [comment] 2018-05-23 06:14
@Ape can you try #3906? I think that that PR might close this issue as well, so I'll link it for now.

**Comment by Ape** [comment] 2018-05-23 17:15
@jgkamat Thanks. I tested the pull request and it fixes this issue.

**Closed** 2018-06-14 13:04 UTC
Labels: bug: behavior, component: QtWebEngine, priority: 1 - middle
