### ISSUE TITLE
Cursor is offset somehow 

### ISSUE THREAD

**Issue by 3nt3** [qutebrowser/qutebrowser#7117] opened 2022-04-09 00:36 UTC
**Version info**:
```
Version info
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

CPython: 3.10.4
PyQt: 5.15.6

sip: 6.5.1
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.11.1
yaml: 6.0
adblock: 0.5.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.38.2
QtNetwork SSL: OpenSSL 1.1.1n  15 Mar 2022

Style: Adwaita::Style
Platform plugin: wayland
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.0.0
Platform: Linux-5.17.1-arch1-1-x86_64-with-glibc2.35, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/ente/.cache/qutebrowser
config: /home/ente/.config/qutebrowser
data: /home/ente/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/ente/.config/qutebrowser/config.py has been loaded
Uptime: 0:02:18
Yank pastebin URL for version info
Copyright info
Copyright 2014-2021 Florian Bruhin (The Compiler)

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see https://www.gnu.org/licenses/ or open qute://gpl.
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
In the right part of the website, the mouse cursor does not seem to be at the same location as it is displayed, hover effects happen when the mouse cursor is not actually hovering over the element but is slightly right of it, buttons are only clickable if you move the mouse off to the right of them etc.

Here's a quick video demonstration: https://user-images.githubusercontent.com/39235738/162549380-0f0e775b-a965-4034-9bab-4cd441c8b02c.mp4

And another one: 

https://user-images.githubusercontent.com/39235738/162550500-e6c097b0-73c9-4982-9c49-26b28eefeff0.mp4

**How to reproduce**
Works on most websites but not always, worked on ebay and aliexpress for some time, then not after opening them in a new window(?)

**Comment by The-Compiler** [comment] 2022-04-09 10:49
This sounds like an issue in Qt(WebEngine) rather than qutebrowser, and there's probably nothing qutebrowser can do about it. Could you try the `qt6-test` branch with `--temp-basedir` and see if you can reproduce there?

**Comment by 3nt3** [comment] 2022-04-09 11:39
The issue is there without `--temp-basedir` but not with the argument. Hmm.

**Comment by 3nt3** [comment] 2022-04-09 11:40
Sorry, didn't mean to close

**Comment by The-Compiler** [comment] 2022-04-09 11:51
Well, nothing we can do about it - sounds like it's resolved upstream already and will land once qutebrowser supports Qt 6.

**Comment by 3nt3** [comment] 2022-04-11 15:53
nvm, the issue still happens in `qt6-test` @The-Compiler

**Comment by 3nt3** [comment] 2022-04-13 17:01
could you reopen this issue? @The-Compiler

**Comment by The-Compiler** [comment] 2022-04-13 17:05
Well, probably still not much we can do about it. Could you perhaps test another browser using QtWebEngine for a bit (such as KDE Falkon) and see if it happens there too?

**Comment by 3nt3** [comment] 2022-04-13 17:51
hmm, it does seem to be a QtWebEngine-related issue, I can reproduce it in Falkon as well.

**Comment by The-Compiler** [comment] 2022-04-13 17:51
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2022-04-13 17:51 UTC
Labels: qt, status: can't reproduce, status: needs triage, bug: behavior

**Comment by 3nt3** [comment] 2022-04-13 18:01
https://bugreports.qt.io/browse/QTBUG-102555
