### ISSUE TITLE
Per-website dark mode

### ISSUE THREAD

**Issue by SFR-git** [qutebrowser/qutebrowser#6395] opened 2021-04-17 11:08 UTC
I have set `colors.webpage.preferred_color_scheme` to dark, because some sites don't look very nice with `colors.webpage.darkmode.enabled`. However, I do want to set it on for some sites that look okay with the forced dark mode.

I think there should be a command to toggle dark mode for a website. Considering that enabling dark mode requires a restart, I'm not sure if that's even possible, but I would like to see this if it is.

**Comment by The-Compiler** [comment] 2021-04-17 11:16
Duplicate of #5542

**Closed by The-Compiler** 2021-04-17 11:16 UTC
