### ISSUE TITLE
percent-encoding makes qutebrowser treat a `javascript:` scheme url as a search query

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#3233] opened 2017-11-01 19:49 UTC
qutebrowser v1.0.2
Git commit: 17e0f6d23 (2017-10-27 07:15:25 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

> 19:19 \<opa\> apparently my problem is with about percent-encoding. :open javascript:alert("test") will alert properly. :open javascript:alert("test%20fest") will google the text (with percentencoding intact, weirdly).
> 19:21 \<opa\> it works jseval, if i decode the bookmarklet javascript code first
> 19:22 \<opa\> *it works with :jseval, if the percentencoding is resolved first

**Comment by The-Compiler** [comment] 2017-11-01 19:57
Duplicate of #2429

**Closed by The-Compiler** 2017-11-01 19:57 UTC
