### ISSUE TITLE
(tabs / statusbar).push =   false or true

### ISSUE THREAD

**Issue by RannyArcher** [qutebrowser/qutebrowser#7739] opened 2023-06-11 22:47 UTC
**Fantastic browser**, but could be more fantastic if the way a bar is shown immediatly can be custom.

i'm setting the `statusbar.show` to `in-mode`.
when i go immediatly to the commands mode i see that the a part of web page goes down cause of the status bar.

same thing happen when setting `tabs.show` to `switching`.

that might be annoying for some users, but in case some users like that behavior. u can create new option named push or anything u found logical... and give them a logical values.

love qutebrowser, thanks.

**Comment by The-Compiler** [comment] 2023-06-11 22:51
Duplicate of #1593

**Closed** 2023-06-11 22:51 UTC
