### ISSUE TITLE
Add flag to make search-next act like less

### ISSUE THREAD

**Issue by LiteracyFanatic** [qutebrowser/qutebrowser#5304] opened 2020-03-23 07:21 UTC
When you do a search with `less` it chooses the next candidate based on you current scroll position. I think adding an option for this to `:search-next` and `:search-previous` would be useful for navigating some pages. The scenario I envisage is one where you have a large page with clusters of the search term appearing in groups which are spaced far apart. Basically, it is useful to search for the first occurrence, visually scan any other instances of the term in the immediate vicinity, scroll past the end of the group with the mouse or keybindings, and then jump to the next group with search. It is much quicker to scroll past a block of text where the term appears ten times than it is to hit a key for each instance. Conversely, it is much easier to hit a key once for `:search-next` to jump to the next group than it is to scroll past a long block of unrelated text. Currently `:search-next` will gladly take you visually backwards if you have skipped any of the occurrences by scrolling.

**Comment by arza-zara** [comment] 2020-03-23 11:29
Duplicate of #1222.

**Closed by arza-zara** 2020-03-23 11:29 UTC
