### ISSUE TITLE
The permission request shows at each qutebrowser restart 

### ISSUE THREAD

**Issue by edi9999** [qutebrowser/qutebrowser#4063] opened 2018-07-12 12:12 UTC
Everytime I connect to gmail, I get following permission request : 

![selection_001](https://user-images.githubusercontent.com/2071336/42632483-9d3b04da-85dd-11e8-95f4-d3ae742a74f0.png)

I would expect that if I do yes, at the next restart, this question is no more asked.

How can I do that ?

```
qutebrowser v1.4.1
Git commit: d1a25b6c3-dirty (2018-07-11 17:17:51 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.6.5
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.11
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: 1.0.2 $Id$
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: no
```

**Comment by The-Compiler** [comment] 2018-07-12 12:14
Duplicate of #832

**Closed by The-Compiler** 2018-07-12 12:14 UTC
