### ISSUE TITLE
gitch display of key chain keybindings, it become very narrow and limit the display

### ISSUE THREAD

**Issue by amalgame21** [qutebrowser/qutebrowser#6892] opened 2021-12-14 11:39 UTC
**Version info**:

qutebrowser v2.4.0
Backend: QtWebEngine 5.15.6, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.10.0
PyQt: 5.15.6

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.10.0
yaml: 5.4.1
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.5.207
sqlite: 3.37.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021

Style: Qt5CTProxyStyle
Platform plugin: xcb
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 495.44
Platform: Linux-5.10.83-1-MANJARO-x86_64-with-glibc2.33, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Autoconfig loaded: no
Config.py: /home/user/.config/qutebrowser/config.py has been loaded

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**

![2021-12-14_18-29](https://user-images.githubusercontent.com/93383215/145992461-5ad5d60a-96c5-4b15-8587-86e7a2e21f03.png)

When ";" key is pressed in normal mode the above screen is shown.
Not only the key chain start with ";", all key chain display like this.
Just the display problem, all key bindings 100% work.

This problem start about two weeks ago, dunno why, maybe after some manjaro update.

**How to reproduce**

Everytime you use the key chain keybindings.

**Comment by The-Compiler** [comment] 2021-12-14 12:46
Duplicate of #6869

**Closed** 2021-12-14 12:46 UTC
