### ISSUE TITLE
Can't working using qute-lastpass for multiple match

### ISSUE THREAD

**Issue by yorkbai** [qutebrowser/qutebrowser#5355] opened 2020-04-14 15:58 UTC
The qute-lastpass is Great !   It's perfect using qute-lastpass fill login info if only match one result.  when more than two matching ,  it's nothing ( dmenu havn't popup for choice)

1. os:  osx 10.13.6
    qb: 1.10.1
2. dmenu installed.(/usr/local/bin/dmenu)  version: dmenu-4.9
3. config in config.py
    config.bind('pa', 'spawn --userscript qute-lastpass --dmenu-invocation /usr/local/bin/dmenu') 
    or
    config.bind('pa', 'spawn --userscript qute-lastpass --dmenu-invocation dmenu')

    Same result. nothing happening,  nothing error info in :messages

 I missing sth?  plz !

**Comment by The-Compiler** [comment] 2020-04-14 16:05
@welps do you have an idea what's happening here?

@yorkbai Can you reproduce this and do `:report` so I can take a look at the logs? It shouldn't contain any passwords, but you might want to review the log before sending it.

**Comment by welps** [comment] 2020-04-14 17:28
Hi @The-Compiler, you can assign this to me and I can look into this. I've never used Qutebrowser on the Mac, but have one to test against.

**Comment by yorkbai** [comment] 2020-04-15 06:57
@The-Compiler  report log had send

**Comment by The-Compiler** [comment] 2020-04-15 07:15
The report has this:

```
14:47:02 ERROR    procs      guiprocess:_on_finished:122 Process stderr:
LastPass CLI returned for zhugeio.com - Please enter the LastPass master password for <...@gmail.com>.
 
Master Password: Error: Could not find decryption key. Perhaps you need to login with `/usr/local/bin/lpass login`.
```

You should definitely see that error in `:messages`. You're saying you don't?

**Comment by yorkbai** [comment] 2020-04-15 07:25
my mistake.  it's error info about not login lastpass.  I resend log after login it already.

![qb](https://user-images.githubusercontent.com/7995150/79309717-571d1100-7f2d-11ea-981c-c439cc79d5f4.jpeg)

**Comment by The-Compiler** [comment] 2020-04-15 07:42
Looks like the process just finishes cleanly:

```
15:20:31 DEBUG    procs      guiprocess:_pre_start:151 Executing: '/Users/yorkbai/Library/Application Support/qutebrowser/userscripts/qute-lastpass' --dmenu-invocation /usr/local/bin/dmenu
15:20:31 DEBUG    procs      guiprocess:_on_started:140 Process started.
15:20:32 DEBUG    procs      guiprocess:_on_finished:89 Process finished with code 0, status 0.
```

I'm guessing indeed something goes wrong with the dmenu invocation and the script exits:

```python
    # Nothing was selected, simply return
    if not selection:
        return ExitCodes.SUCCESS
```

I'll let @welps take over from here, as I don't use the userscript myself.

**Comment by welps** [comment] 2020-04-16 01:41
@yorkbai I took a look into this. I would recommend using [choose](https://github.com/chipsenkbeil/choose) or an alternative dmenu-like launcher for Mac.

Using `spawn --userscript qute-lastpass -d choose`, I was shown a selection of login options as seen below. Confirmed that selecting an option properly autofills the login form.

![qute-lastpass using choose](https://i.imgur.com/HJLf9th.png?1)

dmenu requires X11 which is no longer bundled with the Mac. To get dmenu to work on my own testing, I had to install XQuartz, open it explicitly, add dmenu as an application, and run dmenu from there. This obviously isn't ideal so you should choose to use a dmenu-like launcher built for Mac instead.

**Comment by yorkbai** [comment] 2020-04-16 14:18
Solved after using choose replace dmenu !  👍 @The-Compiler  @welps Thanks a lot!

**Comment by The-Compiler** [comment] 2020-04-16 20:41
Glad to hear that - and thanks @welps from my side as well!

**Closed by The-Compiler** 2020-04-16 20:41 UTC
Labels: status: needs triage
