### ISSUE TITLE
Request to use Desktop Notifications disappears too quickly on Skypeweb

### ISSUE THREAD

**Issue by Penaz91** [qutebrowser/qutebrowser#1998] opened 2016-09-30 11:32 UTC
When logging into SkypeWeb, the website requests the permission to show desktop notifications, however that request doesn't stay long enough to allow giving an answer, probably due to the fact that the request pops out in the middle of some kind of redirection.

The website where this happens is: http://web.skype.com
After the login, you should see a very quick warning, like this:
![mpv-shot0001](https://cloud.githubusercontent.com/assets/6682630/18990453/377790e4-8712-11e6-92b9-606e8d9c81a1.jpg)

The request is so quick i had to screencast my desktop and look for it frame-by-frame on the video

Version information attached as a file to save space.
[version.txt](https://github.com/The-Compiler/qutebrowser/files/502802/version.txt)

Thank you for your attention.

**Comment by The-Compiler** [comment] 2016-10-02 08:46
Reproduced - unfortunately the logs don't really say much:

```
10:44:31 DEBUG    statusbar  prompter:ask_question:368 Asking question <qutebrowser.utils.usertypes.Question default=None mode=<PromptMode.yesno: 1> text='Allow the website at web.skype.com to show notifications?'>, blocking False, loops [], queue deque([])
[...]
10:44:31 DEBUG    webview    webpage:acceptNavigationRequest:527 navigation request: url https://c1.microsoft.com/c.gif?DI=4050&did=1&t=, type NavigationTypeOther, target ClickTarget.normal
10:44:31 DEBUG    modes      modeman:leave:284 Leaving mode KeyMode.yesno (reason: aborted)
```

**Comment by Penaz91** [comment] 2016-12-07 09:50
Tried the new Git Version and seems that prompts stay now, and I was able to enable and see a notification. Sadly QuteBrowser crashed afterwards (Probably due to the QtWebKit engine)
Shall we mark this as solved/closed?

**Comment by The-Compiler** [comment] 2016-12-07 11:05
Huh, weird - I can still reproduce this (the prompt disappearing immediately) with the current git master.

**Comment by Penaz91** [comment] 2016-12-07 11:08
Yeah, I'm sorry. Seems it was a fluke. Now the prompt is back to disappear quickly. But i have a half-idea, is there a way to make the prompts stay even if there is a redirection?

**Comment by The-Compiler** [comment] 2016-12-07 11:14
Currently the prompt is closed whenever a new page load is started. Maybe we can just not do that and rely on QtWebKit for aborting the question when needed, but I haven't looked into it yet.

**Comment by amacfie** [comment] 2021-01-22 20:48
Didn't reproduce

**Comment by The-Compiler** [comment] 2021-01-25 18:58
With QtWebKit I can't seem to access the site anymore at all (even when faking a Chromium UA); with QtWebEngine I can't reproduce. Closing this then - thanks @amacfie!

**Closed by The-Compiler** 2021-01-25 18:58 UTC
Labels: bug: behavior, component: prompts, priority: 2 - low
