### ISSUE TITLE
GTK3 file selector not showing any files

### ISSUE THREAD

**Issue by ghost** [qutebrowser/qutebrowser#5231] opened 2020-02-12 14:30 UTC
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/34bd8850

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
If 1) Qt is told to use GTK theme and 2) all file types are accepted, file selector refuses to show any files, the type filter only has "Accepted types", which seems to be empty.

**How to reproduce**
1. Run Qutebrowser with the following env var:
`$ DESKTOP_SESSION=gnome qutebrowser` or
`$ QT_QPA_PLATFORMTHEME=gtk3 qutebrowser` or
`$ QT_QPA_PLATFORMTHEME=gtk2 qutebrowser`
2. Go to some site which uses file selector not limited by type, e.g. try to upload a file in Telegram.

**Comment by The-Compiler** [comment] 2020-02-12 14:35
Works fine here, on imgur:

![image](https://user-images.githubusercontent.com/625793/74344532-0feb9600-4dad-11ea-8e37-a13aaaa19cd6.png)

How does the dropdown look when you click "Accepted types"? I get a list of video/image types, like I'd expect.

Can you reproduce this in KDE Falkon as well?

**Comment by mike402** [comment] 2020-02-12 14:36
Sorry I just found out it actually works if the selection is limited by types, it only breaks if it's not -- I have just corrected my report.

**Comment by mike402** [comment] 2020-02-12 14:38
In Falkon the only option shows "All Files" and it shows files.

**Comment by mike402** [comment] 2020-02-12 14:56
By the way, it seems there is a related issue with theming. With `$ QT_STYLE_OVERRIDE=Breeze qutebrowser` the file selector seems to be a weird hybrid between Qt default theme and Breeze (top photo), is not the case in Falkon (bottom photo): https://imgur.com/a/Ecyyd0j

**Comment by The-Compiler** [comment] 2020-02-12 15:06
Looks like Falkon overrides `QWebEnginePage::chooseFiles` which somehow doesn't cause this to happen - but this seems to be a QtWebEngine bug. I opened [[QTBUG-82109] [REG 5.14] No files shown in filepicker - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-82109). Keeping this open for now since a workaround might be possible, but don't hold your breath.

**Comment by mike402** [comment] 2020-02-12 17:08
Should I make the styling issue separate issue, or is it ok to just change the title of this one?

**Comment by The-Compiler** [comment] 2020-02-13 10:43
Let's keep it in here for now. I'm not sure if it actually is an issue, or just Qt's default behavior.

**Comment by JonnyHaystack** [comment] 2020-03-06 14:30
I also have this issue with `QT_QPA_PLATFORMTHEME=qt5ct` but had assumed it was just me because when I searched the issue tracker a while back I didn't see anything about it.

**Comment by jhhuisman** [comment] 2020-03-18 10:14
I also experience the same issue.

**Comment by jhhuisman** [comment] 2020-03-20 09:36
Is there some other theme I can set that works?

**Comment by yousufinternet** [comment] 2020-03-24 05:13
I have the same issue and it's a little bit annoying especially when I have to upload/attach multiple files, I have to copy the path to each and every file and paste it in the file picking dialog.
If someone have a nice working workaround it will be much appreciated.

**Comment by baldrianbandit** [comment] 2020-03-24 12:55
Same issue here. Using the telegram web client to test it. The behaviour seems not to depend on the value of QT_QPA_PLATFORMTHEME.

Temporary solution: In qt5ct, set `Appearance/Standard dialogs` from GTK2 to default and restart qutebrowser.

**Comment by The-Compiler** [comment] 2020-05-04 19:53
From #1365:

> @The-Compiler Unfortunatly I have only 5.14.1 available on my distro. /:

@poinck What distro is that?

**Comment by poinck** [comment] 2020-05-04 20:00
@The-Compiler Gentoo. I just saw, 5.14.2 is currently unstable. For now I can live with the workarround by using the address-bar in the GTK-file-chooser by hitting CTRL+L first and then navigating my way to the file I want to upload. This is better than starting another browser to do it.

When Qt 5.14.2 is stable in Gentoo and I had a chance to compile everything, I will test wether the problem still exists and hopefully remember to report back. It seems important for others, too.

**Comment by JonnyHaystack** [comment] 2020-05-04 22:12
FWIW it's now fixed for me in Arch with Qt 5.14.2

**Comment by mschilli87** [comment] 2020-05-05 05:03
@poinck: I'm running 5.14.2 on my Gentoo box (`~arch64`) without any issues.

This is what I have in my `/etc/portage/package.accept_keywords`

```
=dev-qt/linguist-tools-5.14.2 ~amd64
=dev-qt/qtconcurrent-5.14.2 ~amd64
=dev-qt/qtcore-5.14.2 ~amd64
=dev-qt/qtdbus-5.14.2 ~amd64
=dev-qt/qtdeclarative-5.14.2 ~amd64
=dev-qt/qtdiag-5.14.2 ~amd64
=dev-qt/qtgraphicaleffects-5.14.2 ~amd64
=dev-qt/qtgui-5.14.2 ~amd64
=dev-qt/qtmultimedia-5.14.2 ~amd64
=dev-qt/qtnetwork-5.14.2::libressl ~amd64
=dev-qt/qtopengl-5.14.2 ~amd64
=dev-qt/qtpositioning-5.14.2 ~amd64
=dev-qt/qtprintsupport-5.14.2 ~amd64
=dev-qt/qtquickcontrols-5.14.2 ~amd64
=dev-qt/qtscript-5.14.2 ~amd64
=dev-qt/qtsql-5.14.2 ~amd64
=dev-qt/qtsvg-5.14.2 ~amd64
=dev-qt/qttest-5.14.2 ~amd64
=dev-qt/qttest-5.14.2 ~amd64
=dev-qt/qtwebchannel-5.14.2 ~amd64
=dev-qt/qtwebengine-5.14.2 ~amd64
=dev-qt/qtwidgets-5.14.2 ~amd64
=dev-qt/qtxml-5.14.2 ~amd64
```

Depending on your `USE` flags, you might have slighty different dependencies.
Here are mine (for `dev-qt/qtwebengine-5.14.2`):

```
+alsa
-bindist
-debug
-designer
-geolocation
-jumbo-build
-kerberos
-pulseaudio
+system-ffmpeg
+system-icu
-test
+widgets
```

Hope this helps.

**Comment by poinck** [comment] 2020-06-24 18:35
@mschilli87 Yes, today was the first day I saw it working again; version **1.12.0**.

**Comment by The-Compiler** [comment] 2020-06-25 11:18
FWIW nothing changed in qutebrowser about this - it was a bug introduced in QtWebEngine 5.14.1 and fixed in 5.14.2.

**Comment by poinck** [comment] 2021-09-13 08:25
Just a small follow-up: With qutebrowser running with qt-5.15.2 under gnome-40 this problem did not reappear. It is fixed.

**Comment by The-Compiler** [comment] 2023-03-23 21:09
Support for Qt 5.14 is dropped now.

**Closed by The-Compiler** 2023-03-23 21:09 UTC
Labels: priority: 2 - low, component: QtWebEngine, qt: 5.14
