### ISSUE TITLE
adblock not working after re-opening window in private browsing mode in v1.14.0

### ISSUE THREAD

**Issue by coiby** [qutebrowser/qutebrowser#5919] opened 2020-11-28 13:40 UTC
**Version info**:
```
qutebrowser v1.14.0
Git commit: 6a9f3d6cf on master (2020-11-26 22:05:57 +0100)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.8.6
PyQt: 5.15.1

sip: 5.4.0
colorama: 0.4.4
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.2
yaml: 5.3.1
attr: 20.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.1
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1h  22 Sep 2020
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

The adblocking doesn't work after re-opening the window in private browser mode since v1.14.0. This issue doesn't affect previous versions like v1.13.1

**How to reproduce**

1. Launch QB and run `adblock-update`
2. Open a window in private browsing mode and visit https://adblock-tester.com/. QB will pass the tests of Analytic Tools.
3. Close the private browsing window and re-open one
4. Visit https://adblock-tester.com/. Now QB will fail the tests of Analytic Tools.

**Comment by The-Compiler** [comment] 2020-11-28 14:12
Duplicate of #5810

**Closed by The-Compiler** 2020-11-28 14:12 UTC
