### ISSUE TITLE
Renderer was killed 

### ISSUE THREAD

**Issue by kflak** [qutebrowser/qutebrowser#5172] opened 2020-01-02 10:09 UTC
**Version info (see `:version`)**:
qutebrowser v1.8.3
Backend: QtWebEngine (Chromium 77.0.3865.129)

System: Arch 5.4.5-rt3-1-rt, Sway 1.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Renderer crashes when trying to access my net bank on https://nb.nordea.no/login/#!/select/bankid/start with the message:
```
[3371:3399:0102/115729.762104:ERROR:render_process_host_impl.cc(4622)] Terminating render process for bad Mojo message: Received bad user message: GamepadMonitor::GamepadStartPolling faile
[3371:3399:0102/115729.762131:ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
11:57:29 ERROR: Renderer process was killed
```
AFAICT this only affects my bank's website.

**How to reproduce**

**Comment by The-Compiler** [comment] 2020-01-02 10:51
Duplicate of #5164

**Closed by The-Compiler** 2020-01-02 10:51 UTC
