### ISSUE TITLE
Overlays rendered under page content when colors.webpage.bg is transparent

### ISSUE THREAD

**Issue by DogeyStamp** [qutebrowser/qutebrowser#6614] opened 2021-07-22 20:04 UTC
**Version info**:

qutebrowser v2.3.0
Git commit: 
Backend: QtWebEngine 5.15.5, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
When c.colors.webpage.bg is set to a value with an alpha value less than 255, all overlays (keyhints, hints) get hidden under the contents of the webpage.

**How to reproduce**

1. Run `:set colors.webpage.bg transparent`
2. Go to [https://duckduckgo.com](duckduckgo) (for example)
3. Press t to bring up the keyhints menu, it will be mostly hidden under the page
4. Press f to bring up hints, they won't be visible

This issue happens on other websites, too.

**Comment by DogeyStamp** [comment] 2021-07-22 20:09
I've tried setting the z-index of the hints to 100 through CSS, and that doesn't help.

Also, when the page has a transparent background, you can see that the hints are rendered underneath, but they're covered by the contents of the page.

**Comment by leesongun** [comment] 2021-07-22 23:53
![image](https://i.imgur.com/G8uEW4B.png) [source](https://www.reddit.com/r/qutebrowser/comments/ep7k81/attempt_at_background_transparency/)

**Comment by The-Compiler** [comment] 2021-07-23 07:36
Duplicate of #5948

**Closed by The-Compiler** 2021-07-23 07:36 UTC
