### ISSUE TITLE
Having status bar show when hovering a link

### ISSUE THREAD

**Issue by uoou** [qutebrowser/qutebrowser#2911] opened 2017-08-17 03:03 UTC
I'm sorry if this is the wrong place for this or wrong way to ask. I did search for a similar request but it's a tricky thing to search.

I have the status bar hidden because I have no need for it when not entering commands. But it'd be nice if it (or something which provides this function) appeared for a moment when hovering over a link to reveal the url of that link - something I do quite frequently.

Would something like that be possible/desirable?

**Comment by The-Compiler** [comment] 2017-08-17 05:44
This is the right place for it, but it's a duplicate of #2157 :wink:

**Closed by The-Compiler** 2017-08-17 05:44 UTC
