### ISSUE TITLE
Unloaded Tabs Not Saving to Session Upon Closing

### ISSUE THREAD

**Issue by VehementHam** [qutebrowser/qutebrowser#8166] opened 2024-04-19 20:17 UTC
This one is really easy to reproduce.

Suppose I open Qutebrowser, and then right after I close it. Any tabs in that session that had not loaded in the breif time in which it was open are lost. Upon opening a new session all of those tabs are empty.

**Comment by The-Compiler** [comment] 2024-04-19 20:38
Duplicate of #7515

**Closed by The-Compiler** 2024-04-19 20:38 UTC
