### ISSUE TITLE
Random scrolling when changing workspaces

### ISSUE THREAD

**Issue by nagy135** [qutebrowser/qutebrowser#4953] opened 2019-08-05 16:52 UTC
**Version info (see `:version`)**:
qutebrowser v1.6.3

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description/How to reproduce**
I m not sure if last package did this (vacation for few weeks) but i noticed that when i open longer page and i scroll to certain position, change workspace and go back, 9/10 times page randomly scrolls up or down (usually all the way to the bottom). It is extremely annoying i had to stop using qutebrowser for now because i swap workspaces constantly on my notebook.
I m using BSPWM 0.9.7-7-g8fa2185 so issue might be bspwm related, but no other browser or any other app seems to be affected, just qutebrowser.

**Comment by The-Compiler** [comment] 2019-08-05 16:58
Likely a duplicate of #4579.

**Closed by The-Compiler** 2019-08-05 16:58 UTC

**Comment by nagy135** [comment] 2019-08-05 17:04
I thought its bspwm related, it indeed is the same issue .....for anyone reading this, this is very ugly but working solution :

`bind <tab> :nop`

**Comment by zfenj** [comment] 2019-09-07 23:14
`bind <tab> :nop`

Nice workaround.

But this issue [occurs also in other modes].(https://github.com/qutebrowser/qutebrowser/issues/4579#issuecomment-512982462)

For the moment it's nice to have a "solution".
