### ISSUE TITLE
Wrong scroll position for URLs with fragments

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4288] opened 2018-10-03 19:41 UTC
Problem: I post a link to the section of a website to, for instance, FB. Then I click on the link and I get to some random place in the webpage. If I click on the link on another browser, the page opens at the proper anchor.

**Comment by The-Compiler** [comment] 2018-10-03 20:15
Do you have an example (ideally not involving Facebook) to reproduce this?

**Comment by jgkamat** [comment] 2018-10-04 05:53
I can't reproduce this on Facebook either, testing with https://github.com/qutebrowser/qutebrowser#getting-help posted on the news feed.

**Comment by prosoitos** [comment] 2018-10-04 16:36
It is very weird: when I follow the same link, sometimes I get to the anchor nicely and sometimes I get to a random place in the page (?????!!)

**Comment by prosoitos** [comment] 2018-10-04 16:39
So sometimes I can and sometimes I can't even reproduce it myself... I don't know what might be different between the attempts.

**Comment by jgkamat** [comment] 2018-10-04 16:39
If it happens again (reliably), maybe you could restart qutebrowser with --debug and see what it outputs when you click on the link... I've got no other ideas :/

**Comment by prosoitos** [comment] 2018-10-04 16:51
Good point. Will do. Thank you.

**Comment by The-Compiler** [comment] 2018-10-04 17:11
You can also run `:messages debug` to view the log, or `:report` to send it to me.

Could it be possible that it only happens when opening the link in a background tab, or that it's related to resizing the window somehow?

**Comment by prosoitos** [comment] 2018-10-04 18:17
> Could it be possible that it only happens when opening the link in a background tab, or that it's related to resizing the window somehow?

I don't think so. It sometimes happens and sometimes not while doing the exact same thing on the same link.

**Comment by The-Compiler** [comment] 2018-10-23 17:31
I still haven't been able to reproduce this (not even with the steps from #1417), but apparently you're not the only one with the issue. #4230 is likely related as well somehow, because that was the workaround originally introduced for #1190.

**Comment by The-Compiler** [comment] 2018-10-23 17:37
Ah, reproduced with the steps from #4370 (selecting "FAQ entry" on https://aircrack-ng.org/doku.php?id=compatibility_drivers) - it works fine with Qt 5.10 but broke somehow with Qt 5.11.

**Comment by jgkamat** [comment] 2018-10-23 20:32
Just relaying over from IRC, `tabs.background` -> true fixes that case, which is why I didn't see it.

**Comment by The-Compiler** [comment] 2018-10-23 20:33
Setting `tabs.background` to true doesn't seem to make a difference for me, at least with the aircrack-ng link.

**Comment by MacGyverNL** [comment] 2018-11-01 13:36
Observation: Pages on which this happens for me consistently have a wrong number on the page scroll percentage. The number self-corrects immediately when scrolling, and the actual anchor position then turns out to be very close to the scroll percentage initially displayed.

**Comment by prosoitos** [comment] 2019-02-05 21:54
Not sure whether this is related, but I felt it might be:

Situation:
I am at some % down a webpage in qutebrowser, I jump to another workspace, then jump back.

Expected behaviour:
Be returned to the same screen (so same place in the webpage).

Problem:
The behaviour is inconsistant. Sometimes it works fine, but often, the very top of the website is displayed and I have to scroll back down to where I was.

**Comment by MikauSchekzen** [comment] 2019-05-16 10:27
I can confirm the problem with workspaces.

I'm using KDE Plasma on Arch Linux (x64), switching to a different workspace and back resets the scroll position on some pages to the top.

One such page is this one: https://kotlinlang.org/docs/tutorials/command-line.html

**Comment by toofar** [comment] 2019-05-16 11:05
That page seems to go to the top when tab is pressed, could it be the same issue as https://github.com/qutebrowser/qutebrowser/issues/4579?

**Comment by arza-zara** [comment] 2019-10-14 16:11
Seems to be fixed in Qt 5.13.

**Comment by The-Compiler** [comment] 2020-11-04 21:51
Looks like this is also fixed in Qt 5.12(.3) - since I'm dropping Qt 5.11 and older (#3839) I'm closing this.

**Closed by The-Compiler** 2020-11-04 21:51 UTC
Labels: bug: behavior, component: QtWebEngine, priority: 2 - low, qt: 5.11
