### ISSUE TITLE
Qt 6: Frozen until input events happen

### ISSUE THREAD

**Issue by mia-0** [qutebrowser/qutebrowser#7543] opened 2023-01-05 15:24 UTC
**Version info**:
qutebrowser v2.5.2
Backend: QtWebEngine 6.4.1, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.1

CPython: 3.10.9
PyQt: 6.4.0

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.13.0
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: 3.1.81 (/home/mia/.local/share/qutebrowser/pdfjs/build/pdf.js)
sqlite: 3.40.0
QtNetwork SSL: OpenSSL 1.1.1s  1 Nov 2022

Style: QFusionStyle
Platform plugin: wayland-egl
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.3.2
Platform: Linux-6.1.3-1-preempt-x86_64-with-glibc2.36, 64bit
Linux distribution: openSUSE Tumbleweed (opensuse)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt6/libexec, data path: /usr/share/qt6

Paths:
cache: /home/mia/.cache/qutebrowser
config: /home/mia/.config/qutebrowser
data: /home/mia/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/mia/.config/qutebrowser/config.py has been loaded
Uptime: 0:02:15

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Any and all rendering, pageloads, etc. are permanently stuck until qutebrowser gets an input event (keystroke, mouse cursor movement, …). Key repeat is also broken because of this. Really hard to use the browser that way.

**How to reproduce**
Immediately obvious upon running qutebrowser. This is with Tumbleweed snapshot 20230103, in a Wayland session (Sway 1.8).

**Comment by The-Compiler** [comment] 2023-01-05 17:05
Duplicate of #7532

**Closed by The-Compiler** 2023-01-05 17:05 UTC
