### ISSUE TITLE
Cannot write accented characters in input text fields 

### ISSUE THREAD

**Issue by runjaj** [qutebrowser/qutebrowser#2573] opened 2017-04-25 09:55 UTC
When I try to write accented characters (like á, é, í, ó, ú, ü) in an input text filed, I just get the character without the accent. It's quite unpleasant if you write in Spanish. I'm using a mac, but I tried it using the linux version inside a virtual machine and there were problems there too.

The information of my system is:

qutebrowser v0.10.0
Git commit: v0.10.0 (2017-02-25 21:47:56 +0100)
Backend: QtWebEngine

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.6.210 (bundled)
Webkit: no
SSL: Secure Transport, macOS Sierra (10.12)

Style: QMacStyle
Platform: Darwin-16.5.0-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.12.4, x86_64

Paths:
config: /Users/javier/Library/Preferences/qutebrowser
data: /Users/javier/Library/Application Support/qutebrowser
system_data: /Users/javier/Library/Application Support/qutebrowser
cache: /Users/javier/Library/Caches/qutebrowser
download: /Users/javier/Downloads
runtime: /var/folders/8f/w441d30s35n7_h_k_gbv0vbh0000gn/T/qutebrowser

**Comment by The-Compiler** [comment] 2017-04-25 10:16
It's a Qt issue which will be fixed with the next Qt release (scheduled for end of May).

**Closed by The-Compiler** 2017-04-25 10:16 UTC

**Comment by Teyras** [comment] 2019-02-18 14:12
I still have this issue with Qt 5.12... Is there any other info I could provide to help?

**Comment by luishenriqueamaral** [comment] 2020-01-14 19:10
It also happens to me.

qutebrowser v1.9.0
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.0

CPython: 3.8.1
PyQt: 5.14.1

sip: 5.1.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.10.3
pygments: 2.5.2
yaml: 5.1.2
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

**Comment by The-Compiler** [comment] 2020-01-14 19:59
@Teyras Sorry, I must've missed this comment - can you still reproduce with an up-to-date Qt version?

@luishenriqueamaral Can you reproduce this in [KDE Falkon](https://www.falkon.org/)?

**Comment by Teyras** [comment] 2020-01-14 20:35
@The-Compiler ň ň ť... Nah, I think I'm good :smile:

**Comment by luishenriqueamaral** [comment] 2020-01-14 20:46
@The-Compiler also happens with KDE Falkon
Falkon 3.1.0
QtWebEngine 5.14.0

Looks like a QtWebEngine issue?

**Comment by The-Compiler** [comment] 2020-01-14 20:51
@luishenriqueamaral Indeed, though it's weird that you're the only one with this issue nowadays. Do you do something special regarding keyboard layouts?

**Comment by luishenriqueamaral** [comment] 2020-01-14 20:56
I am currently using br abnt2 layout

**Comment by luishenriqueamaral** [comment] 2020-01-16 13:57
I have tried using tox, release 1.8.3 and it works fine, for those who need.

qutebrowser v1.8.3
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.8.1
Qt: 5.12.6
PyQt: 5.12.3

sip: 4.19.19
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.2
cssutils: 1.0.2 $Id$
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

**Comment by The-Compiler** [comment] 2020-01-16 14:13
@luishenriqueamaral What about v1.9.0? If that doesn't work, what about v1.9.0 and `scripts/mkvenv.py --pyqt-version 5.12` instead of the default (5.14)?

**Comment by luishenriqueamaral** [comment] 2020-01-16 14:43
@The-Compiler 
Doen't work: qutebrowser v.1.9.0 with qt 5.14.0
Works fine: qutebrowser v.1.9.0 with qt 5.12  (using scripts/mkvenv.py --pyqt-version 5.12)

Thanks
