### ISSUE TITLE
Memory leaks on idle process

### ISSUE THREAD

**Issue by eckz-dee** [qutebrowser/qutebrowser#3069] opened 2017-10-08 03:05 UTC
There seem to be memory leaks with qutebrowser on linux. To reproduce have ~10 tabs open, minimize it if using a window manager, I'm using xfwm4, without failure the process becomes unresponsive after a couple hours and consumes roughly 3.5 GiB memory.

I think that whenever the OS pages Qutebrowser's memory it becomes unresponsive afterward and must be killed.

**Comment by The-Compiler** [comment] 2017-10-08 07:07
What Qt version, qutebrowser version and backend (see `:open qute://version`)?

(There really is a reason the issue template asks you for that information: So I don't have to :wink:)

**Comment by opaldes** [comment] 2017-10-08 12:26
Have the same issue. It gets high as 6.3 GB with only 3-4 Tabs after hibanation. Ill try to add a screencaptur of a top session when it gets high again.
Here is my current version infos


Version info

qutebrowser v0.11.0
Git commit: 
Backend: QtWebKit-NG (WebKit 602.1)

CPython: 3.6.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
OpenGL: no
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebKitWidgets: yes
pdf.js: no
SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.12.4-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
config: /home/opaldes/.config/qutebrowser
data: /home/opaldes/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/opaldes/.cache/qutebrowser
download: /home/opaldes/Downloads
runtime: /run/user/1000/qutebrowser

**Comment by Ape** [comment] 2017-10-08 13:11
@opaldes Have you tried using the webengine backend or the latest git version of qutebrowser?

**Comment by The-Compiler** [comment] 2017-10-09 04:33
Closing this as duplicate of #1476 now - though I still suspect most memory leaks being in WebKit/Chromium (i.e. QtWebKit/QtWebEngine) and not qutebrowser.

**Closed by The-Compiler** 2017-10-09 04:33 UTC
Labels: status: needs triage
