### ISSUE TITLE
Configurable IPC socket location

### ISSUE THREAD

**Issue by tinywrkb** [qutebrowser/qutebrowser#6300] opened 2021-03-17 22:05 UTC
In order to solve https://github.com/flathub/org.qutebrowser.qutebrowser/issues/3 the Flatpak app need a different location for the IPC socket.  
That's because `XDG_RUNTIME_DIR/qutebrowser` is created by the qutebrowser process, it's not available when Flatpak is setting up the sandbox so Flatpak can't bind-mount it into the sandbox.  
Having the IPC socket location, or the runtime dir location configurable will solve this problem.

Note that the preferred location for the IPC socket dir with Flatpak would be `${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}` which is already bind-mounted to all Flatpak sandbox sessions of the same app / with the same app-id.  
So the alternative for being configurable is to check if the app is running in a Flatpak sandbox and if so then read the environment variable `FLATPAK_ID` value and set the IPC socket dir location accordingly to `${XDG_RUNTIME_DIR}/app/${FLATPAK_ID}`.  
Also, note that `FLATPAK_ID` is `org.qutebrowser.qutebrowser` but I think it's better to get it from the environment so we won't break future forks or have multiple editions of the app with different names (e.g. dev/nightly).

I'm not sure about the correct way to test if the app is running in a Flatpak sandbox maybe checking if the environment variable `container` is equal `flatpak`.

**Comment by tinywrkb** [comment] 2021-03-17 22:22
> I'm not sure about the correct way to test if the app is running in a Flatpak sandbox maybe checking if the environment variable container is equal flatpak.

Check for the existence of `/.flatpak-info`.

**Comment by The-Compiler** [comment] 2021-03-18 07:14
Making it configurable is a bad idea IMHO - it would imply that it's possible to start two separate instances of qutebrowser by configuring its IPC location, but that's not the case: The underlying Chromium doesn't support two separate instances accessing the same data, but doesn't actually use lockfiles or anything, so things can get corrupted. Also see #6231 and #183.

Using that shared directory when we're on Flatpak sounds fine though - can you try this?

```diff
diff --git i/qutebrowser/utils/standarddir.py w/qutebrowser/utils/standarddir.py
index f94d46061..4a571696f 100644
--- i/qutebrowser/utils/standarddir.py
+++ w/qutebrowser/utils/standarddir.py
@@ -232,7 +232,14 @@ def _init_runtime(args: Optional[argparse.Namespace]) -> None:
         # Unfortunately this path could get too long for sockets (which have a
         # maximum length of 104 chars), so we don't add the username here...
 
-    _create(path)
+    from qutebrowser.utils import version
+    if version.is_sandboxed():
+        *parts, app_name = os.path.split(path)
+        assert app_name == APPNAME, app_name
+        path = os.path.join(*parts, 'app', os.environ['FLATPAK_ID'])
+    else:
+        _create(path)
+
     _locations[_Location.runtime] = path
 
 ```

(doing the import globally leads to a circular import, I might look at finding a proper solution for this before pushing this, but will probably push this version to the v2.1.x. branch)

As for finding out whether we're running on Flatpak, currently we already look at `/etc/os-release` for other purposes and use an `ID=org.kde.Platform` value there to assume we're running in Flatpak - I think that should be fine too.

**Comment by The-Compiler** [comment] 2021-03-18 10:32
I've pushed this fix (9f67a763ef86805f0981f037ccd2fb5cb0e84b88) and it seems to work fine for me from a quick test, so I'm closing this - if it doesn't work for you, though, please let me know!

**Closed by The-Compiler** 2021-03-18 10:32 UTC

**Comment by tinywrkb** [comment] 2021-03-18 10:46
@The-Compiler thanks, it's working correctly on my system.  
The recommendation I received in IRC is to use `/.flatpak-info` but the `/etc/os-release` check also seems like a good option as it doesn't break when changing the Flatpak runtime on run-time (it will break if changed on build-time) which is desired for example in order to debug with the Sdk.

**Comment by tinywrkb** [comment] 2021-03-18 10:57
A minor issue that I noticed is that the IPC socket is in `$XDG_RUNTIME_DIR/app/org.qutebrowser.qutebrowser/` but an empty `qutebrowser` dir is still being created next to the socket so we also have `$XDG_RUNTIME_DIR/app/org.qutebrowser.qutebrowser/qutebrowser`

```
$ ls -R $XDG_RUNTIME_DIR/app/org.qutebrowser.qutebrowser/

/run/user/1000/app/org.qutebrowser.qutebrowser/:
ipc-56f61016d8108e1835812a20291f7d59  qutebrowser

/run/user/1000/app/org.qutebrowser.qutebrowser/qutebrowser:
```

**Comment by The-Compiler** [comment] 2021-03-18 11:28
Hmm, I can't reproduce:

```
[📦 org.qutebrowser.qutebrowser qutebrowser]$ ls /run/user/1000/app/org.qutebrowser.qutebrowser/
ipc-56910c52ed70539e3ce0391edeb6d339
```

**Comment by tinywrkb** [comment] 2021-03-18 11:39
Sorry, my mistake, that's a leftover from a previous run. So no issue.
