### ISSUE TITLE
Renderer process was killed on LinkedIn

### ISSUE THREAD

**Issue by aitym** [qutebrowser/qutebrowser#5997] opened 2020-12-30 15:11 UTC
**Version info**:
qutebrowser --version:
```
qutebrowser v1.14.1
Git commit: efa8916fa on master (2020-12-30 13:51:39 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.3
yaml: 5.3.1
adblock: no
attr: 20.3.0
importlib_resources: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.34.0
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.3.1
Platform: Linux-5.9.14-arch1-1-x86_64-with-glibc2.32, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/aitym/.cache/qutebrowser
config: /home/aitym/.config/qutebrowser
data: /home/aitym/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00
```

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**
When I try to visit site `linkedin.com` it crashes with this error
```
Unable to load page
Error while opening http://linkedin.com/
Renderer process was killed
```

I am not authorized. Sometimes I noticed that it starts to crash when the site trying to automatically sign in via Google account, but I am not sure for it. It's just a guess.

**How to reproduce**
Just visit the site
```
https://linkedin.com
```

**Comment by The-Compiler** [comment] 2020-12-30 16:11
This looks like a QtWebEngine regression - reported upstream: [[QTBUG-89740] [REG 5.15.1 -> 5.15.2] Visiting LinkedIn causes "Terminating renderer for bad IPC message" - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-89740)

**Comment by The-Compiler** [comment] 2021-01-06 22:02
Adding `disable-features=InstalledApp` to `qt.args` works around it - going to push a workaround for it soon.

Also has a trivial reproducer: `:jseval navigator.getInstalledRelatedApps()`

**Comment by dhruvasagar** [comment] 2021-01-13 13:06
This appears to have been closed in QtWebEngine

**Comment by The-Compiler** [comment] 2021-01-13 13:08
It was, but I still want to add a workaround (and test) to qutebrowser.

**Comment by dhruvasagar** [comment] 2021-01-13 13:19
Sure, I noticed the v2.0.0 milestone only after commenting, looking forward to the next release. Thanks for your time and efforts on qutebrowser.

**Closed** 2021-01-16 19:54 UTC
Labels: bug: behavior, component: QtWebEngine, priority: 1 - middle

**Comment by dhruvasagar** [comment] 2021-02-28 16:22
I can confirm this issue seems have been fixed now. Thanks @The-Compiler

**Comment by rajendrasp** [comment] 2021-12-23 19:21
@dhruvasagar  In which version is the issue fixed?

**Comment by The-Compiler** [comment] 2021-12-23 21:17
@rajendrasp The Qt bug report linked above shows the QtWebEngine version containing the fix. Users of qutebrowser (an application using QtWebEngine) are unlikely to be able to tell you more (unless they are developers using Qt too, of course).

In any case, you might be able to pass `--disable-features=InstalledApp` to QtWebEngine too, see https://doc.qt.io/qt-5.15/qtwebengine-debugging.html#using-command-line-arguments
