### ISSUE TITLE
Can't see cursor in caret mode on some pages

### ISSUE THREAD

**Issue by slackhead** [qutebrowser/qutebrowser#3936] opened 2018-05-21 07:05 UTC
Version info: http://paste.the-compiler.org/view/0a29b429

On most pages I can't see the cursor in caret mode. When I can see it, it's very hard to actually see it as it seems to be a 1 pixel wide line that's the same colour as most of the text.

Is there some way of changing the style? Maybe a blinking block would be easier to see.

**Comment by jgkamat** [comment] 2018-05-21 07:12
this is kind of a duplicate of a entry in #3583, but I definitely agree, the cursor should at least be more visible by default, and probably should be configurable as well.

The default style [seems to be here](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/javascript/caret.js#L862), so it actually might be very easy to do the first half of this (just coming up with a better style). The configurability part of this might be a bit harder to do, just more code.

**Comment by slackhead** [comment] 2018-05-21 08:06
According to that the initial width is 0px. After that it gets set to rect,.width or node.offsetWidth. I wonder if sometimes they both fail and that's why I don't see it, because the width is still 0px.

**Comment by slackhead** [comment] 2018-05-21 16:19
This makes it much easier to see (caret.js):

    CaretBrowsing.injectCaretStyles = function() {
        const style = ".CaretBrowsing_Caret {" +
            "  position: absolute;" +
            "  z-index: 2147483647;" +
            "  min-height: 10px;" +
            "  min-width: 0.6em;" +
            "  background: inherit;" +
            "  color: inherit;" +
            "  mix-blend-mode: difference;" +
            "  filter: invert(50%);" +
            "  animation: blink 1s step-end infinite;" +
            "}";
        const blink = "@keyframes blink {" +
            "50% { visibility: hidden; }" +
            "}";
        const node = document.createElement("style");
        node.innerHTML = style;
        document.body.appendChild(node);
        const node2 = document.createElement("style");
        node2.innerHTML = blink;
        document.body.appendChild(node2);
    };

Use inherit rather than set colours.
min-width uses the whole character and resizes with zoom and/or min-font-size.
mix-blend-mode inverts the text colour
I tried to invert the background but nothing I tried worked.
Blink helps to make it stand out more

What do you think?

**Comment by slackhead** [comment] 2018-05-21 19:10
My current solution is to put that in a file and change my v and <Esc> binds:

**Comment by The-Compiler** [comment] 2018-05-21 19:29
Sorry, but that sounds too much of a hack to me - I'd rather have a proper fix for this. Note that you can also re-style it via `content.user_stylesheets` in the meantime.

**Comment by slackhead** [comment] 2018-05-21 19:34
In that case, what do you think about my changes to the original function in caret.js?

Would you consider adding those as a PR in itself?

**Comment by The-Compiler** [comment] 2018-05-21 20:01
LGTM from a very quick look - I'm busy with some deadlines, but by all means, please open a PR with that! I'll finally have time to look through all the open PRs in two weeks. :+1:

**Comment by The-Compiler** [comment] 2018-05-21 20:40
Nope, that won't work. The match is on the URL of the page only. What works is running scripts in the non-main world (see the `--world` flag for `:jseval`)

**Comment by slackhead** [comment] 2018-05-22 02:59
I think I can close this now then.

**Comment by The-Compiler** [comment] 2018-05-22 06:15
We usually close issues when the related PR is merged - I'll reopen this :wink:

**Closed** 2018-06-12 14:50 UTC
Labels: component: QtWebEngine, component: ui, priority: 2 - low
