### ISSUE TITLE
New tab link hints go to wrong URL with relative href

### ISSUE THREAD

**Issue by Jetfrog28** [qutebrowser/qutebrowser#6952] opened 2022-01-10 07:22 UTC
**Version info**:
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.2

I'm using the qutebrowser 2.4.0-2 package on an up to date Arch Linux system.

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
There is an issue that happens with certain links.  Following them by clicking, middle clicking, or `:hint` works correctly.  But following with `hint links tab` or `hint links tab -r`, or yanking with `hint links yank`, and presumably other operations, the href path is appended to a substring of the current URL instead of being appended to the base domain.  In the example given below, the href `article/ink` is appended to the page parent path to give `https://drawabox.com/lesson/0/article/ink` rather than the correct `https://drawabox.com/article/ink`.

**How to reproduce**
At https://drawabox.com/lesson/0/4 , click the first link in the text, which has link text `this article, "Why Ink?"`.  Observe that it goes to the correct page.  Then `:hint link tab` and follow the same link and notice the mangled URL and incorrect page.

**Comment**
I've been poking around in the code a bit, and `webelem::resolve_url` is the function that returns the incorrect address.  It only seems to be called in the failing cases I've mentioned above.

I think I remember this happening once before, but I can't recall on which other page.  It doesn't affect most links.  It seems to be an issue when the `href` is a relative path, while the website is treating it as an absolute path.

I'm not all that familiar with standard practice, but most other websites I've checked are using `href`s prefixed with `/`, which I assume explicitly marks them as absolute paths.  I don't know what the 'correct' behavior is when a path is relative and whether this website is breaking a reasonable expectation, but it works as it was intended to in some cases, and so there is at the very least an inconsistency in how qutebrowser is handling the link.  It does seem to go to the intended page in other browsers, so I would imagine qutebrowser should handle it the same way in all cases.

**Comment by toofar** [comment] 2022-01-10 08:00
Duplicate of https://github.com/qutebrowser/qutebrowser/issues/739 I'm afraid (based on the \<base> element). So go +1 that (although it's come up a few times before and no-one has done so yet...)

**Closed by toofar** 2022-01-10 08:00 UTC
