### ISSUE TITLE
The Source Code Pro font renders incorrectly in status bar and completion menus

### ISSUE THREAD

**Issue by JustinLovinger** [qutebrowser/qutebrowser#7327] opened 2022-07-25 17:45 UTC
**Version info**:

qutebrowser v2.5.1
Git commit:
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.3

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

The Source Code Pro font renders incorrectly in status bar and completion menus. It appears to render with single pixel width in washed out color.

**How to reproduce**

`:set fonts.default_family 'Source Code Pro'`

**Comment by The-Compiler** [comment] 2022-07-25 17:48
Seems fine to me:

![image](https://user-images.githubusercontent.com/625793/180841663-62b405ff-35e8-401c-873e-10688869fc35.png)

Do you have a screenshot? Does it look correct in other Qt applications?

**Comment by JustinLovinger** [comment] 2022-07-25 18:06
![dated__2022_07_25t18_03_37-_](https://user-images.githubusercontent.com/7183441/180844318-735b0afd-77f6-4cf7-be6a-04356172cb38.png)

I just tested Falkon and TeXstudio. I didn't notice font issues in either.

**Comment by The-Compiler** [comment] 2022-07-26 16:08
If you run this, do you get the same behavior?

```
python3 -c 'from PyQt5.QtWidgets import QApplication, QLabel; app = QApplication([]); lbl = QLabel(); lbl.setText("Hello World"); lbl.setStyleSheet("font: 12pt \"Source Code Pro\";"); lbl.show(); app.exec()'`
```

What if you replace `PyQt5` by `PyQt6` there?

**Comment by JustinLovinger** [comment] 2022-07-26 19:44
> If you run this, do you get the same behavior?
> 
> ```
> python3 -c 'from PyQt5.QtWidgets import QApplication, QLabel; app = QApplication([]); lbl = QLabel(); lbl.setText("Hello World"); lbl.setStyleSheet("font: 12pt \"Source Code Pro\";"); lbl.show(); app.exec()'`
> ```

That gives the same behavior.

> What if you replace `PyQt5` by `PyQt6` there?

I don't have `PyQt6` on this system.

P.S. if I change the font weight to anything other than `400`, the default, it renders correctly.

**Comment by The-Compiler** [comment] 2022-07-26 19:48
Closing this as an upstream issue in Qt, as it clearly isn't specific to qutebrowser then.

I try to report bugs upstream when I can easily reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2022-07-26 19:48 UTC
Labels: status: can't reproduce, status: needs triage
