### ISSUE TITLE
Relative links are not resolved properly in some cases.

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#3816] opened 2018-04-04 21:39 UTC
Yanking or opening urls in new tabs from https://www.mmo-champion.com/forums/266-General-Discussions causes invalid urls to be yanked.

On the page `PyQt5.QtCore.QUrl('https://www.mmo-champion.com/forums/266-General-Discussions')`, there is a relative link `threads/2382596-BfA-Refund-Policy`. Logically (to me at least), this should resolve to `PyQt5.QtCore.QUrl('https://www.mmo-champion.com/forums/threads/2382596-BfA-Refund-Policy')` and qt agrees, but chrome instead resolves it to `https://www.mmo-champion.com/threads/2382596-BfA-Refund-Policy`.

Since we are using qt to resolve the urls, this could be a bug in qt, but that seems weird.

I probably should read more on web standards...

[see this snippet](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/browser/webelem.py#L301)

**Comment by The-Compiler** [comment] 2018-04-08 08:55
Duplicate of #739

**Closed by The-Compiler** 2018-04-08 08:55 UTC
Labels: bug: behavior
