### ISSUE TITLE
Position marks misplaced when zoom.default != 100%

### ISSUE THREAD

**Issue by Galicarnax** [qutebrowser/qutebrowser#6474] opened 2021-05-24 09:01 UTC
**Version info**:
qutebrowser v2.2.1
Git commit: ef3ba3895-dirty on master (2021-05-17 23:40:28 +0600)
Backend: QtWebEngine 5.15.3, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
I use 140% default zoom, and when I set a mark with ``` `x``` and then jump to it with `'x` I find myslef further down the page, not actually where the mark was set. If I set the default zoom to 100%, the jumps are then correct.

**How to reproduce**
`:set zoom.defaul 140`, scroll to some position, ``` `a```, scroll to another position, `'a`, and find that you are not back to the previous position.

**Comment by The-Compiler** [comment] 2021-05-24 09:02
Duplicate of #4013

**Closed by The-Compiler** 2021-05-24 09:02 UTC

**Comment by Galicarnax** [comment] 2021-05-24 09:06
oh, man, I've searched with `set_mark` and `jump_mark`, nothing found... Should have tried with hyphens.
