### ISSUE TITLE
smhi.se - some date-parsing issue only in qutebrowser?

### ISSUE THREAD

**Issue by cetex** [qutebrowser/qutebrowser#7952] opened 2023-10-07 10:19 UTC
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.4.2, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.2

CPython: 3.11.6
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.4
jinja2: 3.1.2
pygments: 2.15.1
yaml: 5.3.1
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: 2.14.0 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.0.10 1 Aug 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.2.1-1ubuntu2
Platform: Linux-6.5.0-5-generic-x86_64-with-glibc2.38, 64bit
Linux distribution: Ubuntu Mantic Minotaur (development branch) (ubuntu)
Frozen: False
Imported from /home/user/venv/lib/python3.11/site-packages/qutebrowser
Using Python from /home/user/venv/bin/python
Qt library executable path: /usr/lib/qt6/libexec, data path: /usr/share/qt6

Paths:
cache: /tmp/qutebrowser-basedir-en4octxk/cache
config: /tmp/qutebrowser-basedir-en4octxk/config
data: /tmp/qutebrowser-basedir-en4octxk/data
runtime: /tmp/qutebrowser-basedir-en4octxk/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:13:28

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
smhi.se fails to render properly due to some date / time parsing issue in qutebrowser but it works with falkon, chrome, chromium, firefox on the same machine..

**How to reproduce**
go to swedish weather site https://www.smhi.se/q/Stockholm/2673730 and it prints a big pink Oops! An error occured! with a traceback + "Invalid Date" for the weather forecasts.

**Comment by arza-zara** [comment] 2023-10-07 11:58
It also fails with Falkon for me. I wonder if it's the same issues as calendar of https://www.vr.fi/ saying "Invalid Date".

**Comment by toofar** [comment] 2023-10-07 21:34
Maybe the same as this issue? https://github.com/qutebrowser/qutebrowser/issues/7811

**Comment by The-Compiler** [comment] 2023-10-08 19:56
Duplicate of #7811

**Closed by The-Compiler** 2023-10-08 19:56 UTC

**Comment by cetex** [comment] 2023-10-09 07:53
It looks like the same and I'll track #7811 instead.
Thank you!
