### ISSUE TITLE
Follow hint in new tab is incorrect on pages with `<base>` tag

### ISSUE THREAD

**Issue by user202729** [qutebrowser/qutebrowser#5700] opened 2020-09-01 12:21 UTC
**Version info**:
Latest master.

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Title.

**How to reproduce**

* Goto data:text/html,%3Cbase%20href=%22https://www.duckduckgo.com%22%3E%3Ca%20href=%22/%22%3Ex%3C/a%3E . (or create an HTML file with similar content.)
* Press `F` (hint in new tab).
* Select the link.

Expected: the link in <base> opens. (this happens with normal hint, or click, or right-click+"open in a new tab")
Actual: the link is interpreted relative to the current address.

------

Comment: executing `link.href` in JavaScript produces the correct absolute link.

**Comment by The-Compiler** [comment] 2020-09-01 12:39
Duplicate of #739

**Closed by The-Compiler** 2020-09-01 12:39 UTC
