### ISSUE TITLE
Issue with clicking links in macros

### ISSUE THREAD

**Issue by darbyhaller** [qutebrowser/qutebrowser#5263] opened 2020-03-01 07:59 UTC
**Version info**:
qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
The later command doesn't work in macros. (or something else is broken with macros)

**How to reproduce**
I tried to record a macro as follows:
q q /link <Enter> <Enter> q, where link is some text of a link on the page. As I record the macro, this works. Then, when I tried reloading the original page and using the macro, it did not take me to the link.

I tried to fix this using the later command, as that was suggested in someone elses issue about using hints in macros (which I also had issues with), so for the second <Enter>, I replaced it with later 100 fake-key -g <Enter>, but that didn't work either.

**Comment by darbyhaller** [comment] 2020-03-01 08:08
I say that the later command doesn't work because as I was recording my macro, I noticed that when you use later in a macro, it does the command that you latered without delay at the beginning, then repeats it after the delay.

**Comment by The-Compiler** [comment] 2020-04-07 09:45
The main underlying issue is that hinting only records command, but not other keyboard input. If you do `/link`, that's not recorded as a command (`:search link`) would be. When trying this with `:search link`), there still are some issues though, it seems. Closing this as a duplicate of #3453 though, as the underlying issue (macros only recording commands) is probably the same.

**Closed by The-Compiler** 2020-04-07 09:45 UTC
