### ISSUE TITLE
Cant use browser due to SSL Errors

### ISSUE THREAD

**Issue by peyloride** [qutebrowser/qutebrowser#2035] opened 2016-10-18 08:11 UTC
I've done some research and found some issues related to SSL errors but i cant get it to work. Whenever i tried to open any website, i'm facing ssl errors. 

```
qutebrowser v0.8.2
Git commit: v0.8.2-2-gb8d9cde (2016-08-02 19:04:03 +0000)

CPython: 3.5.2+
Qt: 5.6.1
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
Harfbuzz: old
SSL: OpenSSL 1.0.2g  1 Mar 2016

Platform: Linux-4.8.0-22-generic-x86_64-with-Ubuntu-16.10-yakkety, 64bit
Desktop: ubuntu
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.10"
VERSION_ID="16.10"
PRIVACY_POLICY_URL="http://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=yakkety
UBUNTU_CODENAME=yakkety

--- /etc/lsb-release ---
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"

```

**Comment by HolySmoke86** [comment] 2016-10-18 08:14
Can you provide an error message related to the SSL failures? That would be very helpful.

**Comment by peyloride** [comment] 2016-10-18 08:16
On the bottom of browser,
```
SSL errors - continue?
- The issuer certificate of a locally looked up certificate could not be found.
```

**Comment by The-Compiler** [comment] 2016-10-18 08:32
So you get an SSL error when visiting, say, https://www.python.org/ ?

Can you show the output of `openssl s_client -connect www.python.org:443`?

**Comment by peyloride** [comment] 2016-10-18 08:35
Yes, exactly. 

```
CONNECTED(00000003)
140182601977560:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1476779657
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

```

Everything is normal in chromium/firefox.

**Comment by The-Compiler** [comment] 2016-10-18 08:47
This sounds like your system's certificate database is broken, which is unrelated to qutebrowser - things work fine in Firefox/Chromium as they come with their own certificate databases, but if you do something like `wget https://www.python.org/` you'll probably get the same issue.

Maybe try (re)installing the `ca-certificates` package?

**Comment by peyloride** [comment] 2016-10-18 08:50
Yes ,you're right; wget fails. But reinstalling ca-certificates package doesnt help either. I'll try to investigate problem and provide feedfack on here if i can get it to work. Thanks.

**Comment by The-Compiler** [comment] 2016-10-18 08:54
No idea what could be wrong then... I'm closing this in the meantime as there's nothing qutebrowser can do about this, but please keep me updated!

**Comment by peyloride** [comment] 2017-03-17 17:50
I want to reopen this issue. Since then I can not figure out what is the problem. Today, I was using Arch for 1-2 months and did nothing about certificates, I tried to install qutebrowser again and same thing happens to me. With a difference;

My openssl s_client -connect www.python.org:443 log was different, it seems system got certificates properly but still qutebrowser warns me about certificates every time.

openssl s_client -connect www.python.org:443 output:

```
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert High Assurance EV Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert SHA2 Extended Validation Server CA
verify return:1
depth=0 businessCategory = Private Organization, jurisdictionC = US, jurisdictionST = Delaware, serialNumber = 3359300, street = 16 Allen Rd, postalCode = 03894-4801, C = US, ST = NH, L = Wolfeboro, O = Python Software Foundation, CN = www.python.org
verify return:1
---
Certificate chain
 0 s:/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=3359300/street=16 Allen Rd/postalCode=03894-4801/C=US/ST=NH/L=Wolfeboro/O=Python Software Foundation/CN=www.python.org
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
 1 s:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert High Assurance EV Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIIWjCCB0KgAwIBAgIQCXCW7BLw16II/CMOsOFe/jANBgkqhkiG9w0BAQsFADB1
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
d3cuZGlnaWNlcnQuY29tMTQwMgYDVQQDEytEaWdpQ2VydCBTSEEyIEV4dGVuZGVk
IFZhbGlkYXRpb24gU2VydmVyIENBMB4XDTE2MDYyOTAwMDAwMFoXDTE4MDkyNzEy
MDAwMFowgfgxHTAbBgNVBA8TFFByaXZhdGUgT3JnYW5pemF0aW9uMRMwEQYLKwYB
BAGCNzwCAQMTAlVTMRkwFwYLKwYBBAGCNzwCAQITCERlbGF3YXJlMRAwDgYDVQQF
EwczMzU5MzAwMRQwEgYDVQQJEwsxNiBBbGxlbiBSZDETMBEGA1UEERMKMDM4OTQt
NDgwMTELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAk5IMRIwEAYDVQQHEwlXb2xmZWJv
cm8xIzAhBgNVBAoTGlB5dGhvbiBTb2Z0d2FyZSBGb3VuZGF0aW9uMRcwFQYDVQQD
Ew53d3cucHl0aG9uLm9yZzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AMpgUlIza25mor2AW20yRs8uHtRJs0kXpMF2zATQjhYAgfpqjoKugoWBlMrLCFQj
G/Aq8W7pT4WWHCb9Nv2QGdnIEapxi5HSfxc3b1HIRmJDdfxsc2Y4dATfgzIS4wNw
jDM9tmYcMZMKZVdW4WxurQIka8r3tBFP944yAllRn8uuFVXSDYALkZOiiWxuMYKA
q40hYrDhWO53uKk23HNBo5Kgfvcj3t0ZcMSkzekClxyxgyS1nnkNWIdEEMCP/FFU
UXrQt0MEtkmfc++6Ps2SEiHL2T4MEqY8eE0ss6Mvmt+yzy8QsZOArrpxv7l8OwBO
5yB0LU3ByoQan1O/upeNclkCAwEAAaOCBGAwggRcMB8GA1UdIwQYMBaAFD3TUKXW
oK3u80pgCmXTIdT4+NYPMB0GA1UdDgQWBBTL2ztKcGS38IxHEASJaOzwHuUqljCC
AQsGA1UdEQSCAQIwgf+CDnd3dy5weXRob24ub3Jngg9kb2NzLnB5dGhvbi5vcmeC
D2J1Z3MucHl0aG9uLm9yZ4IPd2lraS5weXRob24ub3Jngg1oZy5weXRob24ub3Jn
gg9tYWlsLnB5dGhvbi5vcmeCD3B5cGkucHl0aG9uLm9yZ4IUcGFja2FnaW5nLnB5
dGhvbi5vcmeCEGxvZ2luLnB5dGhvbi5vcmeCEmRpc2N1c3MucHl0aG9uLm9yZ4IM
dXMucHljb24ub3JnggdweXBpLmlvggxkb2NzLnB5cGkuaW+CCHB5cGkub3Jngg1k
b2NzLnB5cGkub3Jngg9kb25hdGUucHlwaS5vcmcwDgYDVR0PAQH/BAQDAgWgMB0G
A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjB1BgNVHR8EbjBsMDSgMqAwhi5o
dHRwOi8vY3JsMy5kaWdpY2VydC5jb20vc2hhMi1ldi1zZXJ2ZXItZzEuY3JsMDSg
MqAwhi5odHRwOi8vY3JsNC5kaWdpY2VydC5jb20vc2hhMi1ldi1zZXJ2ZXItZzEu
Y3JsMEsGA1UdIAREMEIwNwYJYIZIAYb9bAIBMCowKAYIKwYBBQUHAgEWHGh0dHBz
Oi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwBwYFZ4EMAQEwgYgGCCsGAQUFBwEBBHww
ejAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQuY29tMFIGCCsGAQUF
BzAChkZodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGlnaUNlcnRTSEEyRXh0
ZW5kZWRWYWxpZGF0aW9uU2VydmVyQ0EuY3J0MAwGA1UdEwEB/wQCMAAwggF9Bgor
BgEEAdZ5AgQCBIIBbQSCAWkBZwB2AKS5CZC0GFgUh7sTosxncAo8NZgE+RvfuON3
zQ7IDdwQAAABVkgj4a8AAAQDAEcwRQIhAMhsxamO6hrRjfNmH4Yj/cnJo72cmTHm
rSlEi0FHilNtAiB/tDiULYh6rf9H5eKmrV8PRsvFNSflBsQIIF1VejnWrwB2AGj2
mPgfZIK+OozuuSgdTPxxUV1nk9RE0QpnrLtPT/vEAAABVkgj4XYAAAQDAEcwRQIg
Ygh+rvtk2KQd2CRaM+whfGgc6waZACSMgwzYVmOZr9sCIQDGs78IDIoPZhNBGfIK
xXQdq8DwAjahQboXeJWx/AfAxQB1AFYUBpov18Ls0/XhvUSyPsdGdrm8mRFcwO+U
mFXWidDdAAABVkgj4dkAAAQDAEYwRAIgMOOdrhZ0280XsmWuLt7fcFnwtRIu42j7
WmRrQ2NlJLUCIG5Z6vzlhvFNIhN67A0G/hrRH7hzJ13/elILZcjZYJQqMA0GCSqG
SIb3DQEBCwUAA4IBAQCuDt1T9tBxAVYp2u10uONL6FTHQlgguQCiN5ANmjp6dUAq
2I1nCgZB9nxhGUFOsdiQ5DFDgJ0xTAgwF4nWAyXEHKjyacoaUOh3Zq7A62r5+0eE
P3XDNKIN2TWF3+djFneND/uqqpDGo2bMdcm9l0dvktUP9xQXIZBBkOMJZfXSxh0/
7H+bDizx+bq/5Dwv97fs770UCz5LqGRuIUaZQvBQblsP5QoBaKEYW5Hsmfu9FWbW
0qreV7KHFp7ONBSKFUefbG0Q37O8oTPr7JnMxTvdUcthJOLcN9IHo2StTzv3Wru0
5njv0zLw7zwePKc9YJ1YBLmLj7vPxyy/XoW8+8hI
-----END CERTIFICATE-----
subject=/businessCategory=Private Organization/jurisdictionC=US/jurisdictionST=Delaware/serialNumber=3359300/street=16 Allen Rd/postalCode=03894-4801/C=US/ST=NH/L=Wolfeboro/O=Python Software Foundation/CN=www.python.org
issuer=/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert SHA2 Extended Validation Server CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4009 bytes and written 433 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 3188D4C42B6D5191653E502DAF0EFE5913722A616127C5D8BE7B9300D03ABC31
    Session-ID-ctx: 
    Master-Key: 07AB57DA82D0BE515D455DF1C7CE40AD5245EA0DB7C3ECFDC9D8E4DF58B82725D1F24192263C111E8A3F94CC5AD36C9E
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 1200 (seconds)
    TLS session ticket:
    0000 - 66 52 3a 03 40 29 80 50-7f ed b8 b9 dd f9 96 ab   fR:.@).P........
    0010 - 7d 97 73 f5 86 57 69 7a-24 ac b0 4b 62 0b 6e db   }.s..Wiz$..Kb.n.
    0020 - a5 35 41 a0 f4 b4 25 42-21 a5 92 9a 0a 87 2e 5b   .5A...%B!......[
    0030 - da e8 0f 98 a8 1f c6 39-72 0c 26 11 2b 1d fb e4   .......9r.&.+...
    0040 - f9 3d 0e 6c d9 7f 60 81-02 06 d7 a8 b9 bb b0 30   .=.l..`........0
    0050 - 76 f5 1a e9 98 59 6d 13-a2 90 73 d9 06 9c 1d 45   v....Ym...s....E
    0060 - 47 74 64 06 46 ac a4 6b-41 67 56 b4 7b 37 5c 6f   Gtd.F..kAgV.{7\o
    0070 - 4c 80 56 2b b6 1c 7e f1-f5 ad 6f 09 52 77 96 cc   L.V+..~...o.Rw..
    0080 - ae 1f 41 65 02 41 76 10-e7 2a 2e 73 11 83 5d b6   ..Ae.Av..*.s..].
    0090 - 82 27 f1 b8 7d e8 41 e1-4e dd 7e 8d 15 c9 64 c6   .'..}.A.N.~...d.

    Start Time: 1489772937
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---

```

**Comment by The-Compiler** [comment] 2017-03-18 17:04
@peyloride Can you show the version info from `:open qute:version`? Does running `sudo update-ca-trust` change anything?

**Comment by peyloride** [comment] 2017-03-18 17:30
@The-Compiler Sorry, update-ca-trust method doesnt work. 

Here it is log that you wanted;

```
qutebrowser v0.10.1
Git commit: 
Backend: QtWebKit

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.8

sip: 4.19.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
PyQt5.QtWebEngineWidgets: no
pdf.js: no
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: QFusionStyle
Platform: Linux-4.10.2-1-zen-x86_64-with-arch-Arch-Linux, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
OS Version: 

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/arch-release ---
Arch Linux release

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
config: /home/peyloride/.config/qutebrowser
data: /home/peyloride/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/peyloride/.cache/qutebrowser
download: /home/peyloride/Downloads
runtime: /run/user/1000/qutebrowser
```

**Comment by The-Compiler** [comment] 2017-03-18 17:32
No idea what's going wrong there, but I suggest with `qt5-webkit-ng` (which replaces `qt5-webkit`), or install `qt5-webengine` and start with `--backend webengine`.

**Comment by peyloride** [comment] 2017-03-18 19:56
With qt5-webengine it works well now. Any idea about why? If i can help you to resolve this bug i'll happily do anything you say. Thanks.

**Comment by The-Compiler** [comment] 2017-03-18 19:58
Because it uses a different way of checking certificates (Chromium's NSS/BoringSSL). No idea why it doesn't work with QtWebKit for you (works fine here, on Arch too), but that's most likely not a qutebrowser issue.

**Comment by peyloride** [comment] 2017-03-18 20:00
I see. So is it can be related to language or something similiar to this? I'm in Turkey.

**Comment by The-Compiler** [comment] 2017-03-18 20:16
I don't think so. Can you reproduce it with `--temp-basedir --backend webkit` too?

**Comment by peyloride** [comment] 2017-03-18 20:26
I got same SSL errors with these settings.

**Comment by The-Compiler** [comment] 2017-03-18 20:31
Can you reproduce it with those arguments again, and then do `:report` please? Then I can take a look at the log at least, but I guess I still won't be able to explain.

Also, can you please make sure you get the same error when cloning the repo and doing `python scripts/testbrowser.py https://python.org` there?

**Comment by The-Compiler** [comment] 2017-03-22 21:28
Reports:

- [Normal launch](http://paste.the-compiler.org/view/68230508)
- [With `--temp-basedir`](http://paste.the-compiler.org/view/348d8ba9)
- [With QtWebEngine](http://paste.the-compiler.org/view/cfbc5fe7)

Can you try with `openssl s_client -verify 1 -connect start.duckduckgo.com:443 ` again, please? Also, is your system fully up-to-date? Can you try with `qt5-webkit-ng` installed?

I can't explain this so far...

**Comment by peyloride** [comment] 2017-03-23 13:45
Thanks for your interest. My system is fully up-to-date. Also i did my reports on qt5-webkit-ng installed since you already tell me to try with it. 

I did your openssl request here is the result:

```
verify depth is 1
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root CA
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert SHA2 Secure Server CA
verify return:1
depth=0 C = US, ST = Pennsylvania, L = Paoli, O = "Duck Duck Go, Inc.", CN = *.duckduckgo.com
verify return:1
---
Certificate chain
 0 s:/C=US/ST=Pennsylvania/L=Paoli/O=Duck Duck Go, Inc./CN=*.duckduckgo.com
   i:/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
 1 s:/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
   i:/C=US/O=DigiCert Inc/OU=www.digicert.com/CN=DigiCert Global Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFLDCCBBSgAwIBAgIQAbpolJhYh5r8CHrIkqHbbDANBgkqhkiG9w0BAQsFADBN
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMScwJQYDVQQDEx5E
aWdpQ2VydCBTSEEyIFNlY3VyZSBTZXJ2ZXIgQ0EwHhcNMTYwNTI1MDAwMDAwWhcN
MTcwNzI2MTIwMDAwWjBsMQswCQYDVQQGEwJVUzEVMBMGA1UECBMMUGVubnN5bHZh
bmlhMQ4wDAYDVQQHEwVQYW9saTEbMBkGA1UEChMSRHVjayBEdWNrIEdvLCBJbmMu
MRkwFwYDVQQDDBAqLmR1Y2tkdWNrZ28uY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEA0O4pQSRXT3P4sZHYek2Pd3P4lvcCkG6uUEOGeygDYNWcEhLY
q4Pq432vtT6wG/bNwEeA2MorS9zAn6w3xRkSOi0QvdqIdSi6HV0QFMUHWu+Y4lum
zLUKxF2dopSi6xbTBFCurpGqaReNy5h9jGlzi/BLt4+KYWMMX6oxoE0bjRhICKan
o1DKykQgrYlXeTm/7a49rjpZR3/OHwLDlcKG1BsCNk+b5Ciwbu7AoscOHAO0OU1v
FpKw9PhwkG+qppoNrPzW6411ILJ/r8Z9fzOhHtx4DO1KXQ7jtQt1hqKUwTzIXYgV
wLOXtSlMqSKGxocSHQB2HloTWElY85jEt+Fg4wIDAQABo4IB5zCCAeMwHwYDVR0j
BBgwFoAUD4BhHIIxYdUvKOeNRji0LOHG2eIwHQYDVR0OBBYEFK2VQI/ETLfJ90F8
XkAo9eY/eVWHMCsGA1UdEQQkMCKCECouZHVja2R1Y2tnby5jb22CDmR1Y2tkdWNr
Z28uY29tMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB
BQUHAwIwawYDVR0fBGQwYjAvoC2gK4YpaHR0cDovL2NybDMuZGlnaWNlcnQuY29t
L3NzY2Etc2hhMi1nNS5jcmwwL6AtoCuGKWh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNv
bS9zc2NhLXNoYTItZzUuY3JsMEwGA1UdIARFMEMwNwYJYIZIAYb9bAEBMCowKAYI
KwYBBQUHAgEWHGh0dHBzOi8vd3d3LmRpZ2ljZXJ0LmNvbS9DUFMwCAYGZ4EMAQIC
MHwGCCsGAQUFBwEBBHAwbjAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNl
cnQuY29tMEYGCCsGAQUFBzAChjpodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20v
RGlnaUNlcnRTSEEyU2VjdXJlU2VydmVyQ0EuY3J0MAwGA1UdEwEB/wQCMAAwDQYJ
KoZIhvcNAQELBQADggEBAME5ryc8HVN64yKUDvK7IK0qfWBAVw5mYynEgUVeBoN1
DC8lR7vQY/xncOtJU/sGhqsW9h3qT7OnRV4yop3HZWnXQnNn1WSj2BkZl4eH+iQJ
Z51E70mIPAirrkWnzz+PMWgAvcI7H8Q/EnKvw1tYMS3RcE0BKytdjGayYUE0igZ/
ZCOv6nBPpbcVhIQjQgcdsS7HoX5tTZxzYDnCueta7mRJ7p6REHGfwN+vXb+quZtl
z+kWESz+B25nnUAKfvxV3bSYThxXTyqWp68zIx2ItlHtXuIJjUQWDfCWSIAe1b6E
/lnydmf5i+vLrnp87aBuJZUsyDJDBAqRL/dPlPm2fzk=
-----END CERTIFICATE-----
subject=/C=US/ST=Pennsylvania/L=Paoli/O=Duck Duck Go, Inc./CN=*.duckduckgo.com
issuer=/C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
---
No client certificate CA names sent
Peer signing digest: SHA512
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 3182 bytes and written 433 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: C27DD6836B2E54C2562F615FDADDC9C1E28A704E84E64AEBD3B502FB61B30234
    Session-ID-ctx: 
    Master-Key: D7E71C4E62FC3C1B40DF46456AAAE9D59EF348C6D3AA3EE9784ABC9FD81B5477FB16D3E311E37A7E03378E837E023021
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 1200 (seconds)
    TLS session ticket:
    0000 - 44 4d 80 5f 4b 18 c8 d8-70 1d 86 26 d3 9e 49 32   DM._K...p..&..I2
    0010 - 5a f9 3c fc 6b 96 4e f6-1d fc d4 11 e7 1a 13 ad   Z.<.k.N.........
    0020 - 2a d9 eb 5b c1 dc 44 fd-ca 5f e7 48 76 1b ff 31   *..[..D.._.Hv..1
    0030 - 01 1f 18 fd 51 06 46 8d-56 41 1a 05 d4 14 84 ef   ....Q.F.VA......
    0040 - ed c5 8f 08 14 be 98 79-47 a6 49 6e d2 f0 c9 61   .......yG.In...a
    0050 - 77 e5 bb 67 57 6e 20 30-b7 3f 0b 3c 85 23 63 2b   w..gWn 0.?.<.#c+
    0060 - 82 cc 84 71 3c 73 71 3f-73 21 9d 38 f7 cf 7f 7d   ...q<sq?s!.8...}
    0070 - b2 c4 0d 2a e0 7d 71 93-62 e0 af 24 8f 5c 87 c5   ...*.}q.b..$.\..
    0080 - 0b 1e b2 2e 5c ed 4f 50-a1 86 b5 85 c6 d5 00 c0   ....\.OP........
    0090 - 82 b0 37 6e f2 0d c1 6f-cb 6a 10 b7 46 e9 d5 c4   ..7n...o.j..F...
    00a0 - 58 85 05 cb c8 3a b8 53-6a 4e 21 95 2a 11 56 7e   X....:.SjN!.*.V~

    Start Time: 1490276516
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
q
HTTP/1.1 400 Bad Request
Server: nginx
Date: Thu, 23 Mar 2017 13:42:00 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 166
Connection: close

<html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
read:errno=0

```

**Comment by The-Compiler** [comment] 2017-03-23 20:13
http://stackoverflow.com/q/13785862 might be related.

**Comment by peyloride** [comment] 2017-03-23 20:41
I don't really understand how these related, do you want me to do something?

**Comment by The-Compiler** [comment] 2017-03-23 20:44
Sorry for the confusion - those are mainly notes for myself for now. Haven't had time to read them in detail yet.

**Comment by The-Compiler** [comment] 2017-03-24 06:33
@peyloride can you please try the following?

- Download and extract [the Qt 5.8 qtbase release](http://download.qt.io/official_releases/qt/5.8/5.8.0/submodules/qtbase-opensource-src-5.8.0.tar.gz)
- Change to the `qtbase-opensource-src-5.8.0/examples/network/securesocketclient/` directory
- `qmake && make`
- `./securesocketclient`
- Now try to connect to `start.duckduckgo.com` - does it work?

**Comment by peyloride** [comment] 2017-03-25 11:52
Same errors again.

Here is the screenshot: https://i.imgur.com/KqxbRal.png

**Comment by The-Compiler** [comment] 2017-03-26 15:31
Okay, this is definitely some issue with Qt on your system then.

Can you please open a [Qt bugreport](https://bugreports.qt.io/) against the component "Network: SSL" and link it here? In there, mention that this happens with the securesocketclient example.

**Closed** 2017-03-26 15:32 UTC
Labels: priority: 2 - low
