### ISSUE TITLE
Error running qutebrowser:

### ISSUE THREAD

**Issue by Newexplorer** [qutebrowser/qutebrowser#5099] opened 2019-11-02 11:24 UTC
I installed qutebrowser on my Ubuntu 16.04 OS (Xenial) as described on www.qutebrowser.org with tox: tox -e mkvenv-pypi.
Running qutebrowser in the terminal results in this:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/porter/Gitforeign/qutebrowser/qutebrowser/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/porter/Gitforeign/qutebrowser/qutebrowser/qutebrowser/qutebrowser.py", line 199, in main
    from qutebrowser import app
  File "/home/porter/Gitforeign/qutebrowser/qutebrowser/qutebrowser/app.py", line 64, in <module>
    from qutebrowser.completion.models import miscmodels
  File "/home/porter/Gitforeign/qutebrowser/qutebrowser/qutebrowser/completion/models/miscmodels.py", line 24, in <module>
    from qutebrowser.config import configdata
  File "/home/porter/Gitforeign/qutebrowser/qutebrowser/qutebrowser/config/configdata.py", line 32, in <module>
    from qutebrowser.config import configtypes
  File "/home/porter/Gitforeign/qutebrowser/qutebrowser/qutebrowser/config/configtypes.py", line 64, in <module>
    from qutebrowser.config import configexc, configutils
  File "/home/porter/Gitforeign/qutebrowser/qutebrowser/qutebrowser/config/configexc.py", line 25, in <module>
    from qutebrowser.utils import jinja, usertypes, log
  File "/home/porter/Gitforeign/qutebrowser/qutebrowser/qutebrowser/utils/jinja.py", line 33, in <module>
    from qutebrowser.utils import utils, urlutils, log, qtutils, javascript
  File "/home/porter/Gitforeign/qutebrowser/qutebrowser/qutebrowser/utils/utils.py", line 487, in <module>
    typing.Tuple[typing.Type[BaseException]]],
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/home/porter/Gitforeign/qutebrowser/.venv/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

Something is wrong. 
Let me know if you need more (like the output of a strace command e.g.).

*(edited by @The-Compiler to add proper code formatting)*

**Comment by The-Compiler** [comment] 2019-11-02 11:32
That's odd! Can you please show the output of `python3 --version`? Do you get a similar `TypeError` when you do these?

1. `python3 -c 'import typing; typing.Union[typing.Type[BaseException], typing.Tuple[typing.Type[BaseException]]]'`
2. `python3 -c 'import typing; typing.Type[BaseException]'`
3. `python3 -c 'import typing; typing.Tuple[typing.Type[BaseException]]]'`

Also, out of curiosity - is there a particular reason you didn't upgrade to Ubuntu 18.04 yet?

**Comment by The-Compiler** [comment] 2019-11-02 11:40
Ah, nevermind, I was able to reproduce it in an Ubuntu 16.04 Docker container. It looks like a bug in Python 3.5 which was fixed in later 3.5 patch versions, but Ubuntu still ships an earlier one... I'll look for a workaround.

**Comment by Newexplorer** [comment] 2019-11-02 12:05
The reason that I didn't upgrade yet is that I haven't found the time, yet.
The first command gives an error: 
```

porter@porter-Aspire-XC-230:~ $ python3 -c 'import typing; typing.Union[typing.Type[BaseException], typing.Tuple[typing.Type[BaseException]]]'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/usr/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

The other two commands don't give any output after running them. 
You probably knew that already, but to be on the safe side, I am giving the results anyway.
And thank you for your time.

**Comment by The-Compiler** [comment] 2019-11-02 12:06
This is indeed a bug which affects Python 3.5.2 only: https://github.com/python/typing/issues/266

I pushed a workaround - thanks for the report!

**Closed** 2019-11-02 12:06 UTC
Labels: status: needs triage

**Comment by Newexplorer** [comment] 2019-11-02 13:26
It works. Thank you.
