### ISSUE TITLE
Audio renderer error when switching between 2 separate videos

### ISSUE THREAD

**Issue by Harjuu** [qutebrowser/qutebrowser#5815] opened 2020-10-18 21:42 UTC
**Version info**:
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1 (compiled 5.15.0)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Playing a second Youtube video in another tab or browser instance gives me "Audio renderer error. Please restart your computer". Refreshing a few times finally makes the video play, but going back to the first video gives me the same error again, a behavior which repeats every time I switch between the videos. The same behavior when watching streams on Twitch.tv. I'm on Void linux using PulseAudio.

Log:
```
23:35:49 WARNING: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-dag'
[31762:31853:1018/233604.842190:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[31762:31853:1018/233604.842300:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[31762:31853:1018/233604.842388:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[31762:31853:1018/233627.374782:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[31762:31853:1018/233627.374892:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[31762:31853:1018/233627.374994:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
couldn't open play stream: Device or resource busy
[31855:31855:1018/233627.461749:ERROR:sndio_output.cc(69)] Couldn't open audio device.
[31831:4:1018/233627.462068:ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio render error"}
[31831:1:1018/233627.469825:ERROR:batching_media_log.cc(26)] MediaEvent: PIPELINE_ERROR AUDIO_RENDERER_ERROR
couldn't open play stream: Device or resource busy
[31855:31855:1018/233627.661170:ERROR:sndio_output.cc(69)] Couldn't open audio device.
[31831:4:1018/233627.661254:ERROR:batching_media_log.cc(26)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"audio render error"}
[31831:1:1018/233627.665690:ERROR:batching_media_log.cc(26)] MediaEvent: PIPELINE_ERROR AUDIO_RENDERER_ERROR
```

**How to reproduce**
- Open Qutebrowser with `qutebrowser --temp-basedir`
- Go to https://youtube.com/
- Go to any video, pause it or leave it playing
- Open a second video in another tab or browser instance
- Play the second video

**Comment by The-Compiler** [comment] 2020-10-18 21:55
This is unlikely to be a qutebrowser issue - can you check if you see the same with KDE Falkon and/or Chromium?

**Comment by Harjuu** [comment] 2020-10-18 22:10
Experiencing the same issue in Falkon, with the same error message in the logs. Chromium works without any issues.

**Comment by The-Compiler** [comment] 2020-10-18 22:12
Closing this then - I suspect it's some Voidlinux-specific issue like mentioned here: https://old.reddit.com/r/qutebrowser/comments/iy00k6/suddenly_no_sound_in_qutebrowser/

You might want to report this to Void instead.

**Closed by The-Compiler** 2020-10-18 22:12 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by minikN** [comment] 2020-10-23 21:23
@Harjuu Have you found a solution? I'm having the exact same problem. Also on Void Linux.

**Comment by Harjuu** [comment] 2020-10-23 21:27
@minikN Unfortuantely not. I've had so many audio issues in void that I'm thinking of switching back to Arch or something lol.

**Comment by minikN** [comment] 2020-10-23 21:38
Really? Can't say the same thing. I've had issues as well sure. But I think most of the time the problem isn't the problem itself, but the lack of documentation. However up until now I've been able to fix every issue so far. On the other hand a lot of things are easier on void compared to other distros.

But off topic. I checked with a couple of other browsers and I only have this issue in qutebrowser. Really none other. So I'm just gonna switch until this has been fixed.

**Comment by The-Compiler** [comment] 2020-10-24 09:41
@minikN Did those other browsers also include something else based on QtWebEngine, such as KDE Falkon?

**Comment by The-Compiler** [comment] 2020-10-26 19:37
Let me note that Void Linux patches in a completely new audio backend (sndio) in their QtWebEngine package: https://github.com/void-linux/void-packages/tree/master/srcpkgs/qt5-webengine/files/sndio-files

That is also the default being used from what I can tell, so given that this only affects Void Linux users I'm pretty sure the culprit is in those void-specific patches.

**Comment by klardotsh** [comment] 2020-10-26 19:57
As noted in IRC, I'm attempting a qtwebengine rebuild with Void's sndio support turned off, and I'll report back whether I can still repro my flavor of the issue (where qutebrowser/qtwebengine is bypassing PulseAudio completely and taking exclusive control of the `sysdefault` Alsa card (which is onboard laptop sound on this particular machine))
