### ISSUE TITLE
Private mode not restored after crash

### ISSUE THREAD

**Issue by mike402** [qutebrowser/qutebrowser#4995] opened 2019-09-01 19:12 UTC
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/812e6d0d

**Does the bug happen if you start with `--temp-basedir`?**:
not tried yet

**Description**
Tabs that were in private get open in normal mode when Qutebrowser restarts after a crash.

**How to reproduce**
Browse some pages in private mode, get browser to crash.

**Comment by The-Compiler** [comment] 2019-09-01 19:15
Duplicate of #3979

**Closed by The-Compiler** 2019-09-01 19:15 UTC
