### ISSUE TITLE
Screensharing on google meet very blurry on remote side - latest build

### ISSUE THREAD

**Issue by jonasrogert** [qutebrowser/qutebrowser#7895] opened 2023-09-07 10:05 UTC
**Version info**:
`qutebrowser v3.0.0
Git commit: ae2e679df on main (2023-09-06 16:38:46 +0200)
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.11.5
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: 3.10.111 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.43.0
QtNetwork SSL: OpenSSL 3.1.2 1 Aug 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.1.6-arch1.4
Platform: Linux-6.4.12-arch1-1-x86_64-with-glibc2.38, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6`

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
This is a weird one, latest build seems to make the screensharing super blurry on remote side in google meet (have not tested on other services). It works great on firefox. In the presenter view it looks really crisp.

**How to reproduce**
Create a meeting and join the same meet with another browser and share your screen. You can see the different by sharing from both browsers and the quality on qutebrowser is very blurry compared to firefox for example.

**Comment by toofar** [comment] 2023-09-07 11:44
Just throwing an idea out there since I had an issue with low resolution while screen sharing a while back (I think this was on Qt5 too though). Are you sharing a screen with a different geometry than the one you are sharing from? Eg sharing external monitor with browser on laptop monitor? Or sharing a wide screen with browser on a less wide screen. If so try this greasemonkey script (assuming the CSP rules let you inject it into the google meet page):

```javascript

// ==UserScript==
// @name         Override WebRTC getUserMedia video size selection
// @namespace    dsfjhkasdfjh
// @version      0.1
// @description  Workaround for chrome bug where resolution of the screen the browser is running on is used, instead of the size of the screen bring shared: https://bugs.chromium.org/p/chromium/issues/detail?id=1056311
// @author       anon
// @include      https://app.slack.com/*
// @run-at       document-start
// ==/UserScript==
 
(function() {
  // See "DUMPING CONFIGURATION INFORMATION" on:
  // https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture
  // Also see chrome://webrtc-internals/
  var orig = navigator.mediaDevices.getDisplayMedia
  var myGet = function(options) {
    console.log('initial getDisplayMedia() options:')
    console.log(options)
    if (!options.video) {
      options.video = {}
    }
    // hack from https://github.com/jitsi/lib-jitsi-meet/blob/bf79fef6012b3746a0b1f666a52370005ce47b65/modules/RTC/ScreenObtainer.js#L237
    if (!options.video.height) {
      options.video.height = 99999
    }
    if (!options.video.width) {
      options.video.width = 99999
    }
    return orig.call(navigator.mediaDevices, options)
  }
  navigator.mediaDevices.getDisplayMedia = myGet
})();
```

Change the `@include` line for whatever site you are using. There'll be an error in the developer tools console if it doesn't get injected (also it won't print `initial getDisplayMedia() options:`).

**Comment by The-Compiler** [comment] 2023-09-07 14:07
Additionally, could you please try with `--temp-basedir --qt-wrapper PyQt5` as well? Chances are it's caused by the Qt 5 -> 6 upgrade, and not any changes in qutebrowser.

**Comment by The-Compiler** [comment] 2023-09-08 15:48
> This was the version i was on before `qutebrowser-git-3.0.0.r21.g9f65926db`. that did not behave the same.

There are [zero changes to qutebrowser's non-test code](https://github.com/qutebrowser/qutebrowser/compare/9f65926db..ae2e679) between those commits, which again points to this not being a qutebrowser issue.

How did your Qt version change in that timeframe?

**Comment by jonasrogert** [comment] 2023-09-08 20:10
No changes to Qt. I think it might be an update to pipewire, because in that time frame there is nothing else that should interfere (maybe ffmpeg). It is probably something on my end. Sorry for taking the time, will report back if i find something.

**Comment by nlhomme** [comment] 2023-09-12 06:23
Hello, I'm just passing by, I have no idea what your project is, I was just doing a Google search for "google meet screen share" as I have the same issue at the office (I work for at the IT department).

One of my coworker did some tests yesterday and it seems that Chrome (and Chomium based broswers are affected).
Plus the issue you are encounting is know and has been escalated to Meet team:
[https://support.google.com/meet/thread/233987234?product_name=UnuFlow&hl=en&visit_id=638300958600852834-3074697110&rd=1&src=supportwidget0&hl=en](https://support.google.com/meet/thread/233987234?product_name=UnuFlow&hl=en&visit_id=638300958600852834-3074697110&rd=1&src=supportwidget0&hl=en)

[https://support.google.com/meet/thread/234492564?product_name=UnuFlow&visit_id=638300958583155345-906591558&rd=1&src=supportwidget0](https://support.google.com/meet/thread/234492564?product_name=UnuFlow&visit_id=638300958583155345-906591558&rd=1&src=supportwidget0)

Have a nice day :)

**Comment by The-Compiler** [comment] 2023-09-12 06:47
Interesting... thanks for the pointer, @nlhomme! @jonasrogert any chance you could try if this reproduces in Chromium too?

**Comment by The-Compiler** [comment] 2023-09-12 15:07
Always good when issues fix themselves — closing this then, and you're welcome!

**Closed by The-Compiler** 2023-09-12 15:07 UTC
Labels: status: needs triage
