### ISSUE TITLE
fake-key behavior differs between backends

### ISSUE THREAD

**Issue by ryan-farley** [qutebrowser/qutebrowser#3315] opened 2017-11-19 18:24 UTC
For some reason the WebKit backend is ignoring `fake-key <Enter>` for some websites. The simplest example would be the default DuckDuckGo start page. With WebEngine, running 
`:fake-key x ;; fake-key <Enter>`
will search for `x`, while on WebKit nothing happens (other than suggestions). Google, however, shows the same (expected) behavior on both backends. 

This is on 1.0.3 (and I also tested it on `master`).

**Comment by The-Compiler** [comment] 2017-11-19 18:37
I can reproduce this, but no idea why it happens and if qutebrowser can do something about it.

**Comment by ryan-farley** [comment] 2017-11-20 05:10
For interactive use it isn't much of a problem. And in fact that is probably too simple of an example, as a real user hitting those keys will get the same result. The issue is really with 
```enter-mode insert ;; fake-key x ;; fake-key <Enter>```
which are not able to be entered as fake key commands individually without leaving insert mode, fail to do what would be expected as a compound command or sent to a userscript FIFO, but _do_ work as actual keys.

**Comment by The-Compiler** [comment] 2018-03-08 07:23
Looks like this was fixed with the key refactoring which is in `master` since a few days.

**Closed by The-Compiler** 2018-03-08 07:23 UTC
Labels: bug: behavior, component: keyinput, priority: 2 - low
