### ISSUE TITLE
Qt 5.11: Tinted colors when using camera

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#3957] opened 2018-05-28 19:49 UTC
Since upgrading to Qt 5.11, the colors displayed when using my integrated camera are heavily tinted: very red-purple. This holds for taking pictures (e.g. on WhatsApp) and for taking video (e.g. on Jitsi).

Interestingly, when video-chatting on Jitsi, the person I'm chatting with sees my picture in normal color. Also, after I snap a camera shot on WhatsApp, the picture is in normal color. So the problem just has to do with *displaying* video to my own monitor in real time (during recording/before snapping a picture).

This bug is *not* specific to Qutebrowser, because I can reproduce it in Falkon (it does not reproduce in Chromium or Firefox). But I didn't know where else to post this. I also did not find any issues reported on the Qt bug tracker.

Is anyone else experiencing this? I'm running Arch Linux with Qt 5.11 and the latest dev version of qutebrowser.

    qutebrowser v1.3.0
    Git commit: 12e0edbcd (2018-05-24 08:47:31 +0200)
    Backend: QtWebEngine (Chromium 65.0.3325.151)

    CPython: 3.6.5
    Qt: 5.11.0
    PyQt: 5.10.1

**Comment by The-Compiler** [comment] 2018-05-28 19:56
This looks like [QTBUG-68174](https://bugreports.qt.io/browse/QTBUG-68174) which will be fixed in Qt 5.11.1.

I can reproduce it - it looks normal on https://webcamtoy.com/ but wrong on https://webcamtests.com/ like the bug report says.

**Closed by The-Compiler** 2018-05-28 19:56 UTC

**Comment by brianbuccola** [comment] 2018-05-28 20:01
Ah, I searched for "color" and for "camera", but nothing relevant came up. Thanks!
