### ISSUE TITLE
Hint mode and Navigation

### ISSUE THREAD

**Issue by frostmorn** [qutebrowser/qutebrowser#7562] opened 2023-01-24 10:21 UTC
**Version info**:
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.12, based on Chromium 87.0.4280.144
Qt: 5.15.8 (compiled 5.15.7)

**Description**
When are in a hint mode, you are able to scroll page with arrows.
This scroll doesn't affect hints which generated when you entering that mode, so them are just floating at the top of everything. So you, as a user could eventually open a page you haven't mean to open. It doesn't seem to be very critical, but feels a bit strange.

P.S.: that's the best browser I've ever seen, thnx guys :+1:

**Comment by The-Compiler** [comment] 2023-01-24 10:31
Duplicate of #1928

**Closed by The-Compiler** 2023-01-24 10:31 UTC
