### ISSUE TITLE
:jseval to return result

### ISSUE THREAD

**Issue by tex** [qutebrowser/qutebrowser#3729] opened 2018-03-16 09:14 UTC
It would be nice if :jseval returned result when called over pipe. Use-case is testing, remote control, when instance of qutebrowser runs and one wants to control it from other application. Currently it is possible to execute javascript, but it is impossible to retrieve data. Like currently open page, dom, ...

**Comment by The-Compiler** [comment] 2018-03-16 09:17
Duplicate of #902

**Closed by The-Compiler** 2018-03-16 09:17 UTC
Labels: qt: 5.11
