### ISSUE TITLE
Intercept URL open/navigate to open MPV

### ISSUE THREAD

**Issue by tamis-laan** [qutebrowser/qutebrowser#7119] opened 2022-04-10 14:35 UTC
I would like to intercept opening a new URL such that in case of youtube instead of following the URL (blockDefaultAction) mpv is used to stream the video. This would be way more convenient then any shortcut.

**Comment by The-Compiler** [comment] 2022-04-10 14:37
Duplicate of #6368

**Closed** 2022-04-10 14:37 UTC

**Comment by tamis-laan** [comment] 2022-04-10 14:40
I see,

For now, is there a way to programatically block yotube video pages? This way the user is forced to use the mpv shortcut forcing it into muscle memory.
