### ISSUE TITLE
Suggestion:add variable {selection}

### ISSUE THREAD

**Issue by xywwf** [qutebrowser/qutebrowser#3338] opened 2017-11-28 02:45 UTC
When i want bind <shift+g> to search selection text by google, i find it uneasy to do this job. I have to copy the selection to clipboard,and then parse the {clipboard} variable to the url, so is it posibble to add variable {selection} to get the user selected text?

**Comment by jgkamat** [comment] 2017-11-28 04:14
Depending on the method of how the text was selected, qt currently has a bug where we can't get the selected text easily: https://bugreports.qt.io/browse/QTBUG-53134.

If we are willing to make that limitation clear, I think this should be fairly easy to implement (just calling that method).

qtwebkit has a similar function we can use as well: http://doc.qt.io/archives/qt-5.5/qwebview.html#selectedText-prop

**Comment by The-Compiler** [comment] 2017-11-28 05:28
Duplicate of #901

**Closed by The-Compiler** 2017-11-28 05:28 UTC

**Comment by The-Compiler** [comment] 2017-11-28 05:30
Also note that I currently don't want to add more replacements before there's a way to escape them - unfortunately, that's quite a can of worms... see #2017 and #1861 for some discussion.

What you can do however is writing [a small userscript](https://github.com/qutebrowser/qutebrowser/blob/master/doc/userscripts.asciidoc) which uses `$QUTE_SELECTED_TEXT`.

**Comment by jgkamat** [comment] 2017-11-28 05:31
I prepared a very simple patch for this, but it's unlikely to get accepted into core until https://github.com/qutebrowser/qutebrowser/issues/2017 is done, since there's no way to escape `{substitutions}` (from @The-Compiler on IRC)

Here's the patch in case anyone wants it for later:
```
From e93f82d558a8cf23af4508f5794b1f6f198069dd Mon Sep 17 00:00:00 2001
From: Jay Kamat <jaygkamat@gmail.com>
Date: Tue, 28 Nov 2017 00:12:22 -0500
Subject: [PATCH] Add {selection} to command argument variables

---
 doc/help/commands.asciidoc              |  2 ++
 qutebrowser/commands/runners.py         |  1 +
 qutebrowser/mainwindow/tabbedbrowser.py | 11 +++++++++++
 qutebrowser/mainwindow/tabwidget.py     | 12 ++++++++++++
 4 files changed, 26 insertions(+)

diff --git a/doc/help/commands.asciidoc b/doc/help/commands.asciidoc
index 95caf24f1..27a3cb079 100644
--- a/doc/help/commands.asciidoc
+++ b/doc/help/commands.asciidoc
@@ -15,6 +15,8 @@ For command arguments, there are also some variables you can use:
 - `{url:pretty}` expands to the URL in decoded format
 - `{clipboard}` expands to the clipboard contents
 - `{primary}` expands to the primary selection contents
+- `{selection}` expands to the currently selected text. See
+   https://bugreports.qt.io/browse/QTBUG-53134 for limitations on webengine.
 
 It is possible to run or bind multiple commands by separating them with `;;`.
 
diff --git a/qutebrowser/commands/runners.py b/qutebrowser/commands/runners.py
index 095b49108..bbc05943d 100644
--- a/qutebrowser/commands/runners.py
+++ b/qutebrowser/commands/runners.py
@@ -65,6 +65,7 @@ def replace_variables(win_id, arglist):
             QUrl.DecodeReserved | QUrl.RemovePassword),
         'clipboard': utils.get_clipboard,
         'primary': lambda: utils.get_clipboard(selection=True),
+        'selection': lambda: tabbed_browser.current_selection()
     }
     values = {}
     args = []
diff --git a/qutebrowser/mainwindow/tabbedbrowser.py b/qutebrowser/mainwindow/tabbedbrowser.py
index c78c0eced..be84f7a47 100644
--- a/qutebrowser/mainwindow/tabbedbrowser.py
+++ b/qutebrowser/mainwindow/tabbedbrowser.py
@@ -250,6 +250,17 @@ class TabbedBrowser(tabwidget.TabWidget):
         idx = self.currentIndex()
         return super().tab_url(idx)
 
+    def current_selection(self):
+        """Get the selected text of the current tab.
+
+        Intended to be used from command handlers.
+
+        Return:
+            The selected text as a string.
+        """
+        idx = self.currentIndex()
+        return super().tab_selection(idx)
+
     def shutdown(self):
         """Try to shut down all tabs cleanly."""
         self.shutting_down = True
diff --git a/qutebrowser/mainwindow/tabwidget.py b/qutebrowser/mainwindow/tabwidget.py
index b14466337..554100f23 100644
--- a/qutebrowser/mainwindow/tabwidget.py
+++ b/qutebrowser/mainwindow/tabwidget.py
@@ -293,6 +293,18 @@ class TabWidget(QTabWidget):
         qtutils.ensure_valid(url)
         return url
 
+    def tab_selection(self, idx):
+        """Get selected text from the tab at the given index.
+
+        Return:
+            Text selected in the tab at idx.
+        """
+        tab = self.widget(idx)
+        if tab is None:
+            return None
+        else:
+            return tab.caret.selection()
+
 
 class TabBar(QTabBar):
 
-- 
2.11.0
```
