### ISSUE TITLE
Tab "Suspension"

### ISSUE THREAD

**Issue by Penaz91** [qutebrowser/qutebrowser#2936] opened 2017-08-29 12:23 UTC
I think it would be nice to have a feature that suspends inactive tabs, closing the rendering processes that are not being viewed or in a blacklist (like youtube), each tab would be reloaded as soon as it is brought to view.

This would make the browser+rendering processes use a lot less RAM.

Pinned tabs wouldn't be suspended, and it would be possible to have the browser suspend tabs that have been in the background for more than a certain amount of time.

**Comment by The-Compiler** [comment] 2017-08-29 12:45
Duplicate of #67

**Closed by The-Compiler** 2017-08-29 12:45 UTC
