### ISSUE TITLE
Dead lock freeze on linux

### ISSUE THREAD

**Issue by FAETHER** [qutebrowser/qutebrowser#5185] opened 2020-01-09 21:29 UTC
**Version info (see `:version`)**:
qutebrowser v1.8.3
Git commit: d38ade9ee (2019-12-31 16:55:22 +0100)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.0

CPython: 3.8.1
PyQt: 5.14.1

sip: 5.1.0
colorama: no
pypeg2: 2.15
jinja2: 2.10.3
pygments: 2.5.2
yaml: 5.1.2
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.4.8-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/ether/.cache/qutebrowser
config: /home/ether/.config/qutebrowser
data: /home/ether/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00

**Does the bug happen if you start with `--temp-basedir`?**:
Not sure, did not test explicitly yet.

**Description**
Browser randomly freezes entire system. Happens very randomly but seems like has something to do with playing videos on youtube, I also hang out on discord a lot so it may be specific to these websites. Does not matter what I do, I can be programming in vim or be on a different workspace and having browser run in the background still can just freeze everything. I use default i3 version 4.17.1. When such happens it looks like xserver is still functional but can't render anything. Giving any shortcuts commands from i3 does nothing. Can't move mouse, or do anything. Sometimes the freeze lasts 3-10 seconds and then recovers but sometimes it never recovers and I have to close the laptop lid and open quickly, by doing so the system becomes responsive again for like 2-4 seconds before locking up again and in that inverval I can switch to tty2 and sig kill qutebrowser or xorg. I can't make a switch otherwise. (This makes me question the nature of why can't keyboard handled? Maybe the problem is not in the browser but it's deps?) 

Note: 
This does not happen in any other browser, I used chromium && firefox, never had lockups like this. May may be due to new version of pyqt? I can't remember when exactly this started to happen, maybe beginning of December. I have not been using this broswer for very long time, so hard for me to say if this was before or not, since it happens randomly. 
One thing, I've tried to fix the problem myself, so I compiled the thing myself but did not find any log errors or whatever when running. Since when the bug happens I literaly can't do anything and this makes it very hard to debug, you can almost give a name "critical system crash". I think the lastest commit version will still have the same problem. 

More details: 
Host: Aspire VN7-793G V1.11
Kernel: 5.4.8-arch1-1
CPU: Intel i7-7700HQ (8) @ 3.800GHz
GPU: Intel HD Graphics 630
GPU: NVIDIA GeForce GTX 1060 Mobile

Installed drivers from arch repo: 

vulkan-intel 19.3.1-1 (I doubt this is supported by the browser)
xf86-video-ati 1:19.1.0-1
xf86-video-intel 1:2.99.917+899+gf66d3954-1
xf86-video-nouveau 1.0.16-1
xf86-video-vesa 2.4.0-2
xorg-server 1.20.6-3
linux-firmware 20191220.6871bff-1
xorg-server 1.20.6-3
xorg-xinit 1.4.1-1

i3-gaps 4.17.1-1
i3blocks 1.5-3
i3lock 2.12-1
i3status 2.13-2

**How to reproduce**
Just use the browser. This may be specific to my system.

**Comment by The-Compiler** [comment] 2020-01-09 21:31
Duplicate of #5178

**Closed by The-Compiler** 2020-01-09 21:31 UTC

**Comment by FAETHER** [comment] 2020-01-09 21:36
Thanks.
