### ISSUE TITLE
Text in rendered document in Overleaf is invisible

### ISSUE THREAD

**Issue by lrustand** [qutebrowser/qutebrowser#7886] opened 2023-09-03 12:36 UTC
**Version info**:

qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When using the online Latex editor Overleaf.com the text in the rendered document is invisible. This is working fine in version 2.5.4, but in 3.0.0 it is not.

**How to reproduce**

Open a document on Overleaf and render it. The text in the rendered document is invisible.

**Comment by lrustand** [comment] 2023-09-03 12:54
Here is version info from the working version (2.5.4):
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 5.15.14, based on Chromium 87.0.4280.144
Qt: 5.15.10 (compiled 5.15.8)

**Comment by lrustand** [comment] 2023-09-03 12:58
The first screenshot shows how it looks in 2.5.4, where the text is actually shown.
![2023-09-03-145620_1778x1009_scrot](https://github.com/qutebrowser/qutebrowser/assets/13719791/8b11b989-d8cf-4647-8e62-57d7f4404919)

The second screenshot is taken in Qutebrowser 3.0.0, and the text is invisible.
![2023-09-03-145633_1775x1014_scrot](https://github.com/qutebrowser/qutebrowser/assets/13719791/7b713b86-5368-4fa7-a59f-fc29f5948546)

**Comment by lrustand** [comment] 2023-09-03 13:03
This is what happens if I highlight the invisible text:

![2023-09-03-150254_1764x1016_scrot](https://github.com/qutebrowser/qutebrowser/assets/13719791/d5c80890-4280-4083-96de-78b3c26b131c)

**Comment by toofar** [comment] 2023-09-04 09:04
Thanks for the report! Can you please check if you can reproduce with these pages too? https://github.com/qutebrowser/qutebrowser/issues/7489#issuecomment-1471352491

**Comment by lrustand** [comment] 2023-09-04 16:18
The excel document seems to look normal to me, but the pdfjs is weird. Pdfjs has had this weird double text thing for me on all my computers for probably almost a year.

![2023-09-04-181323_1881x838_scrot](https://github.com/qutebrowser/qutebrowser/assets/13719791/e9a33425-4351-4a9f-b05c-e0d0ea79a33b)
![2023-09-04-181336_1087x937_scrot](https://github.com/qutebrowser/qutebrowser/assets/13719791/b4a838b7-cd04-4dd3-9dc2-63a5dbe638d9)

**Comment by toofar** [comment] 2023-09-04 20:24
Hmm, well can you try adding `"disable-accelerated-2d-canvas"` to the `qt.args` setting anyhow and seeing if that helps?

**Comment by The-Compiler** [comment] 2023-09-06 13:56
I doubt this is an issue of v2.5.4 vs. v3.0.0 - it sounds more like a Qt 5 vs. Qt 6 thing. Could you try with:

- `--temp-basedir --qt-flag "disable-accelerated-2d-canvas"` (which is equivalent to what @toofar asked, but temporary)
- `--temp-basedir --qt-wrapper PyQt5` (which runs v3.0.0 but with Qt 5, which I assume will work)

**Comment by lrustand** [comment] 2023-09-06 16:15
Okay, both of the suggestions works to fix the problem

**Comment by toofar** [comment] 2023-09-06 20:36
Alright, I'll close this as a duplicate of #7489. And add that one to the 3.0.1 milestone so we might actually do something about it since it continues to be an issue.

**Closed by toofar** 2023-09-06 20:36 UTC
Labels: status: can't reproduce, status: needs triage
