### ISSUE TITLE
Switching to a previously invisible window sends a tab key

### ISSUE THREAD

**Issue by rien333** [qutebrowser/qutebrowser#4887] opened 2019-07-04 07:17 UTC
**Version info (see `:version`)**:

qutebrowser v1.6.3
Git commit: 012f11ab3 (2019-07-03 21:58:02 +0200)
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.3
Qt: 5.13.0
PyQt: 5.12.3

sip: 4.19.17
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.1.15-arch1-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

I noticed that every time I switched to a desktop that had a qutebrowser window open it would scroll all the way to the top of the page. Using `-T -l debug`, I found out that if a previously invisible window becomes focused it sends a `Tab` key: 
```
08:57:56 DEBUG    misc       app:on_focus_object_changed:845 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f38d8157168>
08:57:58 DEBUG    modes      modeman:_handle_keypress:172 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
08:57:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Got key: 0x1000001 / modifiers: 0x0 / text: '<Tab>' / dry_run False
08:57:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Trying match without modifiers
08:57:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Trying match with key_mappings
08:57:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Giving up with '<Tab>', no matches08:57:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Clearing keystring (was: <Tab>).
08:57:58 DEBUG    modes      modeman:_handle_keypress:199 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: False --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7f38d8157168>)08:57:58 DEBUG    modes      modeman:_handle_keyrelease:219 filter: False08:57:58 DEBUG    misc       app:on_focus_object_changed:845 Focus object changed: None
08:58:19 DEBUG    misc       app:on_focus_object_changed:845 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f38d8157168>
```
Fortunately, I don't I use the `Tab` all that often. Is there any way to disable it for qutebrowser? Let it send a `noop` or something? 

I kinda suspect that not a lot of people can reproduce it, and that it is a QtWebEngine particular to my/an arch install, just like #4883.

**How to reproduce**
Go to a random web page, switch back and forth between the desktop, and qutebrowser will have entered a tab key. I'm using bspwm btw, it still happens without `libinput-gestures` or `sxkhd` running.

**Comment by The-Compiler** [comment] 2019-07-04 07:28
Duplicate of #4579

**Closed by The-Compiler** 2019-07-04 07:28 UTC
