### ISSUE TITLE
can you build appimage file format

### ISSUE THREAD

**Issue by newyorkthink** [qutebrowser/qutebrowser#7433] opened 2022-10-14 03:26 UTC
the appimage file format is can run everywhere, it not us to apt-get.
the appimage is modern file format in linux.

can you building qute browser appimage

**Comment by The-Compiler** [comment] 2022-10-14 05:59
Duplicate of #1912, note there's already a Flatpak and virtualenv installs though. I'm not going to maintain a third variant, but if someone else does, I probably wouldn't say no.

**Closed by The-Compiler** 2022-10-14 05:59 UTC
