### ISSUE TITLE
Hints Don't Stay Tied to Content when Scrolling

### ISSUE THREAD

**Issue by SentToDevNull** [qutebrowser/qutebrowser#3681] opened 2018-03-07 00:39 UTC
Steps to reproduce:

1. Type 'f' for hints.
2. Scroll down.

**Comment by jgkamat** [comment] 2018-03-07 00:44
Duplicate of #1928

I noticed that vimium does this, so maybe we can figure out how they are doing it :)

**Closed by jgkamat** 2018-03-07 00:44 UTC
Labels: bug: behavior, component: hints
