### ISSUE TITLE
Builtin adblock doesn't block youtube video ads

### ISSUE THREAD

**Issue by figos33** [qutebrowser/qutebrowser#6838] opened 2021-11-21 14:59 UTC
**Version info**:
2.0.2

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
I have updated the adblock list in qutebrowser, and still it can't block video ads in youtube.
It would be nice if the functionality of adblock was similar to that of ublock origin on chrome, or there was capability to use extensions of chrome.

**How to reproduce**
open any youtube video and be bombarded with ads

**Comment by The-Compiler** [comment] 2021-11-21 15:22
Duplicate of #6480

**Closed by The-Compiler** 2021-11-21 15:22 UTC
