### ISSUE TITLE
window splitted horizontally when using middle click to open link in new tab

### ISSUE THREAD

**Issue by rezaarifandee** [qutebrowser/qutebrowser#3965] opened 2018-05-30 05:34 UTC
http://paste.the-compiler.org/view/9166c5a3

![Screenshot of the bug](http://i66.tinypic.com/2vwwmis.png)

This also happen when using Shift+Left Click, or anything that open links on a new window or tab.

**Comment by The-Compiler** [comment] 2018-05-30 05:38
Duplicate of #3920

**Closed by The-Compiler** 2018-05-30 05:38 UTC
