### ISSUE TITLE
Airbnb Crash (Status 139)

### ISSUE THREAD

**Issue by mdcnuydt** [qutebrowser/qutebrowser#6944] opened 2022-01-07 10:27 UTC
**Version info**:
qutebrowser v2.4.0
Git commit:
Backend: QtWebEngine 5.15.8, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.10.1
PyQt: 5.15.6

On Arch linux:
Linux Arch 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Qutebrowser crashes when vistiting listing pages on Airbnb.com. It says: 

"Unable to load page
Error while opening https://www.airbnb.co.uk/hosting/listings
Renderer process crashed (status 139)"

Only encountered it yet on the Airbnb website. Does not happen on Firefox.

PS: Massive fan of QT, so keep up the good work! (but need Airbnb for work)

**How to reproduce**
Go to a listing (e.g. [this one](https://www.airbnb.co.uk/s/Stratford--London/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_dates%5B%5D=february&flexible_trip_dates%5B%5D=january&flexible_trip_lengths%5B%5D=weekend_trip&date_picker_type=calendar&query=Stratford%2C London&place_id=ChIJh5ur8oun2EcRivsgVunTab0&checkin=2022-04-15&checkout=2022-04-18&adults=2&source=structured_search_input_header&search_type=autocomplete_click)) and after a few seconds, mayba a minute, the site crashes.

**Comment by The-Compiler** [comment] 2022-01-07 10:31
Duplicate of #6851

**Closed by The-Compiler** 2022-01-07 10:31 UTC
