### ISSUE TITLE
Passthrough mode setting with URL patterns

### ISSUE THREAD

**Issue by BurnyBoi** [qutebrowser/qutebrowser#5524] opened 2020-06-14 20:13 UTC
Similar to `input.insert_mode.auto_enter`, but for passthrough mode. The main reason I ask is so that I can also have this with URL patterns supported. This would allow me to always have passthrough mode on for when I go to play Town of Salem

**Comment by The-Compiler** [comment] 2020-07-03 09:14
Taking the freedom to rename this issue a bit, as I don't think this would be related to `input.insert_mode.auto_enter` - the existing `auto_enter` setting controls whether insert mode is entered when an element supporting it is clicked, while that wouldn't be the case for passthrough mode.

One possible solution for this would be autocmds (#35), though I suppose a setting would make things easier to e.g. leave passthrough mode again when switching away from a tab it's enabled for (also see `tabs.mode_on_change`).

**Comment by phrxmd** [comment] 2020-07-06 15:57
I would also be happy if I could have a facility to load *all* URLs in passthrough mode by default. 
I use Qutebrowser as a Rambox/Franz/Station replacement (essentially as the interface to a fixed number of web clients of popular messengers), so there is not much loading/closing/manipulation of tabs, it's essentially all about entering, copying and pasting text. For that, it would be convenient to be in passthrough mode already when I load up the browser, either per-tab or per-browser, not only per-URL.

**Comment by The-Compiler** [comment] 2020-07-06 15:58
@phrxmd FWIW you can probably launch something like `qutebrowser --basedir ... ':later 100 enter-mode passthrough'` for that.

**Comment by phrxmd** [comment] 2020-07-06 16:02
@The-Compiler Thanks, that's very neat, but it works only for the tab that is open on startup, not for all other tabs (I launch my qutebrowser-messenger instance with a number of fixed tabs for all the messengers I'm using) :)

**Comment by The-Compiler** [comment] 2020-07-06 16:03
@phrxmd Ah, right. It should work if you set `tabs.mode_on_change` to `persist`, though!

**Comment by phrxmd** [comment] 2020-07-06 16:05
@The-Compiler it does, thanks!

**Comment by iNecas** [comment] 2022-04-29 08:46
Seems like after https://github.com/qutebrowser/qutebrowser/pull/7000 this is now possible with:

```
set -u some-page.exmple.com input.mode_override passthrough
```

**Comment by The-Compiler** [comment] 2022-04-29 09:02
It is indeed, thanks @iNecas - looks like this was a duplicate of #4960 all along, but nobody noticed :sweat_smile:

**Closed by The-Compiler** 2022-04-29 09:02 UTC
Labels: component: keyinput, component: config, priority: 2 - low
