### ISSUE TITLE
Display small help on args when a cmd is entered/selected in the completion list

### ISSUE THREAD

**Issue by bzbug** [qutebrowser/qutebrowser#6921] opened 2021-12-30 10:23 UTC
When user enters any `:` cmd, display an additional help section above the completion box, and in this section describe in short what args the entered cmd has and what they mean - similarly to how `--help` works for most CLI tools on Linux.

# Do it when
1. The entered cmd has or hasn't any completions - display the help above them.
2. The cmd is entered fully with or without space after it.
3. The cmd is only entered partially and then the user has navigated through the completion list, the idea is that the help section should change every time the user navigates through the completion list of _root_ cmds.
4. The cmd is entered fully and has any number of arguments already entered as well.

# Do it how
When you enter `:open` in CMD mode, you see multiple sections of things to use with the cmd: search engines, bookmarks, history etc. What about a text box in another section `cmd help` above all those? And, of course, an option in settings to turn it off. _Or_ maybe create an alternative key like `:` that would also mean entering a cmd, but with the help box included, so that users could look things up only when they need it and not bother with it otherwise (press `:` - and enter any command like normal, press `;` - same thing, but help box will be shown for any cmd you enter).

I think it will help new users to learn and memorize all the powerful details of the browser and old users to notice and adapt on the fly to changing cmds and their arguments after each update.

**Comment by The-Compiler** [comment] 2021-12-30 10:33
Duplicate of #55

**Closed by The-Compiler** 2021-12-30 10:33 UTC
