### ISSUE TITLE
The tab title shows 0% even when the tab is fully loaded

### ISSUE THREAD

**Issue by phenax** [qutebrowser/qutebrowser#6361] opened 2021-04-06 07:21 UTC
**Version info**:
```
qutebrowser v2.1.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2
```

**Does the bug happen if you start with `--temp-basedir`?**:
Couldn't reproduce with temp-dir so far but this only occurs sometimes for me. Will try to reproduce it with temp-dir later and update this issue.

**Description**
The tab title shows 0% even after the tab is loaded. It corrects itself on reload.

![part-2021_04_06_12_48_55](https://user-images.githubusercontent.com/11407672/113673349-809ef180-96d6-11eb-9e33-b890114de90d.jpg)

**How to reproduce**
Couldn't find the right steps to reproduce this but it just happens on regular use.

**Comment by The-Compiler** [comment] 2021-04-06 07:22
Duplicate of #6276

**Closed by The-Compiler** 2021-04-06 07:22 UTC
