### ISSUE TITLE
redirect domain

### ISSUE THREAD

**Issue by tamis-laan** [qutebrowser/qutebrowser#6339] opened 2021-03-28 19:31 UTC
It would be nice if we could redirect one domain to another in config, in my case I would like to redirect:
```
reddit.com ----> old.reddit.com
```

**Comment by The-Compiler** [comment] 2021-03-28 20:00
Duplicate of #5476

**Closed by The-Compiler** 2021-03-28 20:00 UTC

**Comment by bitraid** [comment] 2021-03-28 20:25
I'm using greasemonkey scripts like [this one](https://gist.github.com/bitraid/d1901de54382532a03b9b22a207f0417) for redirects, which is simpler and works better than the one posted in https://github.com/qutebrowser/qutebrowser/issues/5476#issuecomment-638066941.
