### ISSUE TITLE
Input mode is unusable on Google pages (docs/gmail)

### ISSUE THREAD

**Issue by teon** [qutebrowser/qutebrowser#3980] opened 2018-06-07 09:19 UTC
After upgrading from 1.2.x to 1.3.x input mode stopped working for google webpages - mainly for Gmail and Google Docs.
I enter the input mode and randomly (after keystroking enter, or shift or sometimes just after some time) the browser leaves the input mode. Sometimes I just enter a sentence in the docs and it happens.

I'm not having any issues now when in input mode at github (or any other pages - gitlab, .,..) - just google products.

```
qutebrowser v1.3.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.11-1-zen-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Comment by mschilli87** [comment] 2018-06-07 09:22
dupliacte of https://github.com/qutebrowser/qutebrowser/issues/3596?

**Comment by The-Compiler** [comment] 2018-06-07 09:34
Duplicate of #3596

**Closed by The-Compiler** 2018-06-07 09:34 UTC
