### ISSUE TITLE
Resource Error (fork failure): Cannot allocate memory 

### ISSUE THREAD

**Issue by bunwayenterprises** [qutebrowser/qutebrowser#4971] opened 2019-08-18 04:47 UTC
**Version info**:

I am currently running with the following:

- arch with the lts kernel (4.19.66-1-lts)
- sway version 1.0
- qutebrowser v1.7.0 (full details below)

**Does the bug happen if you start with `--temp-basedir`?**:

Uncertain - I cannot reproduce on demand, it only happens after running qutebrowser for an indeterminate period of time.

**Description**

Currently seeing a bug after running qutebrowser for an indeterminate period of time (a few hours to a few days).

The issue shows when trying to spawn an external command, such as opening an editor to edit the url or spawn a userscript.

Error is shown in the error message bar at the bottom of the screen as ```Resource Error (fork failure): Cannot allocate memory ```.

Following failure, the browser will continue to run, however upon quitting it will then crash and prompt with the bug report form.

**How to reproduce**

Run qutebrowser for a while and eventually you will be unable to open an editor window or spawn a userscript.

Currently experiencing it when actioning these commands as outlined in ```config.py```

- ```config.bind(';i', 'hint all spawn ~/scripts/system/urlparser.sh {hint-url}')```
- ```config.bind('<Alt-e>', 'edit-url')```

Editor is set as:

- ```c.editor.command = ['termite', '--title', 'qutebrowser_nvim', '--exec', 'nvim {}']```

Environment variables are:

- ```export QT_AUTO_SCREEN_SCALE_FACTOR=0```
- ```export QT_SCALE_FACTOR=1.5```
- ```export QT_QPA_PLATFORM=wayland-egl```

**NOTE** - This never used to happen when running qutebrowser on X, however I have upgraded a couple of versions of qutebrowser/qtwebengine since switching over to wayland/sway so uncertain if this is related.

Qutebrowser version details

```
qutebrowser v1.7.0
Git commit:
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.4
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.2.228 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-4.19.66-1-lts-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt  
```

**Stacktrace**

I don't currently have a stacktrace to add, I didn't succesfully capture it during the last crash. I will update the ticket with it when it next occurs.

**I love this browser** - Thanks for all you do :smile:

**Comment by jgkamat** [comment] 2019-08-18 05:16
Bun writes:

> The issue shows when trying to spawn an external command, such as opening an 
> editor to edit the url or spawn a userscript.

Sounds like a duplicate of 
http://www.github.com/qutebrowser/qutebrowser/issues/4725

**Comment by The-Compiler** [comment] 2019-08-18 15:39
Agreed!

**Closed by The-Compiler** 2019-08-18 15:39 UTC
