### ISSUE TITLE
'set editor.command' does not work when chained to 'open-editor'

### ISSUE THREAD

**Issue by dnebauer** [qutebrowser/qutebrowser#4509] opened 2019-01-05 17:33 UTC
Version info: https://paste.the-compiler.org/view/82e96c45

I'm trying to work around `editor.command` not recognising url patterns. I tried the following in `config.py`:

```python
config.bind('<ctrl-w>', 'set editor.command "[\'gvim\', \'-f\', \'{file}\', \'-c\', \'normal {line}G{column0}l\', \'-c\', \'set filetype=tiddlywiki\']" ;; open-editor ;; set editor.command "[\'gvim\', \'-f\', \'{file}\', \'-c\', \'normal {line}G{column0}l\']"', mode='insert')
```

In short, it adds `-c 'set filetype=tiddlywiki'` to the default `editor.command`, executes `open-editor`, and resets the default `editor.command`.

When I press `<Ctrl-w>` in a textarea it launches gvim with the default `editor.command`, i.e., the changing of `editor.command` fails to have any effect.

Here is the relevant log extract:

```
command called: set ['editor.command', "['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l', '-c', 'set filetype=tiddlywiki']"]

Calling qutebrowser.config.configcommands.ConfigCommands.set(<qutebrowser.config.configcommands.ConfigCommands object at 0x7fcf36a4da58>, 2, 'editor.command', "['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l', '-c', 'set filetype=tiddlywiki']", True, True, pattern=None)

Setting editor.command (type ShellCommand) to ['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l', '-c', 'set filetype=tiddlywiki'] (converted from "['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l', '-c', 'set filetype=tiddlywiki']")

Config option changed: editor.command = ['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l', '-c', 'set filetype=tiddlywiki']

editor.command = ["gvim", "-f", "{file}", "-c", "normal {line}G{column0}l", "-c", "set filetype=tiddlywiki"]

command called: open-editor

Calling qutebrowser.browser.commands.CommandDispatcher.open_editor(<qutebrowser.browser.commands.CommandDispatcher>)

command called: set ['editor.command', "['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l']"]

Calling qutebrowser.config.configcommands.ConfigCommands.set(<qutebrowser.config.configcommands.ConfigCommands object at 0x7fcf36a4da58>, 2, 'editor.command', "['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l']", False, False, pattern=None)

Setting editor.command (type ShellCommand) to ['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l'] (converted from "['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l']")

Config option changed: editor.command = ['gvim', '-f', '{file}', '-c', 'normal {line}G{column0}l']

Marking yaml-config as dirty.

Got element from JS: {'attributes': {'placeholder': 'Type the text for this tiddler', 'style': 'animation: none 0s ease 0s 1 normal none running; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(248, 248, 248); background-blend-mode: normal; border: 1px solid rgb(204, 204, 204); border-radius: 0px; border-collapse: separate; bottom: auto; box-shadow: none; box-sizing: border-box; break-after: auto; break-before: auto; break-inside: auto; caption-side: top; clear: none; clip: auto; color: rgb(51, 51, 51); cursor: text; direction: ltr; display: block; empty-cells: show; float: none; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol"; font-kerning: auto; font-size: 14px; font-stretch: 100%; font-style: normal; font-variant: normal; font-weight: 400; height: 100px; image-rendering: auto; isolation: auto; place-items: normal; place-self: auto; left: auto; letter-spacing: normal; line-height: 18…

Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<textarea placeholder="Type the text for this tiddler" style="animation: none 0s ease 0s 1 normal none running; background: none 0% 0% / auto repeat scroll padding-box border-box rgb(248, 248, 248); background-blend-mode: normal; border: 1px solid rgb(204, 204, 204); border-radius: 0px; border-collapse: separate; bottom: auto; box-shadow: none; box-sizing: border-box; break-after: auto; break-before: auto; break-inside: auto; caption-side: top; clear: none; clip: auto; color: rgb(51, 51, 51); c…'>

Calling "gvim" with args ['-f', '/tmp/qutebrowser-editor-h8yavjtu', '-c', 'normal 1G0l']

Starting process.
```

It appears to show that `editor.command` is successfully changed, but then ignored by `open-editor` which uses the default `editor.command`. Is this a bug or an undocumented feature, and can this approach be made to work?

**Comment by The-Compiler** [comment] 2019-01-05 18:30
Commands in qutebrowser are run asynchronously, so you're effectively switching the setting back before the editor gets spawned. You might get away with combining it with `:later` to wait for a bit before setting it back.

I thought there was an issue for making `;;` wait until a command "finished" somewhere, but I can't find it right now.

As a fun thought exercise: When would something chained to `:open-editor` run? When the editor is opened? When the text is saved the first time? When it's closed? :wink:

**Comment by The-Compiler** [comment] 2019-01-05 18:32
Duplicate of #3007

**Closed by The-Compiler** 2019-01-05 18:32 UTC
Labels: status: needs triage

**Comment by jgkamat** [comment] 2019-01-05 22:17
dnebauer writes:

> I'm trying to work around `editor.command` not recognising url patterns. I tried the following in `config.py`:

You could also add url pattern support to editor.command directly, which is
probably a little cleaner.

**Comment by dnebauer** [comment] 2019-01-06 00:58
@jgkamat That would solve my current use case, provided the url pattern includes port number, since the domain in question is `http://localhost:10744`.

**Comment by dnebauer** [comment] 2019-01-06 03:37
@The-Compiler Thanks for the pointer to `:later`. I had looked at using it, but misread the documentation  ("With this command, ;; is interpreted literally instead of splitting off a second command") to mean it could not be used with chained commands.

This is working reliably for me now:
```python
config.bind('<ctrl-w>', 'set editor.command "[\'gvim\', \'-f\', \'{file}\', \'-c\', \'normal {line}G{column0}l\', \'-c\', \'set filetype=tiddlywiki\']" ;; later 30 open-editor ;; later 500 set editor.command "[\'gvim\', \'-f\', \'{file}\', \'-c\', \'normal {line}G{column0}l\']"', mode='insert')
```
This may or may not be a more lucid way of assembling the same bind command:
```python
editor_tw = ''.join([
    'set editor.command "[',
    '\'gvim\', ',
    '\'-f\', \'{file}\', ',
    '\'-c\', \'normal {line}G{column0}l\', ',
    '\'-c\', \'set filetype=tiddlywiki\'',
    ']"',
])
editor_open = ''.join([
    'later 30 ',
    'open-editor',
])
editor_default = ''.join([
    'later 500 ',
    'set editor.command "[',
    '\'gvim\', ',
    '\'-f\', \'{file}\', ',
    '\'-c\', \'normal {line}G{column0}l\'',
    ']"',
])
editor_bind = ' ;; '.join([
    editor_tw,
    editor_open,
    editor_default,
])
config.bind('<ctrl-w>', editor_bind, mode='insert')
```
I could possibly reduce those millisecond counts further, but these are small enough I don't notice the delay.

With regard to your question about when something chained to `:open-editor` would run, I always assumed it would be immediately after the command associated with `:open-editor` was issued to the operating system. Others, of course, may have different views.

Thanks again for the world's best browser.
