### ISSUE TITLE
no service found for - "org.qt-project.qt.mediaplayer"

### ISSUE THREAD

**Issue by xtuc** [qutebrowser/qutebrowser#1962] opened 2016-09-18 12:39 UTC
I'm not able to play HTML5 video (Youtube) and audio (Soundcloud). I guess Soundcloud uses the Web Audio API.

Thanks in advance,
Sven.
### HTML5 test audio / video

![screen shot 2016-09-18 at 14 30 37](https://cloud.githubusercontent.com/assets/1493671/18615660/933b9fde-7dac-11e6-9f60-94d9c15d91eb.png)
### QuteBrowser logs

First line is on Youtube and the following are on Soundcloud.

```
14:23:00 WARNING qt Unknown module:none:0 defaultServiceProvider::requestService(): no service found for - &quot;org.qt-project.qt.mediaplayer&quot;
14:25:39 WARNING qt Unknown module:none:0 defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
14:25:39 WARNING qt Unknown module:none:0 defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
14:25:39 WARNING qt Unknown module:none:0 defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
14:25:39 WARNING qt Unknown module:none:0 defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"
```
### Version info

qutebrowser v0.7.0
Git commit: v0.7.0-1-g5c1401b (2016-06-10 16:29:35 +0200)

CPython: 3.5.1
Qt: 5.6.1, runtime: 5.6.1
PyQt: 5.6
Style: QMacStyle
Desktop: None
sip: 4.18
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.8
pygments: 2.1.3
yaml: 3.11
cssutils: 1.0.1 $Id$
typing: yes
pdf.js: 1.4.20 (bundled)
Webkit: 538.1
Harfbuzz: system
SSL: Secure Transport, OS X El Capitan (10.11)

Frozen: True
Platform: Darwin-15.0.0-x86_64-i386-64bit, 64bit
OS Version: 10.11.1, x86_64

**Comment by The-Compiler** [comment] 2016-09-18 12:51
Are you using the `.app` from the releases page? Can you try with the 0.8.2 one please?

**Comment by xtuc** [comment] 2016-09-18 13:06
I downloaded qutebrowser v0.7.0 from the Github release page.

Same result on 0.8.2.

**Comment by The-Compiler** [comment] 2016-09-18 13:19
Okay - my first guess would be that there's a plugin file missing from the `.dmg`/`.app`, but it'll probably take me a little while until I find the time to investigate.

**Comment by xtuc** [comment] 2016-09-18 13:30
I don't exactly know which layer is responsible for this. Wouldn't be interesting that I try with Blink ? _(I'm a bit worried about building the project on Mac)._

**Comment by The-Compiler** [comment] 2016-11-02 19:00
I can indeed reproduce this with the `.dmg`/`.app`, while a manual install works fine. Not sure what's missing though...

**Comment by The-Compiler** [comment] 2016-11-02 20:55
According to [this thread](https://forum.qt.io/topic/28620/solved-qtmultimedia-defaultserviceprovider-requestservice-no-service-found-for-org-qt-project-qt-mediaplayer/17) this is because the `mediaservice` plugin directory is needed. That's pulled in by PyInstaller when `PyQt5.QtMultimedia` is used, but apparently PyInstaller doesn't know about the implicit QtMultimedia dependency by QtWebKit.

I think this could be solved by adding `PyQt5.QtMultimedia` to `hiddenimports` in `misc/qutebrowser.spec` and then doing a PR to PyInstaller to add it in their [QtWebKit hook file](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-PyQt5.QtWebKit.py) too.

Unfortunately I ran out of time here, I'll look at this whenever I feel like doing some OS X stuff next time :laughing:

**Comment by The-Compiler** [comment] 2017-03-27 08:37
This should be fixed now that the OS X builds use QtWebEngine.

**Closed by The-Compiler** 2017-03-27 08:37 UTC
Labels: os: OS X, priority: 1 - middle
