### ISSUE TITLE
BitDefender does not like qutebrowser 1.4.2

### ISSUE THREAD

**Issue by KnottyTomatoes** [qutebrowser/qutebrowser#4269] opened 2018-09-29 14:56 UTC
I usually have this installed visa Chocolaty, running on Windows 7 64-bit, today I updated qutebrowser from 1.4.1 to 1.4.2 (with Chocolaty) and out of the blue my anti-virus BitDefender has detected a threat with "qutebrowsers.exe" and says it "Gen:Variant.Razy.393423" which it has never done before today.
So I downloaded the portable version of 1.4.2 from github and extracted it, got the same thing as with Chocolaty. I also downloaded the portable version of 1.4.1 and BitDefender does not detect a threat with this version of qutebrowser.exe.
I have a feeling this is a false positive, but I felt I should post this either way since I couldn't find any posts relating to this.

Also I did a scan with VirusTotal as well, on the 1.4.2 qutebrowser.exe file.
https://www.virustotal.com/#/file/eebce4e768e3a153f1e3227ce96b08fb08b18d4014c5d252b9e5717086a2374c/detection

**Comment by toofar** [comment] 2018-09-29 23:31
Looks like the standard response is https://github.com/pyinstaller/pyinstaller/issues/2500#issuecomment-286097333
> Please contact you anti-virus vendor. There is nothing we can do about this false positive.

> If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is nothing we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

Great.

**Comment by The-Compiler** [comment] 2018-09-30 11:37
I can reproduce this with a freshly built v1.4.2 (and also when I rebuild v1.4.1 now), but when I build the current master branch, only "Jiangmin" detects "Trojan.Generic.cqozq". `¯\_(ツ)_/¯`

**Comment by KnottyTomatoes** [comment] 2018-10-03 20:20
Sorry for my late rely.
I had reported this to Bitdefender, and it has been both fixed on my end. 1.4.2 does now work, I also just downloaded 1.5.0 and it also works without issue from Bitdefender. For now. :D
However, going forward I will likely use the portable/standalone version instead of chocolaty.

**Comment by The-Compiler** [comment] 2018-10-03 20:44
Closing this then - thanks for reporting it to Bitdefender as well!

Checking the v1.5.0 `qutebrowser.exe` via VirusTotal, Avira and "Forcepoint ThreatSeeker" (as in "seeking threats where there aren't any"?) detect it as Malware.

I've contacted Avira at https://analysis.avira.com/en/submit - haven't found an easy way to submit false positives to Forcepoint so I won't care.

**Closed by The-Compiler** 2018-10-03 20:44 UTC
