### ISSUE TITLE
Screenshare not working

### ISSUE THREAD

**Issue by orangecms** [qutebrowser/qutebrowser#5784] opened 2020-10-10 20:56 UTC
**Version info**:
```
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

When attempting screenshare - tried with Jitsi -, `qutebrowser` prompts to accept, but after accepting, only errors with the following message in stdout:
```
[1902764:1902764:1010/224849.652974:ERROR:pulse_util.cc(300)] pa_operation is nullptr.
```

**How to reproduce**

Go to https://meet.jit.si/qutebrowser4ever and use the second button in the bottom left (appearing on hover) to attempt sharing the screen.

**Comment by The-Compiler** [comment] 2020-10-10 21:05
I can reproduce, but the same happens in Falkon as well - so probably a QtWebEngine issue. I'll investigate later and report it upstream.

**Comment by The-Compiler** [comment] 2020-10-30 13:12
There were two related fixes pushed to Qt recently:

- [Do not set audio device for desktop capture if audio loopback is unsupported (Ifb13bce3) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/319725)
- [Fix getDefaultScreenId on X11 (I8e513aa4) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/319623)

With those two applied on top of the current Qt 5.15.2 branch, screen sharing works fine again with Jitsi - I hope those two patches will still make it into Qt 5.15.2 (which is due to be released in Tuesday, so it's questionable whether low-priority fixes are still accepted), but if not, they'll be in Qt 5.15.3.

Nothing more for qutebrowser to be done here, so I'm closing this - thanks for the detailed report!

**Closed by The-Compiler** 2020-10-30 13:12 UTC
Labels: bug: behavior, component: QtWebEngine, priority: 1 - middle, status: needs triage

**Comment by The-Compiler** [comment] 2020-11-10 13:24
Looks like Qt 5.15.2 is delayed a bit, but still, [the second fix](https://codereview.qt-project.org/c/qt/qtwebengine/+/319623) didn't make it in time. It'll be in Qt 5.15.3, which doesn't have a schedule so far.
