### ISSUE TITLE
[Feature Request] Expose a way to run commands automatically on tab switch/opening links

### ISSUE THREAD

**Issue by wz1000** [qutebrowser/qutebrowser#2884] opened 2017-08-03 19:34 UTC
I need different userstyles for different domains. I've almost achieved this with a dirty hack involving a userscript that sets the userstyle depending on the `QUTE_URL` and appending ` ;; spawn --userscript ...` to every command that deals with tabs or opening new urls(next tab, close tab, open in new tab, open etc.),  but this doesn't work when I use the mouse to switch tabs or open a link. If there was some way to register commands to be automatically run when opening new urls or switching tabs, I would have a robust solution.

**Comment by The-Compiler** [comment] 2017-08-03 19:43
Duplicate of #35. Also see #30. By the way, per-domain settings (#27) will come later this year, possibly even in September depending on how fast the new-config branch is merged.

**Closed by The-Compiler** 2017-08-03 19:43 UTC
