### ISSUE TITLE
Blacklist entrys from History

### ISSUE THREAD

**Issue by r00tbox** [qutebrowser/qutebrowser#2809] opened 2017-07-12 09:01 UTC
I often use qutebrowser to visualize html mails, so i create a temporary file (e.g. `file:///tmp/mu4e-1648999ey.html`) and open it with qutebrowser.

All these entrys are useless in my History, so it would be a nice feature to blacklist them like `Blacklist: file:///tmp/*`

**Comment by The-Compiler** [comment] 2017-07-12 09:03
This should be easy once the new config and general infrastructure for per-URL settings are in. Then it can simply be a per-domain `write_to_history` (or so) setting.

**Comment by lahwaacz** [comment] 2017-07-12 09:10
Duplicate of #1768?

**Comment by The-Compiler** [comment] 2017-07-12 09:12
Hmm, it's certainly similar (I guess the point has come where I can't keep >450 issues in my head 😆), but one talks about just blacklisting it from the completion, while here it'd probably be most useful to not have them in the history at all (though I imagine it wouldn't hurt much either way)?

**Comment by The-Compiler** [comment] 2017-07-12 11:36
I added a comment to #1768 now, so I'm closing this one.

**Closed by The-Compiler** 2017-07-12 11:36 UTC
Labels: component: config, priority: 2 - low
