### ISSUE TITLE
New line in ipc

### ISSUE THREAD

**Issue by JingMatrix** [qutebrowser/qutebrowser#7266] opened 2022-06-18 00:38 UTC
**Version info**:

```
qutebrowser v2.5.1
Git commit: ba6db7793 on qt6-v2 (2022-06-18 02:23:28 +0200)
Backend: QtWebEngine 6.2.4, based on Chromium 90.0.4430.228
Qt: 6.2.4 (compiled 6.2.3)

CPython: 3.10.5
PyQt: 6.2.3

sip: no
colorama: 0.4.4
jinja2: 3.0.3
pygments: 2.11.2
yaml: 6.0
adblock: 0.5.1
PyQt6.QtWebEngineCore: 6.2.1
pdf.js: 2.14.305 (/home/jing/.local/share/qutebrowser/pdfjs/build/pdf.js)
sqlite: 3.38.5
QtNetwork SSL: OpenSSL 3.0.3 3 May 2022

Style: Qt6CTProxyStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.0.5
Platform: Linux-5.15.0-35-generic-x86_64-with-glibc2.35, 64bit
Linux distribution: Ubuntu Kinetic Kudu (development branch) (ubuntu)
Frozen: False
Imported from /home/jing/Documents/Project/qutebrowser/qutebrowser
Using Python from /bin/python3
Qt library executable path: /usr/lib/qt6/libexec, data path: /usr/share/qt6

Paths:
cache: /home/jing/.cache/qutebrowser
config: /home/jing/.config/qutebrowser
data: /home/jing/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Autoconfig loaded: no
Config.py: /home/jing/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00
```
**Does the bug happen if you start with `--temp-basedir`?**:

yes

**Description**

ipc could not handle search strings containing newline

**How to reproduce**

Search any string contains newline through ipc

**Comment by toofar** [comment] 2022-06-18 01:26
Can you give an example of a search engine that supports searching newlines and also more details on how you calling qutebrowser via IPC?
When I try it I see this in the logs when using [this](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/open_url_in_instance.sh) script:

```
13:18:22.1655515102 DEBUG    ipc        ipc:_handle_data:320 Processing: {"args": ["one\ntwo"], "target_arg": null, "version": "1.0.4", "protocol_version": 1, "cwd": "/mnt/nvme/qt6.2/qtwebengine/examples3/webenginewidgets/simplebrowser"}

13:18:22.1655515102 DEBUG    url        urlutils:get_path_if_valid:368 Checking if 'one\ntwo' is a path
13:18:22.1655515102 DEBUG    url        urlutils:is_url:272 Checking if 'one\ntwo' is a URL (autosearch=naive).
13:18:22.1655515102 DEBUG    url        urlutils:fuzzy_url:220 URL is a fuzzy search term
13:18:22.1655515102 DEBUG    url        urlutils:_get_search_url:119 Finding search engine for 'one\ntwo'
13:18:22.1655515102 DEBUG    url        urlutils:_parse_search_term:106 engine None, term 'one\ntwo'
13:18:22.1655515102 DEBUG    url        urlutils:fuzzy_url:228 Converting fuzzy term 'one\ntwo' to URL -> https://www.google.com/search?q=one%0Atwo
```

So it seems like it's making it through.

**Comment by JingMatrix** [comment] 2022-06-18 07:45
There is no engine supports that, but it is our duty to support triming newline in between, here is the crash log
```
==== Exception ====
Traceback (most recent call last):
  File "/home/jing/Documents/Project/qutebrowser/qutebrowser/misc/ipc.py", line 323, in _handle_data
    json_data = json.loads(decoded)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jing/Documents/Project/qutebrowser/qutebrowser/misc/ipc.py", line 395, in on_ready_read
    self._handle_data(data)
  File "/home/jing/Documents/Project/qutebrowser/qutebrowser/misc/ipc.py", line 326, in _handle_data
    self._handle_invalid_data()
  File "/home/jing/Documents/Project/qutebrowser/qutebrowser/misc/ipc.py", line 305, in _handle_invalid_data
    assert self._socket is not None
AssertionError
```
To produce it,
```bash
printf '{"args": ["%s"], "target_arg": null, "version": "%s", "protocol_version": %d, "cwd": "%s"}\n' \
	"${search_text}" \
	"${_qb_version}" \
	"${_proto_version}" \
	"${PWD}" | socat -lf /dev/null - UNIX-CONNECT:"${_ipc_socket}" 
```
one set `search_text` with something like `I \n crased`.

**Comment by toofar** [comment] 2022-06-18 12:06
Hmm, maybe the difference is that you are passing a literal newline and I'm passing an escaped one that gets turned into a literal one later.
Anyway, this is a JSON API, I don't think we should be massaging invalid JSON to make it work. The error can be handled better though. It seems the `_handle_invalid_data()` method hasn't kept up with the IPC code? I'm not sure how you get there with self._socket being none, maybe something to do with that self._old_socket thing.

**Comment by The-Compiler** [comment] 2022-06-18 12:10
Duplicate of #6817

**Closed by The-Compiler** 2022-06-18 12:10 UTC
