### ISSUE TITLE
Opening a background tab will give away the focus incorrectly

### ISSUE THREAD

**Issue by Ape** [qutebrowser/qutebrowser#3155] opened 2017-10-18 04:46 UTC
I noticed a weird focus issue with background tabs (`:open -b`). If I open a new tab to the background it will get the focus. I'm expecting that the currently active tab keeps the focus. So if I press some keys it will affect the tab on the background, not the active tab.

Steps to reproduce:
1. Open a new browser with `--temp-basedir`
2. `:open -b https://github.com/qutebrowser/qutebrowser` (or some other page)
3. Press page down, arrow down, or space, etc. (to scroll down)
4. Notice that the keys are not scrolling the active tab
5. Switch to the new tab
6. Notice that this tab has been scrolled down

This seems to also happen with `:hint all tab` if `tabs.background = True`.

```
qutebrowser v1.0.2
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.1
PyQt: 5.9
```

**Comment by Ape** [comment] 2017-10-18 04:50
I can even type text on the background tab.

For example:
1. `open -b https://www.google.com`
2. Wait a second or two so that the page is fully loaded
3. Press `i` multiple times
    * It will first go to insert mode and then insert some `i`s on the Google search box
4. Switch to the tab

**Comment by The-Compiler** [comment] 2017-10-18 04:51
Duplicate of #2320

**Closed by The-Compiler** 2017-10-18 04:51 UTC
