### ISSUE TITLE
The next / prev commands don't work in the new.startpage search engine.

### ISSUE THREAD

**Issue by ViktorWalter** [qutebrowser/qutebrowser#4383] opened 2018-10-25 12:19 UTC
**Version info (see `:version`)**:
1.5.1
**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
yes

If I make a search in the new.startpage.com engine, the next/prev links are not detected by the :navigate next/prev (]] / [[) commands.
The error message says that no forward links were found.
The links say "Next page" and "Previous page" and are matched by simple "/" search for "next" and "prev".

**How to reproduce**
Go to https://new.startpage.com/do/dsearch?query=test  .
Press ]] or :navigate next

**Comment by The-Compiler** [comment] 2018-10-25 13:43
Duplicate of #2897

**Closed by The-Compiler** 2018-10-25 13:43 UTC
