### ISSUE TITLE
;; doesn't work as a hint

### ISSUE THREAD

**Issue by grigorievich** [qutebrowser/qutebrowser#5036] opened 2019-09-21 17:24 UTC
**Version info (see `:version`)**:

```
qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.4
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.2.5-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

```
**Does the bug happen if you start with `--temp-basedir`?**:

yes, with `set hints.chars a;bc`

**Description**

Hint `;;` yields error message `No command given`

**How to reproduce**

1. `set hints.chars a;bc`
2. https://duckduckgo.com/?q=r&t=h_&ia=web
3. `f`
4. `;;`

**Comment by user202729** [comment] 2019-09-21 17:29
Duplicate of #4368.

**Closed** 2019-09-21 17:50 UTC
