### ISSUE TITLE
"Out of date webengine version" returned by WhatsApp login page

### ISSUE THREAD

**Issue by epheo** [qutebrowser/qutebrowser#4445] opened 2018-11-30 09:18 UTC
**Version info (see `:version`)**: 1.5.2-1

qutebrowser 1.5.2-1
qt5-webengine 5.11.2-2

**Description**
Since this morning, accessing https://web.whatsapp.com/ return the following error message:
"WhatsApp works with Google Chrome 36+, to use WhatsApp, update Chrome"

Both qtwebengine and qutebrowser seems to be the latest available version.

Is this more a bug for the Qt community ?

**Comment by The-Compiler** [comment] 2018-11-30 09:21
Works fine for me. Does it work with `--temp-basedir`? (take a guess why the issue template is asking that - so I don't have to :wink:)

**Comment by epheo** [comment] 2018-11-30 09:31
Hi,
Tried with --temp-basedir before as well with the same result.

However, now it's just working fine...
I'm confused.

Not sure what changed in the past 10 minutes. 

Closing this, thanks !

**Comment by The-Compiler** [comment] 2018-12-02 20:08
Just saw this happen as well, with `--temp-basedir`, around 50% of the time - it's their UA parsing being broken, with the default UA but `QtWebEngine/5.12.0` removed it always works...

**Comment by The-Compiler** [comment] 2018-12-05 05:57
Well, there's progress... maybe!

>  We apologize that we have not responded to your message.
>
> We hope that you were able to find an answer in our Help Center: [https://faq.whatsapp.com/](https://faq.whatsapp.com/en/web).
> If not, please respond to this email and we will prioritize your inquiry.

`¯\_(ツ)_/¯`

**Comment by mrpewpew** [comment] 2018-12-12 08:41
Hi I got the same issue. When I try to set the UA, I don't see any default value. I tried `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36` and `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0` without success. Which UA should I use ?

**Comment by The-Compiler** [comment] 2018-12-12 08:45
@mrpewpew Go to http://httpbin.org/user-agent with the user agent set to an empty value, and copy-paste that with `QtWebEngine/...` removed.

**Comment by slashome** [comment] 2018-12-12 08:54
sorry, such a newbie here but I tried to set it in qute://settings, but it disapear after restart qute then  in config.py but it does'nt change anything :/

**Comment by mrpewpew** [comment] 2018-12-12 08:58
@The-Compiler Unfortunately, it doesn't work, Whatsapp is still complaining. The resulting UA was : 
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.128 Safari/537.36`

**Comment by The-Compiler** [comment] 2018-12-12 09:11
@slashome If you have a `config.py`, settings via `:set` or `qute://settings` will be ignored by default. Not sure what else to say with that little information - you might want to read [the configuration docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc).

@mrpewpew I've heard that from someone else as well, but it consistently works fine for me with that user agent. Are you sure it's set correctly, i.e., did you visit http://httpbin.org/user-agent again to verify it's set properly?

**Comment by slashome** [comment] 2018-12-12 09:15
What I was saying is that I tried to set it with qute://settings first, didn't worked then with config.py, didn't work either, I know the configuration priority order :) I'm gonna try to it again

**Comment by mrpewpew** [comment] 2018-12-12 09:18
@The-Compiler Yes I double-checked everything. Will wait to see if it happens to other users as well

**Comment by The-Compiler** [comment] 2018-12-12 09:19
@mrpewpew Can you please try whether this works?

```
qutebrowser --temp-basedir -s content.headers.user_agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.128 Safari/537.36'
```

Also, if that doesn't, what about this UA?

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.80 Safari/537.36
```

**Comment by epheo** [comment] 2018-12-12 09:35
Same here, there's something else in my current conf or data breaking it:
If this is not config related, is there a way to delete the data and cookies of a specific domain only ?
Here's my configdiff, maybe we have an option in common.
`
aliases = {"q": "quit", "w": "session-save", "wq": "quit --save", "x": "quit --save"}
auto_save.session = true
content.cookies.accept = all
content.geolocation = false
content.headers.referer = same-domain
content.headers.user_agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.230 Safari/537.36
file://*: content.javascript.enabled = true
chrome://*/*: content.javascript.enabled = true
qute://*/*: content.javascript.enabled = true
content.plugins = true
downloads.location.directory = 
editor.command = ["urxvt", "-e", "vim", "-f", "{file}", "-c", "normal {line}G{column0}l"]
qt.args = ["ppapi-widevine-path=/usr/lib64/qt5/plugins/ppapi/libwidevinecdmadapter.so"]
spellcheck.languages = ["en-US", "fr-FR"]
tabs.background = true
tabs.close_mouse_button_on_bar = new-tab
tabs.max_width = 150
tabs.min_width = 50
tabs.position = left
tabs.width = 10%
url.default_page = https://epheo.eu/empty.html
url.start_pages = https://epheo.eu/empty.html
`

**Comment by The-Compiler** [comment] 2018-12-12 09:37
Can you try quitting qutebrowser and then moving `~/.cache/qutebrowser` away and see if that helps? If not, what about `~/.local/share/qutebrowser`?

**Comment by epheo** [comment] 2018-12-12 09:45
yes, works ok while deleting `~/.local/share/qutebrowser`

**Comment by The-Compiler** [comment] 2018-12-12 09:50
Smells like WhatsApp sets a cookie or something... How annoying :disappointed:

**Comment by Aster89** [comment] 2018-12-13 09:13
Same problem here. My configdiff:
```
aliases = {"h": "home", "open": "open -r", "q": "close", "qa": "quit", "w": "session-save", "wq": "quit --save"}
auto_save.interval = 15000
auto_save.session = true
backend = webengine
bindings.commands = {"normal": {"<Back>": null, "<Ctrl+F5>": null, "<Ctrl+PgDown>": null, "<Ctrl+PgUp>": null, "<Ctrl+Shift+t>": null, "<Ctrl+Shift+w>": null, "<Ctrl+j>": "tab-move -", "<Ctrl+k>": "tab-move +", "<Ctrl+w>": null, "<F11>": null, "<Forward>": null, "J": "tab-prev", "K": "tab-next", "cm": "clear-messages"}}
bindings.key_mappings = {"<Ctrl+6>": "<Ctrl+^>", "<Ctrl+Enter>": "<Ctrl+Return>", "<Ctrl+[>": "<Escape>", "<Ctrl+j>": "<Return>", "<Ctrl+m>": "<Return>", "<Enter>": "<Return>", "<Shift+Enter>": "<Return>", "<Shift+Return>": "<Return>"}
colors.hints.bg = qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 247, 133, 0.8), stop:1 rgba(255, 197, 66, 0.8))
colors.hints.fg = black
colors.hints.match.fg = green
colors.webpage.bg = white
confirm_quit = ["never"]
content.cookies.accept = all
content.headers.user_agent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.128 Safari/537.36
content.host_blocking.enabled = true
content.javascript.can_open_tabs_automatically = false
file://*: content.javascript.enabled = true
chrome://*/*: content.javascript.enabled = true
qute://*/*: content.javascript.enabled = true
content.plugins = true
content.proxy = system
fonts.completion.category = bold 12pt monospace
fonts.completion.entry = 12pt monospace
fonts.debug_console = 12pt monospace
fonts.downloads = 12pt monospace
fonts.hints = bold 10pt monospace
fonts.keyhint = 12pt monospace
fonts.messages.error = 12pt monospace
fonts.messages.info = 12pt monospace
fonts.messages.warning = 12pt monospace
fonts.monospace = "xos4 Terminus", Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal
fonts.prompts = 12pt sans-serif
fonts.statusbar = 12pt monospace
fonts.tabs = 12pt monospace
fonts.web.family.cursive = 
fonts.web.family.fantasy = 
fonts.web.family.fixed = 
fonts.web.family.sans_serif = 
fonts.web.family.serif = 
fonts.web.family.standard = 
fonts.web.size.default = 16
fonts.web.size.default_fixed = 12
fonts.web.size.minimum = 8
fonts.web.size.minimum_logical = 6
hints.mode = letter
history_gap_interval = 30
input.partial_timeout = 0
keyhint.blacklist = 
keyhint.delay = 100
keyhint.radius = 6
messages.timeout = 0
new_instance_open_target = tab
new_instance_open_target_window = last-focused
qt.args = 
qt.highdpi = true
search.ignore_case = smart
search.incremental = true
session.default_name = 
session.lazy_restore = false
tabs.select_on_remove = last-used
zoom.default = 100%
zoom.levels = ["25%", "33%", "50%", "67%", "75%", "90%", "100%", "110%", "125%", "150%", "175%", "200%", "250%", "300%", "400%", "500%"]
zoom.mouse_divider = 512
```

**Comment by pmiddend** [comment] 2018-12-13 14:23
Note that for me, removing `.local/share/qutebrowser/webengine/IndexedDB/https_web.whatsapp.com_0.indexeddb.leveldb` worked. I didn't have to clear all the cache.

**Comment by pmiddend** [comment] 2018-12-14 07:30
@Aster89 Sorry, it wasn't. I had to switch the User-Agent, too.

**Comment by Aster89** [comment] 2018-12-14 10:41
Which one?

**Comment by The-Compiler** [comment] 2018-12-14 10:43
See https://github.com/qutebrowser/qutebrowser/issues/4445#issuecomment-446507766...

**Comment by Enzime** [comment] 2018-12-15 07:58
If you don't want to delete everything, you just need to delete any files/folders containing `whatsapp` inside the `webengine/IndexedDB` folder.

**Comment by hseg** [comment] 2018-12-15 16:51
Just wiped out cache to check, didn't help. Only workaround was to update UA.
The following UA works: `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.0 Chrome/71.0.3578.80 Safari/537.36`
Note that the only diff from the one Qutebrowser sends is the claimed Chrome version (QB claims `69.0.`stuff). Probably that's what's triggering their flags then.

**Comment by hseg** [comment] 2018-12-15 17:00
Note: UA only needs to be changed once, to get a working login. After that WhatsApp seems to set some local flag that allows the browser to pass through with old UAs. So once that flag is on the system, there's no need to set the UA in `config.py`. Weird, though.

**Comment by jgkamat** [comment] 2019-01-03 00:58
See https://github.com/jiahaog/nativefier/issues/719 as well.

I think that we may want to have a list of "tweaks" to fix websites such as this, as I don't think this is an isolated incident. IIRC, vimperator (or maybe uzbl) had a list of hacks to be applied by default to websites behind a config switch, we may want to do something similar.

**Comment by The-Compiler** [comment] 2019-02-17 19:40
Removing this from v1.6.0 - I'd really like to get this fixed, but it's probably a bit of work, and I'd like to get v1.6.0 out ASAP as the current v1.5 release has various issues with Qt 5.12.

**Comment by prosoitos** [comment] 2019-03-12 02:57
I never used WhatsApp Web before this happened. I am trying to access it now.

- I have `c.content.headers.user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.128 Safari/537.36"` in my config.py

- I deleted `https_web.whatsapp.com_0.indexeddb.leveldb`

But I still get:

![image](https://user-images.githubusercontent.com/4634851/54171498-c6295b80-4437-11e9-86b5-dd2984b6f13a.png)

What am I doing wrong?

**Comment by prosoitos** [comment] 2019-03-12 03:12
Nevermind. It is working now. Deleting `https_web.whatsapp.com_0.indexeddb.leveldb` and the qutebrowser cache wasn't enough for me. I had to delete the entire `~/.local/share/qutebrowserwebengine` for it to work.

Thank you everyone for the workaround!

**Comment by The-Compiler** [comment] 2019-03-27 23:02
I guess we need to look into having some "quirks mode" where we lie to common websites about the UA in general.. see #4669 for Slack.

**Comment by ExpandingMan** [comment] 2019-04-02 16:49
Note that slack is again threatening to sabotage itself at a future date even with the user agent string that we had used to circumvent it.

Sadly it does seem somewhat as if there will be an increasing need to masquerade as chrome or firefox.  It's depressing that the internet is so broken that so many sites try to force you to use their browsers for no good reason.

**Comment by The-Compiler** [comment] 2019-04-18 06:44
Current state for me: After doing `:jseval navigator.serviceWorker.getRegistration().then(function (r) { r.unregister(); document.location.reload() })` and re-registering with the QR code, WhatsApp Web works.

However, as soon as qutebrowser is restarted, it breaks again, apparently no matter what the UA is...

**Comment by The-Compiler** [comment] 2019-04-29 08:43
Yet another case where quirks would make sense: When navigating to drive.google.com with qutebrowser's Windows UA:

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.2 Chrome/69.0.3497.128 Safari/537.36
```

no contents are displayed. Using the Linux UA:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.3 Chrome/69.0.3497.128 Safari/537.36
```

all works fine...

**Comment by The-Compiler** [comment] 2019-05-27 11:26
Hmm, looks like this works again, at least at the moment... Closing this now, and I opened #4810 to collect this and other site-specific quirks.

**Comment by mrpewpew** [comment] 2019-08-03 08:40
The issue seems to be back. Now, I have to delete ~/.local/share/qutebrowser/webengine each time before restarting qutebrowser. My UA is set to `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.128 Safari/537.36
`

**Comment by mrpewpew** [comment] 2019-08-04 08:58
Actually, I just noticed that I also have to delete ~/.local/share/qutebrowser/webengine when I reload the whatsapp web tab otherwise the "out of date" message comes out. Should we reopen that issue ?

**Comment by The-Compiler** [comment] 2019-08-05 06:38
@mrpewpew There's #4810 already.

**Comment by mrpewpew** [comment] 2019-08-05 07:29
@The-Compiler but #4810 links to this issue which is closed ...

**Comment by The-Compiler** [comment] 2019-08-05 07:30
Yes, because we don't need two issues for the same problem (which isn't actually a qutebrowser issue)...

**Comment by mrpewpew** [comment] 2019-08-05 07:42
Oh could you point me to the issue upstream please ? If it's documented of course

**Comment by The-Compiler** [comment] 2019-08-05 08:32
@mrpewpew It's a WhatsApp issue, and their support pretty much ignores it.

**Comment by Aster89** [comment] 2019-08-17 18:53
@The-Compiler , it looks like web whatsapp works again (across reboots, and the likes). Is that you?

**Comment by The-Compiler** [comment] 2019-08-17 19:12
No changes from qutebrowser's side. Maybe they finally managed to fix their page.

**Comment by Jan-PieterBaert** [comment] 2019-08-17 19:14
The default value for `content.headers.user_agent` has been updated on qutebrowser's side.

**Comment by The-Compiler** [comment] 2019-08-17 19:17
@Jan-PieterBaert Not for the default user agent (which causes this issue in the first place). If you see a different Chromium version there, that's because of a Qt update (but Qt 5.13 has been out for a while already).

**Comment by Aster89** [comment] 2019-09-28 09:42
> No changes from qutebrowser's side. Maybe they finally managed to fix their page.

Web whatsapp has been NOT working for some weeks for me, and now it works again, without me taking any action. Therefore, unless @The-Compiler has done something, this means imho that, yes, the service goes broken/working depending on how they tamper with their own page.

**Comment by The-Compiler** [comment] 2019-09-29 12:30
Good to hear, let's hope it stays that way. This has always been a WhatsApp bug, all that qutebrowser could do is try working around it - but there haven't been any changes on qutebrowser's side so far.

**Comment by AckslD** [comment] 2019-10-20 10:13
Whatsapp is not working for me, is there something I can do from my side?

![Screenshot from 2019-10-20 12-11-58](https://user-images.githubusercontent.com/23341710/67157998-0d16f200-f333-11e9-884a-1f166e99c325.png)

**Comment by 3ruce** [comment] 2019-11-06 03:21
Changing the user agent to `Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.128 Safari/537.36` fixed this for me... Debian 10 and apt install from the repo...

**Comment by The-Compiler** [comment] 2019-12-20 16:25
I now pushed a fix for known-broken sites (WhatsApp, Google login, etc.) to the `user-agent` branch. If you're affected by one of those, could you please try that branch without any custom user agent set? Thanks!

**Comment by prosoitos** [comment] 2020-01-04 22:14
Whatsapp now works for me without a custom user agent (while I used to get the same message as @AckslD before the fix).

Thanks!

**Comment by hseg** [comment] 2020-01-05 19:52
Still broken for me, just sent crash dump.

**Comment by The-Compiler** [comment] 2020-01-05 19:56
@hseg That seems unrelated to this issue, see #4657.

**Comment by hseg** [comment] 2020-01-06 12:50
On Sun, Jan 05, 2020 at 11:56:16AM -0800, Florian Bruhin wrote:
> @hseg That seems unrelated to this issue, see #4657.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/qutebrowser/qutebrowser/issues/4445#issuecomment-570942043

True, the crash dump seems unrelated.
That said, WhatsApp Web won't open without setting the UA to one of the provided
strings. Posted version to <https://paste.the-compiler.org/view/30116819>, hope
it helps.

**Comment by The-Compiler** [comment] 2020-01-06 12:56
@hseg You seem to be running the v1.8.3 release. The fix for this issue happened after that, and isn't in a release yet.

**Comment by hseg** [comment] 2020-01-07 11:22
Ah, OK. Sorry for noise, will wait for the new release.

On 6 January 2020 14:56:49 GMT+02:00, Florian Bruhin <notifications@github.com> wrote:
>@hseg You seem to be running the v1.8.3 release. The fix for this issue
>happened after that, and isn't in a release yet.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/qutebrowser/qutebrowser/issues/4445#issuecomment-571128468

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by svmhdvn** [comment] 2020-01-15 02:07
I'm seeing this issue again on v1.9.0. I can confirm that whatsapp web was working for a while (after installing v1.9.0 a few days ago) but I'm trying it now and the problem has returned. Can anyone else reproduce this?

**Comment by The-Compiler** [comment] 2020-01-15 09:29
Argh :angry:. I'll see what I can do.

FWIW, people at https://github.com/jiahaog/nativefier/issues/719 seem to report the same.

**Comment by The-Compiler** [comment] 2020-01-15 10:19
Doing a `:reload --force` (Shift-R) seems to fix it.

Not sure what's going on here. The workaround from https://github.com/qutebrowser/qutebrowser/issues/4920#issuecomment-513791951 doesn't seem to work here...

**Comment by prosoitos** [comment] 2020-01-17 04:28
I think that everybody should just stop using WhatsApp, Skype, Slack and co and start using [Matrix](https://matrix.org/) instead :smirk:

**Comment by The-Compiler** [comment] 2020-01-20 18:50
I just tried reproducing this again and it seems to be fine now/today - @svmhdvn can you still reproduce?

**Comment by svmhdvn** [comment] 2020-01-20 19:47
I can't reproduce it today either, I guess this is intermittent? Has
anyone figured out the reason for this bug?

**Comment by The-Compiler** [comment] 2020-01-20 19:48
Probably just WhatsApp doing stuff server-side. `¯\_(ツ)_/¯`

**Closed by The-Compiler** 2020-01-20 19:48 UTC
Labels: bug: behavior, priority: 0 - high

**Comment by The-Compiler** [comment] 2020-01-20 19:49
Oh, that being said - please let me know if it comes back though, then I'll still check if I can add a workaround of some sorts.

**Comment by The-Compiler** [comment] 2020-01-31 16:00
I just caught this issue again, and added a workaround for it (which will ship with v1.10.0).

**Comment by The-Compiler** [comment] 2020-01-31 21:26
FWIW as a workaround, you can put this in a `greasemonkey/whatsapp.user.js` file inside qutebrowser's data directory (see `:version`):

```js
// ==UserScript==
// @include https://web.whatsapp.com/
// ==/UserScript==
if (document.body.innerText.replace(/\n/g, ' ').search(/whatsapp works with.*to use whatsapp.*update/i) !== -1)
	navigator.serviceWorker.getRegistration().then(function (r) { r.unregister(); document.location.reload() });
```FWIW as a workaround, you can put this in a `greasemonkey/whatsapp.user.js` file inside qutebrowser's data directory (see `:version`):

```js
// ==UserScript==
// @include https://web.whatsapp.com/
// ==/UserScript==
if (document.body.innerText.replace(/\n/g, ' ').search(/whatsapp works with.*to use whatsapp.*update/i) !== -1)
	navigator.serviceWorker.getRegistration().then(function (r) { r.unregister(); document.location.reload() });
```
