### ISSUE TITLE
Audio tag [A] turning on and off when the videos get silent.

### ISSUE THREAD

**Issue by AlvesJorge** [qutebrowser/qutebrowser#6388] opened 2021-04-12 17:18 UTC
**Version info**:

qutebrowser v2.1.0
Git commit: 
Backend: QtWebEngine 5.15.3, Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.4

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.35.3
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: Breeze::Style
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.0.1
Platform: Linux-5.11.10-1-MANJARO-x86_64-with-glibc2.33, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `23?**
Yes
**Description**
When watching a video (both on youtube and udemy) , if there is a pause on the audio, for example it's a video of someone speaking with no background music, the [A] tag in the tab turns off.
I believe it is working as 'intended' but it happens that if it's a course or lecture, then that tag turns on and off very quickly , almost like flickering, and since it is at the beggining of the tab name, it moves the entire text of the tab. It's very distracting.
Maybe giving it 5 seconds before the tag disapears? 

I do notice it is possible to remove in the settings
Keep up the good work!!
**How to reproduce**

**Comment by The-Compiler** [comment] 2021-04-12 17:37
Duplicate of #6168

**Closed by The-Compiler** 2021-04-12 17:37 UTC
