### ISSUE TITLE
Merge quickmarks and bookmarks

### ISSUE THREAD

**Issue by robomica** [qutebrowser/qutebrowser#2887] opened 2017-08-05 13:42 UTC
Syntactically there seems little reason to keep these separate and it's one less thing ot memorize. For example `:open wp qutebrowser` could search Wikipedia and `:open wp` could be a quickmark for the front page.

**Comment by The-Compiler** [comment] 2017-08-05 13:49
Duplicate of #882.

**Closed by The-Compiler** 2017-08-05 13:49 UTC
