### ISSUE TITLE
Switching tabs from fullscreen video makes tab list not show previous tab

### ISSUE THREAD

**Issue by nabakolu** [qutebrowser/qutebrowser#7903] opened 2023-09-09 16:54 UTC
**Version info**:

```
Version info
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.11.5
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: 3.7.107 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.43.0
QtNetwork SSL: OpenSSL 3.1.2 1 Aug 2023

Style: QGtkStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 23.1.6-arch1.4
Platform: Linux-6.4.12-arch1-1-x86_64-with-glibc2.38, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /tmp/qutebrowser-basedir-z63rva51/cache
config: /tmp/qutebrowser-basedir-z63rva51/config
data: /tmp/qutebrowser-basedir-z63rva51/data
runtime: /tmp/qutebrowser-basedir-z63rva51/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:03
**Does the bug happen if you start with `--temp-basedir`?**:
```
**Description**
Setting tabs position to left and watching a video in fullscreen on the first tab, then switching to the second tab, makes the first tab not appear in the tabs list.

**How to reproduce**

1. ```:set tabs.position left```
2. open a new tab
3. switch to first tab and open a video in fullscreen
4. switch to second tab
5. tabs list now only shows second tab

**Comment by The-Compiler** [comment] 2023-09-09 17:38
Duplicate of #7852

**Closed by The-Compiler** 2023-09-09 17:38 UTC
