### ISSUE TITLE
nextcloud calendars are not diplayed any longer

### ISSUE THREAD

**Issue by niels-borne** [qutebrowser/qutebrowser#6047] opened 2021-01-19 08:19 UTC
**Version info**:

https://paste.the-compiler.org/view/796f746a

**Does the bug happen if you start with `--temp-basedir`?**:

yes same bug

**Description**

the nextcloud  calendars are not displayed. It was working fine two weeks ago. It is still working with chromium.

**How to reproduce**

https://framagenda.org

**Comment by The-Compiler** [comment] 2021-01-19 08:27
I don't have an account at framagenda.org, but my own Nextcloud calendar displays just fine.

What does "not displayed" mean exactly? Can you show a screenshot? Anything interesting in the `:devtools` console?

**Comment by niels-borne** [comment] 2021-01-19 08:38
besides the menus on the top row and the left column the page is blank

in devtools two errors

vue.runtime.esm.js:1888 TypeError: Cannot read property '$el' of undefined
    at i.mounted (main.js:4927)
    at He (vue.runtime.esm.js:1854)
    at sn (vue.runtime.esm.js:4218)
    at Object.insert (vue.runtime.esm.js:3138)
    at x (vue.runtime.esm.js:6346)
    at Dn.__patch__ (vue.runtime.esm.js:6566)
    at Dn.e._update (vue.runtime.esm.js:3945)
    at Dn.r (vue.runtime.esm.js:4066)
    at vn.get (vue.runtime.esm.js:4479)
    at new vn (vue.runtime.esm.js:4468)

vue.runtime.esm.js:1888 TypeError: e.replaceAll is not a function
    at Mp (main.js:4186)
    at i.options (main.js:4863)
    at vn.get (vue.runtime.esm.js:4479)
    at vn.evaluate (vue.runtime.esm.js:4584)
    at i.options (vue.runtime.esm.js:4836)
    at i.ls (vue-color.min.js:1)
    at i.e._render (vue.runtime.esm.js:3548)
    at i.r (vue.runtime.esm.js:4066)
    at vn.get (vue.runtime.esm.js:4479)
    at new vn (vue.runtime.esm.js:4468)

does this help ?

**Comment by The-Compiler** [comment] 2021-01-19 08:54
I just created an account, still no issues here:

![image](https://user-images.githubusercontent.com/625793/105010689-54ab9280-5a3c-11eb-98bc-9bb2f6471f13.png)

Can you please try with KDE Falkon and/or Chromium as well?

**Comment by niels-borne** [comment] 2021-01-19 08:59
After disconnecting and reconnecting it is working fine now. I tried this a few days back but it failed then. In any case, thanks a lot for your help.

**Comment by The-Compiler** [comment] 2021-01-19 09:00
You're welcome! Closing this then.

**Closed by The-Compiler** 2021-01-19 09:00 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by cpnfeeny** [comment] 2021-01-21 21:43
Unfortunately, I'm seeing this too. Logging out and logging back in didn't help.

devtools errors nad warnings here:

userscript:GM-AdsBypasser:117 AdsBypasser called unimplemented GM_registerMenuCommand
GM_registerMenuCommand @ userscript:GM-AdsBypasser:117
index.js:46 No OC found
t.getLanguage @ main.js?v=db6f87dd-0:1
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ main.js?v=db6f87dd-0:1
4globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ main.js?v=db6f87dd-0:1
2globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ main.js?v=db6f87dd-0:1
ConsoleLogger.js:46 [INFO] calendar: 
Initial settings:
	- AppVersion: 2.1.3
	- EventLimit: true
	- FirstRun: true
	- ShowWeekNumbers: false
	- ShowTasks: true
	- ShowWeekends: true
	- SkipPopover: false
	- SlotDuration: 00:30:00
	- TalkEnabled: true
	- TasksEnabled: false
	- Timezone: automatic
 Object
vue.runtime.esm.js:1888 TypeError: e.replaceAll is not a function
    at Mp (localeProvider.js:36)
    at i.options (CalendarGrid.vue:127)
    at vn.get (vue.runtime.esm.js:4479)
    at vn.evaluate (vue.runtime.esm.js:4584)
    at i.options (vue.runtime.esm.js:4836)
    at i.ls (CalendarGrid.vue?a26b:7)
    at i.e._render (vue.runtime.esm.js:3548)
    at i.r (vue.runtime.esm.js:4066)
    at vn.get (vue.runtime.esm.js:4479)
    at new vn (vue.runtime.esm.js:4468)
Ve @ calendar.js?v=db6f87dd-0:2
vue.runtime.esm.js:1888 TypeError: Cannot read property '$el' of undefined
    at i.mounted (CalendarGrid.vue:203)
    at He (vue.runtime.esm.js:1854)
    at sn (vue.runtime.esm.js:4219)
    at Object.insert (vue.runtime.esm.js:3139)
    at x (vue.runtime.esm.js:6346)
    at Dn.__patch__ (vue.runtime.esm.js:6565)
    at Dn.e._update (vue.runtime.esm.js:3945)
    at Dn.r (vue.runtime.esm.js:4066)
    at vn.get (vue.runtime.esm.js:4479)
    at new vn (vue.runtime.esm.js:4468)
Ve @ calendar.js?v=db6f87dd-0:2
ConsoleLogger.js:46 [INFO] calendar: Updated moment locale: en Object
session-heartbeat.js:97 session heartbeat polling started
vue-router.esm.js:2257 TypeError: Cannot read property 'getApi' of undefined
    at CalendarGrid.vue:229
    at f (vue-router.esm.js:2300)
    at r (vue-router.esm.js:1947)
    at vue-router.esm.js:1948
    at vue-router.esm.js:2322
    at windowTitleService.js:66
    at f (vue-router.esm.js:2300)
    at r (vue-router.esm.js:1947)
    at xe (vue-router.esm.js:1955)
    at t.Fe.confirmTransition (vue-router.esm.js:2330)
a @ calendar.js?v=db6f87dd-0:2
CalendarGrid.vue:229 Uncaught (in promise) TypeError: Cannot read property 'getApi' of undefined
    at CalendarGrid.vue:229
    at f (vue-router.esm.js:2300)
    at r (vue-router.esm.js:1947)
    at vue-router.esm.js:1948
    at vue-router.esm.js:2322
    at windowTitleService.js:66
    at f (vue-router.esm.js:2300)
    at r (vue-router.esm.js:1947)
    at xe (vue-router.esm.js:1955)
    at t.Fe.confirmTransition (vue-router.esm.js:2330)
vue-router.esm.js:2257 TypeError: Cannot read property 'getApi' of undefined
    at CalendarGrid.vue:229
    at f (vue-router.esm.js:2300)
    at r (vue-router.esm.js:1947)
    at vue-router.esm.js:1948
    at vue-router.esm.js:2322
    at windowTitleService.js:66
    at f (vue-router.esm.js:2300)
    at r (vue-router.esm.js:1947)
    at xe (vue-router.esm.js:1955)
    at t.Fe.confirmTransition (vue-router.esm.js:2330)
a @ calendar.js?v=db6f87dd-0:2
CalendarGrid.vue:229 Uncaught (in promise) TypeError: Cannot read property 'getApi' of undefined
    at CalendarGrid.vue:229
    at f (vue-router.esm.js:2300)
    at r (vue-router.esm.js:1947)
    at vue-router.esm.js:1948
    at vue-router.esm.js:2322
    at windowTitleService.js:66
    at f (vue-router.esm.js:2300)
    at r (vue-router.esm.js:1947)
    at xe (vue-router.esm.js:1955)
    at t.Fe.confirmTransition (vue-router.esm.js:2330)

![2021-01-21_22-41](https://user-images.githubusercontent.com/49805214/105416089-f1874f00-5c39-11eb-9d41-7e09c30aaef0.png)

**Comment by The-Compiler** [comment] 2021-01-21 21:45
@cpnfeeny Can you try with `--temp-basedir` and show your version information as well? Also, can you try with KDE Falkon and/or Chromium?

**Comment by cpnfeeny** [comment] 2021-01-21 21:55
Qutebrowser is really wonderful, by the way. Thanks for making it!

with --temp-basedir
![2021-01-21_22-53](https://user-images.githubusercontent.com/49805214/105417284-acfcb300-5c3b-11eb-8f2a-ece90e3c3dbd.png)
Chromium
![2021-01-21_22-51](https://user-images.githubusercontent.com/49805214/105417267-a837ff00-5c3b-11eb-808a-2229d3b54803.png)

**Comment by The-Compiler** [comment] 2021-01-21 22:09
No idea what's going on I'm afraid. Would still be great if someone who's affected could try with KDE Falkon.

**Comment by fischerling** [comment] 2021-01-22 09:02
For me the calendar is not displayed in both browsers.
Qutebrowser (1.14.1-1) and KDE falkon (3.1.0-15) with qt5-webengine (5.15.2-3) on arch linux
![20210122_09h54m08s_grim](https://user-images.githubusercontent.com/1218430/105469573-c3852780-5c98-11eb-8ded-01024930e3f6.png)

**Comment by The-Compiler** [comment] 2021-01-22 09:42
Ah, I can reproduce this after fully upgrading my Nextcloud.

Looks like they started using `String.replaceAll`, [which only works in very recent browsers](https://caniuse.com/mdn-javascript_builtins_string_replaceall) - it was introduced in Chrome 85, but QtWebEngine 5.15.2 is based on Chromium 83.

Looks like various people ran into similar trouble with other browsers too:

- [Blank page on calendar · Issue #2775 · nextcloud/calendar](https://github.com/nextcloud/calendar/issues/2775)
- [Calendar app white page on Firefox version 63.0.1 (nc20) · Issue #2757 · nextcloud/calendar](https://github.com/nextcloud/calendar/issues/2757)
- [No Calendar were shown on the right screen of Calendar APP 2.1.2 · Issue #2734 · nextcloud/calendar](https://github.com/nextcloud/calendar/issues/2734)

And there was a fix, however it's not released yet:

- [Change String#replaceAll with String#replace and the g switch by tcitworld · Pull Request #2822 · nextcloud/calendar](https://github.com/nextcloud/calendar/pull/2822)

As a workaround, you can put this into the `greasemonkey` directory in your qutebrowser data dir (see `:version`):

```js
// ==UserScript==
// @name replaceAll quirk
// @run-at document-start
// ==/UserScript==
// Based on: https://vanillajstoolkit.com/polyfills/stringreplaceall/

/**
 * String.prototype.replaceAll() polyfill
 * https://gomakethings.com/how-to-replace-a-section-of-a-string-with-another-one-with-vanilla-js/
 * @author Chris Ferdinandi
 * @license MIT
 */

"use strict";

if (!String.prototype.replaceAll) {
	String.prototype.replaceAll = function(str, newStr){

		// If a regex pattern
		if (Object.prototype.toString.call(str).toLowerCase() === '[object regexp]') {
			return this.replace(str, newStr);
		}

		// If a string
		return this.replace(new RegExp(str, 'g'), newStr);

	};
}
```

I'll also push an equivalent workaround to the git master, though I'm probably going to revert it once an update has been released from nextcloud's side.

**Comment by cpnfeeny** [comment] 2021-01-23 17:17
Works great. Thanks!

**Comment by florom** [comment] 2021-03-25 09:01
Hi Devs,
Thanks for fixing it.
Finally with 2.2.0 Calendar version it works.

Thanks again
