### ISSUE TITLE
Allow for easy re-loading of quickmarks

### ISSUE THREAD

**Issue by bearcatsandor** [qutebrowser/qutebrowser#4146] opened 2018-08-19 20:31 UTC
While it would be great to have a way to edit quickmarks, at this time my main concern is re-loading them. Currently, after editing a quickmark in vim, qutebrowser doesn't reflect the changes until i quit qutebrowser and re-load it. How about a reload command that reloads all the config files in their current state, for those of us that use text editors (probably all of us using this browser)

**Comment by jgkamat** [comment] 2018-08-22 05:04
AFAIK, :config-source only reloads config.py, not quickmarks or bookmarks.

That said, if you add quickmarks via :quickmark-add they will get added
properly (although you get less control).

>    @cmdutils.register(instance='config-commands')
>    def config_source(self, filename=None, clear=False):
>        """Read a config.py file.
>
>        Args:
>            filename: The file to load. If not given, loads the default
>                      config.py.
>            clear: Clear current settings first.
>        """
>        if filename is None:
>            filename = os.path.join(standarddir.config(), 'config.py')
>        else:
>            filename = os.path.expanduser(filename)
>
>        if clear:
>            self.config_clear()
>
>        try:
>            configfiles.read_config_py(filename)
>        except configexc.ConfigFileErrors as e:
>            raise cmdexc.CommandError(e)


Jakob Steinn writes:

**Comment by benedikt-bartscher** [comment] 2019-07-22 13:39
Is there really no way to reload quickmarks without restarting qutebrowser? I use syncthing to sync my quickmarks/bookmarks between multiple clients but i have to restart qutebrowser multiple times a day :(

**Comment by The-Compiler** [comment] 2019-07-22 13:58
It's a hack, but you can put this in a Python file:

```python
qm = objreg.get('quickmark-manager')
qm.marks.clear()
qm._lineparser._read()
for line in qm._lineparser:
    if not line.strip():
        continue
    qm._parse_line(line)
```

and use `:debug-pyeval --quiet --file /path/to/qmreload.py`

**Comment by benedikt-bartscher** [comment] 2019-07-23 13:44
Thank you, works like a charm! I'll report if there are any Problems.
For those interested, i created 2 files in .config/qutebrowser/scripts:

reload-quickmarks.sh
```
#!/bin/sh
DISPLAY=:0 /usr/bin/qutebrowser ":debug-pyeval --quiet --file /home/benedikt/.config/qutebrowser/scripts/reload-quickmarks.py" > /dev/null 2>&1
```

reload-quickmarks.py
```
qm = objreg.get('quickmark-manager')
qm.marks.clear()
qm._lineparser._read()
for line in qm._lineparser:
    if not line.strip():
        continue
    qm._parse_line(line)
```

and 2 systemd user files to watch for changes in .config/qutebrowser/quickmarks:

quickmarks.path
```
[Path]
PathChanged= /home/benedikt/.config/qutebrowser/quickmarks

[Install]
WantedBy=multi-user.target
```

quickmarks.service
```
[Unit]
Description=Reload qutebrowsers quickmarks

[Service]
Type=oneshot
ExecStart=/bin/sh /home/benedikt/.config/qutebrowser/scripts/reload-quickmarks.sh

[Install]
WantedBy=multi-user.target
```

This is not optimal and not tested much. If you add a quickmark on machine x, quickmarks will be reloaded on all machines including machine x which is unnecessary. I would love to see a feature where qutebrowser listens to changes via inotify :-)

**Comment by The-Compiler** [comment] 2020-01-07 14:18
Duplicate of #3520

**Closed by The-Compiler** 2020-01-07 14:18 UTC
Labels: component: urlmarks, priority: 2 - low

**Comment by cortsf** [comment] 2024-11-04 04:04
> It's a hack, but you can put this in a Python file:
> 
> ```
> qm = objreg.get('quickmark-manager')
> qm.marks.clear()
> qm._lineparser._read()
> for line in qm._lineparser:
>     if not line.strip():
>         continue
>     qm._parse_line(line)
> ```
> 
> and use `:debug-pyeval --quiet --file /path/to/qmreload.py`.
> 
> Only briefly tested, without any warranty, if it breaks you get to keep both pieces 😉

Any chance this could be officialy supported? After adding a (simple) [quickmark manager](https://github.com/cortsf/quterofi?tab=readme-ov-file#usage-of-the-manage_quickmarks-userscript) to my project, I personally don't need qb to know anything about quickmarks. But it's weird having to tell other users  (in the readme) to restart qutebrowser after updating quickmarks in any way, just for the sake of having the standard qb functions to work as expected.

**Comment by The-Compiler** [comment] 2024-11-04 06:29
There's an open issue for exactly that, see the comment just above yours.

**Comment by cortsf** [comment] 2024-11-04 06:42
That's for bookmarks. Did a search before posting and there is no mention of the word "quickmark" other than the link on this page (?).

**Comment by The-Compiler** [comment] 2024-11-04 09:13
The "motivation" isn't helpful, it's just noise for everyone reading through issues - and if anything, constant pings (you're by far not the only person!) will probably push open source developers closer to burnout rather than motivate them. Use the :+1: reaction, that's exactly what it's here for.
