### ISSUE TITLE
Following a fragment URL in a new tab doesn't focus properly (XWayland)

### ISSUE THREAD

**Issue by bheadmaster** [qutebrowser/qutebrowser#4370] opened 2018-10-20 09:19 UTC
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/95bdfa5c

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Yes.

**Description**
Using `F` for opening a link that contains a fragment URL sometimes doesn't focus the opened webpage on the right place.
It happens both on sway and weston. It doesn't happen when I have another window opened in the same workspace on sway, only when qutebrowser is the only window.
Also, opening the link in the background tab with ";b" doesn't cause this issue.

**How to reproduce**

> Open https://aircrack-ng.org/doku.php?id=compatibility_drivers
> Press F
> Choose the hint on the "FAQ Entry" link
The newly opened windows should be focused somewhere else instead of the "#what_is_the_best_wireless_card_to_buy" part, which should be.

**Comment by jgkamat** [comment] 2018-10-21 03:48
Works for me. I don't think this would be related to wayland, but I could be wrong.

https://github.com/qutebrowser/qutebrowser/issues/1190 may be some interesting history.
bheadmaster writes:

> **Version info (see `:version`)**:
> https://paste.the-compiler.org/view/95bdfa5c
>
> **Does the bug happen if you start with `--temp-basedir`?** (if applicable):
> Yes.
>
> **Description**
> Using `F` for opening a link that contains a fragment URL sometimes doesn't focus the opened webpage on the right place.
> It happens both on sway and weston. It doesn't happen when I have another window opened in the same workspace on sway, only when qutebrowser is the only window.
> Also, opening the link in the background tab with ";b" doesn't cause this issue.
>
> **How to reproduce**
> 
>> Open https://aircrack-ng.org/doku.php?id=compatibility_drivers
>> Press F
>> Choose the hint on the "FAQ Entry" link
> The newly opened windows should be focused somewhere else instead of the "#what_is_the_best_wireless_card_to_buy" part, which should be.

**Comment by The-Compiler** [comment] 2018-10-23 17:31
Duplicate of #4288

**Closed by The-Compiler** 2018-10-23 17:31 UTC
