### ISSUE TITLE
Qutebrowser crashes on gmail?? (idk)

### ISSUE THREAD

**Issue by AnotherRandomGitHubAccount** [qutebrowser/qutebrowser#7977] opened 2023-10-27 11:49 UTC
**Version info**:
qutebrowser v3.0.2
Git commit: 
Backend: QtWebEngine 6.6, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.0

CPython: 3.11.5
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: 3.9.179 (/nix/store/wina0bcmiw1z921hb4hijfr18ajh2sy6-source/build/pdf.js)
sqlite: 3.43.1
QtNetwork SSL: OpenSSL 3.0.11 19 Sep 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.1.9
Platform: Linux-6.1.59-x86_64-with-glibc2.38, 64bit
Linux distribution: NixOS 23.11 (Tapir) (nixos)
Frozen: False
Imported from /nix/store/vjgqmmy2l85cy7ljvpz9xj363gblx0f8-qutebrowser-3.0.2/lib/python3.11/site-packages/qutebrowser
Using Python from /nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/bin/python3
Qt library executable path: /nix/store/0hb20vrnjnnlssa030kxqwbnjr6kr4jh-qtbase-6.6.0/libexec, data path: /nix/store/0hb20vrnjnnlssa030kxqwbnjr6kr4jh-qtbase-6.6.0

Paths:
cache: /home/bongo/.cache/qutebrowser
config: /home/bongo/.config/qutebrowser
data: /home/bongo/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /nix/store/vjgqmmy2l85cy7ljvpz9xj363gblx0f8-qutebrowser-3.0.2/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:01:19

**Does the bug happen if you start with `--temp-basedir`?**:
I tried running qutebrowser with --temp-basedir but for some reason that way it couldn't reach some login page correctly and i couldnt get to the place where i need to reproduce the bug. but also i haven't done any configuring with qutebrowser yet so i don't think its a weird setting i have.

**Description**
So i opened gmail, and i opened an email. everything works fine and i start replying, doing stuff, etc. but INEVITABLY after a short amount of time it freezes and closes. heres the output from STDER:

Received signal 11 SEGV_MAPERR 000000000020
#0 0x7f4c63e25685 base::debug::CollectStackTrace()
#1 0x7f4c63e0c336 base::debug::StackTrace::StackTrace()
#2 0x7f4c63e25b0b base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f4c72855a70 (/nix/store/gqghjch4p1s69sv4mcjksb2kb65rwqjy-glibc-2.38-23/lib/libc.so.6+0x3da6f)
#4 0x7f4c63dfa1b0 (/nix/store/9wnsi31vjhaf2c8khh71kjsws7lfa2xs-qtwebengine-6.6.0/lib/libQt6WebEngineCore.so.6.6.0+0x47fa1af)
#5 0x7f4c637fe99b extensions::MessageService::OpenChannelImpl()
#6 0x7f4c637ffe5e extensions::MessageService::PendingLazyContextOpenChannel()
#7 0x7f4c637fbc01 base::internal::Invoker<>::RunOnce()
#8 0x7f4c63785883 extensions::LazyBackgroundTaskQueue::ProcessPendingTasks()
#9 0x7f4c63740370 extensions::ExtensionHostRegistry::ExtensionHostCompletedFirstLoad()
#10 0x7f4c6374045c extensions::ExtensionHost::DidStopLoading()
#11 0x7f4c62edbac3 content::WebContentsImpl::WebContentsObserverList::NotifyObservers<>()
#12 0x7f4c62f07f7d content::WebContentsImpl::LoadingStateChanged()
#13 0x7f4c62f087e7 content::WebContentsImpl::DidStopLoading()
#14 0x7f4c62b9fd03 content::FrameTreeNode::DidStopLoading()
#15 0x7f4c62cc0035 content::RenderFrameHostImpl::DidStopLoading()
#16 0x7f4c62483774 content::mojom::FrameHostStubDispatch::Accept()
#17 0x7f4c64624153 mojo::InterfaceEndpointClient::HandleValidatedMessage()
#18 0x7f4c64625297 mojo::MessageDispatcher::Accept()
#19 0x7f4c64623b3e mojo::InterfaceEndpointClient::HandleIncomingMessage()
#20 0x7f4c6488c912 IPC::(anonymous namespace)::ChannelAssociatedGroupController::AcceptOnEndpointThread()
#21 0x7f4c64888459 base::internal::Invoker<>::RunOnce()
#22 0x7f4c63dae1fb base::TaskAnnotator::RunTaskImpl()
#23 0x7f4c63dcb6ab base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl()
#24 0x7f4c63dcc257 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork()
#25 0x7f4c6017503e QtWebEngineCore::MessagePumpForUIQt::handleScheduledWork()
#26 0x7f4c711bd74d QObject::event()
#27 0x7f4c6d792d11 QApplicationPrivate::notify_helper()
#28 0x7f4c6e17e49e sipQApplication::notify()
#29 0x7f4c7116d5f8 QCoreApplication::notifyInternal2()
#30 0x7f4c71170f20 QCoreApplicationPrivate::sendPostedEvents()
#31 0x7f4c71420f13 postEventSourceDispatch()
#32 0x7f4c71be8edd g_main_context_dispatch
#33 0x7f4c71be9188 g_main_context_iterate.constprop.0
#34 0x7f4c71be921c g_main_context_iteration
#35 0x7f4c714208ec QEventDispatcherGlib::processEvents()
#36 0x7f4c71179a23 QEventLoop::exec()
#37 0x7f4c71175b38 QCoreApplication::exec()
#38 0x7f4c6e17d2fb meth_QApplication_exec
#39 0x7f4c72d53ec2 cfunction_call
#40 0x7f4c72c099dd _PyObject_MakeTpCall.localalias
#41 0x7f4c72af6a4c _PyEval_EvalFrameDefault.localalias
#42 0x7f4c72d57abc _PyEval_Vector.constprop.0
#43 0x7f4c72d57c5a PyEval_EvalCode.localalias
#44 0x7f4c72d5bb60 run_mod
#45 0x7f4c72d73d06 _PyRun_SimpleFileObject.localalias
#46 0x7f4c72d74591 _PyRun_AnyFileObject.localalias
#47 0x7f4c72d76fc6 Py_RunMain.localalias
#48 0x7f4c7283ffce __libc_start_call_main
#49 0x7f4c72840089 __libc_start_main_alias_2
#50 0x000000401075 _start
  r8: 000000000000f000  r9: 0000000000000001 r10: 0000000000000001 r11: 0000000000000001
 r12: 00000000023a91f0 r13: 000000000000002c r14: 00007ffce5304fa0 r15: 0000000000000001
  di: 0000000000000000  si: 00000000023aac60  bp: 00007ffce5304f50  bx: 00007f4c68f5ed40
  dx: 0000000000000002  ax: 0000000000000000  cx: 0000000000000069  sp: 00007ffce5304c58
  ip: 00007f4c63dfa1b0 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000020
[end of stack trace]
fish: Job 1, 'qutebrowser' terminated by signal SIGSEGV (Address boundary error)

**How to reproduce**
idk, use the latest version of qutebrowser, (im using nixos unstable with hyprland etc) and open gmail?? (idk but this is the place i had the problem it probably affects other things too) and start doing stuff... idk how easy it will be to reproduce on other machines but im consistently having this problem. thanks!

**Comment by The-Compiler** [comment] 2023-10-27 13:41
Duplicate of #7962

**Closed by The-Compiler** 2023-10-27 13:41 UTC
