### ISSUE TITLE
javascript: window.print(); does not work

### ISSUE THREAD

**Issue by dnebauer** [qutebrowser/qutebrowser#3968] opened 2018-06-01 01:10 UTC
The site eventcinemas.com.au generates a page with a button that has the link url `javascript: window.print();`

When I push the button nothing happens. In google chrome pushing the button invokes a print dialog.

Using the qutebrowser `:print` command results in gibberish output. Clearly the javascript is reformatting the page or fetching an alternate version for printing.

All of my `content.javascript.*` settings are `true` except for `content.javascript.can_close_tabs` and, of course, `content.javascript.log` which is a dictionary.

Is the non-operation of this button a bug or feature of qutebrowser?

------------------
qutebrowser v1.3.0
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.0-1-amd64-x86_64-with-debian-buster-sid, 64bit
Linux distribution: Debian GNU/Linux buster/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

**Comment by jgkamat** [comment] 2018-06-01 01:12
Duplicate of #3495 

See https://github.com/qutebrowser/qutebrowser/pull/3864.

**Closed by jgkamat** 2018-06-01 01:12 UTC
