### ISSUE TITLE
I cannot enter Polish characters on Windows 10.

### ISSUE THREAD

**Issue by skowalczyk** [qutebrowser/qutebrowser#5723] opened 2020-09-17 10:16 UTC
I had 1.9.0 for a long time without any issues but after upgrade to latest build I can't input Polich characters (e.g. RAlt + a for ą character) in input boxes. It works fine in command prompt. I had to return back to 1.9.0 to have it working fine (tested 1.12.0 and this doesn't work too). Everything works fine on Arch Linux and FreeBSD for me so looks like something platform specyfix.

**Comment by The-Compiler** [comment] 2020-09-17 10:32
Duplicate of #5399

**Comment by The-Compiler** [comment] 2020-09-17 10:32
FWIW this will be fixed as soon as a qutebrowser release with Qt 5.15.1 is done, most likely today or later this week - #5399 also has a workaround.

**Closed by The-Compiler** 2020-09-17 10:32 UTC
