### ISSUE TITLE
Allow literal (non-percent-encoded) search terms for url.searchengines

### ISSUE THREAD

**Issue by rlue** [qutebrowser/qutebrowser#4990] opened 2019-08-28 10:56 UTC
### Problem

I have a search shortcut (via the `url.searchengines` config option) set up for The Wayback Machine / archive.org. Archive.org expects a complete URL, including the leading "http://". Qutebrowser take URL-unsafe characters in search terms and percent-encodes them, so I end up with a failed search:

![Screenshot_20190828_185312](https://user-images.githubusercontent.com/12194123/63849670-22bc0b00-c9c5-11e9-9605-e522b0d05e1b.png)

### Proposal

Currently, `url.searchengines` recognizes a string placeholder (`"{}"`) in search URLs that it replaces with the percent-encoded search term. Could we get a separate placeholder for literal search terms; _i.e.,_ ones that get passed verbatim to the search URL?

Don't know what string I would suggest as the new placeholder, though, and not sure how this might affect existing users.

**Comment by The-Compiler** [comment] 2019-08-28 13:13
Duplicate of #1772

**Closed by The-Compiler** 2019-08-28 13:13 UTC
