### ISSUE TITLE
Drag and drop leaving artifacts

### ISSUE THREAD

**Issue by Gavinok** [qutebrowser/qutebrowser#5563] opened 2020-07-02 21:51 UTC
**Version info**:

qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.3
PyQt: 5.15.0

sip: 5.3.0i
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.32.2
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 2.1 Mesa 20.0.7
Platform: Linux-5.4.44-1-MANJARO-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/gavinok/.cache/qutebrowser
config: /home/gavinok/.config/qutebrowser
data: /home/gavinok/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/gavinok/.config/qutebrowser/config.py has been loaded
Uptime: 1:23:28

**Does the bug happen if you start with `--temp-basedir`?**:

yes

**Description**

When ever a link or image is dragged the simi translucent link/image is left on screen until qutebrowser is closed.

**How to reproduce**

This may come from QT or Xorg but here is a gif demoing the issue

**Comment by Gavinok** [comment] 2020-07-02 21:54
Sorry the gif was a bit too big ill post a link to it

**Comment by Gavinok** [comment] 2020-07-02 22:08
sorry for the delay here is the [link](https://drive.google.com/file/d/1qk34IVvzoDabgL852qD7mUxrCL3Q6eA6/view?usp=sharing)

**Comment by The-Compiler** [comment] 2020-07-03 07:12
Huh, that's weird. For reference, here's a screenshot from the GIF:

![image](https://user-images.githubusercontent.com/625793/86441930-39ca3880-bd0d-11ea-9746-27f3aa0c82ea.png)

I can't reproduce though, and I doubt qutebrowser is to blame. What window manager are you using? Also, can you try whether this is reproducible with [KDE Falkon](https://falkon.org/) and/or Chromium?

**Comment by Gavinok** [comment] 2020-07-03 20:36
@The-Compiler this issue does not seem to exist in Chromium. I am using dwm, I will try this in a different window manager and see if it persists.

**Comment by The-Compiler** [comment] 2020-07-06 13:03
Thanks for the update! Would be good if you could try with Falkon as well.

**Comment by Gavinok** [comment] 2020-07-07 00:14
i3 has the same issue. 
Falkon also seems to display the same issue.

**Comment by Gavinok** [comment] 2020-07-07 00:15
Sorry didnt mean to close that

**Comment by The-Compiler** [comment] 2020-07-07 07:57
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2020-07-07 07:57 UTC
Labels: status: can't reproduce, status: needs triage
