### ISSUE TITLE
Cannot activate context menu command with keyboard

### ISSUE THREAD

**Issue by qvtqht** [qutebrowser/qutebrowser#6189] opened 2021-02-21 08:28 UTC
**Version info**:
qutebrowser v2.0.2
Git commit: 53b05692e on master (2021-02-12 22:58:32 +0100)
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Context menu items cannot be activated with keyboard

**How to reproduce**
1. Open a page
2. Activate context menu, either with context menu key, Shift+F10, or right-clicking mouse
3. Use arrow keys to select an enabled/available item in the context menu
4. Press Enter

Expected: Selected context menu item is activated, and context menu goes away

Actual: No visible change

**Comment by The-Compiler** [comment] 2021-02-21 09:36
Duplicate of #6129

**Closed by The-Compiler** 2021-02-21 09:36 UTC
