### ISSUE TITLE
:yank syntax inconsistent ?

### ISSUE THREAD

**Issue by sorezzz** [qutebrowser/qutebrowser#3268] opened 2017-11-11 14:04 UTC
version: http://ix.io/Cae

`:spawn blablala {url}`
VS
`:yank -s url`

i initially used {url} on the 2nd one but it said invalid value. Didnt expect that to be honest. Afterwards i thought ":yank -s url" would just yank the string "url" in the clipboard.

**Comment by jgkamat** [comment] 2017-11-11 15:44
If I understand the expansion correctly. `{url}` and other `{...}` terms are expanded before they are even sent to the command. For example:

`:info {url}`

prints out

`https://github.com/qutebrowser/qutebrowser/issues/3268`

for me.

So the command `:yank -s {url}` would always run `:yank -s <current actual url of page>`. 

I suppose it's possible for :yank to parse the immediate value, but that would require making expansions of all the other hint types.

**Comment by The-Compiler** [comment] 2017-11-12 16:04
Duplicate of #901

**Closed by The-Compiler** 2017-11-12 16:04 UTC
