### ISSUE TITLE
Qt components

### ISSUE THREAD

**Issue by ruby-zen** [qutebrowser/qutebrowser#6606] opened 2021-07-16 17:40 UTC
### Discussed in https://github.com/qutebrowser/qutebrowser/discussions/6604

<div type='discussions-op-text'>

<sup>Originally posted by **ruby-zen** July 16, 2021</sup>
None of the components that are listed under `Qt` (see below) are available in the Custom Installation of the latest Qt open source installer version `6.1.1` (there are other versions as well). Could you please say what components must be selected in the custom installation of the Qt installer? There are no components by any of the names given below. I am new to this. Could you please say what components must be selected?

```
Qt 5.12.0 or newer (5.12 LTS or 5.15 recommended) with the following modules:

QtCore / qtbase

QtQuick (part of qtbase or qtdeclarative in some distributions)

QtSQL (part of qtbase in some distributions)

QtDBus (part of qtbase in some distributions; note that a connection to DBus at runtime is optional)

QtOpenGL

QtWebEngine, or

alternatively QtWebKit (5.212)
```
</div>

**Comment by The-Compiler** [comment] 2021-07-19 08:27
Duplicate of #6605

**Closed by The-Compiler** 2021-07-19 08:27 UTC
