### ISSUE TITLE
ebay.de: infinite captcha

### ISSUE THREAD

**Issue by mike402** [qutebrowser/qutebrowser#5088] opened 2019-10-24 00:43 UTC
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/72854681

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
ebay.de gives me a CAPTCHA when I enter name and password, and after I complete it I only get another one. Started happening today.
But ebay.com seems fine.

**How to reproduce**
http://ebay.de
Make eBay ask your password, either by logging in, or by trying to access your personal data.

**Comment by The-Compiler** [comment] 2019-10-24 06:10
Works fine for me, I can log in without any captcha. Does it work in Chromium? If so, can you try how things look if you do `:set content.headers.user_agent` and select the Chrome one from the completion?

**Comment by mike402** [comment] 2019-10-27 12:41
That does not make it go away.

**Comment by The-Compiler** [comment] 2019-10-27 12:51
So have you tested in Chromium? Could you also try with [KDE Falkon](https://www.falkon.org/)?

**Comment by mike402** [comment] 2019-10-27 13:06
Sorry, I had not seen about trying Chromium or Falkon at first.

With Chromium they simply let me in, and with Falkon I got asked twice in a row to verify my account with email or phone, but it worked.

**Comment by mike402** [comment] 2019-12-02 21:19
ebay.com has started "Loading captcha" forever, so I can't use it as a workaround anymore.

**Comment by mschilli87** [comment] 2020-04-06 10:26
I'm hitting this as well but can't reproduce it via

```sh
 qutebrowser --temp-basedir signin.ebay.de
```

I'll go through my config and see if I can find out what's causing this.

**Comment by mschilli87** [comment] 2020-04-06 10:52
Turns out when I have `content.canvas_reading` set to `false`, I get the infinite capture, when I (un)set it to `true` [default] (and restart qutebrowser), I'm not even asked for the capture at all.

**Comment by mike402** [comment] 2020-04-06 11:08
On Mon, Apr 06, 2020 at 03:52:40AM -0700, Marcel Schilling wrote:
> Turns out when I have `content.canvas_reading` set to `false`, I get the infinite capture, when I (un)set it to `true` [default] (and restart qutebrowser), I'm not even asked for the capture at all.

Wow, thank you so much -- now I can use ebay again!

Weird, but back when I tried to investigate, --temp-basedir didn't
seem to help. :S

Is is possible to enable canvas reading only for ebay somehow, so that
the rest of the web can't abuse it?

**Comment by The-Compiler** [comment] 2020-04-06 11:26
Nope, it's only available as a global setting, as it's passed as a command-line argument to Chromium. Closing this then, as I don't think there's anything more qutebrowser can do here.

**Closed by The-Compiler** 2020-04-06 11:26 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by mschilli87** [comment] 2020-04-06 12:25
I guess in principle there could be an option to open specific webpages in a new instance appliying host-specific config. Clearly not a priority but maybe somethig to keep thinking about..

**Comment by mike402** [comment] 2020-04-21 12:08
Now it won't let me in even with canvas reading enabled.

**Comment by mschilli87** [comment] 2020-04-21 12:11
@mike402: Did you restart the browser (and delete cookies/caches)?

**Comment by The-Compiler** [comment] 2020-04-21 12:18
Still no issues (and not even a captcha) here. I don't think qutebrowser can do anything about ebay's behavior here. You might want to double-check `qute://configdiff` and see if you have some other things which might trigger some kind of automatic reaction set (e.g. `content.headers.*`).

**Comment by mschilli87** [comment] 2020-04-21 13:12
I also only got a captcha at all with canvas reading disable, now with it being enabled, I never get asked to complete one anymore.

**Comment by The-Compiler** [comment] 2020-04-23 07:56
Indeed, I can reproduce the captcha loop now when disabling canvas reading. I can also reproduce it with `chromium --user-data-dir=/tmp/ebaytest --disable-reading-from-canvas ebay.de` - so definitely an issue ebay needs to fix on their side.

**Comment by mike402** [comment] 2020-04-23 08:10
By the way I forgot to ask -- how does one even report site issues to
ebay? There seems to be no contact form or email for that kind of stuff
anywhere?

**Comment by The-Compiler** [comment] 2020-04-23 08:18
I have no secret insider knowledge - all I can do is wish you good luck...

**Comment by mike402** [comment] 2020-05-14 20:45
Turns out this was caused by me forgetting the `--qt-flag disable-reading-from-canvas` on even after enabling canvas reading in config.
