### ISSUE TITLE
Grafana dashboard toolbar elements vibrate between responsive display modes

### ISSUE THREAD

**Issue by trysdyn** [qutebrowser/qutebrowser#7516] opened 2022-12-09 22:54 UTC
**Version info**:
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.11, based on Chromium 87.0.4280.144
Qt: 5.15.7

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When accessing a stock, unconfigured Grafana (v9.3.0) web interface the top toolbar vibrates between its two responsive modes rapidly and CPU usage spikes dramatically. Grafana's page code seems to not be able to understand resolution reporting from Qute properly and can't figure out if it should be displaying the full or truncated toolbar.

**How to reproduce**
The Grafana public demo exhibits this behavior immediately (https://play.grafana.org). The buttons in the far top-right should put on quite a show. Note the public demo may flat out reject you if your user-agent isn't spoofed to one of the Big Three-- ugh.

I can replicate this on a personal install as well, but I cannot link you to that :)

This may be a Grafana bug but I cannot replicate with any of their "Supported" browsers.

**Comment by toofar** [comment] 2022-12-09 23:40
Lovely. Reproduced on 6.3.3. I thing it might be [this bit](https://github.com/grafana/grafana/blob/717bd4a6c051d1447c9e35385a4ba176dd391c65/packages/grafana-ui/src/components/ToolbarButton/ToolbarButtonRow.tsx#L45). Not sure why it would be playing up for us though. 

Probably worth opening an issue with them since it's a recent-ish change and easy to reproduce.

**Comment by The-Compiler** [comment] 2022-12-10 12:37
It works fine with QtWebEngine 6.4, so it sounds like this is a Chromium bug which has been fixed in the meantime. I did a [bisect](https://www.chromium.org/developers/bisect-builds-py/) of them, and it gives me:

You are probably looking for a change made after 951766 (known bad), but no later than 951778 (first known good).
CHANGELOG URL:
  https://chromium.googlesource.com/chromium/src/+log/1fb9d004439f8f11d5b2ab70461c5cd15f5f1ebd..b81db9265e8c0cd5f13235e78d3af1ff55b84ab4

From the commits there, it looks like it's probably this one:

- [77a814f3e1b108831994a78d29f091d8df5f84f3 - chromium/src - Git at Google](https://chromium.googlesource.com/chromium/src/+/77a814f3e1b108831994a78d29f091d8df5f84f3)
- [1278897 - ResizeObserver isIntersecting issues with browser zoom - chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1278897)

Nothing qutebrowser can do about this, I'm afraid.

**Closed by The-Compiler** 2022-12-10 12:37 UTC
