### ISSUE TITLE
unable to bind some keys in insert mode

### ISSUE THREAD

**Issue by lxhillwind** [qutebrowser/qutebrowser#3552] opened 2018-02-02 13:04 UTC
I can not bind some keys in insert mode since 2 or 3 months ago.

On Linux, `:bind --mode insert <ctrl+a> fake-key <Home>` does not behave like pressing `<Home>`, but selecting all;

On macos, `:bind --mode insert <ctrl+k> fake-key <shift+End> ;; fake-key <Delete>` does not kill line to end, but delete a character.

I have tried to run qutebrowser with `--temp-basedir`, but they don't work either.

my qutebrowser version info:
```
qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.0
PyQt: 5.10

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: Breeze::Style
Platform: Linux-4.14.15-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/lxhillwind/.cache/qutebrowser
config: /home/lxhillwind/.config/qutebrowser
data: /home/lxhillwind/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```

**Comment by The-Compiler** [comment] 2018-02-02 13:06
Duplicate of #3419

**Closed by The-Compiler** 2018-02-02 13:06 UTC
Labels: bug: behavior, component: QtWebEngine, component: keyinput
