### ISSUE TITLE
ValueError when running :set aliases

### ISSUE THREAD

**Issue by kobezda** [qutebrowser/qutebrowser#1944] opened 2016-09-12 14:17 UTC
When I run 

```
:set aliases o open -t
:o qutebrowser.org
```

then qutebrowser crashes with a ValueError.

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/qutebrowser/misc/savemanager.py", line 181, in autosave
    saveable.save(silent=True)
  File "/usr/lib/python3.4/site-packages/qutebrowser/misc/savemanager.py", line 99, in save
    self._save_handler()
  File "/usr/lib/python3.4/site-packages/qutebrowser/config/config.py", line 874, in save
    f.write(str(self))
  File "/usr/lib/python3.4/site-packages/qutebrowser/config/config.py", line 456, in __str__
    lines += self._str_items(sect)
  File "/usr/lib/python3.4/site-packages/qutebrowser/config/config.py", line 510, in _str_items
    value = option.value(startlayer='conf')
  File "/usr/lib/python3.4/site-packages/qutebrowser/config/value.py", line 84, in value
    raise ValueError("No valid config value found!")
ValueError: No valid config value found!
```

Here's a full log: [qute.log.txt](https://github.com/The-Compiler/qutebrowser/files/467500/qute.log.txt)

**Comment by The-Compiler** [comment] 2016-09-12 16:52
I can reproduce this even without the second `:o` - the crash happens with the next config save after a few seconds.

**Comment by R053NR07** [comment] 2016-09-30 10:15
The -t is interpreted as temp flag for the set.

Would adding a maxsplit=2 to ConfigManager.set_command fix this Problem?

**Comment by The-Compiler** [comment] 2016-09-30 10:41
That'd change the semantics of how `:set` works, and there are some discussions about getting rid of things like maxsplit altogether (and always enforce correct quoting). I don't think anything should be changed about that.

**Comment by The-Compiler** [comment] 2017-03-27 08:22
Duplicate of #1283.

**Closed by The-Compiler** 2017-03-27 08:22 UTC
Labels: bug, component: config, priority: 1 - middle
