### ISSUE TITLE
cVim style tab undo command

### ISSUE THREAD

**Issue by Ape** [qutebrowser/qutebrowser#2862] opened 2017-07-26 04:36 UTC
cVim has this `:restore` command that allows you to undo closed tabs. Unlike qutebrowser's `undo`, it will allow you to select which of the previously closed tabs you would like to reopen.

**Comment by The-Compiler** [comment] 2017-07-26 05:26
Duplicate of #32

**Closed by The-Compiler** 2017-07-26 05:26 UTC
