### ISSUE TITLE
Bug: "yy" covers tabs if located at the bottom

### ISSUE THREAD

**Issue by krzemian** [qutebrowser/qutebrowser#3302] opened 2017-11-16 16:19 UTC
1. Set tabs.position to "bottom" and have it visible
2. Try "yy", "yY" (possibly more commands similar in behavior)
3. The text "Yanked URL to..." hovers over the tab list at the bottom, making them hidden until the prompt is clicked/timeouts.

My suggestion would be to present the message stacked next to the tab/status bar rather than on top of it. Or to allow to config the position of the message bar separately.

Using qb v1.0.3

**Comment by The-Compiler** [comment] 2017-11-16 19:35
Duplicate of #3067

**Closed by The-Compiler** 2017-11-16 19:35 UTC
