### ISSUE TITLE
Occasionally, custom stylesheets break if site styles are in header

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#3377] opened 2017-12-10 18:31 UTC
I've been running into this for quite a while I think even before the new stylesheet code, but I've finally managed to create a minimal reproduction:

[testfiles.zip](https://github.com/qutebrowser/qutebrowser/files/1545912/testfiles.zip)

If you open test.html, click the link, then navigate back to the test.html tab and refresh the page, custom user supplied stylesheets will be broken. For some reason, the one that I ran into on real sites caused the stylesheets to break on that tab for the rest of sites that were loaded in it, causing me to have to clone the tab.

This seems to be caused by including a stylesheet like this:
```
<head>
<link rel="StyleSheet" href="base.css" type="text/css">
</head>
```

Let me know if you can't reproduce, I could reproduce on qtwebengine 5.9 as well (on arch).
```
qutebrowser v1.0.4
Git commit: 5c5f99282 (2017-12-07 14:53:15 -0500)
Backend: QtWebEngine (Chromium 49.0.2623.111)

CPython: 3.5.3
Qt: 5.7.1
PyQt: 5.7.1

sip: 4.19.5
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 16.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.11.1
QtNetwork SSL: 

Style: QFusionStyle
Platform: Linux-4.9.0-4-amd64-x86_64-with-debian-9.3, 64bit
Linux distribution: Debian GNU/Linux 9 (stretch) (debian)
Frozen: False
Imported from /home/jay/.local/lib/python3.5/site-packages/qutebrowser
Qt library executable path: /home/jay/.local/lib/python3.5/site-packages/PyQt5/Qt/libexec, data path: /home/jay/.local/lib/python3.5/site-packages/PyQt5/Qt

Paths:
cache: /home/jay/.cache/qutebrowser
config: /home/jay/.config/qutebrowser
data: /home/jay/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Uptime: 10:05:18
```

**Comment by The-Compiler** [comment] 2017-12-10 22:10
I can reproduce this, even with Qt 5.10. It looks like our stylesheet doesn't get added to the page at all anymore, maybe because some script isn't running anymore?

I don't see any JS errors, so I'll have to investigate some more... cc @ulrikdem

**Comment by davidebaldini** [comment] 2017-12-17 13:30
I noticed that webpages which load stylesheets in the following way don't show any problem with custom stylesheets loaded with `content.user_dtylesheets` :

    <meta>
        <link crossorigin="anonymous" href="style.css" integrity="sha256-HCwxa3oX8VU2xqJu10RlT8IookZYp645XNy/gynIQGs=" media="all" rel="stylesheet">
    </meta>

github.com loads its stylesheets like that.

Instead, google.com uses this:

    <meta>
        <link rel="stylesheet" href="/s1509.css" type="text/css">
    </meta>

and on google I noticed that custom stylesheets do get loaded and affect the page in some unexpected way, but they aren't fully applied or maybe not applied the the whole DOM.

**Comment by ulrikdem** [comment] 2017-12-18 18:50
As far as I can tell, the method used by the page to include its stylesheets has no effect on this. In fact, I can reproduce it using a page without any styles.

It seems that the issue occurs when:
- A new tab is opened using a `target="_blank"` link or the `window.open()` function. New tabs opened by holding `ctrl` while clicking a link do not exhibit this behavior.
- Either the old tab or the new tab is closed.

The result is that scripts added to the profile (including the user stylesheet injection and Greasemonkey scripts) are no longer executed in the remaining tab.

This may be an issue with QtWebEngine, since I get the same behavior with QupZilla.

**Comment by The-Compiler** [comment] 2018-02-12 09:35
@toofar opened [QTBUG-66336](https://bugreports.qt.io/browse/QTBUG-66336) for this now. If you have a bugreports.qt.io account, please give it a vote :wink:

**Comment by The-Compiler** [comment] 2018-02-21 22:40
Can someone try with Qt 5.10.1 (or 5.9.4 / 5.11 Alpha)?

**Comment by ulrikdem** [comment] 2018-02-22 14:31
I can no longer reproduce this with Qt 5.10.1.

**Comment by The-Compiler** [comment] 2018-03-08 13:47
Closing this then - in #3497 someone mentioned that this still affects GreaseMonkey with Qt 5.10.1, but maybe at least this one is fixed.

**Closed by The-Compiler** 2018-03-08 13:47 UTC
Labels: bug: behavior, component: QtWebEngine, priority: 2 - low
