### ISSUE TITLE
Show a visual notification when following a hint

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2943] opened 2017-09-01 12:24 UTC
E.g. with Pentadactyl the hint label would flash Yellow+Green for a second before following.

Also maybe show a visual notification when no hint is followed as a result of entering a keystring which filters all the hints out.

**Comment by lahwaacz** [comment] 2017-09-01 12:31
Why wait for a whole _second_ when the page might load up in just a couple of milliseconds?

**Comment by pkillnine** [comment] 2017-09-01 12:45
well it doesn't have to wait

**Comment by The-Compiler** [comment] 2017-09-04 13:14
Duplicate of #2836

**Closed by The-Compiler** 2017-09-04 13:14 UTC

**Comment by mschilli87** [comment] 2017-09-04 13:22
From what I understood #2836 suggested flashing upon *yanking a hint URL* while this suggest flashing upon *following a hint*.

**Comment by The-Compiler** [comment] 2017-09-04 13:24
Hmm, right - still makes sense to track them in one issue, since they're very similar. I'll add a comment there.
