### ISSUE TITLE
`imap jk <Esc>` in qutebrowser?

### ISSUE THREAD

**Issue by adtac** [qutebrowser/qutebrowser#3448] opened 2017-12-29 13:43 UTC
In (neo)vim, I do:

```vim
imap jk <Esc>
```

to use `jk` to jump from insert mode to normal mode. Is there any way to do this in qutebrowser?

**Comment by The-Compiler** [comment] 2017-12-29 13:54
Duplicate of #1044

**Closed** 2017-12-29 13:54 UTC
Labels: component: keyinput
