### ISSUE TITLE
Screen is flashing white

### ISSUE THREAD

**Issue by wgmayer0** [qutebrowser/qutebrowser#6894] opened 2021-12-15 19:25 UTC
**Version info**:

qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes - but the frequency of the flash is much faster and less frequent

**Description**
While using Qutebrowser, the screen constantly blinks white. I think it could be related to this bug report: https://gitlab.freedesktop.org/mesa/mesa/-/issues/5745.

It also flickers when scrolling using the space bar.

**How to reproduce**

1. Upgrade mesa package on Arch Linux
    -https://archlinux.org/packages/extra/x86_64/mesa/
2. Use the most current version of Qutebrowser

**Comment by The-Compiler** [comment] 2021-12-15 19:27
Duplicate of #6890

**Closed** 2021-12-15 19:28 UTC
