### ISSUE TITLE
CLI flag to only open private window retaining config

### ISSUE THREAD

**Issue by billop** [qutebrowser/qutebrowser#5225] opened 2020-02-09 10:06 UTC
It seems like there are 2 main ways of opening a new private window but each has a downside:

```
qutebrowser ':open -p'
```
works well unless there are no existing instances, in which case this will first open a nonprivate instance

```
qutebrowser --temp-basedir -s content.private_browsing true
```
does not read from main config.py

It would be nice for there to be a simple flag (e.g. --private) that behaved like the first example whether or not there are already instances.

**Comment by The-Compiler** [comment] 2020-02-09 19:05
Duplicate of #4643

**Closed by The-Compiler** 2020-02-09 19:05 UTC
