### ISSUE TITLE
Window management issue in qutebrowser

### ISSUE THREAD

**Issue by YuvanMichael** [qutebrowser/qutebrowser#7566] opened 2023-01-29 11:55 UTC
**Version info**:
Has been there for quite a few versions but it is still there now. I'm using Arch so, probably latest stable version. 

**Does the bug happen if you start with `--temp-basedir`?**:
no, I just start qutebrowser normally without any flags. It only loads my config that's all. And there is nothing wrong with the config. 
**Description**
Qutebrowser takes up all space of my screen. Nothing I can do. I'm using Xmonad. Tried other window managers, DE's as well same issue. First time installing works well for a few weeks. But then takes up my laptop's screen space. It just covers the screen although it functions well. And no, my system works fine too. Usually I have to reinstall Arch to get it fixed. But, after a few days it comes back again. This issue was there for maybe 1 or 2 years by now. Couldn't even find a solution online. So I'm posting an issue now. 
**How to reproduce**
Open qutebrowser. 

Screenshots:

normal: with xmobar wallpaper etc.
![maim-full-20230129-172110](https://user-images.githubusercontent.com/86945563/215324343-c309082d-7a1a-4aaf-9f5f-4167664cde3a.png)

qutebrowser: without xmobar wallpaper etc
![maim-full-20230129-172329](https://user-images.githubusercontent.com/86945563/215324403-f4f41687-baf9-4f2d-a1db-5c8bd30fc6db.png)

Hoping to get this fixed and be able to use qutebrowser again

**Comment by The-Compiler** [comment] 2023-01-29 12:04
Please try to reproduce with `--temp-basedir`. There's a reason the issue template asks you to...

**Comment by YuvanMichael** [comment] 2023-01-29 13:24
It works with --temp-basedir flag and -C for my config. Thank you for your help. But why does it happen in a strangely frequent way? I think when it works normally for a few days it should kind of work like that unless there is some major update to python or qutebrowser and something's wrong with the config.

**Comment by The-Compiler** [comment] 2023-01-29 13:26
Does a `:fullscreen` fix it? Do you quit qutebrowser while it's fullscreened?

**Comment by YuvanMichael** [comment] 2023-01-29 14:28
I did quit qutebrowser once when I was in fullscreen/wide mode. I didn't want to but did it. I guess this is when this started again today. not sure what you mean by :fullscreen.

**Comment by YuvanMichael** [comment] 2023-01-29 14:29
Sorry for the hourly delays in my replies. I was doing other work.

**Comment by YuvanMichael** [comment] 2023-01-29 14:30
With the --temp-basedir flag you told me to try it doesn't follow my quickmarks

**Comment by The-Compiler** [comment] 2023-01-29 14:38
> I did quit qutebrowser once when I was in fullscreen/wide mode. I didn't want to but did it. I guess this is when this started again today.

It remembers the window position/state when quitting, and fullscreen state is part of this. I'm assuming this is a duplicate of #5262 then.

> not sure what you mean by :fullscreen.

It's a qutebrowser command. You run it by typing just that inside qutebrowser.

> With the --temp-basedir flag you told me to try it doesn't follow my quickmarks

That's the point of `--temp-basedir`, that it doesn't load any state.

**Closed by The-Compiler** 2023-01-29 14:38 UTC
Labels: status: can't reproduce, status: needs triage
