### ISSUE TITLE
can't download files that require authentication

### ISSUE THREAD

**Issue by Francesco149** [qutebrowser/qutebrowser#3037] opened 2017-09-29 11:31 UTC
i happen to be using a site called pixiv, which requires you to be logged in with google or other methods to view and download full images. here's an example image: https://www.pixiv.net/member_illust.php?mode=medium&illust_id=50825865 .

if you enlarge it and try to download it from qutebrowser with right click -> save image it will fail. if you try to wget the direct url to the image, you get a 403 forbidden error, which is what i suppose is happening in qutebrowser.

firefox lets me right click and save image just fine once logged in, so I'm guessing the server wants you to send whatever cookies to show that you're logged in and qutebrowser doesn't send any on downloads.

qutebrowser version:

```
qutebrowser v0.11.0
Git commit: 
Backend: QtWebEngine (Chromium 49.0.2623.111)

CPython: 3.5.3
Qt: 5.7.1
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
OpenGL: 3.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
SSL: OpenSSL 1.0.2g  1 Mar 2016

Style: Qt5CTProxyStyle
Platform: Linux-4.10.0-35-generic-x86_64-with-Ubuntu-17.04-zesty, 64bit
Linux distribution: Ubuntu 17.04 (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
data: /home/loli/.local/share/qutebrowser
download: /home/loli/Downloads
runtime: /run/user/1000/qutebrowser
config: /home/loli/.config/qutebrowser
cache: /home/loli/.cache/qutebrowser
system_data: /usr/share/qutebrowser
```

**Comment by The-Compiler** [comment] 2017-09-29 11:36
Duplicate of #2713

**Closed by The-Compiler** 2017-09-29 11:36 UTC
