### ISSUE TITLE
[destroyed object]: error 7: importing the supplied dmabufs failed

### ISSUE THREAD

**Issue by foxjaw** [qutebrowser/qutebrowser#8020] opened 2023-12-07 05:13 UTC
**Version info**:

```
qutebrowser v3.0.2
Git commit: 
Backend: QtWebEngine 6.6.1, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.1

CPython: 3.11.6
PyQt: 6.6.1

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.2
pygments: no
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.6.0
PyQt6.sip: 6.7.12
pdf.js: no
sqlite: 3.44.2
QtNetwork SSL: OpenSSL 3.1.4 24 Oct 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: OpenGL ES
Platform: Linux-6.6.4-zen1-1-zen-x86_64-with-glibc2.38, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: ~/.cache/qutebrowser
config: ~/.config/qutebrowser
data: ~/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00

```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
```
[destroyed object]: error 7: importing the supplied dmabufs failed
10:36:56 WARNING: The Wayland connection experienced a fatal error: Protocol error
```

### Additional Info
Archlinux, (updated), sway, native wayland, PyQT6/QT5  
env vars:
```
GBM_BACKEND=nvidia-drm
__GL_GSYNC_ALLOWED=0
__GL_SYNC_TO_VBLANK=0
__GL_VENDOR_LIBRARY_NAME=nvidia
__GL_VRR_ALLOWED=0
__GLX_VENDOR_LIBRARY_NAME=nvidia
LIBVA_DRIVER_NAME=nvidia
MOZ_DISABLE_RDD_SANDBOX=1
```
sway vars:  
```
export \
	EGL_PLATFORM=wayland \
	GDK_BACKEND=wayland \
	MUTTER_DEBUG_DISABLE_HW_CURSORS=1 \
	QT_AUTO_SCREEN_SCALE_FACTOR=1 \
	QT_QPA_PLATFORM=wayland \
	QT_SCALE_FACTOR=1 \
	QT_WAYLAND_DISABLE_WINDOWDECORATION=1 \
	WLR_{DRM_NO_ATOMIC,NO_HARDWARE_CURSORS}=1 \
	WLR_RENDERER=vulkan \
	XDG_{CURRENT,SESSION}_DESKTOP=sway \
	XDG_SESSION_TYPE=wayland \
	XWAYLAND_NO_GLAMOR=1
sway -- unsupported-gpu -Dnoscanout
```

Yes. Nvidia ;D

**Comment by The-Compiler** [comment] 2023-12-07 10:25
When/how does that happen? Just when starting? Could you try running the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py) please?

**Comment by The-Compiler** [comment] 2023-12-07 12:08
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can easily reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2023-12-07 12:08 UTC
Labels: status: can't reproduce, status: needs triage
