### ISSUE TITLE
Microsoft Defender on Windows 10 thought file qutebrowser.exe was a "Win32/Contebrew.A!ml" and deleted it.

### ISSUE THREAD

**Issue by fungus78sea** [qutebrowser/qutebrowser#8437] opened 2024-12-25 08:50 UTC
**Version info**:
qutebrowser v3.4.0
Backend: QtWebEngine 6.8.1
  based on Chromium 122.0.6261.171
  with security patches up to 131.0.6778.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.1

CPython: 3.13.1
PyQt: 6.8.0

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.4
pygments: 2.18.0
yaml: 6.0.2
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.8.0
PyQt6.sip: 6.9.1
pdf.js: 4.9.155 (bundled)
sqlite: 3.47.0
QtNetwork SSL: OpenSSL 3.0.5 5 Jul 2022

**Does the bug happen if you start with --temp-basedir?**:
Yes.

**Description**
Microsoft Defender on Windows 10 thought file qutebrowser.exe was a "Win32/Contebrew.A!ml" and deleted it.

![Screenshot from Microsoft Defender](https://github.com/user-attachments/assets/7ec93584-f0b6-433a-ae7c-a39f8a9f843c)

qutebrowser.exe in VirusTotal: https://www.virustotal.com/gui/file/7aafc20f3d01181d69d95afeedcf426e317250104a55d11563c127f0e3939cb3

**Comment by The-Compiler** [comment] 2024-12-25 11:36
Duplicate of #8389

**Closed by The-Compiler** 2024-12-25 11:36 UTC
