### ISSUE TITLE
URL incorrectly coloured on youtube.com

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#3110] opened 2017-10-13 14:09 UTC
If you go to https://www.youtube.com and click on a video/channel, the URL colour will change from green to the plain HTTP one. This might be due to Youtube's use of Javascript to change the URL in the addressbar.

**Comment by ryan-farley** [comment] 2017-10-14 04:40
This only occurs on the WebEngine backend, and is specifically caused by the absense of the [`loadFinished`] signal (which I verified by adding debug logging to each signal in the chain leading to `on_load_status_changed` which actually sets the color). The linked documentation explicitly states

> This signal is independent of script execution or page rendering

so if YouTube is able to cause this, it's most likely an upstream bug in WebEngine (or maybe PyQt's interface to it) rather than the Qutebrowser backend code.

**Comment by The-Compiler** [comment] 2017-10-14 14:52
I think the "This signal is independent of script execution or page rendering" means "The signal is emitted when the page finished loading content, but it might still be rendering or running scripts".

The important thing here is that a page can't show up as green (HTTPS) when it isn't in fact a HTTPS page. We clear the URL color in `AbstractTab._on_load_started` and set the color based on the URL scheme in `_on_load_finished`.  From what it looks, loading things dynamically in a way that changes the URL always emits `_on_load_started` (but not `_on_load_finished`), so that part is hopefully fine.

Still, I'd like to look into what YouTube is doing there exactly (can someone knowing JS better than I do comment on that?) and why it doesn't trigger the `loadFinished` signal. I guess we could update the color as a response of `urlChanged`, but then we don't know the load status.

**Comment by The-Compiler** [comment] 2017-10-14 15:10
I can reproduce this with `:jseval history.pushState({}, "title", "foo.html")` (see [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API)) here on GitHub. The URL gets white (as there is a `loadStarted` but no `loadFinished`).

Thankfully, it's not possible to call `pushState` with an URL from a different origin.

**Comment by ryan-farley** [comment] 2017-10-14 19:01
The same signal behavior can be observed in QupZilla as well. Their mitigations (starting around [here](https://github.com/QupZilla/qupzilla/blob/1d34e97c3705adf3565ea3dacc0268a76aa579ec/src/lib/webengine/webpage.cpp#L185)) involve using the loadProgress signal to determine both security status and load status.

**Comment by jgkamat** [comment] 2019-01-22 03:08
I think this was fixed in #3427

**Closed by jgkamat** 2019-01-22 03:08 UTC
Labels: component: ui, priority: 2 - low
