### ISSUE TITLE
Toggling between (mobile) useragents causes crash

### ISSUE THREAD

**Issue by rien333** [qutebrowser/qutebrowser#5220] opened 2020-02-04 18:36 UTC
Excuse the lack of logs (my laptop died on an earlier attempt at this issue), but my hope is this issue will be easily reproducible. 

**Version info (see `:version`)**:

```
qutebrowser v1.10.0
Git commit: db05e19ae (2020-02-02 21:44:34 +0100)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

CPython: 3.8.1
PyQt: 5.14.1

sip: 5.1.1
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.1
pygments: 2.5.2
yaml: 5.3
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.4.17-1-clear-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Some websites, like instagram, have functionality they only expose to mobile browsers. Thus, I setup a toggle to easily change my useragent to that of a mobile web browser. This works fine, but when I switch back to the default useragent, qutebrowser crashes. I've known about this issue for some time now (maybe over a year?), but for multiple reasons never bothered to report (fairly annoying, but nothing something I'm confronted with often). Also note that the crash does not occur on all websites. My guess is that the crash only occurs on websites that actually care if you're on a phone (such as instagram).

**How to reproduce**

1. Create the following binding (or change the useragent using `:set`):

``` python
config.bind('<Alt-m>',  "message-info 'Toggling desktop/mobile';; config-cycle content.headers.user_agent 'Mozilla/5.0 (Linux; Android 7.0; SM-G930V Build/NRD90M) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.125 Mobile Safari/537.36'  'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {qt_key}/{qt_version} {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}'")
```
2. Go to instagram.com
3. Toggle the mobile useragent with alt+m (if it worked, you'll see a previously unavailable icon to check your messages)
4. Toggle back to the default useragent
5. If you now reload, qutebrowser will crash silently (except for a SEGFAULT-ish message).

**Comment by The-Compiler** [comment] 2020-02-04 18:39
Duplicate of #4657

**Closed by The-Compiler** 2020-02-04 18:39 UTC
