### ISSUE TITLE
Browser jumps to top of page when exiting search mode

### ISSUE THREAD

**Issue by j-clem** [qutebrowser/qutebrowser#4418] opened 2018-11-08 19:55 UTC
**Version info (see `:version`)**:
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.1
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.25.2
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: Qt5CTProxyStyle
Platform: Linux-4.18.16-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
No

**Description**
Browser selects first element of page when exiting search mode (`/`) via `ESC` or `Enter`, causing a jump to the top
**How to reproduce**
Scroll down a bit on a page, hit `/`, enter some text you see, hit `ESC` or `Enter`, and the browser selects the first page element. Example https://giant.gfycat.com/ConfusedHideousBinturong.webm You can see the link "jump to content" gets selected after I exit search mode. Then I hit `n` to get back to the match.

**Comment by The-Compiler** [comment] 2018-11-08 20:01
I assume you have `statusbar.hide` set to true? If so, see #2236.

**Comment by j-clem** [comment] 2018-11-08 20:08
Yup, exact same bug. When I unhide the status bar, this doesn't happen.

**Comment by The-Compiler** [comment] 2018-11-08 20:09
Duplicate of #2236

**Closed by The-Compiler** 2018-11-08 20:09 UTC
Labels: status: needs triage
