### ISSUE TITLE
Not able to Login to Reddit 

### ISSUE THREAD

**Issue by Drewjz123** [qutebrowser/qutebrowser#5726] opened 2020-09-18 05:15 UTC
I tried to login to reddit but wasn't able to, cross checked the password and username, they seemed pretty accurate. Does it have to do something with the insert mode ? which keeps showing at the bottom of the browser  ?

**Comment by andrewcarlotti** [comment] 2020-09-18 06:38
Insert mode is one of several input modes that determine how Qutebrowser handles keyboard input, and is the main mode used for inserting text in text fields. By default, Qutebrowser will enter and leave input mode automatically when an input field is focussed or unfocussed. The line at the bottom of the window indicates (among other things) what the current input mode is.
I think Reddit show the number of characters you've entered into the password (and username) fields. I'd suggest checking the following things:
1. Do the username and password you're trying to use work in a different browser?
2. Are the input fields showing the correct number of characters when you type in your username and password?
3. If you type your password into the username field, are the correct characters appearing?
4. Does you password contain any unusual characters (i.e. ones that aren't ASCII printable characters)?
5. If it doesn't work in insert mode, then does it work using passthrough mode (press Ctrl-V to enter passthrough mode)?

**Comment by The-Compiler** [comment] 2020-09-18 08:25
No issues here. The questions raised by @andrewcarlotti are great, in addition it'd be good to know the things asked in the issue template:

- Version info (Please copy the first block from :version, not just the qutebrowser version)
- Does the bug happen if you start with `--temp-basedir`?

(There's a reason the template asks for those :wink:)

**Comment by Drewjz123** [comment] 2020-09-18 08:37
Yeah the username and password work in other browsers and the browser even crashes while trying to login to Gmail. 

Yes I have copied and pasted the credentials aswell to check for the same but didn't work.

**Comment by Drewjz123** [comment] 2020-09-18 08:39
14:08:40 WARNING: QSocketNotifier: Can only be used with threads started with QThread
qutebrowser v1.10.1
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

CPython: 3.8.5
PyQt: 5.14.2

sip: 4.19.21
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.4.2
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1g FIPS  21 Apr 2020

Style: Adwaita::Style
Platform: Linux-5.8.4-200.fc32.x86_64-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Fedora 32 (Workstation Edition) (fedora)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/dhruv/.cache/qutebrowser
config: /home/dhruv/.config/qutebrowser
data: /home/dhruv/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00

**Comment by The-Compiler** [comment] 2020-09-18 08:40
What about all those other questions? Not much we can do about this without more information, given that it only seems to be happening to you.

**Comment by Drewjz123** [comment] 2020-09-18 08:52
Does the bug happen if you start with --temp-basedir?

Yes it does happen when I start with this

**Comment by The-Compiler** [comment] 2020-09-18 08:55
2-5 from @andrewcarlotti above are still missing... Keep in mind we're sending notification emails to ~180 people with every message here, so it'd be great if we wouldn't need so many unnecessary round-trips.

**Comment by Drewjz123** [comment] 2020-09-18 09:03
> 2-5 from @andrewcarlotti above are still missing... Keep in mind we're sending notification emails to ~180 people with every message here, so it'd be great if we wouldn't need so many unnecessary round-

**Comment by Drewjz123** [comment] 2020-09-18 09:07
> 2-5 from @andrewcarlotti above are still missing... Keep in mind we're sending notification emails to ~180 people with every message here, so it'd be great if we wouldn't need so many unnecessary round-trips.

Somehow the issue got closed but please look into it and let me know what to do ! Sorry for the inconviences caused regarding the emails

**Comment by The-Compiler** [comment] 2020-09-18 09:16
Ah, I can actually reproduce this when I try with the older Qt 5.14 you're using, it works fine with Qt 5.15.

That's pretty weird... Browsing around /r/help it seems like some people have similar issues, especially with alternative/mobile browsers:

- [ok so i cant log into my reddit account that im the password and email to for anything and everytime i try and change my password it says changed but when i try it it says wrong password pleaseee help i stay on reddit 24/7all day and i really dont wanna lose my account : help](https://www.reddit.com/r/help/comments/ii0pj6/ok_so_i_cant_log_into_my_reddit_account_that_im/)
- [Can't log into browser : help](https://www.reddit.com/r/help/comments/ii11f2/cant_log_into_browser/)
- [Can't log in on mobile. "Wrong password" : help](https://www.reddit.com/r/help/comments/ij3li8/cant_log_in_on_mobile_wrong_password/)
- [Can't login to reddit using steam overlay browser : help](https://www.reddit.com/r/help/comments/ipddil/cant_login_to_reddit_using_steam_overlay_browser/)
- [Login problem : help](https://www.reddit.com/r/help/comments/ihz0a0/login_problem/)
- [Account login limit? : help](https://www.reddit.com/r/help/comments/igtg2t/account_login_limit/)
- [Cannot login on desktop : help](https://www.reddit.com/r/help/comments/hzqnrp/cannot_login_on_desktop/)

etc. etc...

The server does indeed answer:

```json
{reason: "WRONG_PASSWORD", code: 400, explanation: "wrong password"}
```

but the request looks like the same, so I have no idea what's happening. Spoofing the user agent won't change anything either... I doubt there's much qutebrowser can do about this, but I'd still like to dig in a little bit more before closing this.

---

That all being said, as a workaround it seems to be possible to log in on old.reddit.com instead...

**Comment by Drewjz123** [comment] 2020-09-18 09:21
Okay thanks a lot for your support !

**Comment by Drewjz123** [comment] 2020-09-18 13:16
I tried logging in on Gmail, but now the browser keeps crashing and I am not able to do anything on it, seems weird ! I tried --temp-basedir but doesn't work there too, Is there someway I can update the qt engine to 5.15 so that I no longer face the issues. I also tried reinstalling it multiple times but the same issue persists.

**Comment by The-Compiler** [comment] 2020-09-18 13:25
Can you please open a new issue about the crash on Gmail, including terminal output (if any) and whether you can reproduce it with `--temp-basedir`? It's most likely unrelated to the Reddit issue.

**Comment by The-Compiler** [comment] 2023-03-23 21:07
Qt 5.14 support is dropped now.

**Closed by The-Compiler** 2023-03-23 21:07 UTC
Labels: priority: 1 - middle, component: QtWebEngine, bug: behavior, qt: 5.14
