### ISSUE TITLE
gearbest

### ISSUE THREAD

**Issue by zwykl3** [qutebrowser/qutebrowser#4773] opened 2019-05-11 15:28 UTC
I can 'click' x on top adv
when i would like to change currency i cant change usd because f not appear

**Comment by jgkamat** [comment] 2019-05-11 15:36
Seems like a duplicate of #178. That looks like a div with a click element,
which is hard to get hinting for.

**Comment by The-Compiler** [comment] 2019-05-11 16:08
Probably what @jgkamat says.

@zwykl3 In general, please show us what the issue is, rather than making us guess. Including a link to the page or maybe a screenshot makes a big difference.

**Closed by The-Compiler** 2019-05-11 16:08 UTC

**Comment by zwykl3** [comment] 2019-05-12 07:01
when open web page
*f next da and nothing more
esc f not show
second trouble i see link bottom than change currency menu.
![Zrzut ekranu 2019-05-12 o 08 58 49](https://user-images.githubusercontent.com/50232890/57578892-7ea16900-7494-11e9-94fa-7847ad7a5c93.png)
