### ISSUE TITLE
show running as qutebrowser and not python3 within netstat and htop etc.

### ISSUE THREAD

**Issue by RadicalEd360** [qutebrowser/qutebrowser#4666] opened 2019-03-22 02:21 UTC
Which of the following lines of output are not qutebrowser?
`netstat -antp`
https://imgur.com/Jz67sKA

hint: all the python3 lines were one qutebrowser process

tips or tricks welcome please and thank you!

**Comment by jgkamat** [comment] 2019-03-22 02:32
Radical Edward writes:
> show running as qutebrowser and not python3 within netstat and htop etc. (#4666)

I don't think we can do this in a portable way

> Which of the following lines of output are not qutebrowser?
> netstat -antp
> https://imgur.com/Jz67sKA
>
> hint: all the python3 lines were one qutebrowser process

I don't think this is true, as some of the python3 lines have a different pid
(11338 vs 27375). It could be a different qutebrowser instance though.

Also, here's the direct version of the image for those who can't load js:
https://i.imgur.com/Jz67sKA.png

**Comment by The-Compiler** [comment] 2019-03-22 06:06
Duplicate of #2099

**Closed by The-Compiler** 2019-03-22 06:06 UTC
