### ISSUE TITLE
Blocks of pixels from other places drawn in website.

### ISSUE THREAD

**Issue by magnetophon** [qutebrowser/qutebrowser#6920] opened 2021-12-30 09:51 UTC
**Version info**:

qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.3

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
A lot of times, qutebrowser draws blocks of pixels from another place, either another tab, or a different place of the same tab, or even tabs that where closed minutes ago.
Example:
![image](https://user-images.githubusercontent.com/7645711/147739470-5353d313-92b7-4d25-a531-9d95e040f4ad.png)
When I switch away from the tab with the error and then back to it, the error is usually gone.

**How to reproduce**

This happens on any site, I haven't found out how to avoid or reproduce it.

**Comment by mschilli87** [comment] 2021-12-30 10:18
What operating system is this on? If Linux, are you using X11 or Wayland?

**Comment by magnetophon** [comment] 2021-12-30 10:27
It's on NixOS linux, using X11.

**Comment by mschilli87** [comment] 2021-12-30 10:30
Since this is a graphical issue, some information about your graphics chip and driver could probably be useful as well.
Also, can you reproduce this in another qtwebengine-based brower? My hunch is that this is an upstream issue that can't really be fixed in qutebrowser itself.

**Comment by The-Compiler** [comment] 2021-12-30 10:31
Duplicate of #6879

**Closed** 2021-12-30 10:32 UTC

**Comment by magnetophon** [comment] 2021-12-30 10:41
I searched the issue tracker for similar issues, but didn't find any.
Didn't search well enough apparently.
Sorry for the noise!
