### ISSUE TITLE
Context menu pops up while "grp:menu_toggle" us set

### ISSUE THREAD

**Issue by cacud** [qutebrowser/qutebrowser#5720] opened 2020-09-15 12:17 UTC
**Version info**:
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

**Does the bug happen if you start with `--temp-basedir`?**:
It does

**Description**
I use Sway as my display manager and I type two languages. For me, the most comfortable key for switchitg keyboard layouts is Menu key, so I have `"grp:menu_toggle"` as one of the `xkb_options` in my Sway config file. With this option enabled, qutebrowser is the only program to keep popping up context menu so I consider this a bug.

**How to reproduce**
With block of text below in Sway config file and qutebrowser active, being in any mode other than command mode, press the Menu button.

```
input * {
	xkb_layout "us, ru"
	xkb_variant ","
	xkb_options "grp:menu_toggle" 
}
```

**Comment by The-Compiler** [comment] 2020-09-15 12:19
Can you try with another Qt(WebEngine) application such as KDE Falkon?

**Comment by cacud** [comment] 2020-09-15 12:36
Just tried with Falkon, and the behavior is the same

**Comment by The-Compiler** [comment] 2020-09-15 12:37
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine) (or perhaps Chromium, if you can reproduce it there as well).

I try to report bugs upstream when I can reproduce them, but unfortunately I can't easily reproduce this as a lack a keyboard with a menu key. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2020-09-15 12:37 UTC
Labels: status: needs triage

**Comment by cacud** [comment] 2020-09-15 14:59
Thanks for response!
I reported this bug at Qt: https://bugreports.qt.io/browse/QTBUG-86672
