### ISSUE TITLE
Tab-give - Reuse same "page instance" instead of reloading the page

### ISSUE THREAD

**Issue by edi9999** [qutebrowser/qutebrowser#5335] opened 2020-04-07 07:51 UTC
I use `T` mapped to `:tab-give` (without arguments) a few times a day, most of the time, it is because I want to put that qutebrowser on an other screen.

Whenever I do so, I have found out that this `:tab-give` will not reuse exactly the same page instance, but instead, it seems to me reload the page from the beginning.

Since I do this on pages that usually are slow to load, this is a bit annoying. The other 2 browsers I use (firefox and Chrome), when you drag and drop a tab outside the window (which is similar to `:tab-give` as far as I can tell), they will not do a page reload, but instead will reuse your current tab with the loaded data.

I think it would make sense that this is the default behavior, and maybe (if people have a use for it) add a flag to use the reload behavior, maybe with `:tab-give --reload` or `:tab-give --refresh`

What do you think ?

**Comment by The-Compiler** [comment] 2020-04-07 08:00
Duplicate of #2636

**Closed by The-Compiler** 2020-04-07 08:00 UTC
