### ISSUE TITLE
Split window into two / tab-give for multiple tabs

### ISSUE THREAD

**Issue by IjhUDWzf** [qutebrowser/qutebrowser#5331] opened 2020-04-05 11:28 UTC
I am missing a convenient way how to put multiple tabs to a new window at once. Oftentimes I start searching for something intensively and before I realize it would be better to have a separate window for it there is a dozen of tabs to move. The only way to move tabs to a specific window I am aware of is to `:tab-give #` which is not convenient for many tabs to do each at a time. It seems that the shortcut `gD` is not working for a specific window (`#gD` not working as expected).

I would consider the possibility to select multiple tabs and then use `:tab-give #` the best option to resolve this issue.

Thank you for this awesome browser.

**Comment by The-Compiler** [comment] 2020-04-05 11:29
Duplicate of #2913

**Closed by The-Compiler** 2020-04-05 11:29 UTC
