### ISSUE TITLE
Add a way to right click elements with hint

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [qutebrowser/qutebrowser#7247] opened 2022-06-15 04:50 UTC
As far as I can find, there is no way to right click elements with hint. This is necessary for some websites which have custom context menu items that are vital shortcuts for some of their functionality which would take significantly longer to use otherwise, or is entirely impossible to access without the custom context menu.

I tried to look up features like this but I only found out about the ; commands, which aren't a perfect replacement for this feature.

**Comment by The-Compiler** [comment] 2022-06-15 07:00
Duplicate of #521

**Closed by The-Compiler** 2022-06-15 07:00 UTC

**Comment by Lilith-In-Starlight** [comment] 2022-07-21 00:32
Huh! That's interesting! Is there a double click equivalent? Or can that be set up by the user?

Also interacting with the context menu using hints doesn't seem possible, unless this is also a thing that is possible already and I just don't know.
