### ISSUE TITLE
Press shift to open link in a new tab

### ISSUE THREAD

**Issue by mstruebing** [qutebrowser/qutebrowser#3846] opened 2018-04-16 18:03 UTC
It would be great if pressing shift while in link-hinting-mode would be able to open the link in a new tab.
That way it is possible to decide later on if link should be opened in current or new tab.

Wanted behaviour:
1. press f
2. press shift + link hint char (if more than one press them first and press shift before the last one :))
3. link opens in a new tab

Actual behaviour:
1. press f
2. pressing shift  now exits the 'link-hinting-mode'

**Comment by The-Compiler** [comment] 2018-04-16 18:04
Duplicate of #577

**Closed by The-Compiler** 2018-04-16 18:04 UTC
