### ISSUE TITLE
Why it is not possible to display embedded pdf data

### ISSUE THREAD

**Issue by ridoo** [qutebrowser/qutebrowser#5212] opened 2020-01-29 10:40 UTC
I am using [tiddlywiki](https://tiddlywiki.com/) as a daily journal. From time to time I'd like to import a PDF file which is being embedded in a so called tiddler. Technically, this results into something like this:

```
<div class="tc-tiddler-body tc-reveal">
  <embed src="data:application/pdf;base64,JVBERi0xLjUKJcOkw7z...">
</div>
```

However, Chrome displays the embedded PDF, but qutebrowser does not.

Here are the files, I tested with:

* [test.pdf](https://github.com/qutebrowser/qutebrowser/files/4127473/test.pdf)
* [test.html with embeded pdf](https://github.com/qutebrowser/qutebrowser/files/4127472/test.html.txt)  (Note: GitHub did not allow for `html` files, therefore the `.html.txt` extension)

**Version info (see `:version`)**:
```
qutebrowser v1.9.0
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.0

CPython: 3.8.1
PyQt: 5.14.1

sip: 5.1.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.10.3
pygments: 2.5.2
yaml: 5.3
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.3.200 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.4.15-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/ridoo/.cache/qutebrowser
config: /home/ridoo/.config/qutebrowser
data: /home/ridoo/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 18:50:49
```

**Comment by user202729** [comment] 2020-01-30 09:08
Possible duplicate of [PDFium support · Issue #4911 · qutebrowser/qutebrowser](https://github.com/qutebrowser/qutebrowser/issues/4911)

**Comment by The-Compiler** [comment] 2020-01-30 09:14
That, and also: [[QTBUG-80325] When a PDF is embedded via the <object> tag in a HTML page it will end up showing the whole PDF instead - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-80325)

**Closed by The-Compiler** 2020-01-30 09:14 UTC
