### ISSUE TITLE
Crashed error page leads to larger error page

### ISSUE THREAD

**Issue by psvenk** [qutebrowser/qutebrowser#7146] opened 2022-04-28 04:22 UTC
When a page crashes (in my experience, when the system is out of memory and the renderer process is killed), it is replaced with an error page, whose contents are loaded from a `data:` URI. However, if the out-of-memory issue persists, sometimes the error page will itself crash, leading to another error page where the `href` of the "Try again" link includes the entire `data:` URI of the previous page, which can be quite long.

When this happens several times, the memory problem is worsened and recovering each affected tab requires clicking "Try again" multiple times to unwind the stack of error pages embedded within each other.

One solution to this is to avoid rewriting `data:` URIs upon a crash; because any such page has its entire source code in the address bar, memory savings (as far as I understand) are not too significant from unloading the live webpage. Furthermore, these tend to be simple pages, so it is generally not worth it to unload them.

**Comment by The-Compiler** [comment] 2022-04-28 09:02
Duplicate of #3918 and #5108.

**Closed by The-Compiler** 2022-04-28 09:02 UTC
