### ISSUE TITLE
Noscript like icon support

### ISSUE THREAD

**Issue by casualuser1998** [qutebrowser/qutebrowser#7445] opened 2022-10-22 06:21 UTC
It is pretty confusing to know the status of javascript enabled. Perhaps an icon on the statusbar to show whether 
1. js enabled/disabled 
2. images enabled/disabled
3. scripts enabled/disabled 
would be useful.

**Comment by The-Compiler** [comment] 2022-10-22 08:06
Duplicate of #1052

**Closed by The-Compiler** 2022-10-22 08:06 UTC
