### ISSUE TITLE
Add rl-backward-delete-char as an instert mode command

### ISSUE THREAD

**Issue by alejandrogallo** [qutebrowser/qutebrowser#3415] opened 2017-12-18 21:24 UTC
I tried to add the following line into the `[insert]` section of my keys config file

```
rl-backward-delete-char
    <ctrl-h>
```

but qutebrowser tells me that this command is only vald for the prompt mode and not for insert mode.
I am very used to typing `ctrl h` as backspace as in vim, and I would like to do it in qutebrowser too.

Thanks for the project!

**Comment by The-Compiler** [comment] 2017-12-18 21:25
Duplicate of #68

**Closed by The-Compiler** 2017-12-18 21:25 UTC

**Comment by alejandrogallo** [comment] 2017-12-18 21:29
awesome, thanks!

**Comment by pkillnine** [comment] 2017-12-18 21:50
Just to note: It looks like you're using an old version of qutebrowser, from version 1.0 onwards it no longer uses `keys.conf`.

**Comment by alejandrogallo** [comment] 2017-12-18 21:55
Oh, thanks, good to know, I'll update it then!
