### ISSUE TITLE
qutebrowser error page makes modifying or yanking the current url difficult.

### ISSUE THREAD

**Issue by Phantop** [qutebrowser/qutebrowser#7043] opened 2022-02-26 20:37 UTC
As the title says, whenever one of the built-in error pages show up, the url is changed to something impossible to edit and very long, making yanking useless, requiring extra steps to modify the inteded url to try to remedy the issue, and taking up a lot of space on the status bar and making it harder to input anything in command mode. This doesn't occur with QtWebEngine's built in error pages, so I wonder why qutebrowser does this?

**Comment by toofar** [comment] 2022-02-26 20:57
Duplicate of https://github.com/qutebrowser/qutebrowser/issues/3918
Note that you should be able to navigate back just fine.

**Closed by toofar** 2022-02-26 20:57 UTC
