### ISSUE TITLE
Tabs Tree Grouping

### ISSUE THREAD

**Issue by Yodzorah** [qutebrowser/qutebrowser#3943] opened 2018-05-23 14:49 UTC
Would be nice to have an ability to group tabs, but not just like Opera or Vivaldi did. New tab is always a new 'branch' of a thought and it can't be properly handled with simple grouping.

## How it should work

For example, you have three grouped tabs. You were doing something on `Tab_3`, then you got an idea of `Something_Nice_You_Could_Do` and then you go to new `Tab_4`. When you understand you need more tabs for doing what you were doing on `Tab_4`, you create `Tab_5` and `Tab_6`. In the example `Tab_4`, `Tab_5` and `Tab_6` are members of one logical group - `Something_Nice_You_Could_Do`. But `Tab_4` is also a bridge to `Tab_3` and your thoughts and doings on this tab. So, your tabs should look like this now:
```
[Tab_1] (Initial_Task group)
[Tab_2]
[Tab_3]-->[Tab_4] (Something_Nice_You_Could_Do group)
..........[Tab_5]
..........[Tab_6]
```
`Something_Nice_You_Could_Do` group is not a subgroup of `Initial_Task` group, though it is connected to it via `Tab_3->Tab_4` associative bond. While you were doing something on `Tab_5`, you got another three ideas: the first is a subtask for `Something_Nice_You_Could_Do` that, you've realized while you were on `Tab_5`, needs more tabs to be properly done, the second is a `Belated_Idea` about something you saw on `Tab_2` and the third is a completely new branch of thought about your `IRL_Needs` you suddenly remembered you need to care about. You do this:
```
[Tab_1] (Initial_Task group)
[Tab_2]-->[Tab_9] (Belated_Idea group)
..........[Tab_10]
..........[Tab_11]
..........[Tab_12]
[Tab_3]-->[Tab_4] (Something_Nice_You_Could_Do group)
.........+[Tab_5] {subgroup}
.............[Tab_7] (Do_Subtask_Properly group)
.............[Tab_8]
..........[Tab_6]
[Tab_13] (IRL_Needs group)
[Tab_14]
```
Here you have one subgroup/subtask for `Something_Nice_You_Could_Do`. Parent of a subgroup is always its bond to parent group. At the same time you have parallel groups (not subgroups!) related via the same associative bond. So, you have your "thoughts tree", which helps you to navigate through your connected ideas and subideas without a need to remember your logic's path. In fact, you will never have just tabs - all your tabs are members of some tasks/groups, and if you open a non-related and non-grouped tab somewhere, it's always a new group with a single tab in it and it's a new global branch of tree (like `Tab_13`). Each tab is a member of a group, each group is a task, each task can have subtasks (subgroups), each subtask can have its own subtasks (because that is how logic of subtasks works, you shouldn't have restrictions on tasks nesting) and each task/group has its past (bond to a member of another task/group) or it is a new global branch of the tree, each tab can be nested/bonded to one or few groups, parent tabs (containing subgroups) can be bonded to groups as well as usual tabs.

## How the hell user should create such a tree? Is it even possible to create a tab bar for this?

It's really not that complicated, just... big. Basically, this needs:

1. A few commands/keybindings, for example, to open new tab in new group with bond to the current tab or to open new subgroup of the current group with bond to current tab; we can numerate groups the same way as tabs and manage any of them with `g12`-like keybindings; actually, we need to create commands/keybindings for:
  * Tabs creating(&cloning)/moving/switching. Since a tab is always a member of a group, tabs' global actions are actions for doing something with tabs with some grouping/bonding options, like the keybindings I've mentioned above. All tabs' actions are either local (create/move/switch/close a tab within the current group) and can be managed with the already existing keybindings or global (create a tab in a new bonded/nested group; move tab to the last position of another existing group (last position matters - it means the moved tab continues the inner chain of thoughs within its new group); move tab to a new group with bond to the previous tab of the current group (bond to the previous tab matters for the same reason); switch to the last tab of another group). So, the current tab management is the same for managing tabs of one (current) group, we just need a few commands/keybindings for global management part. If user doesn't need the whole tab grouping thing, there won't be any difference for him, because he will work with his tabs within a single initial group.
  * Groups closing/parent changing/bond changing/pining. Close a group and all its tabs & undo this with dependencies (parent/bond) restoring. Pining a group means you pin not its tabs but the task you need to do. So, if all tabs of a pinned group were closed, the group still exists and it does what user says via "what to do when the last tab is closed" option. As you can still pin tabs within groups, pining a tab means "I need the tab and its info to accomplish my task" and pining a group means "I need to accomplish the task". Since the common logic of new tasks/groups is "first tab of a new group is a historical start of a new task", we need an ability to choose another tab to bond it to the first tab of a group, but we don't need to choose any other than first tab of the group to bond external tabs to.

2. Full-width/-height scrollable and zoomable tabs panel with the whole tree displayed, that can be opened/closed with a command/keybinding; it's not like I'm suggesting to extend the usual tab bar to the extent of a huge page - i'm suggesting to leave the usual tab bar almost unchanged and add a proper map of web surfing.

3. New algorithm of tabs and groups creating/moving as a replacement for the "where to create new tabs" option. Usual tab bar will still display all tabs (not like Vivaldi grouping, when all grouped tabs are united in one tab-like item in the tab bar), but, for example, as far as we have groups we need to autodisplay all tabs of a parallel group after all tabs of previous group and at the same time we need to display all tabs of a nested group next to the parent tab (inside the parent group).

4. Some visual changes for usual tab bar to designate bounds of groups, to show pinned status of some groups and, __maybe__, some additional keybindings for highlighting bonds of selected tab for quick access.

## Unneeded/unneccessarily complicated

All my suggestions are just my assumings of best ways, but we can find another solutions, can't we? I know, it looks big and crazy, but, actually, the feature is what all people stuck with large amount of tabs have been searching for. Tabs grouping feature in some browsers doesn't solve the problem, because the problem is not in inability to classify and group your tabs in the web surfing process but in insufficiency of human memory to remember the whole logic's path behind your tabs management, that makes classifying and grouping process so uncomfortable. Also, there is 'Tree Style Tabs' extension (Firefox, doesn't work for Quantum), that tries to solve the problem properly, but it doesn't really support the way we're thinking when we're creating so much tabs, and instead of making it difficult for us to remember our logic's path like a simple grouping feature does, it forces us to use only one way of thinking, it allows only formal creating of logic's history and doesn't serve as a tool for tabs management __centering on user's way of separating and nesting tasks__. So, basically, the whole idea is to create a proper 'Tree Style Tabs' with ability to group tabs. For the moment there is no tabs grouping/stacking/tree feature somewhere that actually does its job of simplifying tabs management and because of that multitabable people all over the world can never be at home in their browsers.

**Comment by The-Compiler** [comment] 2018-05-23 15:21
Duplicate of #927

**Closed by The-Compiler** 2018-05-23 15:21 UTC
