### ISSUE TITLE
Mouse problem on osx

### ISSUE THREAD

**Issue by piotryordanov** [qutebrowser/qutebrowser#2718] opened 2017-06-13 19:34 UTC
1. I don't know what happened, but now, the mouse scroll is invested and it is super slow. I have to slide too much on my trackpad for it to even more an inch.
2. Also, hovering over links with my mouse doesn't change the mouse cursor to a pointer.
3. `cmd+leftArrow` doesn't take me to start of line in insert mode, neither does `cmd+rightArrow` take me to end of line in insert mode. How can I enable that?

I'm on a mac. Thanks for the help :)

**Comment by The-Compiler** [comment] 2017-06-13 20:38
1) is a [Qt bug](https://bugreports.qt.io/browse/QTBUG-58779) and was fixed in Qt 5.9, which will come with the next qutebrowser release (as soon as PyQt 5.7.1 is released) - see [this mail](https://lists.schokokeks.org/pipermail/qutebrowser-announce/2017-June/000017.html) for details.

2) Smells like a bug with QtWebEngine - can you please check whether you can reproduce it using [QupZilla](https://qupzilla.com/) (another browser based on QtWebEngine)?

As for 3), can you please test whether that works with QupZilla as well? It might be something qutebrowser does wrong, or it might be a QtWebEngine issue - not sure there.

**Comment by piotryordanov** [comment] 2017-06-13 20:40
I'll give QupZilla a try. In the meantime, I did a build from source (using the documentation on the site) and the py executable I got works without the bug. I'm assuming it is the more recent version.

However, the py script is kinda useless for me because it's not a `.app` :(

**Comment by The-Compiler** [comment] 2017-06-13 20:44
With "the bug" you mean the one at 1)? If you have `tox` installed, you should be able to run `python3 scripts/dev/build_release.py` to get an `.app`, though I never tested that script on another machine than mine. As said, there'll be a new `.app` in the next few weeks, I just don't have the time to install things from source on Windows and macOS to build the releases.

(Also, in the future please open separate issues for separate things - makes things easier :wink:)

**Comment by piotryordanov** [comment] 2017-06-13 20:46
Yes, i was referring to 1)

I'd be happy to help with the `.app` version on my machine to make room for more tests. Let me know what the steps are!

**Comment by The-Compiler** [comment] 2017-06-14 08:41
I'm not sure I understand what you mean properly - if you have qutebrowser running from source, you should be able to install `tox` (e.g. via homebrew maybe, or `pip install tox` - I wouldn't use `sudo pip install` though) and then run the `build_release.py` script as per my comment above.

On the other hand, to test those things you shouldn't need an `.app`, anyways, no? :wink:

**Comment by piotryordanov** [comment] 2017-06-19 11:48
- So, I don't face the mouse problem if I use the `cask` version of `qutebrowser`.
If I use the `dmg` provided in the [0.10.1]( brew cask install qutebrowser) release, then i still face the problem.

- How can I run `tox` on the brew version?

- As for the keyboard problem, I have it also on `QupZilla`, but I'll open a new issue for it ;)

**Comment by The-Compiler** [comment] 2017-06-19 12:00
Hmm, that's odd - because [all cask does](https://github.com/caskroom/homebrew-cask/blob/master/Casks/qutebrowser.rb) is installing that dmg.

As for running tox, it depends on how you installed it, and what Homebrew does - I can't really help you there I'm afraid.

I'm closing this, as I think all that's remaining is #2740 now - for the others, I suggest you just wait a week or two until I can push a release based on Qt 5.9 :wink:

**Closed by The-Compiler** 2017-06-19 12:00 UTC
Labels: needs triage

**Comment by piotryordanov** [comment] 2017-06-19 13:42
No wait, the cask version still has the bug. The version i have is the one I installed using

```
$ brew install qt5 --with-qtwebkit
$ brew install -s pyqt5
$ pip3 install qutebrowser
```

This one doesn't have mouse problems even though both are version `0.10.1`!

**Comment by The-Compiler** [comment] 2017-06-19 13:44
Yes, because it's a bug in Qt and not qutebrowser - you get Qt 5.9, and the dmg ships with Qt 5.8.

**Comment by piotryordanov** [comment] 2017-06-19 13:48
Wait, so I'm confused. So `cask` ships QT 5.8?

But i guess, all I have to do now is run `qutebrowser` from term and wait for the next release in a couple of weeks which would be fine by me. The dmg doesn't really make qutebrowser the default browser anwy, and to run stuff, I can let alfred run the script.

**Comment by piotryordanov** [comment] 2017-06-19 17:30
Alright, thx mate :)

**Comment by The-Compiler** [comment] 2017-07-05 10:18
@piotryordanov @javell @rezashamdani v0.11.0 is now out with Qt 5.9, so this should be fixed.

**Comment by piotryordanov** [comment] 2017-07-07 16:24
@The-Compiler is it also available on `pip` ? 
if so, how do I upgrade on pip? Couldn't find instruction manual on the website.

(Also, note that the mac version is for me useless as long as mac doesn't recognize the app as a default browser :( )

**Comment by The-Compiler** [comment] 2017-07-07 16:32
qutebrowser is on pip, but only the source release. You can update via `pip install -U qutebrowser`, see the [pip documentation](https://packaging.python.org/tutorials/installing-packages/#upgrading-packages).
