### ISSUE TITLE
Single URL argument will attempt to open two URLs, the right one, and a `file://` one

### ISSUE THREAD

**Issue by arija-ari** [qutebrowser/qutebrowser#8430] opened 2024-12-19 13:52 UTC
**Version info**:
https://bpa.st/2H6A

qutebrowser v3.4.0
Backend: QtWebEngine 6.8.1
  based on Chromium 122.0.6261.171
  with security patches up to 131.0.6778.70 (plus any distribution patches)
  (source: api)
Qt: 6.8.1

**Does the bug happen if you start with `--temp-basedir`?**:
It's a fresh install

**Description**
`qutebrowser https://google.com` results in:

<img width="814" alt="Screenshot 2024-12-19 at 14 43 25" src="https://github.com/user-attachments/assets/2a5a486d-c0b4-40c7-a5ff-db8e925e848c" />

**How to reproduce**
On MacOS:

```
brew install qutebrowser
qutebrowser https://google.com
```

**Comment by The-Compiler** [comment] 2024-12-19 20:41
Duplicate of #3719

**Closed by The-Compiler** 2024-12-19 20:41 UTC
