### ISSUE TITLE
Heavy graphical glitches on macOS 

### ISSUE THREAD

**Issue by rien333** [qutebrowser/qutebrowser#3901] opened 2018-05-08 01:40 UTC
I downloaded the 1.3.0 .dmg file from the "releases" tab today, but unfortunately practically any page shows black boxes all over (see images below for some examples). When scrolling or interacting with those regions, they'll sometimes flicker, dissapear, or take over even more of the webpage. Earlier, I had a problem with the default background color sometimes not being applied properly, and instead defaulting to black, which could be a related problem. (this is much much worse however, making some more complicated websites as facebook unusable). It might be a local thing, so if anyone else could see if they encounter this that would be great. I'm running macOS 10.13.4. 

Some examples:

![schermafbeelding 2018-05-08 om 03 30 56](https://user-images.githubusercontent.com/10417027/39733076-23d3b546-5271-11e8-85f2-0f0f98eb3673.jpg)

Espcially a lot of textfields have this problem: 
![schermafbeelding 2018-05-08 om 03 31 22](https://user-images.githubusercontent.com/10417027/39733099-47468954-5271-11e8-8bf3-e43088bdb448.jpg)

Google also does not show up correctly (the background of the recommendations bar is supposed to be white):
![schermafbeelding 2018-05-08 om 03 31 38](https://user-images.githubusercontent.com/10417027/39733108-551ec9c4-5271-11e8-915a-ab6e43823b0a.jpg)

**Comment by jgkamat** [comment] 2018-05-08 01:48
Does the previous mac os releases have this issue? @The-Compiler tried to change the buid environment to support older versions of mac os, which might have triggered this, although that seems quite odd.

**Comment by rien333** [comment] 2018-05-08 01:53
Nope, I was running a version from a commit somewhere between 1.2.1 and 1.3.0 before, and the problem was definitely not present in any form. I could have a look which specific commit it was specifically.

**Comment by jgkamat** [comment] 2018-05-08 02:02
If you can run development versions, could you try doing a `git bisect` to find which commit introduced the issue for you? I think it might be 6640768860ea5cd4a7c6e47dd0534baf2bdf1c49, but it would be helpful to be sure. I have no idea how that workaround works, so I can't comment too much on it.

**Comment by rien333** [comment] 2018-05-08 02:12
I might try tommorow as I'm heading to bed now, but the build process is kinda a pain tbh. `$ python3 scripts/dev/build_release.py` should just build everything in one go, but it fails at a few points and so requires some manual editing  (at least this was the case a while back). Any tips on building are welcome, but I can do without them.

**Comment by jgkamat** [comment] 2018-05-08 02:14
You should be able to run development versions by running:

`python3 -m qutebrowser` 

at the root of the repo, assuming you have dependencies set up systemwide. It dosen't do stuff like building help topics, but that dosen't matter in most dev cases :)

**Comment by The-Compiler** [comment] 2018-05-08 02:33
What Qt version were you using before?

**Comment by The-Compiler** [comment] 2018-05-08 04:35
I first thought this would be [QTBUG-66346](https://bugreports.qt.io/browse/QTBUG-66346), but apparently that's Linux-only. Still, this seems like some kind of issue which is more likely to be caused by Qt than by qutebrowser itself.

**Comment by rien333** [comment] 2018-05-08 08:31
> What Qt version were you using before?

I always build qutebrowser with tox, so I am not sure if that uses my local QT install. Regardless, I've been on the same QT version (5.10.1) for a few versions now, without encountering this problem.

**Comment by The-Compiler** [comment] 2018-05-08 08:56
Can you also try with [QupZilla](https://qupzilla.com/download#mac) please?

**Comment by rien333** [comment] 2018-05-08 10:07
Hm yeah QupZilla seems to have the excact same issue. Interesting.

**Comment by toofar** [comment] 2018-05-08 10:14
`:set qt.force_software_rendering true` might help if you have a decent CPU.

**Comment by The-Compiler** [comment] 2018-05-08 10:49
This does sound more and more like Qt isn't able to find some resources, i.e. something like [QTBUG-66346](https://bugreports.qt.io/browse/QTBUG-66346). There's also [QTBUG-67040](https://bugreports.qt.io/browse/QTBUG-67040) which is tracking something similar to this.

My hope would be it's resolved with Qt 5.11, which should be released end of May - I'll do a patch release once that and PyQt 5.11 are out.

Until then, unfortunately I don't think there's anything I can do here.

**Closed by The-Compiler** 2018-05-08 10:49 UTC
Labels: bug: behavior, os: macOS, priority: 2 - low, qt

**Comment by schemar** [comment] 2018-05-11 17:01
Just wanted to chime in and note that I see the same behaviour with a new `brew cask install qutebrowser` on a fresh mac. Which version/commit should I install to have the latest usable version?

**Comment by The-Compiler** [comment] 2018-05-11 20:48
If you're running from the repository (rather than the prebuilt release), you should be able to run the latest commit (or the v1.3.0 release), but make sure to use Qt 5.10.0, 5.9.5 or 5.11.0 (not released yet).

As for the prebuilt releases, I'm not sure what the last one with Qt 5.10.0 was. However, I built the v1.3.0 release against Qt 5.10 - @schemar @rien333 can you please try this? [qutebrowser-1.3.0-qt510-elcap.dmg](https://qutebrowser.org/tmp/qutebrowser-1.3.0-qt510-elcap.dmg)

**Comment by schemar** [comment] 2018-05-14 07:58
Same problem for me, too

**Comment by The-Compiler** [comment] 2018-05-14 08:09
I still have no clue what's going on there unfortunately, and have been unable to reproduce this on three systems. You can install Qt separately from qutebrowser, but then you can't use the `.app` which has some drawbacks.

Still hoping things will look better once Qt 5.11 is released...

**Comment by schemar** [comment] 2018-05-14 09:57
If anyone is interested: the [v1.1.1 release](https://github.com/qutebrowser/qutebrowser/releases/tag/v1.1.1) is the latest `.dmg` that works. 
Cannot use the same `config.py` unfortunately.

**Comment by rien333** [comment] 2018-05-14 10:31
@schemar  like mentioned in this thread already, I think you pretty much have to pull this repo, and then only `python3 -m qutebrowser` in the folder (given that you have all the dependencies) to get a newer version to work. At least that works for me.

**Comment by c0llision** [comment] 2018-05-23 16:26
I had this issue when I installed with:

`brew cask install qutebrowser`

It goes away when I do this:

`pip3 install qutebrowser
python3 -m qutebrowser`

**Comment by schemar** [comment] 2018-07-04 19:15
Fixed in the 1.4 release! 👍
