### ISSUE TITLE
The new tab and dialogue opened by UPS' "print label" button usually close instantaneously

### ISSUE THREAD

**Issue by andrewcarlotti** [qutebrowser/qutebrowser#5622] opened 2020-07-24 21:48 UTC
**Version info**:
Running latest master (also reproduced on master from a few weeks ago with my own history entry changes included):
":version" gives:
```
qutebrowser v1.13.1
Git commit: cee5d0b0d on HEAD (2020-07-23 19:19:52 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.3
PyQt: 5.15.0

sip: 5.3.0
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.32.3
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.1.3
Platform: Linux-5.7.9-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from ~/programs/qutebrowser/qutebrowser
Using Python from /usr/bin/python
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /tmp/qutebrowser-basedir-r423bxld/cache
config: /tmp/qutebrowser-basedir-r423bxld/config
data: /tmp/qutebrowser-basedir-r423bxld/data
runtime: /tmp/qutebrowser-basedir-r423bxld/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:04:51
```

**How to reproduce**
This might be difficult for others to reproduce, because I've so far only encountered trying to print a UPS label from https://www.ups.com/uel/llp/[REDACTED], and for obvious reasons I am not going to share that particular page.

However, I can describe what I've discovered. It works fine in Chromium.

In Qutebrowser, the "Print Label" button opens a new tab with the title "UPS Electronic Return Label: View/Print Label". It then brings up the print dialog, and then instantaneously closes the dialog and tab. I had to record a screengrab to see what was going on - at 50 fps, I get the following frames
1: blank tab with correct title
2: print dialog appears
3: window title changed to title of the orginal UPS tab
4: print dialog content is no longer rendered (it's filled black instead)
5: dialog and tab are both gone.

In an attempt to understand what was going on, I tried inspecting the javascript code. I didn't succeed in understanding the code, but I did discover something curious. If I set a breakpoint on mouseup events (via Sources > Event Listener Breakpoints > Mouse > mouseup) it still fails in the same way. If I set a breakpoint on all Mouse events (and continue past each one with F8), then the behaviour is different. Sometimes it stops responding to clicks (and I have to refresh the page), but sometimes I manage to successfully click the button. When that happens, it correctly loads the new tab, but doesn't bring up the print dialog. I can then manually ask to print it by running ":print", and using the print dialog to successfully print to pdf (the default printer option is a printer that was previously detected by CUPS but doesn't exist on this network).

I think this behaviour suggests that there is a race condition in the (minified) javascript, since spreading out the event listener callbacks changes the behaviour. I don't have a clue what's happening beyond that.

The debug output (even at level vdebug) doesn't reveal anything obvious, but I'm including it here anyway:
```
22:02:58 DEBUG    js         shared:javascript_log_message:150 [https://tags.tiqcdn.com/utag/ups/maestro/prod/utag.js:116] null
22:02:58 DEBUG    js         shared:javascript_log_message:150 [https://tags.tiqcdn.com/utag/ups/maestro/prod/utag.js:116] removing cookie
22:02:58 DEBUG    js         shared:javascript_log_message:150 [https://tags.tiqcdn.com/utag/ups/maestro/prod/utag.js:116] null
22:02:58 DEBUG    js         shared:javascript_log_message:150 [https://tags.tiqcdn.com/utag/ups/maestro/prod/utag.js:116] removing cookie
22:02:58 DEBUG    misc       eventfilter:eventFilter:84 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f31c826c0d0> got new child <PyQt5.QtWidgets.QWidget object at 0x7f31c826ce50>, installing filter
22:02:58 DEBUG    webview    webview:createWindow:125 createWindow with type WebDialog, background False
22:02:58 WARNING  webview    webview:createWindow:132 WebDialog requested, but we don't support that!
22:02:58 DEBUG    webview    tabbedbrowser:tabopen:588 Creating new tab with URL None, background False, related True, idx None
22:02:58 DEBUG    webview    tabbedbrowser:_get_new_tab_idx:678 tabs.new_position next -> opening new tab at 1, next left: 0 / right: 2
22:02:58 DEBUG    misc       app:on_focus_object_changed:524 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f31c826caf0>
22:02:58 DEBUG    misc       app:on_focus_object_changed:524 Focus object changed: <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f31c82df0d0>
22:02:58 DEBUG    modes      tabbedbrowser:_on_current_changed:835 Current tab changed, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=2 url=''>
22:02:58 DEBUG    modes      tabbedbrowser:_on_current_changed:842 Mode before tab change: normal (mode_on_change = normal)
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.hint (reason tab changed) as we're in mode KeyMode.normal
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.caret (reason tab changed) as we're in mode KeyMode.normal
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.insert (reason tab changed) as we're in mode KeyMode.normal
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.passthrough (reason tab changed) as we're in mode KeyMode.normal
22:02:58 DEBUG    modes      tabbedbrowser:_on_current_changed:853 Mode after tab change: normal (mode_on_change = normal)
22:02:58 DEBUG    misc       eventfilter:eventFilter:95 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f31c826c0d0>: removed child <PyQt5.QtWidgets.QWidget object at 0x7f31986f0430>
22:02:58 DEBUG    misc       eventfilter:eventFilter:84 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f31c82df0d0> got new child <PyQt5.QtWidgets.QWidget object at 0x7f31986f0430>, installing filter
22:02:58 DEBUG    misc       app:on_focus_object_changed:524 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f31c826caf0>
22:02:58 DEBUG    webview    webenginetab:_store_match_data:214 Active search match: 0/0
22:02:58 DEBUG    webview    browsertab:_set_load_status:982 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=2 url=''>: LoadStatus.loading
22:02:58 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.loading: 6>) (tab 1)
22:02:58 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 1)
22:02:58 DEBUG    webview    browsertab:_set_load_status:982 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=2 url=''>: LoadStatus.success
22:02:58 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.success: 2>) (tab 1)
22:02:58 DEBUG    misc       webenginetab:_on_history_trigger:1507 Ignoring invalid URL being added to history
22:02:58 DEBUG    sessions   sessions:save:330 Saving session _autosave to /tmp/qutebrowser-basedir-r423bxld/data/sessions/_autosave.yml...
22:02:58 VDEBUG   sessions   sessions:save:339 [REDACTED; IDENTICAL IN BOTH RUNS]
22:02:58 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(True) (tab 1)
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.hint (reason load started) as we're in mode KeyMode.normal
22:02:58 DEBUG    webview    tabbedbrowser:_on_title_changed:748 Ignoring title change to ''.
22:02:58 DEBUG    webview    tabbedbrowser:_on_title_changed:755 Changing title for idx 1 to 'UPS Electronic Return Label: View/Print Label'
[The successful run differs only after this point (aside from irrelevant differences in memory addresses and tab ids). Successful first:]
22:05:01 DEBUG    modes      modeman:_handle_keyrelease:331 filter: False
22:05:01 DEBUG    mouse      eventfilter:eventFilter:310 Ignoring QKeyEvent to <PyQt5.QtWidgets.QWidget object at 0x7f315852e4c1>
[And unsuccessful:]
22:02:58 DEBUG    webview    webenginetab:_js_cb_single:807 Got element from JS: {'attributes': {}, 'class_name': '', 'id': 0, 'is_content_editable': False, 'outer_xml': '<span>Print Label</span>', 'rects': [{'bottom': 392, 'height': 17, 'left': 170, 'right': 243.578125, 'top': 375, 'width': 73.578125}], 'tag_name': 'SPAN', 'text': 'Print Label', 'value': ''}
22:02:58 DEBUG    webelem    webelem:is_editable:252 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<span>Print Label</span>'>
22:02:58 DEBUG    mouse      eventfilter:_mousepress_insertmode_cb:244 Clicked non-editable element!
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.insert (reason click) as we're in mode KeyMode.normal
22:02:58 DEBUG    misc       app:on_focus_object_changed:524 Focus object changed: <PyQt5.QtWidgets.QComboBox object at 0x7f31986f0b80>
22:02:58 DEBUG    modes      tabbedbrowser:_on_current_changed:835 Current tab changed, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://www.ups.com/uel/llp/[REDACTED]>
22:02:58 DEBUG    modes      tabbedbrowser:_on_current_changed:842 Mode before tab change: normal (mode_on_change = normal)
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.hint (reason tab changed) as we're in mode KeyMode.normal
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.caret (reason tab changed) as we're in mode KeyMode.normal
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.insert (reason tab changed) as we're in mode KeyMode.normal
22:02:58 DEBUG    modes      modeman:leave:417 Ignoring leave request for KeyMode.passthrough (reason tab changed) as we're in mode KeyMode.normal
22:02:58 DEBUG    modes      tabbedbrowser:_on_current_changed:853 Mode after tab change: normal (mode_on_change = normal)
22:02:58 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: 2
22:02:58 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: tab
22:02:58 DEBUG    misc       eventfilter:eventFilter:95 <PyQt5.QtWidgets.QWidget object at 0x7f31986f09d0>: removed child <PyQt5.QtCore.QObject object at 0x7f31986f0700>
22:02:58 DEBUG    misc       eventfilter:eventFilter:95 <PyQt5.QtWidgets.QWidget object at 0x7f31986f09d0>: removed child <PyQt5.QtWidgets.QWidget object at 0x7f31986f0700>
22:02:58 DEBUG    misc       app:on_focus_object_changed:524 Focus object changed: None
22:02:58 DEBUG    misc       app:on_focus_object_changed:524 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f31c82df160>
22:02:58 DEBUG    destroy    objreg:_on_destroyed:130 removed: 2
22:02:58 DEBUG    destroy    objreg:_on_destroyed:130 removed: tab
```

Essentially, it seems that whatever is causing the new tab (and dialog) to close is leaving no debug output itself. I think I'd have to start setting breakpoints in the Python to make any further progress.

I'm not sure there's much that can usefully be done here, unless I decide it's worth spending a lot of time digging into it further. I've not hit this problem before, and it was only slightly inconvenient to download it from a different browser.

**Comment by The-Compiler** [comment] 2020-07-25 08:42
Can you reproduce with `--temp-basedir` as well? Could you try with a different QtWebEngine browser such as KDE Falkon too?

**Comment by andrewcarlotti** [comment] 2020-07-25 10:08
This was running with `--temp-base-dir` - I forgot to say that explicity, but I think it can be deduced anyway from the paths in the version info.
I can reproduce exactly the same behaviour in KDE Falkon - it usually doesn't work, but it does work (or at least works well enough) if I set breakpoints on mouse events. So it looks like it's an upstream bug.

**Comment by The-Compiler** [comment] 2020-07-27 07:36
Yep, this looks like a bug in QtWebEngine then. Unfortunately, without a public page to reproduce it, I suppose there's little that can be done about it... Closing this as there isn't anything actionable from qutebrowser's side here.

**Closed by The-Compiler** 2020-07-27 07:36 UTC
Labels: status: needs triage
