### ISSUE TITLE
MacOS: document how to use userscripts and external editor

### ISSUE THREAD

**Issue by Brixy** [qutebrowser/qutebrowser#5032] opened 2019-09-19 09:14 UTC
Thank you for this brilliant browser! It’s difficult to user other browsers now ;-)

Installing the `.dmg` file on MacOS Mojave works out of the box.

But there seem to be some general issues:

- The external editor does not seem to work—even with settings like `c.editor.command = ['/usr/local/bin/nvim', '-f', '{file}', '-c', 'normal {line}G{column0}l']`
- `spawn --userscript …` leads to an error message (see below).
- For some userscripts some kind of `node` settings in `.bashrc` or `.zshrc` seems necessary.

I tested and read a lot but cannot find the relevant information. It would be great if some MacOS specific information could be added.

Thanks a lot!

---

**Setup:**

qutebrowser v1.7.0

MacOS Mojave

---

**Some error messages:**

**:config-edit**

```
message:error:58

Editor exited with status 1, see :messages for details.

guiprocess:_on_finished:112

Process stdout:
[22;0;0t[H[J]11;?[?2004h[0;10m[H[J[?1002h[?1006h[38;2;248;248;242m[48;2;27;29;30m                                                                                
[B                                                                                
[B                                                                                
[B                                                                                
[B                                                                                
[B
…

guiprocess:_on_finished:114

Process stderr:
Vim: Fehler beim Lesen der Eingabe, Abbruch...

Vim: Finished.
```

**Example: `spawn --userscript readability`**

```
message:error:58

Userscript exited with status 1, see :messages for details.

Process stderr:
Traceback (most recent call last):
  File "/Users/username/Library/Application Support/qutebrowser/userscripts/readability", line 55, in <module>
    from readability import Document
  File "/Users/username/Library/Application Support/qutebrowser/userscripts/readability.py", line 55, in <module>
ImportError: cannot import name Document
```

I am not sure, whether I am testing correctly; `:spawn test` output:

```
message:error:58
Command exited with status 1, see :messages for details.
```

---

**Test settings in .zshrc**

```
export NODE_PATH=$NODE_PATH:`npm root -g`
```

```
export NODE_PATH=`which node`
```

**Comment by The-Compiler** [comment] 2019-09-19 20:01
From a quick look, this all seem like issues with your system/setup of some sorts, or things which are already documented in the userscripts.

**Comment by rien333** [comment] 2019-09-20 10:36
Not really sure why you are getting `ImportError: cannot import name Document` with the readability userscript. Do you have the most recent readability library installed (take a look [here](https://github.com/buriy/python-readability))?

Also note that `NODE_PATH` is relevant only for the `readability-js` script, _not_ the python based `readability` script.

**Comment by Brixy** [comment] 2019-09-21 11:02
Thank you very much for your help, guys!

I re-installed `readabilty` and all dependencies using `pip` and `brew`.

Instead of

```
apt-get install libxml2-dev libxslt-dev
```

I had to use

```
brew install libxml2 libxslt
```

Not quite sure whether this is correct.

Unfortunately there is still an error for `:spawn --userscript readability`:

```
message:error:58
Error while spawning userscript: execve: Exec format error
```

There seem to be a number of issues: Neovim and Node seem to require absolute path settings on MacOS, and maybe there are Linux-specific dependencies(?). I will try to investigate and give feedback here.

**Comment by rien333** [comment] 2019-09-21 12:35
> I had to use
`brew install libxml2 libxslt`
Not quite sure whether this is correct.

Looks good.  As you already may know, `apt-get` doesn't exist on macOS, and likes to packages libraries separately, while `brew` generally includes development stuff and binaries in one package.
These two specific packages are probably available under a wide array of names, hence the lack of  OS specific instructions in the userscript. Collecting all the OS-specific dependencies is probably  something the `readability` library maintainers should do. 

Also note that `readability-js` userscript was recently added to qutebrowser, which should probably produce better output. 

> There seem to be a number of issues: Neovim and Node seem to require absolute path settings on MacOS, and maybe there are Linux-specific dependencies(?)

Node also requires me to set an absolute path on linux, I think this is just due to the fact that normally node likes to package _all_ things locally.  

> Unfortunately there is still an error for :spawn --userscript readability:
```
message:error:58
Error while spawning userscript: execve: Exec format error
```

iirc, this error might be related to the exectuable bit. Are you sure that the readability script is an executable? (i.e. run `chmod +x` on the file) 

If that doesn't work, what happens if you execute the following in the folder with the `readability` script?
```bash
touch /tmp/t
env QUTE_URL="https://en.wikipedia.org/wiki/Qutebrowser" QUTE_FIFO=/tmp/t QUTE_HTML=/tmp/t  QUTE_DATA_DIR=/tmp  ./readability
```

**Comment by rien333** [comment] 2019-09-21 12:42
btw, what is your specific issue with neovim? I was able to use emacs+qutebrowser just fine  back when I was on macOS.

**Comment by Brixy** [comment] 2019-09-22 06:27
Thanks a lot for your help, @rien333!

> Also note that `readability-js` userscript was recently added to qutebrowser, which should probably produce better output.

Yes. I just installed `readability` and `readability-js` for testing different kinds of userscripts. My intention was to actually use  `readability-js`.

> iirc, this error might be related to the exectuable bit. Are you sure that the readability script is an executable? (i.e. run `chmod +x` on the file)

Yes, all userscripts are executable.

> btw, what is your specific issue with neovim? I was able to use emacs+qutebrowser just fine back when I was on macOS.

Without any configuration I get this error message, e.g. for `:edit-url`:

```
message:error:58 | Error while spawning editor: execvp: No such file or directory
```

Therefore I tried to use

```
c.editor.command = ['/usr/local/bin/nvim', '-f', '{}']
```

according to #5018.

I will continue to investigate ;-)

**Comment by rien333** [comment] 2019-09-22 09:44
I think I can reproduce `readability-js` not working on macOS. For some reason, it loads all modules correctly, except for JSDOM.

**Comment by The-Compiler** [comment] 2019-09-22 21:02
Seems to work for me after `brew install node`, `npm install -g jsdom` (`jsdom@15.1.1`) and `export NODE_PATH=$NODE_PATH:$(npm root -g)`:

```
Welcome to Node.js v12.10.0.
Type ".help" for more information.
> const { JSDOM } = require("jsdom");
undefined
> JSDOM
[Function: JSDOM]
```

**Comment by rien333** [comment] 2019-09-22 22:33
Thanks @The-Compiler! After some more digging through `npm list -g`, I found out that there was another node package that had a much older version of `jsdom` as a dependency. Removing said package fixes it for me. Maybe something to be aware of @Brixy , given that this old `jsdom` version gave me similar errors as you encountered. 

As far as I'm concerned, both `readability` and `readability-js` work fine under macOS.

**Comment by rien333** [comment] 2019-09-24 17:53
For some reason I was under the impression that `nvim` was a GUI program, that might explain why it didn't work completely. 

> Unfortunately, doing so on macOS seems much more complicated than on Linux, e.g. requiring a custom AppleScript. 

What's worse, iirc, is that there is no good way to if whatever process you launch has exited when you use AppleScript (The spawned process has to 'block' until the file is done editing, and AppleScript does something like forking). I made this terrible hack of a script to cope with this a few years back, maybe it will help you going (see also the discussion  in [this reddit post]():)

```fish
#!/usr/local/bin/fish

# Open up a new iterm window with emacsclient in it, and quit after the editing is done

set nw 'tell application "iTerm"
set newWindow to (create window with default profile)
tell current session of newWindow
write text "emacsclient -nw -c ' $argv[1..-1]'; exit 0"
end tell
end tell'

osascript -e "$nw" &

# wait until emacs has launched
sleep 0.81

set PID (ps aux | grep "emacsclient -nw -c $argv[1..-1]" | awk '{print $2}')
while ps -p $PID > /dev/null ^&1
	sleep 0.5
end
exit 0
```

**Comment by Brixy** [comment] 2019-09-27 13:15
Thank you very much for you tips.

`export NODE_PATH=$NODE_PATH:$(npm root -g)` looks very promising; but despite of re-installing everything and adding this line of code to `.zshrc` if had no success with `readability-js`.

I read **a lot** on the internet and tested dozens of tips.

The strange thing is that I have a very slim and decent setup and have never had any problems. That’s why I thought it had to be a Qutebrowser issue.

As it obviously is not, please feel free to close this issue. I’ll keep trying.

@rien333 Thank you very much for the Script!

**Comment by The-Compiler** [comment] 2019-09-27 13:21
Your `.zshrc` is probably not going to matter unless you launch qutebrowser from zsh. You'll need to find a way of setting the variable for GUI applications, which is unfortunately quite a pain on macOS.

Closing this as indeed I don't think this is a qutebrowser issue.

**Closed by The-Compiler** 2019-09-27 13:21 UTC
Labels: os: macOS, status: needs triage

**Comment by spejamchr** [comment] 2019-09-27 19:40
I'm not sure if this helps, but I'm on macOS and have nvim set up as my editor. I use [kitty](https://github.com/kovidgoyal/kitty) as my terminal, which allows me to do:

```python
c.editor.command = ["kitty", "nvim", "{file}", "+norm {line}G{column}|"]
```

**Comment by rien333** [comment] 2019-09-27 21:07
Kitty is a great terminal, so def worth the try! and it's indeed easier to call/manage from scripts and such.

**Comment by MarcinWieczorek** [comment] 2019-09-29 08:56
> I'm not sure if this helps, but I'm on macOS and have nvim set up as my editor. I use [kitty](https://github.com/kovidgoyal/kitty) as my terminal, which allows me to do:
> 
> ```python
> c.editor.command = ["kitty", "nvim", "{file}", "+norm {line}G{column}|"]
> ```

My approach was similar, only using urxvt as a terminal. The problem is that the very first configuration requires manual intervention from the user. As a fresh user the only thing I knew was "Vim like browser". So first I tried `:config-edit`. I couldn't edit my config without editing my config manually first. This might discourage new users from using the browser. My suggestion is asking the user for an editor (or a cmd running terminal and the editor) on failure with gvim (which I obviously don't have, otherwise I wouldn't write this). Another idea would be getting the terminal from environment variables (most likely `$TERM`, although it's not standardized afaik) and running `$EDITOR` from there. I could even implement this if you want to do something with this issue, or maybe I'm missing some obvious solution, let's discuss.
Marcin

**Comment by rien333** [comment] 2019-09-29 09:26
> The problem is that the very first configuration requires manual intervention from the user

What's so bad about editing the config "manually"? That's how I edit most files. Like I don't really see how editing a file in `~/.config` to configure it (initially) differs from using any other software. 

>  Another idea would be getting the terminal from environment variables (most likely `$TERM`, although it's not standardized afaik) and running `$EDITOR` from there.

Doing something with `$EDITOR` seems neat, although I'm not sure if `$EDITOR` could also point to a GUI text-editor.

**Comment by toofar** [comment] 2019-09-29 09:33
> This might discourage new users from using the browser.

More likely they would just use insert mode.

**Comment by MarcinWieczorek** [comment] 2019-09-29 09:42
> What's so bad about editing the config "manually"? That's how I edit most files. Like I don't really see how editing a file in `~/.config` to configure it (initially) differs from using any other software.
>
There's nothing bad, I do it that way too, but then what's the point of such feature? The only reason why I tried the command was that I didn't know the location of the file, and also it didn't exist yet.

**Comment by The-Compiler** [comment] 2019-09-29 12:20
As a new qutebrowser user, you'll probably use `:set` instead of writing a `config.py` anyways - `config.py` is aimed at advanced users who want full control over their configuration.

`$EDITOR` points to a terminal editor, and there's no good way for qutebrowser to find out what terminal to use. `$TERM` says what capabilities a given terminal has, not what terminal to use.

Bottomline: It's not really easy to find a sensible default - there might be something better than hardcoding gvim, and there's #41 for that already.

**Comment by Brixy** [comment] 2019-10-01 09:31
Hi all!

Thanks again for all your support. As there was some traffic here after this issue was closed I just wanted to give some final feedback.

---

Thanks for pointing me/us to kitty. A fast and highly configurable terminal. Using it in Qutebrowser still results in

    Error while spawning editor: execvp: No such file or directory

I read and tested a lot. The reason *may* be that I have not XCode installed?

Also a simple editor command like `open -a textedit` does not work.

---

There still seems to be a conflict MacOS/Node/qutebrowser (although I have not had any problems with other apps).

Error message is:

> Process stderr:
> env: node: No such file or directory

I did a lot of tweaking ([example](https://gist.github.com/DanHerbert/9520689)) without success.

---

All in all I am using a nicely configurated qutebrowser—without userscripts.

**Comment by rien333** [comment] 2019-10-01 09:52
What the-compiler said, and

> There still seems to be a conflict MacOS/Node/qutebrowser (although I have not had any problems with other apps).
Error message is: ...

Be sure to always tell what you run, instead of only posting the error. Maybe include the output of `echo $NODE_PATH` and `echo $PATH`, and thoroughly inspect the output yourself for the presence of the right files (e.g. the `node` binary and the right readability library). 

As was probably already said, applications under macOS (and other OSes) don't just pick up environment variables when you run e.g. `export $PATH=foo bar` in a terminal, nor are they necessarily visible when you put exports in your `.bashrc` (or your shell's equivalent). 

To troubleshoot `PATH` related issues, I recommend running something like:
```
env NODE_PATH="/usr/lib/node_modules/"  PATH="/usr/bin/ /usr/local/bin" /Applications/Qutebrowser.app/Contents/macOS/qutebrowser
```
This will force qutebrowser to be ran with those environment variable values.

(I'm not sure if I got the macOS path to the qutebrowser binary right)

**Comment by Brixy** [comment] 2019-10-02 08:06
Thank you, guys. It is working now.

@rien333 Your comment

> env NODE_PATH="/usr/lib/node_modules/"  PATH="/usr/bin/ /usr/local/bin" /Applications/Qutebrowser.app/Contents/macOS/qutebrowser

pointed me into the right direction.

What I do now is this:

```
open -a qutebrowser
```

and everything works as expected.

Thank you all very, very much for your help and patience.

P.S.: I also tried to add these (and similar) lines to qutebrowser’s `config.py`:

```
PATH="/usr/local/bin"
NODE_PATH=":/usr/local/lib/node_modules"
``` 

This would be an easy solution but does not work.

**Comment by arza-zara** [comment] 2019-10-02 08:25
> P.S.: I also tried to add these (and similar) lines to qutebrowser’s `config.py`:
> 
> ```
> PATH="/usr/local/bin"
> NODE_PATH=":/usr/local/lib/node_modules"
> ```
> 
> This would be an easy solution but does not work.

In python that's:
```
import os
os.environ['PATH'] += os.pathsep + '/usr/local/bin'
```

**Comment by Brixy** [comment] 2019-10-02 09:00
Brilliant! Thank you, @arza-zara

Now everything is working with these lines in `config.py`:

```
import os
os.environ['PATH'] = os.pathsep + '/usr/local/bin'
os.environ['NODE_PATH'] = os.pathsep + '/usr/local/lib/node_modules'
```

Sorry for bothering: Regarding the title of this issue would’t it make sense to document this very easy setup anywhere?

Thanks again!

**Comment by rien333** [comment] 2019-10-02 09:50
> os.environ['NODE_PATH'] = os.pathsep + '/usr/local/lib/node_modules'`
Sorry for bothering: Regarding the title of this issue would’t it make sense to document this very easy setup anywhere?

This is a nice "tip" that I wasn't aware of actually. Keeps qutebrowser related environment variables separated from the rest, and solves the imo messy  state of universal variables (different shells and OSes have different approaches, etc.)

**Comment by The-Compiler** [comment] 2019-10-07 11:40
@Brixy Agreed! We already have an item for this in the [FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc) at the bottom, that could probably be expanded a bit. Do you want to try opening a pull request for it? Note that your code should probably use `+=` to append to the existing paths rather than overwriting it.

**Comment by Brixy** [comment] 2019-10-09 07:45
Thanks for the confidence, @The-Compiler.

I am neither a (Python) programmer nor a native speaker. So my pull request would be very rudimentary probably lacking the technical vocabulary.

If you give your OK anyway, I will give it a try.

Anyway, I am very glad we found a solution for MacOS.

**Comment by The-Compiler** [comment] 2019-10-09 08:07
Please do give it a try! We can always revise it a bit, no harm done :wink:
