### ISSUE TITLE
Qutebrowser crash on i3 reload:

### ISSUE THREAD

**Issue by alkim0** [qutebrowser/qutebrowser#7957] opened 2023-10-07 16:21 UTC
**Version info**:

qutebrowser v3.0.0
Git commit: 521370944 on adblock-qt6 (2023-09-19 15:24:04 +0900)
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
I don't know

**Description**
I did a live reload of i3, and qutebrowser crashed. More annoyingly, when I restarted qutebrowser, it didn't restore my previous session.

Note, this has never happened before, so I think it's pretty difficult to trigger. But I figured I would report it anyway because of the uncaught exception.

Here is the traceback I got when it crashed:
```
01:11:45 ERROR: Renderer process was killed (status 9)
libpng warning: iCCP: known incorrect sRGB profile
01:11:47 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/home/wind/sources/qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 1028, in <lambda>
    QTimer.singleShot(100, lambda: show_error_page(error_page))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wind/sources/qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 1006, in show_error_page
    tab.set_html(html)
  File "/home/wind/sources/qutebrowser/qutebrowser/browser/webengine/webenginetab.py", line 1516, in set_html
    self._widget.setHtml(html, base_url)
RuntimeError: wrapped C/C++ object of type WebEngineView has been deleted
01:11:47 ERROR: Error while recovering pages: wrapped C/C++ object of type TabWidget has been deleted
Traceback (most recent call last):
  File "/home/wind/sources/qutebrowser/qutebrowser/misc/crashsignal.py", line 194, in _get_exception_info
    pages = self._recover_pages(forgiving=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wind/sources/qutebrowser/qutebrowser/misc/crashsignal.py", line 120, in _recover_pages
    for tab in tabbed_browser.widgets():
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wind/sources/qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 290, in widgets
    for i in range(self.widget.count()):
                   ^^^^^^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type TabWidget has been deleted
01:11:47 ERROR: Could not remove crash log!
Traceback (most recent call last):
  File "/home/wind/sources/qutebrowser/qutebrowser/misc/crashsignal.py", line 183, in destroy_crashlogfile
    os.remove(self._crash_log_file.name)
FileNotFoundError: [Errno 2] No such file or directory: '/home/wind/.local/share/qutebrowser/crash.log'
```

EDIT: I should also note that even though this was on the adblock-qt6 PR branch, there are no changes to the lines that showed up in the traceback in that branch, so the bug likely exists in `main` as well.

**Comment by markstos** [comment] 2023-10-15 13:14
As a small dev-team, at what point should Qutebrowser consider dropping support for X11? 

Even larger, better-resourced projects like Gnome are considering it:
https://www.theregister.com/2023/10/13/gnome_proposes_dropping_x11/

For this bug in particular, it is not reproducible on Sway/Wayland.

**Comment by The-Compiler** [comment] 2023-10-15 15:05
There is nothing qutebrowser does to support X11, that's a Qt thing.

**Comment by The-Compiler** [comment] 2023-10-16 15:08
I'm not sure how this happened exactly - but the original exception triggering the crash is a duplicate of #6826. I don't think there is much we can do about the follow-up issues without a reproducer I'm afraid.

**Closed by The-Compiler** 2023-10-16 15:08 UTC
