### ISSUE TITLE
Error while opening https://www.tradingview.com

### ISSUE THREAD

**Issue by rhysday** [qutebrowser/qutebrowser#6032] opened 2021-01-11 22:06 UTC
**Version info**:
qutebrowser v1.14.1
Git commit: 4a7406fe3 on master (2021-01-05 19:50:48 +0100)
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Unable to load page
Error while opening https://www.tradingview.com/
Renderer process was killed

**How to reproduce**
Visit https://www.tradingview.com

**Comment by The-Compiler** [comment] 2021-01-11 23:25
Does it work with `--temp-basedir --qt-flag disable-features=InstalledApp`?

**Comment by rhysday** [comment] 2021-01-12 00:44
Yes, that does work. 
What do I have to add in my config to keep this fix?

**Comment by The-Compiler** [comment] 2021-01-12 14:15
Duplicate of #5997

**Comment by The-Compiler** [comment] 2021-01-12 14:16
I'll push a workaround shortly - in the meantime, you can `disable-features=InstalledApp` to the `qt.args` setting, e.g. via `:config-list-add qt.args disable-features=InstalledApp`.

**Closed by The-Compiler** 2021-01-12 14:15 UTC

**Comment by rhysday** [comment] 2021-01-14 09:29
In qutebrowser I typed:
:config-list-add qt.args disable-features=InstalledApp
Hit enter
Not sure if I'm doing this right? Trading View still doesn't load

**Comment by rhysday** [comment] 2021-01-14 09:31
Is there something I can add to my config.py instead?

**Comment by The-Compiler** [comment] 2021-01-14 10:37
Sure, `c.qt.args = ["disable-features=InstalledApp"]` - also see the [configuration docs](https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/configuring.asciidoc).

**Comment by rajendrasp** [comment] 2021-12-23 19:20
I do not know if it is okay to ask here on a closed thread but it is a follow up. I am also getting this crash for tradingview.com. and I have a GUI PyQt5 app in which I am using a QWebEngineView to render tradingview website in a layout. So @The-Compiler , you mention the solution to add it config.py but I do not have that file. How do I resolve this crash? And it is resolved yet in latest PyQt5?

**Comment by The-Compiler** [comment] 2021-12-23 21:13
@rajendrasp This isn't really the right place to get support for QtWebEngine outside of qutebrowser, even less so if you comment on multiple duplicate issues about the same topic...
