### ISSUE TITLE
Restored tabs from the last session do not show the <title> correctly

### ISSUE THREAD

**Issue by SirCmpwn** [qutebrowser/qutebrowser#3718] opened 2018-03-14 12:41 UTC
Instead they show the URL, until you refresh.

**Comment by The-Compiler** [comment] 2018-03-14 12:44
Hmm, I see that even with `:undo` etc. - seems to be a v1.2.0 regression.

**Comment by SirCmpwn** [comment] 2018-03-14 18:25
Thanks!

**Comment by SirCmpwn** [comment] 2018-03-15 12:40
I can still reproduce this behavior after updating to the latest version from the master branch. Undo too.

**Comment by The-Compiler** [comment] 2018-03-15 13:08
Hm, indeed. I can't consistently reproduce this, but right now I can again...

**Comment by The-Compiler** [comment] 2018-03-15 13:54
Hopefully really fixed in the latest master - let me know if you still see it. Not sure yet whether the next release is going to be v1.2.2 or v1.3.0 though.

**Closed** 2018-03-15 13:53 UTC
Labels: bug: behavior, component: ui

**Comment by SirCmpwn** [comment] 2018-03-15 14:56
Thanks! I'll test it this afternoon.

**Comment by SirCmpwn** [comment] 2018-03-15 21:24
Fix is good, thanks!
