### ISSUE TITLE
Slow open, warning

### ISSUE THREAD

**Issue by crstcoolv** [qutebrowser/qutebrowser#3815] opened 2018-04-04 17:51 UTC
this is try to read a file that doesnt exist, when i open from the terminal its show this message:
`[0404/143231.060682:WARNING:stack_trace_posix.cc(648)] Failed to open file: /home/usarname/#1840121`
and kind of slow it down.This is not critical but there is an error going on there.

v1.2.1 arch repository

**Comment by jgkamat** [comment] 2018-04-04 21:40
This is a duplicate of #3459. I don't think this should be causing any issues though, the slowness to open might be due to other reasons.

**Closed by jgkamat** 2018-04-04 21:40 UTC
