### ISSUE TITLE
Context menus cannot be interacted with using the keyboard

### ISSUE THREAD

**Issue by squeaktoy** [qutebrowser/qutebrowser#8112] opened 2024-02-23 01:03 UTC
**Version info**:
```
qutebrowser v3.1.0
Git commit: 
Backend: QtWebEngine 6.6.2, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.2
CPython: 3.11.7
PyQt: 6.6.1
Qt wrapper: PyQt6 (via override)
```

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
When tabbing or using `/` to find and select an item such as a link, I wanted to copy the link address. So naturally, I press the menu key. A Qt context menu opens. Great! I can use the arrow keys to navigate the context menu. I select the item "Copy link address" and hit Enter. Uhm, what? It seems that the key gets handled by qutebrowser and the link has been clicked rather than the "Copy link address" button in the context menu. :confused:
Furthermore, it is impossible to close the context menu without a mouse, something which you would expect a keyboard-focused browser to be able to do. Pressing escape does in fact nothing to get you out of this situation... Every key input gets 'stolen' by qutebrowser, and Qt never handles them properly in the context menu like it should. This makes me required to use a pointer device to either interact with the context menu or close it.

**How to reproduce**
1. Go to any site.
2. Select a link.
3. Press Menu, Apps, or Shift+F10
4. A context menu opens, and now you're stuck!

**Comment by The-Compiler** [comment] 2024-02-23 06:38
Duplicate of #3465

**Closed** 2024-02-23 06:38 UTC
