### ISSUE TITLE
Webfont issues after Qt 5.15 upgrade

### ISSUE THREAD

**Issue by lilpea** [qutebrowser/qutebrowser#5494] opened 2020-06-06 16:51 UTC
**Version info**:
```
qutebrowser v1.12.0
Git commit: eaff6e82d (2020-06-01 15:57:24 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0
```
I have tested this only on Windows 8.1; it appears to be a problem with the Qt upgrade.

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Webfonts don't seem to get rendered since the recent update. They seem not to function altogether ([Google Fonts](https://fonts.google.com) also throws up an error).

**How to reproduce**

I have quickly thrown together a [site to test this issue](https://lilpea.github.io/qutewebfonts). Some example screenshots:

Expected result (webfont Fira Sans is loaded):
![Expected result](https://i.imgur.com/LB5MCYE.png)

Actual result (text gets rendered with the fallback font):
![Actual result](https://i.imgur.com/AAbXJBm.png)

The webfont formats I have tested are `woff` and `woff2`. I do have Fira Sans installed on my computer also, but that appears not to affect this issue—if an already installed font is also declared as a webfont via `@font-face`, it still refuses to show up.

**Comment by The-Compiler** [comment] 2020-06-08 18:45
Works fine for me:

![image](https://user-images.githubusercontent.com/625793/84068226-efcd8b80-a9c8-11ea-9c6e-b5f0dd37b9ad.png)

What error is it that Google Font shows? What do you see in the highlighted portion of my screenshot in `:inspector`? What about the console tab of the inspector?

**Comment by lilpea** [comment] 2020-06-09 01:26
Google Fonts shows the following errors:

![Google Fonts error](https://i.imgur.com/p3NcTt9.png)

The inspector shows Arial as a local font:

![Inspector screenshot](https://i.imgur.com/WbBjzPq.png)

Only removing every `@font-face` declaration allows for Fira Sans to be rendered as a local font. The console tab shows no errors.

I have also discovered that TrueType fonts are not affected, as can be seen with [Fontspring's website](https://www.fontspring.com/). The WOFF, WOFF2, and SVG formats are the ones I have tested as not being rendered.

**Comment by The-Compiler** [comment] 2020-06-09 08:48
And no output in the console with your test page, right? I suppose if you open https://lilpea.github.io/qutewebfonts/FiraSans-Italic.woff manually, it gets downloaded just fine? Whta does the network tab show when you force-reload (shift-R) your test page?

**Comment by lilpea** [comment] 2020-06-09 13:41
The console has no output, yes. Opening https://lilpea.github.io/qutewebfonts/FiraSans-Italic.woff2 manually, it gets downloaded as normal. When force-reloading the page, there are no network requests for fonts shown. However, reloading normally does show the font files as having been loaded in from cache ([screenshot](https://i.imgur.com/xKIXByf.png)).

**Comment by The-Compiler** [comment] 2020-06-09 13:43
Hmm, I'm pretty much out of ideas at this point to be honest... Can you launch qutebrowser with `--temp-basedir`, go to Google Fonts, go to your demo page, and then do `:report` so I can take a look at the logs?

**Comment by lilpea** [comment] 2020-06-09 13:50
Done.

**Comment by The-Compiler** [comment] 2020-06-09 13:59
Still no idea what's happening, I'm afraid. If you open https://lilpea.github.io/qutewebfonts/FiraSans-Italic.woff manually and download it, do you actually get a valid WOFF file (for a quick check, does it start with `wOF2` when opened in an editor or so)?

Can you check if you see the same issue in Google Chrome on the same machine?

**Comment by The-Compiler** [comment] 2020-06-18 09:22
@lilpea Any update on my questions above?

**Comment by The-Compiler** [comment] 2020-06-24 07:56
Closing because of inactivity - I doubt qutebrowser is to blame here, but I have to admit I have no idea why this is happening.

**Comment by The-Compiler** [comment] 2020-07-06 13:51
Looks like @tjulioh is seeing the same in https://github.com/qutebrowser/qutebrowser/discussions/5561, apparently on Windows too. Still no idea what could be going on here, but I guess I should report a bug upstream.

**Comment by The-Compiler** [comment] 2020-07-22 14:25
From #5561:

> I tested on linx and work fine,
>
> In Windows i try different versions of qute, the 1.12.0, 1.13.0 and 1.13.1 have this problem, the others dont, 1.11.1 worked.

So I guess this is a Qt 5.15 regression on Windows. Still no idea what's going on exactly or why I can't reproduce it.

**Comment by The-Compiler** [comment] 2020-09-30 21:49
```
23:22 <ssiyad> Hello! I've got an issue with qtwebengine (qutebrowser). Google fonts doesn't seem to load at all while local font files work. What might be the issue causing this?\\
23:22 <The-Compiler> ssiyad: on Windows?
23:23 <ssiyad> The-Compiler: Linux, Arch
23:23 <The-Compiler> huh, I'm only aware of https://github.com/qutebrowser/qutebrowser/issues/5494 (which I can't reproduce though)
23:23 <The-Compiler> ssiyad: what backend, qutebrowser version, and Qt version? (:version)
23:23 <The-Compiler> ssiyad: can you reproduce it when starting with --temp-basedir?
23:23 <ssiyad> qutebrowser 1.13.1-1, python-pyqtwebengine 5.15.1-2
23:24 <ssiyad> qt5-base 5.15.1-1
23:24 <ssiyad> The-Compiler: Yes its also present with --temp-basedir
23:24 <The-Compiler> and I assume they work fine in Chromium?
23:25 <ssiyad> yes, and firefox too
23:25 <The-Compiler> does the https://fonts.google.com/ site work or give you this weird shrugging emoji as well?
23:26 <The-Compiler> also does https://lilpea.github.io/qutewebfonts/ use the custom font or not? (see the screenshots in https://github.com/qutebrowser/qutebrowser/issues/5494 for details)
23:28 <ssiyad> Google fonts work okay
23:28 <ssiyad> https://lilpea.github.io/qutewebfonts/ shows default font
23:29 <The-Compiler> well, I'm out of ideas
23:30 <The-Compiler> Anything in the console in the :devtools ('wi') when you :reload -f ('R')? If you switch to the network tab and reload again, do you notice anything strange with the requests for the WOFF files?
23:30 <ssiyad> let me check
23:30 <ssiyad> Nothing
23:31 <The-Compiler> also I assume the Elements tab will also show Arial rather than Fira Sans as rendered font? (see https://github.com/qutebrowser/qutebrowser/issues/5494#issuecomment-640805293 for a screenshot)
23:31 <ssiyad> https://ibb.co/bBqVKhS Is this something?
23:32 <ssiyad> The-Compiler: Yes, thats true
23:32 <ssiyad> Wait, its Fira
23:33 <ssiyad> https://ibb.co/tm6qh5K
23:34 <The-Compiler> wrong place I think
23:34 <The-Compiler> check the very bottom ("Rendered Fonts")
23:37 <ssiyad> https://ibb.co/6R4mSLw can't see, sorry
23:38 <The-Compiler> select the h1 element like before, switch to the computed tab at the right like before, and then scroll to the very bottom
23:39 <ssiyad> Google fonts does show some error btw
23:40 <ssiyad> https://ibb.co/PCbBdJC
23:40 <ssiyad> https://ibb.co/1ZcGM3S
23:41 <The-Compiler> no idea what that means, but it's hopefully unrelated
23:42 <The-Compiler> looks like you really see the exact same issue there, but happen to be the first one to see it outside of Windows
23:42 <The-Compiler> any chance you can test with another QtWebEngine-based browser such as KDE Falkon?
23:43 <ssiyad> Let me try
23:45 <ssiyad> The-Compiler: Yes, same issue https://ibb.co/tBprfX4
23:48 <The-Compiler> ssiyad: alright, thanks for testing! Still no idea I'm afraid... At this point someone should open an issue at https://bugreports.qt.io/ - and that won't be me because I can't reproduce the issue
23:49 <The-Compiler> ssiyad: is it okay if I post the IRC logs from this discussion in the qutebrowser issue?
23:49 <ssiyad> Sure
```

So apparently not Windows-specific.

**Comment by The-Compiler** [comment] 2020-09-30 22:04
I just found https://bugs.chromium.org/p/chromium/issues/detail?id=1112851&q=woff&can=1 - but apparently `--temp-basedir --qt-flag disable-features=AlignFontDisplayAutoTimeoutWithLCPGoal` doesn't change anything, can anyone else confirm/deny that?

**Comment by tjulioh** [comment] 2020-10-02 11:25
I test and doesn't change anything, thkx.

**Comment by The-Compiler** [comment] 2020-10-02 12:08
Given that it's clear now that this isn't qutebrowser-specific, I'm closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, someone who can reproduce this should please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa). Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2020-10-02 12:08 UTC
Labels: bug: behavior, component: QtWebEngine, os: Windows, qt: 5.15

**Comment by The-Compiler** [comment] 2021-06-30 13:30
I'm being told this is working properly nowadays, with recent QtWebEngine releases, @tjulioh @lilpea @ssiyad could any of you retest?

**Comment by tjulioh** [comment] 2021-07-09 13:44
@The-Compiler for me, now working fine, thkx.

**Comment by tjulioh** [comment] 2021-07-09 13:45
@The-Compiler for me, now working fine, thkx.
