### ISSUE TITLE
Activity Monitor on macOs 10.13.1 shows qutebrowser.app (Not responding)

### ISSUE THREAD

**Issue by Celerrime** [qutebrowser/qutebrowser#3050] opened 2017-10-03 15:17 UTC
I'm able to use the browser fine on macOs, but the activity monitor shows it as (Not responding). See screenshot below.

<img width="793" alt="screen shot 2017-10-03 at 11 04 59" src="https://user-images.githubusercontent.com/23215749/31132802-c0bfc552-a82b-11e7-814c-5e45ea04d309.png">

qutebrowser version info below
> qutebrowser v0.11.0
> Git commit: v0.11.0-8-g725d4a4 (2017-07-04 22:16:21 +0200)
> Backend: QtWebEngine (Chromium 56.0.2924.122)
> 
> CPython: 3.6.0
> Qt: 5.9.1
> PyQt: 5.9
> 
> sip: 4.19.3
> colorama: 0.3.9
> pypeg2: 2.15
> jinja2: 2.9.6
> pygments: 2.2.0
> yaml: 3.12
> cssutils: 1.0.2 $Id$
> typing: yes
> OpenGL: 3.1.0
> PyQt5.QtWebEngineWidgets: yes
> PyQt5.QtWebKitWidgets: no
> pdf.js: no
> SSL: Secure Transport, macOS High Sierra (10.13)
> 
> Style: QMacStyle
> Platform: Darwin-17.2.0-x86_64-i386-64bit, 64bit
> Frozen: True
> Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
> Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
> OS Version: 10.13.1, x86_64

**Comment by The-Compiler** [comment] 2017-10-03 15:19
Can you see how things look with e.g. [QupZilla](https://qupzilla.com/)?

**Comment by Celerrime** [comment] 2017-10-03 15:32
No issue with Qupzilla. I do not get (Not Responding) when using Qupzilla as I do with qutebrowser.

**Comment by The-Compiler** [comment] 2017-10-03 19:34
I can't reproduce this with macOS 10.10.5.

**Comment by The-Compiler** [comment] 2017-10-04 04:15
@residentsummer Since you seem to be on macOS as well, can you try reproducing this?

**Comment by The-Compiler** [comment] 2017-10-04 17:14
I just tried this on a machine with macOS 10.13, and can't reproduce it there either.

**Comment by residentsummer** [comment] 2017-10-04 17:27
Can't reproduce on 10.11 neither. Avg energy consumption is terrifying though...
<img width="700" alt="screen shot 2017-10-04 at 20 26 29" src="https://user-images.githubusercontent.com/813112/31189967-61fdf0bc-a942-11e7-9484-e456cbeaf139.png">

> qutebrowser v0.11.0
> Git commit: v0.11.0-1050-ga576fae-dirty (2017-10-02 01:04:12 +0300)
> Backend: QtWebEngine (Chromium 56.0.2924.122)
> 
> CPython: 3.6.2
> Qt: 5.9.1
> PyQt: 5.9
> 
> sip: 4.19.3
> colorama: 0.3.9
> pypeg2: 2.15
> jinja2: 2.9.6
> pygments: 2.2.0
> yaml: 3.12
> cssutils: 1.0.2 $Id$
> attr: 17.2.0
> PyQt5.QtWebEngineWidgets: yes
> PyQt5.QtWebKitWidgets: no
> pdf.js: no
> sqlite: 3.16.2
> QtNetwork SSL: Secure Transport, OS X El Capitan (10.11)
> 
> Style: QMacStyle
> Platform: Darwin-15.6.0-x86_64-i386-64bit, 64bit
> Frozen: True
> Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
> Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
> OS Version: 10.11.6, x86_64

**Comment by The-Compiler** [comment] 2017-10-04 20:33
Closing this then, seeing that this can't be reproduced on three other machines.

As for the energy consumption, this isn't really actionable. If this is from using the completion a lot, #2815 might help. If it's something else, I'm not sure there's much qutebrowser can do.

**Closed by The-Compiler** 2017-10-04 20:33 UTC
Labels: os: macOS, priority: 2 - low, status: can't reproduce
