### ISSUE TITLE
Upper right part of the screen is sometimes highlighted when exiting command mode

### ISSUE THREAD

**Issue by n0ibe** [qutebrowser/qutebrowser#5413] opened 2020-05-06 20:11 UTC
[Version info](https://paste.the-compiler.org/view/fd984fcb)

On some websites, when I exit command mode the top left part of the screen (which is specific to the website) gets highlighted. Here are two examples, reddit and github. I'm just entering and exiting command mode, and notice what happens in the top left.

![Screen Recording 2020-05-06 at 21 48 11](https://user-images.githubusercontent.com/59321248/81223492-59cbcd00-8fe6-11ea-9c4f-b010e742ff8a.gif)

**Comment by The-Compiler** [comment] 2020-05-06 20:25
Duplicate of #2236

**Closed by The-Compiler** 2020-05-06 20:25 UTC
