### ISSUE TITLE
When using Qt 6, pdfjs displays white character

### ISSUE THREAD

**Issue by OmeletWithoutEgg** [qutebrowser/qutebrowser#7631] opened 2023-03-19 12:36 UTC
```
Version info
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.5.4
Git commit: 294e73660-dirty on master (2023-03-19 13:23:18 +1300)
Backend: QtWebEngine 6.4.3, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.3 (compiled 6.4.2)

CPython: 3.10.10
PyQt: 6.4.2

sip: no
colorama: no
jinja2: 3.1.2
pygments: 2.14.0
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: 3.4.120 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.41.1
QtNetwork SSL: OpenSSL 3.0.8 7 Feb 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.3.6
Platform: Linux-6.2.7-arch1-1-x86_64-with-glibc2.37, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/user/.config/qutebrowser/config.py has been loaded
Uptime: 1:13:15
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Some words in pdf rendered in white font, so no one can see them.

**How to reproduce**
Use qutebrowser qt6-v2 branch to open some pdf file.
For example,

https://www.mathworks.com/content/dam/mathworks/mathworks-dot-com/moler/random.pdf

The problem does not appear when using master branch.
I've also tried the `pdfjs` and `pdfjs-legacy` package on ArchLinux, and both won't fix the problem.

**Comment by The-Compiler** [comment] 2023-03-19 12:38
Duplicate of #7489 - would be interesting to see your chrome://gpu as well! Also see https://github.com/qutebrowser/qutebrowser/issues/7489#issuecomment-1370103835 for a workaround.

**Closed by The-Compiler** 2023-03-19 12:38 UTC

**Comment by OmeletWithoutEgg** [comment] 2023-03-19 12:53
Sorry I just found that the bug doesn't happen with `qutebrowser --temp-basedir`.
I actually executed `python qutebrowser.py -T -C ~/.config/qutebrowser/config.py`. Some gpu-related qt-flags might be set in my config.py.

```python
c.qt.args = [
    # 'ignore-gpu-blocklist',
    'enable-gpu-rasterization',
    'enable-native-gpu-memory-buffers',
    'num-raster-threads=4',
    'enable-accelerated-video-decode',

    'disable-accelerated-2d-canvas',
]
```

How can I show my chrome://gpu btw? Or it is actually the problem that I shouldn't set these qt-flags?

**Comment by The-Compiler** [comment] 2023-03-19 13:46
> How can I show my chrome://gpu btw?

`:open chrome://gpu` and show a screenshot (and maybe also the full report you get with the button)

> Or it is actually the problem that I shouldn't set these qt-flags?

Well, there is always a reason flags like those aren't the default in upstream Chromium. I suggest you comment them out one by one, and find which one is the culprit.

**Comment by OmeletWithoutEgg** [comment] 2023-03-19 15:55
After some testing I found that actually even with only `qutebrowser --temp-basedir` the bug is still there...

I cloned the git repo and used the master branch to do the following test.

In these arguments that white character will appear:

```bash
QUTE_QT_WRAPPER="PyQt6" python qutebrowser.py -T
QUTE_QT_WRAPPER="PyQt6" python qutebrowser.py -T -c ~/.config/qutebrowser/config.py
```

In these arguments the character will display normally.

```bash
QUTE_QT_WRAPPER="PyQt5" python qutebrowser.py -T
QUTE_QT_WRAPPER="PyQt5" python qutebrowser.py -T -c ~/.config/qutebrowser/config.py
```

Here's some info about my `chrome://gpu`.

The `chrome://gpu` when `QUTE_QT_WRAPPER="PyQt5" python qutebrowser.py -T -c ~/.config/qutebrowser/config.py`:
https://pastebin.com/Z4DNjTHg
![Screenshot_20230319_234506](https://user-images.githubusercontent.com/50587059/226187557-e6e779fc-9637-4f3c-a071-9423412d7a35.png)

The `chrome://gpu` when `QUTE_QT_WRAPPER="PyQt6" python qutebrowser.py -T -c ~/.config/qutebrowser/config.py`:
https://pastebin.com/WU3Q7PSh
![Screenshot_20230319_234545](https://user-images.githubusercontent.com/50587059/226187561-218eecfd-8de8-4a27-b3ce-0e1b03f05ccb.png)

**Comment by The-Compiler** [comment] 2023-03-19 18:55
@OmeletWithoutEgg Huh, but with `disable-accelerated-2d-canvas` the issue still happens for you? What does `chrome://gpu` show in that case then?

**Comment by OmeletWithoutEgg** [comment] 2023-03-20 01:06
The flag "disable-accelerated-2d-canvas" did solve the issue.
Sorry for didn't mention that in previous reply...

With these arguments the font appears normally.

```bash
QUTE_QT_WRAPPER="PyQt5" python qutebrowser.py -T --qt-flag "disable-accelerated-2d-canvas"
QUTE_QT_WRAPPER="PyQt5" python qutebrowser.py -T -C ~/.config/qutebrowser/config.py --qt-flag "disable-accelerated-2d-canvas"
QUTE_QT_WRAPPER="PyQt6" python qutebrowser.py -T --qt-flag "disable-accelerated-2d-canvas"
QUTE_QT_WRAPPER="PyQt6" python qutebrowser.py -T -C ~/.config/qutebrowser/config.py --qt-flag "disable-accelerated-2d-canvas"
```

QT5 chrome://gpu information
![image](https://user-images.githubusercontent.com/50587059/226222980-565f6908-e3d6-4331-8db3-44bafe3ffef8.png)
https://pastebin.com/QNnFhNHQ

QT6 chrome://gpu information
![Screenshot_20230320_090133](https://user-images.githubusercontent.com/50587059/226222892-72ffc912-cb44-423e-8edc-3b0703fc41b9.png)
https://pastebin.com/QAdmGGHp
