### ISSUE TITLE
Freeze on specially crafted queries to extremely large entries in sqlite history

### ISSUE THREAD

**Issue by jgkamat** [qutebrowser/qutebrowser#3294] opened 2017-11-15 04:52 UTC
I recently had a hang related to the compeltion, and after debugging it, it was related to a extremely large entry in sqlite. I accidently pasted a source code file in there by mistake, whoops.

I didn't notice it until now, very much later, when making the following query.

`M is a TM and<hang here>`

Here is a sqlite history file which has the offending history entry.

[broken_history.zip](https://github.com/qutebrowser/qutebrowser/files/1473445/broken_history.zip)

Ideally we would
- Not store things this long in sqlite
or
- Handle things this long, but not hang on query

Let me know if you cannot reproduce, it's possible this is linked to a sqlite version (and I seem to be having a bunch of issues relating to old software recently...)

@rcorre, perhaps?

```
qutebrowser v1.0.3
Git commit: e72e8b855 (2017-11-14 13:29:58 +0100)
Backend: QtWebEngine (Chromium 49.0.2623.111)

CPython: 3.5.3
Qt: 5.7.1
PyQt: 5.7.1

sip: 4.19.5
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 16.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.11.1
QtNetwork SSL: 

Style: QFusionStyle
Platform: Linux-4.9.0-4-amd64-x86_64-with-debian-9.2, 64bit
Linux distribution: Debian GNU/Linux 9 (stretch) (debian)
Frozen: False
Imported from /usr/local/lib/python3.5/dist-packages/qutebrowser
Qt library executable path: /usr/local/lib/python3.5/dist-packages/PyQt5/Qt/libexec, data path: /usr/local/lib/python3.5/dist-packages/PyQt5/Qt

Paths:
cache: /home/jay/.cache/qutebrowser
config: /home/jay/.config/qutebrowser
data: /home/jay/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Uptime: 3:53:28
```

```
*[j@laythe qutebrowser]$ sqlite3 --version
3.16.2 2017-01-06 16:32:41 a65a62893ca8319e89e48b8a38cf8a59c69a8209
```
On debian stretch.

**Comment by The-Compiler** [comment] 2017-11-15 05:30
Duplicate of #1099

**Closed by The-Compiler** 2017-11-15 05:30 UTC
