### ISSUE TITLE
"Save page" option in right-click menu creates `~/Downloads` folder (even if `downloads.location.directory` is set to another folder) when `downloads.location.prompt` is set to `false`

### ISSUE THREAD

**Issue by 6b6279** [qutebrowser/qutebrowser#7316] opened 2022-07-15 12:56 UTC
**Version info**:
https://paste.the-compiler.org/view/2a484134

**Does the bug happen if you start with `--temp-basedir`?**:
Yes (when I change `downloads.location.directory` and `downloads.location.prompt`)

**Description**
When `downloads.location.directory` differs from the default value (i.e.  if it’s not equal `$HOME/Downloads`) and `downloads.location.prompt` is set to false, saving a page using the option in the right-click menu ("Save page") creates `$HOME/Downloads` if it didn’t already exist. The saved page seems to end up in the custom downloads directory, though.

**How to reproduce**
Change the default downloads directory (in my case, it’s `$HOME/envnet` instead of `$HOME/Downloads`) and disable the directory selection prompt (i.e. `-s downloads.location.prompt false`. Now save a page using the right-click menu. If `$HOME/Downloads` didn’t exist, it will be created.

**Comment by The-Compiler** [comment] 2022-07-15 13:02
I don't follow. There is no `downloads.directory.location`, so I'm assuming you mean `downloads.location.directory`.

When I set that using `qutebrowser --temp-basedir -s downloads.location.directory ~/tmp/dltest` and use "Save Page" in the context menu, I get a prompt filled with `/home/user/tmp/dltest/` as expected, and pressing enter saves the file there as expected.

**Comment by The-Compiler** [comment] 2022-07-15 13:16
Doesn't seem to change anything:

```
─[florian@aragog]──[~/proj/qutebrowser/git-qt5]──[22-07-15]──[15:15]──[git/master]────┄
$ python3 -m qutebrowser --temp-basedir -s downloads.location.directory ~/tmp/dltest -s download.location.prompt false
15:15:25 ERROR: set: NoOptionError - No option 'download.location.prompt' (did you mean 'downloads.location.prompt'?)

─[florian@aragog]──[~/proj/qutebrowser/git-qt5]──[22-07-15]──[15:15]──[git/master]────┄
$ python3 -m qutebrowser --temp-basedir -s downloads.location.directory ~/tmp/dltest -s downloads.location.prompt false

─[florian@aragog]──[~/proj/qutebrowser/git-qt5]──[22-07-15]──[15:15]──[git/master]────┄
$ ls ~/tmp/dltest
  DuckDuckGo — Privacy, simplified..mhtml

$ ls ~/Downloads/"DuckDuckGo — Privacy, simplified..mhtml"
lsd: /home/florian/Downloads/DuckDuckGo — Privacy, simplified..mhtml: No such file or directory (os error 2).
```

Are you sure the file in `~/Downloads` isn't just from a former attempt before changing the setting?

**Comment by 6b6279** [comment] 2022-07-15 13:44
Weird. I am sure that `~/Downloads` gets created upon saving a page. I have attached a video of me reproducing the issue with `--temp-basedir`:

https://user-images.githubusercontent.com/109346960/179235519-39ac471b-0b95-4739-8dca-0db8984ebf8a.mp4

**Comment by The-Compiler** [comment] 2022-07-15 13:52
> Weird. I am sure that ~/Downloads gets created upon saving a page.

Yes, but that was only a small part of your original issue description... With the updated description, this is just a duplicate of #6312.

**Closed by The-Compiler** 2022-07-15 13:52 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by 6b6279** [comment] 2022-07-15 15:03
Oops, sorry. That didn’t show up while looking for issues.
