### ISSUE TITLE
Chose position of Statusbar Widgets

### ISSUE THREAD

**Issue by Dobbie03** [qutebrowser/qutebrowser#6984] opened 2022-01-30 00:47 UTC
Is it possible to have an option to choose what side (and possibly which widgets) the statusbar widgets can be positioned?

For example:

As a longtime Firefox user my eyes automatically move the the bottom left to view what url the cursor is hovering over, I'd like to move the url widget to that side.  Plus it sort of cleans up the right hand side as there is a fair bit of information there, depending on what widgets are enabled of course.

**Comment by The-Compiler** [comment] 2022-01-30 10:03
Duplicate of #4984

**Closed by The-Compiler** 2022-01-30 10:03 UTC
