### ISSUE TITLE
not able to typing chinese using fcitx on qutebrowser 

### ISSUE THREAD

**Issue by thyeun** [qutebrowser/qutebrowser#3761] opened 2018-03-23 17:16 UTC
OS : Arch linux
WM : i3
qutebrowser : version 1.2.1.1
fcitx : 4.2.9.6-1

Not able to type chinese using fcitx on qutebrowser after upgrade to ```version 1.2.1.1```. (i can using fcitx on firefox and google-chrome).

so what i missing out?

i'm not a pro-user on qutebrowser, just using about two months.

**Comment by The-Compiler** [comment] 2018-03-23 17:19
So it did work in earlier versions? What were you using before?

**Comment by thyeun** [comment] 2018-03-23 17:24
@The-Compiler, yes, work before update, fcitx also and qutebrowser version 1.2.0.

**Comment by The-Compiler** [comment] 2018-03-24 21:15
Can you please try if it works with [Falkon](https://userbase.kde.org/Falkon) (also in the Archlinux repositories)?

**Comment by thyeun** [comment] 2018-03-24 21:24
@The-Compiler same with Falkon, i'm not sure will it because of the qtengine or not? 
but when i change to qtwebkit, it also not able to done the typing too.

p/s : i'm not sure the Falkon version, because i'm not using it, just getting the info from my friend, it happen on Falkon too.

**Comment by The-Compiler** [comment] 2018-03-24 21:26
You said above that fcitx also was updated, right? Does it work in Qt applications in general (like e.g. in qutebrowser's commandline, or the address bar in Falkon)?

**Comment by thyeun** [comment] 2018-03-24 21:38
@The-Compiler, 
**Qutebrowser - 1.2.0**
- insert-mode, pass-through-mode, command-line ```all can```.
**Qutebrowser - 1.2.1.1**
- insert-mode, pass-through-mode, command-line ```all can not```.

**Falkon**
- address-bar ```can```
- chinese web games ```all can not```, an example : ```http://king.icantw.com/game/2077310006```, at the chat area can't typing chinese.

**Comment by The-Compiler** [comment] 2018-03-24 21:42
Are you sure it's related to the qutebrowser update? Can you try installing v1.2.0 again (if you have it in your pacman cache still, `sudo pacman -U /var/cache/pacman/pkg/qutebrowser-1.2.0-1-any.pkg.tar.xz` should work).

**Comment by thyeun** [comment] 2018-03-24 21:53
@The-Compiler, only downgrade back to 1.2.0 still having same issue, since once i update to 1.2.1.1, several dependencies also upgrade. 
 
i wont downgrade the whole dependencies, due to that some of it, i need for others program.

**Comment by thyeun** [comment] 2018-03-24 22:08
@The-Compiler i will post this issue on fcitx also, see will it related with fcitx or not.

**Comment by thyeun** [comment] 2018-03-24 22:38
@The-Compiler from fcitx, some of the users that try fcitx on qt based apps/program, having fcitx qt crash. (crash on program konsole, wizqt) and program/apps based on qt are not possible using fcitx to input chinese.

**Comment by gebulmer** [comment] 2018-03-24 22:47
@thyeun if you're on arch do you have `fxitx-qt5` installed?

**Comment by thyeun** [comment] 2018-03-24 23:19
@gebulmer, yes, below is my fcitx-diagnose

```
3.  Qt IM module files:

    Found fcitx im module for Qt4: `/usr/lib/qt4/plugins/inputmethods/qtim-fcitx.so`.
    Found fcitx im module for Qt5: `/usr/lib/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`.
    Found fcitx qt module: `/usr/lib/fcitx/qt/libfcitx-quickphrase-editor5.so`.
```

**Comment by thyeun** [comment] 2018-03-25 03:05
@The-Compiler i solve it by adding the below into file ```/etc/environment```

```
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
```

**Comment by The-Compiler** [comment] 2018-03-26 04:32
That's weird - can you also reproduce this when starting qutebrowser with `--temp-basedir`?

**Comment by thyeun** [comment] 2018-03-26 04:52
Not sure correct or not, but when using ```--temp-basedir```, will bypass flash-plugins, so i can't load the games.

[0326/124809.103413:WARNING:stack_trace_posix.cc(648)]/thyeun/#4861215 (deleted)
  Error: No such file or directory
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

**Comment by The-Compiler** [comment] 2018-03-26 04:53
Oh, true. Can you start with `--temp-basedir` and then do `:set content.plugins true` before loading the page?

**Comment by thyeun** [comment] 2018-03-26 05:01
@The-Compiler same with the error, can't backspace to deleted the words.

below is the output message

```
[0326/125324.910725:WARNING:stack_trace_posix.cc(648)]/thyeun/#4861041 (deleted)
  Error: No such file or directory
libpng warning: iCCP: known incorrect sRGB profile
[32127:32149:0326/125450.110820:ERROR:service_manager.cc(156)] Connection InterfaceProviderSpec prevented service: content_plugin from binding interface: memory_instrumentation::mojom::Coordinator exposed by: content_browser
[WARNING:flash/platform/pepper/pep_module.cpp(63)] SANDBOXED
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```

**Comment by thyeun** [comment] 2018-03-26 05:06
@The-Compiler more worse, with ```--temp-basedir``` and with ```insert-mode```, can't even type ```1234567890-=\``` inside the games.

**Comment by The-Compiler** [comment] 2018-03-26 05:08
Weird! Can you please reproduce this again in your normal qutebrowser instance (where only backspacing is broken), and then do `:report` so I can take a look at the logs?

**Comment by thyeun** [comment] 2018-03-26 05:21
@The-Compiler, normal i get the same error, but for the ```--temp-basedir```, i not sure how i press, but i manage to using the backspace to delete the word (but i can't manage to done it for second time)

Below is the crash.log (```:report``` to generate it)
[crash.log](https://github.com/qutebrowser/qutebrowser/files/1846396/crash.log)

**Comment by thyeun** [comment] 2018-03-26 05:51
@The-Compiler i can make it work, but have to done a weird things with ```:set sssssssss``` (type it but not press enter, just left it like that in the command-line area) than change the input method inside the games, and i can type chinese and delete the word with backspace.

so

**Comment by The-Compiler** [comment] 2018-03-26 06:16
Are you sure you're actually in insert mode? Does your statusbar show `-- INSERT MODE --`? If not, you'll need to press `i` to get into insert mode first. Looking at the log, you seem to be pressing `<Backspace>` in normal mode, which means it'll be filtered.

**Comment by thyeun** [comment] 2018-03-26 06:19
@The-Compiler , question about this two picture

first picture
![screenshot_2018-03-26_14-06-35](https://user-images.githubusercontent.com/1939446/37889522-5c740006-30ff-11e8-93af-8f69381aa70d.png)

when my mouse click on the area ```11111``` (that area inside games, are for chatting), supposed the ```insert-mode``` will appear, right? but for this games, when i mouse click on that area, ```insert-mode``` won't appear.

than the picture show that, ```insert-mode``` are not appear.
and without ```insert-mode``` appear, i can't done backspace for deleted the wrong words.

second picture
![screenshot_2018-03-26_14-08-17](https://user-images.githubusercontent.com/1939446/37889637-f97e1a30-30ff-11e8-95a5-e562996e3913.png)

when i press ```i``` to call up ```insert-mode``` than everything will become normal (type chinese and using backspace), but once i click that area with mouse, ```insert-mode``` will disappear.

this is how i get after analysis from the crash.log

**Comment by The-Compiler** [comment] 2018-03-26 06:24
With flash plugins, qutebrowser can't know if there's an input field or not. You can set the `input.insert_mode.plugins` setting so qutebrowser always goes into insert mode when clicking e.g. a flash applet, though. 

So I think there's no issue in qutebrowser here, after all :wink: I'm closing this, but let me know if you run into more issues!

**Closed by The-Compiler** 2018-03-26 06:24 UTC
Labels: status: needs triage

**Comment by thyeun** [comment] 2018-03-26 06:33
@The-Compiler , thanks and sorry for everything, i'm not a pro-user on qutebrowser, that why alot to learn and i'm getting fun on qutebrowser, everyday i get a new things to be my play toy on qutebrowser.

**Comment by The-Compiler** [comment] 2018-03-26 06:34
No problem!

**Comment by autoteelar** [comment] 2021-05-20 23:39
no idea if this has been fixed or not, but im having the same issue currently, works in firefox, i will try falkon rn since i saw it was mentioned gotta installit real quick, alright i just tested it does not work on falkon either, any suggestions?

**Comment by autoteelar** [comment] 2021-05-20 23:41
no idea if this has been fixed or not, but im having the same issue currently, works in firefox, i will try falkon rn since i saw it was mentioned gotta installit real quick, alright i just tested it does not work on falkon either, any suggestions?

**Comment by thyeun** [comment] 2021-06-12 06:03
@autoteelar do you put the below line
`export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx`

into `/etc/environment`, ? without include that, you cant type chinese input using qutebrowser with `INSERT MODE`.

As you can see from the image below
![Screenshot_2021-06-12-02-00-35_1366x768](https://user-images.githubusercontent.com/1939446/121766733-ce2c5480-cb86-11eb-8e19-e5a279fe939d.png)

Hope that help.

**Comment by autoteelar** [comment] 2021-06-27 16:14
thank you! @thyeun

**Comment by merrittlj** [comment] 2024-04-26 16:25
While this is an old issue, fcitx's update to fcitx5 makes you change ``fcitx`` to ``fcitx5`` in your ``/etc/environment``. At least with my fcitx5 installation on Gentoo, the command for fcitx also changed to fcitx5. The updated version of the code that @thyeun originally suggested works as follows:

```
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
```
