### ISSUE TITLE
Javascript enable for domain option

### ISSUE THREAD

**Issue by dijit** [qutebrowser/qutebrowser#4481] opened 2018-12-17 22:56 UTC
Hi!

I'm aware that there's an option for per-domain white-listing of specific settings (such as, in this case, enabling javascript)

I'm hoping there's a trivial way to enable javascript for whatever site you currently have open.
Ideally this would be paired with a white-list function too, so that you can whitelist a CDN version of jquery for example.

The way I envision it working, is that if the option is checked for "allow-current-domain JS" then anything under the domain `https://*.domain.com/*.js` is whitelisted for that page alone.

Why do this?:
Well, this allows users to browse things like facebook *but not* tracked by facebooks share buttons (or google analytics) on other sites. It also dissuades users from blanket white-listing domains to get basic functionality working on them (where certain scripts might get loaded on other domains). Or even just saving a huge klutzy config file.

If you think it's a good idea and you point me in the right direction I can start hacking around on a branch.

**Comment by jgkamat** [comment] 2018-12-17 23:02
Jan Harasym writes:

> Hi!
>
> I'm aware that there's an option for per-domain white-listing of specific settings (such as, in this case, enabling javascript)
>
> I'm hoping there's a trivial way to enable javascript for whatever site you currently have open.
> Ideally this would be paired with a white-list function too, so that you can whitelist a CDN version of jquery for example.
>
> The way I envision it working, is that if the option is checked for "allow-current-domain JS" then anything under the domain `https://*.domain.com/*.js` is whitelisted for that page alone.
>
> Why do this?:
> Well, this allows users to browse things like facebook *but not* tracked by facebooks share buttons (or google analytics) on other sites. It also dissuades users from blanket white-listing domains to get basic functionality working on them (where certain scripts might get loaded on other domains). Or even just saving a huge klutzy config file.
>
> If you think it's a good idea and you point me in the right direction I can start hacking around on a branch.

This sounds like a duplicate of #28. A simple setting to only allow
first-party js would not fix many instances of this, because many sites
depends on 3rd party js libraries (like jquery) to work at all. Sites like fb
pull js from fbcdn.net, not from the first party, so I don't think this would
work even for fb.

**Comment by The-Compiler** [comment] 2018-12-18 06:44
I agree, this is pretty much covered by #28 and #2626.

**Closed by The-Compiler** 2018-12-18 06:44 UTC
