### ISSUE TITLE
Don't store commands beginning with space in cmd-history

### ISSUE THREAD

**Issue by cippaciong** [qutebrowser/qutebrowser#3128] opened 2017-10-15 10:13 UTC
Hi, I have skimmed through the documentation and the issues list and didn't find anything related to this, I hope I didn't missed anything.
I think having a feature like the one described in the title would be a nice enhancement, something similar to what we have in bash history.
As an example:
`:open -t somewebsite.tld` would go into cmd-history.
`: open -t somewebsite.tld` would not.

**Comment by The-Compiler** [comment] 2017-10-15 10:14
Duplicate of #2865

**Closed by The-Compiler** 2017-10-15 10:14 UTC
