### ISSUE TITLE
"Port could not be cast to integer value" when using default binds to toggle JavaScript functionality at an IPv6 address.

### ISSUE THREAD

**Issue by n-ameless** [qutebrowser/qutebrowser#8357] opened 2024-10-24 21:46 UTC
**Version info**:
qutebrowser v3.3.1
Git commit: af835c26a-dirty on HEAD (2024-10-15 12:00:25 +0200)
Backend: QtWebEngine 6.7.3
  based on Chromium 118.0.5993.220
  with security patches up to 129.0.6668.58 (plus any distribution patches)
  (source: api)
Qt: 6.7.3

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When using the default binds to toggle JavaScript functionality (`tsh` and `tSh`), it fails and returns the following error.

`ERROR: Error while parsing *://300:ffb4:8643:34d8::f1fa:1/*: Invalid port: Port could not be cast to integer value as 'ffb4:8643:34d8::f1fa:1'`
![image](https://github.com/user-attachments/assets/5501594f-4da1-4e47-b987-82fa08b60e87)

When the command is manually issued via `:set -u http://[300:ffb4:8643:34d8::f1fa:1]/ content.javascript.enabled true`, it succeeds. It seems as though the URL is not being correctly parsed as the error is missing the brackets in the URL, and also cutting off the first set of bits in the address. This is a little problematic for users like myself who browse webpages on the Yggdrasil Network with JavaScript disabled by default.

**How to reproduce**
Access an IPv6 or Yggdrasil address, such as http://[300:ffb4:8643:34d8::f1fa:1]/ and try toggling JavaScript via the default `tsh` or `tSh` keybinds.

**Comment by The-Compiler** [comment] 2024-10-24 21:53
Duplicate of #4006

**Closed by The-Compiler** 2024-10-24 21:53 UTC
