### ISSUE TITLE
running a javascript bookmarklet on a page 

### ISSUE THREAD

**Issue by rpietro** [qutebrowser/qutebrowser#4390] opened 2018-10-28 19:42 UTC
I am using an app called lingq (language learning), and it provides an bookmarklet to import a page into the app. The bookmarklet points to `javascript:var%20lingq_base_url%20=%20%27http://www.lingq.com%27;(function()%7Bvar%20b=document.getElementsByTagName('head')[0],a=document.createElement('script');a.setAttribute('type','text/javascript');a.setAttribute('src',lingq_base_url+'/bookmarklet/js/bookmarklet.js');a.onload=function()%7Blingq_bookmarklet()%7D;b.appendChild(a)%7D)();`

This is a very basic question, but how can I run this bookmarklet on qutebrowser? Storing it as a quickmark won't do it.

**Comment by The-Compiler** [comment] 2018-10-29 10:37
Duplicate of #221

**Closed by The-Compiler** 2018-10-29 10:37 UTC
