### ISSUE TITLE
Completion view wastes pixels even when needed

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#3391] opened 2017-12-13 15:01 UTC
The attached photo explains; maybe also related to width calculation in issue #3359 and poll request #3389.

![untitled](https://user-images.githubusercontent.com/8865788/33945160-a4ce3d26-e037-11e7-9ffe-99423633a356.jpg)

**Comment by The-Compiler** [comment] 2017-12-13 15:05
Duplicate of #693.

**Closed by The-Compiler** 2017-12-13 15:05 UTC
