### ISSUE TITLE
Default action when clicking on download links?

### ISSUE THREAD

**Issue by kflak** [qutebrowser/qutebrowser#3837] opened 2018-04-13 15:11 UTC
First time poster here. Thanks a lot for the great browser! 
More of a feature request than a bug report: 
These days I am assessing a few hundred pdfs, and it would save me a bit of time if I could define a default action to be taken when clicking on a download link. Fx if pdf, then open in default pdf handler, instead of the prompt and extra ctrl-x click. For all I know this is already possible, but I haven't been able to find this option anywhere.

I'm on Arch Linux/i3wm.

**Comment by jgkamat** [comment] 2018-04-13 16:01
Duplicate of #3353.

This would be a killer feature though, I'd love to see it done (and I don't think it's _too_tough).

**Closed** 2018-04-13 16:04 UTC

**Comment by toofar** [comment] 2018-04-13 22:12
You might also be interested in this fascinating workaround: https://github.com/qutebrowser/qutebrowser/issues/3656#issuecomment-378989347

**Comment by kflak** [comment] 2018-04-14 12:07
@toofar: looks very interesting indeed! Will try to implement it when I have a little moment.
