### ISSUE TITLE
qutebrowser cannot handle IPv6 addresses in toggle commands

### ISSUE THREAD

**Issue by squeaktoy** [qutebrowser/qutebrowser#8115] opened 2024-03-01 23:33 UTC
**Version info**:
qutebrowser v3.1.0
Git commit: 
Backend: QtWebEngine 6.6.2, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.2

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
qutebrowser interprets ports wrongly on IPv6 addresses, which makes it impossible to use NoScript-like functionality on IPv6 sites.

**How to reproduce**
First `:open http://[2a00:1450:4009:826::200e]` (Google's IPv6 address) or any other IPv6 site that hosts HTTP.
Now try doing a toggle command like `tsh`.
You'll see an error like `Error while parsing *://2a00:1450:4009:826::200e/*: Invalid port. Port could not be cast to integer value as: '1450:4009:826::200e'`

**Comment by The-Compiler** [comment] 2024-03-01 23:52
Duplicate of #4006

**Closed by The-Compiler** 2024-03-01 23:52 UTC

**Comment by squeaktoy** [comment] 2024-03-02 00:14
I seem to be really bad at identifying duplicates, sorry :/
