### ISSUE TITLE
Tab-close shifts entire tab bar newly focused tab

### ISSUE THREAD

**Issue by alkim0** [qutebrowser/qutebrowser#7399] opened 2022-09-13 20:45 UTC
**Version info**:

qutebrowser v2.5.2
Git commit: 47ef2ca41 on panels (2022-08-29 20:03:37 +0200)
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.5 (compiled 5.15.4)

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
Upon closing a tab, the entire tabbar shifts such that the new focus is at the bottom.

As a side note, the same seems to happen when moving between while the tabs are still loading; the tabbar seems to move such that the tab we moved to is at the bottom.

When I looked through the code, this seems to be something that the upstream tabbar implementation from QT is doing. Another benefit to writing a custom tabbar #5308.

**How to reproduce**

Make sure tabbar position is on the left. Open about 80 pages or so, and try deleting the 70th tab.

I've attached a video. Here, I keep deleting the tab below the google tab, and the tabbar keeps shifting such that the newly focused tab is at the bottom of the tabbar.

https://user-images.githubusercontent.com/9775404/190004931-b4412421-7bf5-4040-8c84-4a9071a5352e.mp4

**Comment by toofar** [comment] 2022-09-13 21:36
Duplicate of https://github.com/qutebrowser/qutebrowser/issues/3579 (see also https://bugreports.qt.io/browse/QTBUG-45381)

**Closed by toofar** 2022-09-13 21:36 UTC
