### ISSUE TITLE
I used for Microsoft Office online also onlyoffice online, can not print or show print preview.

### ISSUE THREAD

**Issue by WINGALA** [qutebrowser/qutebrowser#6248] opened 2021-03-10 09:24 UTC
**Version info**:

The qutebrowser version :qutebrowser-2.0.2.post1-windows-standalone-amd64 or installation version.
**Does the bug happen if you start with `--temp-basedir`?**:
I tried almost all of the setting in config.yml, but still no any change for fix this problem.
**Description**
I used your qutebrowser for Microsoft Office online(office online also have their own print feather), I tried open a word or excel document for print, but can not print, (only can use ctrl+alt+P to print whole page, just like webpage print or save to *.pdf type to local disk,but I don't want this, I want just print that word/excel/ppt document just like office desktop version,but can not.)
This is the office online link: 
https://office.live.com/start/word.aspx
how to set for windows version qutebrowser? can not print and show print preview. Please help, thanks a lot.
![qutebrowser](https://user-images.githubusercontent.com/69828334/110606684-62bc9a80-81c5-11eb-9d20-452cedab14e2.jpg)

**How to reproduce**

https://office.live.com/start/word.aspx

**Comment by WINGALA** [comment] 2021-03-10 09:29
After click print button, Just show"All done. Your file is ready to print" then not show any printer option window,then just can click "open PDF". I just want directly to printing this document.
Bye the way, your browser is pretty awesome for Office online, but unfortunately can not print.

**Comment by The-Compiler** [comment] 2021-03-10 15:05
Does the "Open PDF" button work for you, or do you get an error when you use it?

**Comment by WINGALA** [comment] 2021-03-11 01:02
> Does the "Open PDF" button work for you, or do you get an error when you use it?

Yes, this feature actually is working. but in google chrome or another browser, before show open PDF window, will show a printer option windows also. but this browser not show.

**Comment by The-Compiler** [comment] 2021-03-12 12:28
WIth Firefox, the same happens. I think it's the website checking whether it's Chrome and doing something different. Maybe we can trick it into thinking that it's Chrome, but I haven't tried yet. If not, there's probably nothing qutebrowser can do.

The "The server does not have the requested data" error is probably this QtWebEngine bug: [[QTBUG-78114] [REG 5.13] PDF files are downloaded twice - can't download project euclid files](https://bugreports.qt.io/browse/QTBUG-78114)

**Comment by WINGALA** [comment] 2021-03-15 01:33
Anyway, thanks for your help, have a good day.

**Comment by The-Compiler** [comment] 2021-03-15 17:51
Okay, so what the page actually does is using Chrome's PDF viewer (PDFium) to show the preview and trigger a print of the PDF.

There are a couple of steps needed to make this work:

- qutebrowser needs to enable PDFium, see [PDFium support · Issue #4911 · qutebrowser/qutebrowser](https://github.com/qutebrowser/qutebrowser/issues/4911) for that.
- Qt needs some fixes to actually make it display the PDF - those will be in the upcoming QtWebEngine 5.15.4: [Show PDF viewer in a guest view (Ib1591fbd) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/332797/8)
- Qt needs a fix to actually make the printing work - there's an [abandoned change](https://codereview.qt-project.org/c/qt/qtwebengine/+/283632) for that. I asked to clarify what the current state is.

The download error is indeed caused by the above Qt bug, which should be fixed with QtWebEngine 5.15.4 as well.

So other than #4911 I don't think there's anything qutebrowser can do here.

**Closed by The-Compiler** 2021-03-15 17:51 UTC
Labels: bug: behavior, priority: 2 - low
