### ISSUE TITLE
"Screwed up rendering" of web content

### ISSUE THREAD

**Issue by MrPixelized** [qutebrowser/qutebrowser#7899] opened 2023-09-08 10:00 UTC
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.1.6-arch1.4
Platform: Linux-6.5.1-arch1-1-x86_64-with-glibc2.38, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
On a multi-monitor wayland setup with fractional scaling, rendering is "a bit wacky". The issue happens on any monitor (even those without scaling) but gets much worse when the window is moved between windows with different scaling settings.

![It looks as follows](https://github.com/qutebrowser/qutebrowser/assets/13382482/e9016fe3-f1c7-4788-b9c5-cb0388d1601c)

Sometimes the problem doesn't occur for some specific websites temporarily.

UI elements seem to be fine, it is just web content (so perhaps not a QB issue..?).

**How to reproduce**
I'm uncertain. This issue happens uniquely for me when:
- Using a monitor with DPI scaling on Wayland
- Using QT 6
- Using Qutebrowser (other Chromium-based browsers and all other QT applications I have tried are fine)

And is exacerbated when
- Moving a qutebrowser window between monitors with different scaling settings

**Attempted mitigations**
I've removed the `~/.cache/qutebrowser` and `~/.local/share/qutebrowser/webengine` directories to no avail. I've also tried my setup without fractional scaling, which mitigates the issue somewhat but makes it impossible to do any actual work on my computer.

**Comment by MrPixelized** [comment] 2023-09-08 10:04
Native UI elements such as dropdowns also render incorrectly, at the wrong location and scale, right after the QB window has been moved between monitors and sometimes consistently (oxymoron, yes) on a monitor with fractional scaling. This is sometimes but not always fixed by resizing the QB window.

**Comment by The-Compiler** [comment] 2023-09-08 15:43
This sounds similar to #7857 and most likely isn't an issue specific to qutebrowser (or anything qutebrowser could fix). Do you also see things improving if you move the mouse pointer to the other monitor?

**Comment by MrPixelized** [comment] 2023-09-08 22:32
Hi! Moving the mouse between monitors/qutebrowser windows has no effect. I think this effect is likely to be specific to the compositor in use.

I wasn't really expecting this to be anything qutebrowser could fix, but it seemed the most accessible place for me to share this problem. If you'd like to wait out the QT 6.6 release before taking any further action I completely understand.

Would you like me to get back to you when that release ends up on my system? Anything else you'd like to know?

**Comment by ahesford** [comment] 2023-12-08 14:41
I was just bitten by this with wlroots 0.17 and a fresh build of the master branch of labwc, which together support the new `fractional-scale-v1` Wayland protocol. This is definitely a Qt6 problem, because running qutebrowser with `--temp-basedir` and `--qt-wrapper PyQt5` produces a cleanly rendered window. (See image below for a comparison: Qt6 at left, Qt5 at right.) On the currently released labwc 0.6.6 and wlroots 0.16 (neither of which support the `fractional-scale-v1` protocol), qutebrowser with PyQt6 renders just fine even on displays where I've set a non-integer scale for the display.

The [simple test browser](https://raw.githubusercontent.com/qutebrowser/qutebrowser/main/scripts/testbrowser/testbrowser_webengine.py) shows similarly bad rendering. Other Qt6 applications, like QtCreator, matplotlib with the PyQt6 backend, and an internal Qt6 application render just fine. The issue must be related to webengine views.

![qb-qt5v6](https://github.com/qutebrowser/qutebrowser/assets/48421688/40deaab6-2ce8-4f04-8a52-4f3324e8018d)

**Comment by The-Compiler** [comment] 2023-12-09 18:55
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can easily reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

@MrPixelized so if you can still reproduce this on Qt 6.6.1, I'd suggest to report this there.

**Closed by The-Compiler** 2023-12-09 18:55 UTC
Labels: status: needs triage

**Comment by ahesford** [comment] 2023-12-11 18:37
Although this isn't a qutebrowser bug, I would like to note here for those affected that setting the environment variable `QT_SCALE_FACTOR_ROUNDING_POLICY=round` will cause Qt6 to revert to Qt5-style behavior, and content will render smoothly in webengine views.
