### ISSUE TITLE
Showing fewer hints for duplicate links that are next to each other

### ISSUE THREAD

**Issue by nadrad** [qutebrowser/qutebrowser#8304] opened 2024-09-14 06:41 UTC
On many pages, such as typical search results or LinkedIn feeds, there are multiple elements next to each other that are hyperlinked to the same target. Qutebrowser displays different hints for these, sometimes resulting in too many hints. It can be great to have a setting for the minimum distance between duplicate links, so that if they are within that range, only one hint is shown for the first one.

**Comment by The-Compiler** [comment] 2024-09-14 08:27
Duplicate of #71

**Closed by The-Compiler** 2024-09-14 08:27 UTC
