### ISSUE TITLE
Handle newlines in a pasted URL differently

### ISSUE THREAD

**Issue by wasamasa** [qutebrowser/qutebrowser#7050] opened 2022-03-03 19:56 UTC
I sometimes open long URLs by selecting them in the terminal and copying them into the browser. Due to their length, the URLs are hardwrapped and contain at one newline followed by optional space. Chromium and qutebrowser disagree how to handle these:

- When pasting the URL into Chromium, it removes every newline followed by optional space, essentially turning the hardwrapped URL into the original version. Opening that URL performs as expected.
- When pasting the URL into qutebrowser, seemingly no post-processing is done, be it into an `:open` prompt or with the `p` or `P` command. The newlines are interpreted as URL separator, thereby opening each newline-separated part in a new tab. This is only what we want if there isn't one URL to be opened, but several newline-separated URLs.

Is there merit to this special casing of newlines? If yes, can it be worked around somehow? The obvious workaround on the side of the terminal is to use a program like `urlview`, on qutebrowser's side the `p` and `P` commands could be replaced with a wrapper...

**Comment by toofar** [comment] 2023-12-17 03:08
I'm going to close this as a duplicate of #7685 as that one has slightly more words in it. Sorry, I know you raised it first!

**Closed** 2023-12-17 03:08 UTC
