### ISSUE TITLE
XDG Magnet Links

### ISSUE THREAD

**Issue by reedjosh** [qutebrowser/qutebrowser#3272] opened 2017-11-11 23:42 UTC
When opening magnet links, following hinting, qutebrowser doesn't redirect to xdg-mime, but instead tries to navigate to the magnet link as a url in a new tab.

When opening magnet links via click qutebrowser appropriately launches my magnet mime type application.

Is this the intended behavior? I would not be surprised if I was simply missing some idea or something. 

Thanks for considering my issue, and thanks again for such an awesome browser!

Version Info:
```
qutebrowser v1.0.3
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.3
Qt: 5.9.2
PyQt: 5.9.1

sip: 4.19.5
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.21.0
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: QFusionStyle
Platform: Linux-4.13.11-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/jreed/.cache/qutebrowser
config: /home/jreed/.config/qutebrowser
data: /home/jreed/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```

Also, I'm running arch linux with Sway wm. Please let me know if you need any further information.

**Comment by jgkamat** [comment] 2017-11-12 02:33
This is a duplicate of https://github.com/qutebrowser/qutebrowser/issues/2833

**Comment by reedjosh** [comment] 2017-11-12 02:53
Ah, suppose it kinda is. Well, I'd be happy to follow that issue instead. Either way, just let me know if you need anything from me.

I'm not entirely sure I understand the comments and such in the other issue. I'll do some more research of my own in the meantime.

Thanks!

**Comment by jgkamat** [comment] 2017-11-12 02:54
I'm not entirely sure if/how this is possible, because I haven't looked at the link code yet. It might be that the hints just emulate mouse clicks (in which case this would be hard), but this would be a very nice feature to have. I would reccomend the `:spawn` workaround detailed in the other issue for now!

**Comment by reedjosh** [comment] 2017-11-12 02:55
Haha, meh. I'll just click. 

That's a creative workaround though. : )

**Comment by The-Compiler** [comment] 2017-11-12 11:32
Duplicate of #2833

**Closed by The-Compiler** 2017-11-12 11:32 UTC
