### ISSUE TITLE
Sometimes after opening page in new tab page half of window become blank

### ISSUE THREAD

**Issue by ciechomke** [qutebrowser/qutebrowser#3954] opened 2018-05-28 15:26 UTC
Sometimes when I open new page it splits into half and the rest of the screen is blank
Image explains issue very well: https://imgur.com/a/W6uj4Nc
```
qutebrowser v1.3.0
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.12-2-ck-sandybridge-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Comment by The-Compiler** [comment] 2018-05-28 15:29
Duplicate of #3920

**Closed by The-Compiler** 2018-05-28 15:29 UTC
