### ISSUE TITLE
Jumps to top of page after saving media item

### ISSUE THREAD

**Issue by pzant** [qutebrowser/qutebrowser#7910] opened 2023-09-12 13:10 UTC
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
After saving some element, the browser automatically scroll the page to the beginning.

**Comment by The-Compiler** [comment] 2023-09-12 13:44
You'll need to be more specific. What exactly do you mean with "after saving some element"?

**Comment by pzant** [comment] 2023-09-13 20:09
Any file, video, picture or page.

**Comment by The-Compiler** [comment] 2023-09-13 20:35
It's still difficult to understand what precisely you mean with so little detail, but I'm assuming this is a duplicate of #7885.

**Closed by The-Compiler** 2023-09-13 20:35 UTC
Labels: status: can't reproduce, status: needs triage
