### ISSUE TITLE
`:repeat 30 scroll down` only scrolls a single time on macOS?

### ISSUE THREAD

**Issue by Gira-X** [qutebrowser/qutebrowser#6280] opened 2021-03-14 20:00 UTC
**Version info**:
```
qutebrowser v2.1.0
Git commit: f75032d76 on v2.1.x (2021-03-12 13:32:32 +0100)
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.3

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.4.1
adblock: 0.4.2
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.3
PyQt5.QtWebKitWidgets: no
pdf.js: 2.6.347 (bundled)
sqlite: 3.33.0
QtNetwork SSL: Secure Transport, macOS High Sierra (10.13)

Style: QMacStyle
Platform plugin: cocoa
OpenGL: None
Platform: macOS-10.13.6-x86_64-i386-64bit, 64bit
Frozen: True
Imported from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Using Python from /Applications/qutebrowser.app/Contents/MacOS/qutebrowser
Qt library executable path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt/libexec, data path: /Applications/qutebrowser.app/Contents/MacOS/PyQt5/Qt
OS Version: 10.13.6, x86_64

Paths:
cache: /var/folders/mq/dnp2729x3wd3p22mwm7yhsdc0000gn/T/qutebrowser-basedir-a7_lvxs_/cache
config: /var/folders/mq/dnp2729x3wd3p22mwm7yhsdc0000gn/T/qutebrowser-basedir-a7_lvxs_/config
data: /var/folders/mq/dnp2729x3wd3p22mwm7yhsdc0000gn/T/qutebrowser-basedir-a7_lvxs_/data
runtime: /private/var/folders/mq/dnp2729x3wd3p22mwm7yhsdc0000gn/T/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:54
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
I found this while playing around with repeating scroll commands.

It only scrolls down a single time, not multiple times as requested.

Maybe it can be documented somewhere or fixed?

**Comment by The-Compiler** [comment] 2021-03-14 20:12
Are you sure you can reproduce this with the default settings? I can only reproduce with scolling.smooth enabled.

**Comment by Gira-X** [comment] 2021-03-14 20:17
> Are you sure you can reproduce this with the default settings? I can only reproduce with scolling.smooth enabled.

Ah, you are right, sorry.

I used a little amount when testing and there it looked that it does not work, but it indeed works!

So yes, only when smooth-scrolling is enabled, this does not work.

**Comment by The-Compiler** [comment] 2021-03-14 20:20
Duplicate of #6085

**Closed by The-Compiler** 2021-03-14 20:20 UTC
