### ISSUE TITLE
[MacOS]Yabai can't control qutebrowser, when window_hide_decoration = true.

### ISSUE THREAD

**Issue by command-z-z** [qutebrowser/qutebrowser#7563] opened 2023-01-25 08:34 UTC
**Version info**:
qutebrowser v2.5.2
Git commit: 951a14a66 on HEAD (2022-06-22 15:30:51 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.10.4
PyQt: 5.15.6
OS Version: 10.16, x86_64
Yabai Version: 5.0.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
when I set window_hide_decoration = true, my qutebrowser can't control by my yabai. however I type any shortcut, the qutebrowser can't get response(but can normally search in qutebrowser).

I set yabai -m config window_border  on, but i also see a board in it.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71259900/214515705-2469dcb8-c1e6-4bea-8b71-93a60592df78.png">

**How to reproduce**
use yabai wm.
only set window_hide_decoration = true.

**Comment by The-Compiler** [comment] 2023-01-25 08:52
Duplicate of #4067

**Closed by The-Compiler** 2023-01-25 08:52 UTC
