### ISSUE TITLE
Improve gg and G bindings behavior to consider search pointer

### ISSUE THREAD

**Issue by UnkwUsr** [qutebrowser/qutebrowser#6492] opened 2021-05-30 18:17 UTC
When I do search, I expect that pressing `gg` will move the search pointer to the top of the page, so the next press of `n` should go to the first search result, but it doesn't and searching just continuing from last search result (before pressing `gg`).

**Comment by The-Compiler** [comment] 2021-05-30 18:23
Duplicate of #1222

**Closed by The-Compiler** 2021-05-30 18:23 UTC
