### ISSUE TITLE
When statusbar is hidden, showing then hiding the statusbar causes some websites to scroll to the top

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#2236] opened 2017-01-14 18:45 UTC
qutebrowser v0.9.1
Git commit: v0.8.0-2079-g590586e94 (2017-01-13 17:51:45 +0000)
Backend: webengine
I also have the tabbar set to never show.

For example, www.reddit.com, www.github.com and www.theguardian.com.
However, it doesn't do this on [store.steampowered.com](http://store.steampowered.com).

Steps to reproduce:

 - Run `:set ui hide-statusbar true`
 - Scroll down the page
 - Press `:`
 - Press `<Escape>`
 - It then scrolls to the top of the page.

EDIT: It doesn't do this when tabs are shown and statusbar is hidden.

EDIT2: It may also be related to this issue, that opening the download prompt on [this page](https://tabs.ultimate-guitar.com/m/misc_computer_games/silent_hill_-_waiting_for_you_guitar_pro.htm) and then closing it makes the page scroll to the top. This is with the statusbar not being hidden.

EDIT3: On [this page](https://stackoverflow.com/questions/426230/what-is-the-ld-preload-trick), the top search bar gets selected.

**Comment by The-Compiler** [comment] 2017-01-14 18:46
Come on, please be a bit more verbose in your issues... "some websites"?

**Comment by pkill-nine** [comment] 2017-01-14 18:52
@The-Compiler I updated it :P

**Comment by The-Compiler** [comment] 2017-01-14 20:16
Thanks. I can reproduce this, though while *hiding* it. I'm guessing you're seeing the same.

**Comment by pkill-nine** [comment] 2017-01-14 20:58
@The-Compiler What I mean is, with `:set ui hide-statusbar true`, while halfway down the page, I press `:` and then press `<Escape>`, it then scrolls to the top of the page.

**Comment by Midek** [comment] 2017-05-15 09:01
I think i noticed same behavior, exept that when i have both statusbar and tabs hidden, as soon as i open console (set-cmd-text -s :open  etc ) i get scrolled to the top on sites mentioned in the first post.

**Comment by The-Compiler** [comment] 2017-05-16 05:58
Note it focuses some kind of "Jump to content" link on GitHub and Reddit. Not sure why this is happening though...

**Comment by pkillnine** [comment] 2017-06-13 15:27
A couple observations that I've noticed related to this issue:

- Opening the download prompt on [this page](https://tabs.ultimate-guitar.com/m/misc_computer_games/silent_hill_-_waiting_for_you_guitar_pro.htm) and then closing it makes the page scroll to the top. This is with the statusbar not being hidden.

- On [this page](https://stackoverflow.com/questions/426230/what-is-the-ld-preload-trick), the top search bar gets selected when showing then hiding the statusbar.

**Comment by The-Compiler** [comment] 2017-06-14 08:42
I can't reproduce any of this (even from the original report) with Qt 5.9 - can you?

**Comment by pkillnine** [comment] 2017-06-14 09:08
I can't reproduce it on the Qutebrowser master branch, so I guess it's my custom fork causing the issue

**Comment by Midek** [comment] 2017-06-14 09:37
I am still encountering this error.
I am on Arch GNU/Linux with qt5 version qt5-base 5.9.0-2 and qutebrowser both installed from repository and git version:
qutebrowser v0.10.1
Git commit: v0.10.0-824-g2ffb10bad (2017-06-14 10:44:11 +0200)

**Comment by pevu** [comment] 2017-10-19 11:40
Chromium-browser has the same issue. When you open [lipsum.com](https://www.lipsum.com/), scroll down, then focus the location bar (url box), then press Tab, it will jump to the top of the page and focus the first link.

It seems to be an issue of how the view containing the website is focused when all qutebrowser ui elements disappear.

**Comment by Arriveus** [comment] 2019-12-18 00:49
I am still experiencing this error
qutebrowser v1.8.3
Backend: QtWebEngine (Chromium 73.0.3683.105)

you can trigger it also by:

- opening a new tab, and then moving back
- **passing :nop command**

Are there known workarounds?

**Comment by The-Compiler** [comment] 2019-12-18 10:35
@Arriveus What Qt version?

**Comment by sudo-nice** [comment] 2019-12-18 15:14
> - opening a new tab, and then moving back
> - passing :nop command

Happens for me too.

```
qutebrowser v1.8.3
Git commit:
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.3
Qt: 5.11.3
PyQt: 5.11.3
```

**Comment by Arriveus** [comment] 2019-12-18 16:46
@The-Compiler Qt: 5.13.2

**Comment by The-Compiler** [comment] 2019-12-18 18:04
> Are there known workarounds?

Other than not hiding the statusbar, no.

**Comment by Arriveus** [comment] 2020-02-10 19:18
Thank you for the answer and sorry for the late response.

**Comment by ml-** [comment] 2020-02-29 21:42
Just ran into this. Happens with `statusbar.hide true` on the `qute://settings/` page.

**Steps to reproduce:**
1. `qutebrowser -T`
1. Open `qute://settings/`
1. `:set statusbar.hide true`
1. Press `:` or `ss`. Basically anything that shows the `statusbar` again.
1. Press Escape to close it again
1. The first text input field (value of `aliases`) should be focused now.

I did that twice with with `statusbar.hide` `true` and `false` with debug logs and removed all unique values like timestamps, addresses and durations.

Log starting with `ss` keypresses and goes until hitting Escape.
The (focus) order at the end might be interesting.

The diff: https://gist.github.com/ml-/3bc973a6924dcf32544d9075dc3bc3d1/revisions#diff-5610317951f09d34db39df5785407daf

**Comment by jelinekto** [comment] 2020-07-10 23:22
I've been working around this issue by forcing setting `statusbar.show` to `always` temporarily via key bindings.

For example, a snippet from my `config.py`:
```
config.bind('o', 'set statusbar.show always;; set-cmd-text -s :open')
config.bind('O', 'set statusbar.show always;; set-cmd-text -s :open -t')
config.bind(':', 'set statusbar.show always;; set-cmd-text :')
config.bind('<Escape>', 'enter-mode normal;; set statusbar.show in-mode', mode='command')
config.bind('<Return>', 'command-accept;; set statusbar.show in-mode', mode='command')
```

Perhaps this is something that could be done by default.

**Comment by codeclem** [comment] 2020-07-28 16:14
> I've been working around this issue by forcing setting `statusbar.show` to `always` temporarily via key bindings.
> 
> For example, a snippet from my `config.py`:
> 
> ```
> config.bind('o', 'set statusbar.show always;; set-cmd-text -s :open')
> config.bind('O', 'set statusbar.show always;; set-cmd-text -s :open -t')
> config.bind(':', 'set statusbar.show always;; set-cmd-text :')
> config.bind('<Escape>', 'enter-mode normal;; set statusbar.show in-mode', mode='command')
> config.bind('<Return>', 'command-accept;; set statusbar.show in-mode', mode='command')
> ```
> 
> Perhaps this is something that could be done by default.

There's a slight delay when the statusbar returns to in-mode as the bottom part of the page gets redraw, during which time you can't scroll or hint, or do much of anything, but that's a good enough workaround for me. Thank you!

**Comment by codeclem** [comment] 2020-07-28 16:54
I just realized that its only status bars that take input that trigger this bug. For example the "--- INSERT MODE ---" message bar, or the "Follow hint..." bar don't do this. So there must be a difference between how the widgets are drawn.

**Comment by The-Compiler** [comment] 2020-07-28 16:58
It's probably something happening in QtWebEngine (perhaps connected to #4579) when the page loses keyboard focus (due to a status bar with input) and gains it again.

**Comment by michaelskyba** [comment] 2021-06-30 16:16
> I've been working around this issue by forcing setting `statusbar.show` to `always` temporarily via key bindings.
> 
> For example, a snippet from my `config.py`:
> 
> ```
> config.bind('o', 'set statusbar.show always;; set-cmd-text -s :open')
> config.bind('O', 'set statusbar.show always;; set-cmd-text -s :open -t')
> config.bind(':', 'set statusbar.show always;; set-cmd-text :')
> config.bind('<Escape>', 'enter-mode normal;; set statusbar.show in-mode', mode='command')
> config.bind('<Return>', 'command-accept;; set statusbar.show in-mode', mode='command')
> ```
> 
> Perhaps this is something that could be done by default.

Additionally, you can set ``config.bind('/', 'set statusbar.show always;; set-cmd-text /')`` for searching.

**Comment by kiil** [comment] 2021-08-20 12:02
This happens on drupal-based sites too

**Comment by Pound-Hash** [comment] 2022-10-17 06:47
I've found that the problem is compounded when setting `search.incremental` to `off`. Then, the page jumps to the top after doing a search and hitting enter, but there's no indication saying "skip to content" at the top, which was confusing me until now. I suppose its best to keep the statusbar always on, for now.

**Closed** 2023-12-08 14:16 UTC
Labels: component: ui, priority: 1 - middle, bug: behavior
