### ISSUE TITLE
Search fields that change url exit insert mode

### ISSUE THREAD

**Issue by rcorre** [qutebrowser/qutebrowser#4312] opened 2018-10-07 16:42 UTC
**Version info (see `:version`)**:

```
  Error: No such file or directory
qutebrowser v1.5.0
Git commit:
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.25.2
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.10-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/rcorre/.cache/qutebrowser
config: /home/rcorre/.config/qutebrowser
data: /home/rcorre/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
```

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):

Yes.

**Description**

Certain sites modify the url (possibly reload the page?) every time you input a character into a search field. This makes typing a search term very difficult, as you have to press `i` before every letter.

**How to reproduce**

1. Visit https://codereview.qt-project.org/#/admin/projects/
2. Select the search bar, note that insert mode is entered
3. Enter a letter
4. The url changes and insert mode is cancelled

**Comment by rcorre** [comment] 2018-10-07 16:43
Right now I work around by adding a `searchengine` for every affected site that I frequent.

**Comment by The-Compiler** [comment] 2018-10-07 16:53
Duplicate of #3596

**Comment by The-Compiler** [comment] 2018-10-07 16:54
Also, you were the first one to try the issue templates I just added :wink: Feedback welcome!

**Closed by The-Compiler** 2018-10-07 16:53 UTC

**Comment by rcorre** [comment] 2018-10-07 19:57
Cool! It seemed pretty straightforward, gave me four options, and the bug report template doesn't go over-the-top asking you too many questions.
