### ISSUE TITLE
Renderer process crash on forum.prusa3d.com

### ISSUE THREAD

**Issue by Teteros** [qutebrowser/qutebrowser#7204] opened 2022-05-27 12:34 UTC
**Version info**:
qutebrowser v2.5.1
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
PyQt5.QtWebEngine: 5.15.5
Qt: 5.15.4 (compiled 5.15.2)
[Full --version](http://sprunge.us/P8FTPN)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**How to reproduce**
- `qutebrowser -T --debug "https://forum.prusa3d.com"`
- accept the cookie/privacy dialog prompt
- click any forum leading link, e.g. a category
- `Renderer process crashed (status 133)` on that tab, other tabs keep running fine
- Just going from that point on https://forum.prusa3d.com will crash, no need to even click anything then

**Last few lines of --debug**
```
13:29:06 DEBUG    webview    browsertab:_set_load_status:1008 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://forum.prusa3d.com/forum/english-forum-general-discussion-announcements-and-releases/'>: LoadStatus.error
13:29:06 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.error: 4>) (tab 0)
13:29:06 DEBUG    misc       eventfilter:eventFilter:53 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7fd4b4192320> got new child <PyQt5.QtWidgets.QWidget object at 0x7fd4b545c310>, installing filter
13:29:06 DEBUG    webview    browsertab:_on_navigation_request:1066 navigation request: url data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf…, type Type.typed, is_main_frame True
13:29:06 ERROR    webview    tabbedbrowser:show_error_page:968 Renderer process crashed (status 133)
```

**Comment by The-Compiler** [comment] 2022-05-27 12:35
Duplicate of #7118

**Closed** 2022-05-27 12:35 UTC
