### ISSUE TITLE
Feature request: Focused tab alignment

### ISSUE THREAD

**Issue by Mrnoname1000** [qutebrowser/qutebrowser#4946] opened 2019-08-01 03:47 UTC
It would be nice to set where a focused tab is aligned on-screen. Currently whenever there are too many tabs to fit on-screen, the focused tab is forced to the right side of the screen whenever tabs are closed or reordered, but not when changing focus. This makes navigating 30+ tabs very difficult because movement is inconsistent.
An option to align the focused tab to the left, center, or right of the screen when possible would be very helpful for managing large numbers of tabs.

**Comment by jgkamat** [comment] 2019-08-01 04:50
Mrnoname1000 writes:

> It would be nice to set where a focused tab is aligned on-screen. Currently 
> whenever there are too many tabs to fit on-screen, the focused tab is forced 
> to the right side of the screen whenever tabs are closed or reordered, but 
> not when changing focus. This makes navigating 30+ tabs very difficult 
> because movement is inconsistent.

Seems like a duplicate of #3579

**Closed** 2019-08-01 06:40 UTC

**Comment by Mrnoname1000** [comment] 2019-08-01 07:22
I don't know if it's a duplicate, but a different means to the same end. That issue suggests scrolling the tab bar only when trying to switch to a tab past the edge of the screen. I suggest scrolling the tab bar on every tab switch except where the tab can't be aligned to the specified part of the screen. This would also help telegraph relative tab location, since if the tab bar doesn't scroll, you know the now-focused tab is near the beginning or end. A further extension to this could be to align the focused tab based on its relative location in the tab bar, i.e. tab position / tab bar width * screen width.
Whether or not scrolling behaviour is inconsistent, I suggest that the focused tab be aligned based on a definable setting. Saving the tab position can be handled by the other issue.

**Comment by jgkamat** [comment] 2019-08-01 16:40
Mrnoname1000 writes:

> I suggest scrolling the tab bar on every tab switch except where the tab
> can't be aligned to the specified part of the screen.

I don't think we can set the scroll position at all, because doing so would 
cause twitching due to the qt bug mentioned in the issue.
