### ISSUE TITLE
History including all URL changes(like payloads e.g. ?payload="string")

### ISSUE THREAD

**Issue by SurmanPP** [qutebrowser/qutebrowser#7271] opened 2022-06-18 21:30 UTC
Why?
Because it would allow to continue where you left off, when using pwa's as an example

**Comment by The-Compiler** [comment] 2022-06-18 22:45
I have no idea what you're asking. The history does contain the full URL.

**Comment by SurmanPP** [comment] 2022-06-19 15:59
Oh yeah, sorry for my stupidity.

I changed the title.

**Comment by The-Compiler** [comment] 2022-06-19 16:00
I still don't follow. Do you have a concrete example?

**Comment by SurmanPP** [comment] 2022-06-19 16:03
Edited the title again. What I mean is for example being on the same site like "example.com/something?x=1" but now x changes and "example.com/something?x=2" is also saved in history.

**Comment by The-Compiler** [comment] 2022-06-19 16:08
It is. Given there's still no *concrete* example, I'm just going to assume this is a duplicate of #5012.

**Closed** 2022-06-19 16:08 UTC
Labels: status: can't reproduce, status: needs triage
