### ISSUE TITLE
User-configurable constant hints for certain HTML IDs 

### ISSUE THREAD

**Issue by JadElClemens** [qutebrowser/qutebrowser#4708] opened 2019-04-11 09:07 UTC
It would be useful if we could configure elements based on HTML ID to constantly map to a given hint selector, e.g. I could configure hinting so that "h" on youtube.com* would always point towards the YouTube icon that leads to the homepage (assuming that it has an HTML ID).

**Comment by The-Compiler** [comment] 2019-04-11 09:09
Duplicate of #674

**Closed by The-Compiler** 2019-04-11 09:09 UTC

**Comment by jgkamat** [comment] 2019-04-11 15:35
Also somewhat related: if you switch to number mode, it should be trivial to
add hinting in number mode by typing the id after https://github.com/qutebrowser/qutebrowser/pull/4639
