### ISSUE TITLE
Google Inbox messages can't be opened with "f"

### ISSUE THREAD

**Issue by krzemian** [qutebrowser/qutebrowser#3300] opened 2017-11-16 16:01 UTC
Steps:
1. Go to http://inbox.google.com
2. Type "f" to enter the link mode
3. Messages can't be opened as there's no keyboard shortcut assigned over the subject/header of the message in the mailbox

Using qutebrowser v1.0.3

**Comment by jgkamat** [comment] 2017-11-16 16:33
Like the preivous example, I don't think these messages are actual html elements (probably not html, since the site breaks without javascript), so I don't know if this is possible. I've tried a couple different vim plugins on inbox and I don't think any of them have worked work.

Inbox has it's own shortcuts though, so you can use passthrough or insert mode to use those instead.

**Comment by The-Compiler** [comment] 2017-11-16 19:39
Duplicate of #178

**Closed by The-Compiler** 2017-11-16 19:39 UTC
