### ISSUE TITLE
Qutebrowser automatically goes into edit mode with auto-insert-mode set to false

### ISSUE THREAD

**Issue by B0073D** [qutebrowser/qutebrowser#793] opened 2015-06-29 06:53 UTC
When using IRCCloud (and some other things) selecting a different channel (ie, using a hint to 'click' something) takes me into insert mode.

I would expect to have to enter insert mode manually with the above selected, except if I am directly selecting an input field with a hint.

**Comment by The-Compiler** [comment] 2015-07-03 06:46
You mentioned in IRC that you can do a small minimal example which doesn't require an IRCCloud account - any update on that? :smile:

**Comment by B0073D** [comment] 2015-07-03 06:48
Apologies, I was going to write one up for you. I haven't gotten to it yet.

On Fri, Jul 3, 2015 at 4:46 PM, Florian Bruhin <notifications@github.com>
wrote:

> You mentioned in IRC that you can do a small minimal example which doesn't
> require an IRCCloud account - any update on that? [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/The-Compiler/qutebrowser/issues/793#issuecomment-118252726>
> .
>



-- 
Sincerely,

Tim Suess

**Comment by B0073D** [comment] 2015-07-03 07:00
Alright, here's an example. When you click 'click here' it brings the field into focus and enters edit mode. This is essentially what is happening in IRC cloud except it does a couple of other things first.

``` html
<html>
        <head>
                <title>Cursor Focus Test</title>
        </head>
        <body>
                <span onClick="document.getElementById('ClickTest').focus()">Click Me</span>
                <input type="text" id="ClickTest" />
        </body>
</html>
```

In my view, I should not be entering insert mode unless I directly hint into the field. Thoughts?

**Comment by The-Compiler** [comment] 2015-07-03 07:41
Hrm, I see. I can't reproduce it, but I see how it can happen.

With the [current code](https://github.com/The-Compiler/qutebrowser/blob/master/qutebrowser/browser/webview.py#L239-L284) we try to find out immediately what was clicked - however, sometimes Qt tells us that no element has been clicked. In that case, we wait until the mouse is *released* and then check what element is focused using `webelem.focus_element(...)`.

It seems like in your case, this happens and at the point the mouse is released, there's an input field focused, causing qutebrowser to enter insert mode.

Can you confirm qutebrowser enters the mode when you *release* the mouse, and not yet when you *press* it?

Unfortunately I don't know a good solution for this... Removing the workaround would mean things break in some other cases.

**Comment by B0073D** [comment] 2015-07-03 11:26
Sorry this is all done using hinting. I do not use the mouse when this happens.

**Comment by The-Compiler** [comment] 2015-07-03 11:28
There's no difference - hinting sends a fake mouse click to Qt

**Comment by The-Compiler** [comment] 2017-03-27 07:59
@B0073D There were some changes around insert mode checking recently - can you check if this still happens please?

**Comment by B0073D** [comment] 2017-03-28 22:09
Which engine?

**Comment by The-Compiler** [comment] 2017-03-29 04:24
Both, ideally.

**Comment by B0073D** [comment] 2017-04-19 07:08
Tested with qtwebengine and now works as expected. Only goes into insert mode when hinted into field directly.

**Comment by The-Compiler** [comment] 2017-04-19 07:09
Closing this then, in the hope it's fixed with QtWebKit too.

**Closed by The-Compiler** 2017-04-19 07:09 UTC
Labels: component: keyinput, needs triage, priority: 2 - low
