### ISSUE TITLE
Only trigger confirm-quit when closing last window

### ISSUE THREAD

**Issue by kchr** [qutebrowser/qutebrowser#2850] opened 2017-07-23 15:26 UTC
## Current behavior
When having multiple windows open and closing one of them, the `confirm-quit` dialog is displayed in all windows. This gives the impression that the close command will be applied on all windows, but only the active one is really closed.

## Expected behavior
The application should only trigger the `confirm-quit` dialog if the last window is being closed, since only then is the application actually terminated.

## Possible solution
I can think of two:

1. Only trigger and show `confirm-quit` if active window is the last one
2. Show a different dialog `confirm-close`(?) when window count is > 1

In either case, the UI dialog should probably not be shown in all windows unless the action that preceded it will apply to all of them. It's a bit confusing!

## Steps to reproduce
1. Start application
2. Open a second window
3. Close one of the windows (`:close` or kill window via WM)
2. Application will trigger `confirm-quit` in both windows but only close the active one.

I found multiple issues related to the `confirm-quit` behavior, but none that seemed to address this particular thing. If I missed it please tell me where and I'll close this one as a dupe :-)

**Comment by The-Compiler** [comment] 2017-07-23 15:34
Closing this as a duplicate of #632 - I have to admit that issue isn't very verbose, but it's essentially about that too (with #1088 merged into it).

Showing dialogs on one window only unfortunately isn't an option - for many dialogs, we don't know which window they originated from, and the prompting code is already quite complicated, so I'd rather not introduce more complexity there.

**Closed by The-Compiler** 2017-07-23 15:34 UTC

**Comment by kchr** [comment] 2017-07-28 11:16
@The-Compiler Seems reasonable!
