### ISSUE TITLE
inspector inside tab

### ISSUE THREAD

**Issue by helbling** [qutebrowser/qutebrowser#4236] opened 2018-09-21 09:09 UTC
It would be very cool to have the :inspector inside the tab (splitted window: webpage | inspector) instead of in a separate window. Similar to how chromium or firefox have it.

Has anybody already looked into that?
Would this be possible to implement with the current QtWebEngine?

**Comment by qaeu** [comment] 2018-09-21 11:54
#1400

**Comment by The-Compiler** [comment] 2018-09-21 12:01
Duplicate of #1400

**Closed by The-Compiler** 2018-09-21 12:01 UTC
