### ISSUE TITLE
webengine cookies not saved to disk

### ISSUE THREAD

**Issue by TrilbyWhite** [qutebrowser/qutebrowser#2263] opened 2017-01-30 00:26 UTC
I was recently inspired to clean out my webengine cookies database at ~/.local/share/qutebrowser/webengine/Cookies.  I removed all but a subset of entries from the db and restarted qutebrowser.  I found I deleted one to many, and despite trying, I could not restore it (the cookie was applied throughout the session, but not after a close and restart).  I found the Cookie database file was unchanged.  I suspected there might be some redundant check of the db file, and I had broken that by modifying the db - so I just deleted the whole ~/.local/share/qutebrowser folder for a clean start.

However, *no* cookies would be saved from this point on.  The Cookie database file is created as valid sqlute3 database with two tables "cookies" and "meta", but no matter what I do, no cookies are ever added to the cookies table.  In case it's relevant, the "meta" table has one entry "last_compatible_version|5".

I have the following in my ~/.config/qutebrowser/qutebrowser.conf
```
cookies-accept = no-3rdparty
cookies-store = true
```

I tried qutebrowser with the debug flag which gave the following excerpt during shutdown:
```
18:51:45 DEBUG    destroy    app:_shutdown:673 Removing eventfilter...
18:51:45 DEBUG    destroy    mainwindow:_do_close:503 Closing window 0
18:51:45 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: <qutebrowser.mainwindow.tabwidget.TabBar count=0>
18:51:45 DEBUG    ipc        ipc:shutdown:398 Shutting down IPC (socket 0x7f152601af00)
18:51:45 DEBUG    save       savemanager:save:97 Save of version requested - dirty False, save_on_exit True, is_exit True, force False -> True
18:51:45 DEBUG    save       savemanager:save:90 Not saving config because autosaving has been disabled by general -> auto-save-config.
18:51:45 DEBUG    save       savemanager:save:90 Not saving key-config because autosaving has been disabled by general -> auto-save-config.
18:51:45 DEBUG    save       savemanager:save:97 Save of state-config requested - dirty False, save_on_exit True, is_exit True, force False -> True
18:51:45 DEBUG    destroy    ini:save:72 Saving config to /home/jmcclure/.local/share/qutebrowser/state
18:51:45 DEBUG    save       savemanager:save:97 Save of command-history requested - dirty False, save_on_exit False, is_exit True, force False -> False
18:51:45 DEBUG    save       savemanager:save:97 Save of history requested - dirty True, save_on_exit False, is_exit True, force False -> True
18:51:45 DEBUG    destroy    lineparser:_after_save:82 Saved to /home/jmcclure/.local/share/qutebrowser/history
18:51:45 DEBUG    save       savemanager:save:97 Save of quickmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
18:51:45 DEBUG    save       savemanager:save:97 Save of bookmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
18:51:45 DEBUG    save       savemanager:save:97 Save of cookies requested - dirty False, save_on_exit False, is_exit True, force False -> False
18:51:45 DEBUG    destroy    app:_shutdown:701 Deactivating crash log...
18:51:45 DEBUG    destroy    app:_shutdown:711 Deactivating message handler...
18:51:45 DEBUG    destroy    app:_shutdown:714 Deferring QApplication::exit...
18:51:45 DEBUG    modes      modeman:_eventFilter_keypress:191 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: True --> filter: True (focused: None)
```
The cookies line does not indicate that anything was saved.  If I am interpreting it right, it looks like the cookies in the open instance are not detected as "dirty" thus no save is needed.  However, I repeated this several times with loging into various websites and selecting to "remember me" or "log me in each time I visit" options (e.g. bbs.archlinux.org and here on github.com) - yet this line appears and no cookies are saved.

I see in the webengine tracking issue (#666) that cookie settings are not yet checked off the list.  However, persistent cookies were previously saved to disk properly while using webengine - but they no longer are (as of the qt5-webengine 5.8.0 update it would seem).

**Comment by TrilbyWhite** [comment] 2017-01-30 02:49
Odd ... I just exited qutebrowser with the :wq binding which saves the session.  This also wrote the cookies to the sqlite database and when qutebrowser was reopened I didn't need to log back into websites.

It seems from that point on, new cookies could be added and would remain persistent.

It looks like there needs to have been one saved session before cookies could be added to the database, even if the session was not subsequently saved again.

This is resolved for my use, but either I really don't understand how this should work, or it may not be working properly: must one save a session before cookies are stored?  If so it seems odd that new cookies would be appeneded to the database even when the session is exited without saving.

**Comment by The-Compiler** [comment] 2017-01-30 06:25
Reproduced - though `:wq` didn't seem to help here. FWIW the stuff in the log is about QtWebKit cookies, for QtWebEngine, cookies are entirely handled by Qt.

**Comment by The-Compiler** [comment] 2017-01-30 06:28
Looking at your posts in the archlinux BBS - you are also getting this with the current git master without any segfaults, correct?

**Comment by TrilbyWhite** [comment] 2017-01-30 12:38
Correct, this is happening with git build  r11009.90f472bf5-1 with no seg faults on shutdown.

I just found :wq seems to be a red herring.  I again wiped the local/share directory and tried again.  I did a few permutations of creating cookies (e.g. logging into the arch forums) and closing qutebrowser with Ctrl-Q or with Alt-F4 which is my WM binding to send a WM_DELETE_WINDOW message.  Upon reopening qutebrowser, the cookies were no longer available and the sqlite3 database cookie table was empty.  I may have been mistaken on what the contents of the meta table, as every attempt now creates a meta table with the following:
```
mmap_status|-1
version|9
last_compatible_version|5
```

The Cookies database with both tables are created on the first run of qutebrowser whether or not cookies are successfully stored to the table.  It seems sometimes cookies are stored and sometimes they aren't.  I don't have sufficient data to be sure, but it seems whatever triggers the saving is rare enough that I can make several attempts of opening, creating cookies, and closing before anything is saved.  Yet in every attempt so far, once any cookies are saved every subsequently added cookie is saved without issue.

This leads me to suspect that perhaps there is a smallest volume of cookie data needed to trigger the write to disk.  Once that level is reached, the cookies table is populated.  From then on when qutebrowser opens webengine loads the cookies from the DB so it's already beyond the volume needed to trigger the write to disk, so every new cookie get's properly saved.  This is just speculation, but I should be able to test this on my own site in the next day or so by playing with the number/size of cookies while controlling everything else.

**Comment by The-Compiler** [comment] 2017-02-06 19:40
This is actually a Qt bug - reported as [QTBUG-58675](https://bugreports.qt.io/browse/QTBUG-58675). I found a workaround though!

**Comment by The-Compiler** [comment] 2017-02-06 21:18
Unfortunately I had to revert the workaround as it sometimes caused sqlite cookie errors from Chromium on shutdown. We'll need to wait for Qt for a proper fix for this :wink:

**Comment by The-Compiler** [comment] 2017-07-05 14:16
Looks like [QTBUG-58675](https://bugreports.qt.io/browse/QTBUG-58675) now was closed with a fix in Demobrowser rather than Qt itself. So this might still be some issue in qutebrowser (or PyQt not calling destructors like QtWebEngine expects).

**Comment by The-Compiler** [comment] 2019-11-24 20:48
The new PyQt exit scheme seems to fix this - it does sometimes result in sqlite errors on exit as well, but things seem to work fine...

I'll shortly push a commit to enable it where possible. I also tried the workaround again, but it doesn't actually seem to work reliably.

**Closed** 2019-11-24 21:48 UTC
Labels: bug: behavior, component: QtWebEngine, priority: 2 - low
