### ISSUE TITLE
Feature Request: detect if network needs registration

### ISSUE THREAD

**Issue by merspieler** [qutebrowser/qutebrowser#4447] opened 2018-11-30 10:55 UTC
In some public (w)lan networks you need to register to use it.
QBs current behaviour: can't load page

Other browsers (FF eg.) bring up a popup and a click forwards to the registration page or forwarding directly.

**Comment by The-Compiler** [comment] 2018-11-30 10:59
Duplicate of #3083

**Closed by The-Compiler** 2018-11-30 10:59 UTC
