### ISSUE TITLE
Position of new tabs opened from a pinned tab [new setting request]

### ISSUE THREAD

**Issue by brianbuccola** [qutebrowser/qutebrowser#7746] opened 2023-06-15 15:31 UTC
I like to keep all of my pinned tabs next to each other on the left and all of my unpinned tabs on the right (i.e., starting from the position after the last pinned tab), like this (`P` = pinned, `U` = unpinned):

    PPPPUUUUUU

But when I open a tab from a pinned tab, it opens in the next position, because I have `tabs.new_position.related` set to `next`, which I like for unpinned tabs, but not for pinned tabs, because it results in:

    PPUPPUUUUUU

I then have to manually move the tab rightward to get back to my preferred tab layout.

So, it would be nice to have a setting like this:

    tabs.new_position.pinned

which could be set to the usual possible values: `prev`, `next`, `first`, or `last`.

This way, I could do the following:

    set tabs.new_position.related next
    set tabs.new_position.pinned last

which would turn

    PPPPUUUUUU

into the following, where `N` is the new tab opened from some pinned tab:

    PPPPUUUUUUN

(One could imagine further features/complications, but this would be enough for my use case.)

I rechecked the list of settings and also previous issues and didn't see anything like this. If I've missed something, or if this is easy to do on my own, please let me know.

The best I can come up with using plain commands is to chain the following commands and bind them to a key that I press after opening the tab, but that's less than ideal:

    tab-next ;; tab-move -1 ;; tab-focus last

Thanks!

**Comment by toofar** [comment] 2023-06-18 03:44
Duplicate of https://github.com/qutebrowser/qutebrowser/issues/2898 (which also includes a few other related concerns). Please go +1 that!

**Closed** 2023-06-18 10:35 UTC
