### ISSUE TITLE
support split window like vim

### ISSUE THREAD

**Issue by zdmgmail** [qutebrowser/qutebrowser#6265] opened 2021-03-12 02:54 UTC
Hope support split window like in vim

open url in bottom, top, right , left ...

split current tab like this 

```
:jseval javascript:document.write('<HTML><HEAD></HEAD><FRAMESET COLS=\'50%25,*\'><FRAME SRC=' + location.href + '><FRAME SRC=' + location.href + '></FRAMESET></HTML>')
```

navigate like in vim :  `:wincmd w`

**Comment by The-Compiler** [comment] 2021-03-12 08:02
Duplicate of #1716

**Closed by The-Compiler** 2021-03-12 08:02 UTC
