### ISSUE TITLE
Cannot open R documentation in qutebrowser anymore

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#3917] opened 2018-05-15 23:58 UTC
I normally open the R .html help files into qutebrowser without any problem. Those files are local and called directly from within R. But I suddenly became unable to do so. All I get is:

![image](https://user-images.githubusercontent.com/4634851/40082184-1218acba-5845-11e8-8d13-e481330c2ca2.png)

This is an example address for such a file:
```
http://127.0.0.1:10973/library/graphics/html/plot.html
```
Could it be because of the `http`, rather than `https`? Are `http` addresses blocked now?

I don't know how to test this with `qutebrowser --temp-basedir` since my config settings gets launched if I call an R help file from within R (even if I have no qutebrowser session open).

I updated the adblock with no effect.

Thank you.

**Comment by jgkamat** [comment] 2018-05-16 04:49
@prosoitos, to test if it is the adblocker or not, can you try setting `content.host_blocking.enabled` to false?

I don't think this is related to HTTP/HTTPS myself.

I'm not very familiar with the R documentation, how exactly can I go about reproducing this? I'm not sure how the webserver is started for R.

**Comment by mschilli87** [comment] 2018-05-16 05:48
@prosoitos:
> I don't know how to test this with qutebrowser --temp-basedir since my config settings gets launched if I call an R help file from within R (even if I have no qutebrowser session open).

Try `options(browser="qutebrowser --temp-basedir")` before opening the help from within R.

---
@jgkamat:
> I'm not very familiar with the R documentation, how exactly can I go about reproducing this? I'm not sure how the webserver is started for R.

Run `R` to launch an R session, then `options(help_type="html"); ?help` to launch the help server in your default browser and `q("no")` to quit R again.

**Comment by jgkamat** [comment] 2018-05-16 20:07
Thanks for the instructions @mschilli87 :)

I can't seem to reproduce this myself. I don't think https would work at all, because you'd need certs for that.

I've gotten similar errors when trying to connect to znc being served over the IRC port, so it could be the browser blocking that particular port? I'm not sure though...

**Comment by prosoitos** [comment] 2018-05-17 02:05
Thank you both for the debugging advice.

I can confirm that it is blocked by the adblocker (setting `content.host_blocking.enabled` to `false` allows me to open the page).

This started yesterday. Never had issues before. What should I do from there? Could this be sent to the person building the adblock list (as we already did when I couldn't open the urban dictionary site?)

(Notes: indeed, `https` changed nothing. And thanks for the tip to open `qutebrowser --temp-basedir` from within R).

**Comment by prosoitos** [comment] 2018-05-17 02:07
@jgkamat: did you update your adblocker list before testing? This really just started. I had no issues until 30 or so hours ago.

**Comment by jgkamat** [comment] 2018-05-17 02:11
I updated my lists just now, and I'm still not seeing anything:

The URL that I'm visiting is: http://127.0.0.1:14367/library/utils/html/help.html

The host blocking lists (from 1.3.0 onwards) is managed by [this repo](https://github.com/StevenBlack/hosts), but it's probably best to find the offending entry before filing an issue. The merged host list is located here: `~/.local/share/qutebrowser/blocked-hosts` and is overwritten on adblock-update.

I don't know why the list is interfering, I don't think it should be blocking anything served by localhost.

**Comment by prosoitos** [comment] 2018-05-17 04:37
Mmm... weird. I have no idea either. All I can say is that turning the adblocker off solves the problem.

**Comment by prosoitos** [comment] 2018-05-17 04:50
If I can't find a solution, thanks to @mschilli87 's tip, I can now at least add `options(browser="qutebrowser --temp-basedir")` to my .Rprofile and have help files open in a new window. It takes a little longer to open, but it is not the end of the world.

I would like to understand what is going on though :stuck_out_tongue:

**Comment by jgkamat** [comment] 2018-05-17 04:59
One thing you could try doing is adding the localhost domain that it's pointing to into `content.host_blocking.whitelist`. That should be the same as finding the offending entry but is less clean.

**Comment by prosoitos** [comment] 2018-05-17 05:08
I tried with no results. What exactly is the localhost domain?

I tried adding `"http://127.0.0.1"` to the white list with no effect. (I first tried to add the whole path to the html help file directory with no result either).

**Comment by prosoitos** [comment] 2018-05-17 05:28
> What does `:set content.host_blocking.lists?` say?
```
content.host_blocking.lists = ["https://www.malwaredomainlist.com/hostslist/hosts.txt", "http://someonewhocares.org/hosts/hosts", "http://winhelp2002.mvps.org/hosts.zip", "http://malwaredomains.lehigh.edu/files/justdomains.zip", "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext"]
```
> Is `127.0.0.1` in your ~/.local/share/qutebrowser/blocked-hosts file?

Darn! Yes, it is!!! Why did I not look for that rather than add it to my white list? I am so dumb! Why did it get added there though?

OK. So problem solved then. I'll just remove it from the blocked list (and the white list).

Thank you very much all 3 of you!!!!

**Comment by prosoitos** [comment] 2018-05-17 05:30
Oh and qutebrowser version is v1.2.1

But I guess it doesn't matter now that you found the problem. I have no idea how 127.0.0.1 got added to the blocked list though...

**Comment by The-Compiler** [comment] 2018-05-17 07:37
Note that the `blocked-hosts` file is just what qutebrowser generates from the individual lists when you run `:adblock-update` - so once you do that again, it'll be overwritten.

In 1.3.0 the default blocklist changed to [StevenBlack's combined host file](https://github.com/StevenBlack/hosts) which doesn't seem to have this issue. You can use the same on v1.2.1 by doing `:set content.host_blocking.lists '["https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"]'` (unfortunately, Archlinux' package is outdated right now...)

However, when switching back to the old lists on v1.3.0, I can reproduce this issue - so this looks like there's still some issue with one of the lists, or with qutebrowser's host parsing.

**Comment by The-Compiler** [comment] 2018-05-17 07:57
Yeah, the "someonewhocares" host list has an entry simply reading `127.0.0.1` which seems like a bug there. I sent a mail to the author to tell them about it - in the meantime, I suggest you switch to the StevenBlack list or add 127.0.0.1 to the whitelist.

**Closed by The-Compiler** 2018-05-17 07:57 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by prosoitos** [comment] 2018-05-17 17:45
> Note that the blocked-hosts file is just what qutebrowser generates from the individual lists when you run :adblock-update - so once you do that again, it'll be overwritten.

OK. Thank you for clarifying this. Since @jgkamat could not reproduce, I was starting to think that I had added it in, on top of the automatically generated lines, somehow, unwillingly.

> In 1.3.0 the default blocklist changed to StevenBlack's combined host file which doesn't seem to have this issue. You can use the same on v1.2.1 by doing :set content.host_blocking.lists '["https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"]' (unfortunately, Archlinux' package is outdated right now...)

Oh, I see. That explains why @jgkamat could not reproduce! I should have thought of comparing versions.

> I suggest you switch to the StevenBlack list 

I will choose this option. If you (or other qutebrowser developers/maintainers) decided to switch to this list, I imagine that you must have decided that it was better.

Thank you again very much @The-Compiler , @jgkamat , and @mschilli87 . All your inputs were very valuable. I apologize I keep posting issues on this project and I thank you for your repeated patience and help. On the up-side, this is slowly teaching me how to debug my problems, so I should stop posting them eventually... (I am a passionate but very new geek...).

**Comment by prosoitos** [comment] 2018-05-17 17:53
Oh, one quick question please:

I see that my current `content.host_blocking.lists` is: 
```
["https://www.malwaredomainlist.comi/hostslist/hosts.txt", "http://someonewhocares.org/hosts/hosts", "http://winhelp2002.mvps.org/hosts.zip", "http://malwaredomains.lehigh.edu/files/justdomains.zip", "https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&mimetype=plaintext"]
```
Should I only replace the someonewhocares by StevenBlack or should I replace all of them by StevenBlack, leaving only this entry?

Thank you.

**Comment by The-Compiler** [comment] 2018-05-17 18:31
> Thank you again very much @The-Compiler , @jgkamat , and @mschilli87 . All your inputs were very valuable. I apologize for opening so many issues on this project and I thank you for your repeated patience and help. On the up-side, this is slowly teaching me how to debug my problems, so I should stop posting them eventually... (I am a passionate but very new geek...).

Please don't worry about it! It shows that you're taking the time to make clear what the issue is about (with screenshots and all!), and to answer follow-up questions - the only time issues are annoying is when the reporter provides little information and then vanishes when asking something (or when people are just needlessly demanding), and yours are definitely the opposite of all that! :smile:

Always happy to help when people are nice about it, and I think that can (fortunately) be said about the qutebrowser community as a whole :tada: 

> Should I only replace the someonewhocares by StevenBlack or should I replace all of them by StevenBlack, leaving only this entry?

The StevenBlack list already combines a lot of blacklists into one (see [their readme](https://github.com/StevenBlack/hosts/blob/master/readme.md) for details), so that's the only list you'll need.

**Comment by prosoitos** [comment] 2018-05-17 20:53
Thank you!
