### ISSUE TITLE
:download command does not retain session data

### ISSUE THREAD

**Issue by Holzhaus** [qutebrowser/qutebrowser#4573] opened 2019-02-13 12:36 UTC
As part of a userscript I need to download a file from a website using the users current session on that website. I thought I could use `QUTE_FIFO` and the `:download` command, but unfortunately,`:download` does not do that. Thus, I only get an error message that I'm not logged in.

`:open` works, but it can't really be used in a script, because downloads will open a popup where the user can select a download location.

Maybe a new parameter like `--session` can be added to the `:download` command to allow sending session cookies.

**Comment by The-Compiler** [comment] 2019-02-13 13:18
Duplicate of #2328

**Closed by The-Compiler** 2019-02-13 13:18 UTC
