### ISSUE TITLE
Bug: unpredictably using only the downer half of window to render page

### ISSUE THREAD

**Issue by Unip0rn** [qutebrowser/qutebrowser#3948] opened 2018-05-26 19:51 UTC
=What I did=
I opened a new tab and :open ed a site (https://en.wikipedia.org/wiki/Third-person_pronoun#Historical_and_dialectal_gender-neutral_pronouns), but also experienced the issue with other sites.

=What I expected=
The site is being displayed on the entire space available to the window (except the area used for bars)

=What happened=
The downer half was used to display the site, the upper was blank, in between there was a visible border looking like the kind of border you use for seperate elements of UI the user can resize at will, but in this case you can't.
Also notable it seemed like the page was just moved down that half screen, not 

=What I tried to mitigate / understand / whatever=
* reload the tab, did not change anything (reloading in the downer half of the window)
* restart qutebrowser (several times, this is definitly in the up-to-date version in the arch repos)
* reboot
* close the tab and reload the one coming to the position (11. tab in the window), did not reproduce on the tab moved at the position.
* reopen the suspicious tab on a new tab, reproduced the issue with other sites, URLs will follow when known.

the only change I did lately was to enable auto_save.session in my config.py
Logs will be provided soon or once I find a way to reproduce the issue.
When there is anything else to narrow down the issue let me know.

=config.py=
c.auto_save.session = True
c.backend = "webengine" 

c.tabs.position = "left"
c.tabs.select_on_remove = "last-used"
c.tabs.show = "multiple"
#c.tabs.tabs_are_windows = false
c.tabs.width=190

=Version:=
qutebrowser v1.3.0
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.23.1
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.11-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/me/.cache/qutebrowser
config: /home/me/.config/qutebrowser
data: /home/me/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:09:57

**Comment by Unip0rn** [comment] 2018-05-26 19:53
unpredictedly reproduced with 
https://www.zdnet.com/article/open-source-is-free-like-a-puppy-is-free-says-sun-boss-3039202713/
when opening in new tab with middle mouse

**Comment by jgkamat** [comment] 2018-05-26 20:10
Duplicate of #3920. 

I'd reccomend running qb from git master (where this is migitated) or downgrading to qt 5.10.1.

**Closed by jgkamat** 2018-05-26 20:10 UTC

**Comment by Unip0rn** [comment] 2018-05-27 15:50
Oh. I must have overseen that one. Thanks for pointing!
