### ISSUE TITLE
Quickmark load completion quirk on single list item

### ISSUE THREAD

**Issue by sdothum** [qutebrowser/qutebrowser#2387] opened 2017-03-01 22:21 UTC
qutebrowser v0.10.0

This appears related to problem report #1519. The behaviour now is: when completion refinement results in a single list entry, tabbing to the entry closes the buffer window instead of highlighting the entry itself. Hitting enter at this point, however, opens the intended url.

**Comment by The-Compiler** [comment] 2017-03-01 22:48
I don't see anything unexpected about this. Wasn't it always that way?

**Comment by sdothum** [comment] 2017-03-03 00:02
No. In the earlier release with #1519 tabbing remained in the buffer window but did not initially highlight the entry yellow. Now, tabbing closes the buffer window immediately but the status line continues to show the selection input value. So quickmark load input is still appears to be active. Hitting Enter at that point opens the referenced url, despite it not showing at this point. Strange.

**Comment by The-Compiler** [comment] 2017-03-03 06:30
Oh, indeed - looks like it now inserts a space at the end while it didn't before. I'd guess this happened with the changes by @rcorre or @mlochbaum, but I'm not sure :wink:

> Now, tabbing closes the buffer window immediately but the status line continues to show the selection input value. So quickmark load input is still appears to be active. Hitting Enter at that point opens the referenced url, despite it not showing at this point. Strange.

Think of the status line like a console input. Tabbing completes things (with the completion). `:quickmark-load <name>` is a command loading the quickmark with that name. If you execute a valid command, it'll work no matter whether the completion is still open or not.

**Comment by rcorre** [comment] 2017-03-03 13:12
This seems like intended behavior to me, even if it isn't quite how it worked before

**Comment by The-Compiler** [comment] 2017-03-03 13:13
So my first thought was that it doesn't make much sense to add a space if there's no more arguments that can be added (like with `:quickmark-load`), but you can actually still add e.g. `-t`. Closing this then.

**Closed by The-Compiler** 2017-03-03 13:13 UTC
Labels: component: completion, priority: 2 - low

**Comment by mlochbaum** [comment] 2017-03-11 09:27
This was intended, although now I sometimes find it frustrating that I can't see the additional information from the completion window (date last visited for a URL; description for a command) if there is only one item. Most of the time the current behavior works for me, but it would be neat if something like moving the cursor back to that item opened the window again. Hard to implement, though.
