### ISSUE TITLE
Use pdfjs's zoom/search feature?

### ISSUE THREAD

**Issue by user202729** [qutebrowser/qutebrowser#4314] opened 2018-10-08 16:46 UTC
When search/zoom function is executed, should qutebrowser call the corresponding functions of pdfjs?

Advantages:

* The pdfjs toolbar is not resized.
* The search is executed on the whole document, instead of only the rendered pages.

This can be detected by, for example, check if the URL starts with `qute://pdfjs/viewer.html?` and special case the commands.

**Comment by The-Compiler** [comment] 2018-10-08 16:49
Duplicate of #1916

**Closed by The-Compiler** 2018-10-08 16:49 UTC
