### ISSUE TITLE
fonts.monospace is ignored

### ISSUE THREAD

**Issue by aidanharris** [qutebrowser/qutebrowser#3070] opened 2017-10-08 13:40 UTC
Changing the fonts.monospace doesn't seem to have any effect:

![](https://i.imgur.com/lV030aQ.png)

I managed to hack around this with some JavaScript ([this is much more impactful](https://i.imgur.com/6mNkJjn.png)) as follows:

```js
let fonts = [];
for (tag of document.querySelectorAll('input')) {
  if (tag.id.startsWith('input-fonts')) {
    fonts.push(tag);
  }
}
fonts = fonts.filter(e => { return e.value.indexOf('sans-serif') === -1; }); // Only alter monospace fonts...
for (let i = 1; i < fonts.length; i++) {
  fonts[i].value = fonts[i].value.match(/.*[0-9]pt\s/)[0] + fonts[0].value;
  cset(fonts[i].id.replace('input-',''), fonts[i].value);
}
```

qutebrowser v0.11.0
Git commit: v0.11.0-1160-g0d8edd54f (2017-10-06 14:25:46 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: Qt5CTProxyStyle
Platform: Linux-4.14.0-rc3-g85b1bb248071-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/aidan/.cache/qutebrowser
config: /home/aidan/.config/qutebrowser
data: /home/aidan/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Comment by The-Compiler** [comment] 2017-10-08 13:44
Duplicate of #2973

**Closed by The-Compiler** 2017-10-08 13:44 UTC
