### ISSUE TITLE
url.searchengines not working as expected

### ISSUE THREAD

**Issue by 0n-Zen** [qutebrowser/qutebrowser#4596] opened 2019-02-18 17:24 UTC
I'm in the process of switching to qutebrowser and tried adding my keyword searchstrings like this (autoconfig.yml):

  url.searchengines:
    DEFAULT: https://searx.me/?q={}&categories=general&language=en-US   
    baka: https://www.mangaupdates.com/search.html

The first one for searx.me works, but the second one for mangaupdates.com doesn't. Possibly because it didn't have the %s that could be replaced with {}, but that's just how that site works and the search string above does work within Firefox without the %s.

How can I make it work in qutebrowser?

**Comment by jgkamat** [comment] 2019-02-18 17:34
0n-Zen writes:

>     baka: https://www.mangaupdates.com/search.html

Per the documentation, you need a '{}' section which will be populated with
the query. How does Firefox send the search query?

**Comment by The-Compiler** [comment] 2019-02-18 18:21
That site uses a POST request, see #2605.

**Comment by The-Compiler** [comment] 2019-02-18 18:21
Duplicate of #2605.

**Closed by The-Compiler** 2019-02-18 18:21 UTC
