### ISSUE TITLE
Browser not supported by Slack anymore

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#7951] opened 2023-10-06 20:21 UTC
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.3, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.3 (compiled 6.5.2)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Starting yesterday (October 5, 2023), I am getting "This browser is no longer supported" when trying to access Slack.

**Comment by prosoitos** [comment] 2023-10-06 20:22
Note: I tried the latest commit in case this had been addressed since the latest release, but same problem.

**Comment by toofar** [comment] 2023-10-06 20:43
We had a bit of a discussion on that yesterday on an older issue: https://github.com/qutebrowser/qutebrowser/issues/4669#issuecomment-1749608133

I'm not 100% sure what part of the user agent they don't like though, so if you have time to experiment a bit that could be helpful:
* try setting your user agent for slack to the same as the default one for your browser, but without the `{qt_key}/{qt_version}` part
* if that doesn't work you'll probably have to hardcode the `{upstream_browser_version}` section to some version 112 or higher
* once you get in try unsetting the custom user agent you just set and see if it is still happy

**Comment by williamsonrichard** [comment] 2023-10-06 20:47
I have tried every variation of the user-agent string that I can think of, without success, alas. Moreover, the same user-agent string does work on a different computer running the same operating system (Arch Linux), which suggests that it is not only the user-agent string which is being checked. I also tried clearing site data, to no avail. Finally, I tried digging into Slack's javascript to try to find out what it is doing, but have not succeeded; it is possible it is not entirely client side code.

**Comment by prosoitos** [comment] 2023-10-06 21:47
Sorry for missing that conversation. Your solution there works for me. Thank you!!! 🙂

**Comment by williamsonrichard** [comment] 2023-10-07 09:25
I tried it now with exactly the same syntax as in that conversation, that is, using `:set -u app.slack.com` and also `:set -u slack.com`, and it then worked. Thank you! What I had been doing previously was setting `c.content.headers.user_agent` (to exactly the same user agent as in the `:set -u` commands) globally in `config.py`. Is there some kind of bug here that is causing `c.content.headers.user_agent` not to be used in some circumstances? It is definitely being used on ordinary GET requests in general.

**Comment by The-Compiler** [comment] 2023-10-08 20:00
Reopening this because we should adjust our workaround accordingly.

**Comment by toofar** [comment] 2023-10-11 20:17
With my work instance all I did was set the `{upstream_browser_version}` part of our default user agent to `118.0.5359.220`, I didn't have to remove the qt segment at all, I even still have my custom `qutebrowser/{qutebrowser_version}` segment in there. Strange that @rcorre's 99999 major version didn't work, also that the normal 112 based major version didn't :thinking:

**Comment by prosoitos** [comment] 2023-10-13 16:18
toofar solution stopped working for me today.

**Comment by cortsf** [comment] 2023-10-13 16:26
Same here. Fixed by switching to `118.1.5615.213`.

```
config.set('content.headers.user_agent',
           'Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/118.1.5615.213 Safari/{webkit_version}',
           'slack.com')
```

**Comment by mdtusz** [comment] 2023-10-13 17:40
Not working for me today either with any user agent changes :/

I've sent a somewhat annoyed email to slack support about this and just received the normal template reply about "we care about ensuring a high quality user experience and security", so it's going to be an uphill battle to continue using the web client. 

Interestingly, the support agent has said that they support Chrome and Edge, but do not support Chromium :thinking:. May provide clues as to what parts of their fingerprinting need to be circumvented.

**Comment by prosoitos** [comment] 2023-10-13 19:21
Didn't work for me either.

**Comment by cortsf** [comment] 2023-10-13 20:12
Weird. Just in case, I'm also using:

```
config.set('content.headers.user_agent',
           'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36',
           '*')
```

And `:version` shows:

```
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.3, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.3

CPython: 3.10.12
PyQt: 6.5.2
```

**Comment by mdtusz** [comment] 2023-10-13 20:53
Clearing all the localstorage seems to make it work now, in conjunction with a spoofed user agent string.

**Comment by toofar** [comment] 2023-10-14 00:28
This is the error page FWIW. It links to https://slack.com/help/articles/115002037526-Minimum-requirements-for-using-Slack

![image](https://github.com/qutebrowser/qutebrowser/assets/7419144/efcb0c91-eed7-4301-a2e6-ac072c7cd3f5)

I had a dig around in the source code to see if I could find anything but it seems to be a server side check. Although I did find from the service worker code that if you have `(Slack)` anywhere in the user agent it seems to think you are using the slack SSB (single site browser, the desktop app I presume). Putting that in my user agent seems to make it let me in. I'm not sure if I would recommend that because it might make it think you are running the desktop app and try to use native extensions. Feel free to try it out though I guess, I imagine the worse that happens is that something just doesn't work.

Looking at the main navigation request (this one from force reloading the page with dev tools open and caching disabled) I did see these headers (it's an https/2 request):

![image](https://github.com/qutebrowser/qutebrowser/assets/7419144/d08a0b37-ae1d-461c-b363-a9da06bf9e86)

That Chrome/99 is not normal. It's not in my normal user agent, not in httpbin headers or https://nghttp2.org/httpbin/headers. Maybe it is something to do with user agent reducing? https://developer.chrome.com/docs/privacy-sandbox/user-agent/

Maybe that's why even when I override the usual `{upstream_browser_version}` with a value that was basically the same as my actual current version (112) it started working, because slack wasn't actually seeing the real chrome version but the "reduced" one of 99? If so we could maybe reproduce this is chrome and report to them that they aren't handling Chromes complicated GREASE client hint things.

If that is the case (and I'm just speculating) this could be coming from here: https://github.com/qt/qtwebengine-chromium/blob/14780aaa6b0f85a6912878b3874c18e63c99a5d9/chromium/components/embedder_support/user_agent_utils.cc#L413

So I'll play around with blink::features::kReduceUserAgent and see if I can come up with some convincing reproducers.

**Comment by toofar** [comment] 2023-10-14 01:02
Ah, looks like our "quirk" from last time where we override the user agent for slack is bitting us, oops!

Please add `"ua-slack"` to the "content.site_specific_quirks.skip" setting if you are not using qutebrowser from a git package. I'll remove it in git later today after thinking about how to prevent quirks from hanging around past their use-by date in the future. Or make the "I'm a new chrome" version more dynamic.

**Comment by toofar** [comment] 2023-10-14 03:02
I've pushed the following commits to resolve this:

* https://github.com/qutebrowser/qutebrowser/commit/2edce1244ae9703950b9bb2a14b6d42c73bbd1a0
* https://github.com/qutebrowser/qutebrowser/commit/a7a2420f02661020bcdea8728a1f846a868f4d56

It turns out we've been spoofing Chrome/99 since the previous time this came up. It had a note on it to revisit that with the Qt6 update but we didn't do so. So slack actually thinks we are on an older version than we are.

Setting a custom user agent was working for some people, but intermittently, because the quirk was using the same mechanism. So I think on qute start the (bad) quirk would be active, if you set a custom UA after that then that would be active.

I did some quick testing to see if they were actually testing for chrome 112 but it looks to me like actually 106+ is allowed in just fine. Which [should mean](https://github.com/qutebrowser/qutebrowser/blob/main/qutebrowser/utils/version.py#L608) that Qt6.5 would be fine without the quirk. But testing this stuff reliably can be a bit tricky and I don't think it'll hurt to keep it in (especially when they claim to only support 112).

**Closed by toofar** 2023-10-14 03:02 UTC
Labels: component: QtWebEngine, bug: behavior

**Comment by prosoitos** [comment] 2023-10-14 19:09
Thanks!!!!

**Comment by mdtusz** [comment] 2023-10-16 22:39
Anyone encountering the block yet again here? 

Seems like they're actively adding more checks and blocks to prevent use. If anyone from Slack is reading this, can you just not please? So so user hostile...

Trying the `content.site_specific_quirks.skip ua-slack` doesn't seem to be working here for me, but I'll keep prodding and reply back if I'm successful.

**Comment by prosoitos** [comment] 2023-10-17 01:00
Still working for me right now.
