### ISSUE TITLE
@ does not work for running a macro when italian layout is set on uk keyboard in Windows

### ISSUE THREAD

**Issue by Aster89** [qutebrowser/qutebrowser#5183] opened 2020-01-08 12:58 UTC
The hardware keyboard is UK; as I am not expert of the various layout, on the right of <kbd>L</kbd>
the keys are <kbd>;:</kbd>, <kbd>'@</kbd>, <kbd>#~</kbd> (the second character is the <kbd>Shift</kbd>ed one).

(For reference, the same positions in an Italian hardware are occupied by the keys <kbd>òç@</kbd>, <kbd>à°#</kbd>, <kbd>ù§</kbd> (the second character [...], the third one is the <kbd>AltGr</kbd>ed one).)

I can correctly play a macro recorded in `a` by entering `@a`, which means hitting <kbd>Shift</kbd>+<kbd>'</kbd> and then <kbd>a</kbd> on the UK hardware keyboard, when the UK keyboard is in use.

However, if I have the Italian keyboard setting on, and I hit the keys labelled on the UK hardware as <kbd>AltGr</kbd>+<kbd>;</kbd> (which are labelled <kbd>AltGr</kbd>+<kbd>ò</kbd> in the Italian hardware), and hit <kbd>a</kbd>, it is just like not having pressed `@` at all.

I think this is related to another strange behavior: if a textbox is focused, like the one in which I'm writing right now, Hitting <kbd>AltGr</kbd>+<kbd>;</kbd> (corresponding to <kbd>AltGr</kbd>+<kbd>ò</kbd> in the italian keyboard) inserts a literal @ in the text, without ever entering the insert mode! I can even hold the key combination to insert a flow of @.

- The OS is Windows 10,
- from Language settings, the Windows display language is English (United Kingdom),
- I don't like Windows at all.

**Comment by The-Compiler** [comment] 2020-01-08 13:21
Duplicate of #1258 (see the comments there).

**Closed by The-Compiler** 2020-01-08 13:21 UTC
