### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by Rick21-bit** [qutebrowser/qutebrowser#6971] opened 2022-01-19 19:26 UTC
Ad block on qutebrowser is good till they are not. If plugin system were develop i myself will try making ad block for site like YouTube, besides the existing

**Comment by The-Compiler** [comment] 2022-01-19 19:27
Duplicate of #30

**Closed by The-Compiler** 2022-01-19 19:27 UTC

**Comment by The-Compiler** [comment] 2022-01-19 19:29
As for what's missing for YouTube adblocking, see #6480  - note that you can already use qutebrowser's Greasemonkey support to [run a script](https://github.com/qutebrowser/qutebrowser/issues/6480#issuecomment-872771282) which speeds the ads up and skip them, or spawn mpv from qutebrowser to watch videos, or use something like Invidious.
