### ISSUE TITLE
PyQt5 5.7.1 TypeError: C++ type 'QList<QSslError>' is not supported as a pyQtSlot type argument type

### ISSUE THREAD

**Issue by lluixhi** [qutebrowser/qutebrowser#2213] opened 2017-01-03 23:42 UTC
```
qutebrowser v0.9.0
Git commit: v0.9.0-9-g48d4c9311-dirty (2017-01-02 20:16:51 +0100)

CPython: 3.5.2
Qt: 5.7.1
PyQt: 5.7.1

sip: 4.19
colorama: no
pypeg2: 2.15
jinja2: 2.8.1
pygments: 2.1.3
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.5.188 (/home/lluixhi/.local/share/qutebrowser/pdfjs/build/pdf.js)
Webkit: no
SSL: LibreSSL 2.5.0

Style: QFusionStyle
Platform: Linux-4.8.15-hardened-r1-x86_64-Intel-R-_Core-TM-_i5-4210U_CPU_@_1.70GHz-with-gentoo-2.3, 64bit
Frozen: False
Imported from /usr/lib/python3.5/site-packages/qutebrowser
OS Version:

--- /etc/os-release ---
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo/Linux"

--- /etc/gentoo-release ---
Gentoo Base System release 2.3

--- /etc/lsb-release ---
DISTRIB_ID="Gentoo"

Paths:
runtime: /tmp/.runtime-lluixhi/qutebrowser
data: /home/lluixhi/.local/share/qutebrowser
download: /home/lluixhi/Downloads
config: /home/lluixhi/.config/qutebrowser
system_data: /home/lluixhi/.local/share/qutebrowser
cache: /home/lluixhi/.cache/qutebrowser
```

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.5/qutebrowser", line 11, in <module>
    load_entry_point('qutebrowser==0.9.0', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 168, in main
    from qutebrowser import app
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 51, in <module>
    from qutebrowser.browser.webkit.network import networkmanager
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/webkit/network/networkmanager.py", line 114, in <module>
    class NetworkManager(QNetworkAccessManager):
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/webkit/network/networkmanager.py", line 214, in NetworkManager
    @pyqtSlot('QNetworkReply*', 'QList<QSslError>')
TypeError: C++ type 'QList<QSslError>' is not supported as a pyqtSlot type argument type
```

At the moment I commented out `on_ssl_errors` because I don't know how to work around this -- I'm using the qtwebengine backend.

**Comment by The-Compiler** [comment] 2017-01-04 06:48
When exactly do you get that? No issues when visiting https://expired.badssl.com/ with the same Qt/PyQt/sip versions here.

**Comment by fiete201** [comment] 2017-01-04 22:31
@lluixhi Can you please show your USE flags for qtwebkit?

**Comment by The-Compiler** [comment] 2017-01-04 22:32
And for qtnetwork I guess?

**Comment by fiete201** [comment] 2017-01-04 22:37
Yes for sure :-)

**Comment by lluixhi** [comment] 2017-01-05 00:39
I get this error on startup, but interestingly, I didn't have this issue until very recently.

I don't have qtwebkit installed at all (this is with qtwebengine, a custom qutebrowser ebuild, and qtnetwork from the libressl overlay -- so it'll be hard to identify what is actually going wrong)

Here are the qtwebengine USE flags:
```
USE="pax_kernel system-ffmpeg system-icu widgets -bindist -debug -geolocation -test"
```
and for qtnetwork:
```
USE="libressl ssl -bindist -connman -debug -libproxy -networkmanager -test"
``` 

I guess the easiest thing would be if you could tell me in which library this bug most likely resides in? :P

**Comment by The-Compiler** [comment] 2017-01-05 05:34
If I knew! :wink:

Can you please show:

- The output of `python3 -c 'from PyQt5.QtNetwork import QSslError'` (there should be none)
- The output of `python3 -c 'from PyQt5.QtNetwork import QSslSocket; print(QSslSocket.sslLibraryVersionString())'`
- The build output of PyQt5 (in a pastebin like https://p.cmpl.cc/)

**Comment by lluixhi** [comment] 2017-01-05 19:44
RuhRoh

* 
```
>>> from PyQt5.QtNetwork import QSslError
```
*
```
>>> from PyQt5.QtNetwork import QSslSocket
>>> print(QSslSocket.sslLibraryVersionString())
LibreSSL 2.5.0
```

NOTE: Will rebuild the other things, I actually have a suspicion the issue will disappear on a rebuild, but if not I'll add the build output.

**Comment by lluixhi** [comment] 2017-01-06 03:55
Huh.
Is this normal?
```
>>> from PyQt5.QtCore import QList
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'QList'

**Comment by The-Compiler** [comment] 2017-01-06 05:14
Hmm, I'm none the wiser...

Can you reproduce it with this minimal example?

```python
from PyQt5.QtCore import QObject, pyqtSlot
from PyQt5 import QtNetwork

class Foo(QObject):

    @pyqtSlot('QNetworkReply*', 'QList<QSslError>')
    def foo(self, a, b):
        pass
```

Also, if you have the time and can easily do so, could you check if doing anything of this helps?

- Building Qt/PyQt against OpenSSL instead of SSL
- Downgrading to Qt 5.7.0 without downgrading PyQt
- Downgarding to PyQt 5.7.0 without downgrading Qt

After all that I'll probably report a bug to the PyQt mailinglist and see what they have to say.

**Comment by lluixhi** [comment] 2017-01-06 05:24
Alright, so that is enough to reproduce:
```
>>> from PyQt5.QtCore import QObject, pyqtSlot
>>> from PyQt5 import QtNetwork
>>> class Foo(QObject):
...     @pyqtSlot('QNetworkReply*', 'QList<QSslError>')
...     def foo(self, a, b):
...         pass
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in Foo
TypeError: C++ type 'QList<QSslError>' is not supported as a pyqtSlot type argument type
>>>
```
Going to try the third option you mentioned first because it seems it broke after dev-python/sip and dev-qt/PyQt5 updated, and using LibreSSL and Qt 5.7.1 worked before that..

**Comment by lluixhi** [comment] 2017-01-06 05:52
Welp. Unfortunately downgrading sip and PyQt5 to 4.18.1 and 5.7 respectively worked, so the issue is indeed inside of sip/PyQt5 for me.

**Comment by The-Compiler** [comment] 2017-01-06 06:17
Posted to the PyQt mailinglist: https://www.riverbankcomputing.com/pipermail/pyqt/2017-January/038499.html

FWIW as a workaround you can simply remove the `@pyqtSlot` line but leave the function itself as-is. That should not have any noticeable impact at all on modern PyQt version, but can cause weird issues with older versions - so I'm reluctant to do that unless more people are impacted.

**Comment by The-Compiler** [comment] 2017-01-24 21:35
No answer there... since this hasn't happened for anyone else and seems like a PyQt issue, I'm closing this - please keep me updated if you find out more though!

**Comment by optik-aper** [comment] 2017-01-25 00:12
If it still matters I am also getting this error.  I just did a fresh install from the Void Linux repos and the debug output on startup looks like it's related to this PyQt issue:
```
qutebrowser --debug  
18:45:47 DEBUG    init       earlyinit:init_log:327 Log initialized.  
18:45:47 DEBUG    init       earlyinit:fix_harfbuzz:203 Using system harfbuzz engine (auto)  
Traceback (most recent call last):  
  File "/usr/bin/qutebrowser", line 11, in <module>  
    load_entry_point('qutebrowser==0.9.1', 'gui_scripts', 'qutebrowser')()  
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 168, in main  
    from qutebrowser import app  
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 51, in <module>  
    from qutebrowser.browser.webkit.network import networkmanager  
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/webkit/network/networkmanager.py", line 114, in <module>  
    class NetworkManager(QNetworkAccessManager):  
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/webkit/network/networkmanager.py", line 214, in NetworkManager  
    @pyqtSlot('QNetworkReply*', 'QList<QSslError>')  
TypeError: C++ type 'QList<QSslError>' is not supported as a pyqtSlot type argument type  
```
Let me know if you need any more output.

**Comment by The-Compiler** [comment] 2017-01-25 06:42
@optik-aper that's odd - with LibreSSL as well by any chance?

Reopening for now, if this happens for more people I guess it's time to remove that `@pyqtSlot` and hope it doesn't break things with earlier PyQt versions.

**Comment by lluixhi** [comment] 2017-01-27 19:37
@The-Compiler Just FYI, Voidlinux (and soon Alpine Linux) use LibreSSL by default, so yes, it is possible that this is a LibreSSL/QtNetwork interaction.

**Closed** 2017-02-05 18:10 UTC
Labels: can't reproduce

**Comment by The-Compiler** [comment] 2017-02-06 07:40
This seems more like a PyQt issue, as PyQt disallows `QSslError` as a slot type, while Qt SSL in general seems to work fine (as seen in the `print(QSslSocket.sslLibraryVersionString())` example above).

If you feel like it, `qpy/QtCore/qpycore_chimera.cpp` in PyQt's source would probably be the place to dig further, as that's what's doing the type parsing. I won't bother though, I'm fine with removing the `@pyqtSlot` here.

**Comment by lluixhi** [comment] 2017-02-06 07:46
Alright, I'll look there.

I actually just refreshed the LibreSSL/QtNetwork patch because LibreSSL 2.5.1 was released, and I'm wondering whether this has changed (LibreSSL 2.5.1 supports all the functions from OpenSSL 1.0.2+ used in QtNetwork at the moment).
https://github.com/gentoo/libressl/blob/master/dev-qt/qtnetwork/files/qtnetwork-5.7.1-libressl.patch

**Comment by The-Compiler** [comment] 2017-02-06 07:47
You should be able to find out [with the example above](https://github.com/qutebrowser/qutebrowser/issues/2213#issuecomment-270833112) :wink:

**Comment by lluixhi** [comment] 2017-02-06 07:48
Yup!

**Comment by lluixhi** [comment] 2017-02-06 22:54
It's still broken :/
Wondering whether this could possibly be compiler specific... If I have time I'll test with GCC 5.

**Comment by kjnirlp** [comment] 2017-02-07 03:41
both v0.9.1 and 9999 work fine here

```
qutebrowser v0.9.1
Git commit: v0.9.0-183-ge487fe441 (2017-02-06 22:16:39 +0100)
Backend: QtWebEngine

CPython: 3.4.5
Qt: 5.7.1
PyQt: 5.7.1

sip: 4.19
colorama: no
pypeg2: 2.15
jinja2: 2.9.4
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: no
PyQt5.QtWebEngineWidgets: yes
pdf.js: no
Webkit: no
SSL: LibreSSL 2.5.1

Style: QFusionStyle
Platform: Linux-4.9.8-gentoo-x86_64-Intel-R-_Core-TM-_i5-4460_CPU_@_3.20GHz-with-gentoo-2.2.1, 64bit
Frozen: False
Imported from /usr/lib64/python3.4/site-packages/qutebrowser
OS Version: 

--- /etc/os-release ---
ID="funtoo"
NAME="Funtoo GNU/Linux"
PRETTY_NAME="Linux"
VERSION="2016-12-31"
VERSION_ID="intel64-haswell-2016-12-31"

--- /etc/gentoo-release ---
Funtoo Linux - baselayout 2.2.1
```

**Comment by svenper** [comment] 2017-02-19 23:05
Same issue for me on Void Linux. Using both `libressl` and `musl`.

musl: 1.1.16
libressl: 2.4.5
qutebrowser: 0.9.1
python: 3.5.3
PyQt5-webkit: 5.7.1
Jinja2: 2.8.1
MarkupSafe: 0.23
Pygments: 2.2.0
lxml: 3.7.2
pyPEG2: 2.15.2
sip: 4.19
yaml: 3.12

```
$ qutebrowser --debug
23:54:00 DEBUG    init       earlyinit:init_log:327 Log initialized.
23:54:00 DEBUG    init       earlyinit:fix_harfbuzz:203 Using system harfbuzz engine (auto)
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 11, in <module>
    load_entry_point('qutebrowser==0.9.1', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 168, in main
    from qutebrowser import app
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 51, in <module>
    from qutebrowser.browser.webkit.network import networkmanager
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/webkit/network/networkmanager.py", line 114, in <module>
    class NetworkManager(QNetworkAccessManager):
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/webkit/network/networkmanager.py", line 214, in NetworkManager
    @pyqtSlot('QNetworkReply*', 'QList<QSslError>')
TypeError: C++ type 'QList<QSslError>' is not supported as a pyqtSlot type argument type
```

**Comment by optik-aper** [comment] 2017-02-19 23:24
@svenper a fix for this issue [was commited](https://github.com/qutebrowser/qutebrowser/commit/3f332d3871e5e39f244f63cdba4e8f4d1b530080) and is working when you build from source.  The void repos don't have a new build, probably because there isn't a new tagged release.  I'm also on Void musl and I just built it separately today but there are further issues with running qutebrowser on musl which basically means javascript won't work anywhere and some hinting functionality is hampered.  @The-Compiler commited a change for the hinting problem today but the javascript problem seems to be Qt's fault.  See [this issue](https://github.com/qutebrowser/qutebrowser/issues/1416#issuecomment-208138461) for details there.

**Comment by The-Compiler** [comment] 2017-02-20 05:19
FWIW I'll try to do a new release somewhen this week.
