### ISSUE TITLE
Crash unexpectedly whenever i click to "download tabs" on the top page

### ISSUE THREAD

**Issue by Henry-Ta** [qutebrowser/qutebrowser#6130] opened 2021-02-04 01:56 UTC
**Version info**:

The latest version on Feb 3rd, 2021 - Arch Linux
**Does the bug happen if you start with `--temp-basedir`?**:

**Description**

**How to reproduce**

Downloads pictures
Right-click to download tabs on the top page
CRASH - Everytime

**Comment by The-Compiler** [comment] 2021-02-04 08:17
Duplicate of #6087

**Closed** 2021-02-04 08:18 UTC
