### ISSUE TITLE
PyQt6 - Broken dev-tools.

### ISSUE THREAD

**Issue by mutexdeveloper** [qutebrowser/qutebrowser#7851] opened 2023-08-22 18:17 UTC
**Version info**:
https://bpa.st/ZNIA
**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
Certain actions in dev-tools (clicking close X, right click) doesn't work when using PyQt6
**How to reproduce**
* Open qutebrowser
* Open dev-tools (wi - normal)
* Try clicking close X or right click

```
$ qutebrowser -T --qt-wrapper PyQt6
[48965:48965:0822/191211.365368:ERROR:interface_endpoint_client.cc(694)] Message 6 rejected by interface blink.mojom.WidgetHost
[48965:48965:0822/191211.365416:ERROR:interface_endpoint_client.cc(694)] Message 7 rejected by interface blink.mojom.WidgetHost
[48965:48965:0822/191211.365449:ERROR:interface_endpoint_client.cc(694)] Message 3 rejected by interface blink.mojom.Widget
```
( The above error shows when dev-tools is opened, **not** when clicking closing X or right click )

**Comment by The-Compiler** [comment] 2023-08-22 18:50
Duplicate of #7676

**Closed by The-Compiler** 2023-08-22 18:50 UTC

**Comment by mutexdeveloper** [comment] 2023-08-22 22:52
> Duplicate of #7676

Sorry, couldn't find that issue.
