### ISSUE TITLE
Prevent tab bar from consuming window space when active while tabs.show = 'switching'

### ISSUE THREAD

**Issue by wu4** [qutebrowser/qutebrowser#4113] opened 2018-08-06 18:38 UTC
Whenever switching tabs with `tabs.show` set to `'switching'`, the tab bar showing up will reduce the size of the web page display, which can be very laggy and disorienting for some websites. I suggest to at least add an option to make it behave like the completion widget, where it sits on top of the web page display instead of resizing it.

**Comment by The-Compiler** [comment] 2018-08-06 18:39
Duplicate of #1593

**Closed by The-Compiler** 2018-08-06 18:39 UTC
