### ISSUE TITLE
Ctrl+C crashes when "QtWebEngine version change" popup is open

### ISSUE THREAD

**Issue by arza-zara** [qutebrowser/qutebrowser#7791] opened 2023-07-22 11:45 UTC
```
$ QUTE_QT_WRAPPER=PyQt5 qutebrowser -B ~/qutetest :quit

$ QUTE_QT_WRAPPER=PyQt6 qutebrowser -B ~/qutetest  # then press ctrl+c
^C14:39:48 INFO: SIGINT/SIGTERM received, shutting down!
14:39:48 INFO: Do the same again to forcefully quit.
14:39:48 ERROR: Uncaught exception
Traceback (most recent call last):
  File "misc/quitter.py", line 222, in shutdown
    prompt.prompt_queue.shutdown()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'shutdown'
14:39:48 ERROR: Error while getting history: 'command-history'
Traceback (most recent call last):
  File "misc/crashsignal.py", line 213, in _get_exception_info
    cmd_history = objreg.get('command-history')[-5:]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "utils/objreg.py", line 246, in get
    return reg[name]
           ~~~^^^^^^
  File "/usr/lib/python3.11/collections/__init__.py", line 1124, in __getitem__
    raise KeyError(key)
KeyError: 'command-history'
```

**Comment by The-Compiler** [comment] 2023-07-22 12:18
Duplicate of #6827

**Closed by The-Compiler** 2023-07-22 12:18 UTC
Labels: qt: 6
