### ISSUE TITLE
This browser or app may not be secure when trying to login to GMail

### ISSUE THREAD

**Issue by cdosborn** [qutebrowser/qutebrowser#5181] opened 2020-01-07 17:22 UTC
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/fd47e978

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**

![image](https://user-images.githubusercontent.com/3847314/71914731-3a13bd80-3148-11ea-9471-506a80a93689.png)

**How to reproduce**
Try to login to gmail. I tested with 2FA enabled/disabled w/o luck.

**Comment by The-Compiler** [comment] 2020-01-07 17:23
Duplicate of #5144

**Closed by The-Compiler** 2020-01-07 17:23 UTC

**Comment by The-Compiler** [comment] 2020-01-07 18:05
I just wrote a more detailed explanation for what's going on: #5182
