### ISSUE TITLE
Segfault on Wayland

### ISSUE THREAD

**Issue by samflores** [qutebrowser/qutebrowser#7603] opened 2023-03-08 18:53 UTC
## Description

I've been running the `qt6-v2` branch successfully for a while now, except for WebRTC screen sharing. Recently I tried switching from X to a Wayland compositor and Qutebrowser isn't able to start. I'm running a Gentoo distribution so I re-compiled the whole system with wayland support enabled. Not sure the egl warning is relevant, I just found it strange because egl support is also enabled. All other qt applications are working as expected.
## `--version` output
```
qutebrowser v2.5.2
Git commit: f4f5ca266-dirty on qt6-v2 (2023-01-29 15:43:08 +0100)
Backend: QtWebEngine 6.4.2, based on Chromium 102.0.5005.177 (from api)
Qt: 6.4.2

CPython: 3.10.10
PyQt: 6.4.2

sip: no
colorama: 0.4.4
jinja2: 3.1.2
pygments: 2.14.0
yaml: 5.4.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.4.0
pdf.js: no
sqlite: 3.40.1
QtNetwork SSL: OpenSSL 1.1.1t  7 Feb 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: None
Platform: Linux-6.2.1-gentoo-x86_64-AMD_Ryzen_7_4800H_with_Radeon_Graphics-with-glibc2.36, 64bit
Linux distribution: Gentoo Linux (gentoo)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3.10
Qt library executable path: /usr/lib64/qt6/libexec, data path: /usr/share/qt6
```
## does it happen with `--temp-basedir`?
```
yes
```
## Stack trace
```
qutebrowser --temp-basedir --debug                                                                                                                                                                             ~
15:30:09 WARNING: Failed to load client buffer integration: "wayland-egl"
15:30:09 WARNING: Available client buffer integrations: QList()
15:30:10 WARNING: QRhiGles2: Failed to create temporary context
15:30:10 WARNING: QRhiGles2: Failed to create context
15:30:10 WARNING: Failed to create QRhi for QBackingStoreRhiSupport
15:30:10 WARNING: QRhiGles2: Failed to create temporary context
15:30:10 WARNING: QRhiGles2: Failed to create context
15:30:10 WARNING: Failed to create QRhi for QBackingStoreRhiSupport
15:30:10 WARNING: QQuickWidget: Failed to get a QRhi from the top-level widget's window
15:30:10 WARNING: QQuickWidget::resizeEvent() no QRhi
15:30:10 WARNING: QRhiGles2: Failed to create temporary context
15:30:10 WARNING: QRhiGles2: Failed to create context
15:30:10 WARNING: Failed to create QRhi for QBackingStoreRhiSupport
15:30:10 WARNING: QQuickWidget: Failed to get a QRhi from the top-level widget's window
15:30:10 WARNING: QRhiGles2: Failed to create temporary context
15:30:10 WARNING: QRhiGles2: Failed to create context
15:30:10 WARNING: Failed to create QRhi for QBackingStoreRhiSupport
15:30:10 WARNING: QQuickWidget: Failed to get a QRhi from the top-level widget's window
15:30:10 WARNING: QQuickWidget::resizeEvent() no QRhi
15:30:10 WARNING: QQuickWidget: Attempted to render scene with no rhi
Received signal 11 SEGV_MAPERR 000000000000
#0 0x7f2fc8ae85f9 (/usr/lib64/libQt6WebEngineCore.so.6.4.2+0x42c55f8)
#1 0x7f2fc8a2d386 (/usr/lib64/libQt6WebEngineCore.so.6.4.2+0x420a385)
#2 0x7f2fc8ae8a9a (/usr/lib64/libQt6WebEngineCore.so.6.4.2+0x42c5a99)
#3 0x7f2fd61c8c10 (/lib64/libc.so.6+0x37c0f)
#4 0x7f2fd1313836 (/usr/lib64/libQt6Gui.so.6.4.2+0x233835)
#5 0x7f2fd14b8f99 QPlatformBackingStore::rhiFlush()
#6 0x7f2fd1bbe3dd QWidgetRepaintManager::flush()
#7 0x7f2fd1bbfa34 QWidgetRepaintManager::flush()
#8 0x7f2fd1bc1f0e QWidgetRepaintManager::paintAndFlush()
#9 0x7f2fd1bc2936 QWidgetRepaintManager::sync()
#10 0x7f2fd1bcbf52 (/usr/lib64/libQt6Widgets.so.6.4.2+0x1e1f51)
#11 0x7f2fd1b5bae1 QApplicationPrivate::notify_helper()
#12 0x7f2fd24d70ee (/usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so+0x38d0ed)
#13 0x7f2fd5015b98 QCoreApplication::notifyInternal2()
#14 0x7f2fd129d8db QGuiApplicationPrivate::processExposeEvent()
#15 0x7f2fd12f5dcb QWindowSystemInterface::sendWindowSystemEvents()
#16 0x7f2fd1802070 (/usr/lib64/libQt6Gui.so.6.4.2+0x72206f)
#17 0x7f2fd469fdc8 g_main_context_dispatch
#18 0x7f2fd46a0068 (/usr/lib64/libglib-2.0.so.0.7400.5+0x56067)
#19 0x7f2fd46a00fc g_main_context_iteration
#20 0x7f2fd5302e6c QEventDispatcherGlib::processEvents()
#21 0x7f2fd50221fb QEventLoop::exec()
#22 0x7f2fd501e0d8 QCoreApplication::exec()
#23 0x7f2fd24d5f1b (/usr/lib/python3.10/site-packages/PyQt6/QtWidgets.abi3.so+0x38bf1a)
#24 0x7f2fd645c643 (/usr/lib64/libpython3.10.so.1.0+0xf7642)
#25 0x7f2fd641e160 _PyObject_MakeTpCall
#26 0x7f2fd63d1fbd _PyEval_EvalFrameDefault
#27 0x7f2fd64ef194 (/usr/lib64/libpython3.10.so.1.0+0x18a193)
#28 0x7f2fd63d081b _PyEval_EvalFrameDefault
#29 0x7f2fd64ef194 (/usr/lib64/libpython3.10.so.1.0+0x18a193)
#30 0x7f2fd63d1f69 _PyEval_EvalFrameDefault
#31 0x7f2fd64ef194 (/usr/lib64/libpython3.10.so.1.0+0x18a193)
#32 0x7f2fd63d081b _PyEval_EvalFrameDefault
#33 0x7f2fd64ef194 (/usr/lib64/libpython3.10.so.1.0+0x18a193)
#34 0x7f2fd64ef3b9 PyEval_EvalCode
#35 0x7f2fd652f3c3 (/usr/lib64/libpython3.10.so.1.0+0x1ca3c2)
#36 0x7f2fd652f5f6 (/usr/lib64/libpython3.10.so.1.0+0x1ca5f5)
#37 0x7f2fd652f6d0 (/usr/lib64/libpython3.10.so.1.0+0x1ca6cf)
#38 0x7f2fd6531879 _PyRun_SimpleFileObject
#39 0x7f2fd6531e20 _PyRun_AnyFileObject
#40 0x7f2fd6550090 Py_RunMain
#41 0x7f2fd655061a Py_BytesMain
#42 0x7f2fd61b434a (/lib64/libc.so.6+0x23349)
#43 0x7f2fd61b43fc __libc_start_main
#44 0x556cf0783081 _start
  r8: 00007ffeaedcb080  r9: 0000000000040296 r10: 0000000012c8cb7a r11: 00000000005870ff
 r12: 0000556cf29cdd40 r13: 0000556cf2a180b0 r14: 0000556cf27f7ca8 r15: 0000000000000000
  di: 0000000000000001  si: 00007ffeaeca90c0  bp: 00007ffeaeca9370  bx: 0000556cf2a180f8
  dx: 0000000012c8cb7a  ax: 0000000000000000  cx: 0000000000000018  sp: 00007ffeaeca9100
  ip: 00007f2fd1313836 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
[2]    25638 segmentation fault  qutebrowser --temp-basedir
```

**Comment by toofar** [comment] 2023-03-10 22:07
Seems like a question for gentoo people? Maybe try Falkon and see if that runs fine. You can set QT_QPA_PLATFORM=xcb to use XWayland as a workaround. Other than that it looks like something in the platform isn't working. Maybe make sure PyQt is built right too.

**Comment by samflores** [comment] 2023-03-11 02:04
Every other Qt app I tried works fine on Wayland, including Falkon. The QT_QPA_PLATFORM workaround works but I'll keep investigating on my own. Feel free to close the ticket if needed. Thanks.

**Comment by The-Compiler** [comment] 2023-03-12 15:02
Could you please try the [Qt 6 testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/qt6-v2/scripts/testbrowser/testbrowser_webengine.py) and see how things look there?

If that works, could you try the [C++ testbrowser](https://github.com/qutebrowser/qutebrowser/tree/qt6-v2/scripts/testbrowser/cpp/webengine) (get those two files, run `qmake`, run `make`) and see how that works?

**Comment by samflores** [comment] 2023-03-13 12:16
Both fail under wayland.

### Qt 6 testbrowser script output

https://gist.github.com/samflores/c8315951032560707576147b628ced93

### C++ testbrowser output

https://gist.github.com/samflores/d98f0a6631109f299e367c1f611a1294

**Comment by The-Compiler** [comment] 2023-03-13 12:19
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can easily reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2023-03-13 12:19 UTC
Labels: status: needs triage, qt: 6

**Comment by yokem55** [comment] 2023-06-16 02:59
I don't know if you ever got a resolution on this, but I ran into the same crash on my gentoo/wayland box. I did get qutebrowser running again though by running with the vulkan backend for qutewebengine - `QSG_RHI_BACKEND=vulkan qutebrowser` did the trick without any obvious downsides yet.

**Comment by vimproved** [comment] 2023-06-17 03:41
Figured out the issue:
First, dev-qt/qtbase needs to be compiled with the egl USE flag. Then, dev-qt/qtwayland needs to be recompiled after dev-qt/qtbase is compiled with the egl USE flag. This should probably be a usedep in the qutebrowser-9999 ebuild, I'll file a PR to the repos.
