### ISSUE TITLE
window.transparent & set colors.webpage.bg with alpha value brings webpage above context menu

### ISSUE THREAD

**Issue by Doomer-Cat** [qutebrowser/qutebrowser#8025] opened 2023-12-08 19:40 UTC
**Version info**:

```
qutebrowser v3.0.2
Git commit: 
Backend: QtWebEngine 6.6.1, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.1

```
**Does the bug happen if you start with `--temp-basedir`?**:

Yes:

**Description**

Webpage is above contextmenu when window.transparent is enabled and a webpage background color is set with alpha value
(Also for some reason if alpha value (hex & rgba) is set it just makes it 100% transparent & just ignores color & the alpha value.
can only be set manually)

![20231208_20h25m08s_grim](https://github.com/qutebrowser/qutebrowser/assets/81427193/62765c3f-3da9-44aa-8195-fd68e13b1e3a)
![20231208_01h08m32s_grim](https://github.com/qutebrowser/qutebrowser/assets/81427193/f70741a7-bc44-4520-b0cf-52023fc3c333)

**How to reproduce**

1.
```
qutebrowser -T ":set window.transparent True" ":set colors.webpage.bg #1d2021c0" :restart
```
2. use duckduckgo bang "!archman"

**Comment by Doomer-Cat** [comment] 2023-12-08 19:57
Also happens with recent version:
qutebrowser v3.1.0
Git commit: a9f6ad973 on main (2023-12-08 15:30:58 +0000)
Backend: QtWebEngine 6.6.1, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.1

**Comment by The-Compiler** [comment] 2023-12-11 13:06
Duplicate of #5948

**Closed by The-Compiler** 2023-12-11 13:06 UTC
