### ISSUE TITLE
devtools network tab crashes

### ISSUE THREAD

**Issue by LiteracyFanatic** [qutebrowser/qutebrowser#5564] opened 2020-07-03 02:37 UTC
**Version info**:

qutebrowser v1.13.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Since the most recent update, using the network tab of the devtools causes qutebrowser to crash. This happens with both the embedded and standalone window.

**How to reproduce**

1. Open the devtools.
2. Switch to the network tab.
3. Click on the first request. This is usually enough to cause the crash. Sometimes you have to click on a different request or switch  between the different sections of the request (headers, preview etc.).

[log.txt](https://github.com/qutebrowser/qutebrowser/files/4867412/log.txt)
[stack-trace.txt](https://github.com/qutebrowser/qutebrowser/files/4867484/stack-trace.txt)

**Comment by The-Compiler** [comment] 2020-07-03 06:38
Duplicate of #5513

**Closed by The-Compiler** 2020-07-03 06:38 UTC

**Comment by The-Compiler** [comment] 2020-07-07 11:40
FWIW if you happen to use Archlinux, the crashes were [fixed](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/qt5-webengine&id=fc7cbcf3af5fe895e7f19a2b8ce6333c150c362c) in qt5-webengine 5.15.0-3 which backports the upstream fix.

**Comment by LiteracyFanatic** [comment] 2020-07-07 16:31
I do as a matter of fact. Great to hear!
