### ISSUE TITLE
Right clicking on the "downloads" bar crashes qutebrowser

### ISSUE THREAD

**Issue by Penaz91** [qutebrowser/qutebrowser#6106] opened 2021-01-30 20:40 UTC
**Version info**:
```
qutebrowser v2.0.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.1
PyQt: 5.15.2

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.2
pygments: 2.7.4
yaml: 5.3.1
adblock: 0.4.1
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.7.570 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1i  8 Dec 2020
```
**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

When you right click on the black space where the completed downloads are situated, qutebrowser crashes

**How to reproduce**
1. Download any file
2. When the download is completed, right click on the black space where downloads are located (not on the download itself)
3. Qutebrowser should crash

**Comment by The-Compiler** [comment] 2021-01-30 20:49
Duplicate of #6087

**Closed by The-Compiler** 2021-01-30 20:49 UTC
