### ISSUE TITLE
Tab changes without an appropriate user input if a particular map exists

### ISSUE THREAD

**Issue by qsmodo** [qutebrowser/qutebrowser#6387] opened 2021-04-12 14:40 UTC
Please create this `config.py`:
```
config.load_autoconfig(False)
config.bind('<Tab>','tab-next')
config.bind('<Shift-Tab>','tab-prev')
```
Launch Qutebrowser, `:clone` the tab and `:open wikipedia.org`.

Expected: Wikipedia is loaded in the current tab.

Actually: *When Wikipedia loads*, Qutebrowser changes to the other tab.

This is not specific to Wikipedia, every site I try has the problem.

The problem did not show up in a previous version (1.6.1 IIRC).

Here are some info, please let me know if more is needed:
```
qutebrowser v2.0.2
Git commit:
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

CPython: 3.9.2
PyQt: 5.15.2

sip: 5.4.0
colorama: no
jinja2: 2.11.3
pygments: 2.7.1
yaml: 5.3.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.2
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.34.1
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021
```

**Comment by The-Compiler** [comment] 2021-04-12 14:41
Duplicate of #4579

**Closed by The-Compiler** 2021-04-12 14:41 UTC
