### ISSUE TITLE
Login loop at gitlab.com

### ISSUE THREAD

**Issue by pinarruiz** [qutebrowser/qutebrowser#7346] opened 2022-08-17 11:23 UTC
**Version info**:
```
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.4

CPython: 3.10.6
PyQt: 5.15.7

sip: 6.6.2
colorama: 0.4.4
jinja2: 3.1.2
pygments: 2.12.0
yaml: 6.0
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: 2.14.0 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.39.2
QtNetwork SSL: OpenSSL 3.0.5 5 Jul 2022

Style: Qt5CTProxyStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 22.2.0-rc2
Platform: Linux-5.18.0-4-amd64-x86_64-with-glibc2.34, 64bit
Linux distribution: Debian GNU/Linux bookworm/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/user/.cache/qutebrowser
config: /home/user/.config/qutebrowser
data: /home/user/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/user/.config/qutebrowser/config.py has been loaded
Uptime: 0:38:59
```

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
Login Loop at [https://gitlab.com/users/sign_in/](https://gitlab.com/users/sign_in/), on doing a challenge against cloudflare, I have tried with firefox and it works fine, trying to use firefox user agent (even on all domains just in case) does not work either, incognito on qutebrowser does not work either.

![Error image](https://global.discourse-cdn.com/business4/uploads/gitlab/original/3X/9/c/9ca605042759fb02582039f80434258b31f92340.png)

Issue i opened over at gitlab's forums: [https://forum.gitlab.com/t/loop-on-gitlab-com-checking-browser/73753?u=alejandropinarruiz](https://forum.gitlab.com/t/loop-on-gitlab-com-checking-browser/73753?u=alejandropinarruiz)

**How to reproduce**
Go to [https://gitlab.com/users/sign_in/](https://gitlab.com/users/sign_in/) and, at least on my setup, the page stays on the checking your browser "stage".

**Comment by The-Compiler** [comment] 2022-08-17 13:57
Duplicate of #7208

**Closed by The-Compiler** 2022-08-17 13:57 UTC
