### ISSUE TITLE
Javascript enabled indicator in statusbar.

### ISSUE THREAD

**Issue by toofar** [qutebrowser/qutebrowser#3859] opened 2018-04-22 00:23 UTC
When using url patterns and `content.javascript.enabled` to only enable javascript on some sites I would like to see whether javascript is enabled on the current page.

If I remember correctly dwb had a thing in the statusbar like `[SC]` where the presence of `S` indicated that javascript was enabled and `C` was for cookies. I implemented something similar previously (https://github.com/toofar/qutebrowser/blob/js-whitelist/qutebrowser/mainwindow/statusbar/settings.py#L67) and I was wondering if others wanted this and what would be the preferred implementation. There was a couple of directions I was having trouble choosing between so I opened this so someone could help me decide.

1. I could add a `settings` widget for the statusbar which could show more than just javascript in the future. It could even be configurable as to what it includes, anything in websettings should be supportable.
2. Just add a `javascript` widget and deal with any others later. No need to add complexity.
3. Don't do anything, toofar, no-one wants this.

Does anyone have an opinion?

**Comment by The-Compiler** [comment] 2018-04-22 09:39
See #1052 - this would definitely be useful! Would be nice to have it configurable, I guess for an initial implementation it could just support boolean settings?

**Comment by The-Compiler** [comment] 2018-04-22 09:39
Duplicate of #1052

**Closed by The-Compiler** 2018-04-22 09:39 UTC
Labels: component: ui, priority: 3 - wishlist
