### ISSUE TITLE
Saving error pages in sessions takes a long time

### ISSUE THREAD

**Issue by m42a** [qutebrowser/qutebrowser#3976] opened 2018-06-04 02:40 UTC
If a rendering process dies, the entire error page is stuck directly into the page URL (including an 80k base64-encoded png).  If the new rendering process also dies, the previous error page URL is encoded in the new error page URL 3 times, for a grand total size of about 360k.  This is written to the session file twice: once in a "url" key, and once in a "original-url" key.  On my machine, this means qutebrowser maxes out a CPU for 1.5 seconds while generating the session file.  Qutebrowser appears to do automatic session saves multiple times when loading a URL, so there can be a delay of up to half a minute during which the UI does not repaint.

The easiest cost-savings is probably sticking the png behind a qute:// URL instead of embedding it into the page.  Putting the entire error page behind a URL would be better, but I don't know how feasable that is.  It would be really nice if the session was saved asynchronously so it didn't block browsing, but that's probably a non-trivial change.

Version Info:

qutebrowser v1.3.0
Git commit: 7762017f0 (2018-05-03 19:25:04 +0200)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.1
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2j  26 Sep 2016

Style: QWindowsStyle
Platform: Windows-10-10.0.17134-SP0, 64bit
Frozen: True
Imported from C:\Program Files\qutebrowser\qutebrowser
Qt library executable path: C:/Program Files/qutebrowser/PyQt5/Qt/bin, data path: C:/Program Files/qutebrowser/PyQt5/Qt
OS Version: 10, 10.0.17134, SP0, Multiprocessor Free

**Comment by The-Compiler** [comment] 2018-06-11 09:18
Ideally those error pages wouldn't change the URL at all, see #3918 - I'm going to merge this there.

> The easiest cost-savings is probably sticking the png behind a qute:// URL instead of embedding it into the page.

That won't work unfortunately, because it's a disallowed cross-origin request.

**Comment by The-Compiler** [comment] 2018-06-11 09:18
Duplicate of #3918

**Closed by The-Compiler** 2018-06-11 09:18 UTC

**Comment by MarSoft** [comment] 2020-04-07 19:20
What if we serve the error page from `qute://`? Like this: `qute://error/?url=https://google.com/`.
This would fix at least session size issue.

**Comment by The-Compiler** [comment] 2020-04-07 20:17
I'm going to answer in #3918 rather than here (a closed duplicate).
