### ISSUE TITLE
Searching Annoyances

### ISSUE THREAD

**Issue by Radvendii** [qutebrowser/qutebrowser#3924] opened 2018-05-18 17:22 UTC
There seem to be a couple of places where the way searching works seems to me not ideal (maybe other people like the way it works and this is just me)

When I type `/foo` in a web browser, it selects the first instance of "foo". That's fine. Then when I hit `<enter>`, it selects the next instance. What this means, is that there's no way to exit the search input field without gong to the *second* instance of the search. This is annoying if, for example, I want to search for a link and then click on that link I have to press `/foo<enter><S-n><enter>` to select that first link.

Secondly, when I search for something, and then enter a new page that has that search result on it, it immediately goes to that search result, rather than staying at the top of the page. This often happens to me with search engine results.

**Comment by jgkamat** [comment] 2018-05-18 17:30
Part 1 seems like a duplicate of #3511 - What qb version are you on?

The second part seems to be [this qtbug](https://bugreports.qt.io/browse/QTBUG-61506), which says it's fixed, but I seem to see it even on newer versions, so that probably needs a closer look.

**Comment by Radvendii** [comment] 2018-05-18 18:09
I'm on 1.2.1, but now that I try it again, Part 1 isn't happening anymore. Maybe I updated and it got fixed.

**Comment by The-Compiler** [comment] 2018-05-18 18:12
See #3693 for the second part.

**Closed by The-Compiler** 2018-05-18 18:12 UTC
Labels: status: needs triage
