### ISSUE TITLE
Emoji input crashes qutebrowser

### ISSUE THREAD

**Issue by Jan-PieterBaert** [qutebrowser/qutebrowser#4656] opened 2019-03-19 13:53 UTC
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/98dd0d9a

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Qutebrowser crashed when I inputted an emoji
trace:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/qutebrowser/keyinput/keyutils.py", line 82, in _check_valid_utf8
    s.encode('utf-8')
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud83d' in position 0: surrogates not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 929, in eventFilter
    return handler(event)
  File "/usr/lib/python3.7/site-packages/qutebrowser/app.py", line 902, in _handle_key_event
    return man.handle_event(event)
  File "/usr/lib/python3.7/site-packages/qutebrowser/keyinput/modeman.py", line 353, in handle_event
    return handler(event)
  File "/usr/lib/python3.7/site-packages/qutebrowser/keyinput/modeman.py", line 173, in _handle_keypress
    match = parser.handle(event, dry_run=dry_run)
  File "/usr/lib/python3.7/site-packages/qutebrowser/keyinput/basekeyparser.py", line 167, in handle
    txt = str(keyutils.KeyInfo.from_event(e))
  File "/usr/lib/python3.7/site-packages/qutebrowser/keyinput/keyutils.py", line 316, in __str__
    key_string = _key_to_string(self.key)
  File "/usr/lib/python3.7/site-packages/qutebrowser/keyinput/keyutils.py", line 201, in _key_to_string
    _check_valid_utf8(result, key)
  File "/usr/lib/python3.7/site-packages/qutebrowser/keyinput/keyutils.py", line 85, in _check_valid_utf8
    .format(data, s, e))
ValueError: Invalid encoding in 0xd83d -> \ud83d: 'utf-8' codec can't encode character '\ud83d' in position 0: surrogates not allowed
14:44:53 WARNING: /usr/lib/python3.7/tempfile.py:796: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/qutebrowser-downloads-gl5ip597'>
  _warnings.warn(warn_message, ResourceWarning)

[1]    6924 segmentation fault (core dumped)  qutebrowser
```

**How to reproduce**

Open qutebrowser
Input an emoji

**Comment by The-Compiler** [comment] 2019-03-19 13:55
Duplicate of #4439

**Closed by The-Compiler** 2019-03-19 13:55 UTC
