### ISSUE TITLE
Enable/disable CSS command

### ISSUE THREAD

**Issue by AndrewBelt** [qutebrowser/qutebrowser#3036] opened 2017-09-28 06:37 UTC
This might be an odd request, but I used to be able to toggle all stylesheets with Firefox and Vimperator, and it's eons easier to hint-navigate when everything looks like raw HTML pages.

Some webpages are too broken without CSS, while others are improved, so a toggle command that I could bind to would be fantastic. It would be per-page.

I can't find anything in the WebEngine API that does this, but perhaps you know how to navigate it better than I do. Feel free to close if too nontrivial.

**Comment by The-Compiler** [comment] 2017-09-28 06:38
Taking the freedom of closing it as duplicate of #2626 instead :wink:

**Closed by The-Compiler** 2017-09-28 06:38 UTC
