### ISSUE TITLE
Add hint for <someTag id="..."

### ISSUE THREAD

**Issue by ridoo** [qutebrowser/qutebrowser#4556] opened 2019-01-30 17:33 UTC
It would be nice to have a copy hint to the current URL appended with a particular anchor tag. For example 

```html
<div id="important-section">
  some content
</div>
```

When pressing `;<tbd>` qutebrowser shows up hints where `id`s exist. When selecting a hint the URL appended by the corresponding anchor tag is copied to clipboard: `https://URL/#important-section`

**Comment by ridoo** [comment] 2019-01-30 20:08
probably mentioned already here: https://github.com/qutebrowser/qutebrowser/issues/521

**Comment by The-Compiler** [comment] 2019-02-04 20:32
Duplicate of #521

**Closed by The-Compiler** 2019-02-04 20:32 UTC
