### ISSUE TITLE
Crashing after a short period on multiple web sites

### ISSUE THREAD

**Issue by vitomircanadi** [qutebrowser/qutebrowser#5312] opened 2020-03-26 16:30 UTC
**Version info**:
qutebrowser v1.10.1
Git commit: 7fef6a9c8 (2020-02-15 14:17:18 +0100)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1
Also tested on v1.10.0 with same outcome

**Does the bug happen if you start with `--temp-basedir`?**:
IDK
**Description**
Crashing on multiple pages after a short time period.

**How to reproduce**
This possibly started happening after answering Y (always) to the gmail popup
"Allow the website at https://mail.google.com?extsrc=mailto&url=%25s to open all mailto links?"
It was fixed after deleting  C:\Users\vitomir.canadi\AppData\Roaming\qutebrowser\data\webengine\Service Worker
directory

**Comment by The-Compiler** [comment] 2020-03-26 16:34
Duplicate of #5279

**Closed by The-Compiler** 2020-03-26 16:34 UTC
