### ISSUE TITLE
Specific website and specific blocked-host files causes crash

### ISSUE THREAD

**Issue by BilLOPGVkPPn8z0JGJhgiAGNo9YAqpk5ruChl0F** [qutebrowser/qutebrowser#4969] opened 2019-08-16 21:35 UTC
**Version info (see `:version`)**:
```
Version info
qutebrowser v1.7.0
Git commit: 262422077 (2019-08-11 10:12:23 +0200)
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.4
Qt: 5.13.0
PyQt: 5.13.0

sip: 4.19.18
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.2.228 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: Qt5CTProxyStyle
Platform: Linux-5.2.8-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /tmp/qutebrowser-basedir-vwiqbkx6/cache
config: /tmp/qutebrowser-basedir-vwiqbkx6/config
data: /tmp/qutebrowser-basedir-vwiqbkx6/data
runtime: /tmp/qutebrowser-basedir-vwiqbkx6/runtime
system data: /usr/share/qutebrowser
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**:
Visiting http://it.dss.ucdavis.edu/ with a `blocked-hosts` file with an extra newline causes a crash as the website loads.

**How to reproduce**
1. `qutebrowser --temp-basedir`
2. Create `blocked-hosts` file in the temporary `config` dir, add the following:
```

oj.com
```
3. `:restart`
4. Visit http://it.dss.ucdavis.edu/

It does not seem to matter which domains are added, as long as there is at least one newline before an entry.

```
oj.com
oj.com
```
for example doesn't cause the crash.

**Comment by The-Compiler** [comment] 2019-08-16 21:38
Reproduced - stack:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/interceptor.py", line 183, in interceptRequest
    interceptors.run(request)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/extensions/interceptors.py", line 119, in run
    interceptor(info)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/components/adblock.py", line 129, in filter_request
    first_party_url=info.first_party_url):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/components/adblock.py", line 124, in _is_blocked
    not _is_whitelisted_url(request_url))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/components/adblock.py", line 69, in _is_whitelisted_url
    if pattern.matches(url):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/urlmatch.py", line 291, in matches
    qtutils.ensure_valid(qurl)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/qtutils.py", line 156, in ensure_valid
    raise QtValueError(obj)
qutebrowser.utils.qtutils.QtValueError: PyQt5.QtCore.QUrl('') is not valid: Invalid hostname (contains invalid characters); source was "https://++resource++jquery-ui-themes/sunburst/images/ui-bg_flat_50_75ad0a_40x100.png"; scheme = "https", host = "", path = "/sunburst/images/ui-bg_flat_50_75ad0a_40x100.png"
```

**Comment by toofar** [comment] 2019-08-16 23:48
Tt isn't crashing for me on 5.11 because the whole page gets blocked because of https://github.com/qutebrowser/qutebrowser/issues/4325 I guess because the blob URLs don't come through on 5.13 you don't have the problem of all pages being blocked but because that URL is invalid it ends up matching the empty line for the same reason, so since it is blocked it moves on to the whitelist check which doesn't handle invalid URLs.
Maybe the interceptor runner shouldn't even bother running the interceptors for requests where the URL being requested is invalid.

**Comment by The-Compiler** [comment] 2019-08-27 14:28
This doesn't happen anymore with #4863 merged because now empty lines are properly filtered from the blocklist, so this doesn't ever get to the point of checking the whitelist:

```python
        return ((host in self._blocked_hosts or
                 host in self._config_blocked_hosts) and
                not _is_whitelisted_url(request_url))
```

I agree this should be filtered out by the QtWebEngine host interceptor though.

**Closed** 2019-08-27 14:37 UTC
Labels: bug: exception, priority: 1 - middle
