### ISSUE TITLE
honour enter key in context menu (enabling keyboard-only navigation)

### ISSUE THREAD

**Issue by ThPcoder** [qutebrowser/qutebrowser#8081] opened 2024-01-25 13:55 UTC
When right-clicking on a page opens the page-related context menu, it is then possible to navigate its items using the cursor keys. It would be great if the context menu also accepted the Enter key to effect the corresponding mouse click. (So far the key press appears to be captured by the qb "command line processor" only.)

The above is a puzzle stone in enabling keyboard-only controlling of page navigation in qutebrowser.

(concerning: all qb version)

**Comment by The-Compiler** [comment] 2024-01-25 13:59
Duplicate of #3465

**Closed by The-Compiler** 2024-01-25 13:59 UTC
