### ISSUE TITLE
Feature Request: Support for screen capture

### ISSUE THREAD

**Issue by winmillwill** [qutebrowser/qutebrowser#3870] opened 2018-04-27 13:19 UTC
This issue makes it seem like sharing with eg google hangouts should work in QtWebEngine https://bugreports.qt.io/browse/QTBUG-52720?jql=text%20~%20%22screenshare%22

...and the linked test page gives the following error when attempting to share my screen:

```
PERMISSION_DENIED. Are you no SSL? Have you enabled the --enable-usermedia-screen-capture flag?
```

So, I'm not "no SSL", so I'm wondering if there is a procedure for enabling this flag, or if that's a red herring. In any case, I'd like to be able to present my screen without having to start a different browser.

**Comment by The-Compiler** [comment] 2018-04-27 13:59
Duplicate of #2939

**Closed by The-Compiler** 2018-04-27 13:59 UTC
