### ISSUE TITLE
Devtools navigation is bugged in qutebrowser v3.0.0

### ISSUE THREAD

**Issue by minenwerfer** [qutebrowser/qutebrowser#7871] opened 2023-08-30 18:58 UTC
**Version info**:

qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
The devtools top "»" icon now shows a page context menu where "Application", "Security", "Lighthouse" etc should be. Image attached.

![2023-08-30_15-48](https://github.com/qutebrowser/qutebrowser/assets/80406377/1df0d471-d7b2-4003-b754-ef8c099bbbf6)

**How to reproduce**
Open the devtools in windowed mode, shrink its window horizontally until some of the options become hidden, then try to access them with the "»" icon. You must see a page context menu instead.

**Comment by minenwerfer** [comment] 2023-08-30 19:01
Just found out that the "×" icon at the top right is also not working, along several others. Seems like a general issue with devtools.
I first perceived it when I did a full system upgrade on my Arch Linux.

**Comment by The-Compiler** [comment] 2023-08-30 20:29
Duplicate of #7676

**Closed by The-Compiler** 2023-08-30 20:29 UTC

**Comment by minenwerfer** [comment] 2023-08-30 20:43
> Duplicate of #7676

Should have checked before, I'm sorry.
