### ISSUE TITLE
Downloading won't work on sites with captcha

### ISSUE THREAD

**Issue by Mikle-Bond** [qutebrowser/qutebrowser#3983] opened 2018-06-08 21:36 UTC
I've noticed this behaviour while downloading pictures. If site used catpcha for the session, downloading from it with both `:download` and `:hint [target] download` would fail. More exactly: 
 - download starts;
 - prompt about file path spawns;
 - then in a second status changes to "Download error: Error transferring {target url} - server replied: Forbidden";
 - prompt vanishes.

But if you manage to hit Enter before it fails, it will save file, but will put there html code of "Complete captcha" page. In contrary, if you use "Save image" from context menu, it works perfectly. 

So, here what I think the reason of this. When download is initiated, QB spawns another subprocess, which tries to establish new connection. But doesn't seem to use the same cookies, so that site redirects query to captcha page. Subprocess doesn't know what to do and fails.

If I am right about cookies theory, QB should just share cookies for this session with download process.

On the other hand, why QB have to download this files again? I mean, it already displays them in buffer. Isn't it easier to just export them as files on user demand? Running something like `:hint images save`, which would save viewed image without re-downloading would do the trick.

Anyway, this behaviour can be reproduced on almost any booru-like site with proxy set to Tor. Some ExitNodes catch captcha-requests even on Google Images and DeviantArt, but those are pretty rare. Random link to try it out: https://safebooru.donmai.us/posts/3153284
qute:version: http://paste.the-compiler.org/view/ca657cf2

**Comment by The-Compiler** [comment] 2018-06-08 21:42
Duplicate of #2328

**Closed by The-Compiler** 2018-06-08 21:42 UTC

**Comment by The-Compiler** [comment] 2018-06-08 21:44
It's not another subprocess, but another network stack (Qt's instead of Chromium's) which indeed isn't sharing cookies. Since Qt 5.10 it should be possible to trigger custom downloads with Chromium's network stack, but I haven't gotten around to looking at it yet.

**Comment by Mikle-Bond** [comment] 2018-06-08 23:56
Ah, didn't find that one among issues. Sorry.

Just in case I'm missing something again, was the "save without re-download" feature mentioned somewhere else before? IIRC, on Firefox I could open some image (or any supported media) in another tab, and then save it without redownloading (sometimes that happened without Internet connection). 

In fact, Vimperator's `;S` and `;A` would perform redownload, while <kbd>Ctrl</kbd>+<kbd>S</kbd> would just save media if it's the only thing in tab.

Issue #521 looks like a good place for this feature, but I'm not sure if it's the right one.

**Comment by The-Compiler** [comment] 2018-06-09 10:53
No problem!

The "save image" context menu should already save it without having to redownload it, no? I'd expect the same thing to happen (because of Chromium's caching) once #2328 is implemented.
