### ISSUE TITLE
Jumping between tabs with <Tab> and <Shift-Tab>

### ISSUE THREAD

**Issue by danielfalbo** [qutebrowser/qutebrowser#5701] opened 2020-09-02 18:20 UTC
**Version info**:
qutebrowser v1.13.1
Git commit: a99f61071 on HEAD (2020-07-17 17:00:38 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
After mapping tab and shift-tab to what J and K already do, some random times opening a link in the current tab jumps to  another tab

**How to reproduce**
Seems to happen so randomly... but this way to reproduce seems stable
1. Open qutebrowser with `--temp-basedir`
2. Type `:bind <Tab> tab-next` and hit return
3. Type `:bind <Shift-Tab> tab-prev` and hit return
4. Type `O` and hit return (basically we're opening another tab with `:open -t`, but writing it as a command seems not to make the bad behaviour happen in this case) 
5. Do O and return again
6. From the current tab (should be the third), type `o!pocket` and hit return (expanding in `open !pocket`)
7. Type `o!pocket` again and hit return

You should be redirected form the third tab to the first tab
If this doesn't recreate the bug, try to do a little bit of random web navigation, sooner or later should randomly happen

![output](https://user-images.githubusercontent.com/39460524/92021122-8eb01c80-ed59-11ea-9a44-50bba18b201a.gif)

**Comment by jgkamat** [comment] 2020-09-02 18:25
Seems like a duplicate of #4579

**Comment by The-Compiler** [comment] 2020-09-02 18:25
I was about to say that :wink:

**Comment by danielfalbo** [comment] 2020-09-02 18:25
Thanks!

**Closed by The-Compiler** 2020-09-02 18:25 UTC
