### ISSUE TITLE
Flashing white screen 

### ISSUE THREAD

**Issue by edl2** [qutebrowser/qutebrowser#6939] opened 2022-01-05 01:07 UTC
While using qutebrowser, every few seconds the whole screen flashes white, especially during video playback.

**Comment by toofar** [comment] 2022-01-05 02:13
I assume this happened after a recent upgrade? Most likely this is https://github.com/qutebrowser/qutebrowser/issues/6890. I don't think any other issues like this has come up recently.

If it doesn't look like that please post your :version like the issue template says so that somehow has more of a chance of being able to help.

**Comment by nihilistkitten** [comment] 2022-01-07 06:14
I have the same issue. White flashes, especially during video playback. https://paste.the-compiler.org/view/c3a814cc

**Comment by The-Compiler** [comment] 2022-01-07 06:15
Assuming this is a duplicate of #6890.

**Closed** 2022-01-07 06:15 UTC
Labels: status: can't reproduce, status: needs triage
