### ISSUE TITLE
Tab-take should not show the tabs in current window

### ISSUE THREAD

**Issue by wentaozou1** [qutebrowser/qutebrowser#3800] opened 2018-04-02 22:11 UTC
If I am in one window and write ```:tab-take ```, the options of available tabs will pop up. All the tabs in the current window will be shown in the options as well. However, a window can not take its own tab, so I think we should remove the tabs in the current window from the options for the ```:tab-take```
![screen shot 2018-04-02 at 6 06 33 pm](https://user-images.githubusercontent.com/10876776/38218844-1a6ffdac-36a1-11e8-9415-fca73ca13884.png)
![screen shot 2018-04-02 at 6 08 13 pm](https://user-images.githubusercontent.com/10876776/38218845-1b9b7b70-36a1-11e8-8b7c-6ac6ffc1a047.png)

.

**Comment by jgkamat** [comment] 2018-04-03 00:32
Hm, the behavior you describe seems what was intended, I think this is a bug. let me take a stab.

I think that that tabs in win_id '0' are always included, on other window id's it behaves as expected

**Comment by mschilli87** [comment] 2018-04-10 05:40
@wentaozou1: Why did you close this? PR #3802 is not merged yet so I'd assume this still is an 'open issue'. :wink:

**Comment by wentaozou1** [comment] 2018-04-10 05:45
ok, I am sorry

**Comment by toofar** [comment] 2018-04-10 05:57
Yeah we usually keep the issue open until solved, and I think most projects do that too, at least on GitHub. Also if you didn't know GitHub can automatically close issues if a related PR is merged, where they are related by the PR message or one of the commit messages in a PR pointing to the issue via `Closes #1234` or whatever, like explained here: https://help.github.com/articles/closing-issues-using-keywords/

**Closed** 2018-04-10 20:24 UTC
Labels: bug: behavior, component: completion, priority: 2 - low
