### ISSUE TITLE
Some pages don't get recorded in history

### ISSUE THREAD

**Issue by jpalus** [qutebrowser/qutebrowser#6102] opened 2021-01-30 11:56 UTC
**Version info**:
qutebrowser v2.0.1
Git commit: 
Backend: QtWebEngine (Chromium 83.0.4103.122)
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
After following links on some pages they don't end up in history. They seem to be using some dynamic mechanism (I'm not very fluent in current web) so that might be the reason. Affects both opening files in GitHub repos as well as following links on YouTube.

**How to reproduce**
1. Go to https://github.com/qutebrowser/qutebrowser
2. Click on README.asciidoc
3. Try to find displayed README in browser history

Actual result: link is not recorded
Expected result: preferably it should be there (unless this is due to some magic of modern web that prevents it)

**Comment by The-Compiler** [comment] 2021-01-30 12:03
Duplicate of #5012

**Closed by The-Compiler** 2021-01-30 12:03 UTC

**Comment by andrewcarlotti** [comment] 2021-03-07 02:30
Both cases you mention (YouTube and GitHub) will be fixed by #5337
