### ISSUE TITLE
Can't enable microphone in Discord

### ISSUE THREAD

**Issue by kirusfg** [qutebrowser/qutebrowser#7053] opened 2022-03-06 20:24 UTC
**Version info**:
https://paste.the-compiler.org/view/4e40650d

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Similar to #6911. Cannot enable microphone input in Discord even after providing permissions. Discord reports that no input devices are enabled:

![1646597576-wayshot](https://user-images.githubusercontent.com/32136879/156940556-69c84e1d-795d-4a38-869d-38a5e7456bd3.png)

Clicking on **access to your microphone** produces thir error in the console: 
`[AudioActionCreators] unknown getUserMedia error: NotReadableError`

**How to reproduce**

1. Join a Discord voice channel
2. Press y to enable audio input
3. Discord asks for permissions again

or 

1. Press Y to enable audio input
2. Clicking on unmute button does nothing but producing the same `NotReadableError`

**Comment by mschilli87** [comment] 2022-03-07 06:52
Can you use your microphone on other websites using qutebrowser?

**Comment by kirusfg** [comment] 2022-03-07 09:08
It was late into the night when I was filing the issue, checked it today on other websites. Errors are similar
`DOMException: Could not start audio source`
`ERROR Error: Uncaught (in promise): NotReadableError: Could not start audio source`
Gonna try removing pipewire and using something else as a backend.

**Comment by kirusfg** [comment] 2022-03-07 09:21
It is working when using `PulseAudio` only. With `PipeWire` as an audio server for PulseAudio, only output works.

**Comment by mschilli87** [comment] 2022-03-07 09:53
I guess this is the wrong place to look for help then. FWIW, I am using Pipewire as PA server without any issues on a Gentoo system. So maybe Arch is the next place for you to be asking for help.

**Comment by The-Compiler** [comment] 2022-03-07 10:16
Could you try another browser based on QtWebEngine, such as KDE Falkon?

**Comment by kirusfg** [comment] 2022-03-07 13:38
Getting the same error in Falkon

**Comment by The-Compiler** [comment] 2022-03-07 13:41
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them easily, but unfortunately this wasn't the case here (as I don't have a full Wayland setup, and know nothing about Wayland). Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2022-03-07 13:41 UTC
Labels: status: needs triage

**Comment by Yeyito777** [comment] 2025-10-18 07:44
Posting in case this helps anyone:
Got pipewire audio working by piping alsamixer to pipewire and editing config.py so discord has mic perms by default (It can't ask qutebrowser for perms for some reason)

In Arch linux:
create ~/.asoundrc and paste something like this in:
```sh
pcm.!default {
    type pipewire
    playback.pcm "default"
    capture.pcm "default"
    hint.description "PipeWire via ALSA"
}

ctl.!default {
    type pipewire
    hint.description "PipeWire Control"
}
```

Then go to your config.py and add this:

```py
config.set('content.media.audio_capture', True, 'https://discord.com/*')
```

**Comment by nkidis2cool** [comment] 2026-08-09 20:58
Hey I’m new to Linux and having very similar issue. Laptop detects microphone but discord doesn’t due to permissions I’m assuming. Would these commands work on tuxedo os?
