### ISSUE TITLE
Fullscreen in Hero Wars Facebook not working

### ISSUE THREAD

**Issue by SnorlaxYum** [qutebrowser/qutebrowser#6004] opened 2021-01-02 03:25 UTC
**Version info**:https://paste.the-compiler.org/view/082f87d9

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**

**How to reproduce**
https://apps.facebook.com/mobaheroes

**Comment by The-Compiler** [comment] 2021-01-02 09:14
This is unlikely to be an issue specific to qutebrowser. Can you please try with another QtWebEngine-based browser such as Falkon, as well as with Chromium?

**Comment by SnorlaxYum** [comment] 2021-01-03 05:12
Chromium: works
Falkon: same, not working
![](https://user-images.githubusercontent.com/17645894/103472176-5b43d400-4dc5-11eb-86ee-672c791ac879.png)

**Comment by The-Compiler** [comment] 2021-01-03 22:04
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this isn't the case here as I don't have a Facebook account. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2021-01-03 22:04 UTC
Labels: status: needs triage
