### ISSUE TITLE
[Feature Request] Show search count at the bottom right

### ISSUE THREAD

**Issue by leosolid** [qutebrowser/qutebrowser#6636] opened 2021-08-03 22:08 UTC
When you search using `/`, the status bar should show the total occurances found and the one currently selected.

I didn't see a setting for this, so please let me know if it exists already.

**Comment by toofar** [comment] 2021-08-04 08:07
Duplicate of https://github.com/qutebrowser/qutebrowser/issues/3910, sorry.

**Closed by toofar** 2021-08-04 08:07 UTC

**Comment by The-Compiler** [comment] 2021-08-04 08:23
Ah, I knew we had an issue about that already! It should be possible with Qt 5.14+ though, I'm going to reopen #3910.
