### ISSUE TITLE
`insert mode` not entered automatically with option `input.insert_mode.auto_enter = True` when entering Facebook writable areas

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#3794] opened 2018-04-01 22:38 UTC
Not being a Vim user, I struggled for a ridiculous amount of time with remembering to enter `insert` mode before typing. But it suddenly hit me that I was making this mistake *only* on Facebook. Looking closer, I realized that:

while I have the option `input.insert_mode.auto_enter = True` (which works everywhere else, as far as I have noticed), clicking on a writable area in Facebook does not put me in `insert mode` automatically. This is true for messages and comments alike.

**Comment by prosoitos** [comment] 2018-04-01 22:45
Same problem when running qutebrowser with `--temp-basedir`

**Comment by prosoitos** [comment] 2018-04-01 22:46
It does work in the search box, but nowhere else.

**Comment by jgkamat** [comment] 2018-04-01 22:58
This is because (I think) facebook dosen't use real text elements for areas to type, and instead implements their own with divs and js. With js disabled, everything works as expected.

I did notice that fb links have `role="textbox"` as a tag, so we could special case that, maybe.

You'll also notice that `:open-editor` will be broken for these 'fake input elements' too.

**Comment by prosoitos** [comment] 2018-04-01 23:15
So, I tried to disable java script since this FB thing tricks me all the time and, when I went to try to test it I got:

```
JavaScript Required
We're sorry, but Facebook doesn't work properly without JavaScript enabled. If you can't enable JavaScript try visiting the mobile-optimized website.
```

I guess, tons of other things will stop working without `js`. So I'll have to live with it, unless you come up with something.

Anyhow, thanks!!

**Comment by prosoitos** [comment] 2018-04-01 23:48
Ya, I didn't try to the mobile website. I figured that disabling fs would mess up lots of websites. I can survive the Vim nightmare on FB. Been dealing with it for months now :smile: 

If you happen to think of a solution at some point, great! But if not, no worries :slightly_smiling_face: 

And thanks for the help :slightly_smiling_face:

**Comment by The-Compiler** [comment] 2018-04-10 19:28
This might be a duplicate of #253, but I can't verify that as I don't have a Facebook account, and no such text form seems to be available anywhere.

Can you please run qutebrowser with `--debug --logfilter webview,webelem,mouse` and show the output you get when clicking there?

**Comment by jgkamat** [comment] 2018-04-10 19:54
This is from clicking the status composer:

```
15:53:56 DEBUG    webview    webenginetab:_js_cb_single:565 Got element from JS: {'attributes': {'class': '_1mf _1mj', 'data-offset-key': 'l1e2-0-0'}, 'class_name': '_1mf _1mj', 'id': 5, 'outer_xml': '<div data-offset-key="l1e2-0-0" class="_1mf _1mj"><span data-offset-key="l1e2-0-0"><br data-text="true"></span></div>', 'rects': [{'bottom': 499, 'height': 16, 'left': 327.59375, 'right': 631.5, 'top': 483, 'width': 303.90625}], 'tag_name': 'DIV', 'text': '', 'value': ''}
15:53:56 DEBUG    webelem    webelem:is_editable:249 Checking if element is editable: <qutebrowser.browser.webengine.webengineelem.WebEngineElement html='<div data-offset-key="l1e2-0-0" class="_1mf _1mj"><span data-offset-key="l1e2-0-0"><br data-text="true"></span></div>'>
15:53:56 DEBUG    mouse      mouse:_mousepress_insertmode_cb:158 Clicked non-editable element!
```

I think it's a duplicate, fwiw.

**Comment by The-Compiler** [comment] 2018-04-10 20:34
That looks interesting because of two reasons:

- There's no good "heuristic" coming to mind to catch those `div` elements, because the attributes seem like gibberish.
- I don't see a `<textarea>` or `<input>` nested in it, which is the case #253 was tracking originally (though it probably still makes sense to merge this there, and use #253 for generic "rich-text editor" issues).

How does the element look e.g. in the inspector? Is there actually a nested textarea/input somewhere?

**Comment by jgkamat** [comment] 2018-04-10 20:42
Yup, I actually did find an input, but it was a bit higher in the dom than I expected:

Here's the html, I went up a couple levels so that I didn't miss anything.

```
<div class="_fmi _613v UFIInputContainer">
    <div class="_2xwx _289c" role="presentation">
        <input class="_1osa mentionsHidden" name="add_comment_text" tabindex="-1">
        <div class="UFIAddCommentInput _1osb _2xww _5yk1" role="presentation">
            <div class="_5yk2" tabindex="-1">
                <div class="_5rp7">
                    <div class="_1p1t">
                        <div class="_1p1v" id="placeholder-88dek" style="white-space: pre-wrap;">Write a comment...</div>
                    </div>
                    <div class="_5rpb">
                        <div aria-autocomplete="list" aria-controls="js_3n" aria-describedby="placeholder-88dek" aria-multiline="true" class="notranslate _5rpu" data-testid="ufi_comment_composer" role="textbox" spellcheck="true" style="outline: medium none currentcolor; -moz-user-select: text; white-space: pre-wrap; overflow-wrap: break-word;" contenteditable="true">
                            <div data-contents="true">
                                <div class="" data-block="true" data-editor="88dek" data-offset-key="a5fjm-0-0">
                                    <div data-offset-key="a5fjm-0-0" class="_1mf _1mj"><span data-offset-key="a5fjm-0-0"><br data-text="true"></span></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="_fmk UFICommentAttachmentButtons _5op2 _15i7 _2kwm">
        <a aria-label="Insert an emoji" class="_r1a UFICommentEmojiButton _5f0v" data-hover="tooltip" data-tooltip-alignh="center" data-tooltip-content="Insert an emoji" role="button" href="#" id="js_3t">
            <div class="UFICommentEmojiIcon"></div>
        </a>
        <div class="_r1a UFIPhotoAttachLinkWrapper _m" data-hover="tooltip" data-tooltip-alignh="center" data-tooltip-content="Attach a Photo or Video" role="presentation"><span class="UFICommentPhotoIcon"><input accept="video/*,  video/x-m4v, video/webm, video/x-ms-wmv, video/x-msvideo, video/3gpp, video/flv, video/x-flv, video/mp4, video/quicktime, video/mpeg, video/ogv, .ts, .mkv, image/*" aria-label="Attach a Photo or Video" class="_n _5f0v" name="file" title="Attach a Photo or Video" id="js_0" type="file"></span></div>
        <a aria-label="Post a GIF" class="_r1a UFICommentGifButton _5f0v" data-hover="tooltip" data-tooltip-alignh="center" data-tooltip-content="Post a GIF" role="button" href="#" id="js_3u">
            <div class="UFICommentGifIcon"></div>
        </a>
        <a aria-label="Post a sticker" class="_r1a UFICommentStickerButton _5f0v" data-hover="tooltip" data-tooltip-alignh="center" data-tooltip-content="Post a sticker" role="button" href="#" id="js_3v">
            <div class="UFICommentStickerIcon"></div>
        </a>
    </div>
</div>
```

**Comment by The-Compiler** [comment] 2018-04-10 20:58
The `<input class="_1osa mentionsHidden" name="add_comment_text" tabindex="-1">` looks like some hack unrelated to the actual textinput (`mentionsHidden` and `tabindex="-1"`).

However, looking at this again:

```html
<div aria-autocomplete="list" aria-controls="js_3n" aria-describedby="placeholder-88dek" aria-multiline="true" class="notranslate _5rpu" data-testid="ufi_comment_composer" role="textbox" spellcheck="true" style="outline: medium none currentcolor; -moz-user-select: text; white-space: pre-wrap; overflow-wrap: break-word;" contenteditable="true">
    <div data-contents="true">
        <div class="" data-block="true" data-editor="88dek" data-offset-key="a5fjm-0-0">
            <div data-offset-key="a5fjm-0-0" class="_1mf _1mj"><span data-offset-key="a5fjm-0-0"><br data-text="true"></span></div>
        </div>
    </div>
</div>
```

it's the same concept as in #253 - we get that `<div>` with `class="_1mf _1mj"` when asking what was clicked. Walking up only slightly, we get the `div` with `role="textbox"`, which we'd already handle successfully I think. I'll look at what to merge where when I get some more time, off to bed now :wink:

> EDIT: we could also do the CSS trick to see if the cursor would be a 'input' cursor to see if we should enter insert mode, maybe?

Maybe. But maybe it's time to finally get proper focus tracking with a communication from JS to Python instead of more hacks (because JS should know when a text box is focused, and it could tell Python with a `QWebChannel` or so) - but that's for another day :wink:

**Comment by prosoitos** [comment] 2018-04-11 01:05
Sorry for the late reply and thank you @jgkamat for answering! Sorry I didn't realize #253 was dealing with the same situation. I guess we could also all stop using FB :wink:

**Comment by toofar** [comment] 2018-04-11 07:26
There is also the `contenteditable="true"` attribute.

**Comment by The-Compiler** [comment] 2020-06-24 09:33
Closing this as a duplicate of #253/#5349.

**Closed by The-Compiler** 2020-06-24 09:33 UTC
Labels: component: keyinput, status: needs triage
