### ISSUE TITLE
Cookies being cleared after returning to last page

### ISSUE THREAD

**Issue by mortezadadgar** [qutebrowser/qutebrowser#6832] opened 2021-11-19 14:03 UTC
**Version info**:

qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
not necessary
 
**How to reproduce**

this only occurs with content.cookies.accept = "no-3rdparty"
1. open duckduckgo change theme to dark so it would be noticeable if the cookie if cleared
2. search a website that always fail to load(in my case facebook because I'm living in a restricted country)
3. open it you will get `This site can’t be reached` error page
4. return back to duckduckgo with H
5. now the webpage theme is light

**Comment by toofar** [comment] 2021-11-19 21:50
I think I've seen this with tab crashes. As in 1) be logged in to site 2) have tab crash 3) go back from error page 4) site thinks you aren't logged in. In that that case just reloading the tab makes it pick up my cookies again.
So if you can reliably reproduce this can you try reloading the page once you go back to the duckduckgo one and see if the dark theme comes back?

**Comment by mortezadadgar** [comment] 2021-11-20 04:57
@toofar yes reloading the page bring back cookies

**Comment by toofar** [comment] 2021-11-20 07:39
Thanks, I didn't realise it only happened if you are blocking third party cookies. I raised a bug upstream https://bugreports.qt.io/browse/QTBUG-98461 and I'll close this because it doesn't seem to be an issue with qutebrowser itself.
It turns out there is a workaround we can apply, but I'm not sure it's a good idea. I'll re-open this if the Qt people say we are holding the cookie filter wrong.

**Closed by toofar** 2021-11-20 07:39 UTC
Labels: qt, priority: 2 - low, component: QtWebEngine, bug: behavior
