### ISSUE TITLE
Flatpak regressions

### ISSUE THREAD

**Issue by ykgmfq** [qutebrowser/qutebrowser#4879] opened 2019-07-01 19:02 UTC
This issue aims to collect all regressions resulting from the sandboxing done by Flatpak.

The main restriction is that qutebrowser may only call binaries *inside* the sandbox, i.e. the ones it ships with. Below are some suggestions on how to remedy these problems.

## Download dispatcher
Binary outside the sandbox. If `download` is called with an argument, an error should be shown. If an override is saved in the config, it should be ignored and a warning shown. Always use `QDesktopServices.openUrl()`.

## Download file name question
The qutebrowser file question fails silently for `$HOME`. `QFileDialog` supports the https://github.com/flatpak/xdg-desktop-portal, use that for Flatpak?

## Editor
Binary outside the sandbox. Use `QDesktopServices.openUrl()` so that the user can choose their editor from the portal.

## Widevine CDM
Not free software, so not possible to ship through Flathub?

**Comment by The-Compiler** [comment] 2019-07-17 11:07
Is spawning `flatpak-spawn` via `:spawn` supposed to work? See https://www.reddit.com/r/qutebrowser/comments/ce5wba/anyone_using_qutebrowser_flatpak_having_trouble/

**Comment by tinywrkb** [comment] 2021-04-14 12:50
@The-Compiler I don't feel comfortable about using `flatpak-spawn` to execute code in the host environment, this can have some serious security implications.  
This means we are giving access to run every command available in the host system.  
Access to [org.freedesktop.Flatpak](https://github.com/flatpak/flatpak/blob/master/data/org.freedesktop.Flatpak.xml) is also given.  
In other Flatpak packages? maybe. In a web browser package? no.  


If the user feels comfortable with this then it can be enabled easily with a Flatpak override, the relevant userscript can be changed to use `flatpak-spawn`, or the user can place a flatpak-spawn wrapper in some folder accessible in the sandbox, and prepend it to PATH when starting the app.

I would rather add to the packaging the most useful and popular utilities that are used with the installed userscripts, and maybe also allow filesystem access to the user configuration folders of those utilities (basically bind-mounts into the sandbox).  
I'm not sure yet how to handle dmenu/rofi.

We're hitting here some Flatpak limitations, it would be nice if xdg-open would allow requesting a specific app instead of just the user default app. Even the [OpenURI Portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.OpenURI) doesn't allow that.  
Why this is matter? because this way we could have for example a userscript or a command in qutebrowser to open YouTube videos in MPV without needing to give access to execute commands on the host or packaging MPV with the app.

**Comment by The-Compiler** [comment] 2021-04-15 06:28
> I don't feel comfortable about using `flatpak-spawn` to execute code in the host environment, this can have some serious security implications.
> This means we are giving access to run every command available in the host system.
> Access to [org.freedesktop.Flatpak](https://github.com/flatpak/flatpak/blob/master/data/org.freedesktop.Flatpak.xml) is also given.
> In other Flatpak packages? maybe. In a web browser package? no.

To be fair, if it was possible for e.g. websites to execute commands (or anything along those lines), that'd be a big issue either way, since only a minority of qutebrowser users uses Flatpak (at least I'm assuming).

But I totally understand - there's definitely value in an additional sandboxing layer, and allowing to spawn arbitrary things makes that sandboxing near useless.

So I wonder what's left to do here for qutebrowser?

- I think the download dispatcher is done (2d2c59c6b8ff1d48e30a5f0a9bbe55a3481b0b76).
- Not sure what's happening for downloads exactly. When I enter my home dir as download destination, nothing ends up there. I suppose like mentioned in the OP, qutebrowser should fall back to `QFileDialog` there.
- Spawning an external editor (`Ctrl+e` in an input field) fails. Not sure what we could do about that. I don't think using `QDesktopServices.openUrl()` will work, as qutebrowser will need to know when the editor closed (so it can update the text field and stop watching the files for changes).

**Comment by tinywrkb** [comment] 2021-04-19 10:51
Sorry for the late response.

>To be fair, if it was possible for e.g. websites to execute commands (or anything along those lines), that'd be a big issue either way, since only a minority of qutebrowser users uses Flatpak (at least I'm assuming).

I personally believe that enabling flatpak-spawn host access is wrong, but your opinion as the developer takes precedence here. 
 If you think that this makes the app less usable and you don't agree with this packaging decision then I'll enable this capability.  
My belief is that Flatpak should be seen as a distribution channel first. This way it will promote developers to officially distribute, support, and maintain their apps via Flathub.  
Sandboxing takes a back seat compared to usability and distribution, it can always be improved later on when missing APIs are added to XDG Portal.

> Not sure what's happening for downloads exactly. When I enter my home dir as a download destination, nothing ends up there. I suppose like mentioned in the OP, qutebrowser should fall back to QFileDialog there.

Well, that's because we're limiting filesystem access so only xdg-download, xdg-music, xdg-pictures, and xdg-videos are bind-mounted on the respected targets in the sandbox.  
I think that the rest of the filesystem is part of the initial rootfs tmpfs in the mount namespace created by bubblewrap. These folders are created with the `--dir` bubblewrap option as can be seen when appending `-vv` to `flatpak run`.

Maybe qutebrowser can offer the option to open the system file dialog and this should go through the file portal, offering the option to save files to host locations that are not accessible by default by the sandbox.  
And there's always the override option so the user can give more permissive filesystem access.

> Spawning an external editor (Ctrl+e in an input field) fails. Not sure what we could do about that. I don't think using QDesktopServices.openUrl() will work, as qutebrowser will need to know when the editor closed (so it can update the text field and stop watching the files for changes).

Another XDG Portal oversight, there are a bunch of other apps that need this feature as some of the note-taking apps (e.g. Joplin). I'm in favor of documenting in a wiki page or somewhere else how to enable flatpak-spawn permissions so the user will be aware of this option, removing some of the sandbox restrictions but having this feature working.

**Comment by The-Compiler** [comment] 2021-04-19 10:58
> I personally believe that enabling flatpak-spawn host access is wrong, but your opinion as the developer takes precedence here.

I'm not necessarily saying it's wrong. If it's easy for users to enable, I think it's good to have it disabled by default. At least, so far nobody complained about it :slightly_smiling_face: 

> Maybe qutebrowser can offer the option to open the system file dialog and this should go through the file portal, offering the option to save files to host locations that are not accessible by default by the sandbox.

Yep - see #1365. The remaining question is whether this should be default on Flatpak (once implemented). I guess if it allows safely writing downloads to host locations, that'd be preferrable to the custom qutebrowser prompt.

> I'm in favor of documenting in a wiki page or somewhere else how to enable flatpak-spawn permissions so the user will be aware of this option, removing some of the sandbox restrictions but having this feature working.

Certainly sounds good to me!

**Comment by tinywrkb** [comment] 2021-04-19 11:19
> Yep - see #1365. The remaining question is whether this should be default on Flatpak (once implemented).

Can this be added as an entry to the "Save file to" widget here?

![save_file_widget](https://user-images.githubusercontent.com/44030034/115227468-2a3fa300-a119-11eb-9c5c-62b136f2a840.png)

so instead of directly opening the native file picker, we will first go through this qutebrowser's widget first?  
The user should also have the option to set the native file picker as the default.  
The reasoning is the average qutebrowser's user probably prefers avoiding the floating system file dialog.

**Comment by The-Compiler** [comment] 2021-04-19 11:23
Not sure if that's possible to implement due to how the dialog works, but it's worth a look. Let's close this in favor of #1365 now though, as I think everything else is taken care of.

**Closed by The-Compiler** 2021-04-19 11:23 UTC
Labels: bug: behavior, priority: 2 - low

**Comment by Narice** [comment] 2022-11-17 20:46
Hi! I had some problems on NixOS using the Flatpak version of qutebrowser.
Thought I'd mention them on this thread. Tell me if it is better if seperate issues should be opened.

The **pdf viewer is not working by default** (using --temp-basedir) and **color emojis do not work** and are replaced by black and white emojis.
Both of these are not problems on my distribution's package.

Pdf viewer:
![image](https://user-images.githubusercontent.com/31109099/202555696-1d39f75b-acac-4753-80fc-0700caaa5004.png)
![image](https://user-images.githubusercontent.com/31109099/202555938-d9fb41dd-4ef5-4578-8b5a-294766c7d8e0.png)

Emoji support:
![image](https://user-images.githubusercontent.com/31109099/202555412-4b63d63e-457d-40e9-abef-9959e7558f2a.png)
![image](https://user-images.githubusercontent.com/31109099/202555467-23890333-3cfa-4c02-833e-c7e7bf59578e.png)

**Comment by Narice** [comment] 2022-11-17 20:47
non flatpak qutebrowser version: https://paste.the-compiler.org/view/41c543d6
flatpak qutebrowser version: https://paste.the-compiler.org/view/816cfce7

**Comment by tinywrkb** [comment] 2022-11-18 19:20
If you're hitting Flatpak specific issues, then please file a ticket for each of such bug in the [Flatpak packaging repository for qutebrowser](https://github.com/flathub/org.qutebrowser.qutebrowser).  
Make sure to detail reproducing steps.  

Be advised that we might see better handling of system fonts when the app will switch to a Freedesktop 22.08 based runtime (I'm not sure yet when). That's due to Fontconfig to 2.14 which adds configs for Noto Fonts, though I'm not sure about Noto Emoji.  
And there's also the newly added font folders detection based on `XDG_DATA_DIRS` value.

Also note that I might not be able to look into this before mid-Dec.

**Comment by Narice** [comment] 2022-11-18 19:50
Oh! sorry, I didn't know there was a specific repo for it, thanks!
I'll make an issue on that repo if the issue isn't already reported there yet.
And no worries about timing :yum:
