### ISSUE TITLE
Hint color is always black, could not be set on macOS Big Sur

### ISSUE THREAD

**Issue by junwei-wang** [qutebrowser/qutebrowser#5928] opened 2020-12-02 10:22 UTC
**Version info**:
https://paste.the-compiler.org/view/911db073

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

Setting `c.colors.hints.fg = 'some color'` does not work, the color used is always black. 
It does not work both using neither yaml nor config.py
How setting `c.colors.hints.match.fg` does work.

When use `--temp-basedir` from command and setting the color via yaml, I can see in the terminal
```
11:16:39 INFO: Saved session default.
11:16:39 WARNING: Could not parse stylesheet of object Message(0x7ff3cad4ffd0)
11:16:51 INFO: Saved session default.
11:16:51 WARNING: Could not parse stylesheet of object Message(0x7ff3cebb50d0)
11:17:11 INFO: Saved session default.
11:17:11 WARNING: Could not parse stylesheet of object Message(0x7ff3cecacd00)
```

**How to reproduce**

Nothing particular but installing qutebrowser via `brew cask install qutebrowser`

**Comment by The-Compiler** [comment] 2020-12-02 10:24
Duplicate of #5663

**Closed by The-Compiler** 2020-12-02 10:24 UTC
