### ISSUE TITLE
Prev/next page hotkeys don't respect base URL

### ISSUE THREAD

**Issue by rr-** [qutebrowser/qutebrowser#4195] opened 2018-09-06 15:13 UTC
<details>
<summary>Qutebrowser version (click to expand)</summary>
<pre>
qutebrowser v1.4.1
Git commit: b962c5c4d (2018-08-13 14:33:53 -0700)
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.12
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.17.14-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/rr-/.cache/qutebrowser
config: /home/rr-/.config/qutebrowser
data: /home/rr-/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
</pre></details>

### Bug description

1. Consider a page:
    - containing `<a href="post/35" rel="next">`
    - containing `<base href="/">`
    - located at `https://example.com/post/34`
2. Navigate to the next page (<kbd>&gt;</kbd>)
3. Get redirected to `https://example.com/post/post/35` rather than `https://example.com/post/35`

**Comment by The-Compiler** [comment] 2018-09-06 15:16
Duplicate of #739

**Closed by The-Compiler** 2018-09-06 15:16 UTC
