### ISSUE TITLE
MacOS dmg does not include scripts folder

### ISSUE THREAD

**Issue by fzf** [qutebrowser/qutebrowser#5027] opened 2019-09-17 00:08 UTC
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/ab85755a

**Does the bug happen if you start with `--temp-basedir`?**:

**Description**
The FAQ states:

`Use dictcli.py script to install dictionaries. Run the script with -h for the parameter description.`

When installing on MacOS this script is not included

**How to reproduce**

**Comment by The-Compiler** [comment] 2019-09-17 05:16
Duplicate of #3321

**Closed by The-Compiler** 2019-09-17 05:16 UTC
