### ISSUE TITLE
per-domain/URL-pattern default to passthrough

### ISSUE THREAD

**Issue by hyiltiz** [qutebrowser/qutebrowser#4960] opened 2019-08-09 18:28 UTC
I would like to set the default input mode to `passthrough` for some websites, e.g. `*.gmail.com`, `email.*.edu` and `localhost:8787` (RStudio). Reading #27 and issues linked to it and the documentations, it seems I could edit `config.py` using the command `enter-mode passthrough`, but the documentation only shows how to change *settings* based on domain/URL, but not run commands. If this is an implemented feature, could we include a few lines in the official documentation (and here)?

**Version info (see `:version`)**:
```
qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.4
Qt: 5.11.3
PyQt: 5.11.3

sip: 4.19.18
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: Qt5CTProxyStyle
Platform: Linux-4.19.0-5-amd64-x86_64-with-Debian-testing-buster, 64bit
Linux distribution: Debian GNU/Linux bullseye/sid (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/hyiltiz/.cache/qutebrowser
config: /home/hyiltiz/.config/qutebrowser
data: /home/hyiltiz/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```

**Comment by toofar** [comment] 2019-08-10 02:30
Duplicate of https://github.com/qutebrowser/qutebrowser/issues/35
There is no such facility at the moment.

**Closed by toofar** 2019-08-10 02:30 UTC

**Comment by hyiltiz** [comment] 2019-08-10 03:10
Great, thanks! I'll stop tweaking and hacking.

**Comment by smautner** [comment] 2019-08-26 15:14
I put this in the tabbedbrowser class.

```
if "localhost:888" in  str(tab.url()): 
            modeman.enter(self._win_id, usertypes.KeyMode.passthrough,reason='evil hack', only_if_normal=False)
```

**Comment by iNecas** [comment] 2022-04-29 09:06
To save some time anyone searching how to configure it:

```python
with config.pattern("example.com") as p:
    p.input.mode_override = "passthrough"
```

This is very useful feature! Thanks for getting it in!
