### ISSUE TITLE
Show matching hints for matching urls on same page

### ISSUE THREAD

**Issue by tobip** [qutebrowser/qutebrowser#4767] opened 2019-05-09 08:42 UTC
On some pages there are many urls and therefore many hints, which end up being a long combination of up to three or four letters.

Actually, in many cases there are multiple hrefs pointing to an identical url. In this case I think it would be a great relief if also the hints are identical. In this case less unique hints are being needed on every page, making them shorter and the overall use of following hints easier.

At the same time, by viewing the hints that way, I could also understand if two hrefs on one website are going to lead to the same url.

If i missed a reason of why this can or will not get implemented I would love to understand the situation, maybe you can give me some more details on that.

**Comment by The-Compiler** [comment] 2019-05-09 08:45
This is already mentioned in #71, so I'm going to close this as a duplicate. However, note that "same URL" doesn't necessarily mean "same thing happens when clicking it" thanks to JavaScript click handlers, so it's (unfortunately) not really straightforward to find a solution which merges enough but not too much.

**Comment by The-Compiler** [comment] 2019-05-09 08:45
Duplicate of #71

**Closed by The-Compiler** 2019-05-09 08:45 UTC
