### ISSUE TITLE
Bypassing proxy for certain websites

### ISSUE THREAD

**Issue by fat-fighter** [qutebrowser/qutebrowser#4594] opened 2019-02-18 09:01 UTC
Hi! I am loving qutebrowser so far, but there's one thing I feel is missing from this amazing software. Without changing the system proxy settings, would it be possible to set a proxy in qutebrowser but bypassing the same for some websites (such as localhost or my local university websites). In order to visit some websites, I have to change the proxy on the fly and such a setting would be awesome. I wanted to ask (request) whether it is possible to have this feature in qutebrowser. If possible (and with probably a lot of guidance) I would like to help implement this in.

**Comment by ninewise** [comment] 2019-02-18 09:09
It isn't possible yet, but might not be too hard to get in. It's still on the TODO list for [per domain settings](https://github.com/qutebrowser/qutebrowser/issues/3636).

**Comment by The-Compiler** [comment] 2019-02-18 13:11
Duplicate of #3636

**Closed by The-Compiler** 2019-02-18 13:11 UTC
