### ISSUE TITLE
Leaves insert mode when URL is changed (via JS history API) while typing

### ISSUE THREAD

**Issue by AndrewBelt** [qutebrowser/qutebrowser#4562] opened 2019-02-02 23:45 UTC
**Version info (see `:version`)**: v1.5.2

**Does the bug happen if you start with `--temp-basedir`?** (if applicable): Yes

**Description**
A common trend in JS-powered search boxes is to update the URL of the page as the user is typing, so that copying the URL also copies the search context. However, Qutebrower, upon noticing that the URL changes, exits insert mode. This makes it impossible to enter text in these boxes unless you enter insert mode for every letter you type, or you enter Passthrough mode. 

**How to reproduce**
- https://github.com/ when logged in, using the "Repositories" field
- https://vcvrack.com/plugins.html when using the Search field
- etc, I can find more if you want

**Comment by toofar** [comment] 2019-02-03 00:51
duplicate of https://github.com/qutebrowser/qutebrowser/issues/3596

**Closed by toofar** 2019-02-03 00:51 UTC
