### ISSUE TITLE
Text with `font-family: monospace` renders in a variable width font on OSX

### ISSUE THREAD

**Issue by Lanny** [qutebrowser/qutebrowser#5206] opened 2020-01-22 06:04 UTC
**Version info (see `:version`)**:

https://paste.the-compiler.org/view/2b9f18e3

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**

Any element which has `font-family: monospace` without specifying a particular typeface renders in a variable width font. See screenshot:

https://i.imgur.com/6qrabNa.png

I suspect it's related to this:

https://github.com/qutebrowser/qutebrowser/commit/6cceadd9a79a83c5c351d633e486149af1746cbc

I should be able to take a look at it in a couple of days but wanted to make a ticket in case it's something obvious, given it was a recent change.

**How to reproduce**

Load any page with text where `font-family: monospace` applies, this one is an example: https://docs.python.org/3/library/venv.html

**Comment by The-Compiler** [comment] 2020-01-22 06:50
I can't reproduce: 

![image](https://user-images.githubusercontent.com/625793/72871655-c21ec900-3ceb-11ea-8027-f433949a1264.png)

Note that you're running the v1.9.0 release, which does not contain 6cceadd.

How exactly are you launching qutebrowser when you tried with `--temp-basedir`?

**Comment by Lanny** [comment] 2020-01-22 06:58
I did `/Applications/qutebrowser.app/Contents/MacOS/qutebrowser --temp-basedir`.

As an aside, I tried `.venv/bin/python3 -m qutebrowser --temp-basedir` from source but I get:

```
qutebrowser needs QtWebKit or QtWebEngine, but neither could be imported!
The errors encountered were:
QtWebKit: cannot import name 'QtWebKit' from 'PyQt5' (/Users/lanny/qutebrowser/.venv/lib/python3.7/site-packages/PyQt5/__init__.py)
QtWebEngine: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (/Users/lanny/qutebrowser/.venv/lib/python3.7/site-packages/PyQt5/__init__.py)
```

But it doesn't seem to have any issue finding Qt dependencies if I leave off the `--temp-basedir`.

**Comment by The-Compiler** [comment] 2020-01-22 07:09
That's odd.

Can you please open the `:inspector`, then do right-click -> inspect on the (non-)monospace text and give me a screenshot of the "computed style" tab? Here's what it looks like for me:

![image](https://user-images.githubusercontent.com/625793/72872762-699cfb00-3cee-11ea-9f95-172245cb5136.png)

Also, does something like `:set fonts.web.family.fixed Monaco` (or some other monospace font which is installed) change anything?

**Comment by Lanny** [comment] 2020-01-22 07:19
I see the same thing in the inspector:

![Screen Shot 2020-01-21 at 11 14 48 PM](https://user-images.githubusercontent.com/2343714/72873209-0e461b00-3ca4-11ea-9f27-db668e7cbb1e.png)

Same thing happens if no styling at all is applied to a `pre` tag, so it only gets the user-agent style of `font-family: monospace`.

`:set fonts.web.family.fixed Monaco` ends up rendering everything you'd expect to be in monospace in Monaco, reflected in the "Rendered Fonts" section.

**Comment by The-Compiler** [comment] 2020-01-22 07:22
Okay, so the main question is why the underlying Chromium picked Times as a monospace font... If there are other people who could test with macOS 10.15 that'd be great, I only have 10.13 available.

Do you happen to have Google Chrome available to test? If so, I assume it looks correct there.

**Comment by Lanny** [comment] 2020-01-22 07:32
Yes, slightly out of date Google Chrome (79.0.3945.88) end up picking Courier in the same places

**Comment by The-Compiler** [comment] 2020-01-22 07:37
If you start with `--temp-basedir`, then do `:debug-console`, and there run `from PyQt5.QtWebEngineWidgets import QWebEngineSettings` and `QWebEngineSettings.globalSettings().fontFamily(QWebEngineSettings.FixedFont)`, what do you get? I do get `'Monaco'` FWIW.

**Comment by Lanny** [comment] 2020-01-22 07:42
I get the empty string for some reason:

```
>>> from PyQt5.QtWebEngineWidgets import QWebEngineSettings
>>> QWebEngineSettings.globalSettings().fontFamily(QWebEngineSettings.FixedFont)
''
>>> QWebEngineSettings.FixedFont
1
>>> 
```

**Comment by The-Compiler** [comment] 2020-01-22 08:19
Could you please try this?

```
from PyQt5.QtGui import QFont, QFontDatabase
 
font1 = QFont()
font1.setStyleHint(QFont.Monospace)
print(font1.defaultFamily())

font2 = QFont()
font2.setStyleHint(QFont.TypeWriter)
print(font2.defaultFamily())
 
font3 = QFontDatabase.systemFont(QFontDatabase.FixedFont)
print(font3.family())
```

(it looks like you'll need to copy it line for line for it to work - sorry for that!)

**Comment by Lanny** [comment] 2020-01-22 17:42
No problem, the output I get is:

```
>>> from PyQt5.QtGui import QFont, QFontDatabase

>>> font1 = QFont()

>>> font1.setStyleHint(QFont.Monospace)

>>> print(font1.defaultFamily())


>>> font2 = QFont()

>>> font2.setStyleHint(QFont.TypeWriter)

>>> print(font2.defaultFamily())


>>> font3 = QFontDatabase.systemFont(QFontDatabase.FixedFont)

>>> print(font3.family())

.SF NS Mono
>>> 
```

**Comment by The-Compiler** [comment] 2020-01-22 17:43
Is the dot in `.SF NS Mono` part of the output? Does setting `fonts.web.family` to `SF NS Mono` (or with the dot, if that really was in there) give you a suitable font on the website?

**Comment by Lanny** [comment] 2020-01-22 17:51
The dot really is part of the output, without the `print()` you get:

```
>>> from PyQt5.QtGui import QFont, QFontDatabase
>>> font3 = QFontDatabase.systemFont(QFontDatabase.FixedFont)
>>> font3.family()
'.SF NS Mono'
```

Setting `fonts.web.family` to any of ".SF NS Mono", "SF NS Mono", or "SF Mono" doesn't do anything, visually at least.

**Comment by The-Compiler** [comment] 2020-01-22 17:53
Sorry, I meant `fonts.web.family.fixed` above - `fonts.web.family` doesn't exist.

**Comment by The-Compiler** [comment] 2020-01-22 18:06
Fun, I just [found](https://github.com/tcltk/tk/commit/09fe4a9aaf45f55440dcd7af939040cc492c8acc) this:

```
#if 0

    /*
     * In macOS 10.15.1 Apple introduced a bug in NSFontManager which caused
     * it to not recognize the familyName ".SF NSMono" which is the familyName
     * of the default fixed pitch system fault on that system.  See bug [855049e799].
     * As a workaround we call [NSFont userFixedPitchFontOfSize:11] instead.
     * This returns a user font in the "Menlo" family.
     */

    nsFont = (NSFont*) CTFontCreateUIFontForLanguage(fixedPitch, 11, NULL);
#else
    nsFont = [NSFont userFixedPitchFontOfSize:11];
#endif
```

I suppose I could have a similar workaround in qutebrowser as well... Given that they originally only removed the `.SF ` prefix, can you please check whether `NS Mono` works?

Also, adding the v1.10.0 milestone as this would likely affect all UI fonts as well with the upcoming release and 6cceadd.

**Comment by Lanny** [comment] 2020-01-23 03:57
Setting `fonts.web.family` to "NS Mono", or "SF Mono" doesn't seem to do anything either, at least on my system. Menlo is a nice font IMO, previously the system font but still installed in newer distros. Does Qt expose the result of [userFixedPitchFont](https://developer.apple.com/documentation/appkit/nsfont/1531381-userfixedpitchfont) anywhere? That yields Menlo for me:

```
 14> let k = NSFont.userFixedPitchFont(ofSize: 0)
k: NSFont? = 0x000000010061e870 {
  baseUIFont@0 = {
    baseNSFont@0 = {
      baseNSObject@0 = {
        isa = NSCTFont
      }
    }
  }
}
 15> k?.fontDescriptor
$R5: NSFontDescriptor? = 0x0000000100208e60 {
  ObjectiveC.NSObject = {
    baseNSFontDescriptor@0 = {
      baseNSObject@0 = {
        isa = NSCTFontDescriptor
      }
      _attributes = {}
      _reserved1 = nil
      _reserved2 = {}
      _reserved3 = nil
      _reserved4 = {}
      _reserved5 = {}
    }
    _attributes = 2 key/value pairs {
      [0] = {
        key = "NSFontSizeAttribute"
        value =
      }
      [1] = {
        key = "NSFontNameAttribute"
        value = "Menlo-Regular"
      }
    }
    _reserved1 = {}
    _reserved2 = nil
    _reserved3 = {}
    _reserved4 = nil
    _reserved5 = "CTFontPostScriptName"
  }
}
```

**Comment by Lanny** [comment] 2020-01-23 04:58
Digging around Qt a bit I found this:

https://github.com/qt/qtbase/blob/0c29ebe374caad7e29c6a3d35c72c4eddaacc6af/src/platformsupport/fontdatabases/mac/qcoretextfontdatabase.mm#L695

It looks like `QFontDatabase.FixedFont` resolves to Apple's `kCTFontUIFontUserFixedPitch` (assuming the Cocoa theme) which is deprecated. Seems (to me, and being honest I don't know a whole lot about the subject) like this is a fix that should happen in Qt.

Maybe we could do the Monospace style hint route and fall back to hardcoded Courier (which I think pretty much everyone has?)

**Comment by The-Compiler** [comment] 2020-01-23 13:34
If you do `:set fonts.monospace "SF Mono"`, does the UI end up being a non-fixed font as well? What about `"SFMono"` or `"NS Mono"` or `"NSMono"` or `"SF NS Mono"` or the original `".SF NS Mono"`?

I don't think qutebrowser can do any macOS-specific stuff here, and I know too little about the subject to open a Qt bug report.

> Maybe we could do the Monospace style hint route and fall back to hardcoded Courier (which I think pretty much everyone has?)

I agree we should have some kind of workaround here. Unfortunately, I don't know a way how I can actually find out whether a given font family will work or not - so the best thing qutebrowser could do is replacing `.SF NS Mono` (which clearly doesn't work) with something that does. I'd prefer something which actually ends up with that font, but if none of the above variants work, I guess we can just use `Menlo` if that font is returned on macOS.

**Comment by Lanny** [comment] 2020-01-23 17:54
After starting up and navigating to a page, but no change in settings:

![Screen Shot 2020-01-23 at 9 44 58 AM](https://user-images.githubusercontent.com/2343714/73009425-6b85bd80-3dc5-11ea-91fe-1ff65964402e.png)

If I set `fonts.monospace` to anything that isn't really a font (e.g. `:set fonts.monspace fooooobar`) I get this, which I also get with all of the above font family names EXCEPT
![Screen Shot 2020-01-23 at 9 45 18 AM](https://user-images.githubusercontent.com/2343714/73009424-6aed2700-3dc5-11ea-9147-53201fb7f8c8.png)

The original `".SF NS Mono"`, which produces this:

![Screen Shot 2020-01-23 at 9 47 39 AM](https://user-images.githubusercontent.com/2343714/73009423-6aed2700-3dc5-11ea-8e22-9f53cc49a254.png)

It ends up somehow effecting the background color and scroll bar of the command pane, as well as the bottom bar. Not sure if it comes through on the screenshot but thee usual content is there, it's just light-gray-on-white and barely legible.

Not sure what's going on there. Setting `fonts.web.family.monospace` has no visible effect with any of these, including `".SF NS Mono"`.

**Comment by The-Compiler** [comment] 2020-01-23 18:03
Thanks for all the testing and the great writeup :heart: I assume doing `:set fonts.monospace Menlo` gives you a good UI font as well? I'll just go with that then...

I can reproduce the issue with `".SF NS Mono"` with v1.9.0 but not with the latest master branch. It looks like qutebrowser produced `font: 10pt .SF NS Mono;` (with missing quotes), which causes the Qt CSS to be invalid, so Qt falls back to the default styling.

**Comment by The-Compiler** [comment] 2020-01-24 09:19
Oh, can you please also show the result of:

```python
from PyQt5.QtGui import QFontDatabase
db = QFontDatabase()
print(db.families())
```

in the debug console? I still wonder whether we can find that `.SF NS Mono` font under some name.

**Comment by The-Compiler** [comment] 2020-01-24 09:47
Hmm, wait, I just found this bug / fix:

- [[QTBUG-79900] QFontDatabase::systemFont(QFontDatabase::FixedFont) returns proportional font - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-79900)
- [CoreText: Fix getting system fonts on recent macOS/iOS versions (Ie375c8c2) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/282837)

This landed in Qt 5.14, while the v1.9.0 release you're using is still shipping with Qt 5.12. So if we're lucky, this already works without any workarounds on qutebrowser's side!

I packaged a prerelease to test, could you please give it a try? https://qutebrowser.org/tmp/qutebrowser-1.10.0-pre.dmg - you might want to create a backup of `~/Library/Application Support/qutebrowser` just to make sure you can downgrade to the normal release again, then run it (probably with `--temp-basedir`). With that release, do you get proper monospace font both for the websites and UI?

**Comment by Lanny** [comment] 2020-01-25 01:26
Sorry for the delay! Good news is the prerelease fixes the issue, it ends up rending menlo which I'm happy with.

For the record here's my list of families from the fonts database:

https://paste.the-compiler.org/view/664f7820

'.SF NS Mono' is on there but even if I do `:set fonts.web.family.fixed '.SF NS Mono'` on v1.9.0 I still get times.

**Comment by The-Compiler** [comment] 2020-01-25 12:39
> Sorry for the delay! Good news is the prerelease fixes the issue, it ends up rending menlo which I'm happy with.

As (hopefully) the last test, could you show the output of https://github.com/qutebrowser/qutebrowser/issues/5206#issuecomment-577060854 again with the prerelease?

Currently, the default for `fonts.web.family.fixed` uses a different way to get the font than `fonts.default_family` does, so it'd be nice to unify that code.

**Comment by Lanny** [comment] 2020-01-25 18:47
Sure thing, here's what I get:

```
>>> from PyQt5.QtGui import QFont, QFontDatabase

>>> font1 = QFont()

>>> font1.setStyleHint(QFont.Monospace)
>>> print(font1.defaultFamily())
Menlo
>>> font2 = QFont()
>>> font2.setStyleHint(QFont.TypeWriter)
>>> print(font2.defaultFamily())
American Typewriter
>>> font3 = QFontDatabase.systemFont(QFontDatabase.FixedFont)
>>> print(font3.family())

.SF NS Mono
>>> 
```

So it looks like style hints are fixed/patched for macOS 10.15 but the issue with `.systemFont()` giving unusable values still exists.

Also as a side note, I just noticed there's a similar issue of `font-family: sans-serif` getting some ".something" unrenderable family and falling back to times in v1.9.0 which is also fixed in the prerelease you made.

**Comment by The-Compiler** [comment] 2020-01-25 18:51
Hmm, wait, I just noticed the fix above landed in Qt 5.14.1 (which isn't released yet), not 5.14.0 like I originally assumed... I'll get back to this once it's out. Thanks again for all the testing!

**Comment by The-Compiler** [comment] 2020-01-31 22:06
Qt/PyQt got updated now, so I built another pre-release:

https://qutebrowser.org/tmp/qutebrowser-1.10.0-pre2.dmg

Could you start that with `--temp-basedir` again, confirm you see Qt 5.14.1 in `:version` and confirm you get a sensible (and fixed-width) font for both the user-interface and websites?

Also, do the commands from above now not give you `.SF NS Mono` anymore?

**Comment by Lanny** [comment] 2020-02-01 23:14
Sure thing. :version reports that this build is using Qt and PyQt 5.14.1. This is what it looks like:

![Screen Shot 2020-02-01 at 2 50 01 PM](https://user-images.githubusercontent.com/2343714/73600277-c1afda80-4502-11ea-8c27-35021f734021.png)

Inspector reports the rendered font for `font-family: monospace` text on a page is Menlo. Debug console output is:

```
>>> from PyQt5.QtGui import QFont, QFontDatabase
>>> font1 = QFont()
>>> font1.setStyleHint(QFont.Monospace)
>>> font2 = QFont()
>>> font2.setStyleHint(QFont.TypeWriter)
>>> print(font2.defaultFamily())
American Typewriter
>>> font3 = QFontDatabase.systemFont(QFontDatabase.FixedFont)
>>> print(font3.family())
.SF NS Mono
>>> 
```

`:set fonts.web.family.fixed '.SF NS Mono'` still ends up with Menlo getting rendered for some reason.

The UI font seems to have changed slightly vs v1.9.0 :

![Screen Shot 2020-02-01 at 3 07 42 PM](https://user-images.githubusercontent.com/2343714/73600439-f58bff80-4504-11ea-9b2b-82cab267ab10.png)

Left is the prerelease, right is the v1.9.0 install I use normally. I like the previous value a little better personally but it's minor and I think the new font is seems perfectly acceptable. Just wanted to mention that it seemed to have changed.

**Comment by The-Compiler** [comment] 2020-02-02 20:20
Okay - I'm considering this fixed then, I don't think there's a good reason for adding a workaround to qutebrowser itself.

Thanks again for all the testing and your patience - I'll release v1.10.0 soon (right now, if everything goes according to plan).

**Closed by The-Compiler** 2020-02-02 20:20 UTC
Labels: os: macOS, status: can't reproduce, status: needs triage

**Comment by CL-Jeremy** [comment] 2021-03-19 10:41
I reached this issue from Google searching for `.SF NS Mono`. I was also trying to find a solution myself, knowing that front-end frameworks like Bootstrap have adopted `SFMono-Regular` (the font's PostScript name, which is never used unless the font is installed by the user, but has worked since at least 10.13 if the user does install it separately, which many actually do, hence the adoption).

It's very interesting to see that, while Safari (and for that matter, Epiphany, which is basically vanilla WebKitGTK) happily matches dotted fonts (they are proper font names on macOS - WebKit requires quotes though, unlike Chromium/Firefox), it apparently won't match this family name, not even under Linux. I suppose this has something to do with the actual OpenType name table entries, but that's not something browsers should normally rely on (rather than matching via proper system API). I'm sharing my test results on Linux (Manjaro GNOME Unstable), which I believe could help people understand the situation better.

This screenshot demonstrates `.Hiragino Kaku Gothic Interface`, the default Japanese system UI font, a scaled down version of the proper "Hiragino Kaku Gothic ProN"/"Hiragino Sans" (10.11+) to match the height of Western glyphs.
![Bildschirmfoto von 2021-03-19 10-48-48](https://user-images.githubusercontent.com/1714243/111762309-2eba3700-88a1-11eb-9fc7-fe6eae3e83db.png)

This is Epiphany, which, while not using Core Text on Linux, should resemble the behavior of WebKit on macOS to some extent.
![Bildschirmfoto von 2021-03-19 10-46-40](https://user-images.githubusercontent.com/1714243/111762347-38dc3580-88a1-11eb-800c-d4be95394404.png)

For this matter, Chromium works fine under Linux:
![Bildschirmfoto von 2021-03-19 10-58-28](https://user-images.githubusercontent.com/1714243/111763151-14cd2400-88a2-11eb-83bc-ff8089467868.png)

The situation is practically the same for `SFMono-Regular` (compatibility matching name for 10.13+):
![Bildschirmfoto von 2021-03-19 10-46-23](https://user-images.githubusercontent.com/1714243/111763349-552ca200-88a2-11eb-8ffb-3470f396b370.png)
![Bildschirmfoto von 2021-03-19 10-43-18](https://user-images.githubusercontent.com/1714243/111763507-84431380-88a2-11eb-8ad4-b008e5c429cd.png)

The only way to use this font under Linux is to source the 10.13 version of "SF Mono" from Xcode/Terminal.app and use its `SF Mono` family name. This matches the situation on macOS with `SFMono-Regular`:
![Bildschirmfoto von 2021-03-19 10-45-56](https://user-images.githubusercontent.com/1714243/111764166-367adb00-88a3-11eb-93e2-f9b0d0a35df3.png)
![Bildschirmfoto von 2021-03-19 10-58-03](https://user-images.githubusercontent.com/1714243/111764232-498dab00-88a3-11eb-8258-d66f2b185cf1.png)

Note that WebKit also matches family names without spaces (e. g. `TimesNewRoman` for "Times New Roman"), but that's purely non-standard and such usage should be discouraged.

Safari also added additional restriction to not match user-installed fonts unless an administrator installs it to `/Library/Fonts` at least since 10.15 (not tested earlier, might even be a bug due to the new partition layout, might have been solved later), so that could have explained some of the test results should people happen to have those fonts installed in `~/Library/Fonts`.
