### ISSUE TITLE
Narrow down to hinted fields when tabbing

### ISSUE THREAD

**Issue by Ambrevar** [qutebrowser/qutebrowser#3134] opened 2017-10-16 09:38 UTC
When I press `f`, hints get displayed. I can press `TAB` to browse them.
If I start completing hints (assuming they have more than one letter), the non-matching hints disappear.
From there, pressing `TAB` keeps browsing all fields, including the ones that are not hinted at.

It would be neat if `TAB` would only browse the still-hinted fields.

**Comment by The-Compiler** [comment] 2017-10-16 10:26
Duplicate of #1305

**Closed by The-Compiler** 2017-10-16 10:26 UTC
