### ISSUE TITLE
Regular Segmentation Fault

### ISSUE THREAD

**Issue by tdehaeze** [qutebrowser/qutebrowser#6401] opened 2021-04-18 15:07 UTC
**Version info**:
```
qutebrowser v2.1.1
Git commit: 
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.9.3
PyQt: 5.15.4

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.4.1
adblock: 0.4.3
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.8.335 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.0.1
Platform: Linux-5.10.30-1-MANJARO-x86_64-with-glibc2.33, 64bit
Linux distribution: Manjaro Linux (manjaro)
Frozen: False
Imported from /home/thomas/.local/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python
Qt library executable path: /home/thomas/.local/lib/python3.9/site-packages/PyQt5/Qt5/libexec, data path: /home/thomas/.local/lib/python3.9/site-packages/PyQt5/Qt5

Paths:
cache: /home/thomas/.cache/qutebrowser
config: /home/thomas/.config/qutebrowser
data: /home/thomas/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/thomas/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:04
```

**Does the bug happen if you start with `--temp-basedir`?**:
No

**Description**
For 2 or 3 weeks, qutebrowser often crashes without me knowing the cause of that.
When I look at the logs, I just see `Segmentation fault (core dumped)`.
It turns out, that I have this error each time (at least) I open my "homer" page (https://github.com/bastienwirtz/homer). When I look at the "javascript" console, I obtain an error described here: https://github.com/bastienwirtz/homer/issues/210

**How to reproduce**
Just put the following in `config.py`:

```
from qutebrowser.config.configfiles import ConfigAPI
from qutebrowser.config.config import ConfigContainer

import sys, os

config.load_autoconfig(True)
```

And go the demo homer page: https://homer-demo.netlify.app/

Cheers

**Comment by anmolmathias** [comment] 2021-04-19 06:04
Can confirm this has been happening to me too ever since I updated to v2.2.0. For me, the browser crashes whenever I open Spotify's web player and this error is not replicable when starting with`--temp-basedir`. 

Version dump for reference:
```
qutebrowser v2.2.0
Git commit: de4fff386 on master (2021-04-15 11:16:39 +0200)
Backend: QtWebEngine 5.15.2, Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.8.6
PyQt: 5.15.4

sip: 5.4.0
colorama: 0.4.4
jinja2: 2.11.3
pygments: 2.8.1
yaml: 5.4.1
adblock: 0.4.3
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1f  31 Mar 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.0.0
Platform: Linux-5.8.0-7642-generic-x86_64-with-glibc2.32, 64bit
Linux distribution: Pop!_OS 20.10 (ubuntu)
Frozen: False
Imported from /opt/qutebrowser/qutebrowser
Using Python from /opt/qutebrowser/.venv/bin/python3
Qt library executable path: /opt/qutebrowser/.venv/lib/python3.8/site-packages/PyQt5/Qt5/libexec, data path: /opt/qutebrowser/.venv/lib/python3.8/site-packages/PyQt5/Qt5

Paths:
cache: /home/nml/.cache/qutebrowser
config: /home/nml/.config/qutebrowser
data: /home/nml/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:03:58
```

**Comment by The-Compiler** [comment] 2021-04-19 09:20
This is most likely an issue in Qt or PyQt rather than qutebrowser itself.  Does something change if you enable `qt.workarounds.remove_service_workers` and `:restart`?

**Comment by tdehaeze** [comment] 2021-04-19 09:31
It indeed solves my issue

**Comment by The-Compiler** [comment] 2021-04-19 09:50
See #5634 then - the issue here is that Chromium's service worker cache gets corrupted, and that then causes crashes when accessing it.

I'd really like to make a proper upstream report about this, but so far, nobody has been able to find a clean way to reproduce it - what we've trying to find out since about a year is what actually causes the data corruption. The issue has never happened to me. If this is a site you visit often, could you disable the workaround again and see if you find some pattern if the issue reappears? Maybe it's related to some kind of unclean shutdown or something which causes the corruption, and then on the next start, the crash starts happening.

Closing this as a duplicate for now, as I suspect @anmolmathias' issue was the same thing.

**Closed by The-Compiler** 2021-04-19 09:50 UTC
Labels: bug: segfault/crash/hang, status: can't reproduce, status: needs triage

**Comment by tdehaeze** [comment] 2021-04-19 09:58
Sure, I disabled the workaround, and if I see some crash again, I'll keep you updated.

Thanks a lot !

**Comment by anmolmathias** [comment] 2021-04-19 11:39
Enabling `qt.workarounds.remove_service_workers' solved it for me too. Without it, the instant I load the Spotify tab, the browser crashes.

**Comment by The-Compiler** [comment] 2021-04-19 11:45
@anmolmathias All the workaround does is removing the corrupted data. You will be able to disable it again, and for a while, shouldn't have any crashes. The big question is what causes the data to corrupt (i.e. the crashes to come back) again.
