### ISSUE TITLE
Render Crash

### ISSUE THREAD

**Issue by Spounka** [qutebrowser/qutebrowser#5436] opened 2020-05-14 15:07 UTC
**Version info**:
qutebrowser v1.11.1
Git commit:
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2

**Does the bug happen if you start with `--temp-basedir`?**:
yes it does

**Description**
qutebrowser keeps crashing frequently when trying to open a webpage, i have to retry several times before the browser finally renders the page

**How to reproduce**
it mostly happened with stackoverflow
-opening google in new page using a predefined shortcut (ag)
-fd for focus on searching and typing a question
-CTRL-SHIFT-LeftMouse click on a link
-render crash message pops

**Comment by The-Compiler** [comment] 2020-05-14 15:32
What OS/distribution is this on? Can you show the output you get with `--debug --debug-flag stack` in a terminal when the crash happens?

**Comment by Spounka** [comment] 2020-05-14 16:26
i just reproduced the bug after a hard time
how can i get the stack trace of it ? knowing i already started it with the before mentioned arguments

**Comment by The-Compiler** [comment] 2020-05-14 16:27
You should get some output in the terminal, no?

**Comment by Spounka** [comment] 2020-05-14 16:28
no, the application isn't outputing any log into the terminal
it did output version and DEBUG destroy then the browser started normally

**Comment by The-Compiler** [comment] 2020-05-14 16:29
Make sure you don't have an existing instance running when you start it like that in a terminal - then you should get more output. There's only one instance running at a given time, so what was still running (and crashing) was your existing instance without debug output in the terminal.

**Comment by Spounka** [comment] 2020-05-14 16:30
yes i managed to find it out, thank you
i will try to reproduce the bug now and send you clear screenshot / output

**Comment by Spounka** [comment] 2020-05-14 16:39
reproduced the bug
steps to reproduce:
**having multiple tabs open at same time** 5+
doing a google search
ctrl+shift+middle/left mouse on a link

**Comment by Spounka** [comment] 2020-05-14 16:41
17:34:53 DEBUG    webview    tabbedbrowser:_on_title_changed:751 Changing title for idx 3 to 'Error loading https://www.sciencedirect.com/science/article/pii/B9780125184205500298'
17:34:53 DEBUG    webview    browsertab:_set_load_status:935 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=49 url='data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf…'>: LoadStatus.success
17:34:53 DEBUG    signals    signalfilter:_filter_signals:88 emitting: cur_load_status_changed(<LoadStatus.success: 2>) (tab 3)
17:34:54 DEBUG    sessions   sessions:save:317 Saving session _autosave to /home/spounka/.local/share/qutebrowser/sessions/_autosave.yml...
17:34:54 DEBUG    signals    signalfilter:_filter_signals:88 emitting: cur_load_finished(True) (tab 3)
17:34:54 DEBUG    modes      modeman:leave:379 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
17:34:54 DEBUG    modes      modeman:leave:379 Ignoring leave request for KeyMode.hint (reason load started) as we're in mode KeyMode.normal
17:34:54 DEBUG    modes      modeman:_handle_keypress:246 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Got key: 0x1000053 / modifiers: 0x0 / text: '<Super L>' / dry_run True
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match without modifiers
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match with key_mappings
17:34:54 DEBUG    modes      modeman:_handle_keypress:273 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: True --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7f20c68e2af0>)
17:34:54 DEBUG    modes      modeman:_handle_keypress:246 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Got key: 0x1000053 / modifiers: 0x0 / text: '<Super L>' / dry_run True
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match without modifiers
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match with key_mappings
17:34:54 DEBUG    modes      modeman:_handle_keypress:273 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: True --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7f20c68e2af0>)
17:34:54 DEBUG    modes      modeman:_handle_keypress:246 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Got key: 0x1000053 / modifiers: 0x0 / text: '<Super L>' / dry_run False
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match without modifiers
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match with key_mappings
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Giving up with '<Super L>', no matches
17:34:54 DEBUG    keyboard   basekeyparser:_debug_log:196 Clearing keystring (was: <Super L>).
17:34:54 DEBUG    modes      modeman:_handle_keypress:273 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: False --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7f20c68e2af0>)
17:34:55 DEBUG    modes      modeman:_handle_keyrelease:293 filter: False
17:34:56 DEBUG    modes      modeman:_handle_keypress:246 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Got key: 0x1000053 / modifiers: 0x0 / text: '<Super L>' / dry_run True
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match without modifiers
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match with key_mappings
17:34:56 DEBUG    modes      modeman:_handle_keypress:273 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: True --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7f20c68e2af0>)
17:34:56 DEBUG    modes      modeman:_handle_keypress:246 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Got key: 0x1000053 / modifiers: 0x0 / text: '<Super L>' / dry_run True
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match without modifiers
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match with key_mappings

17:34:56 DEBUG    modes      modeman:_handle_keypress:273 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: True --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7f20c68e2af0>)
17:34:56 DEBUG    modes      modeman:_handle_keypress:246 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Got key: 0x1000053 / modifiers: 0x0 / text: '<Super L>' / dry_run False
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match without modifiers
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Trying match with key_mappings
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Giving up with '<Super L>', no matches
17:34:56 DEBUG    keyboard   basekeyparser:_debug_log:196 Clearing keystring (was: <Super L>).
17:34:56 DEBUG    modes      modeman:_handle_keypress:273 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: False --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7f20c68e2af0>)
17:34:56 DEBUG    misc       app:on_focus_object_changed:495 Focus object changed: None

**Comment by The-Compiler** [comment] 2020-05-14 16:51
That looks like the output of loading the crash page - what do you get before the "Changing title for idx 3 to 'Error loading https://www.sciencedirect.com/science/article/pii/B9780125184205500298'"?

**Comment by The-Compiler** [comment] 2020-05-14 16:56
Ah, I'm able to reproduce. Seems to only happen with Qt 5.13 though, not Qt 5.14. Quite possible there's nothing qutebrowser can do about this.

**Comment by Spounka** [comment] 2020-05-14 17:00
ah, so it's a Qt problem ...
thank you for your time

**Comment by The-Compiler** [comment] 2020-05-14 17:06
Yep, I found a way to get some logs now:

```
../../3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0230
```

Which is this: [[QTBUG-81313] Renderer process crash due to seccomp-bpf failure with glibc 2.30.9000-18 - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-81313)

So you'll need to upgrade Qt, or downgrade glibc (which probably will cause some trouble), or get your distribution's maintainer to backport that patch to Qt 5.13 (which is not officially supported upstream - 5.12 and 5.14 are, and the fix landed in 5.12.8 and 5.14.1).

**Closed by The-Compiler** 2020-05-14 17:06 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by Al-Caveman** [comment] 2020-10-28 08:08
```
sys-libs/glibc 2.32-r2
dev-qt/qtwebengine 5.15.1
```
gentoo.  renderer crashes sometimes despite `~/.{cache,local}/qutebrowser` deleted.

not gonna debug anything, but just to ask: is there anything wrong with versions above?

**Comment by The-Compiler** [comment] 2020-10-28 13:04
@Al-Caveman I'm guessing #5721 in case Gentoo doesn't have that patch backported. FWIW Qt 5.15.2 with a fix is planned for next week.
