### ISSUE TITLE
Keybind to remove all focus

### ISSUE THREAD

**Issue by binex-dsk** [qutebrowser/qutebrowser#7991] opened 2023-11-06 18:39 UTC
Sometimes, when I edit a text box, after I'm done editing and hit enter or otherwise submit the form, insert mode is exited but I remain focused on the textbox, thus making the arrow keys h,j,k,l no longer work.

Having a keybind to remove focus from any focused widgets would be a nice addition, as in that scenario, I'd have to move my mouse and click outside of the textbox.

**Comment by toofar** [comment] 2023-11-06 19:09
I believe the recommendation is rebind `Escape` to also call `document.activeElement.blur()`. Like so: https://github.com/qutebrowser/qutebrowser/issues/2668#issuecomment-1053497243

Or if you want to use the autoconfig: `:bind --mode=insert <esc> mode-leave ;; jseval -q document.activeElement.blur()`

Hope that helps! I'll mark this as a duplicate of that issue.

**Closed by toofar** 2023-11-06 19:09 UTC
