### ISSUE TITLE
Kerberos support

### ISSUE THREAD

**Issue by rkratky** [qutebrowser/qutebrowser#5443] opened 2020-05-16 11:51 UTC
Support for authenticating with Kerberos would be great. Not sure if it has been considered, but it would allow use in many corporate environments.

**Comment by The-Compiler** [comment] 2020-05-16 11:58
Duplicate of #4595

**Closed by The-Compiler** 2020-05-16 11:58 UTC

**Comment by rkratky** [comment] 2020-05-16 12:03
Thanks. I only searched in opened issues.
