### ISSUE TITLE
How to make web.whatsapp.com remember that notifications are allowed?

### ISSUE THREAD

**Issue by akobel** [qutebrowser/qutebrowser#5433] opened 2020-05-13 13:04 UTC
The web interface for WhatsApp seems to forget that it's allowed to send desktop notifications. I granted them to the site (autoconfig.yml has the entry `content_notifications: https://web.whatsapp.com: true`), and they work fine; but I have to wait for and click the blue button "Turn on" everytime I close and re-open the browser. Is there any way to circumvent that? Chrome somehow remembers this, or signals to the site that permissions are granted without user interaction.

![20200513_14h46m03s_grim](https://user-images.githubusercontent.com/4997431/81814778-70fc4480-9529-11ea-883d-e3cbeebeb248.png)

Possibly (though unlikely to be, IMHO) related: on startup of qutebrowser, I get the following message:
```
propsReply "Method \"GetAll\" with signature \"s\" on interface \"org.freedesktop.DBus.Properties\" doesn't exist\n"
nmReply "Method \"GetDevices\" with signature \"\" on interface \"org.freedesktop.NetworkManager\" doesn't exist\n"
"Object path cannot be empty"
```
and, at some point, my system journal gets flooded with those messages in 10 sec-intervals:
```
dbus-daemon[715]: [system] The maximum number of pending replies for ":1.440" (uid=1000 pid=6271 comm="/usr/bin/python3 /usr/bin/qutebrowser ") has been reached (max_replies_per_connection=128)
```
(unsurprisingly, starting after 1280 seconds). I don't know how to find out the parameters of this method call, but I assume it's *not* related to notifications, right?

**Version info (see `:version`)**:
qutebrowser v1.11.1
Git commit:
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2
(from Arch Linux repo, all up-to-date)

**If applicable: Does the issue happen if you start with `--temp-basedir`?**:
Yes.

**Comment by The-Compiler** [comment] 2020-05-13 13:10
Duplicate of #5233

**Closed by The-Compiler** 2020-05-13 13:10 UTC

**Comment by kguidonimartins** [comment] 2021-06-28 17:15
Well, this is a closed issue, but I think people can benefit from the solution. Thanks to @bascht, you can auto-enable notifications using a greasemonkey script:

I put the script below at `~/.local/share/qutebrowser/greasemonkey/enable-notification-web-whatsapp.js`. In sum, you just need to change the xpath in the [original script](https://github.com/qutebrowser/qutebrowser/issues/5233#issuecomment-614444694).

```js
// ==UserScript==
// @name        Fix web WhatsApp Notifications
// @description	Hits the notification button, once
// @version		1.0
// @namespace   https://web.whatsapp.com/
// @run-at document-idle
// @grant       none
// ==/UserScript==
(function() {
    'use strict';

    var waitForThatFrickingButton = setInterval(function() {
        let xpath = "//span[@class='lHWcP'][contains(.,'Turn on desktop notifications')]";
        let button = document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
        if(button) {
            button.click();
            clearInterval(waitForThatFrickingButton);
        }
    }, 500)
})();
```

**Comment by 7sev7nsev7n7** [comment] 2026-02-25 06:18
> Well, this is a closed issue, but I think people can benefit from the solution. Thanks to [@bascht](https://github.com/bascht), you can auto-enable notifications using a greasemonkey script:
> 
> I put the script below at `~/.local/share/qutebrowser/greasemonkey/enable-notification-web-whatsapp.js`. In sum, you just need to change the xpath in the [original script](https://github.com/qutebrowser/qutebrowser/issues/5233#issuecomment-614444694).
> 
> // ==UserScript==
> // @name        Fix web WhatsApp Notifications
> // @description	Hits the notification button, once
> // @version		1.0
> // @namespace   https://web.whatsapp.com/
> // @run-at document-idle
> // @grant       none
> // ==/UserScript==
> (function() {
>     'use strict';
> 
>     var waitForThatFrickingButton = setInterval(function() {
>         let xpath = "//span[@class='lHWcP'][contains(.,'Turn on desktop notifications')]";
>         let button = document.evaluate(xpath, document, null, XPathResult.FIRST_ORDERED_NODE_TYPE, null).singleNodeValue;
>         if(button) {
>             button.click();
>             clearInterval(waitForThatFrickingButton);
>         }
>     }, 500)
> })();

is this still working? i've added this script to my greasemonkey scripts directory and yet i still have to manually click the button every time
