### ISSUE TITLE
"Try Again" button does not work on "Renderer process crashed" page

### ISSUE THREAD

**Issue by MarSoft** [qutebrowser/qutebrowser#4870] opened 2019-06-25 23:26 UTC
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/b8be4bd4

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
When I push `Try again` button on `Renderer process crashed` page, nothing happens. If I open developer console, I can see the following message in it:
`Not allowed to load local resource: qute://back/#(urlencoded page title)`. Each time I push `Try again` button, the counter beneath this message increments.

**How to reproduce**

1. Create a file with the following contents:
```
<html><body>
<script>function crashme() { var a=''; while(1) a+='x'; }</script>
<button onclick='crashme()'>Crash!</button>
</body></html>
```
2. Open that file in Qutebrowser
3. Click the button
4. Wait for the tab to crash
5. Press the `try again` button. Nothing will happen. Look in dev console, it will contain the message.

**Comment by user202729** [comment] 2019-06-26 02:34
Generally it doesn't work when the URL scheme is `file`. Just use `:back` (H) instead.

**Comment by MarSoft** [comment] 2019-06-26 13:24
But this problem happens with gmail as well! File:// was just a quick way
to reproduce.

ср, 26 июн. 2019 г., 5:34 user202729 <notifications@github.com>:

**Comment by The-Compiler** [comment] 2019-06-26 18:49
Duplicate of #3918

**Closed by The-Compiler** 2019-06-26 18:49 UTC
