### ISSUE TITLE
Never open a tab with the url domain as another opened tab

### ISSUE THREAD

**Issue by aidam38** [qutebrowser/qutebrowser#5347] opened 2020-04-11 21:17 UTC
When I want to **open `example.com/foo`** from anywhere (clicking a link, :open, ...) and I **already have** `example.com/bar` **tab open**, qutebrowser **moves the existing tab** to the position, where the new tab would appear and **load `example.com/foo` there**. 

I know this feature would be for everybody, but would probably solve a lot of people significant headaches over too many opened tabs (cf. [Kai Hendry's video](https://www.youtube.com/watch?v=QRMSoSrQ1e8)).

Also, feel free to nitpick the idea here. Like restricting this behavior under the condition that the action is done from the tab with the same url domain and leave the default behaviour when getting to the same site a different way.

**Comment by toofar** [comment] 2020-04-11 21:36
Might be an idea to tie into pinned tabs. But finding an open tab by fuzzy finding based on title and URL is already builtin to qutebrowser in the :buffer completion. Other browsers have extensions which provide a way to fuzzy search history and open tabs at the same time too.

**Comment by The-Compiler** [comment] 2020-04-14 15:22
For clicking links, this isn't possible with the API we get (we open a tab and return the QWebEngineView to Qt/Chromium). For `:open`, this is a duplicate of #5037.

**Closed by The-Compiler** 2020-04-14 15:22 UTC
