### ISSUE TITLE
Crash reporting: data protection

### ISSUE THREAD

**Issue by pyropeter** [qutebrowser/qutebrowser#4862] opened 2019-06-23 12:31 UTC
After qutebrowser was OOM-killed, it greeted me with a crash reporting dialogue. First of all, I really do understand the wish to get automated crash reports. I know from own experience how frustrating it is to not be informed about bugs in my software.

But nonetheless I found the experience really frustrating. Had I pushed the space or enter key in the wrong moment, the following data would have been sent somewhere:

* My name
* My envvars
* My settings, including my search engines
* My browser history

The dialogue was a desaster. The option to send my browser history was optimistically enabled by default. The small hint at the possibility to remove personal data was hidden behind some UI widget. There was no information as to where the data will be sent, who will get access to it, how long it will be stored, who is responsible for data protection, how to withdraw the consent to store the data. Please note that such information would be the absolute minimum required by [law in my jurisdiction](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation).

**Comment by The-Compiler** [comment] 2019-06-23 13:03
> After qutebrowser was OOM-killed, it greeted me with a crash reporting dialogue. First of all, I really do understand the wish to get automated crash reports. I know from own experience how frustrating it is to not be informed about bugs in my software.

I do agree things probably have changed a bit from back when I originally implemented the crash reporting some >5 years ago, with a handful of users or so.

> Had I pushed the space or enter key in the wrong moment

When the dialog is opened, the focus is on a text field. Pressing enter or space inserts the respective character there. You'd need to tab to the "report" key and press enter/space then. If there's a way to accidentally submit the dialog, that should be fixed.

> * My name

Your username, yes.

> * My envvars

There's a whitelist of environment variables (`DESKTOP_SESSION`, `DE`, `QT_*`, `PYTHON*`, `LC_*`, `LANG`, `XDG_*`, `QUTE_*`, `PATH`) to not send anything that isn't needed and potentially sensitive (API keys and such).

> The dialogue was a desaster. The option to send my browser history was optimistically enabled by default.

Indeed, because segfault reports are pretty much useless without that information.

> The small hint at the possibility to remove personal data was hidden behind some UI widget.

That could probably be outside of the folded-in part, true.

> There was no information as to where the data will be sent, who will get access to it, how long it will be stored, who is responsible for data protection, how to withdraw the consent to store the data.

I intend to write a small privacy policy when I start actively collecting donations for qutebrowser again - but to answer those questions:

- Reports are sent to my own server.
- They can be accessed by me, as well as other core developers who needed and requested access (@jgkamat, @rcorre, @user202729)
- They are currently stored indefinitely, since there's not really any tooling around it (they end up in a pastebin hosted by me). I plan to [change that](https://github.com/The-Compiler/crashbin/) with my bachelor thesis (a crash reporting tool tailored to qutebrowser's need) - with the necessary tooling, it should be possible to delete reports after the underlying issue is fixed. I even mentioned that [in the thesis](https://t.cmpl.cc/ba.pdf) (German).
- I do not live in the EU, and as a non-profit project, do not have the resources to have a data-protection officer in the EU.
- Regardless, of course I'll handle any questions regarding that (or requests to delete reports), e.g. at mail@qutebrowser.org

> Please note that such information would be the absolute minimum required by [law in my jurisdiction](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation).

Citing from that page: *The regulation does not apply to the processing of data by a person for a "purely personal or household activity and thus with no connection to a professional or commercial activity." (Recital 18)*

On the other hand, the question whether qutebrowser has *a connection to a professional or commercial activity* is hard to answer, especially when I intend to work part-time on qutebrowser soon.

**Closed** 2019-10-25 19:12 UTC
Labels: priority: 1 - middle

**Comment by The-Compiler** [comment] 2019-10-25 19:15
> > Had I pushed the space or enter key in the wrong moment
> 
> When the dialog is opened, the focus is on a text field. Pressing enter or space inserts the respective character there. You'd need to tab to the "report" key and press enter/space then. If there's a way to accidentally submit the dialog, that should be fixed.

FWIW I tried to reproduce this again and couldn't - if you have more information on how what you claimed could happen, I'm all ears.

> > The small hint at the possibility to remove personal data was hidden behind some UI widget.
> 
> That could probably be outside of the folded-in part, true.

I moved it there now.

> > There was no information as to where the data will be sent, who will get access to it, how long it will be stored, who is responsible for data protection, how to withdraw the consent to store the data.
> 
> I intend to write a small privacy policy when I start actively collecting donations for qutebrowser again

I added some words [to the FAQ](https://github.com/qutebrowser/qutebrowser/blob/master/doc/faq.asciidoc#privacy) about this now. Let me know if you feel like something is missing - but note I'd rather have something which is useful for users, not necessarily something to make lawyers happy.
