### ISSUE TITLE
Possible javascript related problem

### ISSUE THREAD

**Issue by aanastasiou** [qutebrowser/qutebrowser#6638] opened 2021-08-08 21:36 UTC
Please note: * This is more of an issue WITH qutebrowser, but possibly not a bug OF qutebrowser as such. *

**Version info**:

```
qutebrowser v2.3.1
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.8.10
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: 0.4.3
jinja2: 3.0.1
pygments: no
yaml: 5.3.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: no
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.33.0
```

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

Starting up qutebrowser causes a severe crash (seg fault without anything meaningful in the log).

**How to reproduce**

This is going to be very difficult. I am on ` Linux-5.4.0-74-generic-x86_64-with-glibc2.29, 64bit` and upgraded to 2.3.1 with absolutely no problem. I have probably gone through tens of cycles of launching qutebrowser, picking it up from where I left and closing qutebrowser preserving the last state. Today, I launched qutebrowser and it started seg faulting so hard that even with `-l debug` it would show nothing meaningful to the log. It would start up, restore tabs, linger for 4-5 seconds as if everything was alright and then crash. The last thing it would log would be something like "[...] broker.cc pipe broken" which was probably because a control had died already. 

Starting it up with `--temp-basedir` seemed to work for a minute but once I navigated to reddit, the browser crashed again. I suspected javascript and `set content.javascript.enabled false`.

Crashing stopped.

Cleared `.cache/qutebrowser`, enabled javascript, crashes came back. Disabled javascript again.

Still looking for some sort of state remnant that would cause these crashes, I started poking around `.local/share/qutebrowser/webengine`. It is probably best not to mess around with most files in there, to ensure the browser remains stable, but inside directory `Service Worker` there was `CacheStorage` and `ScriptCache`. `Service Worker` also has a `-bak`... (great).

Cleared `.local/share/qutebrowser/webengine/"Service Worker"/CacheStorage`, `.local/share/qutebrowser/webengine/"Service Worker"/ScriptStorage`, enabled javascript.

Crashing stopped. Qutebrowser back at its best.

Hope this helps.

**Comment by toofar** [comment] 2021-08-09 20:31
Duplicate of https://github.com/qutebrowser/qutebrowser/issues/5634
Make sure you have `qt.workarounds.remove_service_workers` set to true.
Its some QT issues with web workers being serialized in a state that the deserialization can't handle.Sites don't depend on these workers sticking around across restarts anyway.

**Closed by toofar** 2021-08-09 20:31 UTC
