### ISSUE TITLE
QT6: Impossible to open page with invalid HTTPS. `content.tls.certificate_errors` seems to be ignored

### ISSUE THREAD

**Issue by saro** [qutebrowser/qutebrowser#7086] opened 2022-03-28 14:16 UTC
**Version info**:
qutebrowser v2.3.1
Git commit: 87b31406e on qt6-test (2022-01-06 18:42:12 +0100)
Backend: QtWebEngine 6.2.1, based on Chromium 90.0.4430.228
Qt: 6.2.1

CPython: 3.10.4
PyQt: 6.2.1

sip: no
colorama: 0.4.4
jinja2: 3.0.1
pygments: 2.10.0
yaml: 5.4.1
adblock: 0.5.0
PyQt6.QtWebEngineWidgets: yes
PyQt6.QtWebEngine: no
PyQt6.QtWebKitWidgets: no
pdf.js: 2.13.216 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.36.0
QtNetwork SSL: OpenSSL 1.1.1n  15 Mar 2022

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

When trying to open a page with invalid TLS certificate, the page is
no loaded and it just display "ERR_CERT_AUTHORITY_INVALID".
This independently of the `content.tls.certificate_errors` setting.

**How to reproduce**

Try to open any page served by a server running self-signed
certificate.

**Comment by The-Compiler** [comment] 2022-03-30 07:32
Reproduced with: `qutebrowser --temp-basedir --debug https://expired.badssl.com`, works fine with the simplebrowser example.

Looks like there is just some new API we need to use instead: https://doc.qt.io/qt-6/qtwebengine-changes-qt6.html#qwebenginepage-certificateerror

**Comment by The-Compiler** [comment] 2022-04-22 14:36
Fixed with 37488adc55e537c2df9ed1420f3072324b1df399 in `qt6-v2`.

**Closed by The-Compiler** 2022-04-22 14:36 UTC
Labels: bug: behavior, qt: 6
