### ISSUE TITLE
Insert mode not maintained after the search results get updated in search boxes that allow live filtering

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4143] opened 2018-08-18 20:53 UTC
Example: in the search box of GitHub repositories for users.

[See here for instance.](https://github.com/The-Compiler?utf8=%E2%9C%93&tab=repositories&q=&type=&language=)

**Comment by The-Compiler** [comment] 2018-08-18 20:54
Duplicate of #3596

**Closed by The-Compiler** 2018-08-18 20:54 UTC
