### ISSUE TITLE
Qutebrowser lags significantly when downloads bar is visible in multiple windows in different virtual desktops

### ISSUE THREAD

**Issue by ethanalker** [qutebrowser/qutebrowser#7573] opened 2023-01-31 20:55 UTC
**Version info**:

qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.12, based on Chromium 87.0.4280.144
Qt: 5.15.8

CPython: 3.10.9
PyQt: 5.15.8

sip: 6.7.6
colorama: no
jinja2: 3.0.1
pygments: 2.10.0
yaml: 6.0
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.40.1
QtNetwork SSL: OpenSSL 3.0.7 1 Nov 2022

Style: QFusionStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.3.3
Platform: Linux-6.1.8-arch1-1-x86_64-with-glibc2.36, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:
Yes, when both windows start from the same temp basedir

**Description**
When I have multiple windows in different virtual desktops (in my case sway workspaces), qutebrowser lags to the point of unusability whenever the downloads bar is visible. Switching tabs takes multiple seconds, scrolling does not happen, the download takes extra time to download and to open, etc. This is an issue as I use qutebrowser to view html emails, which I leave open in another workspace. When the downloads bar is closed with `cd` the lag persists for short amount of time, then qutebrowser returns to normal function. I checked htop and I didn't see excessive resource usage. 

**How to reproduce**

1. Open two sway windows from the same basedir
2. Move the windows into seperate virtual desktops
3. Download an item so that the downloads bar is visible

**Comment by The-Compiler** [comment] 2023-01-31 20:58
Duplicate of #4857

**Comment by The-Compiler** [comment] 2023-01-31 20:59
As noted there, setting `QT_QPA_PLATFORM=wayland` in your environment might be a workaround - but in the end, this seems like some bug in Qt/Wayland of some sorts.

**Closed by The-Compiler** 2023-01-31 20:58 UTC

**Comment by ethanalker** [comment] 2023-01-31 21:23
Setting the environment variable seemed to fix it on my system, thanks! :)

**Comment by ulzu** [comment] 2026-06-03 06:18
> As noted there, setting `QT_QPA_PLATFORM=wayland` in your environment might be a workaround - but in the end, this seems like some bug in Qt/Wayland of some sorts.

this has the unfortunate effect that qutebrowser can't be opened from the shell, only from the wm. but without this variable set, the browser is virtually unusable.

edit: works alright after reboot, sorry for the noise.
