### ISSUE TITLE
PAC support on windows

### ISSUE THREAD

**Issue by DrTobe** [qutebrowser/qutebrowser#3889] opened 2018-05-03 13:37 UTC
I would like to make use of PAC files on a windows OS. Referring to issue https://github.com/qutebrowser/qutebrowser/issues/2492, this is not implemented in the QtWebEngine backend. When I try to start qutebrowser with the QtWebKit backend configured, I get the following error message:
```
Failed to start with the QtWebKit backend!
The error encountered was:
cannot import name 'QtWebKit'
```
I have installed the 64-bit version v1.2.1 on Win10.

**Comment by The-Compiler** [comment] 2018-05-03 13:40
QtWebKit support for Windows would mean compiling PyQt, QtWebKit (and possibly the rest of Qt) from sources for every release, which is not something which is going to happen :wink:

**Comment by The-Compiler** [comment] 2018-05-03 13:40
Duplicate of #2492

**Closed by The-Compiler** 2018-05-03 13:40 UTC
