### ISSUE TITLE
statusbar.show = in-mode breaks search

### ISSUE THREAD

**Issue by jeffmhubbard** [qutebrowser/qutebrowser#6865] opened 2021-12-04 22:44 UTC
**Version info**:
qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
With `statusbar.show in-mode` enabled, when I do a search with /, after hitting Enter, it jumps to the first element (link, input box, etc) on the page instead of the matched text.

Possibly related to #6367?

**How to reproduce**
`:set statusbar.show in-mode`
Go to `:version` page
Type `/` to  search
Type string and see it being matched
Hit enter and focus jumps to "Yank pastebin URL for version info" button instead of scrolling page to matched text.

Also tested on Github (focuses to "Skip to content" button and archlinux.org (focuses header image).

**Comment by The-Compiler** [comment] 2021-12-04 22:46
Duplicate of #2236

**Closed** 2021-12-04 22:46 UTC

**Comment by jeffmhubbard** [comment] 2021-12-04 22:57
Ah, thanks. I'll see if any of those workarounds will work for me.
