### ISSUE TITLE
Allow positional arguments with slice syntax in search engine formatting

### ISSUE THREAD

**Issue by BanchouBoo** [qutebrowser/qutebrowser#6658] opened 2021-08-28 19:08 UTC
Would allow more flexibility in what we can do with search engines
`{1}` = first argument
`{2-4}` = second through fourth argument
`{-1}` = last argument
`{2-}` second argument through last argument
e.g. searching a subreddit (and if there's only the first argument it will just open the subreddit) and searching a github project
```python
c.url.searchengines = {
    "subreddit": "reddit.com/r/{1}/search/?q={2-}&restrict_sr=1",
    "gh-project": "https://github.com/{1}/{2}/search?q={3-}",
}
```

**Comment by The-Compiler** [comment] 2021-08-28 19:15
Merging this into #5560 which (other than the slicing) this is a duplicate of.

**Closed by The-Compiler** 2021-08-28 19:15 UTC
