### ISSUE TITLE
Rebinding mouse action?

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#3774] opened 2018-03-26 09:14 UTC
OK, I have to admit it... I *still* use the mouse, sometimes... (but just a little bit).

Now that I have pleaded guilty: is there a way to rebind mouse clicks? I went through all the documentation and I failed to find anything on that.

More specifically, I would like to rebind `<Ctrl-Shift-mouse1>` to `<Shift-mouse1>` and `<Shift-mouse1>` to `<Alt-mouse1>`.

(mouse1 = left-click). My keyboard is not great with multikey presses and I want to get rid of the `<Ctrl-Shift>` combo (+ rebind shift and alt based on my frequency of use since I am at it).

Thank you!!! (again).

**Comment by The-Compiler** [comment] 2018-03-26 09:17
There is no way to do mouse bindings right now - there's #591 for that, but I'm not entirely sure if it'll be possible to rebind the modifiers when clicking a link.

**Comment by The-Compiler** [comment] 2018-03-26 09:17
Duplicate of #591

**Closed by The-Compiler** 2018-03-26 09:17 UTC
Labels: component: keyinput

**Comment by prosoitos** [comment] 2018-03-26 09:38
Damn. Sorry I missed #591. Ok. Ah well... I'll be following that issue. Thanks for the quick reply!
