### ISSUE TITLE
Spectre and meltdown mitigation?

### ISSUE THREAD

**Issue by AcarBurak** [qutebrowser/qutebrowser#3488] opened 2018-01-14 14:37 UTC
qtwebengine's incorporation of Chromium patches doesn't seem promising and if it happens it will be with an unconfortable delay.

https://bugreports.qt.io/browse/QTBUG-65561

> Looking at the recent Meltdown/Spectre attacks, it'd also be good to support Site Isolation (site-per-process, not to be confused with process-per-site) as it's the recommended mitigation at the moment. Currently it seems to be possible to pass that switch to QtWebEngine, but I'm not sure whether it actually works correctly.

What about webkit?

https://webkit.org/blog/8048/what-spectre-and-meltdown-mean-for-webkit/

Has qutebrowser incorporated such things?

**Comment by The-Compiler** [comment] 2018-01-14 14:38
Duplicate of #3473

**Closed** 2018-01-14 14:38 UTC

**Comment by The-Compiler** [comment] 2018-01-15 12:21
In the meantime, both QtWebKit and QtWebEngine pushed mitigations, see https://github.com/qutebrowser/qutebrowser/issues/3473#issuecomment-355752646 for details. Let me also mention again here that this can't be fixed/mitigated in qutebrowser's code :wink:

**Comment by AcarBurak** [comment] 2018-01-15 12:54
Perfectly clear, thank you.
