### ISSUE TITLE
`mailto` opens a new tab instead of launching mail client

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#3907] opened 2018-05-09 19:32 UTC
I read #3861, so I am sure that this is not a bug and that I am simply too ignorant to get this to work on my system.

I just set emacs mu4e as my default mail client and, without changing anything on chromium, I got it to work by clicking on a `mailto` link there. But if I click on the same link on qutebrowser, it opens a new tab with the `mailto://` address.

I suspect this is a noob question with an easy answer so I am not providing any setup information now. But I will be happy to do so if needed.

Thank you!

**Comment by jgkamat** [comment] 2018-05-09 19:39
I don't think that qb handles `mailto` at all, see #2833.

If that issue is fixed, you may be able to open mailtos properly with a config setting.

**Comment by The-Compiler** [comment] 2018-05-09 19:42
Yup, closing that as a duplicate of #2833

**Closed** 2018-05-09 19:42 UTC

**Comment by prosoitos** [comment] 2018-05-09 21:07
I read #2833, but I also read #3861, which is a lot more recent and I understood that the author had a proper behaviour with a mouse click and only had issues with `hint`. I would be very happy to have the behaviour working with mouse click. But maybe I mis-understood his issue?

**Comment by The-Compiler** [comment] 2018-06-07 12:39
I just re-discovered this issue and realized I never answered to your comment above.

@prosoitos can you re-test this with Qt 5.11 (which landed on Arch a few weeks ago) and ideally the latest git master of qutebrowser (`qutebrowser-git` in the AUR)? Indeed I'm only aware of issues when opening links via hints (rather than clicking on them), but both Qt 5.11 and qutebrowser had a few changes related to external URL handling.

**Comment by prosoitos** [comment] 2018-06-08 16:50
Thank you for getting back to this @The-Compiler!!! I was left quite confused. I think that you are right and the difference between the author of #3861 and I is that they had a newer version of qutebrowser (I hadn't realized that I was on a rather old version due to Arch until your comment on this on another issue). With the last Arch stable release (not the git version from the AUR), it looks like it works. I am not totally sure as I am currently having a little problem with some links due to my recent implementation of [exwm](https://github.com/ch11ng/exwm) on my system. But my guess is that without my exwm problem, it would indeed work because qutebrowser does not open an empty tab anymore as it used to :slightly_smiling_face: 

Thank you!!
