### ISSUE TITLE
For some reason Fox News won't load

### ISSUE THREAD

**Issue by wgmayer0** [qutebrowser/qutebrowser#7726] opened 2023-05-31 01:24 UTC
qutebrowser crashes every time I go on foxnews.com

**Comment by mschilli87** [comment] 2023-05-31 05:39
Cannot reproduce.

**Comment by The-Compiler** [comment] 2023-05-31 08:58
Works fine for me too. Does it work with `--temp-basedir`? What's your `:version` information? (...there's a reason the issue template asks for those things :wink:)

**Comment by wgmayer0** [comment] 2023-05-31 10:58
Good point, will try after work. Thank you!

**Comment by wgmayer0** [comment] 2023-06-02 03:24
I am trying it on another machine and I am just seeing a blank screen when I type: `qutebrowser --temp-basedir www.foxnews.com`. The version is:
```
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 5.15.14, based on Chromium 87.0.4280.144
Qt: 5.15.9 (compiled 5.15.8)

CPython: 3.11.3
PyQt: 5.15.9

sip: 6.7.9
colorama: no
jinja2: 3.1.2
pygments: no
yaml: 6.0
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.0.9 30 May 2023

Style: QStyleSheetStyle
Platform plugin: xcb
OpenGL: NVIDIA Corporation, 4.6.0 NVIDIA 530.41.03
Platform: Linux-6.3.5-arch1-1-x86_64-with-glibc2.37, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /tmp/qutebrowser-basedir-9gdx_43i/cache
config: /tmp/qutebrowser-basedir-9gdx_43i/config
data: /tmp/qutebrowser-basedir-9gdx_43i/data
runtime: /tmp/qutebrowser-basedir-9gdx_43i/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:03:19
```

**Comment by The-Compiler** [comment] 2023-06-02 08:52
Try with `-s qt.chromium.sandboxing disable-seccomp-bpf` - you might also want to try with Qt 6 (#7202).

**Comment by wgmayer0** [comment] 2023-06-02 22:01
`-s qt.chromium.sandboxing disable-seccomp-bpf` doesn't work either, blank screen. I should be fine just waiting for the upstream fix if this issue starts affecting more sites than just Fox News. I haven't seen this issue on any other sites, so it can't be that bad.

**Comment by wgmayer0** [comment] 2023-12-29 21:41
I can access it now FYI. Thank you @The-Compiler

**Comment by The-Compiler** [comment] 2023-12-29 22:50
Thanks for the update, closing this then!

**Closed by The-Compiler** 2023-12-29 22:50 UTC
Labels: status: can't reproduce, status: needs triage
