### ISSUE TITLE
Unable to edit text with editor on Whatsapp

### ISSUE THREAD

**Issue by tom-doerr** [qutebrowser/qutebrowser#4162] opened 2018-08-27 09:39 UTC
Version: 1.1.1

Steps to reproduce:
- Focus on Whatsapp text field
- Press <C-e> to open the editor
- Insert text, save and exit

The text doesn't appear in the text box. Interestingly it seems to get inserted somewhere, since the same text appears again when relaunching the editor.

**Comment by The-Compiler** [comment] 2018-08-27 09:41
Duplicate of #2215

**Closed by The-Compiler** 2018-08-27 09:41 UTC

**Comment by tom-doerr** [comment] 2018-08-27 09:55
I saw that issue, and I'm not sure if it's really the same problem. The text entered on https://regex101.com/ is not visible after closing the editor and opening it again whereas the text is still there when you reopen the editor in Whatsapp.

**Comment by The-Compiler** [comment] 2018-08-27 10:03
It's the same issue as in that both websites use some "rich text" editor.
