### ISSUE TITLE
QtWebEngine and Wayland

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2932] opened 2017-08-27 17:52 UTC
Apparently `--backend webengine` on Wayland (probably with `QT_QPA_PLATFORM=wayland-egl` or `QT_QPA_PLATFORM=wayland`, without xwayland) segfaults (or aborts?).

We should probably detect that and show an error.

**Comment by The-Compiler** [comment] 2017-08-30 16:14
Hmm, https://codereview.qt-project.org/#/c/203480/4//ALL,unified mentions "Fixed crash when using Wayland QPA.".

**Comment by tidux** [comment] 2017-09-12 17:28
This looks like it goes back to QtWebEngine not having an actual Wayland port.  Last I looked it still uses Xcb directly on Linux.

**Comment by The-Compiler** [comment] 2017-09-12 17:29
Yes, but I'm mainly wondering whether we can handle this in a nicer way, i.e. display an error message instead of crashing.

**Comment by The-Compiler** [comment] 2017-09-28 08:26
I now pushed a nicer fix for this to the `webengine-by-default` branch, it'd be nice if some people could try it out. I've tried with Weston and sway both with XWayland (which should work normally) and without (which should show an error).

**Comment by bitraid** [comment] 2017-09-29 07:01
For me it didn't always crash (wayland-sway). Some times it started and worked fine.

**Comment by The-Compiler** [comment] 2017-09-29 07:02
@bitraid  And that was with the QtWebEngine backend and without XWayland?

**Comment by bitraid** [comment] 2017-09-29 07:04
Yes.

**Comment by The-Compiler** [comment] 2017-09-29 07:20
I only get this:

```
09:15:11 WARNING: WebEngine compiled with X11 support, however qpa backend is not xcb. This may fail.
[27960:27960:0929/091511.391419:ERROR:browser_main_loop.cc(494)] Failed to put Xlib into threaded mode.
[27960:27960:0929/091511.391534:ERROR:browser_main_loop.cc(1471)] Unable to open X display.
```

and then a segfault. I don't see how things could be any different for you...

Note that sway automatically uses XWayland unless you don't have it installed at all (or set `WLC_XWAYLAND=0`). If `echo $DISPLAY` gives you something, QtWebEngine used X, and qutebrowser should continue to run.

**Comment by bitraid** [comment] 2017-09-29 07:41
Yes, thats the crash message i get under wayland:
```
WARNING: WebEngine compiled with X11 support, however qpa backend is not xcb. This may fail.
  File "/home/bitraid/bin/qutebrowser/qutebrowser.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/bitraid/bin/qutebrowser/qutebrowser/qutebrowser.py", line 172, in main
    return app.run(args)
  File "/home/bitraid/bin/qutebrowser/qutebrowser/app.py", line 119, in run
    init(args, crash_handler)
  File "/home/bitraid/bin/qutebrowser/qutebrowser/app.py", line 145, in init
    _init_modules(args, crash_handler)
  File "/home/bitraid/bin/qutebrowser/qutebrowser/app.py", line 429, in _init_modules
    crash_handler.handle_segfault()
  File "/home/bitraid/bin/qutebrowser/qutebrowser/misc/crashsignal.py", line 98, in handle_segfault
    self._args.debug, data)
  File "/home/bitraid/bin/qutebrowser/qutebrowser/misc/crashdialog.py", line 472, in __init__
    self._set_crash_info()
  File "/home/bitraid/bin/qutebrowser/qutebrowser/misc/crashdialog.py", line 244, in _set_crash_info
    self._gather_crash_info()
  File "/home/bitraid/bin/qutebrowser/qutebrowser/misc/crashdialog.py", line 510, in _gather_crash_info
    super()._gather_crash_info()
  File "/home/bitraid/bin/qutebrowser/qutebrowser/misc/crashdialog.py", line 228, in _gather_crash_info
    self._crash_info.append(("Version info", version.version()))
  File "/home/bitraid/bin/qutebrowser/qutebrowser/utils/version.py", line 329, in version
    lines.append("Backend: {}".format(_backend()))
  File "/home/bitraid/bin/qutebrowser/qutebrowser/utils/version.py", line 319, in _backend
    return 'QtWebEngine (Chromium {})'.format(_chromium_version())
  File "/home/bitraid/bin/qutebrowser/qutebrowser/utils/version.py", line 303, in _chromium_version
    profile = QWebEngineProfile()
  File "/home/bitraid/bin/qutebrowser/qutebrowser/utils/log.py", line 445, in qt_message_handler
    stack = ''.join(traceback.format_stack())

[8090:8113:0928/193852.754907:ERROR:gl_surface_qt.cpp(479)] eglCreatePbufferSurface failed with error EGL_BAD_MATCH

```

After 3-5 retries (sometimes more) it starts ok.
It runs for sure under wayland: xprop doesn't recognize the window and yanking doesn't pass the text to X clipboard. I have set `QT_QPA_PLATFORM=wayland-egl`

**Comment by The-Compiler** [comment] 2017-09-29 07:47
I've seen that kind of thing happen when `QT_QPA_PLATFORM=wayland-egl` is set, but `DISPLAY` (and thus XWayland) is still available. Is that the case for you?

Like you say it doesn't really work reliably though, so I'd rather not support that. Maybe things look better with 5.9.2 or 5.10, I haven't checked that yet.

**Comment by bitraid** [comment] 2017-09-29 07:55
Yes XWayland is available. Things on wayland-wlc are not reliable in general.

**Comment by The-Compiler** [comment] 2017-09-29 08:29
Hmm, fair enough, that scenario seems fine to run under Weston. I'll need to investigate some more and maybe allow that again.

**Comment by The-Compiler** [comment] 2017-10-10 18:55
I just tried with some other compositors (orbment and way-cooler), and I get the same crashes there. So it seems like it works in Weston but even there shows some Qt/OpenGL errors. I'd rather keep that disabled for now, and look at it again with Qt 5.10 as part of #2939.

**Comment by bitraid** [comment] 2017-10-10 20:12
Sway and way-cooler will soon switch to wlroots. I guess things will be better then...

**Comment by The-Compiler** [comment] 2017-10-10 20:18
Okay, okay, you just gave me another reason to re-open this 😆 See https://github.com/swaywm/sway/issues/1301

I'll take a look at how things look then.

**Comment by The-Compiler** [comment] 2017-10-11 07:29
FWIW in 9c080538ba23ecb3253275060af7a79ccf9ae514 I added a `qt.force_platform` setting plus a button in the wayland error dialog to set that to `xcb` (if `DISPLAY` was set). In other words, if you have `QT_QPA_PLATFORM=wayland` set globally, you can easily set that back to `xcb` for qutebrowser/QtWebEngine to work properly now.

**Comment by bitraid** [comment] 2017-10-11 15:56
That's useful. How about an option to `qt.force_platform` setting, so it will try to run under wayland  anyway (for testing purposes)?

**Comment by bitraid** [comment] 2017-10-11 16:03
That's useful. How about an option (for testing purposes) to `qt.force_platform`, so it will try to run under wayland anyway?

**Comment by The-Compiler** [comment] 2017-10-11 16:25
There's `QUTE_SKIP_WAYLAND_CHECK=1` you can set as an environment variable. I don't want to document it, because I know people will ignore my warnings and I'll have to deal with the crash report :wink:

**Comment by The-Compiler** [comment] 2017-10-12 08:41
https://codereview.qt-project.org/#/c/208094/ might also be relevant

**Comment by bitraid** [comment] 2017-10-12 09:26
I tried setting `QUTE_SKIP_WAYLAND_CHECK=1` but i still get the check...

**Comment by The-Compiler** [comment] 2017-10-12 09:40
@bitraid How did you set it? Note that you need to do `export QUTE_SKIP_WAYLAND_CHECK=1` if doing it in a terminal.

**Comment by bitraid** [comment] 2017-10-12 09:50
I forgot the `export`, sorry - now it works.

**Comment by edrex** [comment] 2017-10-23 23:59
It seems to work for me (arch, sway, qt 5.9.2):

```
QT_QPA_PLATFORM=wayland QUTE_SKIP_WAYLAND_CHECK=1 qutebrowser --temp-basedir --backend webengine
16:41:46 WARNING: WebEngine compiled with X11 support, however qpa backend is not xcb. This may fail.
[4694:4715:1023/164147.056835:ERROR:gl_surface_qt.cpp(480)] eglCreatePbufferSurface failed with error EGL_BAD_MATCH
[4694:4715:1023/164147.705767:ERROR:gl_surface_qt.cpp(480)] eglCreatePbufferSurface failed with error EGL_BAD_MATCH
```

The window decorations show up and fullscreen youtube doesn't quite work, but other than that it seems ok.

I'm eager to make the leap to wayland/sway to benefit from its better support for mixed DPI with native wayland clients, so I'll probably keep testing.

**Comment by edrex** [comment] 2017-10-24 00:00
(no segfault)

dependent on your graphics card, i'd guess

**Comment by edrex** [comment] 2017-10-24 02:05
nevermind, I am getting segfaults after awhile :P

**Comment by The-Compiler** [comment] 2017-10-24 04:35
@edrex Note that you can still run qutebrowser on Wayland (via XWayland).

**Comment by The-Compiler** [comment] 2017-10-31 10:31
I've tried the current Qt dev branch, but get:

```
[21635:21658:1031/112807.219869:ERROR:gl_implementation.cc(246)] Failed to load /home/florian/code/qt/devenv/bin/libGLESv2.so: /home/florian/code/qt/devenv/bin/libGLESv2.so: cannot open shared object file: No such file or directory
[21635:21658:1031/112807.534079:ERROR:gl_surface_qt.cpp(701)] Requested OpenGL implementation is not supported. Implementation: 0
11:28:07 CRITICAL: ASSERT failure in Q_UNREACHABLE(): "Q_UNREACHABLE was reached", file ../gl_surface_qt.cpp, line 702
Received signal 6
#0 0x7f8c87cc275b base::debug::StackTrace::StackTrace()
#1 0x7f8c87cc0558 base::debug::StackTrace::StackTrace()
#2 0x7f8c87cc1444 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7f8ca657fda0 <unknown>
#4 0x7f8ca61eb8a0 __GI_raise
#5 0x7f8ca61ecf09 __GI_abort
#6 0x7f8ca0d3fa7f qt_message_fatal()
#7 0x7f8ca0d4084d QMessageLogger::fatal()
#8 0x7f8ca0d3a772 qt_assert_x()
#9 0x7f8c83e22abe gl::init::CreateOffscreenGLSurfaceWithFormat()
#10 0x7f8c89e7bebe gl::init::CreateOffscreenGLSurface()
#11 0x7f8c89eb7874 gpu::GpuChannelManager::GetDefaultOffscreenSurface()
#12 0x7f8c89ec1ea3 gpu::GpuCommandBufferStub::Initialize()
#13 0x7f8c89ebf0c7 gpu::GpuCommandBufferStub::Create()
#14 0x7f8c89e962aa gpu::GpuChannel::CreateCommandBuffer()
#15 0x7f8c89e95a6d gpu::GpuChannel::OnCreateCommandBuffer()
#16 0x7f8c89ea6fce _ZN4base20DispatchToMethodImplIPN3gpu10GpuChannelEMS2_FvRK28GPUCreateCommandBufferConfigiNS_18SharedMemoryHandleEPbPNS1_12CapabilitiesEERSt5tupleIJS4_iS7_EESD_IJbS9_EEJLm0ELm1ELm2EEJLm0ELm1EEEEvRKT_T0_OT1_PT2_NS_13IndexSequenceIJXspT3_EEEENSP_IJXspT4_EEEE
#17 0x7f8c89ea290a _ZN4base16DispatchToMethodIPN3gpu10GpuChannelEMS2_FvRK28GPUCreateCommandBufferConfigiNS_18SharedMemoryHandleEPbPNS1_12CapabilitiesEERSt5tupleIJS4_iS7_EESD_IJbS9_EEEEvRKT_T0_OT1_PT2_
#18 0x7f8c89e9dd41 _ZN3IPC8MessageTI38GpuChannelMsg_CreateCommandBuffer_MetaSt5tupleIJ28GPUCreateCommandBufferConfigiN4base18SharedMemoryHandleEEES2_IJbN3gpu12CapabilitiesEEEE8DispatchINS7_10GpuChannelESC_vMSC_FvRKS3_iS5_PbPS8_EEEbPKNS_7MessageEPT_PT0_PT1_T2_
#19 0x7f8c89e94c6d gpu::GpuChannel::OnControlMessageReceived()
#20 0x7f8c89e95782 gpu::GpuChannel::HandleMessageHelper()
#21 0x7f8c89e95886 gpu::GpuChannel::HandleOutOfOrderMessage()
#22 0x7f8c89eb0b38 _ZN4base8internal13FunctorTraitsIMN3gpu10GpuChannelEFvRKN3IPC7MessageEEvE6InvokeIRKNS_7WeakPtrIS3_EEJS7_EEEvS9_OT_DpOT0_
#23 0x7f8c89eadcc6 _ZN4base8internal12InvokeHelperILb1EvE8MakeItSoIRKMN3gpu10GpuChannelEFvRKN3IPC7MessageEERKNS_7WeakPtrIS5_EEJS9_EEEvOT_OT0_DpOT1_
#24 0x7f8c89eaa257 _ZN4base8internal7InvokerINS0_9BindStateIMN3gpu10GpuChannelEFvRKN3IPC7MessageEEJNS_7WeakPtrIS4_EES6_EEEFvvEE7RunImplIRKSA_RKSt5tupleIJSC_S6_EEJLm0ELm1EEEEvOT_OT0_NS_13IndexSequenceIJXspT1_EEEE
#25 0x7f8c89ea575c _ZN4base8internal7InvokerINS0_9BindStateIMN3gpu10GpuChannelEFvRKN3IPC7MessageEEJNS_7WeakPtrIS4_EES6_EEEFvvEE3RunEPNS0_13BindStateBaseE
#26 0x7f8c83fa61bd _ZNO4base8CallbackIFvvELNS_8internal8CopyModeE0ELNS2_10RepeatModeE0EE3RunEv
#27 0x7f8c87f5fff3 base::debug::TaskAnnotator::RunTask()
#28 0x7f8c87d3860a base::MessageLoop::RunTask()
#29 0x7f8c87d387a1 base::MessageLoop::DeferOrRunPendingTask()
#30 0x7f8c87d38ce7 base::MessageLoop::DoWork()
#31 0x7f8c87d51e0b base::MessagePumpDefault::Run()
#32 0x7f8c87d37ef6 base::MessageLoop::Run()
#33 0x7f8c87dddf1c base::RunLoop::Run()
#34 0x7f8c87e67ae4 base::Thread::Run()
#35 0x7f8c87e68399 base::Thread::ThreadMain()
#36 0x7f8c87e46004 base::(anonymous namespace)::ThreadFunc()
#37 0x7f8ca657508a start_thread
#38 0x7f8ca62ad24f __GI___clone
  r8: 0000000000000000  r9: 00007f8c1f31b940 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007f8c1f31bd38 r13: 0000000000000000 r14: 00007f8c1f31bf78 r15: 00007f8c08009760
  di: 0000000000000002  si: 00007f8c1f31b940  bp: 00007f8c1f31bba8  bx: 0000000000000006
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007f8ca61eb8a0  sp: 00007f8c1f31b940
  ip: 00007f8ca61eb8a0 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[21662:21662:0100/000000.446258:ERROR:command_buffer_proxy_impl.cc(229)] Failed to send GpuChannelMsg_CreateCommandBuffer.
[21662:21662:0100/000000.446377:ERROR:context_provider_command_buffer.cc(262)] GpuChannelHost failed to create command buffer.
```

**Comment by bitraid** [comment] 2017-11-27 17:09
I haven't seen any crash yet after the latest qt update on arch.

**Comment by camoz** [comment] 2017-11-27 23:53
I still get crashes sometimes with `QT_QPA_PLATFORM=wayland QUTE_SKIP_WAYLAND_CHECK=1 qutebrowser` on up-to-date Arch Linux (without testing).
This is on a Thinkpad X200 (Intel GMA X4500MHD).

**Comment by bitraid** [comment] 2017-11-28 11:11
Well, i got one  today...

**Comment by Nobabs27** [comment] 2018-02-07 02:59
Getting it right now on Void with Sway, backend regardless.

**Comment by The-Compiler** [comment] 2018-02-07 11:52
@Nobabs27 "it"? Can you please open a new issue with the output you get exactly and version information?

**Comment by The-Compiler** [comment] 2018-02-07 11:53
FWIW with Qt 5.10 there's [QTBUG-65682](https://bugreports.qt.io/browse/QTBUG-65682) so using Wayland + QtWebEngine without XWayland will need to wait at least until Qt 5.10.1.

**Comment by Nobabs27** [comment] 2018-02-07 22:43
@The-Compiler By "it" I mean this issue (segfault on Wayland).

**Comment by The-Compiler** [comment] 2018-02-07 22:49
@Nobabs27 Well, with that little information, I still won't be able to help you.

**Comment by tidux** [comment] 2018-02-15 07:25
I'm not seeing segfaults of QtWebEngine on Wayland either, even with explicitly forcing the Wayland QPA variables.

**Comment by The-Compiler** [comment] 2018-05-12 18:35
FWIW I'm still having issues here with Qt 5.10.1 and Sway/Weston (when doing `QT_QPA_PLATFORM=wayland QUTE_SKIP_WAYLAND_CHECK=1  python3 -m qutebrowser --temp-basedir`). It crashes before it even starts.

Hoping things will look better with Qt 5.11 though!

**Comment by bitraid** [comment] 2018-05-12 20:30
I'm testing (and writing this message from) the alpha version of sway 1.0, which uses wlroots, and that crash seems to be gone (the QT version is 5.10.1).

**Comment by edrex** [comment] 2018-05-14 16:47
@bitraid as soon as sway@wlroots gets tab/stack container layouts I'm going to try using it as my daily driver. I'll test a bit now with qutebrowser...

**Comment by edrex** [comment] 2018-05-14 16:55
@The-Compiler qutebrowser is working with that line for me under sway alpha, qt 5.10.1.

**Comment by The-Compiler** [comment] 2018-05-29 11:27
On Qt 5.10.1 I got [QTBUG-63862](https://bugreports.qt.io/browse/QTBUG-63862) - entirely possible that this got fixed in Qt 5.11.

On Qt 5.11, I'm getting [QTBUG-68479](https://bugreports.qt.io/browse/QTBUG-68479), but Archlinux [added a patch](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/qt5-webengine&id=63a746db589c1c45999849ebe8afcc90da103a00) to make it work (with disabled GPU rendering).

I'd still much rather let the user choose (rendering without GPU support can be quite a performance hog on some machine), but it's definitely time to update that dialog on Qt 5.11 (and maybe 5.10.1 too).

**Comment by The-Compiler** [comment] 2018-06-09 14:59
On Qt 5.11, the dialog now offers "use software rendering" as a third option (which is the equivalent of the Archlinux patch).

**Comment by edrex** [comment] 2018-07-06 18:34
Confusingly, I'm no longer seeing the QTBUG-68479 workaround message, and qutebrowser is running (not so stably, but usable for awhile) with HW acceleration reported in chrome:gpu (Arch, Qt 5.11.1 package, latest sway trunk). I don't see any relevant patches in the [arch package commit log](https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/qt5-webengine) so I have no idea what changed. Anyway it looks gorgeous on my 4k XPS13. This feels tantalizingly close :)

**Comment by glglwty** [comment] 2018-08-25 01:07
Qt 5.11.1 with QTBUG-68479 patch works for me with HW accelaration (sway 0.15.2, mesa driver).

**Comment by The-Compiler** [comment] 2018-08-25 05:38
@glglwty Huh? What that Archlinux patch does is disabling HW acceleration.

**Comment by glglwty** [comment] 2018-08-25 07:44
@The-Compiler I meant the upstream fix https://codereview.qt-project.org/#/c/232017/

**Comment by dax-dev** [comment] 2018-08-25 17:49
Working fine under Arch with sway-1.0-alpha.5, qt5-5.11.1, qutebrowser-1.4.1

QT_QPA_PLATFORM=wayland QUTE_SKIP_WAYLAND_CHECK=1 qutebrowser

**Comment by The-Compiler** [comment] 2018-08-26 08:54
Looks like I'll need to look at this one yet again :laughing: 

FWIW 5.12 has some other changes (mostly [using the Ozone backend](https://codereview.qt-project.org/#/c/220302/)) which might change this situation yet again.

**Comment by CosmoJG** [comment] 2018-09-15 12:53
Here's a screenshot of my setup: https://i.imgur.com/txJVuZb.png

I have both `QT_QPA_PLATFORM=wayland` and `QUTE_SKIP_WAYLAND_CHECK=1` set and use Qutebrowser natively on a daily basis! Everything works beautifully, even hardware acceleration according to chrome:gpu. I'm currently running qt5-base version 5.11.1-3, qt5-wayland version 5.11.1-1, and qt5-webengine version 5.11.1-3, all three of which are straight from the Arch Linux repositories without any patching on my part.

The only problem I've experienced thus far is that UI elements and UI fonts appear comically large with Wayland and the default 10-point font settings. For comparison, here's how fonts look with XWayland on the same system with the same settings: https://i.redd.it/4s2wsyy2snl11.png

Any idea what's causing this?

**Comment by The-Compiler** [comment] 2018-09-15 13:39
@CosmoJG No clue I'm afraid. I guess you could always decrease the font size in the config.

**Comment by bitraid** [comment] 2018-09-15 14:13
@CosmoJG https://github.com/swaywm/sway/issues/2424

**Comment by CosmoJG** [comment] 2018-09-15 23:01
@bitraid Thank you so much!

**Comment by concatime** [comment] 2018-09-16 02:15
One little issue with QuteBrowser on Wayland: `app_id` is set to `python3`, hence, cannot assign it to a workspace (python3 is too generic).

**Comment by vilhalmer** [comment] 2018-09-16 03:46
I fixed that recently (#4153), should be in the next release!

**Comment by johanhelsing** [comment] 2018-09-17 12:40
@CosmoJG, @bitraid: The comically large fonts probably happen because qutebrowser uses point-sized fonts with pixel-sized ui elements and you have a monitor with high dpi and a low scale factor. qutebrowser should either scale the tab-bar height based on the text height (or dpi), or switch to pixel-sized fonts.

I just checked, and I think you can set to pixel fonts manually. i.e.

```python
c.fonts.tabs = '13px DejaVuSans'
```

Fixes it for me

A workaround is to lie about your monitor DPI by setting `QT_WAYLAND_FORCE_DPI=96`

**Comment by The-Compiler** [comment] 2018-09-18 19:09
Doesn't look like [Qt supports that](http://doc.qt.io/qt-5/stylesheet-reference.html#length) for stylesheets, so that's pretty much out of the question.

**Comment by zetorian** [comment] 2018-11-27 06:45
So I have been running qutebrowser under sway beta for a while now, no major issues apart from a really weird one where if any qutebrowser instance is in a workspace that is not shown, no other instance or window will update.
I suspect that this is due to sway's lack of virtual workspaces and that windows that are drawn out of site are not really considered visible, which makes sense as to why they would not be updated, I do not understand why this affects other windows though.
using: 
QT_QPA_PLATFORM=wayland
QT_WAYLAND_DISABLE_WINDOWDECORATION=1

exampe:
1. open qutebrowser in workspace 12. 
2. switch to workspace 2
3. attempt to open qutebrowser, nothing happens4. 
4. switch back to workspace 1 and a second window loads
5. move second window to ws26. qutebrowser is unresponsive, both on ws1 and ws2

Is there some reason that this would happen? does qutebrowser attempt to check if it is visible before updating the window? while not usually an issue this can be quite annoying in edge cases.

**Comment by shioyama** [comment] 2018-11-27 06:54
I'm running qutebrowser with `tabs_are_windows` set to `true` and `tabs_show` set to `never`. With xwayland this works fine, but with `QT_QPA_PLATFORM=wayland QUTE_SKIP_WAYLAND_CHECK=1 QT_WAYLAND_DISABLE_WINDOWDECORATION=1`, I can open one window but when I try opening a new tab (i.e. new window), the window opens but qutebrowser hangs and I need to force kill it.

I'm using sway if that matters. I've trie dchanging `tabs_are_windows` to `false` and `tabs_show` to `always` and the issue disappears, so I suppose it has something to do with how qb is interacting with sway to open new windows, not sure though why that would work in xwayland...

**Comment by johanhelsing** [comment] 2018-11-27 07:08
@shioyama and @zetorian. It's a bug in Qt, fix will hopefully be in 5.12.1, maybe backported for some distros.

https://codereview.qt-project.org/#/c/245665/

**Comment by The-Compiler** [comment] 2018-11-27 07:33
@zetorian @shioyama @johanhelsing Note that the fix is currently in the `dev` branch (because it seems rather complex, I guess), so it'll make it into Qt 5.13 and not 5.12.1.

@shioyama Not 100% sure if this is the same bug. To confirm, I guess you could [run qutebrowser in gdb](https://qutebrowser.org/doc/stacktrace.html) and press ctrl-c in the terminal to get a gdb shell when it hangs.

**Comment by shioyama** [comment] 2018-11-27 08:53
@johanhelsing @The-Compiler Thanks for the super fast feedback. I'll try debugging in gdb and post my findings here later.

**Comment by johanhelsing** [comment] 2018-12-14 06:07
@The-Compiler, @shioyama: The fix for freeze on minimization was merged into the Qt 5.12 branch yesterday.

**Comment by shioyama** [comment] 2018-12-15 12:39
Wow, just upgraded to 5.12 and problem is fixed! And qb seems to run really smoothly, no more choppy X rendering, really fast! I don't see any rendering issues so far.

**Comment by shioyama** [comment] 2018-12-15 13:58
@The-Compiler Hmm, `:open qute://gpu` gets me an `ERR_FILE_NOT_FOUND`.

Also, I may have jumped the gun a bit in my last comment -- the choppiness is actually not totally gone in Wayland, although it does feel faster. I see no issues so far though, so put the env variables into my local desktop file and I'll be running with this in Wayland from here on.

**Comment by bitraid** [comment] 2018-12-15 13:58
It's `chrome://gpu`

**Comment by shioyama** [comment] 2018-12-15 14:34
Ah, `chrome://gpu` does indeed work. And it does seem that hardware acceleration is enabled, at least things like `Canvas`, `Composting` etc all show `Hardware accelerated`.

The "choppiness" I mentioned happens only when I open a new window (which happens each time I open a tab since I have the setting `tabs_are_windows` enabled). I first see the window open halfway, then it expands to the full size very quickly. It's fast enough that it doesn't really matter practically speaking, but slow enough to be mildly annoying. I thought it was an X issue but since it's still happening I suppose it's not.

But other than that (minor thing), everything is working very smoothly :smile:

**Comment by shioyama** [comment] 2018-12-15 14:35
Oh, but I notice that `Rasterization` and `Native GpuMemoryBuffers` are `Software only`.

**Closed** 2018-12-15 14:44 UTC
Labels: component: QtWebEngine, priority: 2 - low, qt: 5.12

**Comment by The-Compiler** [comment] 2018-12-15 14:45
Looking at the Archlinux package history, it looks like Qt 5.11.2 was the first version to work without any Archlinux-specific patching (with software rendering). I'm guessing since Qt 5.12, software rendering isn't required anymore (yay!).

I now disabled the check for Qt 5.11.2 is newer, so I think it's finally time to close this. Thanks to everyone who helped testing things!

**Comment by gabm** [comment] 2018-12-19 08:03
Yeah it seems to render quite nicely..

But what about the new window/tab bug that @shioyama mentions? I open a new windows (`tabs_are_windows` with `:open -t whatever.com`) and everything kind of freezes...

**Comment by The-Compiler** [comment] 2018-12-19 08:07
@gabm "Kind of freezes" sounds different from what @shioyama described - either way, most likely not a qutebrowser bug, and not a reason to prevent people from using Wayland with qutebrowser.

**Comment by shioyama** [comment] 2018-12-21 00:41
So actually, "kind of freezes" more or less described what *was* happening, but the upgrade completely fixed it!

Unfortunately, with another upgrade today to qt5-wayland, the issue is happening again. I've just downgraded qt5-wayland from  5.12.0-3 back to  5.12.0-2 and everything is working again. If anybody on wayland sees this issue, for now downgrade and it should work. I guess things are still a bit unstable in Qt land with wayland...

Other than that serious issue, I see a few other minor things, main one being when I change font size, it occasionally will momentarily bounce back to the original size before shrinking the text size down. This  didn't happen in Xwayland. I assume that's a Qt bug.

**Comment by johanhelsing** [comment] 2018-12-21 09:56
@shioyama, I asked the arch maintainer to cherry-pick the patch that fixes it (which resulted in 5.12.0-2), but he removed it again (5.12.0-3) due to nm-applet suddenly consuming a lot of CPU (which I suspect might be an application bug). [details](https://bugreports.qt.io/browse/QTBUG-69077?focusedCommentId=439708&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-439708)

I guess It's the lesser of two evils. The patch is still in the Qt 5.12 branch and will be in the 5.12.1 release unless someone convinces me it's actually a bug in Qt.

**Comment by shioyama** [comment] 2018-12-23 13:59
@johanhelsing Thanks for the explanation! That makes a lot of sense. I don't use nm-applet since there's no tray in Sway to see it, so that issue doesn't affect me and I'm quite happy with 5.12.0-2. I'll just stick with it until the next patch version is released.

**Comment by gabm** [comment] 2018-12-23 14:20
True, qt5-wayland 5.12.0-2 solves the problem,so its indeed a qt bug. I'm going to stick with it and monitor the progress meanwhile... thanks @johanhelsing @shioyama for pointing that out :+1:

**Comment by The-Compiler** [comment] 2019-04-24 14:10
FWIW looks like the fix now got [merged](https://codereview.qt-project.org/#/c/251380/) for Qt 5.12.4.
