### ISSUE TITLE
Unable to create context - wayland

### ISSUE THREAD

**Issue by JakeDevs** [qutebrowser/qutebrowser#7586] opened 2023-02-18 01:53 UTC
[4268:4316:0217/205219.850134:ERROR:shared_image_stub.cc(470)] SharedImageStub: unable to create context
[4268:4316:0217/205219.850140:ERROR:gpu_channel.cc(449)] GpuChannel: Failed to create SharedImageStub
[4268:4316:0217/205219.850407:ERROR:gl_context_egl.cc(259)] eglCreateContext failed with error EGL_BAD_CONTEXT

When I open qutebrowser in terminal these same 3 lines are spammed endlessly and all my pages are just a blank white page, even the start page.

**Comment by toofar** [comment] 2023-02-18 07:44
Please post your `:version` output. So that we get a bunch of contextual information at once.
This seems similar to https://github.com/qutebrowser/qutebrowser/issues/7440, but I don't think the root cause was actually found on that issue.

**Comment by JakeDevs** [comment] 2023-02-18 10:34
> Please post your `:version` output. So that we get a bunch of contextual information at once. This seems similar to #7440, but I don't think the root cause was actually found on that issue.

https://paste.the-compiler.org/view/8b2b86a3

Here is the outpu

**Comment by toofar** [comment] 2023-02-18 21:48
I suspect there is some issue with the nvidia drivers and Qt (5.15) on wayland. There is a bunch of similar reports around the internet but they all seem to be "resolved" by turning on software rendering or switching to XWayland. The only related resolution with an actual code change I could find was https://github.com/NVIDIA/egl-wayland/issues/40 but that is merged and should be shipping in qtwayland in arch already.

Do you get the same error with `--temp-basedir`? #7440 said they do.
If so could you try a `--temp-basedir` with qutebrowser-qt6-git and see if it is fixed in Qt6? You might want to back up your current qutebrowser data (see the "Paths" section in :version) in case you run your main config with Qt6 and then want to revert back to Qt5.

**Comment by toofar** [comment] 2023-02-19 22:01
Oh there is a test script [here](https://github.com/qutebrowser/qutebrowser/blob/qt6-v2/scripts/testbrowser/testbrowser_webengine.py) so you don't have to use a whole basedir to test. (From #7584)

**Comment by JakeDevs** [comment] 2023-02-20 01:29
Hi, Qutebrowser works with --temp-basedir. The qt6 version is just completely broken with --temp-basedir and normal. It's just a transparent window. What does --temp-basedir do?

**Comment by toofar** [comment] 2023-02-20 06:36
> What does --temp-basedir do?

It starts qutebrowser with a fresh temporary "profile" (that's what it's called in firefox). Generally if something works in a temp basedir but not your normal one its due to your config (or, rarely, something in the webengine state). To see all the config items you have which are different to the default values you can look at qute://configdiff/.

**Comment by JakeDevs** [comment] 2023-02-20 09:57
The output of configdiff is <Default Configuration> so I guess it's something in the webengine state (whatever that means).

**Comment by toofar** [comment] 2023-02-21 19:45
That would be stuff like:
* ~/.cache/qutebrowser/webengine/ = webengine cache, should be able to delete with no issues
* ~/.local/share/qutebrowser/webengine/ = more important stuff like cookies, local storage and visited links. General advice to test if this is breaking stuff is to move it out of the way and then put it back, not to delete it unless you really must
* ~/.local/share/qutebrowser/state = some not-very-important qutebrowser state (just last-geometry at the moment)

Note that [this person](https://github.com/qutebrowser/qutebrowser/issues/7587#issuecomment-1436775441) managed to fix it by running `qutebrowser -R` to tell it not to load a session. Bit surprising if that works robustly but it might!

**Comment by JakeDevs** [comment] 2023-03-03 16:40
Hi, I reinstalled my operating system and it seems to have fixed the issue.

**Comment by toofar** [comment] 2023-03-03 20:50
Okay, pity we didn't get to a root cause, but onto the next one.

**Closed by toofar** 2023-03-03 20:50 UTC
