### ISSUE TITLE
PAC proxy

### ISSUE THREAD

**Issue by mbab** [qutebrowser/qutebrowser#3868] opened 2018-04-26 14:57 UTC
I've `set content.proxy pac+file:///home/m/.config/proxy.pac` the file is:
```
function FindProxyForURL(url, host) {     
  if (isInNet(host, "10.10.0.0", "255.255.0.0"))
  {       
    return "SOCKS localhost:8080";    
  }
  return "DIRECT";
```
When try to reach computer on 10.10.0.0 network in new tab blank page appears status and title set given address, all other pages work.
`:messages` show:
`16:51:18 INFO    network pac:dnsResolve:115 Failed to resolve host during PAC evaluation:`

Same file used in Firefox works fine.

Version used:
```qutebrowser v1.2.1
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10

sip: 4.19.7
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: QFusionStyle
Platform: Linux-4.15.3-2-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/m/.cache/qutebrowser
config: /home/m/.config/qutebrowser
data: /home/m/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:02:53
```

**Comment by jgkamat** [comment] 2018-04-26 17:05
I don't think that PAC support is implemented on qtwebengine (the backend you are using), it's only available on qtwebkit. see https://github.com/qutebrowser/qutebrowser/issues/2492 for the issue on adding it to webengine. I could be wrong about this though, because I don't know how to use PAC currently :P

**Comment by mbab** [comment] 2018-04-28 15:29
setting `auto_proxy` variable didn't help but this works using `webkit` backend.

**Comment by jgkamat** [comment] 2018-04-30 23:18
Closing as duplicate of #2492 then, I think that's the same as this one

**Closed by jgkamat** 2018-04-30 23:18 UTC
