### ISSUE TITLE
Strange visual artifacts with Intel graphics

### ISSUE THREAD

**Issue by anticapsitalist** [qutebrowser/qutebrowser#6913] opened 2021-12-24 17:02 UTC
**Version info**:
```
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.4.0
Git commit: 
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.10.1
PyQt: 5.15.6

sip: 6.1.0.dev2104271705
colorama: no
jinja2: 3.0.3
pygments: no
yaml: 5.4.1
adblock: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.37.0
QtNetwork SSL: OpenSSL 1.1.1m  14 Dec 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.3.2
Platform: Linux-5.15.11-zen1-1-zen-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.10/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /tmp/qutebrowser-basedir-n2sajf_1/cache
config: /tmp/qutebrowser-basedir-n2sajf_1/config
data: /tmp/qutebrowser-basedir-n2sajf_1/data
runtime: /tmp/qutebrowser-basedir-n2sajf_1/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:13
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
Moving between tabs, scrolling, and resizing the window sometimes causes visual artifacts to appear on the webpage. They go away after a redraw. [Here](https://i.imgur.com/acOqRJT.png) is a screenshot. The screen also flashes white when switched between tabs. I've tested the same pages in the latest chromium package available for my distro (chromium-96.0.4664.110-1) and the issue isn't present. The issue is also not present on my desktop, which has an AMD GPU.

**Other info**
Laptop is an Acer N20C5 (Aspire 5)

`lspci | grep VGA`:
`0000:00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)`

`cat .local/share/xorg/Xorg.0.log | grep modesetting`:
```
[    38.157] (==) Matched modesetting as autoconfigured driver 1
[    38.157] (II) LoadModule: "modesetting"
[    38.157] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[    38.161] (II) Module modesetting: vendor="X.Org Foundation"
[    38.162] (II) modesetting: Driver for Modesetting Kernel Drivers: kms 
```
(issue occurs with xf86-video-intel as well)

**How to reproduce**
Perform an action that causes the webpage (not qutebrowser's UI elements) to be redrawn (i.e., scrolling, switching tabs, typing in a textbox).

This issue is likely impossible to reliably reproduce on different hardware. On my machine, it happens on roughly 10-25% of page redraws.

**Comment by The-Compiler** [comment] 2021-12-24 17:18
Duplicate of #6879

**Closed by The-Compiler** 2021-12-24 17:19 UTC
