### ISSUE TITLE
On "Unable to Load", "Try Again" page, "r" should be mapped to load the original page, not the error page.

### ISSUE THREAD

**Issue by markstos** [qutebrowser/qutebrowser#6635] opened 2021-08-03 15:14 UTC
When a page crashes, it's natural to try to "reload" to try again, but Qute changes the's the URL to a "data:"  URI, so reloading reloads the error page instead of the intended page.  If you don't realize the URL has change, you could end up repeatedly reloading the "error" page when you mean to reload the original page.

Since reloading the error page seems like it would have no benefit, I suggest mapping "reload" on this error page to reloads the original page.

**Comment by The-Compiler** [comment] 2021-08-03 15:16
Duplicate of #3918

**Closed by The-Compiler** 2021-08-03 15:16 UTC
