### ISSUE TITLE
Many options not working on https://community.rstudio.com/

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#3778] opened 2018-03-27 05:55 UTC
Many "buttons" not showing up:

- like, flag, delete, edit, etc. buttons in messages
- menu button next to profile picture
- bookmark, messages, preferences button at top of drop down menu from profile picture

Many icons not showing up or having only some pixels showing:

- icons on the badges in the badge page
- icon next to username in the drop down menu from the profile picture.

Very hard to use this site from qutebrowser... The icons is not a big deal, but the lack of some of the other functionality (or the fact that they might work, but you have to hover the mouse blindly trying to find where they and what they are) forced me to use chromium.

http://paste.the-compiler.org/view/6d0e1049

**Comment by The-Compiler** [comment] 2018-03-27 06:00
Hmm, that sounds odd. Is something of that reproducible without an account on the page? If there is, can you please also show a screenshot to make sure we're talking about the same thing?

Also, clickable link because I'm lazy :wink: https://community.rstudio.com/

**Comment by prosoitos** [comment] 2018-03-27 07:44
![image](https://user-images.githubusercontent.com/4634851/37953471-d2a8b110-3157-11e8-95f3-3f2b7feb081f.png)

Is this what you see in the top right corner of the page? If so, it is a small example, but one that can be seen without an account. Compare with the same top right corner in another browser. Now, if this is not what you see, then I guess there is something on my end.

**Comment by prosoitos** [comment] 2018-03-27 07:49
![image](https://user-images.githubusercontent.com/4634851/37953667-63b99da4-3158-11e8-98ed-882d7b320669.png)
A larger section of the page. Missing down arrows on the headers, missing tick boxes, icon on "Log in" button only showing some of the pixels, missing menu button, search button not showing properly

**Comment by prosoitos** [comment] 2018-03-27 07:50
![image](https://user-images.githubusercontent.com/4634851/37953785-c5e10eea-3158-11e8-92f8-dbf73f4fe8f5.png)
Same page on Chromium

**Comment by The-Compiler** [comment] 2018-03-27 07:52
Looks fine here:

![image](https://user-images.githubusercontent.com/625793/37953937-908cdc46-31a4-11e8-9c96-279ab65cf915.png)

Can you reproduce this when starting with `--temp-basedir`?

**Comment by prosoitos** [comment] 2018-03-27 08:00
Works fine with default settings :cry: Apologies: I guess I should always test with `--temp-basedir` before posting an issue.

If you still have my config file and if you have a clue what it might be, I am interested (I can resubmit a report if need be). Otherwise, I'll comment all my settings and re-add them until I find the culprit.

**Comment by The-Compiler** [comment] 2018-03-27 08:10
It's probably `content.headers.custom = {"accept": "text/html, */*; q=0.01"}` - that sounds like a bad idea in general.

**Comment by prosoitos** [comment] 2018-03-27 08:32
Bingo... Works perfectly now. I don't remember why I had set this in the first place...

And may I ask you what `input.forward_unbound_keys` does please?

Thank you for all your time @The-Compiler . I really appreciate the help.

**Comment by The-Compiler** [comment] 2018-03-27 08:44
FWIW people usually set this when trying to reduce fingerprinting, but it most likely [does more harm than good](https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#Why-isnt-passive-browser-fingerprinting-including-passive-cookies_in-Chromes-threat-model).

As for `input.forward_unbound_keys` - I'll [answer on Twitter](https://twitter.com/MHBurle/status/978323603170082816) as we already started that conversation there.

Closing this now as it turns out this wasn't a qutebrowser issue :wink:

**Closed by The-Compiler** 2018-03-27 08:44 UTC
Labels: status: can't reproduce
