### ISSUE TITLE
Use font size of current tab when opening a new one

### ISSUE THREAD

**Issue by acastello** [qutebrowser/qutebrowser#4661] opened 2019-03-20 14:43 UTC
When using screens with different DPI, it's convenient to increase the font size on some qutebrowser windows. But when opening new tabs (via links or otherwise) the default 100% gets used. It would be convenient if qutebrowser assumed you want the same font size you're using in your current tab

**Comment by The-Compiler** [comment] 2019-03-20 14:45
Duplicate of #703

**Closed by The-Compiler** 2019-03-20 14:45 UTC
