### ISSUE TITLE
Link hinting breaks when running QtWebEngine in single-process mode

### ISSUE THREAD

**Issue by rnhmjoj** [qutebrowser/qutebrowser#6277] opened 2021-03-14 15:08 UTC
### Description

Link hinting breaks when running QtWebEngine in single-process mode.
It appears that the type error is coming from the code generated by the `javascript.compile` function, called at webenginetab.py:838.  In particular, `window._qutebrowser` is undefined and the error comes from trying to call the function `window._qutebrowser.webelem.find_css`.

### Steps to reproduce

1. run qutebrowser -T -s qt.process_model single-process --debug
2. type :help and open any link
3. type f

### Version information

- qutebrowser v1.14.1
- Backend: QtWebEngine (Chromium 83.0.4103.122)
- Qt: 5.15.2
- PyQt: 5.15.2
- PyQt5.QtWebEngineWidgets: yes
- PyQt5.QtWebEngine: 5.15.2
- PyQt5.QtWebKitWidgets: no

### Backtrace

```
15:06:33 DEBUG    commands   command:run:542 command called: hint
15:06:33 DEBUG    commands   command:run:556 Calling qutebrowser.browser.hints.HintManager.start(<qutebrowser.browser.hints.HintManager object at 0x7f4ec8123430>, 'all', <Target.normal: 1>, mode=None, add_history=False, rapid=False, first=False)
15:06:33 DEBUG    modes      modeman:_handle_keypress:306 match: 2, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False, dry_run: False --> filter: True (focused: <PyQt5.QtWidgets.QWidget object at 0x7f4ec8030160>)
15:06:33 DEBUG    js         shared:javascript_log_message:150 [qute://help/quickstart.html:2] Uncaught TypeError: Cannot read property 'webelem' of undefined
15:06:33 DEBUG    message    message:_log_stack:42 Stack for error message:
  File "/nix/store/cplcfay4mr6bd4qih6hzh2w7mfsnm5zp-qutebrowser-1.14.1/bin/.qutebrowser-wrapped", line 9, in <module>
    sys.exit(main())
  File "/nix/store/cplcfay4mr6bd4qih6hzh2w7mfsnm5zp-qutebrowser-1.14.1/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 204, in main
    return app.run(args)
  File "/nix/store/cplcfay4mr6bd4qih6hzh2w7mfsnm5zp-qutebrowser-1.14.1/lib/python3.8/site-packages/qutebrowser/app.py", line 128, in run
    ret = qt_mainloop()
  File "/nix/store/cplcfay4mr6bd4qih6hzh2w7mfsnm5zp-qutebrowser-1.14.1/lib/python3.8/site-packages/qutebrowser/app.py", line 138, in qt_mainloop
    return q_app.exec_()
  File "/nix/store/cplcfay4mr6bd4qih6hzh2w7mfsnm5zp-qutebrowser-1.14.1/lib/python3.8/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 804, in _js_cb_multiple
    error_cb(webelem.Error("Unknown error while getting "
  File "/nix/store/cplcfay4mr6bd4qih6hzh2w7mfsnm5zp-qutebrowser-1.14.1/lib/python3.8/site-packages/qutebrowser/browser/hints.py", line 771, in <lambda>
    error_cb=lambda err: message.error(str(err)),
  File "/nix/store/cplcfay4mr6bd4qih6hzh2w7mfsnm5zp-qutebrowser-1.14.1/lib/python3.8/site-packages/qutebrowser/utils/message.py", line 54, in error
    stack = ''.join(traceback.format_stack())
15:06:33 ERROR    message    message:error:59 Unknown error while getting elements
```

**Comment by rnhmjoj** [comment] 2021-03-14 15:46
Is it possible `_inject_early_js` is failing in some cases?

**Comment by The-Compiler** [comment] 2021-03-15 13:11
Reproduced with: `qutebrowser -T -s qt.process_model single-process --debug  ':later 1000 open qute://help' ':later 1500 hint' ':later 2000 hint-follow s' ':later 2500 hint'`.

Works fine with Qt 5.12, 5.13 and 5.14, breaks with Qt 5.15.0+

**Comment by rnhmjoj** [comment] 2021-03-26 08:04
Do you have any idea how I could help debugging this?

**Comment by The-Compiler** [comment] 2021-03-26 08:09
Hmm - perhaps try playing around with qutebrowser's greasemonkey support with e.g. a greasemonkey script using `console.log` or something? Then it'd be possible to find out whether there are certain conditions where it doesn't get loaded anymore.

In the end, I guess we'd need a standalone C++ example to report this upstream. However, it might well be a Chromium bug, and since they're [discussing removing single-process mode entirely](https://groups.google.com/a/chromium.org/g/chromium-dev/c/9Nmw91P45wM) I wouldn't get my hopes up if so.

Out of curiosity, why are you using it?

**Comment by rnhmjoj** [comment] 2021-03-26 10:48
> In the end, I guess we'd need a standalone C++ example to report this upstream. However, it might well be a Chromium bug, and since they're discussing removing single-process mode entirely I wouldn't get my hopes up if so.

Argh, that's bad. I guess it's not worth the trouble if it will get reomved anyway.

> Out of curiosity, why are you using it?

I just don't like programs spawning a whole process forest:
```
$ ps -eo rss,cmd cf | grep 'qute\|Qt'
228340 qutebrowser
  8536  \_ QtWebEngineProc
  8240  \_ QtWebEngineProc
 10512  |   \_ QtWebEngineProc
102256  |       \_ QtWebEngineProc
163716  |       \_ QtWebEngineProc
 93256  |       \_ QtWebEngineProc
116644  |       \_ QtWebEngineProc
 43364  \_ QtWebEngineProc
 10040  \_ QtWebEngineProc

$ ps -eo rss,cmd c | grep 'qute\|Qt'
274908 qutebrowser
```

It also reduces the memory usage from by a third. 
I now there are security implications, but considering I almost always have javascript disabled it can't be too much of a problem.

**Comment by The-Compiler** [comment] 2021-04-01 14:04
According to https://bugs.chromium.org/p/chromium/issues/detail?id=1162066#c8:

> Alright, I think that dropping --single-process has been pretty decisively shot down in that thread

So, we're lucky on that front it seems.

**Comment by The-Compiler** [comment] 2021-04-13 13:58
Didn't notice it until now, but this looks like a duplicate of #5569.

**Closed by The-Compiler** 2021-04-13 13:58 UTC
Labels: bug: behavior, component: QtWebEngine, priority: 2 - low, qt: 5.15, status: needs triage
