### ISSUE TITLE
Strange static and speedup in youtube and other similar sites

### ISSUE THREAD

**Issue by zamlz** [qutebrowser/qutebrowser#5544] opened 2020-06-24 18:24 UTC
**Version info**:

```
qutebrowser v1.12.0
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2
```

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
Whenever I load up a youtube video, it takes about 3-20 seconds for it to stop playing audio as static. Furthermore it seems that the video itself also speeds up too. It eventually fixes itself, but if there is an ad in the video, the issue will reappear.

**How to reproduce**

youtube.com is for sure affected, and I can reproduce it by playing any video. Happens on other tube sites, but I've only checked a few.

**Comment by zamlz** [comment] 2020-06-24 18:32
I would like to add that it seems that if I start qutebrowser from the terminal once (not using the --temp-basedir) it seems to have fixed the issue (I was curious about what gets printed out), but I'd like to confirm if it stays fixed. It seems now whenever I open qutebrowser its okay, but I'm going to check to see if it persists after a reboot.

**Comment by The-Compiler** [comment] 2020-06-24 18:45
Can you check if you can reproduce the same with KDE Falkon (and maybe Chromium as well)?

**Comment by The-Compiler** [comment] 2020-07-06 17:31
@zamlz Any update on this?

**Comment by zamlz** [comment] 2020-07-10 23:27
My apologies, I have not had the time to check this further yet.

**Comment by The-Compiler** [comment] 2020-07-12 15:40
Closing this for now because I doubt this is a qutebrowser issue. If you don't see the same issue with KDE Falkon, please let me know!

**Closed by The-Compiler** 2020-07-12 15:40 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by zamlz** [comment] 2020-07-31 16:09
Yeah keep this closed, I started using spotify recently I noticed it had the same problem. Seems like its an issue with pulseaudio instead.

**Comment by The-Compiler** [comment] 2020-07-31 16:11
Perhaps, or some issue in the underlying Chromium (which both qutebrowser and Spotify use, IIRC) on your system. If you find out something, please keep me updated, I'm curious! :slightly_smiling_face:

**Comment by Kazimazi** [comment] 2020-09-28 08:26
for me falkon has the same problem

**Comment by zamlz** [comment] 2020-09-29 16:03
So I completely reinstalled my whole sound stack. And I'm not sure if that
actually fixed it yet (haven't done specific tests) but I haven't been
noticing it recently. I think it might have to do with having the alsaaudio
service starting on boot which isn't there anymore.

**Comment by vonpost** [comment] 2020-12-26 03:37
Got this same problem, it's present in Falkon as well, but not in Chromium. I guess this points towards it being a QtWebEngine problem. 
It appears whenever I play a video anywhere with a static crackling for a good 10 seconds and the video running at something like 2x speed.

**Comment by vcanadi** [comment] 2021-02-12 20:34
I'm experiencing the same thing on any video inside qb (yt, netflix preview, etc.). Haven't noticed this in chromium or anywhere else. 
I'm suspecting pulse as well. After turning on pavucontrol-qt, its window flickers and static and video speedup stops after couple of seconds.
