### ISSUE TITLE
clicking link on startpage.com does not select new tab if using webengine

### ISSUE THREAD

**Issue by johnlane** [qutebrowser/qutebrowser#2744] opened 2017-06-20 09:27 UTC
(This follows IRC chat today 20.6.17) When using the webengine backend, clicking on some web links (such as the search results presented by [startpage.com][1]) opens the link in a new tab but does not select the new tab, instead leaving the original tab in view. There is little visible feedback that clicking a click has any effect (unless watching the tab bar for the appearance of a new tab).

Contrast with wekbit-ng where clicking a similar link does select the new tab, which is the desired behaviour when clicking a link on a page.

Note however that this appears to be site-specific behaviour and peculiar to startpage:

| | webkit | webengine |
| --- | --- | --- |
startpage | new tab is selected | new tab is not selected |
google    | current tab        | current tab
ddg       | current tab        | current tab

[1]: https://startpage.com/do/search?query=qutebrowser

Note also that `control+click` does open and select a new tab (setting `tabs.background-tabs = false`)

[relevant code](https://github.com/qutebrowser/qutebrowser/blob/v0.10.1/qutebrowser/browser/webengine/webview.py#L91-L97)

----------
version information:
    
    qutebrowser v0.10.1
    Git commit: v0.10.0-377-g1539301d6 (2017-04-24 08:41:29 +0200)
    Backend: QtWebEngine (Chromium 56.0.2924.122)
    Backend: QtWebKit-NG (WebKit 602.1)
    Linux 4.11.5-1-ARCH #1 SMP PREEMPT Wed Jun 14 16:19:27 CEST 2017 x86_64 GNU/Linux

**Comment by The-Compiler** [comment] 2020-06-24 09:34
Duplicate of #3231

**Closed by The-Compiler** 2020-06-24 09:34 UTC
Labels: component: QtWebEngine, priority: 2 - low, status: needs triage
