### ISSUE TITLE
Userscript on hint

### ISSUE THREAD

**Issue by ElModdy** [qutebrowser/qutebrowser#4753] opened 2019-05-02 12:53 UTC
Hi, I'm trying to launch a userscript from hint mode like that:
`config.bind('F','hint -r links userscript hintProblem rb')`
The problem is that qutebrowser tries to launch the userscript called `hintProblem rb` but I would like it could  interpret `rb` as an argument of `hintProblem`

**Comment by The-Compiler** [comment] 2019-05-02 12:58
Duplicate of #3400

**Closed by The-Compiler** 2019-05-02 12:58 UTC
