### ISSUE TITLE
Small select list

### ISSUE THREAD

**Issue by vanarok** [qutebrowser/qutebrowser#7154] opened 2022-05-02 13:59 UTC
**Version info**: https://paste.the-compiler.org/view/abdc5b70

**Does the bug happen if you start with `--temp-basedir`?**:yes

**Description**
![2022-05-02T17:48:56,186954100+04:00](https://user-images.githubusercontent.com/6105977/166245515-a01e0ad2-4720-4cf0-bc3d-cc5170c0b4bf.png)
I have two monitors with specify dpi scale (1 and 1.5).
**How to reproduce**
I dont know

**Comment by The-Compiler** [comment] 2022-05-02 14:08
Can you try with another browser using QtWebEngine, such as KDE Falkon?

**Comment by vanarok** [comment] 2022-05-02 17:18
The same in this browser

**Comment by The-Compiler** [comment] 2022-05-02 17:27
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2022-05-02 17:27 UTC
Labels: status: can't reproduce, status: needs triage
