### ISSUE TITLE
Gmail redirect loop

### ISSUE THREAD

**Issue by rakanalh** [qutebrowser/qutebrowser#4281] opened 2018-10-01 21:04 UTC
Hello,

I was able to reproduce a bug when using gmail which is by:
1. Start fresh
2. Login to gmail
3. Close qutebrowser (:wq)
4. Start qutebrowser

The problem has been consistently reproducible and the only way to i was able to figure out to fix the issue is to `rm -rf ~/.local/share/qutebrowser/`... which is neither conveinent nor correct (on my end)

version info:
```
qutebrowser v1.4.2
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.12
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.5-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/rakan/.cache/qutebrowser
config: /home/rakan/.config/qutebrowser
data: /home/rakan/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser
```

**Comment by The-Compiler** [comment] 2018-10-01 21:10
No issues here with `--basedir /tmp/gmail`. I get logged in again like expected (when waiting 30s before closing due to #2263).

You'll need to be more specific - what do you do exactly and what happens?

**Comment by rakanalh** [comment] 2018-10-01 21:14
I just installed qutebrowser today and started playing with it. Basically i login to gmail which works on a clean slate. When i close qutebrowser and open it back, gmail complains about a redirect loop then takes me to a page which says that something is wrong with my cookies.

**Comment by rakanalh** [comment] 2018-10-01 21:14
Wrong button

**Comment by The-Compiler** [comment] 2018-10-01 21:17
Some questions:

- Can you reproduce it when starting with `--basedir /tmp/gmail` twice as well?
- Can you show a screenshot of that page?
- Can you try to reproduce it with [KDE Falkon](https://www.falkon.org/)?
- Can you please do `:report` after it happens so I can take a look at the logs?

**Comment by The-Compiler** [comment] 2018-10-01 21:27
re 1.: Can you try again but wait for 30s after logging in before you quit qutebrowser?

**Comment by rakanalh** [comment] 2018-10-01 21:31
Same issue... the weird part is, if i navigate to google.com, it actually shows me as logged in. I tried navigating to other google services such as Calendar or Google Drive and it works seemlessly.

**Comment by phmongeau** [comment] 2018-10-01 22:52
Hi, I have the same issue and can reproduce it without restarting the browser:

1. `qutebrowser --basedir /tmp/gmail`
2. `:open gmail.com` and login
3. wait 30s
4. `:open -t gmail.com` -> ERR_TOO_MANY_REDIRECTS

**Comment by The-Compiler** [comment] 2018-10-02 05:49
It does look like GMail is indeed stuck in a redirect loop - looking at the URLs:

- http://gmail.com/
- https://gmail.com/
- https://www.google.com/gmail/
- https://mail.google.com/mail/
- https://mail.google.com/mail/u/0/
- https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.g…
- https://mail.google.com/accounts/SetOSID?authuser=0&continue=https%3A%2F%2Fmail.google.com%2Fmail%2…
- https://mail.google.com/mail/?pli=1#
- https://mail.google.com/mail/u/0/?pli=1#
- https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.g…
- https://mail.google.com/accounts/SetOSID?authuser=0&continue=https%3A%2F%2Fmail.google.com%2Fmail%2…
- https://mail.google.com/mail/?rli=xyREDACTED&rld=1&pli=1#
- https://mail.google.com/mail/u/0/?rli=xy76REDACTED&rld=1&pli=1#
- https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.g…
- https://mail.google.com/accounts/SetOSID?authuser=0&continue=https%3A%2F%2Fmail.google.com%2Fmail%2…
- https://mail.google.com/mail/?rli=xyREDACTED&rld=2&pli=1#
- https://mail.google.com/mail/u/0/?rli=xyREDACTED&rld=2&pli=1#
- https://accounts.google.com/ServiceLogin?service=mail&passive=true&rm=false&continue=https://mail.g…
- https://mail.google.com/accounts/SetOSID?authuser=0&continue=https%3A%2F%2Fmail.google.com%2Fmail%2…
- https://mail.google.com/mail/?rli=xyREDACTED&rld=3&pli=1#
- https://mail.google.com/mail/u/0/?rli=xyREDACTED&rld=3&pli=1#

Can you try whether `:set content.cookies.accept all` or `:set content.headers.referer always` (needs a restart) makes any difference?

**Comment by rakanalh** [comment] 2018-10-02 07:40
> Can you try whether :set content.cookies.accept all or :set content.headers.referer always (needs a restart) makes any difference?

Didn't work for me `set contnet.headers.referer always` showed an error saying it's not available in QTWebEngine backend.

**Comment by The-Compiler** [comment] 2018-10-02 07:53
Nevermind about `content.headers.referer` then, that was added recently (and isn't released yet). What about `:set content.cookies.accept all`?

**Comment by rakanalh** [comment] 2018-10-02 08:14
Sorry, forgot to mention that one. It didn't seem to help (i set it, restarted qutebrowser)

**Comment by rakanalh** [comment] 2018-10-02 08:16
After posting my comment, i thought about setting the value of `content.cookies.accept all` permanently in my config.py... seems to have resolved the problem. I can now open gmail without issues

**Comment by The-Compiler** [comment] 2018-10-02 08:18
@phmongeau can you please give that a try as well?

**Comment by VictorBjelkholm** [comment] 2018-10-02 14:30
I also had this issue happen to me. Setting `c.content.cookies.accept = 'all'` in config.py solved the issue.

**Comment by The-Compiler** [comment] 2018-10-02 14:39
Can someone of you please try reproducing this in Chromium as well? Start it with `--user-data-dir=/tmp/foo` to get a fresh instance, then go to Settings -> Advanced -> Content settings (under "Privacy and Security") -> Cookies, and there enable "Block third-party cookies".

**Comment by phmongeau** [comment] 2018-10-03 00:09
both `:set content.cookies.accept all` or `:set content.headers.referer always` fix the issue for me.

I tried blocking third-party cookies in firefox and chromium, but wasn't able to reproduce the issue. Do you know if they also have a settings to disable the referer header?

**Comment by phmongeau** [comment] 2018-10-03 23:49
Oh right, `content.headers.referer always` doesn't actually fix the issue. I had enabled `content.cookies.accept all` and disabled it after and it continued to work because I got the cookie while the setting was enabled.

I tested again with a temp basedir and it's definitly only `content.cookies.accept all` that fixes the issue.

**Comment by rpietro** [comment] 2018-10-15 07:09
So, I used the `: set content.cookies.accept all` and it took care of it. But when I tried to log into a second gmail account I have I got the same error. Repeating the same command on the second gmail page took care of it, but my expectation was that the accept all command would be global. Again, this question is more of a curiosity, fix above does work.

**Comment by The-Compiler** [comment] 2018-10-15 13:28
That setting is indeed global, so either there's some bug somewhere, or something else happened. Can you reproduce this?

**Comment by Jasu** [comment] 2018-10-15 20:56
I encountered the issue today. Deleting Cookies in `~/.local` did not help, but opening the inspector and unregistering mail.google.com's service worker did.

**Comment by jgkamat** [comment] 2018-10-16 06:28
> This used to work for me, although I'm not sure whether the upgrade from
> 1.5.0 to 1.5.1 or from 1.4.2.2 to 1.5.0 broke this for me. Or maybe Google
> just changed something.

I'm guessing this is related to the gmail redesign, as that's when I started
to hear about this.

**Comment by rpietro** [comment] 2018-10-21 10:01
It also happens with youtube.

**Comment by teon** [comment] 2018-10-25 07:45
I confirm this bug (screenshot: https://prnt.sc/l8tya9). I have delated all cookies I have also cleared all cache (removed ~/.cache/qutebrowser) - nothing works. Gmail just stopped working.

I needed to go back to Firefox ;-(

**Comment by The-Compiler** [comment] 2018-10-25 08:35
@teon or you could `:set content.cookies.accept all` instead as per the comments above :wink:

**Comment by The-Compiler** [comment] 2018-10-25 08:57
I can now reproduce this as well - I guess GMail had some kind of staged rollout or so. I reported it upstream as [QTBUG-71393](https://bugreports.qt.io/browse/QTBUG-71393).

The only thing qutebrowser can do is setting `content.cookies.accept` to `all` instead of `no-3rdparty` by default - I've toyed with the idea of doing that for a while anyways, I guess this is the final straw...

**Comment by teon** [comment] 2018-10-25 11:48
@The-Compiler did that, thank you!

**Comment by The-Compiler** [comment] 2018-10-26 08:43
Just did a quick v1.5.2 release which sets `content.cookies.accept` to `all` by default.

**Comment by The-Compiler** [comment] 2018-10-29 15:21
There's a fix for that in Qt now: https://codereview.qt-project.org/#/c/244021/

I'd like to keep `content.cookies.accept` to `all` by default (to be in line with what other browsers do), but based on that change, we can probably add a workaround.

**Comment by The-Compiler** [comment] 2018-10-29 20:05
Workaround:

```diff
diff --git a/qutebrowser/browser/webengine/cookies.py b/qutebrowser/browser/webengine/cookies.py
index d9d11cd98..37d24d3de 100644
--- a/qutebrowser/browser/webengine/cookies.py
+++ b/qutebrowser/browser/webengine/cookies.py
@@ -20,7 +20,7 @@
 """Filter for QtWebEngine cookies."""
 
 from qutebrowser.config import config
-from qutebrowser.utils import utils
+from qutebrowser.utils import utils, qtutils
 
 
 def _accept_cookie(request):
@@ -29,7 +29,13 @@ def _accept_cookie(request):
     if accept == 'all':
         return True
     elif accept in ['no-3rdparty', 'no-unknown-3rdparty']:
-        return not request.thirdParty
+        if qtutils.version_check('5.11.3'):
+            third_party = request.thirdParty
+        else:
+            # WORKAROUND for https://bugreports.qt.io/browse/QTBUG-71393
+            third_party = (request.thirdParty and
+                           not request.firstPartyUrl.isEmpty())
+        return not third_party
     elif accept == 'never':
         return False
     else:
```

waiting for the Qt change to be merged before commiting it.

**Closed** 2018-10-31 08:13 UTC
Labels: bug: behavior, component: QtWebEngine, priority: 0 - high, qt

**Comment by The-Compiler** [comment] 2018-10-31 08:17
With that workaround, GMail works again with `content.cookies.accept = no-3rdparty`. However, I'd still prefer to keep the default on `all` since that's in line with what other browsers do.

**Comment by mschilli87** [comment] 2018-10-31 11:13
> However, I'd still prefer to keep the default on all since that's in line with what other browsers do.

On the other hand, if whatever other browser do would be ideal, we wouldn't need this one. :wink:

Joking aside, while I think people running into 'issues' and realizing that they were caused by blocking something that can be considered 'dangerous' might help to educate the masses (*'Why does this webapge actually need 3rd party cookies to function? What do these contain? And which '3rd party' is putting these files on my device?'*), I'm totally fine with changing this setting to a non-default (that's what settings are for after all and I for one couldn't care less about not being able to login to Google anyways) - after all, the 'masses' are probably not using this gem of a browser anyways.

**Comment by tgy** [comment] 2018-11-09 09:52
I had the problem too, `content.cookies.accept = all` fixed it but I would prefer using `no-3rdparty`. When do you plan on releasing this?

**Comment by cvincent** [comment] 2018-11-21 11:17
Is that really the default in other browsers? I seem to remember years ago that Safari introduced "no third party cookies" as a default, and that being relatively quickly picked up by the other major browsers, and having to work around that default for my old startup. In fact, I very recently reported a bug in someone else's web app which could be worked around by *allowing* third party cookies in my browser (Firefox), which I was running on a brand new laptop.

Either way, I agree with @mschilli87 that defaulting to "no third party cookies" is the best default for end users.
