### ISSUE TITLE
Missing hint for span tab

### ISSUE THREAD

**Issue by CmdrSharp** [qutebrowser/qutebrowser#3814] opened 2018-04-04 12:28 UTC
Version: 2.7.2

I'm missing a hint on a webpage. Hints seem to mark every element correctly (from images, to inputs, to buttons) - but neglects two spans that act as tab switchers.
Is there any way to have QuteBrowser understand that these (based on their markup) should be hinted and clickable?

![image](https://user-images.githubusercontent.com/5938745/38307598-73ac3786-3814-11e8-9e65-28e388bde4db.png)

Forgot to note, this is the relevant markup:

```
<div class="tabs2_strip" id="tabs2_section" data-initial-tab-index="0" style="display: block" role="tablist">
    <span class="tab_header">
        <span class="tabs2_tab tabs2_active" tabindex="0" role="tab">
            <span mandatory="true" class="label_description" style="display: none; margin-right: 2px; visibility: hidden;">
            *
            </span>

            <span class="tab_caption_text">General</span>
        </span>
    </span>

    <span class="tab_header">
        <span class="tabs2_tab" tabindex="-1" role="tab">
            <span mandatory="true" class="label_description" style="display: none; margin-right: 2px; visibility: hidden;">
            *
            </span>
            <span class="tab_caption_text">Ticket Log</span>
        </span>
    </span>
</div>
```

Cheers!

**Comment by CmdrSharp** [comment] 2018-04-04 18:42
Thanks @jgkamat, I'll keep a look at it - though I suspect it'll be a while until that makes it into a release.
Not sure I'd say a span itself is always clickable, but it's certainly not uncommon. A more dynamic approach to selectors may be a good idea.
Something simple, that allows perhaps using the mouse to identify an element would be cool - though I'd have no idea how to implement it myself since this is outside of my own development areas.

**Comment by jgkamat** [comment] 2018-04-04 21:05
Ah, I'm pretty sure the span isn't actually what's causing the click to be registered, it's a javascript click handler (I think). In that case, this is probably a speical case of #178.

**Comment by jgkamat** [comment] 2018-04-05 06:28
Actually, this is already in the top post of that issue, so I'm closing this as a duplicate of #178.

**Closed by jgkamat** 2018-04-05 06:28 UTC
Labels: component: hints
