### ISSUE TITLE
Text in command line becomes deselected when caret reaches left edge

### ISSUE THREAD

**Issue by gulkily** [qutebrowser/qutebrowser#4376] opened 2018-10-22 21:10 UTC
**Version info (see `:version`)**:

v1.5.1
Git commit: c7a21b37e-dirty (2018-10-10 08:23:17 +0200)

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):

N/A

**Description**

When selecting text in the command line with the keyboard, moving the cursor left will cause the text to be de-selected once it reaches the left edge of the field.

**How to reproduce**
1. Open a page
2. Press g,o to pre-fill ":open <url>" in command line
3. Hold down Shift and start pressing the left arrow key; The text should become selected from the right to the left.
4. Keep pressing the arrow key until it reaches the beginning of the field/text, and then press it again.

Expected: Text remains in command line remains selected

Actual: Text in command line becomes de-selected

**Comment by user202729** [comment] 2018-10-23 00:19
Same situation when `[Home]` is pressed. This is probably a side effect of the fact that the `:` cannot be selected.

Also same situation for `/` or `?` mode. (search forward/backward)

**Comment by The-Compiler** [comment] 2018-10-23 11:22
Duplicate of #2886

**Closed by The-Compiler** 2018-10-23 11:22 UTC
