### ISSUE TITLE
crashes on page with emoji in title

### ISSUE THREAD

**Issue by swalladge** [qutebrowser/qutebrowser#2306] opened 2017-02-09 00:40 UTC
When I open a page containing a unicode emoji in the title element, such as this:

```
<html>
  <head>
    <title>🕴️</title>
  </head>
  <body>
    <p>
      Test page with a unicode emoji in the title.
    </p>
  </body>
</html>
```

I get weird behaviour depending on where/how I open qutebrowser.

- `qutebrowser --backend webengine` = seg fault - see debug log: http://paste.the-compiler.org/view/a3cee804 and gdb trace: http://paste.the-compiler.org/view/ce58a36e
- `qutebrowser --backend webengine --temp-basedir` == bad rendering ( https://nextcloud.walladge.net/s/CNUAHVQcOX7INNd )
- `qutebrowser` == abort (core dumped) with the following backtrace: http://paste.the-compiler.org/view/2d478a1a
- It was weirder, because it wouldn't crash and just display the bad rendering when run from the terminal, but crash when run from the .desktop file, but it seems to be consistent now after pulling the latest version of qutebrowser.
- EDIT: also when running from the terminal it will actually render the emoji correctly, but seems to crash soon after.

## qutebrowser version info

```
qutebrowser v0.9.1
Git commit: v0.9.0-220-g038a517c5 (2017-02-08 23:46:37 +0100)
Backend: QtWebKit

CPython: 3.6.0
Qt: 5.8.0
PyQt: 5.7.1

sip: 4.19
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.5
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
pdf.js: 1.6.210 (/usr/share/pdf.js/build/pdf.js)
Webkit: 538.1
SSL: OpenSSL 1.0.2k  26 Jan 2017

Style: Qt5CTProxyStyle
Platform: Linux-4.9.8-1-ARCH-x86_64-with-arch, 64bit
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
OS Version: 

--- /etc/lsb-release ---
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"

--- /etc/os-release ---
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux

Paths:
config: /home/samuel/.config/qutebrowser
data: /home/samuel/.local/share/qutebrowser
system_data: /home/samuel/.local/share/qutebrowser
cache: /home/samuel/.cache/qutebrowser
download: /home/samuel/Downloads
runtime: /run/user/7000/qutebrowser
```

**Comment by The-Compiler** [comment] 2017-02-11 20:54
Can you try with e.g. QupZilla please?

**Comment by swalladge** [comment] 2017-02-12 22:07
Aha, same issue. http://paste.the-compiler.org/view/186f1722

Also probably related - [CopyQ](https://github.com/hluk/CopyQ) also crashes now after copying some emoji into the clipboard.

**Comment by The-Compiler** [comment] 2017-02-18 10:47
This is interesting... how about this?

```python
from PyQt5.QtWidgets import QApplication, QLabel

app = QApplication([])
label = QLabel(text='a🕴️b')
label.show()
app.exec_()
```

**Comment by swalladge** [comment] 2017-02-19 22:01
Yep, that segfaults instantly. Interestingly enough, now qutebrowser _doesn't_ crash, but simply shows a missing glyph box instead of the emoji...

**Comment by The-Compiler** [comment] 2017-02-19 22:06
Okay, this definitely looks like a Qt bug then - I don't have the time to track those down too I'm afraid, too busy with qutebrowser bugs :wink:

Can you please open an issue in the [Qt bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) with that example and stacktrace and link it here though?

**Comment by swalladge** [comment] 2017-02-20 00:07
QT bug report: https://bugreports.qt.io/browse/QTBUG-59022

**Comment by The-Compiler** [comment] 2017-02-20 04:22
Thank you! Closing this then.

**Closed by The-Compiler** 2017-02-20 04:22 UTC

**Comment by The-Compiler** [comment] 2017-11-22 12:26
I wonder whether the fix for [QTBUG-64239](https://bugreports.qt.io/browse/QTBUG-64239) also fixes this. It's part of Qt 5.9.3, which was released today. @swalladge can you check whether you can still reproduce this now, and then re-check as soon as Arch has Qt 5.9.3?

**Comment by swalladge** [comment] 2017-11-22 21:45
Can confirm, segfault still happens in 5.9.2. I'll let you know regarding 5.9.3 as soon as I get it installed.

**Comment by swalladge** [comment] 2017-11-22 21:51
Can confirm, segfault still happens in 5.9.2. I'll let you know regarding 5.9.3 as soon as I get it installed.

**Comment by swalladge** [comment] 2017-11-25 13:16
@The-Compiler it renders perfectly with no segfaults with 5.9.3! :+1:
