### ISSUE TITLE
qutebrowser can't play Twitch player on Windows

### ISSUE THREAD

**Issue by umplifierr** [qutebrowser/qutebrowser#7451] opened 2022-10-26 16:25 UTC
**Version info**: qutebrowser 2.5.2
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
CPython: 3.9.13
PyQt: 5.15.6

**Description**
Hey guys, I am a new user on qutebrowser, I really I fell in love of this browser I encountered following issue:

When I trying to open on certain page on twitch.tv for example opening: https://www.twitch.tv/ninja, 
I am getting this massage in center of my player: 
(This video is either unavailable or not supported in this browser. (Error #4000))

BTW qutebrowser can't play the netflix player as well and 

what should I do. help please.

![Screenshot 2022-10-26 154831](https://user-images.githubusercontent.com/116736534/198058857-b85aa455-0871-48b9-a2e6-0e6ccc7b8482.png)

@The-Compiler 

**How to reproduce**

**Comment by The-Compiler** [comment] 2022-10-26 16:31
Duplicate of #7019

**Closed by The-Compiler** 2022-10-26 16:31 UTC
