### ISSUE TITLE
Show statusbar when in insert mode despite statusbar.hide=true

### ISSUE THREAD

**Issue by krzemian** [qutebrowser/qutebrowser#3304] opened 2017-11-16 16:33 UTC
As an addition to #2157, I like to keep statusbar hidden in order to maximize working space (working from a 13-inch laptop). I often find it ambiguous to work out if I'm in Insert Mode and a small hint (preferrably not the whole horizontal/vertical line) would be a nice addition. 
My current workaround (haven't tested it yet) would be to set statusbar.hide=false and make the statusbar just a few pixels high, with a non-intrusive background color and font color set to match the background (making it in turn invisible)

Using qb v1.0.3

**Comment by jgkamat** [comment] 2017-11-16 16:36
Duplicate of https://github.com/qutebrowser/qutebrowser/issues/1747

**Closed by jgkamat** 2017-11-16 16:36 UTC
