### ISSUE TITLE
Form fields not recognized in Todoist despite input.insert_mode.auto_load=true

### ISSUE THREAD

**Issue by krzemian** [qutebrowser/qutebrowser#3301] opened 2017-11-16 16:13 UTC
1. Set input.insert_mode.auto_load = true
2. Go to https://todoist.com/app (requires to register with a free account (or use a dummy account I've created: 123asd123@inboxbear.com for both login and password)
3. Click/focus on "Quick Find" search bar and see it doesn't switch to insert mode
4. Click "Add task" link below the task list and see that it correctly opens a form field and focuses the caret, however it doesn't switch to insert mode.

Using qb v1.0.3

**Comment by jgkamat** [comment] 2017-11-16 16:25
I don't think they are using a html textarea (I think that might be built with javascript entirely) so I don't know if it would be possible to figure out that you're typing (as everything is being handled by javascript). If you turn off js, the entire page dosen't load.

**Comment by The-Compiler** [comment] 2017-11-16 19:38
Duplicate of #253

**Closed by The-Compiler** 2017-11-16 19:38 UTC
