### ISSUE TITLE
Broken statusbar for nonexistent url when javascript disabled

### ISSUE THREAD

**Issue by amerlyq** [qutebrowser/qutebrowser#5819] opened 2020-10-19 13:50 UTC
**Version info**:

https://paste.the-compiler.org/view/7d9eaab6

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Statusbar shows complete data:text/html content instead of simple URL `http://ss.ss`
![2020-10-19-164508_1202x396_scrot](https://user-images.githubusercontent.com/5730096/96459188-7f623100-122a-11eb-92a8-638f42a5d025.png)

**How to reproduce**

Open nonexistent url, get ERR_NAME_NOT_RESOLVED, disable javascript and reload
```
$ qutebrowser --temp-basedir
:open ss.ss
:set content.javascript.enabled false
:reload
```

**Possible mitigation / workarounds**

Allow patterns without host to explicitly allow scripts execution on such banner pages (currently prohibited).
`config.set('content.javascript.enabled', True, '*:///*')`
Or make this page to have proper e.g. `qute://404` url.

**Comment by The-Compiler** [comment] 2020-10-19 13:52
Duplicate of #3918

**Closed by The-Compiler** 2020-10-19 13:52 UTC

**Comment by amerlyq** [comment] 2020-10-19 13:59
Ah, for me that duplicate was impossible to find by any keywords combinations I tried before posting issue.
Moreover even when reading that old description it was not immediately obvious how they are related.
Thanks for keeping all this knowledge in your head! :)
