### ISSUE TITLE
Restore page cache after restart

### ISSUE THREAD

**Issue by pzant** [qutebrowser/qutebrowser#7902] opened 2023-09-09 10:06 UTC
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Before restarting the browser I can go forward/backward per page but after restart I can't.

**Comment by toofar** [comment] 2023-09-09 10:17
Duplicate of https://github.com/qutebrowser/qutebrowser/issues/5359

**Closed by toofar** 2023-09-09 10:17 UTC
