### ISSUE TITLE
Cannnot scroll using <Space> after opening a link

### ISSUE THREAD

**Issue by magnetophon** [qutebrowser/qutebrowser#3913] opened 2018-05-14 15:45 UTC
Since upgrading from 1.2.1 to 1.3.0, I get the above behaviour.
It is solved when I add these lines tomy config:
```
config.bind('<Space>', 'scroll-page 0 1')
config.bind('<Shift-Space>', 'scroll-page 0 -1')
```

```
qutebrowser --version                                                                                                                                                                    [17:43:09]
17:43:35 ERROR: Error while loading config.py
Traceback (most recent call last):
  File "/nix/store/cfcd2j5l3ff8j51r6ad60ka5qg043lgd-qutebrowser-1.3.0/lib/python3.6/site-packages/qutebrowser/config/configinit.py", line 60, in early_init
    configfiles.read_config_py(config_file)
  File "/nix/store/cfcd2j5l3ff8j51r6ad60ka5qg043lgd-qutebrowser-1.3.0/lib/python3.6/site-packages/qutebrowser/config/configfiles.py", line 569, in read_config_py
    raise configexc.ConfigFileErrors('config.py', api.errors)
qutebrowser.config.configexc.ConfigFileErrors: Errors occurred while reading config.py:
  While setting 'tabs.favicons.show': Invalid value 'True' - expected a value of type str but got bool.
  While setting 'window.hide_wayland_decoration': No option 'window.hide_wayland_decoration' (this option was renamed to 'window.hide_decoration')
qutebrowser v1.3.0
Git commit: 
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.5
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.6
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.0.2o  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.7-x86_64-with-glibc2.3.4, 64bit
Linux distribution: NixOS 18.09.git.a931395 (Jellyfish) (unknown)
Frozen: False
Imported from /nix/store/cfcd2j5l3ff8j51r6ad60ka5qg043lgd-qutebrowser-1.3.0/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /nix/store/q1bnn9w3kvlgxqmy62z9mcshhcdjwh7i-qtbase-5.10.1/libexec, data path: /nix/store/q1bnn9w3kvlgxqmy62z9mcshhcdjwh7i-qtbase-5.10.1
OS Version: 

--- /etc/os-release ---
NAME=NixOS
ID=nixos
VERSION="18.09.git.a931395 (Jellyfish)"
VERSION_CODENAME=jellyfish
VERSION_ID="18.09.git.a931395"
PRETTY_NAME="NixOS 18.09.git.a931395 (Jellyfish)"

Paths:
cache: /home/bart/.cache/qutebrowser
config: /home/bart/.config/qutebrowser
data: /home/bart/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Uptime: 0:00:00

```

**Comment by jgkamat** [comment] 2018-05-14 19:49
Is this happening when hinting links with `tab-bg`?  I don't think thats a new issue, but #3906 should solve that. 

Do you have `tabs.background` set to true? That PR could solve the issue in that case as well, could you test it out and see on your config?

**Comment by jgkamat** [comment] 2018-05-14 19:50
Unrelated to this issue but:

>Traceback (most recent call last):
  File "/nix/store/cfcd2j5l3ff8j51r6ad60ka5qg043lgd-qutebrowser-1.3.0/lib/python3.6/site-packages/qutebrowser/config/configinit.py", line 60, in early_init
    configfiles.read_config_py(config_file)
  File "/nix/store/cfcd2j5l3ff8j51r6ad60ka5qg043lgd-qutebrowser-1.3.0/lib/python3.6/site-packages/qutebrowser/config/configfiles.py", line 569, in read_config_py
    raise configexc.ConfigFileErrors('config.py', api.errors)
qutebrowser.config.configexc.ConfigFileErrors: Errors occurred while reading config.py:
  While setting 'tabs.favicons.show': Invalid value 'True' - expected a value of type str but got bool.
  While setting 'window.hide_wayland_decoration': No option 'window.hide_wayland_decoration' (this option was renamed to 'window.hide_decoration')

You may want to look at the changelog, those two settings have updated choices in the new release.

**Comment by jgkamat** [comment] 2018-05-14 21:10
Assuming your python package has the needed dependencies, you should be able to 

`python3 -m qutebrowser` 

at the root of a repo checked out to the commit. I am pretty sure it will solve your issue though, I'll see if I can make a release tarball at some point.

**Comment by jgkamat** [comment] 2018-05-15 00:07
I'd rather keep this open for visibility until the related PR is merged into master. I'll link them so that will happen automatically.

**Comment by Ape** [comment] 2018-05-23 17:16
This is a duplicate of #2320.

**Comment by jgkamat** [comment] 2018-05-23 17:34
Yup, sorry I didn't see that sooner :P

**Closed by jgkamat** 2018-05-23 17:34 UTC
Labels: bug: behavior, component: QtWebEngine, priority: 2 - low
