### ISSUE TITLE
Vim mode in text-area

### ISSUE THREAD

**Issue by python-clojure** [qutebrowser/qutebrowser#6515] opened 2021-06-04 10:46 UTC
There is an extension for Brave(Chrome) calles [wasavi](https://chrome.google.com/webstore/detail/wasavi/dgogifpkoilgiofhhhodbodcfgomelhe) which enables vim mode in text-area. So, is it possible to emulate vim in any of the text areas inside this browser?

**Comment by The-Compiler** [comment] 2021-06-04 10:47
Duplicate of #827

**Closed by The-Compiler** 2021-06-04 10:47 UTC

**Comment by python-clojure** [comment] 2021-06-04 10:50
Oh sorry for that. Thanks anyway.
