### ISSUE TITLE
Can't pass cloudflare turnstile

### ISSUE THREAD

**Issue by Juliaria08** [qutebrowser/qutebrowser#7931] opened 2023-09-22 14:00 UTC
**Version info**: https://bpa.st/RRCQ

**Does the bug happen if you start with `--temp-basedir`?**: No

**Description**
Can't pass cloudflare turnstile captcha (hidden)

**How to reproduce**

https://kagi.com/fastgpt?query=What%27s+data%3F
Trying to press Answer is impossible, checking console reveals the website is reloading in the background.

**Comment by The-Compiler** [comment] 2023-09-22 16:00
Duplicate of #7208

**Closed by The-Compiler** 2023-09-22 16:00 UTC
