### ISSUE TITLE
When keyboard is not in english language browser is not accepting the commands

### ISSUE THREAD

**Issue by hgareeballa** [qutebrowser/qutebrowser#2407] opened 2017-03-06 17:22 UTC
qute version 0.10.0 - windows
if keyboard is not in Eng language browser is not accepting any commands, like closing page or going into insert mode .. etc
unless changing the keyboard to english again and then proceed ,

i assume this issue will be there if the keyboard is in any other langauage

**Comment by The-Compiler** [comment] 2017-03-06 17:29
Your assumption is wrong :wink: What keyboard layout are you using?

**Comment by hgareeballa** [comment] 2017-03-07 13:50
this layout ! :)
basically if am writing in arabic, and when i try any command like "d" or "Ctrl h" .. etc
will not work unless keyboard is in English lang.

![123123](https://cloud.githubusercontent.com/assets/6079147/23659076/64172646-035e-11e7-9d49-a64eabbe3951.png)

**Comment by The-Compiler** [comment] 2017-03-07 13:58
Can you please run `python3 -m scripts.keytester` in the qutebrowser repository, press your A key in arabic mode, and show what you get there?

**Comment by hgareeballa** [comment] 2017-03-08 05:14
can i do that from windows environment ! i did not install python3 !?

**Comment by The-Compiler** [comment] 2017-03-08 05:20
Oh, probably not.

Different plan: Quit qutebrowser, start a fresh instance of it, press `a` once in english/arabic mode (in normal mode, not in insert mode) and then do `:report`.

**Comment by hgareeballa** [comment] 2017-03-08 05:30
done,
for me to be able to do :report i have to switch back the keyboard to english from arabic and then the report popup appeared

for english there was no issues.

**Comment by The-Compiler** [comment] 2017-03-08 05:35
When pressing a:

```
9:31:59 DEBUG    modes      modeman:_eventFilter_keypress:167 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
09:31:59 DEBUG    commands   command:run:509 command called: clear-keychain
09:31:59 DEBUG    commands   command:run:524 Calling qutebrowser.keyinput.modeman.ModeManager.clear_keychain(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.normal: 1>>)
09:31:59 DEBUG    keyboard   basekeyparser:_debug_log:112 discarding keystring 'a'.
```

When pressing ش:

```
09:32:00 DEBUG    modes      modeman:_eventFilter_keypress:167 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
09:32:00 DEBUG    keyboard   basekeyparser:_debug_log:112 No special binding found for ش.
09:32:00 DEBUG    keyboard   basekeyparser:_debug_log:112 Got key: 0x634 / text: 'ش'
09:32:00 DEBUG    keyboard   basekeyparser:_debug_log:112 Giving up with 'ش', no matches
09:32:00 DEBUG    keyboard   basekeyparser:_debug_log:112 discarding keystring 'ش'.
```

So this seems to be a duplicate of #1207. I don't know yet if I can do anything about it, but you can edit your `keys.conf` (in `%LOCALAPPDATA%/qutebrowser` on Windows if I remember correctly) and add bindings for those keys manually.

**Closed by The-Compiler** 2017-03-08 05:35 UTC
