### ISSUE TITLE
When using editor text isn't inserted inside field

### ISSUE THREAD

**Issue by loustak** [qutebrowser/qutebrowser#5354] opened 2020-04-14 13:55 UTC
**Version info**:
https://paste.the-compiler.org/view/e94506d7

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
On google doc when using the system's editor (ctrl + e) it spawn gvim on my system. I enter text in vim then save and quit (`:wq`), but the text is not entered in the google doc document.

**How to reproduce**
Go to google doc. Create empty document. Click inside it to enter text, pass in insert mode, use ctrl+e to spawn your system editor (on my system gvim) and insert text then save and quit.
The text doesn't appear in the google document page.

**Comment by The-Compiler** [comment] 2020-04-14 15:20
Duplicate of #2215

**Closed by The-Compiler** 2020-04-14 15:20 UTC
