### ISSUE TITLE
Bookmark sort by date.

### ISSUE THREAD

**Issue by Flagrantior** [qutebrowser/qutebrowser#6554] opened 2021-06-17 07:47 UTC
Alphabetical sorting is not convenient when trying, for example, to find what you bookmarked yesterday.
Sorting by date would be much more logical. It could be switchable in **set:**.
Thanks.

**Comment by The-Compiler** [comment] 2021-06-17 07:50
Duplicate of #3688

**Closed** 2021-06-17 07:50 UTC
