### ISSUE TITLE
QtWebEngine recieves rogue tab keypresses

### ISSUE THREAD

**Issue by prosoitos** [qutebrowser/qutebrowser#4579] opened 2019-02-15 09:54 UTC
**Version info**:

qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.1
PyQt: 5.12

sip: 4.19.14
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.0.943 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.27.1
QtNetwork SSL: OpenSSL 1.1.1a  20 Nov 2018

Style: QFusionStyle
Platform: Linux-4.20.8-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

The position on a webpage is sometimes properly maintained and sometimes lost when jumping back and forth between a qutebrowser window and another window.

**Details**

I jump very often between windows of different applications using keybindings of my window manager (EXWM).

Sometimes the scroll position on a webpage is properly maintained when I jump back to it. Sometimes it is shifted. Quite often the page is scrolled back up to the top and I have to scroll back down to where I was.

I believe that this behaviour is quite recent (maybe a month or two?). I don't remember ever having this issue before.

**Comment by jgkamat** [comment] 2019-02-15 15:44
Can you reproduce in kde falkon as well?

On February 15, 2019 1:56:12 AM PST, Marie-Helene Burle <notifications@github.com> wrote:
>**Version info**:
>
>qutebrowser v1.5.2
>Git commit: 
>Backend: QtWebEngine (Chromium 69.0.3497.128)
>
>CPython: 3.7.2
>Qt: 5.12.1
>PyQt: 5.12
>
>sip: 4.19.14
>colorama: no
>pypeg2: 2.15
>jinja2: 2.10
>pygments: 2.3.1
>yaml: 3.13
>cssutils: no
>attr: 18.2.0
>PyQt5.QtWebEngineWidgets: yes
>PyQt5.QtWebKitWidgets: yes
>pdf.js: 2.0.943 (/usr/share/pdf.js/build/pdf.js)
>sqlite: 3.27.1
>QtNetwork SSL: OpenSSL 1.1.1a  20 Nov 2018
>
>Style: QFusionStyle
>Platform: Linux-4.20.8-arch1-1-ARCH-x86_64-with-arch, 64bit
>Linux distribution: Arch Linux (arch)
>Frozen: False
>Imported from /usr/lib/python3.7/site-packages/qutebrowser
>Using Python from /usr/bin/python3
>Qt library executable path: /usr/lib/qt/libexec, data path:
>/usr/share/qt
>
>**Does the bug happen if you start with `--temp-basedir`?**:
>
>Yes
>
>**Description**
>
>The position on a webpage is sometimes properly maintained and
>sometimes lost when jumping back and forth between a qutebrowser window
>and another window.
>
>**Details**
>
>I jump very often between windows of different applications using
>keybindings of my window manager (EXWM).
>
>Sometimes the scroll position on a webpage is properly maintained when
>I jump back to it. Sometimes it is shifted. Quite often the page is
>scrolled back up to the top and I have to scroll back down to where I
>was.
>
>I believe that this behaviour is quite recent (maybe a month or two?).
>I don't remember ever having this issue before.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/qutebrowser/qutebrowser/issues/4579

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by prosoitos** [comment] 2019-02-15 20:48
I don't know. I don't have falkon installed. If it is important, I guess I could install it.

**Comment by user202729** [comment] 2019-02-16 08:19
On which websites do this happen? All of them?

**Comment by The-Compiler** [comment] 2019-02-16 10:51
Would indeed be good if you could try to reproduce this with Falkon, so we know whether it's a QtWebEngine or a qutebrowser issue.

The size of the windows doesn't change when you do this, right? Not sure what's going on, I've never seen this FWIW.

**Comment by prosoitos** [comment] 2019-02-16 22:59
> On which websites do this happen? All of them?

Not sure if it happens on all sites as I never really paid attention to that. The behaviour is also very inconsistant (for instance, I can do this jumping back and forth 2 or 3 times in a row fine and on the 4th time it will jump back to the top. On other occasions, it jumps back to the top right from the first time I leave the qutebrowser window and go back to it).

I know for sure that it does it on the Arch Wiki, on the Emacs Wiki, and on the LaTeX Wikibook websites because I do a lot of jumping back and forth from those sites (reading things and implementing them in my files or cli). Can't remember for sure about other sites.

> The size of the windows doesn't change when you do this, right?

No, it does not. It's just that the scrolling position is lost. Most often I am back at the top, some other time I am still near-ish the area of the page where I previously was, but not the same place.

> Would indeed be good if you could try to reproduce this with Falkon, so we know whether it's a QtWebEngine or a qutebrowser issue.

Ok. Will do.

**Comment by prosoitos** [comment] 2019-02-16 23:01
Of note, in case it matters at all: I am using [EXWM](https://github.com/ch11ng/exwm) as my window manager. So that jumping back and forth I do is one of:

- jumping to another workspace, then coming back to the workspace in which qutebrowser is, or
- jumping to another window within the same workspace

And I do this with Emacs keybindings. The problem happens in both situation.

**Comment by prosoitos** [comment] 2019-02-16 23:15
Actually, you might have a point @user202729: I am trying to trigger the problem on various sites right now. I am failing to have it happen in this page, but it happens all the time on the Arch Wiki page. So it seems that it does depend on the page.

**Comment by prosoitos** [comment] 2019-02-16 23:29
Same thing happens in Falkon...

**Comment by prosoitos** [comment] 2019-02-17 07:39
As a way to go back to where I was in the page faster, I tried to use `set_mark` and `jump_mark` and they work quite poorly. `jump_mark` gets me kind of in the area of the mark, but it is very far from accurate. I had played with this a little when I first started using qutebrowser and I remember it as working much better.

Not sure whether there is any link with the current issue or whether I should open a new one.

**Comment by jgkamat** [comment] 2019-02-17 08:41
Marie-Helene Burle writes:

> Which is bad news for me I guess as you probably will not be able to do anything about it then. No? Should I close this issue and open an issue [on the qtwebengine GitHub](https://github.com/qt/qtwebengine)? _edit: seems that I can't open issues there._

qtwebengine isn't developed on github, you'll need to file a qtbug on their
issue tracker if you want to properly report an issue. You'll probably want to
provide a minimal test-case that dosen't involve exwm though.

**Comment by prosoitos** [comment] 2019-02-18 06:12
I don't know how to do this. I am perfectly ignorant with all things Qt related... I love qutebrowser, but its code is totally outside of my (very small) field of expertise.

If this is something that you can/want to do on your end, great. If not, I would be thankful to get a few tips and advice about how to tackle this.

Thank you!

**Comment by prosoitos** [comment] 2019-02-18 06:14
Mmmm... to do that, I would have to install another Window Manager... I am not sure I want to get into that.

I can run qutebrowser without launching EXWM, but then I cannot jump back and forth between windows, which is what cause the problem behaviour.

**Comment by prosoitos** [comment] 2019-02-19 01:21
No idea if this is of any interest, but the same thing happens on a page with a pdf (with pdfjs).

**Comment by codesections** [comment] 2019-02-20 14:26
I can add an additional data point here, in case it's helpful.

I am experiencing the same issue, and it appears that it might be triggered by qutebrowser believing it has received an extra `<TAB>` key press, which modifies the scroll position.  (Though other applications do not receive that key press when changing windows).

I can also add some info about the window manager.  I do *not* experience the issue when using dwm, but I do when using [stumpwm](https://github.com/stumpwm/stumpwm).  Stumpwm, like exwm, is built in Lisp—I note that as an interesting commonality, though I'm not sure how it could be related.

**Comment by codesections** [comment] 2019-02-20 19:23
One possible work-around is to use `set-mark` and `jump-mark` to return to the previous scroll position (which, depending on the WM, could probably be automated with each window jump).  I haven't been able to implement this work around, though, because I ran into #4013, which means that `set-mark` and `jump-mark` don't work properly for me.

**Comment by prosoitos** [comment] 2019-02-21 01:55
Thanks for your additional info! The Lisp thing is interesting...

I am also using a default zoom different from 100% and that explains my comments above in this thread about `set_mark` and `jump_mark` working poorly. I hadn't spotted #4013. Thank you for pointing it out to me. At least, now I know why this is, that it is not related to the current issue, and that an issue is already open.

I would very much love for this to be addressed as I do a lot of this jumping back and forth and this is a rather big issue for me. I am in the same boat re-posting an issue upstream. Keen to help with the process though.

**Comment by user202729** [comment] 2019-02-21 05:32
If that's the case, `bind <tab> :nop KP-FG` would temporarily solve the issue.

**Comment by prosoitos** [comment] 2019-02-21 08:35
> If that's the case, `bind <tab> :nop KP-FG` would temporarily solve the issue.

Would you mind giving a little explanation please? Thanks!

**Comment by codesections** [comment] 2019-02-21 12:01
> If that's the case, `bind <tab> :nop` would be a possible	workaround for the issue.

@user202729 that does solve it!  Thanks so much—I don't know why that didn't occur to me.

> Would you mind giving a little explanation please? Thanks!

The work-around is to re-bind the `<tab>` to do nothing (instead of sending a `<tab>` to the webpage).  To do this, you can enter `:bind <tab> nop` in qutebrowser's command mode.  ("nop" stands for "no operation", that is, do nothing.)

Equivalently, you can add the following to your `.config/qutebrowser/config.py` file:

```py
c.bindings.commands = {
        'normal': {
            '<tab>': 'nop',
            }
        }
```
(If you have other bindings set in your `config.py` file, you'd need to merge this in with that config dict)

**Comment by prosoitos** [comment] 2019-02-22 01:04
Should I understand that you are switching windows with Alt+Tab as is the case on Windows? I am still confuse.

To unbind a key, one can also do

```py
config.unbind('<tab>', mode='normal')
```
But I still don't get the point (unless you use Alt+Tab to switch windows).

In my case, my jumping back and forth occurs with various keybindings set through EXWM and none of them involve Tab.

**Comment by codesections** [comment] 2019-02-22 01:19
> Should I understand that you are switching windows with Alt+Tab as is the case on Windows? I am still confused.

No, I am not pressing tab at all to switch windows.  

I am switching with `<C-SPC> + a`, actually, but the actual keys aren't important.

What I am saying is
> it appears that [the bug] might be triggered by qutebrowser believing it has received an extra `<TAB>` key press, which modifies the scroll position. (Though other applications do not receive that key press when changing windows).

That is, for *some* reason, qutebrowser/qtwebengine is acting as though it received a `<tab>` press, even though we never sent one.  Based on thinking it got a tab press, it is changing the scroll position of the page (just as it would if we actually pressed `<tab>`).  Thus, the temporary work-around is to rebind `<tab>` to `nop`.  That way, qutebrowser still (incorrectly) gets an extra `<tab>`, but that doesn't change the scroll position at all.

**Comment by prosoitos** [comment] 2019-02-22 01:35
Oh, I see. Thank you! I had missed that comment of yours and was totally confused.

I will certainly try this!!

**Comment by prosoitos** [comment] 2019-02-22 01:50
Out of curiosity @codesections, you don't happen to have any issues on Twitter (if you use that site)? #4108 is closed but I still have the problem. I wonder now whether it could be some other keys being sent when they shouldn't and if it isn't a similar sort of problem...

**Comment by codesections** [comment] 2019-02-22 02:43
I don't use Twitter, and haven't encountered any issue like that on Mastodon (the Twitter-like site that I do use).  Sounds pretty odd!

**Comment by prosoitos** [comment] 2019-02-22 03:48
Closing this as the workaround works (even if it is still unclear what is really going on). It also solved #4600 and #4108.

**Comment by prosoitos** [comment] 2019-02-22 03:50
> Sounds pretty odd!

Yes, it was totally crazy. But the workaround for this issue actually solved that too (even if the behaviour was very different than what TAB would do, which is quite puzzling).

**Comment by The-Compiler** [comment] 2019-02-22 05:46
Reopening this for now - even if it's a QtWebEngine bug, I'd like to find out what's going on, or at least find some more straightforward way to reproduce it in order to send it upstream.

**Comment by user202729** [comment] 2019-02-22 14:51
Does the bug happen for other applications other than QtWebEngine?  (in that case, it's a EXWM bug)

**Comment by jgkamat** [comment] 2019-02-22 17:20
Also, does anyone have a debug log of these tab presses being sent to us? I
don't think anyone linked that yet.

You could also try the keytester script in the repo as well.

**Comment by codesections** [comment] 2019-02-22 18:35
> Does the bug happen for applications other than QtWebEngine? (in that case, it's a EXWM bug)

Previous testing showed that the bug occurs with three QtWebEngine browsers (qutebrowser, webmacs, and falcon) and no other apps.  It also doesn't happen in qutebrowser if it's run with the `--backend webkit` flag.  So it sure looks like QtWebEngine is involved!  (And, anyway, it can't be a purely EXWM bug, since I ran into it using stumpwm.)

> Also, does anyone have a debug log of these tab presses being sent to us? I don't think anyone linked that yet.

Here's an excerpt of the log.  Is there a more readable way to get you the full log?

```

13:25:55 DEBUG    keyboard   basekeyparser:_debug_log:91 Got key: 0x1000024 / modifiers: 0x0 / text: '<CapsLock>' / dry_run False
13:25:55 DEBUG    keyboard   basekeyparser:_debug_log:91 Trying match without modifiers
13:25:55 DEBUG    keyboard   basekeyparser:_debug_log:91 Trying match with key_mappings
13:25:55 DEBUG    keyboard   basekeyparser:_debug_log:91 Giving up with '<CapsLock>', no matches
13:25:55 DEBUG    keyboard   basekeyparser:_debug_log:91 Clearing keystring (was: <CapsLock>).
13:25:55 DEBUG    modes      modeman:_handle_keypress:199 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: False --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7efc34c13288>)
13:25:56 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None
13:25:59 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7efc34c13288>
13:25:59 DEBUG    modes      modeman:_handle_keyrelease:219 filter: True
13:26:01 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None
13:26:02 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7efc34c13288>
13:26:02 DEBUG    modes      modeman:_handle_keypress:172 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
13:26:02 DEBUG    keyboard   basekeyparser:_debug_log:91 Got key: 0x1000001 / modifiers: 0x0 / text: '<Tab>' / dry_run False
13:26:02 DEBUG    keyboard   basekeyparser:_debug_log:91 Definitive match for '<Tab>'.
13:26:02 DEBUG    keyboard   basekeyparser:_debug_log:91 Clearing keystring (was: <Tab>).
13:26:02 DEBUG    commands   command:run:491 command called: nop
13:26:02 DEBUG    commands   command:run:506 Calling qutebrowser.misc.utilcmds.nop()
13:26:02 DEBUG    modes      modeman:_handle_keypress:199 match: 2, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: False --> filter: True (focused: <PyQt5.QtWidgets.QWidget object at 0x7efc34c13288>)
13:26:02 DEBUG    modes      modeman:_handle_keyrelease:219 filter: True
13:26:02 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None
13:26:05 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7efc34c13288>
13:26:05 DEBUG    modes      modeman:_handle_keyrelease:219 filter: True
13:26:05 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None
13:26:11 DEBUG    destroy    crashsignal:handle_signal_wakeup:346 Handling signal wakeup!
13:26:11 INFO     destroy    app:qt_mainloop:153 SIGINT/SIGTERM received, shutting down!
```

**Comment by prosoitos** [comment] 2019-02-22 21:35
> Previous testing showed that the bug occurs with three QtWebEngine browsers (qutebrowser, webmacs, and falcon) and no other apps. It also doesn't happen in qutebrowser if it's run with the `--backend webkit` flag. So it sure looks like QtWebEngine is involved! (And, anyway, it can't be a purely EXWM bug, since I ran into it using stumpwm.)

I can totally confirm this: I have never had the issue with any other app but qutebrowser and Falkon.

**Comment by prosoitos** [comment] 2019-02-22 21:39
Of note, in case it helps somewhat to pinpoint the QtWebEngine bug, this was not happening until some weeks ago. Unfortunately, I don't remember when it started. Maybe @codesections will have a better memory?

**Comment by prosoitos** [comment] 2019-02-22 21:48
> or at least find some more straightforward way to reproduce it in order to send it upstream

You might have to learn some Lisp :laughing: At least, you have the option: Emacs Lisp or Common Lisp :laughing:

**Comment by codesections** [comment] 2019-02-22 21:56
> I don't remember when it started. Maybe @codesections will have a better memory?

Can't help you there.  I encountered it for the first time when I switched to stumpwm from dwm, which was after you had opened this issue

**Comment by The-Compiler** [comment] 2019-03-08 09:21
Hah, I'm actually seeing fake Tab keypresses as well, when reproducing #4632.

**Comment by tollerm** [comment] 2019-03-13 18:03
It seems that I have exactly the same problem. I've remapped <End> key to <Hyper-L> key, which I use to switch windows. When I press <Hyper-L> key, the web page is scrolled down, that is very annoying. It started to happen one or two weeks ago, cannot remember exactly. The same thing occurs when I use Chromium, while Firefox respects my key mapping. BTW I use Qtile as a window manager.

**Comment by tollerm** [comment] 2019-03-13 18:11
Sorry, wrong formatting. It should be

It seems that I have exactly the same problem. I've remapped \<Hyper-L\> key to  \<Home\> key, which I use to switch windows. When I press \<Home\> key, the web page is scrolled down, that is very annoying. It started to happen one or two weeks ago, cannot remember exactly. The same thing occurs when I use Chromium, while Firefox respects my key mapping. BTW I use Qtile as a window manager.

**Comment by The-Compiler** [comment] 2019-03-15 07:25
@tollerm That sounds more like a (potentially different) Chromium bug.

**Comment by prosoitos** [comment] 2019-04-02 14:48
The problem came back for me (while I still have `<tab>` bound to `nop`).

**Comment by PluMGMK** [comment] 2019-04-30 21:03
I use Sway and I've been getting this whenever I switch tabs in qutebrowser, or even run a command or a search. It's been happening ever since I switched to WebEngine, but for some reason I didn't think to mention it until now. The workaround presented here doesn't work.

**Comment by prosoitos** [comment] 2019-05-02 08:54
That workaround doesn't work for me anymore.

**Comment by toofar** [comment] 2019-06-22 00:41
Maybe this is this bug? [Tab key is sent to WebEngine view every time the window is minimized
](https://bugreports.qt.io/browse/QTBUG-76268 )

**Comment by The-Compiler** [comment] 2019-06-23 11:07
@toofar Good catch, I missed that one!

Looks like it's fixed for Qt 5.12.5 here: [Do not forward key-events on QQuickItem level (I067f8f94) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine/+/265154)

Looks like it won't be in 5.13.0, but probably in 5.13.1.

**Comment by jpalus** [comment] 2019-06-26 12:24
Odd I see same issue with 5.13.0 (#4869) but not with 5.12.3. I've tried to port QTBUG-76268 to my custom build of QtWebEngine but that did not fix anything. I start to wonder whether the culprit is indeed there. After downgrading QtWebEngine to 5.12.3 but keeping rest of Qt5 with version 5.13.0 I still see the issue. After downgrading all of it to 5.12.3 issue is gone.

**Comment by brianbuccola** [comment] 2019-07-06 12:54
This issue started happening to me recently (within the last week or two, I'd say). The workaround mentioned above (`bind <tab> nop`) works. I'm running QtWebEngine version 5.13.0.

**Comment by prosoitos** [comment] 2019-07-07 20:48
> That workaround doesn't work for me anymore.

I was wrong there. What was not working anymore with the way I had written the workaround (using `c.bindings.commands`), but it works fine using `config.bind`.

**Comment by dschrempf** [comment] 2019-07-17 05:53
I am also experiencing this issue for around two weeks now. On some webpages like Wikipedia it happens every time (it jumps to the top). On other webpages, it depends on which element is focussed. Unbinding the tab key works also for me.

**Comment by brianbuccola** [comment] 2019-07-18 20:51
Another quick follow-up: the issue occurs not only in normal mode, but also in other modes, namely insert, hint, passthrough, caret, and register modes. It doesn't happen in command mode (for some reason); I haven't checked prompt or yesno modes.

As with normal mode, binding `<tab>` to `nop` solves the issue:

```
bind --mode insert <tab> nop
bind --mode hint <tab> nop
bind --mode passthrough <tab> nop
bind --mode caret <tab> nop
bind --mode register <tab> nop
```

**Comment by amenl** [comment] 2019-10-09 07:39
Here is another finding to that issue.
The tab problem doesn't occur when I open a link/quickmark in a new tab (this was known). But it also doesn't occur when I open the same link in the same tab, whereas if it's a different link, the tab gets sent (which in my case results in tab-next, kind of annoying).

**Comment by The-Compiler** [comment] 2019-10-09 08:08
Can people who still see this mention on which Qt versions you are? I still suspect this is due to [QTBUG-76268](https://bugreports.qt.io/browse/QTBUG-76268) which means it should be fixed in Qt 5.12.5, 5.13.1 and 5.14.

**Comment by amenl** [comment] 2019-10-09 08:29
Most qt5 packages I see show version 5.13.1-1 (arch linux), upgraded some days ago. the problem persists.

**Comment by arza-zara** [comment] 2019-10-09 12:09
On archlinux with openbox, upgrading qt5-webengine 5.13.0-4 -> 5.13.1-1 fixes it for me.

**Comment by dschrempf** [comment] 2019-10-09 13:17
I am also on archlinux, the problem seems to be gone! Version 5.13.1-3.

**Comment by amenl** [comment] 2019-10-11 08:00
What's interesting...

I keep 3 machines (all Arch Linux) in sync (config + most packages). All 3 are up to date and show the same erroneous bahaviour. 

The only changes that work are following:
- uncommenting tab key binding
    # config.bind('<Tab>', 'tab-next')
- setting webkit backend
    config.set('backend', 'webkit')

So I encourage everyone to bind Tab to tab-next and check the result.

**Comment by PluMGMK** [comment] 2019-10-26 12:29
Guys, this is kind of embarrassing, but I figured out what's causing it in my case, and it was kind of obvious. I have had "statusbar.hide" on for years now, and disabling it got rid of this problem.
Seems that the act of hiding the statusbar, when a command is finished, automatically sends a tab to WebEngine…

**Comment by The-Compiler** [comment] 2019-10-26 12:52
@PluMGMK You might be seeing #2236.

**Comment by amenl** [comment] 2019-10-26 16:49
@PluMGMK Makes no difference for me. Still same ol'..

**Comment by PluMGMK** [comment] 2019-10-26 17:52
Yeah, looks like I've been following the wrong issue all along. One would like to think they're related though…

**Comment by The-Compiler** [comment] 2020-04-08 12:13
From Reddit, this apparently seems to (differently) affect newer Qt versions as well:

https://www.reddit.com/r/qutebrowser/comments/fkohq7/return_triggers_tabnext_after_keybind_to_tab/

**Comment by adigitoleo** [comment] 2020-09-25 13:19
Hi,

So I just switched from i3 to bspwm and am now experiencing this as well. It wasn't happening on i3 (i3-gaps). I think it's only happening in normal mode.  Happens when showing the previously hidden qutebrowser window in any way (mod+<n>, rofi, etc.). I have <tab> bound to tab-next so it's a bit disorienting.

<details>
<summary>My qutebrowser info</summary>

```
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.8.5
PyQt: 5.15.1

sip: 5.4.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.1
yaml: 5.3.1
cssutils: no
attr: 20.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.1
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1h  22 Sep 2020

Style: Kvantum::Style
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.1.8
Platform: Linux-5.8.10-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/leon/.cache/qutebrowser
config: /home/leon/.config/qutebrowser
data: /home/leon/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/leon/.config/qutebrowser/config.py has been loaded
Uptime: 0:14:52
```
</details>

**Comment by toofar** [comment] 2023-03-17 08:41
I think we can remove these with a patch like this:

```patch
diff --git i/qutebrowser/keyinput/eventfilter.py w/qutebrowser/keyinput/eventfilter.py
index 31ffcc7f9b34..30737090d19f 100644
--- i/qutebrowser/keyinput/eventfilter.py
+++ w/qutebrowser/keyinput/eventfilter.py
@@ -85,12 +85,17 @@ class EventFilter(QObject):
 
         Return:
             True if the event should be filtered, False if it's passed through.
         """
         if not isinstance(obj, QWindow):
             # We already handled this same event at some point earlier, so
             # we're not interested in it anymore.
             return False
 
+        if not obj.isVisible() and obj.objectName() == 'QQuickWidgetOffscreenWindow':
+            print(f"Ignoring event from QtQuick offscreen window {event.type()=}")
+            return False
+
         typ = event.type()
 
         if typ not in self._handlers:
```

Because the KeyEvents (which are the only ones we are handling here) are [being sent](https://code.qt.io/cgit/qt/qtdeclarative.git/tree/src/quickwidgets/qquickwidget.cpp?h=dev#n1420) to the offscreen window. We probably don't need to be handling key events to that? We are only getting them because we have a [global event filter](https://github.com/qutebrowser/qutebrowser/issues/5376https://github.com/qutebrowser/qutebrowser/issues/5376).

I'm not sure if we should be returning False here or just not calling out to our handlers.

**Comment by The-Compiler** [comment] 2023-12-06 14:43
I think this was fixed in Qt at some point. Can't reproduce anymore even with Qt 5: `python3 -m qutebrowser -s qt.chromium.sandboxing disable-all --qt-wrapper PyQt5 --temp-basedir  ':bind <Tab> message-info foo'`

**Closed by The-Compiler** 2023-12-06 14:43 UTC
Labels: component: keyinput, priority: 0 - high, component: QtWebEngine, bug: behavior
