### ISSUE TITLE
Command variable for page title

### ISSUE THREAD

**Issue by Ape** [qutebrowser/qutebrowser#3240] opened 2017-11-04 07:21 UTC
I would like to bind a key for adding a bookmark, but so that I can edit the url and title before saving the bookmark. This could be done with something like this:

```
:bind M set-cmd-text :bookmark-add {url:pretty} {title}
```

However, AFAIK there is no command variable `{title}` for the current page title. For my use case I'd like it to be equivalent to just running `:bookmark-add` with default parameters.

**Comment by The-Compiler** [comment] 2017-11-04 13:25
Duplicate of #901

**Closed by The-Compiler** 2017-11-04 13:25 UTC
