### ISSUE TITLE
Jumps to page top when downloading something

### ISSUE THREAD

**Issue by mharig** [qutebrowser/qutebrowser#7911] opened 2023-09-13 22:04 UTC
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.11.5
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0.1
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: no
sqlite: 3.43.0
QtNetwork SSL: OpenSSL 3.1.2 1 Aug 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 2.1 Mesa 23.1.6-arch1.4
Platform: Linux-6.4.12-arch1-1-x86_64-with-glibc2.38, 64bit
Linux distribution: EndeavourOS (arch)

**Does the bug happen if you start with `--temp-basedir`?**:
Not tested.

**Description**

When downloading something, e.g. an Image, after hitting Return to confirm the filename, the page jumps to the top. That is very annoying when there are other things on the page further down to download.

**How to reproduce**

Happens on all sites I tested, with all content types I tested.

**Comment by The-Compiler** [comment] 2023-09-13 22:50
Duplicate of #7885

**Closed by The-Compiler** 2023-09-13 22:50 UTC
