### ISSUE TITLE
Crashes on :download if errors preparing download directory

### ISSUE THREAD

**Issue by toofar** [qutebrowser/qutebrowser#3818] opened 2018-04-05 08:18 UTC
There are two issue here, both relating to unhandled exceptions thrown when trying to prepare the download location.

1. If the configured download directory doesn't exist the config system throws a validation exception and the download code never gets the chance to try to create the directory.
2. If there is no configured directory but the standard (default) directory doesn't exist and the `os.makedirs()` fails (eg due to permissions errors) that'll also crash the browser.

The download code (or maybe even the command runner code) needs to catch errors somewhere and cancel the download, rather than cancelling the browsing session.

Configured directory doesn't exist
==========================

If `config.val.downloads.location.directory` is set to a directory that doesn't exist I get the stack trace below when trying to download. I don't think crashing is the right thing to do here, especially since `download_dir()` handles the directory not being present by calling `os.makedirs()`. I suspect those validation errors are meant for `config.py`.

```
  File "/home/user/projects/qutebrowser/qutebrowser/commands/runners.py", line 325, in run_safely
    self.run(text, count)
  File "/home/user/projects/qutebrowser/qutebrowser/commands/runners.py", line 304, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/user/projects/qutebrowser/qutebrowser/commands/command.py", line 502, in run
    self.handler(*posargs, **kwargs)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/commands.py", line 1520, in download
    suggested_fn=suggested_fn
  File "/home/user/projects/qutebrowser/qutebrowser/browser/qtnetworkdownloads.py", line 408, in get
    return self.get_request(req, **kwargs)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/qtnetworkdownloads.py", line 476, in get_request
    **kwargs)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/qtnetworkdownloads.py", line 492, in _fetch_request
    return self.fetch(reply, **kwargs)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/qtnetworkdownloads.py", line 534, in fetch
    parent=self)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/downloads.py", line 172, in get_filename_question
    q.default = _path_suggestion(suggested_filename)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/downloads.py", line 118, in _path_suggestion
    return os.path.join(download_dir(), '')
  File "/home/user/projects/qutebrowser/qutebrowser/browser/downloads.py", line 72, in download_dir
    directory = config.val.downloads.location.directory
  File "/home/user/projects/qutebrowser/qutebrowser/config/config.py", line 525, in __getattr__
    return self._config.get(name)
  File "/home/user/projects/qutebrowser/qutebrowser/config/config.py", line 317, in get
    return opt.typ.to_py(obj)
  File "/home/user/projects/qutebrowser/qutebrowser/config/configtypes.py", line 1292, in to_py
    value, "must be a valid directory!")
qutebrowser.config.configexc.ValidationError: Invalid value '/tmp/hi/' - must be a valid directory!
```

Permissions error from `os.makedirs`
============================

This was reported on IRC and lead me to find the above issue.

> 07:33 < hdqn> apparently I have some download dir hard-coded: PermissionError: 
>                         [Errno 13] Permission denied: '/home/rogue/local'

That was presumably due to the Qt standard paths thing picking up on a user dir that didn't exist for whatever reason and failing to create a directory under `/home/`. Here is a stack trace by using an existing test basedir, removing the download directory and then setting the basedir root to be owned by `root:root`.

```
  File "/home/user/projects/qutebrowser/qutebrowser/commands/runners.py", line 325, in run_safely
    self.run(text, count)
  File "/home/user/projects/qutebrowser/qutebrowser/commands/runners.py", line 304, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/user/projects/qutebrowser/qutebrowser/commands/command.py", line 502, in run
    self.handler(*posargs, **kwargs)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/commands.py", line 1520, in download
    suggested_fn=suggested_fn
  File "/home/user/projects/qutebrowser/qutebrowser/browser/qtnetworkdownloads.py", line 408, in get
    return self.get_request(req, **kwargs)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/qtnetworkdownloads.py", line 476, in get_request
    **kwargs)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/qtnetworkdownloads.py", line 492, in _fetch_request
    return self.fetch(reply, **kwargs)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/qtnetworkdownloads.py", line 534, in fetch
    parent=self)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/downloads.py", line 172, in get_filename_question
    q.default = _path_suggestion(suggested_filename)
  File "/home/user/projects/qutebrowser/qutebrowser/browser/downloads.py", line 118, in _path_suggestion
    return os.path.join(download_dir(), '')
  File "/home/user/projects/qutebrowser/qutebrowser/browser/downloads.py", line 83, in download_dir
    os.makedirs(ddir)
  File "/home/user/projects/qutebrowser/.venv/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/qute-basdir-webchannel/download'
```

**Comment by The-Compiler** [comment] 2018-04-08 18:11
Duplicate of #2570

**Closed by The-Compiler** 2018-04-08 18:11 UTC
Labels: bug: behavior, component: downloads

**Comment by toofar** [comment] 2018-05-16 08:35
I know this has been a while but I was discussing a related thing on irc. I think the first example is different from the one in 2570, it isn't due to an error creating a directory, it is due to the config system handling any unexpected values by throwing an excepting and the calling code not handling that. Those errors are presumable meant to notify the user that they have made an error in their config at init time, but they are thrown on paths that are used after init time too.
