### ISSUE TITLE
Download does not send domain cookies

### ISSUE THREAD

**Issue by jpalus** [qutebrowser/qutebrowser#5246] opened 2020-02-19 16:16 UTC
Consider following scenario that surprisingly works differently depending on what way of downloading is used:
1. Go to a web page that requires authentication (JIRA instance in my case)
2. Go to ticket with downloadable attachments
3. "Click" on attachment to download with "f" and hint
4. Or download attachment by using ";d" and hint

Expected: Steps 3. and 4. should result in exactly the same downloaded file
Actual: Step 3. downloads correct file, while Step 4. results in HTML payload about unauthenticated user

The problem is especially annoying when attachment is a text file since qutebrowser shows it inside browser instead of triggering download. Both ";d" + hint, as well as "gd" within open document result in HTML file about missing authentication.

So I guess step 3. is handled by WebEngine itself and sends correct cookies, while most likely rest of cases are handled by qutebrowser itself which does not.

**Comment by The-Compiler** [comment] 2020-02-19 16:28
Duplicate of #2328

**Closed by The-Compiler** 2020-02-19 16:28 UTC
