### ISSUE TITLE
Renderer process crashed

### ISSUE THREAD

**Issue by Mugworth** [qutebrowser/qutebrowser#7705] opened 2023-05-20 10:11 UTC
Pretty much just after the fresh installation, everything worked almost just fine, but after i opened the qutebrowser with -B /path/to/config -C /path/to/config/config.py, I now cant open any sites due to Renderer process crashed, cant even open the :version page

**Does the bug happen if you start with `--temp-basedir`?**:
$HOME/git/qutebrowser/.venv/bin/python3 -m qutebrowser --temp-basedir reproduces this bug

```
~/git/qutebrowser/.venv/bin/python3 -m qutebrowser --temp-basedir
12:11:41 ERROR: Renderer process crashed (status 159)
12:11:41 ERROR: Renderer process crashed (status 159)
12:11:42 ERROR: Renderer process crashed (status 159)
12:11:42 ERROR: Renderer process crashed (status 159)
12:11:46 ERROR: Renderer process crashed (status 159)
12:11:46 ERROR: Renderer process crashed (status 159)
12:11:46 ERROR: Renderer process crashed (status 159)
12:11:47 ERROR: Renderer process crashed (status 159)
```
Here is version log
```

         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v2.5.4
Git commit: 04c64b743 on master (2023-05-15 10:08:29 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

CPython: 3.10.6
PyQt: 5.15.9

sip: 6.7.9
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 3.0.2 15 Mar 2022

Style: QFusionStyle
Platform plugin: xcb
OpenGL: AMD, 4.6 (Compatibility Profile) Mesa 22.3.0-devel
Platform: Linux-5.15.0-72-generic-x86_64-with-glibc2.35, 64bit
Linux distribution: Linux Mint 21 (linuxmint)
Frozen: False
Imported from /home/kuba/git/qutebrowser/qutebrowser
Using Python from /home/kuba/git/qutebrowser/.venv/bin/python3
Qt library executable path: /home/kuba/git/qutebrowser/.venv/lib/python3.10/site-packages/PyQt5/Qt5/libexec, data path: /home/kuba/git/qutebrowser/.venv/lib/python3.10/site-packages/PyQt5/Qt5

Paths:
cache: /home/kuba/.cache/qutebrowser
config: /home/kuba/.config/qutebrowser
data: /home/kuba/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00
```

**Comment by toofar** [comment] 2023-05-20 10:19
Assuming this is a duplicate of https://github.com/qutebrowser/qutebrowser/issues/7353

Run with a newer Qt version or launch with `-s qt.chromium.sandboxing disable-seccomp-bpf`.

**Closed by toofar** 2023-05-20 10:19 UTC
