### ISSUE TITLE
Per window status bar setting

### ISSUE THREAD

**Issue by quantum-booty** [qutebrowser/qutebrowser#5743] opened 2020-09-25 10:05 UTC
I would like to run jupyterlab on qutebrowser with passthrough mode, however I can't disable the statusbar on jupyterlab without also disabling it on the other qutebrowser windows. Is it possible to have per window status bar settings? If not possible, it would be nice to have a fourth mode, aside from always, never, in-mode:
Don't show status bar in passthrough mode.

Thank you!

**Comment by mschilli87** [comment] 2020-09-25 11:28
You should be able to run a separate instance of qutebrowser (different `--basedir`) I think (not tested).

**Comment by quantum-booty** [comment] 2020-09-25 11:31
@mschilli87 Thank you for your reply. However I am using a slow laptop with less than ideal amount of memories. It would be nice to run them on a single instance.

**Comment by The-Compiler** [comment] 2020-09-28 17:36
Duplicate of #2314

**Closed by The-Compiler** 2020-09-28 17:36 UTC
