### ISSUE TITLE
Incomplete mesa fix

### ISSUE THREAD

**Issue by martynjy** [qutebrowser/qutebrowser#5462] opened 2020-05-24 19:12 UTC
Probably related to #5461.

When opening a session the tabs load in the backgound and many tabs will open until a random tab
will crash the browser.

Seems maybe related to 'QtWebEngine' as when I use the 'QtWebKit' backend the problem disappears.

Also, sometimes whilst browsing and opening a website in a new tab it will also crash.

Arch Linux 
qutebrowser 1.11.1-1
qt5-webengine 5.14.2-3
python-pyqtwebengine 5.14.0-4

**Comment by The-Compiler** [comment] 2020-05-24 19:15
Does the crash go away if you start with `--temp-basedir` and then load the session with the full path to `~/.local/share/qutebrowser/sessions/....yml` passed to `:session-load`?

**Comment by martynjy** [comment] 2020-05-25 21:21
No. Still crashes.

Probably useless, but this is an example of what I get when I open the tab that crashes the browser, which is random.

rt_sigprocmask(SIG_BLOCK,` ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 9378
gettid()                                = 9378
tgkill(9378, 9378, SIGSEGV)             = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_TKILL, si_pid=9378, si_uid=1000} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core `dumped)

**Comment by The-Compiler** [comment] 2020-05-25 21:30
Can you share that session file then (and maybe find out what part of it makes things crash)?

**Comment by martynjy** [comment] 2020-05-25 21:42
It was an strace.

**Comment by The-Compiler** [comment] 2020-05-25 21:43
You said "when opening a session" in the issue description...

**Comment by martynjy** [comment] 2020-05-25 21:44
Sorry misunderstood.

**Comment by martynjy** [comment] 2020-05-25 21:51
Do you mean a qutebrowser yml session file?

**Comment by The-Compiler** [comment] 2020-05-25 21:51
Yep!

**Comment by martynjy** [comment] 2020-05-25 21:54
It won't accept yml. Renamed.
[default.yml.txt](https://github.com/qutebrowser/qutebrowser/files/4678957/default.yml.txt)

**Comment by The-Compiler** [comment] 2020-05-26 09:01
So if you run this:

```
qutebrowser --debug --temp-basedir  ":session-load $PWD/default.yml.txt"
```

with that file in the current working directory, you get a crash as well? Can you show the last few lines of the logs before the crash, and also the output of `coredumpctl info` directly after the crash?

**Comment by martynjy** [comment] 2020-05-26 12:04
Last few lines of '--debug':

12:41:37 DEBUG    sessions   sessions:save:317 Saving session _autosave to /tmp/qutebrowser-basedir-96n5pyuc/data/sessions/_autosave.yml...
12:41:37 DEBUG    signals    signalfilter:_filter_signals:92 ignoring: cur_load_finished(True) (tab 14)
12:41:39 DEBUG    misc       app:on_focus_object_changed:495 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7faa7c3c7dc0>
12:41:40 DEBUG    modes      modeman:_handle_keyrelease:293 filter: True
12:41:54 DEBUG    webview    browsertab:_on_navigation_request:993 navigation request: url https://platform.twitter.com/widgets/tweet_button.2a008290075125adde2d7b849b06a0bb.en.html#dnt=true…, type Type.redirect, is_main_frame False
12:41:54 DEBUG    webview    browsertab:_on_navigation_request:993 navigation request: url https://platform.twitter.com/widgets/tweet_button.2a008290075125adde2d7b849b06a0bb.en.html#dnt=true…, type Type.redirect, is_main_frame False
12:41:54 DEBUG    webview    browsertab:_on_navigation_request:993 navigation request: url https://platform.twitter.com/widgets/tweet_button.2a008290075125adde2d7b849b06a0bb.en.html#dnt=true…, type Type.redirect, is_main_frame False
Segmentation fault (core dumped)

coredump:
[coredump.txt](https://github.com/qutebrowser/qutebrowser/files/4682019/coredump.txt)

**Comment by The-Compiler** [comment] 2020-05-26 12:05
What's the version of your `mesa` package?

**Comment by martynjy** [comment] 2020-05-26 12:10
mesa 20.0.7-3

**Comment by The-Compiler** [comment] 2020-05-26 12:18
Can you try downgrading to [20.0.7-2](https://archive.archlinux.org/packages/m/mesa/mesa-20.0.7-2-x86_64.pkg.tar.zst) and see if that changes anything? Might be a good idea to reboot after the downgrade - and please only do this if you're able to upgrade again even if your graphical environment isn't working anymore (this shouldn't happen, but just in case).

**Comment by martynjy** [comment] 2020-05-26 12:24
Ok, i'll downgrade.
I noticed as well, it is saving a '_autosave.yml' file even thought set to 'false'.

**Comment by The-Compiler** [comment] 2020-05-26 12:27
`_autosave.yml` is always saved for crash recovery (and only restored in case of a crash)

**Comment by martynjy** [comment] 2020-05-26 12:39
Well Done.  That SEEMS to have fixed it.

**Comment by The-Compiler** [comment] 2020-05-26 12:41
This is this bug then: https://bugs.archlinux.org/task/66666

Seems like the upstream mesa fix which they introduced in -3 is incomplete then...

**Comment by martynjy** [comment] 2020-05-26 12:43
Thank you very much.  I will ignore 'mesa' until the next release.

**Comment by sentriz** [comment] 2020-05-27 16:06
hey I'm experiencing this on mesa `20.0.6-2` should I maybe try "update" to `20.0.7-2`?

**Comment by The-Compiler** [comment] 2020-05-27 16:13
@sentriz Maybe you're not seeing this issue either than, that was just a guess in #5279. Could you please show the output of `coredumpctl info` right after the crash?

**Comment by The-Compiler** [comment] 2020-05-27 16:14
@martynjy Unfortunately I still can't reproduce this, even after upgrading to mesa 20.0.7-3 - but maybe it depends on the used graphic drivers. Could you please find out which URL of those in the session is causing it by e.g. loading them one-by-one?

- https://www.google.com/search?hl=en&biw=1682&bih=909&ei=glaQXpPQMvLlxgPX8reQBA&q=Cumin+Coriander+Fennel+Tea&oq=Cumin+Coriander+Fennel+Tea&gs_lcp=CgZwc3ktYWIQAzICCAAyAggAMgIIADICCAAyBAgAEB4yBggAEAgQHjIGCAAQCBAeMgYIABAIEB4yBQgAEM0CMgUIABDNAjoECAAQRzoECAAQDToGCAAQDRAeOggIABAIEA0QHkoJCBcSBTEyLTYzSggIGBIEMTItNFD8aFiPbmD1cGgAcAJ4AIABSIgBjQGSAQEymAEAoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwiTmbfg3t3oAhXysnEKHVf5DUIQ4dUDCAw&uact=5
- https://www.medicalmedium.com/blog/ashwagandha
- https://www.herbfacts.co.uk/lemon-balm/
- https://www.winchesterhospital.org/health-library/article?id=21487
- https://www.google.com/search?hl=en&q=passion%20flower%20and%20lemon%20balm
- http://store.newwayherbs.com/acne-and-skin-disorderscombination-liquid-formula-1003-p334.aspx
- https://glacierpeakholistics.com/pages/herbal-uses-through-history
- https://sites.google.com/site/kruidwis/planten-van-a-tot-z/verbena-officinalis-ijzerhard?tmpl=%2Fsystem%2Fapp%2Ftemplates%2Fprint%2F&showPrintDialog=1
- https://www.healthline.com/health/foot-cramps-at-night#takeaway
- https://goodnights.rest/bed-botany-and-beyond/5-single-plant-sleep-remedies/
- https://www.medicalnewstoday.com/articles/322455#home-remedies
- http://cms.herbalgram.org/expandedE/YeastBrewer27s.html
- https://www.justingredients.co.uk/horse-chestnut-seeds.html
- https://www.justingredients.co.uk/meliot-lemon-sweet-clover.html
- https://www.justingredients.co.uk/yeast-powder.html
- http://cms.herbalgram.org/commissione/Monographs/Monograph0367.html?ts=1590438003&signature=d044754049db3c99efe4f1d7844ae52c
- https://www.realnatural.org/brewers-yeast-medicinal-benefits/#Brewers_yeast_improves_sleep

**Comment by sentriz** [comment] 2020-05-27 16:18
> @sentriz Maybe you're not seeing this issue either then, that was just a guess in #5279. Could you please show the output of `coredumpctl info` right after the crash?

sure, I think this is a "last 5 minutes command"
```shell
$ coredumpctl -S -5m
TIME                            PID   UID   GID SIG COREFILE  EXE
Wed 2020-05-27 17:15:43 IST  263472  1000  1000  11 present   /usr/bin/python3.8
```

**Comment by The-Compiler** [comment] 2020-05-27 16:21
@sentriz That only shows an overview of crashes, `coredumpctl info` shows detailed information about a specific crash.

**Comment by sentriz** [comment] 2020-05-27 16:26
oops! sorry here it is https://termbin.com/qwqg

**Comment by The-Compiler** [comment] 2020-05-27 16:35
@sentriz Okay, from what I can see so far, you're seeing yet another segfault in Qt which is independent from #5279 and this one... I opened a new issue, let's continue this there: #5470.

**Comment by martynjy** [comment] 2020-05-27 20:56
@The-Compiler 

The crashes happened randomly.  No particular website, it could be any tab that was clicked on.

It is a 13 years old computer & radeon graphics card.  So the drivers could very well have a part in it.  

Although the downgrade to 20.0.7-2 fixed the session issue,  qutebrowser would still crash now and then but this time whilst browsing.  Opening a website would cause crash.  Again any random website.

I finally ditched 20.0.7 and returned to 20.0.6-2 and both problems are now fixed.

**Comment by pazz** [comment] 2020-06-17 08:26
I'm not sure if this is related, but I also get a segfault after upgrading my debian testing.

```terminal
gdb $(readlink -f $(which python3)) -ex 'run -m qutebrowser --debug --no-err-windows'

...

09:19:27 DEBUG    sql        sql:run:220 query bindings: {':atime': 1592381967, ':redirect': False, ':title': 'Date/timestamp missing from search mode · Issue #1527 · pazz/alot', ':url': 'https://github.com/pazz/alot/issues/1527'}
09:19:27 DEBUG    sql        sql:__init__:183 Preparing SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
09:19:27 DEBUG    sql        sql:run:216 Running SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
09:19:27 DEBUG    sql        sql:run:220 query bindings: {':last_atime': 1592381967, ':title': 'Date/timestamp missing from search mode · Issue #1527 · pazz/alot', ':url': 'https://github.com/pazz/alot/issues/1527'}
09:19:27 DEBUG    sessions   sessions:save:317 Saving session _autosave to /home/pazz/.local/share/qutebrowser/sessions/_autosave.yml...
09:19:27 DEBUG    signals    signalfilter:_filter_signals:92 ignoring: cur_load_finished(True) (tab 1)
[New Thread 0x7fff42c79700 (LWP 68180)]

09:19:33 DEBUG    misc       mainwindow:_update_overlay_geometry:356 new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x7fffa80cd040>: PyQt5.QtCore.QRect(0, 1370, 846, 1)
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "python3.8" received signal SIGSEGV, Segmentation fault.
0x00007fffd74439b8 in ?? () from /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
```

The file `/usr/lib/x86_64-linux-gnu/dri/iris_dri.so` belongs to a package called `libgl1-mesa-dri`, installed in version `20.1.1-1`.

```terminal
[~] dpkg -S /usr/lib/x86_64-linux-gnu/dri/iris_dri.so 
libgl1-mesa-dri:amd64: /usr/lib/x86_64-linux-gnu/dri/iris_dri.so
[~] sudo apt search libgl1-mesa-dri       
Sorting... Done
Full Text Search... Done
libgl1-mesa-dri/testing,now 20.1.1-1 amd64 [installed]
  free implementation of the OpenGL API -- DRI modules
```

**Comment by The-Compiler** [comment] 2020-06-23 13:41
@pazz I assume `glxgears` will crash as well? Looks like there are various Debian bugs open already: https://www.mail-archive.com/search?q=iris_dri.so&l=debian-bugs-dist%40lists.debian.org - according to some of them, switching to the modesetting driver (removing `xserver-xorg-video-intel` and maybe adjusting X configuration) seems to help.

Closing this, as I don't think there's much qutebrowser can do here...

**Closed by The-Compiler** 2020-06-23 13:41 UTC
Labels: bug: segfault/crash/hang, priority: 0 - high, status: can't reproduce, status: needs triage
