### ISSUE TITLE
Hints overlapping on page

### ISSUE THREAD

**Issue by craftyguy** [qutebrowser/qutebrowser#3998] opened 2018-06-13 23:21 UTC
On some pages (hackernews is typically really bad), hints overlap and are impossible to read. Even worse, some of the overlapping hints start with the same first letter, so when only the first letter of the background hint is shown (see screenshot), you actually can't select it unless you correctly guess what the second letter is.

![2018-06-13_86x381_scrot](https://user-images.githubusercontent.com/1474209/41383432-82beed70-6f25-11e8-96aa-6fac8f1ca17b.png)

```
qutebrowser v1.3.2
Git commit: 093f07f55 (2018-06-11 23:28:04 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.13-2-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Comment by jgkamat** [comment] 2018-06-14 02:59
Duplicate of #71 :P

**Closed by jgkamat** 2018-06-14 02:59 UTC

**Comment by craftyguy** [comment] 2018-06-14 03:00
Damn! I'm 0 for 2 today, I really need to improve my github searching abilities..

**Comment by jgkamat** [comment] 2018-06-14 03:08
github really needs to improve it's search, you're doing fine xD
