### ISSUE TITLE
Video stuttering

### ISSUE THREAD

**Issue by nicholasrupert** [qutebrowser/qutebrowser#8250] opened 2024-07-01 15:16 UTC
**Version info**:

qutebrowser v3.1.0
Backend: QtWebEngine 6.7.1, based on Chromium 118.0.5993.220 (from api)
Qt: 6.7.1

CPython: 3.12.3
PyQt: 6.7.0

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: no
jinja2: 3.1.4
pygments: 2.17.2
yaml: 6.0.1
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.7.0
PyQt6.sip: 6.7.12
pdf.js: no
sqlite: 3.45.1
QtNetwork SSL: OpenSSL 3.2.1 30 Jan 2024

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 24.1.2
Platform: Linux-6.9.5-200.fc40.x86_64-x86_64-with-glibc2.39, 64bit
Linux distribution: Fedora Linux 40 (Cinnamon) (fedora)
Frozen: False
Imported from /usr/lib/python3.12/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt6/libexec, data path: /usr/share/qt6

Paths:
cache: /tmp/qutebrowser-basedir-er4tj8fz/cache
config: /tmp/qutebrowser-basedir-er4tj8fz/config
data: /tmp/qutebrowser-basedir-er4tj8fz/data
runtime: /tmp/qutebrowser-basedir-er4tj8fz/runtime

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:36

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

Streaming video stutters. The video plays only a few frames per second, and it seems to go back a frame sometimes. Like it might play frame 1, 4, 3, 4, 9, 8, 9, 13, 12, 13 (just guessing). 

This happens with every video streaming service I have tried, including Youtube, Reddit-hosted video, Lingopie, Themis, Quimbee (study sites) and others.

The audio plays perfectly.

The video quality seems to make no difference at all. Whatever video quality I select, it plays in that quality, but stuttering. I have tried it in the lowest video quality settings in youtube, and it still stutters.

This problem is not happening in any other browser, including firefox, vivaldi, or surf.

**How to reproduce**

Go to any video streaming site and play a video.

**Comment by The-Compiler** [comment] 2024-07-01 15:32
Could you please try if you can reproduce this with the [testbrowser script](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py)? You should be able to download just that file and run e.g. `python3 testbrowser_webengine.py https://youtube.com`

**Comment by nicholasrupert** [comment] 2024-07-01 15:44
Looks like the issue is the same.

However, I have now found that Olympics videos on youtube do not skip either with or without the testbrowser script.

**Comment by The-Compiler** [comment] 2024-07-01 15:52
Given that you can reproduce there, closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can easily reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2024-07-01 15:52 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by nicholasrupert** [comment] 2024-07-01 16:02
[> treaming video stutters. The video plays only a few frames per second, and it seems to go back a frame sometimes. Like it might play frame 1, 4, 3, 4, 9, 8, 9, 13, 12, 13 (just guessing).
> 
> This happens with every video streaming service I have tried, including Youtube, Reddit-hosted video, Lingopie, Themis, Quimbee (study sites) and others.

](https://bugreports.qt.io/browse/QTBUG-126821)
