### ISSUE TITLE
qute-pass support for GitHub

### ISSUE THREAD

**Issue by ssiyad** [qutebrowser/qutebrowser#5984] opened 2020-12-23 18:22 UTC
qute-pass userscript currently does not work for https://github.com/login

**Comment by GbGp** [comment] 2020-12-27 21:23
keepass databases (at least modern versions) have a field to specify a custom autotype sequence that should be supported by most (all?) clients.
The autotype sequence is just string using a relatively simple syntax to parse (documented here https://keepass.info/help/base/autotype.html#autoseq). For example, a working sequence for a github entry is ```{USERNAME}{TAB}{TAB}{PASSWORD}{ENTER}```.
So it should just be matter of parsing such strings and converting to something edible for the ```fake-key``` command.

**Comment by The-Compiler** [comment] 2020-12-27 21:25
@GbGp The userscript is for [pass](https://www.passwordstore.org/) (or [gopass](https://www.gopass.pw/), not keepass.

**Comment by GbGp** [comment] 2020-12-27 21:31
oops, my bad. Well qute-keepass has the same issue, any solution found for pass can be useful for keepass as well.

**Comment by The-Compiler** [comment] 2020-12-30 14:54
Like mentioned by @lufte over in #5985, this is indeed a regression on GitHub's side:

- It worked properly on December 17: https://web.archive.org/web/20201217101721/https://github.com/login
- but then broke on December 18: https://web.archive.org/web/20201218103719/https://github.com/login

I've contacted GitHub support about it, and if you're affected by this, I'd encourage you to do the same.

**Comment by The-Compiler** [comment] 2021-03-18 18:07
Looks like this was fixed on GitHub's side.

**Closed by The-Compiler** 2021-03-18 18:07 UTC
