### ISSUE TITLE
jk to escape

### ISSUE THREAD

**Issue by premell** [qutebrowser/qutebrowser#6467] opened 2021-05-17 22:06 UTC
The escape key is quite hard to reach so it would be great if say "jk" could be clicked in quick sucession to escape from insert mode, like many users do with regular vim

**Comment by The-Compiler** [comment] 2021-05-18 06:04
Duplicate of #1044

**Closed by The-Compiler** 2021-05-18 06:04 UTC

**Comment by The-Compiler** [comment] 2021-05-18 06:05
If you could at least do a quick search before opening a new issue, I'd appreciate that. Here, you could search for "jk" and that issue was one of four results. So far, [most of your issues](https://github.com/qutebrowser/qutebrowser/issues?q=is%3Aissue+author%3Apremell) ended up being about either things that already exist or duplicates.

**Comment by premell** [comment] 2021-05-18 06:36
Yes I am sorry I will try to do better
