### ISSUE TITLE
Horrible color banding with the wayland backend.

### ISSUE THREAD

**Issue by DarkDefender** [qutebrowser/qutebrowser#5528] opened 2020-06-17 14:50 UTC
**Version info**:
```
qutebrowser v1.12.0
Git commit: b300a5464 (2020-06-17 09:34:12 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.7.7
PyQt: 5.15.0

sip: 4.19.23
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: Qt5CTProxyStyle
Platform plugin: wayland
OpenGL: X.Org, 4.6 (Compatibility Profile) Mesa 20.2.0-devel (git-de7c6950b3)
Platform: Linux-5.7.2-gentoo-x86_64-Intel-R-_Core-TM-_i7-9700K_CPU_@_3.60GHz-with-gentoo-2.6, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3.7
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/zed/.cache/qutebrowser
config: /home/zed/.config/qutebrowser
data: /home/zed/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:02:34
```
**Does the bug happen if you start with `--temp-basedir`?**:
No, it seems to ignore `QT_QPA_PLATFORM` so it defaults to the `xcb` backend there it seems.

**Description**
When running qutebrowser with the qt wayland backend, video and images seem to have really horrible color banding (left: xcb, right: wayland):
![screenshot](https://user-images.githubusercontent.com/312503/84912959-48ccac00-b0ba-11ea-94ff-0161fe69a83f.png)

**How to reproduce**
1. Launch qutebrowser with the wayland backend
`export QT_QPA_PLATFORM=wayland && qutebrowser`
2. Go to http://www.lagom.nl/lcd-test/gradient.php#gradient-h.png notice the color banding

I'm guessing this is probably an issue on QTs side. But I'm not sure, so that is why I am reporting it here.

**Comment by The-Compiler** [comment] 2020-06-17 14:57
Looks fine here. `qutebrowser --temp-basedir` should work with `QT_QPA_PLATFORM=wayland` just fine (it does show wayland in `:version` for me) - are you sure you did set the environment variable correctly when trying with that? Also, can you check if you see the same issue with [KDE Falkon](https://www.falkon.org/)?

**Comment by DarkDefender** [comment] 2020-06-17 17:18
Hmm, you are right.

If I rename my `.config/qutebrowser` dir, the issue goes away...
Do you have any clue what setting could cause this?

**Comment by DarkDefender** [comment] 2020-06-17 21:25
Ok I found the setting that causes this.

if `window.hide_decoration` is true, I get this issue on startup.
But I have to start qutebrowser with this option on, if I toggle it when it is running, nothing seems to happen.

**Comment by The-Compiler** [comment] 2020-06-18 07:56
Well, that's weird! That setting needs a restart on Wayland because all it does internally is setting an `QT_WAYLAND_DISABLE_WINDOWDECORATION=1` environment variable.

However, I still can't reproduce this... What Wayland compositor are you using? Can you test with Falkon and `QT_WAYLAND_DISABLE_WINDOWDECORATION=1` set as well?

**Comment by DarkDefender** [comment] 2020-06-20 12:13
I tried this in both sway and weston. Both has the same issue. So I don't think this is a bug with sway and weston.

I have the same issue with falkon. So I guess this is a qtwebengine issue.

**Comment by The-Compiler** [comment] 2020-06-20 13:05
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2020-06-20 13:05 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by qoh** [comment] 2021-02-10 19:47
@DarkDefender Did you ever get any further with this? Did you ever report it upstream? I can't seem to find a relevant issue there.

I am still experiencing the same issue in sway with newest `qutebrowser 2.0.2; QtWebEngine (Chromium 83.0.4103.122); Qt 5.15.2`. Just as mentioned previously, the color banding goes away for me as well if I run with `QT_QPA_PLATFORM=xcb`.

I can see perfect banding-free gradients in Firefox (Wayland) side-by-side with qutebrowser, on the same output.

**Comment by DarkDefender** [comment] 2021-02-10 19:54
@qoh I didn't get around to report this upstream.
I simply worked around it and then forgot about it.

I don't really have that much time to spend on this right now so I guess it would be best if you take over and report it upstream.

**Comment by DaemonLife** [comment] 2025-10-23 19:14
I also got this error. I solved it by setting the browser to "hide_decoration = false"

And launching the browser with the command:
`export QT_WAYLAND_DISABLE_WINDOWDECORATION=0 && qutebrowser`

Now the colors display well. Meanwhile, in my Sway environment, I have the settings
QT_QPA_PLATFORM=wayland
QT_WAYLAND_DISABLE_WINDOWDECORATION=1 (cause of error!)

So, you can launch the browser in Wayland this way to be sure:
`export QT_QPA_PLATFORM=wayland && export QT_WAYLAND_DISABLE_WINDOWDECORATION=0 && qutebrowser`!
But don't forget to set "hide_decoration = false"!
