### ISSUE TITLE
Unable to log in to onenote.com

### ISSUE THREAD

**Issue by robcsi** [qutebrowser/qutebrowser#3145] opened 2017-10-17 08:07 UTC
When trying to log into onenote.com, this message is displayed by the site.

![image](https://user-images.githubusercontent.com/5070886/31653353-f7f16ba2-b32a-11e7-8800-91f0902a1c20.png)
This happens after entering the email address and pressing the button on the log in form. The password form is not reached yet, so you probably don't need an existing onenote account to reproduce this...

It seems that qutebrowser is executing a series of requests, which make onenote respond like this. I see the behavior in the address bar as well.

**Comment by The-Compiler** [comment] 2017-10-17 08:09
What Qt version, backend and qutebrowser version?

(There's a reason the issue template asks you for this - so I don't have to :wink:)

**Comment by robcsi** [comment] 2017-10-17 08:10
Running on Windows 7.
qutebrowser v1.0.1
Git commit: v1.0.1 (2017-10-13 09:21:56 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)
Qt: 5.9.1

**Comment by The-Compiler** [comment] 2017-10-17 08:14
Works fine for me with the same setup. Can you reproduce it when starting with `--temp-basedir`? Or maybe even in another browser? I guess it's hard to consistently reproduce it though if they're rate limiting...

Is your IP shared, like in an organization with other people using their accounts?

**Comment by robcsi** [comment] 2017-10-17 08:20
My IP is not shared.

It is not reproducible in Chrome or Firefox, I log in from those successfully.

With --temp-basedir I am able to get to the password form, but the same message appears after that.

**Comment by robcsi** [comment] 2017-10-17 08:21
I'm behind a proxy, though... QB asks for authentication info when it start up.

**Comment by The-Compiler** [comment] 2017-10-17 08:27
I've tried with a HTTP proxy with authentication (mitmproxy), and I still can't reproduce this. I guess you have that proxy configured in Chrome/Firefox as well?

Can someone else with a Microsoft account try to reproduce this please?

**Comment by robcsi** [comment] 2017-10-17 08:48
Yes, I have it configured in those browsers.

I asked a colleague, and he experiences the same problem, but only after the completing the password on the second form.

I'm unable to bypass the proxy at the moment, but will do some tests when I can.

**Comment by jgkamat** [comment] 2017-10-17 14:04
I'm able to login fine as well:

```
qutebrowser v1.0.2
Git commit: 5c6a821b1-dirty (2017-10-17 15:35:58 +0200)
Backend: QtWebEngine (Chromium 49.0.2623.111)
```

**Comment by The-Compiler** [comment] 2017-10-17 14:05
I'm closing this then - sorry, but I don't think there's anything qutebrowser can do here. If anything, it'd be a bug with its backend (QtWebEngine in this case), but I'm really not sure what's going on here.

**Closed by The-Compiler** 2017-10-17 14:05 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by robcsi** [comment] 2017-10-17 21:00
I'm unable to reproduce it either on my personal laptop, so it must have been the company proxy that was causing the issue.

Thanks.
