### ISSUE TITLE
Reset search to start at top of page

### ISSUE THREAD

**Issue by adigitoleo** [qutebrowser/qutebrowser#7071] opened 2022-03-15 11:58 UTC
Currently the only way I know of to reset search so that it looks from the start of the page again is to reload the entire webpage. It would be nice if blank `:search` or blank `/` would also do this. Current search (retaining the last location of a hit) could still be resumed using `n` or `N`.

**Comment by adigitoleo** [comment] 2022-03-15 11:59
There is currently one other workaround: Hit `G` to bo to the bottom of the page, then repeat the search `/pattern`. A message will appear saying that the search is beginning from the top again.

**Comment by toofar** [comment] 2022-03-15 20:51
Possibly a duplicate of #1222, maybe not quite.

One other way to make it start from the top is to click at the top of the page with a pointing device. Obviously not a satisfactory solution for many qutebrowser users, but it exists!

**Comment by adigitoleo** [comment] 2022-03-16 00:36
Agree, it's more or less a duplicate. As mentioned over there this is kind of two issues:

> I noticed 2 issues here:
>
> - search-next and search-prev go to next/previous search text ignoring the scroll position;
> - re-searching ANY text starts from previous match location instead from start of the page or first visible element (/the<Enter>2n/the). To make it "reset" and search from the top some text that isn't on page should be searched.

**Comment by The-Compiler** [comment] 2022-03-17 13:46
Merging this into #1222 since I think a solution for both would look very similar code-wise.

**Closed by The-Compiler** 2022-03-17 13:46 UTC
Labels: priority: 3 - wishlist
