### ISSUE TITLE
Dynamic Drop-downs take you out of insert mode

### ISSUE THREAD

**Issue by bearcatsandor** [qutebrowser/qutebrowser#4873] opened 2019-06-26 22:40 UTC
**Version info (see `:version`)**:
qutebrowser v1.6.3
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.6.8
Qt: 5.12.3
PyQt: 5.12.2

sip: 4.19.17
colorama: 0.4.1
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.3.1
yaml: 5.1
cssutils: 1.0.2 $Id$
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.28.0
QtNetwork SSL: OpenSSL 1.1.0k  28 May 2019

Style: Kvantum::Style
Platform: Linux-4.19.42-gentoo-x86_64-AMD_FX-tm-6300_Six-Core_Processor-with-gentoo-2.6, 64bit
Linux distribution: Gentoo/Linux (gentoo)
Frozen: False
Imported from /usr/lib64/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python3.6
Qt library executable path: /usr/lib64/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/moonwind/.cache/qutebrowser
config: /home/moonwind/.config/qutebrowser
data: /home/moonwind/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Does the bug happen if you start with `--temp-basedir`?**:
yes
**Description**
When I type into a dynamic search field (a field that queries and populates a list as i type), qutebrowser will exit insert mode and go into command mode as i'm typing.  This leads to undesired effects, as depending on what words I was trying to type, all of my tabs may disappear aside from the one i was on, old tabs may be re-opened the page may jump around and input buttons my be pressed. 

It  doesn't matter how many characters i type, but typing with a 1 second pause between each letter will delay it for about 10 characters.  It happens not just on google searches, but the input boxes i've used on my own websites.  Interestingly enough i can not reproduce it on the title field of this bug report, so there is probably a coding difference there. 
**How to reproduce**
Go to https://www.google.com/alerts and start typing in the search bar

**Comment by The-Compiler** [comment] 2019-06-26 22:43
Duplicate of #3596

**Closed by The-Compiler** 2019-06-26 22:43 UTC

**Comment by The-Compiler** [comment] 2019-06-26 22:44
This is already fixed in the current git master, but you can also use passthrough mode (ctrl-v) or do something like `:set -u www.google.com/alerts input.insert_mode.leave_on_load false` as a workaround.

**Comment by bearcatsandor** [comment] 2019-06-27 08:40
Thank you! I looked for a duplicate but wasn't sure what to search under. I'm glad it's fixed in current master and thank you for the workaround.
