### ISSUE TITLE
Can't open any thread on Reddit

### ISSUE THREAD

**Issue by pierre-jean** [qutebrowser/qutebrowser#5577] opened 2020-07-07 20:59 UTC
**Version info**:
qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.3
Qt: 5.12.7 (compiled 5.12.4)
PyQt: 5.12.2

sip: 4.19.17
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 2.1.266 (/app/share/pdf.js/build/pdf.js)
sqlite: 3.27.2
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: Adwaita::Style
Platform: Linux-5.6.16-200.fc31.x86_64-x86_64-with-glibc2.2.5, 64bit
Linux distribution: KDE Flatpak runtime (kde)
Frozen: False
Imported from /app/lib/python3.7/site-packages/qutebrowser-1.7.0-py3.7.egg/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/libexec, data path: /usr

**Does the bug happen if you start with `--temp-basedir`?**:
No
**Description**
Clicking (with the mouse or through keyboard shortcut) on "View entire discussion" for any Reddit thread doesn't do anything (button looks clicked but no content is loaded). 

**How to reproduce**
Reproduce on fresh install of qutebrowser on both Fedora and NixOs.
Example of url: https://www.reddit.com/r/linux4noobs/comments/9383kw/qutebrowser_doesnt_open_reddit/
Click on the button "View entire discussion (7 comments)" (or use hints to use the keyboard).

The button should disappear and the rest of the conversation should load. The button stays there instead and no new content is loaded.

**Comment by The-Compiler** [comment] 2020-07-07 21:01
Duplicate of #5486, fixed if you update to either Qt 5.13+ or with a workaround in qutebrowser v1.13.0.

**Closed by The-Compiler** 2020-07-07 21:01 UTC
