### ISSUE TITLE
pdfjs/google spreadsheets renders text more than once and both renders don't align

### ISSUE THREAD

**Issue by Bonoolu** [qutebrowser/qutebrowser#7774] opened 2023-07-10 14:30 UTC
**Version info**:
qutebrowser v2.5.4
Git commit: 72aee69c9 on master (2023-07-10 10:14:03 +0200)
Backend: QtWebEngine 6.5.1, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.1

CPython: 3.11.3
PyQt: 6.5.1

Qt wrapper: PyQt6 (via QUTE_QT_WRAPPER)

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
pdf.js: 3.7.107 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.1.1 30 May 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 21.3.9 Amber
Platform: Linux-6.3.9-artix1-1-x86_64-with-glibc2.37, 64bit
Linux distribution: Artix Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /tmp/qutebrowser-basedir-m285o79u/cache
config: /tmp/qutebrowser-basedir-m285o79u/config
data: /tmp/qutebrowser-basedir-m285o79u/data
runtime: /tmp/qutebrowser-basedir-m285o79u/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:01:52

**Does the bug happen if you start with `--temp-basedir`?**:
Yes, i even cleared my ENV vars of everything that might affect rendering
**Description**
pdfjs looks like this:
![pic](https://github.com/qutebrowser/qutebrowser/assets/64061670/2887d243-0f68-43b0-afba-dc26d3d19db3)
And Google Spreadsheets looks like this:
![pic](https://github.com/qutebrowser/qutebrowser/assets/64061670/ff8f7fcb-b99e-48a4-a9a5-6014cfa66188)
When the page first renders the text looks a little bit bold and uneven, that's because the text is rendered twice and both renders align somewhat. As soon as I start scrolling, both renders misalign like shown in the pictures above.
**How to reproduce**
reproducable with any pdf and with any spreadsheet
1. open pdf
2. start scrolling

**Comment by The-Compiler** [comment] 2023-07-10 14:46
Reminds me of #7489... though most likely an upstream QtWebEngine/Chromium issue which qutebrowser won't be able to do anything about.

Could you try with `--temp-basedir --qt-flag disable-accelerated-2d-canvas` as well?

**Comment by Bonoolu** [comment] 2023-07-10 14:50
Thank you --qt-flag disable-accelerated-2d-canvas did indeed work
![pic](https://github.com/qutebrowser/qutebrowser/assets/64061670/c4b1902d-da2b-488a-aa3c-559b3e6d17d8)

**Comment by The-Compiler** [comment] 2023-07-10 14:54
Looks like a duplicate of #7489 then. You can add this to `qt.args` in your config to persist it.

**Closed by The-Compiler** 2023-07-10 14:54 UTC
