### ISSUE TITLE
Create a snap of qutebrowser. v1+ onwards

### ISSUE THREAD

**Issue by 3DJetengine** [qutebrowser/qutebrowser#3142] opened 2017-10-17 00:28 UTC
Snaps are a [basic feature](https://build.snapcraft.io/) for ubuntu and arch based distros now.

Looking to implement a base qute-browser snap, and then to make minimal KB updates as used by
[ScarlettGatelyClark](https://launchpad.net/~sgclark) and others in at the recent [Rally in NY](http://ubuntupodcast.org/2017/10/12/s10e32-possessive-open-chicken/).
if you listen for a minute from 17:50mins in - you'll get the jist.

putting this as a feature request.

**Comment by The-Compiler** [comment] 2017-10-17 03:13
Duplicate of #1912

**Closed by The-Compiler** 2017-10-17 03:13 UTC
