### ISSUE TITLE
Discord weirdness

### ISSUE THREAD

**Issue by mike402** [qutebrowser/qutebrowser#4379] opened 2018-10-23 15:56 UTC
**Version info (see `:version`)**:
https://paste.the-compiler.org/view/2a0528bc

**Does the bug happen if you start with `--temp-basedir`?** (if applicable):
Have not tried yet.

**Description**
Discord:
* Often forgets my auth cookies, so I have to enter password ten times a week.
* Sometimes will either not load at all or get stuck at the loading screen. Simple refresh does not work, have to open another tab. Happens much less often than around two months ago, but still does.
* Sometimes refuses to mark channels I view as read.

**How to reproduce**

http://discordapp.com

**Comment by jgkamat** [comment] 2018-10-23 16:22
Maybe this is related to https://github.com/qutebrowser/qutebrowser/issues/4281

**Comment by The-Compiler** [comment] 2018-10-23 18:14
Can't say much more without knowing whether it happens with `--temp-basedir` as well or not. Haven't seen any problems myself so far, but I use Discord quite rarely.

**Comment by mike402** [comment] 2018-10-24 07:44
At least not marking messages as read does. But I'm not sure I'm doing this right because with --temp-basedir I notice no changes in config -- I see the same history etc?

**Comment by The-Compiler** [comment] 2018-11-09 07:47
Sorry for the late answer - if you start with `--temp-basedir` you shouldn't see any of your existing configuration or history. If you do, something is wrong indeed :wink:

**Comment by mike402** [comment] 2018-11-28 15:13
I think I know what is happening. From what I understand Quteborwser does not flush cookies to the disk immediately. So it must be either me closing it with WM keybind instead of Control-Q, or after either a tab hangs or it crashes with Discord open. IMHO it would be better to shut down gracefully if window is closed from WM.

**Comment by The-Compiler** [comment] 2018-11-28 15:16
That's already the case, but QtWebEngine doesn't provide a way to save the cookies gracefully - see #2263.

**Comment by The-Compiler** [comment] 2018-11-28 15:16
Duplicate of #2263

**Comment by basedtho** [comment] 2020-11-17 20:17
discord still does not remember cookies here. i have to log in everytime i restart qb

**Comment by The-Compiler** [comment] 2020-11-17 20:21
@basedtho Works fine here. Not much more I can say without version information or anything.

**Comment by basedtho** [comment] 2020-11-17 20:22
@The-Compiler https://paste.the-compiler.org/view/88d4410e

i'm on arch. how do i test it with --temp-basedir? i mean it needs to remember login

**Comment by mike402** [comment] 2020-11-17 20:25
The issue has not been occurring here for a while.

**Comment by basedtho** [comment] 2020-11-17 20:27
my config.py
https://0x0.st/i59_.bin

**Comment by The-Compiler** [comment] 2020-11-17 20:30
@basedtho You can use `--basedir` with a path to some empty directory instead. Also, please show `:config-diff` instead.

**Comment by basedtho** [comment] 2020-11-17 20:37
https://0x0.st/i599.txt config-diff

while i was switching between profiles it lost many tabs btw (including this one)
![image](https://user-images.githubusercontent.com/60894565/99444772-859f0800-28d1-11eb-8d3d-35695a815304.png)

**Comment by The-Compiler** [comment] 2020-11-17 20:39
You have `content.cookies.accept = no-3rdparty` set, I'm guessing that's the culprit. No idea what's up with those tabs, though.

**Comment by basedtho** [comment] 2020-11-17 20:40
i tried switching it to `all` to no avail

**Comment by basedtho** [comment] 2020-11-17 20:41
i guess i'll start from scratch

**Comment by The-Compiler** [comment] 2020-11-17 20:43
Either that, or maybe try deleting cookies for discord.com/discordapp.com in `:devtools` - but I don't think there's anything wrong in qutebrowser itself.

**Comment by basedtho** [comment] 2020-11-17 20:50
i deleted the file Cookies, and it works now! i guess their old address (discordapp.com) clashed with the new one somehow or something. thank you for the help!

**Comment by basedtho** [comment] 2020-11-18 07:40
after a long inspection i've narrowed down the problem to my `autoconfig.yml`. it's hard to believe but the reason discord does not save login is because of these lines

```
  tabs.position:
    global: right
```

**Comment by basedtho** [comment] 2020-11-18 07:50
here's a minimal non-working `autoconfig.yml` https://0x0.st/i5V8.txt (auto_save.session for convinience). you can check it with `--basedir` . discord remembers login once, and on second browser restart you have to login again

**Comment by basedtho** [comment] 2020-11-19 09:25
@The-Compiler Florian? anything to say on this?

**Comment by The-Compiler** [comment] 2020-11-19 09:35
@basedtho I'm in contact with dozens of users every week, over a variety of channels (some of which are public, some of which aren't). Maybe try waiting more than just a day if you don't get an immediate reaction to something, especially when it involves some more thorough investigation?

**Comment by basedtho** [comment] 2020-11-19 09:37
okay, sorry

**Comment by The-Compiler** [comment] 2020-11-20 13:36
I can reproduce, and I don't really have an explanation. My best bet is that the combination of "exotic browser" and "weird window size" (or... something) triggers some kind of protection in Discord's code.

This isn't specific to qutebrowser, though - I was able to reproduce when the bookmarks sidebar is open in KDE Falkon as well. I don't think there's anything qutebrowser can do about it, I'm afraid.

**Comment by Isti115** [comment] 2021-04-24 19:52
Hmm, I thought that I had to have a haunted computer after bisecting my config file and ending up at this setting, but seemingly I'm not alone.
What are the ways that Discord can be applying checks to detect the sizes? Out of curiousity I have already tried resizing my browser window to weird sizes, but that didn't drop my credentials. Maybe they compare `window.innerWidth` and `window.outerWidth`? There are several results for `innerWidth` in their source files and only one for `outerWidth`, which (at least to me) seems to make my suspicion not completely unrealistic, but when opening that file my devtools crashed, so I couldn't check the code.
Would it have any negative consequence for QuteBrowser to just return the `innerWidth` value for both properties? :thinking:

**Comment by The-Compiler** [comment] 2021-04-24 20:18
> Would it have any negative consequence for QuteBrowser to just return the `innerWidth` value for both properties?

qutebrowser doesn't (and probably can't) affect that, it's all handled by the underlying QtWebEngine/Chromium. Maybe you can patch it via its Greasemonkey support though - if that's possible, I'd definitely consider adding it as a site-specific quirk for discord.

> so a difference in inner and outer width could suggest some kind of embedding, which they want to avoid?

No idea. It's quite stupid either way.

**Comment by mike402** [comment] 2021-04-24 20:19
Strange, but the problem has not occured to me anymore for a while. The only change I remember making to my config before the issue disappeared was to enable canvas reading because of Youtube's move to canvas-reading-based controls. Maybe disabled canvas reading can contribute to triggering their "exotic browser" logic?

**Comment by The-Compiler** [comment] 2021-04-24 20:28
I experimented a bit and it looks like Discord logs me out whenever the width of the tab bar changes?!

**Comment by Isti115** [comment] 2021-04-24 20:43
Aaand I've managed to fix it with this userscript:
https://gist.github.com/Isti115/3273626a38cf2206a85da8de522d36a5

**Comment by The-Compiler** [comment] 2021-04-24 20:47
@Isti115 Wouldn't that break once you resize the window? I've been playing with this:

```js
// ==UserScript==
// @include https://discord.com/login
// @run-at document-start
// ==/UserScript==
Object.defineProperty(window, 'innerWidth', { get() { return window.outerWidth; } });
```

it seems to work for me from a quick test, despite me accidentally using `window` rather than `unsafeWindow`? Could you give it a test too?

**Comment by Isti115** [comment] 2021-04-24 20:51
This seems to work as well, and indeed looks like a better solution. :+1:  
(Even though I think that the resizing would need to happen during the loading of the page, which has a very low probability, but still, it's a more solid approach. :upside_down_face:)  
Maybe include this in the FAQ? Probably it isn't that _frequent_ though. :thinking:

**Comment by The-Compiler** [comment] 2021-04-24 21:02
> Maybe include this in the FAQ? Probably it isn't that _frequent_ though.

I'd happily ship it with qutebrowser as a site-specific quirk to fix this for everyone. This is too stupid to care about whatever Discord wants to achieve with it.

> Edit: Your solution breaks if I put it in an immediately invoked function expression

FWIW there's no need, every Greasemonkey script [already is in an IIFE](https://github.com/qutebrowser/qutebrowser/blob/v2.2.0/qutebrowser/javascript/greasemonkey_wrapper.js#L195) (together with some Greasemonkey utilities).

> Edit 2: Ohh, or maybe it was just because your `@match` is not generic enough! If I already had a channel open, then the URL is more complicated.

How does the URL look then (or how can I reproduce this exactly)? I'd like to avoid running it on `https://discord.com/*` if we can find a more narrow match.

**Comment by Isti115** [comment] 2021-04-24 21:24
After going through the whole interface I've managed to compile the following list of possible URLs:
- https://discord.com/login
- https://discord.com/channels/*
- https://discord.com/store
- https://discord.com/guild-discovery

Here is an example for a direct message:
- https://discord.com/channels/@me/830131624859271248  

And a server URL:
- https://discord.com/channels/175192201486270464/175194399859277824

**Comment by The-Compiler** [comment] 2021-04-24 21:31
Ah, right, thanks - I thought it was always checking on the `/login` page only, but it looks like that's not the case. Well, `*` it is then...

> Just out of curiosity, what other pages are there that need such "site-specific quirks"?

The worst offenders are Google and WhatsApp Web, also there are some minimal polyfills for older QtWebEngine versions:

- https://github.com/qutebrowser/qutebrowser/blob/master/doc/help/settings.asciidoc#content.site_specific_quirks.skip
- https://github.com/qutebrowser/qutebrowser/tree/master/qutebrowser/javascript/quirks
- https://github.com/qutebrowser/qutebrowser/blob/v2.2.0/qutebrowser/browser/webengine/webenginesettings.py#L440-L457

Reopening this so I don't forget to add it tomorrow, off to bed now!

**Closed** 2021-04-28 06:19 UTC
Labels: priority: 1 - middle
