### ISSUE TITLE
vimium-like input hints

### ISSUE THREAD

**Issue by thamma** [qutebrowser/qutebrowser#3006] opened 2017-09-20 14:56 UTC
Vimium provides input hints like this:
https://i.imgur.com/mu32mRA.png
Allowing you to tab between the inputs in `-- INSERT MODE --`, highlighting the selected.

What do you think about having this feature in qutebrowser? I'm not sure how vimium implements this but I assume it should be rather easy to implement it to qutebrowser as well.

**Comment by The-Compiler** [comment] 2017-09-20 14:59
I don't really follow - how is this different from just tabbing between the fields normally?

**Comment by thamma** [comment] 2017-09-20 15:53
Normal tabbing skips between every link. I'm talking about tabbing between the inputs of (the visible area of) a website. Currently qutebrowser supports hints on inputs via `hint inputs`, however when I was using Chromium I found it more comfortable to tab between the inputs rather than having to select the hint with a letter/number keystroke.

**Comment by pkillnine** [comment] 2017-09-20 16:39
Do you mean be able to press tab to select hints (combined with `hint inputs`)? There's an issue open for that, but I can't find it.

**Comment by The-Compiler** [comment] 2017-09-20 19:41
There's #1305 - but after trying this in Vimium, it seems to me like what @thamma means is basically #219. The tabbing there isn't a feature of Vimium, that's how any browser reacts when you tab in an input field. The only thing Vimium does there is focusing the first input field (what #219 is about), and highlighting the input fields (which I don't think is necessary).

I'm closing this - let me know if you disagree with that conclusion though, @thamma :wink:

**Closed by The-Compiler** 2017-09-20 19:41 UTC
Labels: status: needs triage

**Comment by thamma** [comment] 2017-09-21 01:48
#219 is pretty much what I was talking about. Thanks for referencing that issue. Your initial comment is very much the code resulting in the behaviour i expect - without the annotation about a `--first` flag.

> and highlighting the input fields (which I don't think is necessary).

I totally agree. It's nice to have and pretty to look at but not needed at all.

> The only thing Vimium does there is focusing the first input field (what #219 is about),

Using `gi` in vimium focuses the first input field, that's correct. However once focused you can tab to the next available input fields whilst never focusing links or something like that. I think having this functionality in qutebrowser would be a very nice.

I assume it should be easy to shape the code you provided from vimium in your first comment in #219 into at least something like [this](https://github.com/qutebrowser/qutebrowser/issues/219#issuecomment-259289461).

**Comment by The-Compiler** [comment] 2017-09-21 04:43
> However once focused you can tab to the next available input fields whilst never focusing links or something like that. I think having this functionality in qutebrowser would be a very nice.

Do you have an example page where that's not the case already?

**Comment by thamma** [comment] 2017-09-21 11:47
Any pages where there is a link between two inputs will do. Consider the [reddit frontpage](https://reddit.com) for example (without being logged in). 

Reproducing behaviour in vimium:
- `gi` to select the first input field (search)
- `tab` to switch to next input field (username)
- continui to `tab` into next input field (password)

Reproducting behaviour in qutebrowser:
- select the first input field (search) (however you want. for instance using #219's `first`-script)
- hit `tab`.

Actual behaviour in qutebrowser:
- focus jumps to the magnifying glass of the search bar
- subsequent `tab`s between links on the page

Expected behaviour in qutebrowser:
- focus jumps into next input field (user)
- subsequent `tab`s jump between input fields on the page. In this instance cycling between search, username and password.

**Comment by The-Compiler** [comment] 2017-09-25 06:45
Hm, not sure why I never noticed this! I think something like that should be possible with #1305.

**Comment by ViktorWalter** [comment] 2018-10-25 19:49
Inspired by https://github.com/qutebrowser/qutebrowser/issues/219#issuecomment-259289461 i made a substitution for this functionality that works at least for my uses - basically if there is only one input field, then it gets focused, otherwise hints are shown. This helps with frustration in cases where I don't notice some other input field from the intended being present, which is for me the most frequent use-case of the vimium input switching:
:bind gi hint inputs ;; jseval --quiet var inputs = document.getElementsByTagName("input"); if ( inputs.length > 1) { hidden = hidden || inputs[i].attributes[j].value.includes("hidden"); if(!hidden) { inputs[0].focus(); break; } }
Let me just say that I find this kind of scriptability amazing in qutebrowser.

**Comment by jgkamat** [comment] 2018-10-26 05:30
I think github is dropping comments again, @ViktorWalter posted this but it didn't come in here:

> Inspired by #219 (comment) i made a substitution for this functionality that works at least for my uses - basically if there is only one input field, then it gets focused, otherwise hints are shown. This helps with frustration in cases where I don't notice some
other input field from the intended being present, which is for me the most frequent use-case of the vimium input switching:
:bind gi hint inputs ;; jseval --quiet var inputs = document.getElementsByTagName("input"); if ( inputs.length > 1) { hidden = hidden || inputs[i].attributes[j].value.includes("hidden"); if(!hidden) { inputs[0].focus(); break; } }
Let me just say that I find this kind of scriptability amazing in qutebrowser.

**Comment by ViktorWalter** [comment] 2018-10-26 07:39
No, sorry, I deleted it. Turns out I made a mistake. After rereading my post I realized that the expected behavior was actually not the result of the script (since it had a glaring error in it), but rather of me setting hints.auto_follow to always previously, which initially seemed not to work.
