### ISSUE TITLE
PDFjs shows blank page

### ISSUE THREAD

**Issue by lrustand** [qutebrowser/qutebrowser#7448] opened 2022-10-25 10:36 UTC
**Version info**:

qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.6

CPython: 3.10.8
PyQt: 5.15.7

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
If I try to open any pdf file with ctrl+p to open it in PDFjs, PDFjs only shows a blank pdf file. This happens every time and has been like this for many months. I have reinstalled both Qutebrowser and PDFjs several times, but no change.

![2022-10-25-123347_1272x606_scrot](https://user-images.githubusercontent.com/13719791/197751594-4bc07cf7-a381-4c13-bbaf-96367854c1bd.png)

**How to reproduce**

Open any pdf link and press ctrl+p. For example https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf

**Comment by The-Compiler** [comment] 2022-10-25 10:37
Duplicate of #7335 - if you're on Archlinux, install `pdfjs-legacy` instead.

**Closed by The-Compiler** 2022-10-25 10:37 UTC

**Comment by lrustand** [comment] 2022-10-25 10:39
Thanks!!  It worked like a charm
