### ISSUE TITLE
Crash when loading Google Chat

### ISSUE THREAD

**Issue by ndcontini** [qutebrowser/qutebrowser#7965] opened 2023-10-16 14:21 UTC
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.6, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.0
**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
After logging into Google Chat, the landing page (where you can select a conversation and view the selected chat) loads and then the browser crashes.
**How to reproduce**
Log into Google Chat

[debug_log.txt](https://github.com/qutebrowser/qutebrowser/files/12917916/debug_log.txt)
[gdb.txt](https://github.com/qutebrowser/qutebrowser/files/12917917/gdb.txt)

**Comment by The-Compiler** [comment] 2023-10-16 14:55
Duplicate of #7962

**Closed by The-Compiler** 2023-10-16 14:55 UTC
