### ISSUE TITLE
Display issue for tabs opened with the middle-click

### ISSUE THREAD

**Issue by bedumont** [qutebrowser/qutebrowser#3960] opened 2018-05-29 09:28 UTC
Info : http://paste.the-compiler.org/view/31fc5c06
I am running Arch.
Hello ! Since last update (I think...) some links opened in new tabs by middle-clicking on them are displayed on the bottom half of the browser. The top half is empty white space. Opening the new tab with hints displays it correctly, so does right clicking -> "Open link in new tab". Closing the tab from wich the link was opened immediatly corrects the layout of the new tab. Undoing the closure leaves the new tab correctly displayed and restore the closed tab correctly as well. It does not happen on every website. It does on GitHub, Facebook for external links, Google...

**Comment by The-Compiler** [comment] 2018-05-29 09:30
Duplicate of #3920

**Closed by The-Compiler** 2018-05-29 09:30 UTC
