### ISSUE TITLE
Render Process Crashes 

### ISSUE THREAD

**Issue by monkeynaleo** [qutebrowser/qutebrowser#5736] opened 2020-09-21 08:11 UTC
**Version info**:

qutebrowser v1.13.1
Git commit: d8473590e on master (2020-09-16 21:13:47 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.8.5
PyQt: 5.15.1

sip: 5.4.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.1
yaml: 5.3.1
cssutils: no
attr: 20.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.1
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.6.347 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.1.8
Platform: Linux-5.8.9-arch2-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/naleo/.cache/qutebrowser
config: /home/naleo/.config/qutebrowser
data: /home/naleo/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/naleo/.config/qutebrowser/config.py has been loaded
Uptime: 0:02:32
**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
I am having a lot of renderer crashes.  Specifically, If I navigate to the main Ebay website, type something in the search box, and click search, I get renderer crashes, where it states Unable to load page, renderer process crashed.  I have also got the same problems trying to login to my credit card's website, card.discover.com.  
**How to reproduce**

Just like I said, easy replication for me is to go to ebay.com, and simply search.  The renderer process crashes every time for me.

**Comment by The-Compiler** [comment] 2020-09-21 14:59
Duplicate of #5721

**Closed by The-Compiler** 2020-09-21 14:59 UTC
