### ISSUE TITLE
Renderer process crashes with Qt 5.15.1

### ISSUE THREAD

**Issue by martonbalazs** [qutebrowser/qutebrowser#5721] opened 2020-09-16 23:37 UTC
Hi, following an upgrade two days ago on Arch, I have occasional "Renderer process crashed" on various log-in sites, and consistent 100% "Renderer process crashed" on my lloydsbank.com after I enter username and password. This even happens with --temp-basedir. The upgrade included

[2020-09-14T13:54:03+0100] [ALPM] upgraded glib2 (2.64.5-1 -> 2.66.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded python-pygments (2.6.1-3 -> 2.7.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded python-prompt_toolkit (3.0.7-1 -> 3.0.7-2)
[2020-09-14T13:54:13+0100] [ALPM] upgraded python-pyqt5 (5.15.0-3 -> 5.15.1-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded python-pyqtwebengine (5.15.0-2 -> 5.15.1-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded python-toml (0.10.1-1 -> 0.10.1-2)

and further down I'll show all from that day in case I missed something important above. Is this known? Or is there anything I can do to trace this down? Launching Chromium can handle lloydsbank.com fine. Thanks in advance! Version:

qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.8.5
PyQt: 5.15.1

sip: 5.4.0
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.0
yaml: 5.3.1
cssutils: no
attr: 20.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.1
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 20.1.7
Platform: Linux-5.8.8-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/balazs/.cache/qutebrowser
config: /home/balazs/.config/qutebrowser
data: /home/balazs/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:08:12

---

[2020-09-14T13:54:03+0100] [ALPM] upgraded systemd-libs (246.4-1 -> 246.5-1)
[2020-09-14T13:54:03+0100] [ALPM] upgraded systemd (246.4-1 -> 246.5-1)
[2020-09-14T13:54:03+0100] [ALPM] upgraded attica (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:03+0100] [ALPM] upgraded cliquer (1.21-4 -> 1.22-1)
[2020-09-14T13:54:03+0100] [ALPM] upgraded glib-networking (2.64.3-2 -> 2.66.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded gstreamer (1.16.2-2 -> 1.18.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded gst-plugins-base-libs (1.16.2-2 -> 1.18.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded libva (2.8.0-1 -> 2.9.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded rav1e (0.3.3-1 -> 0.3.4-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded gst-libav (1.16.2-2 -> 1.18.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded gst-plugins-bad-libs (1.16.2-13 -> 1.18.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded gst-plugins-good (1.16.2-3 -> 1.18.0-1)
[2020-09-14T13:54:12+0100] [ALPM] installed libavtp (0.1.0-2)
[2020-09-14T13:54:12+0100] [ALPM] installed svt-hevc (1.5.0-1)
[2020-09-14T13:54:12+0100] [ALPM] installed libmicrodns (0.1.2-1)
[2020-09-14T13:54:12+0100] [ALPM] installed zxing-cpp (1.1.1-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded gst-plugins-bad (1.16.2-13 -> 1.18.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded gst-plugins-base (1.16.2-2 -> 1.18.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded gst-plugins-ugly (1.16.2-4 -> 1.18.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kcoreaddons (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kconfig (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kwindowsystem (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kactivities (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded karchive (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kauth (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kdbusaddons (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kcrash (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kglobalaccel (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kcodecs (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kguiaddons (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded ki18n (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kwidgetsaddons (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kconfigwidgets (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kitemviews (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kiconthemes (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kxmlgui (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kbookmarks (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded solid (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kjobwidgets (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded knotifications (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kservice (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kwallet (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded kcompletion (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:12+0100] [ALPM] upgraded sonnet (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded ktextwidgets (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded kded (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded kio (5.73.0-1 -> 5.74.1-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded kpackage (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded kdeclarative (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded kcmutils (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded kirigami2 (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded kjs (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded kparts (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded kpty (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded lib32-glib2 (2.64.5-1 -> 2.66.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded libbraiding (1.0-4 -> 1.1-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded purpose (5.73.0-1 -> 5.74.0-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded qhull (2020.1-1 -> 2020.2-3)
[2020-09-14T13:54:13+0100] [ALPM] upgraded systemd-sysvcompat (246.4-1 -> 246.5-1)
[2020-09-14T13:54:13+0100] [ALPM] upgraded threadweaver (5.73.0-1 -> 5.74.0-1)

**Comment by The-Compiler** [comment] 2020-09-17 11:08
I haven't seen this so far. Should be possible to track this down once my Qt debug packages are updated to Qt 5.15.1. I'll get back to you once that's the case.

**Comment by martonbalazs** [comment] 2020-09-17 19:10
Thanks!

**Comment by The-Compiler** [comment] 2020-09-17 20:20
I still need to debug some issues with the pyqt packages before uploading everything to my qt-debug repo, but in the meantime I just uploaded the qt5-webengine package with debug symbols which should be enough to track this down.

If you start in a terminal normally and reproduce this, do you get any interesting output? If not, please do the following:

- Run `sudo pacman -U https://qutebrowser.org/tmp/qt5-webengine-debug-5.15.1-1-x86_64.pkg.tar.zst` to install my qt5-webengine build with debugging symbols
- Run `gdb -ex r --args /usr/bin/python3 -m qutebrowser --temp-basedir --qt-flag single-process lloydsbank.com` and reproduce the issue (the single-process flag *might* introduce other crashes, but let's hope it doesn't)
- Once you get a `(gdb)` prompt, do `set logging on`, then `bt` - you should get a `gdb.txt` with a (hopefully usable) C++ stacktrace about the crash.

**Comment by The-Compiler** [comment] 2020-09-17 20:37
Argh, looks like on `lloydsbank.com` the `single-process` flag causes a crash on the login page even before logging on:

```
[521232:521388:0917/223612.553575:ERROR:data_channel_controller.cc(405)] channel label not found

Thread 95 "Chrome_InProcUt" received signal SIGTRAP, Trace/breakpoint trap.
[Switching to Thread 0x7ffe37fff640 (LWP 521394)]
0x00007fffe6bcc72d in operator() () at ../../../../qtwebengine-everywhere-src-5.15.1/src/3rdparty/chromium/services/audio/service.cc:56
56	   CHECK(!base::SystemMonitor::Get());
```

Not sure if that's related - if you see the same, maybe also check with the other pages you saw this issue on (make sure to quit existing qutebrowser instances and remove the `--temp-basedir` above).

**Comment by martonbalazs** [comment] 2020-09-17 22:26
**Without gdb, from terminal:**

[I] balazs@mizen~> qutebrowser 
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[2405326:16:0917/215229.093357:ERROR:data_channel_controller.cc(405)] channel label not found

_on the login screen, but no crash yet. Then after user/password: nothing on the actual crash, just_

21:56:12 ERROR: Renderer process crashed

_Browser says:_

Unable to load page
Error while opening https://online.lloydsbank.co.uk/personal/primarylogin
Renderer process crashed

**With gdb:**

Yes, it crashes with an error very similar to what you describe on lloydsbank.com, https://myaccount.capitalone.co.uk/login, and https://transferwise.com/login2/ . But it might be related, as

each time in normal Qutebrowser
- I can enter username and password
- I can do some things in Transferwise but not in Lloyds and CapitalOne before "Renderer process crashed".

Each time following your instructions with gdb I got an error like you describe and crash, but until then
- I can enter username and password
- I can do some things in Transferwise but not in Lloyds and CapitalOne before I get the error and crash, but I never saw "Renderer process crashed".

Logs:

gdb_lloyds.txt
[https://pastebin.com/dAsq9BuU](https://pastebin.com/dAsq9BuU)

terminal_lloyds.txt
[https://pastebin.com/cpYifcy0](https://pastebin.com/cpYifcy0)

gdb_capital1.txt
[https://pastebin.com/yeDtdyNU](https://pastebin.com/yeDtdyNU)

terminal_capital1.txt
[https://pastebin.com/KxwbfcZw](https://pastebin.com/KxwbfcZw)

gdb_transferwise.txt
[https://pastebin.com/RGiXLGZZ](https://pastebin.com/RGiXLGZZ)

**Comment by The-Compiler** [comment] 2020-09-18 09:52
Thanks for the detailed information! With the `single-process` flag, the renderer process is part of the main process, so there's no way for qutebrowser to inform you that the renderer process crashes - as the whole thing crashes :wink:

I'd still like to confirm that the crashes without `single-process` are indeed the same. Do you see `QtWebEngineProcess` crashes when you do `coredumpctl list`? If so, can you please show `coredumpctl info PID` with the PID(s) you see in the list after the date/time? Ideally from a crash that happened since you had the debug packages installed.

**Comment by The-Compiler** [comment] 2020-09-18 11:45
Ah, I just got a rendering process crash as well when logging into Google Groups, with the stacktrace pointing to `blink::RTCPeerConnectionHandler::Observer::OnInterestingUsageImpl(int)`. Would be good if you could confirm you're seeing the same.

I've opened two upstream issues:

- [[QTBUG-86752] [REG 5.15.0 -> 5.15.1] Frequent renderer process crashes in blink::RTCPeerConnectionHandler::Observer::OnInterestingUsageImpl - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-86752)
- [[QTBUG-86753] [REG 5.15.0 -> 5.15.1] Failing CHECK in services/audio/service.cc with --single-process - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-86753)

**Comment by martonbalazs** [comment] 2020-09-18 16:17
Yes, Google Groups crashes the same way on original Arch Qutebrowser. However, I couldn't get it to crash after I changed to your qt5-webengine-debug-5.15.1-1-x86_64.pkg.tar.zst . I can still crash lloydsbank as before, here is coredumpctl (running qutebrowser without any option):

https://pastebin.com/mcnJ7qRk

I wonder if this could be related:
https://bbs.archlinux32.org/viewtopic.php?pid=7317 ?

**Comment by The-Compiler** [comment] 2020-09-18 18:03
> I couldn't get it to crash after I changed to your qt5-webengine-debug-5.15.1-1-x86_64.pkg.tar.zst

That's weird. If you do `sudo pacman -S qt5-webengine` to get the original QtWebEngine again, do the crashes come back? If so, can you still show a `coredumpctl info` for such a crash, without debugging symbols?

> I can still crash lloydsbank as before, here is coredumpctl (running qutebrowser without any option): [...]

That confirms it's the same `blink::RTCPeerConnectionHandler::Observer::OnInterestingUsageImpl` I've seen above, which is somewhat reassuring.

> I wonder if this could be related: https://bbs.archlinux32.org/viewtopic.php?pid=7317 ?

I don't think it is. It's 32-bit specific and you'd see the same "**CRASHING**:seccomp-bpf failure in syscall 0403" output if that was the culprit.

**Comment by martonbalazs** [comment] 2020-09-18 20:03
Back on qt5-webengine 5.15.1-1, Google Groups crashes again.

Coredumpctl:

https://pastebin.com/YnZfVxbj

**Comment by martonbalazs** [comment] 2020-09-18 20:13
It's quite random, it crashed twice to give me confidence; I've now tried a few more times and no crashes on Groups. Lloydsbank is still 100% reliable (in crashing). :-)

**Comment by homunkoloss** [comment] 2020-09-21 09:21
I have this issue as well on aliexpress.com
I am also running Arch, the problem exists since the last update a few days ago.

**Comment by The-Compiler** [comment] 2020-09-21 09:40
@homunkoloss I don't have any issues on Aliexpress. I assume this is also the same issue (and nothing qutebrowser can fix), please show a stacktrace if you want to be sure.

**Comment by martonbalazs** [comment] 2020-09-21 20:35
Re #5736 it still seems to be connected to logins/passwords. I wasn't logged in, ebay asked me if I want to continue with Google (where I _was_ logged in), I said no, crash came. But since then "continue with Google" hasn't come up again, and I can search, click on items, do a lot of things in ebay without being logged in and everything looks stable, no crash at all. Maybe it's only when we are logged in somewhere? My banks also only crash after I log in.

**Comment by The-Compiler** [comment] 2020-09-21 20:37
Nope, I can reproduce the crash with `--temp-basedir` and just doing a search on ebay, without logging in.

**Comment by martonbalazs** [comment] 2020-09-21 20:42
You are right, I crashed three times with --temp-basedir and no logins, after which ebay seems stable, no further crashes. Also, terminal gave errors like "[1341063:15:0921/213822.789879:ERROR:stun_port.cc(76)] Binding error response: class=4 number=1 reason=Unauthorized" before crash occurred on the next click.

**Comment by The-Compiler** [comment] 2020-09-23 08:11
FWIW I'd still appreciate if someone had a reliable way to reproduce this which doesn't involve an account I don't have (a Google account is fine). I thought the ebay.com search thing was a reliable reproducer, but it looks like it's not - while it reproduced the issue consistently yesterday, today I have to browse around for a couple of minutes for it to happen.

**Comment by YokaiRick** [comment] 2020-09-24 19:46
mh for me it crashes in ebay nearly on every link rn.
ebay was ne only site for now where i encountered this error.

**Comment by throwaway38924792** [comment] 2020-09-26 17:29
I'm also getting this error in the following pages

- ebay.com (when trying to login)
- bbva.es (on successfull login, if I use a wrong password it doesn't crash)

> I'd still appreciate if someone had a reliable way to reproduce this which doesn't involve an account

NSFW but it crashes anytime a video is opened in xvideos.com

**Comment by NixUnderflow** [comment] 2020-09-29 01:42
I can reproduce this bug reliably on refresh with this document:

```html
<!DOCTYPE html>

<html lang="en">
	<head>
		<title>Should crash on refresh</title>
		<meta charset="UTF-8"/>
	</head>
	<body>
		<p>Should crash on refresh</p>
		<script>
			var rtc = new window.RTCPeerConnection();
			rtc.createDataChannel("");
			rtc.createOffer((description) => {
				rtc.setLocalDescription(description);
			}, (error) => console.error);
		</script>
	</body>
</html>
```

Hope it's helpful.

**Comment by martonbalazs** [comment] 2020-09-29 13:44
Yep, it crashes. How on Earth could you figure this? :-)

**Comment by The-Compiler** [comment] 2020-09-29 16:17
Thanks @NixUnderflow - great job! After starting to bisect the issue, I've noticed that Qt pushed a fix even before I could tell them about the awesome reproducer :slightly_smiling_face: 

Here it is: [[Backport] Fix for bug 1071327 (Icf418990) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/315691)

I've opened an Archlinux bug, so a patched qt5-webengine package should land soon-ish: [FS#68040 : [qt5-webengine] Renderer process crashes related to WebRTC](https://bugs.archlinux.org/task/68040)

Finally, I've made the Debian Qt maintainer aware of it because they're currently in the process of upgrading to Qt 5.15(.1).

My work is done here - nothing more we can do than wait now (and hope for a rather fast Qt 5.15.2 as I won't be able to release updated Windows/macOS releases with Qt 5.15.1 now, and I refuse to build QtWebEngine from sources on those systems as that's an incredible timesink).

Thanks everyone for all the useful information! :+1:

**Closed by The-Compiler** 2020-09-29 16:17 UTC
Labels: bug: segfault/crash/hang, component: QtWebEngine, qt: 5.15

**Comment by The-Compiler** [comment] 2020-09-29 18:06
In an insanely quick move, Antonio Rojas (one of the Archlinux Qt maintainers) already uploaded qt5-webengine 5.15.1-2 containing the fix. :tada:

**Comment by martonbalazs** [comment] 2020-09-29 18:33
That's incredible. Thank you so much for the best browser in the World. :-)

**Comment by amosbird** [comment] 2020-10-08 13:04
@NixUnderflow That's incredible. How did you come up with that document?
