### ISSUE TITLE
Wierd Google search bug

### ISSUE THREAD

**Issue by thokis** [qutebrowser/qutebrowser#3132] opened 2017-10-16 07:02 UTC
Hi,

The qutebrowser version im using is qutebrowser v1.0.1 but it also happens with the default version from pacman. Im using Arch Linux btw. I discovered a wierd bug when using the google.com search. And it only happens when im logged in to my google account. The search field looses the focus immediately after the site is fully loaded. So i cant type in my search string when im hitting "i". After clicking the search field manually with the mouse, insert mode is activated but after about 2 to 5 ticks the search field looses focus again. After i click the search field a last time it stays focuses for infintiy i would say and i can search on google the normal way. Which informations can i provide to help you fixing this bug because this do not happen when using any other browser on my system. Maybe it is caused by an pacman update somehow. Also excuse me for my somewhat poor english it isn't my main language.

**Comment by The-Compiler** [comment] 2017-10-16 07:04
Duplicate of #3124

**Closed by The-Compiler** 2017-10-16 07:04 UTC
