### ISSUE TITLE
Open pdfjs without blank pages

### ISSUE THREAD

**Issue by JingMatrix** [qutebrowser/qutebrowser#6432] opened 2021-04-27 23:13 UTC
If invoke pdfjs with `tabopen`, there will be always a blank new tab for user to close:

https://github.com/qutebrowser/qutebrowser/blob/2599e9bc9796d255ffd4f350bd9aace7fb3893e3/qutebrowser/browser/downloads.py#L901-L902

Hence I suggest use `load_url` function:

```python
        tabbed_browser.load_url(pdfjs.get_main_url(filename, original_url),
                               newtab=False)
```

**Comment by The-Compiler** [comment] 2021-04-28 05:44
Duplicate of #4588

**Closed by The-Compiler** 2021-04-28 05:44 UTC

**Comment by JingMatrix** [comment] 2021-04-28 11:07
Sorry, what is the scene to open an pdf in new tab?

**Comment by The-Compiler** [comment] 2021-04-28 11:08
I don't understand the question. Scene?

**Comment by JingMatrix** [comment] 2021-04-28 12:44
Ah, I meant when do we need to open a  pdf in a new tab? 

I didn't think this situation is really worthy of consideration.

**Comment by The-Compiler** [comment] 2021-04-28 18:56
It is. Lots of people (including myself) open links in new tabs.

**Comment by JingMatrix** [comment] 2021-04-28 19:21
I understand people open links in new tabs.

If I understand correctly your worry, you mean that you want to view pdf in a new tab and don't want original tab destroyed. Am I right?

Then, I can tell you, my solution won't lose your expectation; as a pdf link will always invoke a new tab, and what I do is load_url in that empty tab.

**Comment by The-Compiler** [comment] 2021-04-28 19:42
No, your solution loads the PDF in whatever tab is focused currently.

**Comment by JingMatrix** [comment] 2021-04-28 20:33
Did you ever try it, or just use the model in your mind?

I strongly recommand you give a try if not yet. You may get surprised.

**Comment by The-Compiler** [comment] 2021-04-28 20:41
I did try it indeed.

**Comment by JingMatrix** [comment] 2021-04-28 22:41
Then I don't know. For me everything works as expected.

**Comment by The-Compiler** [comment] 2021-04-28 22:45
Try opening a PDF in a background tab (ctrl-click on duckduckgo with the default settings, other than enabling pdf.js); or opening a PDF which takes a couple of seconds to download and switch tabs.

The only case this would work is the most trivial one, where you open a PDF in a foreground tab and then don't touch anything until it finished downloading.

For any other case, the currently focused tab and the tab the PDF was downloaded in are two different tabs, and opening the PDF in the currently focused one (while still keeping a blank tab open!) is not an acceptable solution.

**Comment by JingMatrix** [comment] 2021-04-29 00:35
Ok, I see. The situation you mentioned is possible for users. I agree people won't be fully satisfied by this solution.

Tough for me, in the situation when I want to have a such a 'background' download, I will wait download for small files and download directly or open with external reader for large files.
