### ISSUE TITLE
Leaving prompt mode focuses first link on some websites

### ISSUE THREAD

**Issue by wasamasa** [qutebrowser/qutebrowser#7885] opened 2023-09-02 22:48 UTC
**Version info**:
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
On some websites, leaving prompt mode (as produced by the JS `prompt` API) ends up focusing the first link and thereby scrolls it into view. This does not happen in Chromium or Falkon.

**How to reproduce**

- `qutebrowser -T 'https://www.x.org/releases/current/doc/xproto/x11protocol.html#requests:GrabServer'`
- Wait for the page to have loaded and "GrabServer" being in focus
- Open developer tools with `:devtools`
- Switch to JS console tab
- Evaluate `prompt('hello?')`
- Choose either prompt option to leave prompt
- The page now has scrolled to the "Acknowledgements" link, which happens to be the first in the document

**Comment by The-Compiler** [comment] 2023-09-13 20:49
This reminds me of #2236 and #4579. `gd` followed by esc seems to be enough to reproduce as well. Or this:

```
qutebrowser --temp-basedir https://github.com/qutebrowser/qutebrowser/issues/7885 ":later 1000 scroll-px 0 100" ":later 1500 download" ":later 2000 mode-leave" 
```

Bisected to 8e152aaa0ac40a5200658d2b283cdf11b9d7ca0d:

>     Don't give keyboard focus to tab bar
>     
>     This partially solves #7820. The web view still loses focus for an unknown
>     reason (apparently when swtiching out the rendering process?), but at least it
>     regains focus now when the window is unfocused and then focused again.

**Comment by The-Compiler** [comment] 2023-12-05 15:18
Events according to GammaRay when closing the dialog with Esc:

![image](https://github.com/qutebrowser/qutebrowser/assets/625793/7ddf9246-372f-48e7-9a96-1f550542966f)

![image](https://github.com/qutebrowser/qutebrowser/assets/625793/4b036044-4174-40dd-a6e0-d927b75dd563)

![image](https://github.com/qutebrowser/qutebrowser/assets/625793/6877092c-92c7-4fc3-827c-5a263d805780)

When using `:cmd-later 2000 mode-leave`, the bug only triggers when the application window still has focus when the mode is left. When the dialog is closed while the qutebrowser window is unfocused, later focusing it does not cause the page to jump.

**Closed** 2023-12-08 14:16 UTC
Labels: priority: 1 - middle, bug: behavior
