### ISSUE TITLE
[feature request idea] function to enter insert mode on text box highlight detection?

### ISSUE THREAD

**Issue by autoteelar** [qutebrowser/qutebrowser#6411] opened 2021-04-19 14:41 UTC
like how when you click on a text box and it enters insert mode, this works fine for most things but some websites like discord or messenger will automatically select and click on it for you, but qutebrowser doesnt enter insert mode automatically so some people (me) dont notice sometimes and just start typing and doing a bunch of random qutebrowser shortcut keys and doing all kinds of unintended things, i feel like this would be a great feature to have to avoid such situations as this one.

**Comment by The-Compiler** [comment] 2021-04-19 14:48
Duplicate of #2471

**Closed by The-Compiler** 2021-04-19 14:48 UTC
