### ISSUE TITLE
Crash on login in several sites

### ISSUE THREAD

**Issue by Aledosim** [qutebrowser/qutebrowser#5423] opened 2020-05-09 20:32 UTC
**Version info**:
qutebrowser v1.11.1
Git commit: e46ae39eb (2020-05-07 18:04:15 +0200)
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.2

**Does the bug happen if you start with `--temp-basedir`?**:
NO

**Description**
Tried to login on Spotify via Facebook and it crashed. After the Spotify crash, runned it with "qutebrowser -R" several times and retried the login on Spotify, tried to access Whatsapp Web and Gmail, all are crashing the browser. The terminal says Segment Faults.
It happened other times. After some use it crashed when I was trying to access WhatsappWeb initially, so I reinstalled with venv in various dirs and still.

**Comment by The-Compiler** [comment] 2020-05-09 20:35
Do the crashes go away if you move the "webengine/Service Worker" directory in qutebrowser's data dir (see `:version`) away?

**Comment by Aledosim** [comment] 2020-05-09 20:41
I've removed all the webengine dir from qutebrowser's data dir and it worked. Needed a fast solution and dont expected your fast answer, sorry. But I know it will happen again since I've done it before. Gonna post more information here then.

**Comment by The-Compiler** [comment] 2020-05-09 20:43
Probably a duplicate of #5279 then.

**Closed by The-Compiler** 2020-05-09 20:43 UTC
Labels: status: needs triage
