### ISSUE TITLE
Hints stay put after scrolling the page with the mouse

### ISSUE THREAD

**Issue by robcsi** [qutebrowser/qutebrowser#3164] opened 2017-10-19 08:34 UTC
![image](https://user-images.githubusercontent.com/5070886/31761549-ef15d81e-b4c0-11e7-8ad1-e438c33171a0.png)

Steps to reproduce:
1. https://vimawesome.com/plugin/ale - open page
2. f - lots of hints appear
3. scroll down with the mouse
4. hints appearing on the right, the few ones, stay in place, they are not scrolled up with the page (doesn't happen with Vimium/Chrome)

:ver -> qutebrowser v1.0.2
Git commit: v1.0.2 (2017-10-17 07:44:14 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)
...
Qt: 5.9.1
PyQt: 5.9
...
Platform: Windows-7-6.1.7601-SP1, 64bit

**Comment by The-Compiler** [comment] 2017-10-19 08:35
Duplicate of #1928

**Closed by The-Compiler** 2017-10-19 08:35 UTC
