### ISSUE TITLE
Enable URL pattern for downloads.location.directory

### ISSUE THREAD

**Issue by maxigit** [qutebrowser/qutebrowser#5650] opened 2020-08-06 08:55 UTC
I switched recently to Qutebrowser and so far I'm very impressed and really pleased with it. Over the past few years I've tried all vim like firefox alternavite (from Vimperator to pentadactly to vimfox etc) all either stopping to work or not being quite exactly what I wanted. Qutebrowser seems to be nicest "vim" experience so far. However, I am missing a simple feature (which I could get before with a FF plugin) : choose a different download location depending on the URL. I download lots of things for work (like bank statements, each statment go in a different folder depending on the bank, payroll -> payroll directory , invoices -> per supplier directory etc ...).
It looks like settings the `downloads.location.directory` with a url pattern will work (even though a bit cumbersome to set up , but that will do). However when I try it. I got an error message saying that url pattern are not allowed for this settings.
I try modifying the code by adding `supports_pattern: true` in `config/configdata.yml` and it seems to be working. Is there a reason why pattern are not supported for this options and even why pattern is not supported for ALL options ? If not maybe the default should set to true instead of false.

**Comment by The-Compiler** [comment] 2020-08-06 09:01
Duplicate of #3636.

As for:

> I try modifying the code by adding `supports_pattern: true` in `config/configdata.yml` and it seems to be working. Is there a reason why pattern are not supported for this options and even why pattern is not supported for ALL options ? If not maybe the default should set to true instead of false.

That definitely won't work. The code getting the download directory needs to pass the relevant URL for patterns to work.

**Closed by The-Compiler** 2020-08-06 09:01 UTC

**Comment by maxigit** [comment] 2020-08-06 09:33
I thought it was working, but you are right it doesn't. Thank you for your quick answer.
