### ISSUE TITLE
args not respected by ipc interface?

### ISSUE THREAD

**Issue by xalexalex** [qutebrowser/qutebrowser#7130] opened 2022-04-18 10:04 UTC
**Version info**:
qutebrowser v2.5.0
Git commit: 
Backend: QtWebEngine 5.15.9, based on Chromium 87.0.4280.144
Qt: 5.15.3 (compiled 5.15.2)

**Does the bug happen if you start with `--temp-basedir`?**
yes

**Description**
using the [open_url_in_instance](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/open_url_in_instance.sh) script, if I try to pass arguments, as for example `--untrusted-args` as is default with the qutebrowser.desktop file, qutebrowser instead opens "--untrusted-args" as an URL and ignores the remaining arguments, i.e. the actual URL

**How to reproduce**
```
qutebrowser &
curl -LO https://raw.githubusercontent.com/qutebrowser/experiments/master/scripts/open_url_in_instance.sh
sleep 2
bash open_url_in_instance.sh --untrusted-args duck.com
```

Expected behavior: open url `duck.com`
Actual behavior: open url `--untrusted-args`

**Comment by xalexalex** [comment] 2022-04-18 10:13
Some fault was due to the open_url_in_instance script that does `_url="$1"`  ignoring other arguments. However, even sending a well-formed json to the ipc socket, such as
`{"args": ["--untrusted-args","duck.com"], "target_arg": null, "version": "2.5.0", "protocol_version": 1, "cwd": "/home/al"}`
still reproduces the bug. Two tabs are opened, one for `--untrusted-args` and one for `duck.com`.

**Comment by The-Compiler** [comment] 2022-04-18 10:52
Duplicate of #6787

**Closed** 2022-04-18 10:52 UTC
