### ISSUE TITLE
Make bookmarks sortable

### ISSUE THREAD

**Issue by merspieler** [qutebrowser/qutebrowser#3088] opened 2017-10-11 17:35 UTC
It would be really helpful, especially with a large amount of bookmarks, if I would be able to sort the bookmarks in a directory like structure.

**Comment by The-Compiler** [comment] 2017-10-11 17:38
Closing this as duplicate of #882 because there's a lot of discussion about subfolders there already. You can use quickmarks and give them names like `foo/bar` though.

**Closed by The-Compiler** 2017-10-11 17:38 UTC
