### ISSUE TITLE
Setting to have tab "pane" NOT resize the website

### ISSUE THREAD

**Issue by linkert** [qutebrowser/qutebrowser#5748] opened 2020-09-28 17:31 UTC
Not sure if it's just a case of my brain being tired but I'm having a hard time expressing this functionallity. 

I have my tabs hidden, showing when switching tabs - off to the right side of my browser window. Everytime I switch tab it resizes the site being displayed for the 800 miliseconds the tab pane is being displayed (20% less width). Is there a setting to configure that would make it so that the tab pane would work similar to the "command" pane which does not resize the website "area". 

I guess tab panel overlapping is what I'm looking for.

![qutebrowser-tabs-pushing](https://user-images.githubusercontent.com/44402757/94466046-18b89d00-01c1-11eb-8977-950cffc28b9e.gif)
(amazing blur effect added by picom <3 )

**Comment by The-Compiler** [comment] 2020-09-28 17:35
Duplicate of #1593

**Closed by The-Compiler** 2020-09-28 17:35 UTC
