### ISSUE TITLE
Frequent ERR_NETWORK_CHANGED errors while browsing 

### ISSUE THREAD

**Issue by acaloiaro** [qutebrowser/qutebrowser#6356] opened 2021-04-04 22:27 UTC
Hi all, I'd like to report my experience using `qutebrowser`. I've been using it for quite some time and love it, however on Ubuntu 20 (Regolith Linux), it's becoming quite unusable. 

I'm not convinced the problem is with `qutebrowser` specifically, as I'm aware of others running `qutebrowser` on similar hardware on Ubuntu 20 (Regolith Linux) without a hitch. 

What I'm experiencing is the following: 

1. I browse to a page and the page load fails completely 
2. In debug mode, the message appears as follows:

> 16:15:13 ERROR    webview    webenginetab:_error_page_workaround:1482 Load error: ERR_NETWORK_CHANGED

While the message suggests network instability -- my network is stable and `qutebrowser` is the only application that experiences any network issues. Roughly 50% of page loads suffer from this affliction. 

Both `1.x` and `2.x` versions of qutebrowser are affected. Version info here:
[1.14.1](https://paste.the-compiler.org/view/e07bbb95)
[2.1.1](https://paste.the-compiler.org/view/cf60f153) 

I'm happy to provide any additional information that might get to the bottom of this issue.  

Cheers

**Comment by The-Compiler** [comment] 2021-04-05 10:23
Those errors are coming from the underlying Chromium, so there's likely little that qutebrowser can do about it.

I assume the issue happens with `--temp-basedir` as well? Could you try with [KDE Falkon](
https://www.falkon.org/) and/or Chromium too (ideally both)?

**Comment by acaloiaro** [comment] 2021-04-05 15:09
Thanks @The-Compiler -- I'll get that tested soon and report back.

**Comment by acaloiaro** [comment] 2021-04-09 14:40
@The-Compiler I've confirmed the following

1. `--temp-basedir` does not alleviate the issue 
2. Chromium does not have the same issue 
3. KDE Falkon _does_ have the same issue

**Comment by The-Compiler** [comment] 2021-04-09 14:41
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2021-04-09 14:41 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by vikasrawal** [comment] 2022-04-23 01:29
I wonder if this was reported to Qt Bug Tracker, and if there has been any progress? I do not see anything.
