### ISSUE TITLE
Unknown protocols and webengine

### ISSUE THREAD

**Issue by dschrempf** [qutebrowser/qutebrowser#3082] opened 2017-10-11 12:35 UTC
Thank you very much for developing this project!

I noticed that unknown protocols such as magnet links are not handled when using `--backend webengine` (see also #210).

Version:
qutebrowser v0.11.0
Git commit: 
Backend: QtWebKit-NG (WebKit 602.1)

CPython: 3.6.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: no
typing: yes
OpenGL: 3.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
SSL: OpenSSL 1.0.2l  25 May 2017

Style: Qt5CTProxyStyle
Platform: Linux-4.13.5-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
config: /home/dominik/.config/qutebrowser
data: /home/dominik/.local/share/qutebrowser
system_data: /usr/share/qutebrowser
cache: /home/dominik/.cache/qutebrowser
download: /home/dominik/Downloads
runtime: /run/user/1000/qutebrowser

**Comment by The-Compiler** [comment] 2017-10-11 12:38
Duplicate of #2833

**Closed by The-Compiler** 2017-10-11 12:38 UTC
