### ISSUE TITLE
Completion window moves horizontally

### ISSUE THREAD

**Issue by Al-Caveman** [qutebrowser/qutebrowser#3359] opened 2017-12-04 04:55 UTC
How to reproduce:

  - Open any page.
  - Press o (to show the completion window).
  - Pan left/right, you will see it shakes (bad).

How to not reproduce:

  - Open any page.
  - Press :.
  - Pan left/right, you will see it not shaking (good).

qutebrowser v1.0.4
Git commit: a137a29cc (2017-12-03 22:32:17 +0100)
Backend: QtWebEngine (Chromium 56.0.2924.122)
CPython: 3.6.3
Qt: 5.9.3
PyQt: 5.9.2

**Comment by The-Compiler** [comment] 2017-12-04 05:17
What do you mean with "pan left/right"? Can you reproduce this when starting with `--temp-basedir` (and than visiting some websites to get history entries)?

**Comment by Al-Caveman** [comment] 2017-12-04 22:13
"pan left/right" means: use the mouse pad gesture to navigate the completion menu. When using such gesture, you can move vertically, or horizontally. The ``pan left/right'' is the horizontal one. (I think also identical to: scroll your horizontal mouse wheel)

As for reproducing with `--temp-dirbase`, could I reproduce? The answer is "no". But it is tricky, because I can't even reproduce it now *without* `--temp-dirbase` ever since I deleted my history by `history-clear`.

So it seems that there is some kind of nastiness that needs to be in the completion menu in order to allow for the horizontal panning.

**Comment by The-Compiler** [comment] 2017-12-05 12:21
I just reviewed the related code and it seems fine to me. If you can reproduce this again, please re-open this - until then, there's little we can do.

**Comment by Al-Caveman** [comment] 2017-12-05 20:14
I reproduced it with ``--temp-basedir`` as follows:

  1. `open -t ddg test #i`
  2. Increment i += 1.
  3. Go to step 1. Stop condition: if completion buffer is long enough to show a side scrollbar.
  4. Press o. Close buffer.
  5. Press o (again). This time pan the completion buffer horizontally. You will see it moving horizontally -- bug reproduced.

**Comment by The-Compiler** [comment] 2017-12-05 20:18
I was able to reproduce that.

**Comment by rcorre** [comment] 2017-12-06 13:06
Can't repro on my end, probably because I can't figure out how to horizontally pan the completion buffer. I don't have a horizontal mouse wheel and swiping left/right on my laptop's touchpad did nothing

**Comment by Al-Caveman** [comment] 2017-12-08 03:32
Not sure what is swiping is. To be specific, here is how I have page panning configured in Xorg (no need for horizontal mouse wheel):

    Section "InputClass"
        Identifier  "touchpad"
        Driver      "synaptics"
        Option      "VertScrollDelta"          "-111"
        Option      "HorizScrollDelta"         "-111"
        MatchIsTouchpad "on"
            Option "TapButton1" "1"
            Option "TapButton2" "2"
            Option "TapButton3" "3"
            Option "VertTwoFingerScroll" "on"
            Option "HorizTwoFingerScroll" "on"
            Option "CircularScrolling" "on"
            Option "FingerLow" "30"
            Option "FingerHigh" "50"
            Option "MaxTapTime" "125"
    EndSection

With that config, I can pan in any direction as follows:

  1. I put two fingers on the touch pad.
  2. Move the two fingers around in any direction.
  3. When I open/close the completion buffer numerous times (2 I found is enugh), I find it to also pan horizontally.

**Comment by rcorre** [comment] 2017-12-08 12:40
I tried your xorg config, and while I can pan horizontally on a page (this one, if I zoom in), I can't horizontally pan the completion buffer (even after closing/opening multiple times).

**Comment by The-Compiler** [comment] 2017-12-08 15:28
FWIW I haven't been able to reproduce this in my usual instance, but I could reproduce it with the instructions [above](https://github.com/qutebrowser/qutebrowser/issues/3359#issuecomment-349427143) (i.e. `--temp-basedir`, opening duckduckgo, and hitting `ctrl-a` / `gC` a few times until the completion was filled).

**Comment by Al-Caveman** [comment] 2017-12-11 16:40
@rcorre, just to verify: Did you do it with these:

  - Enough history in completion buffer to make qb show a scrollbar for the completion buffer.
  - Completion buffer is shown by pressing `o` (not `:`).

?

Ty.

**Comment by rcorre** [comment] 2017-12-13 01:54
Got it. I eventually managed to make my completion window jiggle back and forth. What a bizarre issue. It really does seem to only happen after the completion has been opened more than once in a session. What's more, it doesn't seem to happen if there is a quickmarks section, so we never would have seen this before #3279.

**Closed** 2017-12-14 08:40 UTC
Labels: bug: behavior, component: completion, component: ui, priority: 2 - low
