### ISSUE TITLE
Appimage

### ISSUE THREAD

**Issue by danrobi11** [qutebrowser/qutebrowser#5418] opened 2020-05-07 16:17 UTC
Hello
Appimage would be nice.
Is it the qute team that are maintaining the flatpak? 
Thank you very much for qutebrowser :+1:

**Comment by The-Compiler** [comment] 2020-05-07 16:18
Duplicate of #1912

**Comment by The-Compiler** [comment] 2020-05-07 16:18
And nope - only releases at https://github.com/qutebrowser/qutebrowser/releases are "official".

**Closed by The-Compiler** 2020-05-07 16:18 UTC
