### ISSUE TITLE
Mouse cursor remains hidden even after pointer locking tab/window is closed

### ISSUE THREAD

**Issue by sid-code** [qutebrowser/qutebrowser#5306] opened 2020-03-25 21:18 UTC
**Version info**:

qutebrowser v1.10.1
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)
Qt: 5.14.1

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
If a web page locks the pointer and is closed without releasing it, the pointer remains hidden in every tab/window until qutebrowser is restarted.

**How to reproduce**
1) Visit any website with pointer locking (example: https://devanbuggay.com/bspview/)
2) Close the window/tab without unlocking the pointer

Now the mouse will be hidden until qutebrowser restarts.

**Comment by The-Compiler** [comment] 2020-03-26 08:16
Duplicate of #4571

**Closed by The-Compiler** 2020-03-26 08:16 UTC
