### ISSUE TITLE
Cache last fired hint for ease of access

### ISSUE THREAD

**Issue by christophergeiger3** [qutebrowser/qutebrowser#4372] opened 2018-10-22 01:03 UTC
It would be nice if after firing a hint to navigate to another page, any link containing the same text on the following page would be marked with the same label as before.

For example, if I were navigating between issues on github, and I fired the label `gk` for  `next page`, then on the following page, if I were to fire a hint for `next page` again, the label should also appear as `gk`.

To go even further with this idea, a priority queue system for hint labels could be implemented (instead of random generation), so that easier to type labels (e.g. `fff` or `ggg`) would be assigned to links that are frequently followed (such as `next`, `previous`, `search`, `submit`, `go`, etc).

**Comment by mschilli87** [comment] 2018-10-22 07:06
duplicate of https://github.com/qutebrowser/qutebrowser/issues/4373

**Comment by toofar** [comment] 2018-10-22 11:17
I think guessing which link should get an easy hint would be a lot of maintanance for little return. But using a per-tab per-origin record of previously used hints to opportunistically re-apply the same hints to the same link texts could have a lot lower implementation burdon. And it could be nice while monotonously paging through a site with a variable number of links on each page.

**Comment by user202729** [comment] 2018-10-22 14:11
Currently qutebrowser has `[[` and `]]` which recognizes some prev/next links, but unfortunately not github's.

**Comment by jgkamat** [comment] 2018-10-22 17:10
user202729 writes:

> Currently qutebrowser has [[ and ]] which recognizes some prev/next links, but unfortunately not github's.

hmm, it seems to work for me fine on github issues at least.

I'm pasting the conversation that happened during the github outage below:

Right now, (I think) the elements are sent back to python, where they are
counted, and hints are generated based on the number of hint keys and
elements. Since we have access to the elements in python, I don't think
there's anything blocking this from happening. However, we would need to start
to store hinting history and find some algorithm for ranking things by
frequency, which wouldn't be trivial. Since the elements may not be exactly
the same, we would also need a way to treat similar elements as 'equal' as
well.

I think there might be an issue for trying to sort hints by 'most likely to be
useful' as well.

The code for this is in qutebrowser/browser/hints.py:418 in case your curious.

Maybe adding custom mapping functions (from a list of elements to a list of
hints) could be something that is added to the plugin api. Because this seems
pretty complex, it's probably something that won't get worked on unless it's
an external contribution (or a plugin).

-Jay

Christopher Geiger writes:

> Oh, what I was suggesting was a change in functionality, like instead of
> generating the hint labels sequentially, they should be generated based on
> past usage. Like you said though, this may not be feasible.
>

**Comment by christophergeiger3** [comment] 2018-10-22 23:05
For me the `[[` and `]]` keys work on github issues as well. I still feel that repeating a hint label value may be useful for repeating an action on a page or between pages (but now that I know `]]` exists, may not be as useful...)

**Comment by user202729** [comment] 2018-10-23 00:16
Somehow it works now, probably because github recently changed the pages.

**Comment by The-Compiler** [comment] 2018-10-23 18:12
#674 explores some quite similar ideas, so I'm going to merge this there.

**Closed by The-Compiler** 2018-10-23 18:12 UTC
