### ISSUE TITLE
Wanikani Niai Similar Kanji called unimplemented GM_getResourceText

### ISSUE THREAD

**Issue by ma9e** [qutebrowser/qutebrowser#3975] opened 2018-06-04 01:43 UTC
```
qutebrowser v1.3.1
Git commit: 5e99da545 (2018-05-30 11:59:34 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.151)
```
```
20:39:26 DEBUG    js         shared:javascript_log_message:146 [userscript:GM-Wanikani Niai Similar Kanji:113] Wanikani Niai Similar Kanji called unimplemented GM_getResourceText
20:39:26 DEBUG    js         shared:javascript_log_message:146 [https://www.wanikani.com/kanji/%E5%B0%8F:1] Uncaught SyntaxError: Unexpected token u in JSON
at position 0
```

**Comment by toofar** [comment] 2018-06-04 05:01
Yes that is indeed not implemented. Gosh, that script is all metadata.
Not gonna lie, I'm not terrible motivated to implement it because no-one else has asked for it yet (and I'm working on other stuff). On a scale of one to ten how pissed of does this script not working make you?

Note to self:
* Support picking up resource directives
* Make `_get_required_scripts` also handle queuing them for download (probably change the requires folder to resources). Just save them to files with the sanitized URL so we don't have to worry about duplicates and do the normalising again at compile time to match the labels. Can't handle relative links until an installer is in.
* Refactor `_add_script_with_requires` to also handle pulling resource blobs into variables with the label names
* getResourceUrl can just scrape the script meta for now, if we ever handle resolving relative links at install time we'll have to either write a map of labels to URLs somewhere or just save a base URL (or use `downloadURL`?).

**Comment by The-Compiler** [comment] 2018-06-11 09:16
Merging this into #3238 as we already track other missing GreaseMonkey features there.

I assume [this is the script](https://github.com/mwil/wanikani-userscripts/blob/master/wanikani-similar-kanji/wk_niai.user.js) in question?

**Comment by The-Compiler** [comment] 2018-06-11 09:16
Duplicate of #3238

**Closed by The-Compiler** 2018-06-11 09:16 UTC
