### ISSUE TITLE
Completion list items not redrawn under Wayland/Sway

### ISSUE THREAD

**Issue by bitraid** [qutebrowser/qutebrowser#3288] opened 2017-11-14 07:57 UTC
I've noticed this happening after 23716f121, when running under Wayland/Sway (using XWayland or not):
Completion list items are not automaticly redrawn as i type, unless i change the window size or switch to/from full screen.

---

edited by @the-compiler to remove the backticks so I can click the commit ID :wink:

**Comment by The-Compiler** [comment] 2017-11-14 08:06
That's weird... @rcorre do you have an idea why that happens?

**Comment by The-Compiler** [comment] 2017-11-14 09:24
Actually, this seems like an exact duplicate of #3016. Until we find a way to fix that without causing a performance regression, I'd propose reverting 23716f1212744878d345a81a4f9ccb65ab57605a.

**Comment by rcorre** [comment] 2017-11-14 12:28
Ah crap, you're right. Let's revert it

**Comment by The-Compiler** [comment] 2017-11-14 12:32
Done!

**Closed** 2017-11-14 12:31 UTC
