### ISSUE TITLE
Escape key doesn't close context menus, which is very unconvenient

### ISSUE THREAD

**Issue by ringeringeraja** [qutebrowser/qutebrowser#6542] opened 2021-06-11 21:29 UTC
**Version info**:

qutebrowser v2.2.3
Git commit: 
Backend: QtWebEngine 5.15.4, Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
-

**How to reproduce**

open a context menu, then try to close it with keyboard

**Comment by The-Compiler** [comment] 2021-06-11 21:57
Duplicate of #6129

**Closed by The-Compiler** 2021-06-11 21:57 UTC
