### ISSUE TITLE
Context Menu and Tooltips Don't Disappear

### ISSUE THREAD

**Issue by tedster-08** [qutebrowser/qutebrowser#7022] opened 2022-02-13 19:30 UTC
**Version info**:
qutebrowser v2.4.0
Git commit: 36ffff2f6 on HEAD (2021-10-21 18:50:06 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Misc. System Info**:
OS: macOS Monterey 12.2.1
Computer: 2020 M1 Mac Mini
Window Manager: Yabai

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
Tooltips for some elements remain on mouse leaving, as well as the right click context menu. 

![Screen Shot 2022-02-13 at 2 28 57 PM](https://user-images.githubusercontent.com/75181949/153771392-71c19037-f180-4927-bd00-740fbc944ef4.png)

**How to reproduce**
Right clicking to bring up a context menu successfully brings it up, but it doesn't go away. Tooltips also sometimes don't disappear correctly (I've noticed this seems to be most prevalent on Youtube, especially with the Youtube home button.)

**Comment by The-Compiler** [comment] 2022-02-13 19:53
What OS/system is this on?

**Comment by tedster-08** [comment] 2022-02-13 22:20
I added a Misc. Info section, let me know if you need anything else!

**Comment by The-Compiler** [comment] 2022-02-13 22:27
Duplicate of #6833

**Closed by The-Compiler** 2022-02-13 22:27 UTC
Labels: status: can't reproduce, status: needs triage
