### ISSUE TITLE
When opening afresh on MacOS, there seems to be no way to only get the site asked for

### ISSUE THREAD

**Issue by andrewferrier** [qutebrowser/qutebrowser#5350] opened 2020-04-12 14:29 UTC
**Version info**:
qutebrowser v1.8.3
Git commit: bf410fd13 (2019-12-05 16:29:08 +0100)
Backend: QtWebEngine (Chromium 69.0.3497.128)

**Does the bug happen if you start with `--temp-basedir`?**:
Yes, but I'm not convinced I'm using `--temp-basedir` correctly. On MacOS, extra arguments (I think) need to be passed like this: `open -a qutebrowser http://www.google.com/ --args --temp-basedir /tmp`. But this seems to open up two tabs: `file:///tmp` and Google, whereas I assume I didn't/shouldn't see the `/tmp` one.

**Description**
On MacOS, many applications will open up a website using (or the equivalent of) `open -a qutebrowser http://www.google.com`. However, when I do this, I get *two* tabs, the second for Google, and the first for DuckDuckGo, which is set in `url.start_pages`. The problem is, in this circumstance, I want to go to Google (or whichever site is specified); I don't need my Start page; I think it should be left only for when I haven't specified another site. However, I cannot set `url.start_pages` to "empty"; I've tried a zero-length string, and `[]`, and the configuration UI will not allow either.

**How to reproduce**
1. Install above qutebrowser version on MacOS.
2. Open a terminal, and run `open -a qutebrowser http://www.google.com`.

**Comment by andrewferrier** [comment] 2020-04-12 14:29
I should note additionally that this *only* happens if qutebrowser is not already open. If it is, I only get the additional tab asked for, which is what I would expect.

**Comment by andrewferrier** [comment] 2020-04-12 14:30
And thanks for all your great work on this amazing browser :)

**Comment by The-Compiler** [comment] 2020-04-13 13:36
Duplicate of #3081

**Closed by The-Compiler** 2020-04-13 13:36 UTC

**Comment by andrewferrier** [comment] 2020-04-13 13:45
Thanks, and sorry for the dup.

**Comment by The-Compiler** [comment] 2020-04-13 14:07
No worries, it happens!
