### ISSUE TITLE
Touchpad scroll sporadic failures

### ISSUE THREAD

**Issue by moorchegue** [qutebrowser/qutebrowser#4347] opened 2018-10-17 03:57 UTC
**Version info (see `:version`)**: 1.5.1-1 (since at least 1.1.1-1):

qutebrowser v1.5.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.2
PyQt: 5.11.3

sip: 4.19.13
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.25.2
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.12-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Description**
Sometimes two-finger scroll suddenly stops working. There's no error messages, everything else including hjkl keys seems to work normally. The scope of the problem is a tab, the rest of the open tabs aren't affected. The only way to get the touchpad scroll back seems to be closing and reopening the tab.

**How to reproduce**
This happens relatively rarely (less often than once a day), and I don't have a sense of what factors are involved and how to reproduce it. Maybe somebody else does? Or have any pro-tips of what I could do to gather more info when it happens?

I also don't know if it's the same with a regular mouse and not a touchpad.

**Comment by jgkamat** [comment] 2018-10-17 04:07
Maybe this is related to https://github.com/qutebrowser/qutebrowser/issues/3939. On 5.11, I'm very occasionally seeing failures in focusing the webview.

You can get more information about how focus is behaving by starting with `--debug --logfilter misc`

**Comment by The-Compiler** [comment] 2018-10-17 04:15
Just to confirm - clicking some empty part of the page doesn't change anything?

**Comment by moorchegue** [comment] 2018-10-17 04:17
@The-Compiler, yeah, no, it doesn't. Nothing I've tried helps except closing the tab.

@jgkamat, thanks for the hint, I'll try running it in a debug mode and see if I can catch anything related.

**Comment by moorchegue** [comment] 2018-10-17 08:48
Okay, have a tab open with broken scroll right now. Here's what I'm with --debug enabled when I try to scroll:
```
16:44:57 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7ffa66e05b88>
16:44:57 DEBUG    modes      modeman:_handle_keyrelease:219 filter: False                                                                               
16:44:58 DEBUG    modes      modeman:_handle_keypress:172 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:44:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Got key: 0x1000022 / modifiers: 0x10000000 / text: '<Meta>' / dry_run True                     
16:44:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Ignoring, only modifier                                                                        
16:44:58 DEBUG    modes      modeman:_handle_keypress:199 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: True --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7ffa66e05b88>)
16:44:58 DEBUG    modes      modeman:_handle_keypress:172 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:44:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Got key: 0x1000022 / modifiers: 0x10000000 / text: '<Meta>' / dry_run True                     
16:44:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Ignoring, only modifier                                                                        
16:44:58 DEBUG    modes      modeman:_handle_keypress:199 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: True --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7ffa66e05b88>)
16:44:58 DEBUG    modes      modeman:_handle_keypress:172 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
16:44:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Got key: 0x1000022 / modifiers: 0x10000000 / text: '<Meta>' / dry_run False                    
16:44:58 DEBUG    keyboard   basekeyparser:_debug_log:91 Ignoring, only modifier                                                                        
16:44:58 DEBUG    modes      modeman:_handle_keypress:199 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: False --> filter: False (focused: <PyQt5.QtWidgets.QWidget object at 0x7ffa66e05b88>)
16:44:58 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None                                                                 
```

Not sure if it's helpful, because seemingly the same happens when scrolling works normally. Let me know if there's anything else I can do to debug this while I have a faulty tab open.

**Comment by LiteracyFanatic** [comment] 2020-01-06 20:12
I started having the same issue with qutebrowser a few weeks ago. It can be resolved by reloading the tab, changing to another tab and then back to the original tab, or by focusing another window and then switching back to qutebrowser. I'm on Arch Linux. I've tested v1.8.1-v1.8.3, and the issue is still present, so I don't think it is appearing for me as a result of any recent code changes in qutebrowser itself. Could this be related to an update in QT5 or one of the python libraries?

qutebrowser v1.8.3
Git commit: 
Backend: QtWebEngine (Chromium 77.0.3865.129)

CPython: 3.8.1
Qt: 5.14.0
PyQt: 5.14.0

sip: 5.0.1
colorama: 0.4.3
pypeg2: 2.15
jinja2: 2.10.3
pygments: 2.5.2
yaml: 5.1.2
cssutils: no
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.14.0
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.30.1
QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

Style: QFusionStyle
Platform: Linux-5.5.0-rc1-drm-tip-git-g5f07735eaf4b-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/jordan/.cache/qutebrowser
config: /home/jordan/.config/qutebrowser
data: /home/jordan/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/jordan/.config/qutebrowser/config.py has been loaded
Uptime: 14:17:38

**Comment by moorchegue** [comment] 2020-01-07 03:16
Interestingly enough, there's no longer such issue with my qutebrowser. At least I don't remember experiencing it for many months now. Current version is also 1.8.3.

**Comment by The-Compiler** [comment] 2020-01-07 08:35
I'm pretty sure the only thing influencing this is the Qt version. @LiteracyFanatic how often does it happen? Do you have a consistent way to reproduce?

**Comment by LiteracyFanatic** [comment] 2020-01-08 07:35
It's happening ~5 times a day. I just browse normally and eventually one of my tabs stops scrolling. It seems to be pretty random. I thought it might have to do with my libinput touchpad configuration so I tested without it but the bug persisted. I will investigate further and see if I can reproduce it on another machine with a minimal installation.

**Comment by The-Compiler** [comment] 2020-01-08 08:20
Can you try using [KDE Falkon](https://www.falkon.org/) for a day and see if it happens there as well?

**Comment by LiteracyFanatic** [comment] 2020-01-08 08:25
Sure thing.

**Comment by LiteracyFanatic** [comment] 2020-01-09 02:45
The same thing happens in Falkon. Only difference is that switching tabs doesn't fix the problem; you have to focus another application.

**Comment by The-Compiler** [comment] 2020-01-09 09:33
Seems like a bug in QtWebEngine then, I assume you can't reproduce in Chromium?

I'm guessing this started happening for you in Qt 5.14 which was added to Arch relatively recently. I don't know why it happens to you and not to others though - I'd recommend opening a [Qt Bug report](https://bugreports.qt.io/secure/Dashboard.jspa).

Closing this now as I don't think there's anything qutebrowser can do about this.

**Closed by The-Compiler** 2020-01-09 09:33 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by LiteracyFanatic** [comment] 2020-01-09 10:40
Yeah, it doesn't happen with Chromium. Thanks for your help. I'll open a bug with Qt.

**Comment by moorchegue** [comment] 2024-05-31 03:02
Started happening again with v3.1.0. This time all tabs lose scrolling with trackpad (hjkl-scroll continues to work) at the same time.

**Comment by moorchegue** [comment] 2024-09-04 04:14
Seems to be related to either mesa or opengl version. Back in May I was able to downgrade to some lower versions and that made this go away, but recently too many packages depended on latest versions. So the scroll issue is back with vengeance.
