### ISSUE TITLE
Unbinding a key multiple times toggles between unbound and it's default

### ISSUE THREAD

**Issue by pkillnine** [qutebrowser/qutebrowser#3192] opened 2017-10-24 21:08 UTC
e.g. run `:unbind d` and d is unbound, then run it again and d is bound to `tab-close` again.

This is especially noticeable when using `config-edit`.

**Comment by The-Compiler** [comment] 2017-10-24 21:16
Duplicate of #3162

**Closed by The-Compiler** 2017-10-24 21:16 UTC
