### ISSUE TITLE
document.hidden is some time wrong ?!

### ISSUE THREAD

**Issue by coucougael94** [qutebrowser/qutebrowser#5422] opened 2020-05-08 23:50 UTC
Hello, i build Greasemonkey script that require this JS information : 
`document.hidden //= document.visibilityState but same issue`
So, my script has to know if himself tab is the current browsing tab.
But my script seems to have incorrect supplied values ?!
**How to reproduce**
I share you a little page script for this issue (i hope you can see like me what is strange) :
[http://projetdnb.chez.com/2.html](http://projetdnb.chez.com/2.html)
To get the problem : Click on the link in a new tab (F or middle mouse btn) but wait 1 or 2 seconds before activating the tab.

**My results**
I got this (wrong) values : 
> "visible"             // Expected : "hidden"
> "visible"             // Bad
> "visible"             // Bad
> "visible"             // when i go on the tab (Good value)
> "visible"             // Good value
> "hidden"            // when i go on other tab (Good value)
> ...

(In the console input you can see the answer of document.hidden (← Same bug, but bool))

**My research**
Searching for something relative to visible property , i found in the QWebEnginePage docs:
[https://doc.qt.io/qt-5/qwebenginepage.html#visible-prop](https://doc.qt.io/qt-5/qwebenginepage.html#visible-prop)

> This property was introduced in Qt 5.14.

My :version :
```
Qt: 5.14.2
PyQt: 5.14.2
```
**Finally**
My question is : i'm the only one with this bad qutebrowser ?

Thanks to qutebrowser for this project (I don't know if emacs>vim but qutebrowser rocks :)
(Maybe i've incomprehensible english, not my BirthLang :)

**Comment by toofar** [comment] 2020-05-09 00:16
It can be be wrong is some cases, we open "background" tabs as visible. What is your `tabs.background` setting set to? I wrote some stuff about it on here https://github.com/qutebrowser/qutebrowser/issues/4881 but 5.14 wasn't out at that point. Does it work better if you open the tabs in the foreground first? Or could you script work if it ignored the value until it had changed once?

**Comment by coucougael94** [comment] 2020-05-09 16:25
great!

**Comment by The-Compiler** [comment] 2020-05-14 11:23
Duplicate of #3366

**Closed by The-Compiler** 2020-05-14 11:23 UTC
