### ISSUE TITLE
Indicator text to signal if option is on or off?

### ISSUE THREAD

**Issue by tamis-laan** [qutebrowser/qutebrowser#5881] opened 2020-11-10 15:35 UTC
So I have a binding to toggle my proxy on or of i.e.
`config.bind('xp', 'config-cycle content.proxy system ****************')`
However there is no signal to the user the proxy is enabled or disabled. It would be nice If I could put some text in the status bar signalling that the proxy is on or off.

**Comment by The-Compiler** [comment] 2020-11-10 15:36
Duplicate of #1052

**Closed by The-Compiler** 2020-11-10 15:36 UTC
