### ISSUE TITLE
Can't use Whatsapp - chromium too old!

### ISSUE THREAD

**Issue by XaheenA** [qutebrowser/qutebrowser#4860] opened 2019-06-22 08:47 UTC
**Version info (see `:version`)**:
qutebrowser **v1.6.1**
Backend: _**QtWebEngine (Chromium 56.0.2924.122)**_
CPython: 3.6.8
Qt: 5.9.5
PyQt: 5.10.1
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.5.188 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018
Style: QFusionStyle
Platform: Linux-4.15.0-52-generic-x86_64-with-Ubuntu-18.04-bionic, 64bit
Linux distribution: **Ubuntu 18.04.2 LTS**
Frozen: False

**Description**

I have installed qutebrowser form the deb package on ubuntu 18.04. Everything works fine but the Chromium version is so old that I cant use few websites - like Whatsapp. What should I do to update this?

**Comment by toofar** [comment] 2019-06-22 09:04
The chromium version in the webengine in 5.9 is old and whatsapp decided it isn't good enough. You can upgrade your Qt or change your user agent to look like a newer chrome or install from [tox](https://qutebrowser.org/doc/install.html#tox).

**Comment by XaheenA** [comment] 2019-06-22 09:56
Thanks. How can I _change my user agent to look like a newer chrome or Upgrade QT_?

**Comment by jgkamat** [comment] 2019-06-22 14:42
Xaheen writes:

> Thanks. How can I change my user agent to look like a newer chrome or 
> Upgrade QT?

To change your user agent you can use the content.headers.user_agent setting.

Does it say 'WhatsApp works with Google Chrome 36+'? That's due to a UA 
parsing bug, and not a 'too old' version.

See http://www.github.com/qutebrowser/qutebrowser/issues/4445

**Comment by The-Compiler** [comment] 2019-06-23 10:07
Yeah, I see the same (wrong) warning with Qt 5.12, so this is probably a duplicate of #4445.

You should be able to work around it by getting your user agent (e.g. via http://httpbin.org/user-agent), removing the `QtWebEngine/...` part, and doing `:set -u web.whatsapp.com content.headers.user_agent ...` with the new user-agent.

**Closed by The-Compiler** 2019-06-23 10:07 UTC

**Comment by The-Compiler** [comment] 2019-12-20 16:25
I now pushed a fix for known-broken sites (WhatsApp, Google login, etc.) to the `user-agent` branch. If you're affected by one of those, could you please try that branch without any custom user agent set? Thanks!
