### ISSUE TITLE
Prebuilt binary for windows fail virus check on virustotal

### ISSUE THREAD

**Issue by MerlinsGreatBeard** [qutebrowser/qutebrowser#6664] opened 2021-09-01 10:59 UTC
Ran qutebrowser.exe from [windows-64-bit-standalone](https://github.com/qutebrowser/qutebrowser/releases/download/v2.3.1/qutebrowser-2.3.1-windows-standalone-amd64.zip) on virustotal.com and got the result that "15 security vendors flagged this file as malicious".
See Result: [1f909ab19539089cc631cda5caf5175bdffed6ebff0c6a2d21910bb8d329114c](https://www.virustotal.com/gui/file/1f909ab19539089cc631cda5caf5175bdffed6ebff0c6a2d21910bb8d329114c/detection)

On my local machine, Windows Defender Antivirus quarantines qutebrowser.exe as it detects it as Trojan:Win32/Zpevdo.B

Is this a known problem?

**Comment by The-Compiler** [comment] 2021-09-01 11:38
It's a recurring problem that virus scanners detect PyInstaller-built executables as false-positive, also see #4269, #5823 and #6081. We did something in #6194 which helped to some degree, but apparently didn't eliminate the problem entirely.

I tried to [report it to Microsoft](https://www.microsoft.com/en-us/wdsi/filesubmission) again, but it fails with "File upload failed - please try again.". Not really much I can do at that point.

**Comment by MerlinsGreatBeard** [comment] 2021-09-01 12:03
Thank you for the fast response! I now feel safe adding it to allowed exceptions on Windows Defender.

**Comment by The-Compiler** [comment] 2021-09-01 20:53
I managed to submit this to Microsoft now - note to self, that's submission 42377ba7-b1ca-4cd5-a7f8-3e2e8feba767.

Two other people already reported this via other channels, I'll post here once I have an update from Microsoft. Note that many other projects are affected too, from what it seems like: https://github.com/search?q=Zpevdo.B&type=issues

**Comment by bitraid** [comment] 2021-09-02 09:55
For avoiding the constant flagging, I wonder if it's wise to not use the prebuilt pyinstaller bootloader. I did a test for x64, by building (and using) the bootloader of v4.3 using clang from llvm-mingw, the binary of which ([runw.exe.gz](https://github.com/qutebrowser/qutebrowser/files/7097902/runw.exe.gz)) is very different from the msvc one, and also doesn't have the limitations of mingw-w64 that the [docs describe](https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html#building-for-windows), because it's linked against ucrt instead of msvcrt.
The produced `qutebrowser.exe` v2.3.1 (python 3.9.6) passes all VirusTotal engines: [link](https://www.virustotal.com/gui/file/bc2c2ca4cb322e827b67aa192b6ce777756f890dc001e1b958d702f0a75d20bf/detection)

**Comment by The-Compiler** [comment] 2021-09-02 10:01
Yeah, I've been thinking about this as well. I'd really rather not have to set up a C building toolchain on my qutebrowser VM, but I suppose I should probably do so.

**Comment by The-Compiler** [comment] 2021-09-06 19:41
I got this:

> **Analyst comments:**
> 
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> 
> Thank you for contacting Microsoft.

Can someone confirm?

**Comment by bitraid** [comment] 2021-09-07 07:16
I can confirm. Also, the VirusTotal false positives are down to 4.

**Comment by The-Compiler** [comment] 2021-09-07 07:57
Huh, do those just get their definitions from Microsoft or what, or are they based on the moon phase or something? Either way, indeed we're down to:

- Antiy-AVL: Trojan/Generic.ASMalwS.329A072
- TrendMicro-HouseCall: TROJ_GEN.R002H09HF21
- Webroot: W32.Malware.Gen
- Zillya: Trojan.Badur.Win32.34336

Which I don't think are antivirus products qutebrowser users would typically use. Thus, I'm closing this. I opened #6674 for the idea about a custom PyInstaller bootloader build.

**Closed by The-Compiler** 2021-09-07 07:57 UTC
Labels: os: Windows, priority: 0 - high
