### ISSUE TITLE
Scrollbar visibility depends on javascript being enabled

### ISSUE THREAD

**Issue by sudo-nice** [qutebrowser/qutebrowser#5250] opened 2020-02-21 11:32 UTC
**Version info (see `:version`)**:

<details>
  <summary>Details</summary>

  qutebrowser v1.10.1
  Git commit: 
  Backend: QtWebEngine (Chromium 69.0.3497.128)
  Qt: 5.12.5

  CPython: 3.7.3
  PyQt: 5.14.1

  sip: 4.19.21
  colorama: 0.3.7
  pypeg2: 2.15
  jinja2: 2.10
  pygments: 2.3.1
  yaml: 3.13
  cssutils: no
  attr: 18.2.0
  PyQt5.QtWebEngineWidgets: yes
  PyQt5.QtWebEngine: 5.14.0
  PyQt5.QtWebKitWidgets: no
  pdf.js: no
  sqlite: 3.27.2
  QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019

  Style: QFusionStyle
  Platform: Linux-4.19.0-8-amd64-x86_64-with-debian-10.3, 64bit
  Linux distribution: Debian GNU/Linux 10 (buster) (debian)
  Frozen: False
  Imported from /usr/lib/python3/dist-packages/qutebrowser
  Using Python from /usr/bin/python3
  Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5
</details>

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**How to reproduce**

1. Disable scrollbar in the config: `c.scrolling.bar = 'never'`
2. Visit https://ruby-doc.org/core-2.7.0/ (happens for some other sites too)
3. Toggle javascript with <kbd>tsh</kbd>

Expected: the scrollbars never show up.
Actual: the scrollbars are visible when javascript is turned off.

![off](https://i.imgur.com/Rkk83Rf.png)
![on](https://i.imgur.com/QVGaBNu.png)

**Comment by The-Compiler** [comment] 2020-02-21 11:54
Duplicate of #4937

**Closed by The-Compiler** 2020-02-21 11:54 UTC
