### ISSUE TITLE
Using capitals while typing 'f' hints could behave as 'F'

### ISSUE THREAD

**Issue by Tattomoosa** [qutebrowser/qutebrowser#3486] opened 2018-01-13 18:22 UTC
cVim on Chrome allows you to follow 'f' hinting with capital letters to open in a new tab - as if you started the command with 'F'. For example, if the hint is 'jlj', then typing 'fJLJ' would have the same effect as typing 'Fjlj'. In cVim's implementation, 'fjlJ' would also function as 'Fjlj', which I think is ideal.

I find this useful since sometimes I decide at the last second I want to keep my current page and this is a bit more fluid than escaping out and pressing F. It is a major reason why I stick with cVim instead of Vimium or others when I am using Chrome.

This is a very minor thing but does not seem to interfere with qutebrowser's hinting, which doesn't even respond to capital letters at the moment, so I was hoping this feature could be a possible addition to this excellent browser.

**Comment by The-Compiler** [comment] 2018-01-13 18:53
Duplicate of #577

**Closed by The-Compiler** 2018-01-13 18:53 UTC
Labels: component: hints, priority: 2 - low
