### ISSUE TITLE
Remove Cursor from Unselected Textbox

### ISSUE THREAD

**Issue by Fredo699** [qutebrowser/qutebrowser#5431] opened 2020-05-13 07:30 UTC
Sorry if this is covered in a pre-existing issue, but this is one of the only things that really bugs me about qutebrowser.

When you don't have any text boxes selected, there should not be any blinking cursors on screen. This implies to the user that they are currently in insert mode, and if they just start typing, who knows what behavior that will cause.

**Comment by Fredo699** [comment] 2020-05-13 07:31
I don't really know how you'd fix this... I've never contributed to this project before, but I'll take a look.

**Comment by The-Compiler** [comment] 2020-05-13 07:34
Duplicate of #2668

**Closed by The-Compiler** 2020-05-13 07:34 UTC

**Comment by Fredo699** [comment] 2020-05-13 08:38
oops

sorry, I tried to search for it. I was surprised that I was the only one who had this problem :man_shrugging:

**Comment by The-Compiler** [comment] 2020-05-13 08:40
No worries! Duplicates can happen with so many open issues :)
