### ISSUE TITLE
Scrolling laggy unless pressing gg

### ISSUE THREAD

**Issue by lunaticstraydog** [qutebrowser/qutebrowser#3811] opened 2018-04-03 19:53 UTC
Since this is pretty specific and I dont think it will be easily solvable (cant bring much informations since I dont get how it exactly work), I dont know if it will be usefull to anyone, so feel free to remove it.
Basically, I had noticed qutebrowser felt very laggy when pressing vim mouvement keys to do more than one scroll down, i.e long press. Except it wasnt systematic, and after some time browsing, it would seem to solve itself. Thing was, I recently noticed it was correlated with me pressing G or gg (top or bottom), after what it would behave perfecly for  the rest of the session.
As I said, this is pretty strange and I cant bring much, except some video evidence if interested.
http://paste.the-compiler.org/view/322093f3  for version information.
Hoping it will be usefull to someone(who knows?)

---

*edited by @The-Compiler to fix up the pastebin link*

**Comment by jgkamat** [comment] 2018-04-03 20:01
I see this too with the default scrolling on some computers. However, if I use `:scroll-px` or `:scroll-page` as my scrolling method, I don't see this. Can you try using the other scrolling methods? They have the added benefit of allowing you to control how much a page is scrolled per press.

**Comment by lunaticstraydog** [comment] 2018-04-04 17:26
Thanks for the advice, sadly it doesn't seem to make a difference

**Comment by jgkamat** [comment] 2018-04-04 17:42
Maybe this is a result of software rendering being enabled (I've heard it can be slower and laggy). 

Could you try installing qupzilla/falkon (https://qupzilla.com/), and see if holding down the `<Down>` key has the same behavior? (both qupzilla and qutebrowser use the webengine backend). By default, the scrolling method used just presses the down key, although the other scrolling methods I mentioned don't do this.

**Comment by The-Compiler** [comment] 2018-04-23 09:28
@lunaticstraydog Any update on this?

**Comment by lunaticstraydog** [comment] 2018-04-29 16:57
(I've had to get away from computer for quite some time, sorry)
I have tried to use qupzilla and use some other scrolling methods, and qupzilla works perfectly fine with no  such issues, and no other scrolling methods seem to make a difference as far as my problem is concerned.
Not that it makes qutebrowser unusable- I just have not to forget to press "gg" on startup (it really isn't hard, is it).
If noone else encountered this issue, then I think it is quite fine as is, plus I cant seem to give any valuable information whatsoever.
ps: maybe there would be a way to work around this by getting qutebrowser to automatically press "gg" on startup? I couldn't figure that out myself.

**Comment by lunaticstraydog** [comment] 2018-04-29 16:59
(closed by accident, although I may do it if no real progress can be made)

**Comment by The-Compiler** [comment] 2018-04-29 17:25
I haven't had time to look into this yet, so I'm fine with leaving it open for now. It certainly sounds strange enough to make me curious on what's going on...

**Comment by lunaticstraydog** [comment] 2018-04-29 17:27
Alright, thank you again for your help and good luck then

**Comment by The-Compiler** [comment] 2018-05-24 15:05
@shizy do you also see a difference after pressing `gg`? It sounds more that you just see the keypress delay with individual key presses bound to qutebrowser scroll commands.

**Comment by shizy** [comment] 2018-05-24 15:57
With the faster rate settings of (200 50), the difference after pressing 'gg' is very noticable and much improved.

**Comment by jgkamat** [comment] 2018-05-24 18:29
I use a faster rate `(250 30)` and can't reproduce this....

I'm surprised that `:scroll-px` or `:scroll-page` dosen't help as it should be very similar to `gg` (which uses `:scroll-to-perc`)

**Comment by shizy** [comment] 2018-07-11 21:34
Just an update.

It seems that with the recent change for qt.force_software_rendering from a boolean to a string value I have noticed that the scroll lag is completely gone when using 'qt-quick'. The lag is still present when using the other two values, and as before goes away when 'gg' is triggered.

I have tested this on two completely different machines with the same results.

Hope this helps!

**Comment by GoingFast** [comment] 2018-08-24 17:17
@shizy your fix works. thanks man. had the same problem with laggy scrolling however qt-quick to software rendering fixed it

**Comment by The-Compiler** [comment] 2020-06-24 09:32
@lunaticstraydog @shizy @rislah Do you still see this with up-to-date Qt/qutebrowser versions (and `qt.force_software_rendering` not set)?

**Comment by lunaticstraydog** [comment] 2020-06-24 15:20
@The-Compiler 
No, I have long since changed my config and completely forgot about this problem.
At the very least, it is but noticeable.
If nobody still has the issue, go ahead and close this.
I'll add that the point I removed qt.force_software_rendering and noticed no difference in lag was when I switched to wayland , so I've no idea if it still exist on X tbh.

**Comment by shizy** [comment] 2020-06-24 16:08
@The-Compiler Tested with all options under `qt.force_software_rendering`, and I no longer see the issue.

**Comment by The-Compiler** [comment] 2020-06-24 16:09
I'm assuming this was fixed in Qt at some point then!

**Closed by The-Compiler** 2020-06-24 16:09 UTC
Labels: status: needs triage
