### ISSUE TITLE
v1.2.0 recognizes Meta(Command) key as Control key on macOS 

### ISSUE THREAD

**Issue by ynakao** [qutebrowser/qutebrowser#3697] opened 2018-03-10 13:01 UTC
As title described, v1.2.0 qutebrowser takes Meta key as Control key on macOS. Until v1.1.1 like `<Ctrl-d>` and `<Ctrl-u>` worked fine to scroll half page down and up, but at v1.2.0 when I type `<Ctrl-d>` nothing happens. Instead, I have to enter `<Meta-d>` to scroll half page down.

Other commands which have Ctrl- prefix don't work either as far as I confirmed.

I took log by `$ /Applications/qutebrowser.app/Contents/MacOS/qutebrowser --temp-basedir` and `:report` command at both versions. I entered `<Crtl-d>` x5, `<Ctrl-u>` x5, `<Meta-d>` x5, `<Meta-u>` x5 respectively.

logs:  [v1.1.1](https://gist.github.com/ynakao/0ceace48b682b1a87cfb0ffe7205ddd4#file-qute_v1-1-1-log), [v1.2.0](https://gist.github.com/ynakao/0ceace48b682b1a87cfb0ffe7205ddd4#file-qute_v1-2-0-log)

**Comment by The-Compiler** [comment] 2018-03-10 14:22
Hmm, this is likely caused by Qt swapping Ctrl/Meta by default, and qutebrowser not accounting for that.

I wonder though, what would the expected behavior be?

- When using `Ctrl` in user-defined bindings, I agree that should be Ctrl and not Command.
- What about the default bindings? Should they really use Ctrl or would Command be more appropriate for macOS? Though we can't really have OS-specific defaults anyways...
- What about editor shortcuts, i.e. stuff like Ctrl-X/C/V? That should probably continue using Command, right?

**Comment by ynakao** [comment] 2018-03-10 15:27
That makes sense. However, people who expect qutebrowser behaves like vim might be confused by using command key because they are used to control key when scrolling or something.

Even in Mac, vim and gVim are handling command and control key separately, so I think features inspired by vim should use control key at least.

**Comment by The-Compiler** [comment] 2018-03-10 15:41
Can you try what happens after running `"debug-pyeval objreg.get('app').setAttribute(7, True)` please (7 is the `AA_MacDontSwapCtrlAndMeta` attribute)? Not sure if it can be set at runtime, but if so, I'd hope that goes back to Ctrl for qutebrowser bindings, but still uses Command for editing shortcuts.

**Comment by ynakao** [comment] 2018-03-10 15:59
Only `None` appeared in `qute://pyeval/` tab, and control key still doesn't work properly.

[logs](https://gist.github.com/ynakao/269fcd6eead53c28a1c41d05594ea9a1)

**Comment by Linuus** [comment] 2018-03-11 19:29
I have the same issue here. All <Ctrl>-bindings are now treated as Cmd-bindings.

**Comment by ynakao** [comment] 2018-03-12 01:02
Oh, maybe I misunderstood the key naming. In macOS, Alt(Option) key is called Meta key and Command key is Super key by convention.

I should have wrote 'Super(Command) key' and '`<Super-d>`' etc... in the issue title and the description instead of 'Mata key'. Should I fix that terms in comments above?

**Comment by The-Compiler** [comment] 2018-03-12 09:36
Hmm, I tried this in `config.py`:

```python
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QApplication
assert not QApplication.instance()
QApplication.setAttribute(Qt.AA_MacDontSwapCtrlAndMeta, True)
```

but for some reason that didn't change anything.

@ynakao Don't worry about it - Qt calls Command `MetaModifier` and Alt `AltModifier`, so that was clear to me.

**Comment by Linuus** [comment] 2018-03-12 10:55
I guess this is relevant

https://codereview.qt-project.org/#/c/195412/

I also guess you’ve already seen it :)

**Comment by The-Compiler** [comment] 2018-03-12 18:49
@Linuus Thanks for the link! I wasn't aware of that. I mostly only follow QtWebEngine stuff, qtbase is way too active. The related issue is [QTBUG-51293](https://bugreports.qt.io/browse/QTBUG-51293), so it looks like this has been broken since Qt 5.5 and fixed in 5.11.

**Comment by Linuus** [comment] 2018-03-12 18:54
@The-Compiler Glad I could help :)

Yes and 5.11 is only in beta, right?

**Comment by The-Compiler** [comment] 2018-03-12 19:02
Indeed, the Qt 5.11 final is [coming end of May](https://wiki.qt.io/Qt_5.11_Release), so until PyQt and then qutebrowser is updated it'd be June or July.

Waiting isn't really an option, but it should be quite easy to handle the swapping in qutebrowser's code like it did before. I'll take a look as soon as I'm in front of a Mac again, which is hopefully Wednesday.

**Comment by The-Compiler** [comment] 2018-03-13 09:46
If someone can test this before I get to it, here's a patch:

```diff
diff --git a/qutebrowser/keyinput/keyutils.py b/qutebrowser/keyinput/keyutils.py
index a56efeab8..048043a93 100644
--- a/qutebrowser/keyinput/keyutils.py
+++ b/qutebrowser/keyinput/keyutils.py
@@ -505,6 +505,15 @@ class KeySequence:
                 not ev.text().isupper()):
             modifiers = Qt.KeyboardModifiers()
 
+        # On macOS, swap Ctrl and Meta back
+        if utils.is_mac:
+            if modifiers & Qt.ControlModifier:
+                modifiers &= ~Qt.ControlModifier
+                modifiers |= Qt.MetaModifier
+            if modifiers & Qt.MetaModifier:
+                modifiers &= ~Qt.MetaModifier
+                modifiers |= Qt.ControlModifier
+
         keys = list(self._iter_keys())
         keys.append(key | int(modifiers))
 
```

**Comment by The-Compiler** [comment] 2018-03-14 08:36
That patch won't work properly, but I pushed what I think is a proper fix to the `mac-modifiers` branch now. Will hopefully get a chance to test it on a Mac later today.

**Closed** 2018-03-14 18:41 UTC
Labels: bug: behavior, component: keyinput, os: macOS, priority: 1 - middle
