### ISSUE TITLE
qutebrowser start to freeze after sometimes with intel i915 and modsetting drivers

### ISSUE THREAD

**Issue by dummys** [qutebrowser/qutebrowser#5163] opened 2019-12-25 09:16 UTC
**version**:

        qutebrowser v1.8.3
        Git commit:
        Backend: QtWebEngine (Chromium 77.0.3865.129)
         
        CPython: 3.8.0
        Qt: 5.14.0
        PyQt: 5.14.0
         
        sip: 5.0.1
        colorama: 0.4.3
        pypeg2: 2.15
        jinja2: 2.10.3
        pygments: 2.5.2
        yaml: 5.1.2
        cssutils: no
        attr: 19.3.0
        PyQt5.QtWebEngineWidgets: yes
        PyQt5.QtWebEngine: 5.14.0
        PyQt5.QtWebKitWidgets: yes
        pdf.js: no
        sqlite: 3.30.1
        QtNetwork SSL: OpenSSL 1.1.1d  10 Sep 2019
         
        Style: QFusionStyle
        Platform: Linux-5.4.6-arch1-1-x86_64-with-glibc2.2.5, 64bit
        Linux distribution: Arch Linux (arch)
        Frozen: False
        Imported from /usr/lib/python3.8/site-packages/qutebrowser
        Using Python from /usr/bin/python3
        Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
         
        Paths:
        cache: /home/dummys/.cache/qutebrowser
        config: /home/dummys/.config/qutebrowser
        data: /home/dummys/.local/share/qutebrowser
        runtime: /run/user/1000/qutebrowser
        system data: /usr/share/qutebrowser
         
        Autoconfig loaded: no
        Config.py: /home/dummys/.config/qutebrowser/config.py has been loaded
        Uptime: 0:00:11

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
After a while the qutebrowser start to freeze, the computer is only accessible through ssh. the issue is not happening with firefox, it seems to be qutebrowser/chromium issue only. version of kernel: 5.4.6-arch1-1 and my cpu is a `i7-6700HQ`. It looks like the same issue as #4641. I tried playing with lots of kernel options like: 
```
i915.force_probe=1
i915.enable_guc=2
i915.enable_fbc=1
i915.fastboot=1
i915.enable_dc=1
i915.enable_psr=0
```

Here is the dmesg log:
```
[ 9156.837247] i915 0000:00:02.0: GPU HANG: ecode 9:0:0x00000000, hang on rcs0
[ 9156.837248] [drm] GPU hangs can indicate a bug anywhere in the entire gfx stack, including userspace.
[ 9156.837249] [drm] Please file a _new_ bug report on bugs.freedesktop.org against DRI -> DRM/Intel
[ 9156.837249] [drm] drm/i915 developers can then reassign to the right component if it's not a kernel issue.
[ 9156.837250] [drm] The gpu crash dump is required to analyze gpu hangs, so please always attach it.
[ 9156.837251] [drm] GPU crash dump saved to /sys/class/drm/card0/error
[ 9156.838259] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9156.838259] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9438.856990] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9520.776367] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9594.802504] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9652.828731] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9704.668282] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9718.748237] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9726.854844] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9738.801416] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9754.801261] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9762.694520] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9800.667578] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9810.694236] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9820.720756] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9830.747418] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
[ 9846.747300] i915 0000:00:02.0: Resetting rcs0 for hang on rcs0
```

**Comment by k3rn31** [comment] 2019-12-26 09:30
The same started to happen to me in the last few days, I never experienced this before. I cannot tell when exactly this started to happen, but it could be a couple of weeks at most. I use ArchLinux and I update it frequently, so maybe some upgrade introduced this problem.
The only way to gain control of the PC is to shutdown it via the power button and starting it again. I didn't try ssh, but I suppose it works.

**Comment by The-Compiler** [comment] 2019-12-26 09:34
No issues here (yet?) - can you try whether the same happens with KDE Falkon or with Chromium as well?

**Comment by rien333** [comment] 2019-12-26 17:02
Yeah this is not qutebrowser related at all. You're most likely experiencing this: https://gitlab.freedesktop.org/drm/intel/issues/673#note_371824

Seems to happen a lot on chromium-based browsers.

**Comment by rien333** [comment] 2019-12-26 17:08
@k3rn31 

>  I didn't try ssh, but I suppose it works.

As it's basically only the GPU that freezes, ssh works. I can almost always recover by closing some GPU intensive apps (like qutebrowser) over ssh, and then doing a `systemctl suspend`.

**Comment by The-Compiler** [comment] 2019-12-26 21:04
Yup, doesn't look like qutebrowser could do anything here - closing this then!

**Closed by The-Compiler** 2019-12-26 21:04 UTC
Labels: status: needs triage

**Comment by dummys** [comment] 2019-12-27 11:31
it seems to be with chromium engine.

**Comment by rien333** [comment] 2019-12-27 11:58
@dummys Not really, although chromium somehow frequently triggers the crash. The problem is with the Linux kernel, you can except a fix in Linux 5.5 (or possibly a 5.4.X release).

**Comment by dummys** [comment] 2019-12-27 16:03
ok thanks for your information

**Comment by brianbuccola** [comment] 2020-01-08 22:04
This has been happening to me as well. One thing I noticed is that, every couple of minutes or so while the system is "frozen", my clock will update, indicating that freezing sort of goes in and out. One solution I've found is to hit `Ctrl-Alt-F2` to go to tty2. It may take a few minutes for the system to bring you there (go grab a coffee while you wait), but once there, you can sign in and kill qutebrowser (`pkill -KILL qutebrowser` or whatever), and then head back over to tty1 (`Alt-F1`). Annoying, but not as bad as force-restarting the computer.

**Comment by rien333** [comment] 2020-01-08 23:08
@brianbuccola Indeed, your system definitively does not completely freeze from this problem, it's just the GPU. For example, all the music I  stream will keep playing like normal. `ssh` and internet in general also still work. If you can, connecting to your machine by `ssh` (most phones can do this), and then executing `systemctl suspend`  is probably a lot faster than grabbing a coffee. From what I can remember,  if suspending recovers fasters than switching to tty2 (in ssh: `sudo chvt 2`), but that might vary on a case by case basis.

Also note that (arch) Linux 5.4.7 seemed to have brought some improvements to this problem. Some users have reported seeing the freeze less frequently, and the computer recovering by itself pretty quickly.

**Comment by dummys** [comment] 2020-01-09 08:44
no more freeze for me with latest arch kernel

**Comment by brianbuccola** [comment] 2020-01-09 13:10
@rien333: Thanks for these tips.

@dummys: I'm running Linux 5.4.8 (since upgrading from 5.4.7 on 3 days ago), and my system froze (just) once yesterday. Not as bad as the once-an-hour freezing from a couple weeks ago, but it still seems to happen.

**Comment by rien333** [comment] 2020-01-12 21:08
Finally, it seems like the relevant fix has been merged (in 5.4.11), although it might be just a patch from Arch Linux. Whatever may be, lets hope that 5.4.11 moves from testing soon (for minor releases, this mostly happens  in a day or so I think), and that this annoying bug is finally quelled.

**Comment by brianbuccola** [comment] 2020-01-16 16:21
I'm running Linux 5.4.11, and things seem to be a little better: fewer freezes, and less freeze time. It still does happen, but less often, and now the system only locks up for about 30 seconds, which is annoying but bearable.

**Comment by rien333** [comment] 2020-01-17 10:54
I went ahead and installed 5.5-rc6 because the crashes became quite annoying (although some minor release improved the situation, it seemed to fluctuate a bit between them).  As other reports have indicated, the bug seems to be gone.
