### ISSUE TITLE
Black windows after monitors resume from sleep

### ISSUE THREAD

**Issue by JustinLovinger** [qutebrowser/qutebrowser#5631] opened 2020-07-28 23:01 UTC
**Version info**:

```
qutebrowser v1.13.0
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)
Qt: 5.12.7
```

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
If I put my monitors to sleep with `swaymsg 'output * dpms off'`, wait for my monitors to enter power-saving mode, and resume with `swaymsg 'output * dpms on'`, existing Qutebrowser windows turn completely black. Terminal output shows many lines of `WARNING: QPaintDevice::metrics: Device has no metric information` and `WARNING: QQuickWidget: Cannot render due to failing makeCurrent()`.

**How to reproduce**

See Description.

**Comment by The-Compiler** [comment] 2020-07-29 05:44
Can you check whether you see the same issue with another QtWebEngine based browser such as KDE Falkon?

**Comment by JustinLovinger** [comment] 2020-07-29 19:24
> Can you check whether you see the same issue with another QtWebEngine based browser such as KDE Falkon?

I just tested Falkon, and it has the same behavior, same error messages even.

**Comment by The-Compiler** [comment] 2020-07-29 19:27
This isn't a qutebrowser issue then - can you try a newer Qt release such as 5.12.9 or ideally 5.15.0?

**Comment by JustinLovinger** [comment] 2020-07-30 01:41
> This isn't a qutebrowser issue then - can you try a newer Qt release such as 5.12.9 or ideally 5.15.0?

Trying a newer Qt won't be easy. I'm on NixOS and that was the latest Qutebrowser in Nixpkgs unstable branch. I'm pretty sure it was using the latest Nixpkgs Qt. Although, `:version` did show `PyQt5.QtWebEngine: 5.15.0`.

**Comment by The-Compiler** [comment] 2020-07-30 07:45
Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

FWIW a newer Qt version should be coming soon in NixOS:

- https://github.com/NixOS/nixpkgs/pull/84232
- https://github.com/petabyteboy/nixpkgs/pull/1

Maybe you can try those somehow? It works fine for me on Archlinux with Qt 5.15.0, and there is nothing qutebrowser can do about it FWIW.

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, if you can still reproduce this with newer Qt versions, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. If you end up reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2020-07-30 07:45 UTC
Labels: status: needs triage

**Comment by petabyteboy** [comment] 2020-07-30 16:16
It's still an issue for me with Qt 5.15.0 on NixOS. This is my version information:

```
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v1.13.1
Git commit:
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

CPython: 3.8.3
PyQt: 5.15.0

sip: 4.19.23
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.6.1
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.0
PyQt5.QtWebKitWidgets: no
pdf.js: 2.3.200 (/nix/store/fvdbc4d34dsc94n2rpfhld8x452ryb6y-pdfjs-2.3.200/build/pdf.js)
sqlite: 3.32.3
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: wayland
OpenGL: X.Org, 4.6 (Compatibility Profile) Mesa 20.1.3
Platform: Linux-5.8.0-rc6-x86_64-with-glibc2.2.5, 64bit
Linux distribution: NixOS 20.09 (Nightingale) (unknown)
Frozen: False
Imported from /nix/store/ac5cvzdrr2n9jbgn834psf79lgd5689n-qutebrowser-1.13.1/lib/python3.8/site-packages/qutebrowser
Using Python from /nix/store/8hf2rpqx8fnx6a3jm9pvn0d40c065zxl-python3-3.8.3/bin/python3.8
Qt library executable path: /nix/store/6sq8kb88ybf95y8b6kdc5kpzdpiyr0iz-qtbase-5.15.0/libexec, data path: /nix/store/6sq8kb88ybf95y8b6kdc5kpzdpiyr0iz-qtbase-5.15.0
OS Version:

--- /etc/os-release ---
NAME=NixOS
ID=nixos
VERSION="20.09.git.a8546a078dfM (Nightingale)"
VERSION_CODENAME=nightingale
VERSION_ID="20.09.git.a8546a078dfM"
PRETTY_NAME="NixOS 20.09 (Nightingale)"
LOGO="nix-snowflake"
DOCUMENTATION_URL="https://nixos.org/learn.html"

Paths:
cache: /home/pbb/.cache/qutebrowser
config: /home/pbb/.config/qutebrowser
data: /home/pbb/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /nix/store/ac5cvzdrr2n9jbgn834psf79lgd5689n-qutebrowser-1.13.1/share/qutebrowser

Autoconfig loaded: no
Config.py: /home/pbb/.config/qutebrowser/config.py has been loaded
Uptime: 0:00:00

```

**Comment by The-Compiler** [comment] 2020-07-30 16:21
I suggest you report this upstream to QtWebEngine then. Not much I can do about a bug which isn't qutebrowser specific and I can't reproduce myself, I'm afraid.

This might well be something NixOS specific (as I haven't heard of this issue before), but I have no idea what exactly. The only thing which seems weird is that your OpenGL vendor is listed as `X.org`, I get `Intel` there and would expect something like that.

**Comment by petabyteboy** [comment] 2020-07-30 16:23
> I suggest you report this upstream to QtWebEngine then. Not much I can do about a bug which isn't qutebrowser specific and I can't reproduce myself, I'm afraid.

That's fine, I'm searching the bug tracker for a similar issue now and if I can't find one I will report it. But this issue will still be useful for qutebrowsers to find this bug and share information on what works and what not, and to find the link to the upstream issue.

**Comment by petabyteboy** [comment] 2020-07-30 16:29
It looks like this was already reported to upstream [here](https://bugreports.qt.io/browse/QTBUG-84161?jql=text%20~%20%22Device%20has%20no%20metric%20information%22).

**Comment by The-Compiler** [comment] 2020-07-30 16:38
Ah, good catch! I'll add a comment there.
