### ISSUE TITLE
Fonts corrupted in pdf.js display, fontconfig error on startup

### ISSUE THREAD

**Issue by emulti** [qutebrowser/qutebrowser#7812] opened 2023-08-03 06:03 UTC
**Version info**:
qutebrowser v2.5.4
Git commit: 5344163f4 on main (2023-08-02 21:29:48 +1200)
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.11.3
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.10
pdf.js: 3.7.107 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.1.2 1 Aug 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.2 (Compatibility Profile) Mesa 23.1.4
Platform: Linux-6.1.39-1-lts-x86_64-with-glibc2.37, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6

Paths:
cache: /home/chris/.cache/qutebrowser
config: /home/chris/.config/qutebrowser
data: /home/chris/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/chris/.config/qutebrowser/config.py has been loaded
Uptime: 0:07:35

**Does the bug happen if you start with `--temp-basedir`?**:
the font corruption is still present- but the error "Fontconfig error: Cannot load default config file: No such file: (null)" isn't shown.

**Description**
If a pdf file is displayed using pdf.js viewer, the fonts are corrupted and mostly unreadable. 
When starting qutebrowser from command line, the following errors are shown: 
$ qutebrowser 
13:47:47 ERROR: Failed to load session default: PyQt6.QtCore.QUrl('') is not valid
Fontconfig error: Cannot load default config file: No such file: (null)

The previous session (saved with :wq) isn't restored. This seems to occur after pdfjs is used in the prior session.
The usual Fontconfig fonts.conf files are present on the system. 

**How to reproduce**

 :open https://dagrs.berkeley.edu/sites/default/files/2020-01/sample.pdf (with pdfjs enabled)

Same issue occurs with either pdfjs or pdfjs-legacy

**Comment by The-Compiler** [comment] 2023-08-03 06:43
Works fine here, the fontconfig error is likely unrelated. Can you show a screenshot, and double-check via `:version` that you're indeed running the Qt version from above?

**Comment by emulti** [comment] 2023-08-03 08:34
![Screenshot from 2023-08-03 16-23-14](https://github.com/qutebrowser/qutebrowser/assets/7505390/5f55de6c-07a4-468f-9d53-7202ca04618b)

The version text in the issue above is directly from :version.
This is qutebrowser-git from AUR, which I found necessary to make keepassxc integration work. This was suggested on Arch Wiki, but now I'm not so sure the packages version is non-functional for Keepassxc, it might have been my Keepass configuration, where I had to enable 'Chrome' browser integration.

fonts.default_family is set to "Bitstream Vera Sans"

fonts.web.family.sans_serif to "Bitstream Vera Sans"

fonts.web.family.serif to "Bitstream Vera Serif"

fonts.web.family.standard to "Bitstream Vera Serif"

Session restore doesn't work after using pdf.js once, unless I delete the _autosave.yml and default.yml files.

**Comment by The-Compiler** [comment] 2023-08-03 09:20
Does it happen with just that file, or with any PDF file? If it's the latter, does it reproduce when you go to https://mozilla.github.io/pdf.js/web/viewer.html as well? If so, what happens when you [download `testbrowser_webengine.py`](https://github.com/qutebrowser/qutebrowser/blob/main/scripts/testbrowser/testbrowser_webengine.py) and then run `python testbrowser_webengine.py https://mozilla.github.io/pdf.js/web/viewer.html`?

**Comment by emulti** [comment] 2023-08-03 11:10
Both tests show corrupted fonts.
For example testbrowser_webengine.py:
![Screenshot from 2023-08-03 19-08-30](https://github.com/qutebrowser/qutebrowser/assets/7505390/fc3b1c16-3661-4247-93e7-7cf9d5bcbe12)

I am wondering if that fontconfig error message originates from pdfjs

**Comment by emulti** [comment] 2023-08-03 11:41
I tried with the 'qutebrowser' package rather than the qutebrowser.git
qutebrowser v2.5.4
Git commit: 
Backend: QtWebEngine 5.15.14, based on Chromium 87.0.4280.144
Qt: 5.15.10 (compiled 5.15.8)

CPython: 3.11.3
PyQt: 5.15.9

sip: 6.7.10
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0.1
adblock: 0.6.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.6
PyQt5.QtWebKitWidgets: no
pdf.js: 3.7.107 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.1.2 1 Aug 2023

Style: Qt5CTProxyStyle
Platform plugin: xcb
OpenGL: Intel, 4.2 (Compatibility Profile) Mesa 23.1.4
Platform: Linux-6.1.39-2-lts-x86_64-with-glibc2.37, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/chris/.cache/qutebrowser
config: /home/chris/.config/qutebrowser
data: /home/chris/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: /home/chris/.config/qutebrowser/config.py has been loaded
Uptime: 0:03:02

KeepassXC integration works- Archwiki needs an update.

But no PDF file is rendered if the 'pdfjs' package is installed. With 'pdfjs-legacy', very strange corruption is produced: 
![Screenshot from 2023-08-03 19-37-06](https://github.com/qutebrowser/qutebrowser/assets/7505390/84cbaef8-2920-4acd-a802-6201900591c9)

**Comment by The-Compiler** [comment] 2023-08-03 11:53
For the other issues you described, see:

- #7774
- #7696

As for this one, given that it happens with the testbrowser too, I'm closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can easily reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2023-08-03 11:53 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by emulti** [comment] 2023-08-03 12:26
Actually it does seem to be a duplicate of [https://github.com/qutebrowser/qutebrowser/issues/7774](https://github.com/qutebrowser/qutebrowser/issues/7774)

Launching qutebrowser with -qt-flag disable-accelerated-2d-canvas fixes the issue, at the cost of visibly slower initial page rendering to screen.

Since display corruption seems to be a known issue with older Intel graphics cards (like mine) using SNA acceleration (Chromium blacklisting them for Hardware Acceleration for this reason) I am not convinced it's actually a qtwebengine issue.

However, since I like the snappiness of the HA, I will just manage without the in-browser PDF rendering, because lack of feature bloat is the main reason I am using qutebrowser in the first place.

Thanks for providing a great, fast and simple keyboard-driven browser!
