### ISSUE TITLE
On referencesource.microsoft.com the input field loses focus while typing

### ISSUE THREAD

**Issue by m42a** [qutebrowser/qutebrowser#4223] opened 2018-09-17 00:59 UTC
## Steps to reproduce:
1. Go to https://referencesource.microsoft.com/
2. Start typing in the search box in the top left

## Expected results
Qutebrowser stays in insert mode

## Actual results
Qutebrowser leaves insert mode when updating the search results

This appears to be caused by a call to `top.history.replaceState`.  Qutebrowser interprets that as a page load, and so leaves insert mode.  This can be reproduced on any site with a text box; go into insert mode and then run `top.history.replaceState(null, top.document.title, "#")` in the inspector.

This works fine in passthrough mode.

## Version info

qutebrowser v1.4.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.0
Qt: 5.11.1
PyQt: 5.11.2

sip: 4.19.12
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.13
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.17.14-arch1-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Comment by jgkamat** [comment] 2018-09-17 01:30
I think this is a duplicate of https://github.com/qutebrowser/qutebrowser/issues/3596. Please vote for https://bugreports.qt.io/browse/QTBUG-65223

**Closed by jgkamat** 2018-09-17 01:30 UTC
