### ISSUE TITLE
Qutebrowser search is triggering accessibility features on websites?

### ISSUE THREAD

**Issue by andys8** [qutebrowser/qutebrowser#5608] opened 2020-07-20 23:24 UTC
**Version info**:
qutebrowser v1.13.1
Git commit: da585f2b5 on master (2020-07-18 11:39:00 +0200)
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.0

**Description**

I noticed that text searches with qutebrowser seem to trigger accessibility settings on some websites. A similar behavior can be noticed when hitting `TAB`.

**How to reproduce**

1. https://google.com or https://github.com
2. Hit `/a<ENTER>`
3. In the top right corner there is the text (jump to main content / skip to content)

![image](https://user-images.githubusercontent.com/13085980/87995977-41e9ec80-caf1-11ea-8d8b-76ee2e0c9b44.png)

**Comment by The-Compiler** [comment] 2020-07-21 04:21
Do you have a hidden statusbar?

**Comment by andys8** [comment] 2020-07-21 09:31
That's a good hint. The setting is:
```
c.statusbar.show = 'in-mode'
```

The issue is not occuring, when this setting is removed / the statusbar is visible all the time.

**Comment by The-Compiler** [comment] 2020-07-21 09:32
This is a duplicate of #2236 then.

**Closed by The-Compiler** 2020-07-21 09:32 UTC
Labels: status: needs triage
