### ISSUE TITLE
Insert mode is being left when URL's #anchor is being changed by a page whilst you type

### ISSUE THREAD

**Issue by moorchegue** [qutebrowser/qutebrowser#4321] opened 2018-10-10 06:11 UTC
**Version info (see `:version`)**: 1.5.0-1 (basically any version for the last couple of years)

**Description**

When a page sends AJAX requests in background and changes the URL, qutebrowser exits insert mode. Which is incredibly annoying, especially when trying to change some wording in the search query, as there's usually a timeout in JS code to prevent frequent meaningless queries.

**How to reproduce**
Not very many search engines (and similar services) use this technique, but a few do. Good example is Google Translate: https://translate.google.com/#auto/en/

**Comment by The-Compiler** [comment] 2018-10-10 06:12
Duplicate of #3596

**Closed by The-Compiler** 2018-10-10 06:12 UTC
