### ISSUE TITLE
Fullscreen doesn't work properly for qutebrowser in SwayWM

### ISSUE THREAD

**Issue by jso8910** [qutebrowser/qutebrowser#6595] opened 2021-07-13 14:31 UTC
**Version info**:

https://paste.the-compiler.org/view/0abac970
**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**

qutebrowser's current implementation of going fullscreen doesn't work well on SwayWM as the window loses its place upon leaving fullscreen. It leaves a tabbed layout, for example. This does not occur with other browsers such as Chromium.

**How to reproduce**

All steps on SwayWM. It is most apparent if you use a tabbed layout
- Enter full screen with F11 (which isn't a Sway keybinding so I presume it is something that qutebrowser implements) or by entering fullscreen on a video. 
- Leave fullscreen. You will see that it left the tabbed layout.

[Video](https://imgur.com/OZPdNye)

**Comment by The-Compiler** [comment] 2021-07-13 15:11
Can you try with another browser based on QtWebEngine, such as KDE Falkon?

**Comment by jso8910** [comment] 2021-07-13 15:13
Yep it happens with Falkon as well. So it is probably an upstream issue.

**Comment by kisik21** [comment] 2021-07-18 13:29
Doesn't happen for me on Sway 1.6 and qutebrowser v2.3.0.

**Comment by jso8910** [comment] 2021-07-18 13:40
Maybe it is some issue with my Sway config? I don't know what could
be wrong with it though because tabbed view is tabbed view

**Comment by The-Compiler** [comment] 2021-07-19 11:17
I'm afraid I can't reproduce this either. Closing this as it doesn't seem to be a qutebrowser issue. No idea where the culprit is though, I don't use Wayland myself.

**Closed by The-Compiler** 2021-07-19 11:17 UTC
Labels: status: needs triage

**Comment by greenfoo** [comment] 2021-11-28 21:37
Just reporting that this also happens to me using...
```
qutebrowser v2.4.0
Backend: QtWebEngine 5.15.7, based on Chromium 87.0.4280.144
Qt: 5.15.2
Sway: 1.6.1
```

**Comment by greenfoo** [comment] 2021-12-04 20:12
This is an example of the actual behavior (just for reference, as this is probably, as already stated, not a qutebrowser issue).
On the gif below you will see this:

1. First I create a tabbed layout and switch between the two tabs (qutebrowser in one and a terminal in the other).
2. Then, while in the qutebrowser tab, I enter and exit full screen using sway key shortcuts. It works as expected and when I return from fullscreen the tabbed layout is still there.
3. Finally, I used the you tube "full screen" button to enter and exit full screen mode. This time, when I return from full screen, the tabbed layout has dissapeared and, instead, I have two different windows (one with qutebrowser and the other one with the terminal).

![demo](https://user-images.githubusercontent.com/42691086/144723177-26889245-6e78-4e4a-8b84-d9d3718da210.gif)

**Comment by greenfoo** [comment] 2021-12-04 20:58
Final update: it looks like this issue **has already been fixed** in [this sway PR](https://github.com/swaywm/sway/pull/6207).

Unfortunately, as of today, the latest sway release (1.6.1) was branched from a previous commit and thus people experiencing this issue will either have to build sway from master or wait for the next release.

**Comment by crocket** [comment] 2022-02-01 02:52
Installing sway-1.7 fixed the issue.
