### ISSUE TITLE
Configurable placeholders for audio status for tabs

### ISSUE THREAD

**Issue by LamprosPitsillos** [qutebrowser/qutebrowser#8210] opened 2024-05-27 07:29 UTC
```python
# tabwidget.py
    # Strings for controlling the mute/audible text
    MUTE_STRING = '[M] '
    AUDIBLE_STRING = '[A] '
```

Simple feature request , i am willing to contribute , i was just wandering what is the best way to do this according to the projects managment.

I noticed that config options are added in `configdata.yml` , but adding a config option `tabs.title.format.audio:` doesnt seem right.

Maybe have a `tabs.title.placeholders` dictionary ?

Any guidance is appreciated

**Comment by The-Compiler** [comment] 2024-05-27 09:22
Duplicate of #5689 - I'd rather not have a separate setting, and have #1578 as a proper solution to make tab texts configurable.

**Closed by The-Compiler** 2024-05-27 09:22 UTC
