### ISSUE TITLE
windows on seperate workspaces playing videos drastically reduces performance

### ISSUE THREAD

**Issue by AlexBocken** [qutebrowser/qutebrowser#6551] opened 2021-06-16 09:27 UTC
**Version info**:
This issue does not seem version specific to me. I have experienced this issue for quite a while now, it just took me ages to realize what exactly causes it.

qutebrowser v2.2.3
Git commit: fc5aae8a7 on master (2021-06-15 23:03:17 +0200)
Backend: QtWebEngine 5.15.4, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.9.5
PyQt: 5.15.4

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.1
pygments: 2.9.0
yaml: 5.4.1
adblock: 0.4.4
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.4
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.35.5
QtNetwork SSL: OpenSSL 1.1.1k  25 Mar 2021

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 21.1.2
Platform: Linux-5.12.10-arch1-1-x86_64-with-glibc2.33, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.9/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:
Yes.

**Description**
If `tabs.tabs_are_windows` is set to `true`, another tab is opened, and this tab is moved to another workspace/tag (I'm using dwm) the performance of both tabs is decreased drastically. The picture refreshes around 1/sec. Sound seems to be unaffected by it.

**How to reproduce**
1. `:set tabs.tabs_are_windows true`
2.  open any website, for best effect I reccomend something like youtube.
3.  start two videos in seperate tabs
4. move one tab to another workspace.
5. Both videos should play sound without issue, but the picture only refreshes around 1/sec

**Possibel Solution?**:
It seems to me like `tabs_are_windows` does not literally treat tabs like windows. Maybe recoding this setting to always start a new window instead of a tab could fix this issue?

**Comment by AlexBocken** [comment] 2021-06-16 09:33
https://github.com/qutebrowser/qutebrowser/issues/4692
https://github.com/qutebrowser/qutebrowser/issues/5482
seem to have similar issues. Both of them are also related to Wayland as of my knowledge which I am not using.
https://bugreports.qt.io/browse/QTBUG-69077
This bug thus should not be applicable.

**Comment by The-Compiler** [comment] 2021-06-16 10:01
> It seems to me like `tabs_are_windows` does not literally treat tabs like windows. Maybe recoding this setting to always start a new window instead of a tab could fix this issue?

Can you elaborate? That's exactly what it does. I'm assuming the bug is unrelated to the setting, and if you open a new window via `:open -w` you'll see the same issue too?

**Comment by AlexBocken** [comment] 2021-06-16 10:59
Ah, you are right. This does also happen with `:open -w`. Apologies. I
could've sworn it was only with `-t`.
Is this more precise issue already known to you?

**Comment by The-Compiler** [comment] 2021-06-16 11:05
No - I've never heard of it happening outside of Wayland. Could you check if it happens with another QtWebEngine-based browser such as [KDE Falkon](https://www.falkon.org/) as well?

**Comment by AlexBocken** [comment] 2021-06-16 11:14
Weird...
I've checked Falkon and the issue persists. I guess this means you're
in the clear? hahaha

**Comment by The-Compiler** [comment] 2021-06-16 11:32
Indeed, I'm afraid there's nothing qutebrowser can do about it then. Closing this as an upstream issue in [QtWebEngine](https://wiki.qt.io/QtWebEngine).

I try to report bugs upstream when I can reproduce them, but unfortunately this wasn't the case here. Since I'll be unable to provide any follow-up information when being asked, could you please report the bug to the [Qt Bugtracker](https://bugreports.qt.io/secure/Dashboard.jspa) yourself? Please use "Project: Qt (QTBUG)"  and "Component: WebEngine" there. After reporting the bug, it'd be good if you could post the link to it here!

**Closed by The-Compiler** 2021-06-16 11:32 UTC
Labels: status: can't reproduce, status: needs triage

**Comment by AlexBocken** [comment] 2021-06-16 12:01
Alright, I reported it. Thanks for your help.
https://bugreports.qt.io/browse/QTBUG-94547
