### ISSUE TITLE
WhatsApp Web no longer works after site update

### ISSUE THREAD

**Issue by phrxmd** [qutebrowser/qutebrowser#6812] opened 2021-11-07 14:31 UTC
**Version info**:
qutebrowser v2.4.0
Backend: QtWebEngine 5.15.6, based on Chromium 87.0.4280.144
Qt: 5.15.2

CPython: 3.8.12
PyQt: 5.15.6

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.2
pygments: 2.9.0
yaml: 5.4.1
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.5
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.36.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
After WhatsApp pushed an update to their web app that supposedly enables being online simultaneously with several devices (without having to be online with your phone), the WhatsApp web app at https://web.whatsapp.com no longer works with Qutebrowser. You can log in, but you are immediately logged out again.

Reloading with Shift+R does not make a difference.

**How to reproduce**
- Enable the "multi-device beta" in your WhatsApp settings
- Open https://web.whatsapp.com, a QR code appears
- In the WhatsApp app on your phone, go to Settings, Linked devices, tap "Add Device" and scan the QR code
- You see a progress bar that says "Organizing messages", then the WhatsApp Web app may appear briefly, then you see a message "Logging out" and the QR code appears again

**Comment by The-Compiler** [comment] 2021-11-08 08:55
I don't have a WhatsApp account, so I won't be able to debug this I'm afraid. A couple of questions:

- I assume it works fine with Chromium?
- How do things look with another browser based on QtWebEngine, such as KDE Falkon?
- Anything interesting in the `:devtools` console?
- Any chance you could test the `qt6-test` branch? It's in a barely working state, but hopefully usable enough to try to reproduce this.

**Comment by phrxmd** [comment] 2021-11-08 10:00
It seems to work how, WhatsApp might to have pushed some server-side change to the interface. I will post here again if it breaks again. For the sake of documentation:
- It works fine with Chromium and Brave as well; it was working with Brave even when it wasn't working with Qutebrowser.
- With Falkon I get an error message that WhatsApp Web needs at least Chrome 60+ (Falkon seems to have been moribund for a while now, so it may be due to other issues with Falkon that are going unfixed)  
- How would I test the `qt6-test` branch?

**Comment by The-Compiler** [comment] 2021-11-08 10:19
Closing this for now then, but feel free to comment if it comes back and I will reopen.

As for testing the branch, you would:

- Clone the git repo, e.g. via `git clone https://github.com/qutebrowser/qutebrowser.git`
- `cd qutebrowser`
- Check out the branch using `git checkout qt6-test`
- Run `qutebrowser --temp-basedir` and verify via `:version` that you're indeed on Qt 6

**Closed by The-Compiler** 2021-11-08 10:19 UTC
Labels: status: needs triage

**Comment by smartlitchi** [comment] 2022-03-06 08:22
Now that Whatsapp pushed the update to everyone, it seems that the issue is hitting me as well. I can't connect at all though, it's stuck at the "Scan the QR code". I don't know if I should open a new issue though
![image](https://user-images.githubusercontent.com/56811153/156915111-83a29901-249e-4e8c-ac8a-3f659251a339.png)
